owncloud/web

Makefile
apps/files/Makefile

Don't repeat unneeded operations.
Only fetch deps when needed, not for every `make run`.
Please test if this works on your side as well.
`make clean` then `make run` fetches deps.
Next time `make run` directly starts the server, no npm.

Improve makefiles

---

config.json.sample

Currently if one copies the sample file, it's missing the files app and
the demo and servstat apps do not compile.
Better fix the sample config to contain at least the files app then.

The sample file must be usable directly

---

src/default.js

Move the registration of the drag and drop components so that it is ensured that this is done before the app is initialized.

Move drag-drop init before attempt to load config and init app

---

src/default.js

This patch replaces the use of lodash forEach with the ES2015 standard construct of for...of. This should not cause compatibility problems as babel will take care of this if necessary.

Replace the use of lodash forEach with ES2015 for...of

---

apps/demo/src/ButtonRowItem.vue
apps/demo/src/DemoShowConfig.vue
apps/demo/src/app.js
apps/files/src/components/File-Details-Buttonrow.vue
apps/files/src/components/File-Details.vue
apps/files/src/components/Tile.vue
apps/servstat/src/Indicator.vue
apps/servstat/src/app.js
src/default.js
src/store.js

Semicolons are unnecessary in Javascript in most cases. Some propose to get rid of them (e.g. the so called "Standard" JS recommendation) while others disagree and point out that using semicolons all the time brings more consistency as there are also edge cases where they are still necessary.
While I actually prefer the semicolon-less style in my own code, the matter of fact is that in this project semicolons are used throughout. This change adds the semicolons where they were forgotten in order to have a consistent style of coding.

Style consistency: Add missing semicolons

---

Makefile.release

The markdown editor shall be release as well ...
Because being the first app which which integrates into the open file action selector we better release it
- call make release

Add markdown-editor to dist

---

appinfo/info.xml

Because core platform is switching to Semver

Set max version to 10 for Semver

---

.htaccess
Makefile.release

Phoenix assets are usually cached for a long time in browsers - this causes issues when deploying new versions.
The htaccess file holds a config to basically disable caching for some file types.

Add htaccess to define caching in browsers

---

apps/files/src/FileUpload.js
apps/files/src/components/FilesApp.vue

1. Error handling on upload was not properly implemented
2. Successful upload into a subfolder was buggy as well
1. try to upload into a readonly folder or upload where the user has no quota - error notification shall pop up
2. try uploading into a subfolder. progess bar shall disappear and file shall be visible

[files] Fix error handling on upload and success handling in sub folder

---

README.md
tests/acceptance/stepDefinitions/loginContext.js

respect custom env vars for oc credentials, which enhances local & drone acceptance testing.
the default credentials for testing against new containers remains untouched.
improved security for testing. my dev cloud has no `admin` user & i need to use a preinstalled oc instance for maximal testing performance.
- `yarn acceptance-tests`
- `export OC_USER=username && export OC_PASS=entropie && yarn acceptance-tests`

allow custom credentials in acceptance-tests

---

apps/files/package.json
apps/files/yarn.lock
apps/markdown-editor/package.json
apps/markdown-editor/yarn.lock
package.json
yarn.lock

bump webpack in core & core apps
- refs #486 
- refs #487
- refs #488
rebase 3 dependabot pr's into one & test webpack build locally
didn't I mention this right before ?

bump webpack as core dependency

---

apps/files/src/components/FileInfoSidebar.vue

This PR fixes FileInfoSideBar.vue always showing 0 bytes.
Manually
Before the fix:
After the fix:

Fix totalSize showing 0 bytes on FileInfoSidebar

---

apps/files/src/components/FilesApp.vue
apps/files/webpack.common.js
src/components/form/SearchBar.vue
webpack-phoenix-integration.js

The second commit is the offline-search functionality for open folder.
To be able to reuse the SearchBar, i've designed some webpack alias magic to use inside app's build systems, visible in the first commit of this PR.
- refs #172 
- close #517
We need some way Interface in Phoenix which apps can use to import Models, Services, Mixins, etc...
One possible solution is to outsource them & publish them on npm, so we could import them in phoenix same as in apps. This may be an idea if our pattern library is available & grown, but we need some way to use them right now. To avoid proliferation of incorrect settings, i've created a little helper script located in phoenix root directory. Apps can wrap their webpack config up & it get's enriched with some nice path aliases.
I could adopt some …

Filter search term in open folder

---

apps/markdown-editor/src/MarkdownEditor.vue
l10n/Makefile

- Sync translations for markdown-editor and pdf-viewer
- Translation string in markdown-editor
- refs #584 
- run make l10n-read
- see template.pot in the apps l10n folders

Add translations to markdown-editor and pdf-viewer

---

apps/files/src/components/FileDetails.vue
apps/files/src/components/FileInfoSidebar.vue
apps/files/src/components/FilesApp.vue
src/Phoenix.vue
src/components/OcAppContent.vue
src/components/OcAppNavBar.vue
src/components/OcAppSideBar.vue

This Commit will Introduce OcAppSidebar component with a reference implementation in files-app.
As befor OcAppSidebar can be used as base component and can be extended by slots.
All slots are inspirated by current Sidebar appearance and are open for discussion!
* Position: Right-hand side of app content
* Width: 20vw
* Slots:
* icon - left upper icon
* title - title
* action - right upper action slot, can be disabled
* headerContent - row below actual header
* content - the full content area
* footer - footer area not used now
* Position: centered 
* Width: All available space
* Slots: Content - is there more we need?
* Position: Left-hand side of app content
* Width: same as sidebar
* Slots: Content - more tbd
- Refs #433 
Most of the existing UI is based on vuetify which make us depend …

Introduce OcAppSidebar, OcAppNavbar and OcAppContent

---

apps/files/src/components/FileList.vue
apps/files/src/components/FilesApp.vue
apps/files/src/components/FilesTopBar.vue
apps/files/src/mixins.js
apps/files/src/store.js
nightwatch.conf.js
src/components/form/SearchBar.vue
tests/acceptance/stepDefinitions/loginContext.js

search for files in files app via ownCloud search. Filter local folder, even in searched folder list!
The local file filter filters the search result, if search term is inside the search-bar.
SearchBar need's keydown Enter, File Filter work's onType.
Integrates special view for search results. It's using the search-bar component.
**:warning:Including Heavy FileApp state refactoring!**
- Fixes #516
- Fixes #662
- refs #665
- replace pr #588 
- replace pr #607 
global search now hide's the breadcrumb & changes the file row design.
It's parent folder is only shown in search mode.
I've found some issues related to our refactoring, i've almost solved them all. I needed to put some files-state derived data into the store, so we're able to map them in few components.
- open Files app
- type 'md' …

global & local file search

---

apps/files/src/components/FileFilterMenu.vue
apps/files/src/components/FilesTopBar.vue
apps/files/src/fileFilters.js
apps/files/src/store.js

moved filter into `fileFilters.js`, load in store.
Split v-model from checkbox to catch event manually & inject value into v-checkbox `input-value` prop
- Fixes #665
filters were hardcoded before, but we need them at a few places...
abstract them in state.
- create folder, directory & hidden files
- check & uncheck file filters
design has not changed, It's just working again

close #665 fix file filters

---

apps/files/src/components/FilesTopBar.vue
apps/files/src/components/ocDialogPrompt.vue

Add spinner for file/folder creation dialogs.
- Fixes #419
To make UX more interactive
Tested locally, manually

Add spinner for file/folder creation dialog

---

apps/files/src/components/FileList.vue
apps/files/src/store.js

Allow rename only if permissions are granted
- fixes -#793
- :hand:

Allow rename only if permissions are given to the user

---

src/components/Menu.vue
src/components/Top-Bar.vue

- burger bar toggles menu
- close button works
- menu items loaded from root navItems provided by apps
- logout hardcoded 
Relies on https://github.com/owncloud/owncloud-design-system/pull/121

use oc-left-menu for main owncloud menu

---

apps/files/src/components/FilesApp.vue
apps/pdf-viewer/src/PdfViewer.vue
apps/pdf-viewer/src/PdfViewerTopbar.vue
apps/pdf-viewer/src/app.js

Fixed opening of pdf viewer and wrong components names and added reset of current page when switching between different pdf files.

Fixed opening of pdf viewer and wrong components names

---

apps/files/src/components/FilesTopBar.vue

Fixed progress bar by assigning progress status with fileUploadProgress.

Fixed progress bar

---

apps/files/src/components/FilesTopBar.vue

Renamed route in breadcrumps to 'to' because of ods component. Also edit base path because the link ignored files/list.

Fixed links in breadcrumbs

---

tests/acceptance/pageObjects/filesPage.js

find the complete `tr` element as fileRow and not only the link to the file
the link is not the row, we want to find the complete row to be able to get to the buttons of that particular files e.g. the delete button

use tr as fileRow instead of the link

---

nightwatch.conf.js

allow to specify an selenium host when running UI tests locally
useful when running selenium in docker

allow to specify external selenium host

---

apps/files/src/components/FileList.vue
apps/files/src/mixins.js

Moved multiplying of file size into its own filter to preserve it in file list but get rid of it in file upload menu.
- Fixes #901 

Fixed file size in file upload menu

---

.drone.yml
tests/acceptance/features/webUIFiles/createFolders.feature
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/pageObjects/phoenixPage.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/generalContext.js

1. improve waiting for folder creation should give us 90-100% passing see https://drone.owncloud.com/owncloud/phoenix/2204 https://drone.owncloud.com/owncloud/phoenix/2205
2. move folder creation code to pageObject
3. create a folder with a name that already exists
part of #844

Create folder with existing name tests

---

tests/acceptance/features/webUIFiles/browseDirectlyToDetailsTab.feature

feature files for the browse-directly-to-tab feature
Is that actually something that should be implemented in phoenix?
part of #844 
features were copied from core and are currently skipped here, as the feature is not implemented in phoenix yet and also the test steps need to be implemented in nightwatch.js

descriptions for browse-directly-to-tab feature

---

tests/acceptance/features/webUIWebdavLockProtection/delete.feature
tests/acceptance/features/webUIWebdavLockProtection/move.feature
tests/acceptance/features/webUIWebdavLockProtection/upload.feature
tests/acceptance/features/webUIWebdavLocks/locks.feature
tests/acceptance/features/webUIWebdavLocks/unlock.feature

feature files for the webdav lock feature
part of #844 
features were copied from core and are currently skipped here, as thefeature is not implemented in phoenix yet and also the test steps need to be implemented in nightwatch.js

descriptions of webdav lock feature

---

README.md
package.json

only run those tests locally that are requested
as the test suite grows it is not practical to run all tests when developing
so we want to be able to specify what tests to run
e.g. a single test `yarn run acceptance-tests tests/acceptance/features/webUIFiles/createFolders.feature:20`
all tests of a file `yarn run acceptance-tests tests/acceptance/features/webUIFiles/createFolders.feature`
all tests of a suite `yarn run acceptance-tests tests/acceptance/features/webUIFiles/`
all available tests `yarn run acceptance-tests tests/acceptance/features`

do not run all tests locally

---

tests/acceptance/features/webUIRenameFiles/renameFiles.feature
tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
tests/acceptance/features/webUIRenameFolders/renameFolders.feature
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

tests to check renaming of files & folders
1. `waitForFileVisible()` also checks the human readable file-name
2. enabled various rename tests
3. implementation of rename steps and pageObject actions
4. tagged problematic tests with the related issues. In some cases its hard to write tests that pass now and will fail when the bug is fixed. Main problem is that after the rename part of the DOM is updated and part not - so bots `should` and `should not be listed` steps failing - see #934
- part of #844

rename file and folders tests

---

src/components/Avatar.vue

No need to createObjectURL if the request failed

---

apps/files/src/components/FileList.vue

Exchanged single quotes with backticks and squashed deleteConfirmation dialogue and translated variable.
- Fixes #911

Fixed display of special characters in delete dialog

---

apps/files/src/components/FilesApp.vue
apps/files/src/components/FilesTopBar.vue
apps/files/src/mixins.js
apps/files/src/store/actions.js

Added clearing of the search after navigating into a folder and after trying to navigate into the active folder.
- Fixes #979

Clean search after navigating into a folder

---

webpack.dev.js

Ignore tests folder on webpack-dev-server watch so that the full page reload doesn't occur for test file changes.
Don't reload web app on test file changes.
:hand:

Don't watch test files for full page reload

---

apps/files/src/components/FileDetails.vue

Just like in OC10 some more information about the current selected file is displayed in the header

Add some more information about a file in the side bar header

---

apps/files/src/components/FilesTopBar.vue

We need to prevent data loss at any time. It is not allowed to overwrite a file silently.
- refs #476 
- create a file on the server - e.g. via the old webui 
- do not reload phoenix
- create the same file in phoenix
- see an error poping up

Use If-Not-Match: * to prevent overwrite of new uploaded file

---

.drone.yml

Only run build-docker-image on pull request merge
Make drone faster
🤖

Add missing matrix for run build-docker-image only after job

---

.drone.yml

Hide the screenshots taken from failing acceptance tests by default.
This way we are not polluting the PR that much,
In addition the failing acceptance test is now part of the comment as well
- :robot:

Bugfix/collapse screenshots on GitHub

---

apps/files/src/components/FileList.vue
apps/files/src/mixins.js

Translating interpolated strings has to be done this way: https://github.com/Polyconseil/vue-gettext#interpolation-support-1
- :hand:

Fix usage of interpolated strings in gettext

---

.drone.yml
oidc-callback.html
oidc-silent-redirect.html
src/services/auth.js
webpack.prod.js

OAuth/OpenIDConnect redirect uris are not allowed to contain fragments.
- Fixes #573 
- :hand: 
- :robot:

Use OAuth/OpenIDConnect redirect uri without fragment

---

tests/acceptance/pageObjects/filesPage.js

Fix drone failing sometimes on scenario `Delete empty folder` 
on create folder step.
fixes #1090
Add more tests
🤖

Fix drone error on creating folder

---

apps/files/src/components/FileList.vue
apps/files/src/components/FilesApp.vue
package.json

The effort to make the filesApp responsive.
TODO:
**Landscape**

gradually hide fileList elements as width shrinks

---

apps/files/src/components/FileDetails.vue
apps/files/src/components/FileList.vue
apps/files/src/components/FilesApp.vue
apps/files/src/components/FilesTopBar.vue
src/Phoenix.vue
src/components/Top-Bar.vue

I removed stickiness from elements and ensured scrolling by adding scroll to apps. To ensure scroll for any app in the future, there is a container in phoenix.vue. That way other developers doesn't have to define it all the time again. But I also defined scroll in files app. That way we also don't need stickiness at sidebar.
- https://github.com/owncloud/owncloud-design-system/issues/225

Added scroll to apps and removed stickiness

---

apps/files/src/components/FilesApp.vue
apps/files/src/components/FilesTopBar.vue
apps/files/src/default.js
apps/files/src/store/actions.js
src/components/Menu.vue

Created a `favorites` item inside of `menu`,  added condition in `loadFolder` action and used `getFavoriteFiles` function.

Created favorites page

---

tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/helpers/httpHelper.js
tests/acceptance/helpers/userSettings.js
tests/acceptance/stepDefinitions/loginContext.js
tests/acceptance/stepDefinitions/provisioningContext.js

Add methods to implement default user creation.
#844
Create users with some pre-defined settings like, `password`, `displayname` and `email`
🤖

acceptance-test/implement default user creation

---

index.html
src/phoenix.js

Bundle wicked-good-xpath
fixes #1208 
- :hand: in IE11 ina VM

Bundle wicked-good-xpath

---

.drone.yml

use an older version of chrome selenium to make CI pass again.
The latest version updated the chrome browser and since then CI fails with 
```
Error while running .isElementDisplayed() protocol action: TypeError [ERR_UNESCAPED_CHARACTERS]: Error while trying to create HTTP request for "/wd/hub/session/fa970f0d7a9230b30b045d3661db484d/element/[object Object]/displayed": Request path contains unescaped characters
at new ClientRequest (_http_client.js:115:13)
at Object.request (http.js:42:10)
at HttpRequest.createHttpRequest (/home/artur/www/owncloud-phoenix/node_modules/nightwatch/lib/http/request.js:112:55)
at HttpRequest.send (/home/artur/www/owncloud-phoenix/node_modules/nightwatch/lib/http/request.js:191:29)
at Promise (/home/artur/www/owncloud-phoenix/node_modules/nightwatch/lib/transpo …
```

use pre-latests selenium

---

apps/files/src/components/ocDialogPrompt.vue

Fixes #1259 - break text in prompt dialog

---

apps/files/src/components/FileList.vue

Added oc-drop with actions for smaller resolution.
- Fixes #1237 

Added actions for small resolution

---

tests/acceptance/features/webUIFavorites/favoritesFile.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/filesContext.js

Add test step to assert the number of files/folders displayed on the web UI
Tests were failing the webUIFavories due to issue #1189 because the last item
that should be listed in the favorite page was not being displayed. By using the number of items that should be displayed, we are free from file/folder name dependency that should be displayed in the favorites page.
*Note: callbacks are removed in favor of Promises to improve code readability.*
🤖

Add test step to assert the number of files/folders in webUI

---

.drone.yml
nightwatch.conf.js
tests/acceptance/stepDefinitions/loginContext.js

run UI tests again with the current version of Chrome
tests were switched to chrome 74 in https://github.com/owncloud/phoenix/pull/1260
nightwatch made a workaround of the current issue in chrome and now it works again with disabled W3C protocol and nightwatch 1.1.12 https://github.com/nightwatchjs/nightwatch/releases/tag/v1.1.12
:robot:

run UI tests in chrome 75

---

apps/files/src/components/FilesApp.vue

Changed the `v-show` to `v-if` in right sidebar. If the sidebar was loaded on page load, the versions were loaded even without selected files which kept throwing errors and blocked call for the function `getFileVersions()` in case a new file was selected.
Functioning file versions and no errors 🙂 
- test case 1: Select file without any previous version
- test case 2: Select file with previous version

Fix loading of file versions

---

Dockerfile

ran into this:
```
Step 1/10 : FROM node:9.11.1-alpine as build-stage
---> 9cc7800b3f3c
Step 2/10 : RUN apk update && apk upgrade &&     apk add --no-cache bash git
---> Running in 16dd6e8d858e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
v3.6.5-44-gda55e27396 [http://dl-cdn.alpinelinux.org/alpine/v3.6/main]
v3.6.5-34-gf0ba0b43d5 [http://dl-cdn.alpinelinux.org/alpine/v3.6/community]
OK: 8448 distinct packages available
Upgrading critical system libraries and apk-tools:
(1/1) Upgrading apk-tools (2.7.5-r0 -> 2.7.6-r0)
Executing busybox-1.26.2-r9.trigger
Continuing the upgrade transaction with new apk-tools:
(1/7) Upgrading musl (1.1.16-r14 -> 1.1.16-r15)
(2/7) Upgrading busybox …
```

fix phoenix build

---

apps/files/src/store/actions.js
tests/acceptance/features/webUIFavorites/favoritesFile.feature
tests/acceptance/features/webUIFavorites/unfavoriteFile.feature

Set root folder as current folder for favourites page and removed permissions to upload in that page.
- Fixes #1247
- Fixes #1189

Load favorite page without items

---

nightwatch.conf.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/pageObjects/favoritesPage.js
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/loginContext.js

this should hopefully make the most frequent failures less likely
1. retries when the authentication did not work properly
2. retries when the typing in the share-with input did not trigger the event
3. wait for better indicators when opening files pages
4. wait till ajax calls are finished when sharing
5. disable-dev-shm-usage should help prevent selenium crashes, see https://stackoverflow.com/questions/53902507/unknown-error-session-deleted-because-of-page-crash-from-unknown-error-cannot
- run CI a lot, seems to be better but still not 100% stable

improve test stability

---

tests/acceptance/features/webUIFavorites/favoritesFile.feature
tests/acceptance/pageObjects/phoenixPage.js
tests/acceptance/stepDefinitions/filesContext.js

Add test for going back to files page after the user has browsed to the favourites page.
🤖
Fixes #1188

Add tests for going back to files page

---

tests/acceptance/pageObjects/phoenixPage.js

Favorites page tests were failing because the test tried to click the sidebar element 
while the sidebar was still sliding.
This PR fixes it to only click on the element after the sliding animation is complete.

Fix favoritesPage test failure due to sidebar sliding slow.

---

src/store/app.js

Replaced notifications name in messages in app store to messages.

Fixed name of alerts in store

---

tests/acceptance/features/webUIFavorites/favoritesFile.feature
tests/acceptance/features/webUIFiles/createFolderEdgeCases.feature
tests/acceptance/features/webUIRenameFiles/renameFiles.feature
tests/acceptance/helpers/xpath.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/filesContext.js

This adds a test scenario for favoriting files and making sure that they exist in the favorites page. More scenario are needed. To accustom for the full path shown in the page, `fileList()` had to be changed, which now checks for whole filename instead of an attribute (which is a good thing?).
- Related to #1194
- locally

Acceptance test for favorites page

---

apps/files/src/components/FileDetails.vue
apps/files/src/components/FileList.vue
apps/files/src/default.js
src/Phoenix.vue
src/components/Menu.vue
src/store/user.js

The sharing side bar is only enabled if sharing is enabled on server side
- Fixes #1155 
- :hand:

Enable sharing sidebar only if sharing is enabled

---

apps/files/src/components/ocDialogPrompt.vue

Added focus on confirm button in dialog if there is no input available.
User can now confirm dialog by hitting enter.

Autofocus in oc-dialog

---

tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/helpers/httpHelper.js
tests/acceptance/helpers/userSettings.js
tests/acceptance/stepDefinitions/loginContext.js
tests/acceptance/stepDefinitions/provisioningContext.js
tests/acceptance/stepDefinitions/sharingContext.js

1. remember users that have been created during the test run in a separate table. When information about users that are expected to exist are required use the data from that new table.
When general information about a specific user is required, but the user is not created yet, fall back to the information from the general users table
2.  delete users that have been created during a test-run after the test
3. delete a test step that refereed to an non-existing user. This test used to pass because the user was created in some other scenario, but now users get deleted after every scenario, so the test could not share with that user. But that step is also not needed for that particular test
4. retrieve the display name of the current user on the go without using unnecessary global variables
- …

remember created users

---

apps/files/src/store/mutations.js

Find index of file by id and not by name to prevent wrong files to be found in case they have same name.
- Fixes #1385

Unfavourite files with same names in favourites page

---

package.json
yarn.lock

because of https://github.com/IdentityModel/oidc-client-js/pull/898 we switch temporary to git version of oidc client

Use oids from git because of latest bugfix

---

apps/files/src/components/FileFilterMenu.vue
apps/files/src/components/FileList.vue
apps/files/src/components/FilesApp.vue
apps/files/src/components/FilesAppBar.vue
apps/files/src/components/Trashbin.vue
tests/acceptance/pageObjects/phoenixPage.js

Moved load folder and load trashbin methods to its related components to prevent issues caused by its placement in FilesApp and to get rid of conditions to decide which should be used.
- Fixes #1410 
Less bugs, cleaner code.

Moved load folder methods into related components

---

tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
tests/acceptance/helpers/userSettings.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/provisioningContext.js
tests/acceptance/stepDefinitions/sharingContext.js

1. remember created groups
2. delete groups with `DELETE` not `POST` :see_no_evil: 
3. make the step `Then all users and groups that contain the string {string} in their name should be listed in the autocomplete list on the webUI` check if all users and groups, that are expected to be in the list, are in the list
- Fixes #1473

improve sharing autocomplete tests

---

src/components/MessageBar.vue

Added limit to messages to display maximum 5 at once and transition (needs https://github.com/owncloud/owncloud-design-system/pull/419 to work).
Not spamming users whole 🖥 with messages.

Added limit for messages and transition

---

apps/files/src/components/FileList.vue
apps/files/src/mixins.js

User can now see what file is he renaming and if it is a folder or file.
- test case 1: Open rename dialog for file
- test case 2: Open rename dialog for folder

Change title of rename dialog

---

apps/files/src/components/FilesAppBar.vue
apps/files/src/components/ocDialogPrompt.vue
apps/files/src/mixins.js

Resolve promise as false if the user clicks on cancel button in overwrite dialog and move clean input action into the addToQue methods to ensure it is triggered even if the file is not being uploaded.
- test case 1: Upload file that already exists and cancel overwrite
- test case 2: Upload file that already exists confirm overwrite
- test case 3: Upload folder that already exists and cancel overwrite
- test case 4: Upload folder that already exists and confirm overwrite
- test case 5: Upload multiple files and do both cancel and confirm actions

Fixed cancel action of overwrite dialog

---

apps/files/src/components/FilesAppBar.vue
apps/files/src/components/ocDialogPrompt.vue
tests/acceptance/features/webUIFiles/createFolders.feature

Added check if file or folder already exists into the creation features.
- Refs #1164
- test case 1: Try to create a file with existing name
- test case 2: Try to create a folder with existing name

Check if file already exists

---

.dockerignore

Since #1454 we require the git folder to determine the commit hash
Due to build errors the demo system was not updated since then
- docker build .

Build requires the git folder to determine the commit hash

---

.htaccess

New caching setting ensure that all assets are not cached at all.
Pro: always get latest frontend deliverables
Con: more server load

Disable caching for all Phoenix deliverables

---

src/services/auth.js

The log level of the open id client can now be set via config.json

Allow to set the oidc log level via config.json

---

apps/files/src/components/FileList.vue
apps/files/src/components/ocDialogPrompt.vue
apps/files/src/mixins.js
tests/acceptance/features/webUIRenameFiles/renameFiles.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js

Use the same error handling in rename feature as is in create folder/file.
- Fixes #1450
Consistent error handling behaviour

Make name errors consistent

---

apps/media-viewer/src/Mediaviewer.vue

Download via the media viewer is now properly working. Before getToken was undefined ...
- open image in mediaviewer
- click download icon
- see the download happen

Properly set token in download request

---

.drone.yml
apps/files/package.json
apps/files/src/components/Trashbin.vue
apps/files/yarn.lock
tests/acceptance/features/webUITrashbin/trashbinDelete.feature
yarn.lock

Within the trashbin up to 4 permanent delete operations are performed in parallel at a time.
This approach needs to be adapted to any file operation ....
#1502 
- delete a lot of files
- go to trash bin
- mark some of them (10+)
- open network tab
- click delete selected
- see 4 requests being executed in parallel

Allow 4 concurrent delete operations

---

apps/files/src/components/FileSharingSidebar.vue
tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

Filter results of collaborators search by id as well and not only by label.
- Fixes #1532
- test case 1: Create a user (e. g. with username: "owncloud1" and display name "user1")
- test case 2: Write into collaborators autocomplete "owncloud1"
- test case 3: Write into collaborators autocomplete "user1"

Search collaborators also by id

---

apps/files/src/components/FileSharingSidebar.vue

If the share already exists for users/groups don't show them as a result in autocomplete.
- Refs #1186

Don't show items in autocomplete if they already exist

---

apps/files/src/mixins.js

In FilesApp wasn't passed the token thus download failed with unauthorised error. The getter for token is now in mixins so we don't need to pass it with the specific component.
- Download file with button in file row
- Download file with link in actions menu

Added getter for token into mixins

---

apps/files/src/components/FileDetails.vue
apps/files/src/components/FileInfoVersions.vue
apps/files/src/components/FileList.vue
apps/files/src/components/FilesAppBar.vue
apps/files/src/components/PublicLinks/PublicLink.vue
apps/files/src/default.js
apps/files/src/mixins.js
apps/files/src/store/actions.js
apps/files/src/store/getters.js
apps/files/src/store/mutations.js
apps/files/src/store/state.js
apps/files/yarn.lock
apps/markdown-editor/yarn.lock
apps/media-viewer/src/Mediaviewer.vue
apps/media-viewer/src/app.js
apps/media-viewer/yarn.lock
apps/pdf-viewer/yarn.lock
package.json
src/components/Top-Bar.vue
src/phoenix.js
src/plugins/mediaSource.js
src/plugins/phoenix.js
src/router/index.js
yarn.lock

Adding public link display - following cases are implemented:
- refs #1655 
- get https://github.com/owncloud/core/pull/35932
- setup the phoenix.baseUrl setting in the config.php - see https://github.com/owncloud/core/blob/bd3df85448af0e32bf199d6772b5b5eaf8c02091/core/routes.php#L84
- share a file publicly (old oc frontend for now)
- open this link in a private browser window
- see the browser opening up phoenix and displaying the file/image

Add public link display

---

apps/files/src/components/Collaborators/AutocompleteItem.vue
apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/Collaborators/NewCollaborator.vue
apps/files/src/components/Collaborators/mixins.js
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/store/actions.js
apps/files/src/store/getters.js
apps/files/src/store/mutations.js
apps/files/src/store/state.js
package.json

Grey out other collaborators when add or edit action is in progress, added cancel button to edit and divided code into smaller components.
- Refs #1186 

Fix process of collaborators

---

apps/files/src/components/FileList.vue

FileList: clicking on a disabled button shall not open the sidebar
- test case 1:
- test case 2:
- ...

FileList: clicking on a disabled button shall not open the sidebar

---

apps/files/src/components/Collaborators/AutocompleteItem.vue
apps/files/src/components/Collaborators/mixins.js
package.json
yarn.lock

Added icons as placeholders for collaborators

---

src/components/Notifications.vue

Removed sort of actions, replaced buttons with oc-button component and added reload action for files list.
- Refs #1186 
- Fixes #1667
1. Turn off auto-accept of shares
2. Share file with another user
3. Open notifications drop
4. Decline notification
5. Accept notification

Fixed actions in notifications

---

.drone.yml

use mySQL as the database server
converting `.drone.yml` to the new version caused the tests to run with sqlite again. That would explain the increasing CI failures
:robot:

user MySQL server as database

---

apps/files/src/components/FileDetails.vue
apps/files/src/components/FileList.vue

Use name of the tab to define which one is selected instead of key to prevent wrong tab being selected if other tab is disabled but the key is not changed.
1. Open sidebar by clicking on file row
2. Open sidebar by clicking on folder row
3. Open sidebar by clicking on collaborators action

Define active tab by name instead of key

---

apps/files/src/components/Collaborators/SharedFilesList.vue
apps/files/src/components/FileDetails.vue
apps/files/src/components/FileList.vue
apps/files/src/components/FilesApp.vue
apps/files/src/default.js
apps/files/src/mixins.js
apps/files/src/store/actions.js

Created `SharedFilesList` component. Moved most of file list related functionality into mixins so we can reuse it in different lists. At the moment this list doesn't contain any actions thus checkboxes and star were removed as well and file name got class `uk-disabled` to prevent any hover/focus on it and to allow selecting of the row by clicking on it.
- Refs #1186 
1. Share file with other user
2. Share file that has been shared with me with can share permission with some other user

Shared with others list

---

apps/files/src/components/FileInfoVersions.vue
tests/acceptance/features/webUIFiles/fileDetails.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

Tests to make sure the side-panel opens correctly when clicking just the file row and not the action button
:robot:

test the files side-bar when clicking the file row

---

apps/files/src/components/Collaborators/AutocompleteItem.vue
apps/files/src/components/Collaborators/Collaborator.vue

In case admins sets additional info to be displayed, show it next to the display name in collaborators for both autocomplete and list.
- Refs #1186 

Show additional info

---

tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature

currently its impossible to navigate into a subfolder in trashbin see https://github.com/owncloud/phoenix/issues/1725#issuecomment-519390558
so no need to try to test it
:robot:

delete unneeded steps for trashbin tests

---

apps/files/webpack.common.js

Fixes ES6 transpiling issues in files and media viewer, that popped up in IE11.

Fix babel transpiling issues

---

src/plugins/phoenix.js

Inserted download anchor into the body of document and hid it with `display: none`
- Fixes #1719
1. Download file in Chrome
2. Download file in Firefox

Fixed download in Firefox

---

apps/files/src/components/FileList.vue
apps/files/src/mixins.js

Added relative position to table cell containing actions to prevent them staying at the same position while scrolling.
- Fixes #1762
- Fixes #1771
Since we use overflow to handle scroll of files list absolute position won't work properly while scrolling. To prevent the element to stay on the screen it's parent needs position relative.
1. Open actions drop on mobile resolution
2. Open actions drop on desktop resolution while having sidebar opened
3. Scroll

Prevent scroll of file row actions

---

apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/Collaborators/mixins.js

Check if the new selected role is not the same as original role and prevent trigger of edit if it is.
- Refs #1186
1. Select same role for collaborator
2. Select different role for collaborator

Trigger collaborator edit only after change

---

apps/files/src/components/FilesAppBar.vue

Created focus helper method
- Fixes #1648 
Accessability bugfix
- checkout the mobile files app view
- click on search
- the search drop opens and the input should be focused automatically

Focus search input when clicking search drop on mobile views

---

src/components/MessageBar.vue

Added `uk-width-large` class to alert messages.
With transition alert messages were getting position absolute which led to their shrinking while disappearing. With fixed width this is prevented.
1. Trigger alert message
2. Close the message

Added fixed width to alert messages

---

apps/files/src/components/FilesAppBar.vue

Removed value from mobile search bar and reset its value after the route has been changed.
- Fixes #1770
When the `searchTerm` was used as a value the button would be always disabled since the value wasn't updated when writing a new search term.
1. Switch to mobile view in dev tools
2. Open search bar
3. Write a search term
4. See button change it's colour to primary
5. Click on the button
6. Try navigating into found folder
7. Open search bar again and see empty value

Enable click on search button on mobile

---

README.md

Add entry in README to mention the switch that enables unstable APIs from server core.
- Ref: https://github.com/owncloud/core/issues/36118 and https://github.com/owncloud/core/pull/36124
Some APIs in core are still in development and not stable for production use.
The DAV Trashbin API and public DAV endpoint for public links are currently unstable, so for Phoenix to use them we must enable them in the setup.
Doc-only change

Add setup about tech preview APIs in server core

---

webpack.dev.js

Prevents running quickly out of watch descriptors.
In my setup, just running `yarn watch` would tell me that it ran out of descriptors.
Of course I could also decide to increase the system limit, but having a better default prevents the potential distraction of having an extra config step for new setups.

Don't yarn watch node_modules

---

apps/files/src/components/FileList.vue
apps/files/src/components/FilesAppBar.vue
src/plugins/phoenix.js

Use request in file download method, add the file that is being downloaded into progress queue and disable file actions if download action is in progress.
- Refs #526
This is a temporary solution since we wanted to rework the progress handler anyway and it also doesn't solve the issue with download being done in the background so just referencing the issue instead of closing it.
- Fixes #1808 
When user downloads a big file he could start triggering download multiple times since he had no feedback until the file was downloaded in the background. With request, we can track the progress and add the file into the progress queue. To also prevent triggering the download again it's better to disable actions for the file that is being currently downloaded.
1. …

Add download feedback

---

src/pages/accessDenied.vue

Added fixed width to footer of access denied page and moved link into `p` tag to keep it on same line.
Without fixed width the footer would expand across the screen create one big line of text - bad. Also when the link was outside the `p` tag, it was always on its own line + margin bottom was applied.

Adjusted access denied template

---

src/store/user.js

Use path instead of name in redirect.
The redirect wasn't working with name in push function.
1. Create fake error in authorisation
2. Authorise
3. Get redirected to access denied page

Fix redirect to access denied page

---

apps/files/src/components/Trashbin.vue

Applied the same logic on the trashbin files as file-favorites uses
- Fixes #1525 
- See #1525

Render full file path in trashbin

---

src/components/Notifications.vue

Added a procentual width(75%) instead of a fixed width to all small devices (<640px = all common mobile devices) and removed the boundary
- Fixes #1505 
- Generate a test notification via occ
- Check if the notification panel is fully visible on large as well as small devices

Notifications now fully visible on small screens

---

webpack.dev.js

For some reason I got an error again today about too many watchers and it was pointing at a file in "apps/*/node_modules".
This PR also excludes apps' "node_modules" and additionally "dist" and "build", just in case...

More watch exclusions

---

src/components/Top-Bar.vue

Whenever the server does not support notifications, don't bother pinging
its API
Fixes https://github.com/owncloud/phoenix/issues/1957

Only fetch notifications if capability is set

---

src/store/user.js

Any request sent from phoenix to ownCloud has to include the header X-Requested-With
This is necessary to prevent browsers to popup an authentication dialog on a 401 response
This will only work with ownCloud 10.3

Set X-Requested-With header - required ownCloud 10.3

---

.editorconfig
tests/acceptance/features/webUILogin/login.feature

Adjusted `.editorconfig` for feature files.
Adjusted one feature file that still had tabs.

Use 2 spaces instead of tab for feature files

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature

test sharing also just a single file via public link

test sharing a file via public link

---

apps/files/src/components/FileLinkForm.vue
apps/files/src/store/actions.js
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/stepDefinitions/publicLinkContext.js

The permissions for Editor and Contributor got mixed up.
This swaps them.
Fixes https://github.com/owncloud/phoenix/issues/1979
- test case 1:
- test case 2:
- ...
Test will come separately in https://github.com/owncloud/phoenix/pull/1980

Fix public link permissions mix up

---

package.json
yarn.lock

See https://github.com/championswimmer/vuex-persist/issues/138 - 2.1.0 is not working in IE11

Downgrade vuex-persist to 2.0.1 to fix IE11 issues

---

src/pages/oidcCallback.vue

Handle OAuthh/OpenIdConnect error in callback request query string
- requires https://github.com/owncloud/oauth2/pull/220
- connect with owncloud and OAuth2 app as per PR above
- send wrong request type in https://github.com/owncloud/phoenix/blob/e93dd8bcddf19b966476e2c5bcb9025cda5f178c/src/services/auth.js#L49 - e.g. 'oken' instead of 'token'
- see the redirect page being called with a general error message

Handle OAuth/OpenIdConnect error in callback request query string

---

apps/files/src/fileSortFunctions.js
apps/files/src/store/getters.js
apps/files/src/store/state.js
tests/acceptance/features/webUIFiles/sort.feature
tests/acceptance/helpers/webdavHelper.js
tests/acceptance/stepDefinitions/filesContext.js

To sort by folder, file, then name using natural sort.
The utility functions were imported from OC core.
Ref https://github.com/owncloud/phoenix/issues/1854#issuecomment-531293571
We need at least one default sort to make the list look less ugly when it has a mix of files and folders.
- test case 1:
- test case 2:
- ...

Add default client side sort

---

package.json
src/phoenix.js
src/store/apps.js

Load also external apps via requirejs and load their config either from appInfo, config.json or both. Define apps in config with:
```
"external_apps": [
{
"id": "<app-id-specified-in-appinfo>",
"path": "<path-to-app-bundle.js>",
"config": {
...
}
}
]
```
- Fixes #1151
Tested with https://github.com/owncloud/ocis-hello

Enable loading apps from external sites

---

tests/acceptance/helpers/sharingHelper.js
tests/acceptance/stepDefinitions/sharingContext.js

Use human readable strings instead of number.
- Fixes #2047 
- CI

Use sharetype keys that are human readable instead of number

---

apps/files/src/components/FileDetails.vue

1. Get item which returns no size
2. See no comma before mdata

Hide comma before mdate if size is in pending state

---

apps/files/src/components/FilesAppBar.vue
tests/acceptance/customCommands/getClipBoardContent.js
tests/acceptance/features/webUIFiles/copyPrivateLinks.feature
tests/acceptance/helpers/webdavHelper.js
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

Allows to copy the private link
- Fixes #1988

Add a private link for the current folder to the app bar

---

src/plugins/phoenix.js

When opening public links while a session exists, we should still
consider the page a public page whenever the route is not requiring
auth. The latter is the case for public files and files drop pages.
Fixes https://github.com/owncloud/phoenix/issues/1884

Fix detection of public pages despite existing auth

---

tests/acceptance/helpers/webdavHelper.js

The `password` argument was unused. Removing it here as `httpHelper.createAuthHeader()` already uses password from given userid.
- locally

Remove unused password arg from webdav.propfind

---

src/components/Menu.vue
tests/acceptance/features/webUILogin/login.feature
tests/acceptance/helpers/loginHelper.js
tests/acceptance/pageObjects/phoenixPage.js
tests/acceptance/stepDefinitions/loginContext.js

Added logout step.
Added logout test case that includes the step and checks that the login
page appears after logging out.
Needed to be able to log out in some test cases, especially the public link ones.
- manual run

Added logout step for acceptance tests

---

src/store/index.js

When logging out, we also reset capabilities in the SET_CAPABILITIES
mutation. To make sure that the cleared capabilities are persisted in
localStorage, we must include the above mutation in the whitelist for
vuex-persist.
See more detailed analysis here: https://github.com/owncloud/phoenix/issues/1882#issuecomment-537012974
Indirectly related to https://github.com/owncloud/phoenix/issues/1882
Proper cleanup on log out and avoid side effects with public pages like public links.
Login then log out. Then check local storage in the browser console, key "phoenixState" and in the JSON look at "user.capabilities" and "user.versions".
Before the fix, logging out would leave the values there.
After the fix, those arrays are properly cleared.

Properly reset capabilities on logout

---

apps/files/src/components/FilesAppBar.vue

- Refs #2119
Fixing properly drag and drop for IE11 would take a lot of effort. Due to escalation needs to be disabled for now.
1. Try drag and drop in normal browser
2. Try the same in IE11

Disable drag and drop for ie11

---

tests/acceptance/helpers/webdavHelper.js
tests/acceptance/stepDefinitions/filesContext.js

The following scenario was failing a lot (given other are fixed). 
https://github.com/owncloud/phoenix/blob/417dd1e771f7e45b070c2b4bef893374cbf98525/tests/acceptance/features/webUIFiles/copyPrivateLinks.feature#L11-L18
This adds a better error handling on why the given scenario is failing. Also, as this uses `async`/`await`, it should be able to handle edge cases as well. 
Example failures:
https://drone.owncloud.com/owncloud/phoenix/5433/3/13
https://drone.owncloud.com/owncloud/phoenix/5432/3/13

Test: Reject promise if invalid response during permalink check

---

tests/acceptance/features/webUITrashbin/trashbinDelete.feature

These tests were failing because of #1502
That issue was fixed in https://github.com/owncloud/core/pull/35879
so let's run them again
part of  #1502
tests don't like to be ignored https://blog.developer.atlassian.com/open-letter-from-an-ignored-test/
:robot:

run tests again that were failing because of #1502

---

tests/acceptance/features/webUIFiles/fileDetails.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/stepDefinitions/filesContext.js

1. fix username in a test, that test only passed because of #2150
2. test if the correct shares come up on the share-with-me and shared-with-other pages, mainly to test #2150
#2150

Shared pages tests

---

.drone.yml

Some `webUISharingPublic` scenarios were added in PR #1985 but actually that test suite is not being run in drone.
Add it to the drone pipeline matrix.
Run all acceptance tests in CI
CI

Run webUISharingPublic acceptance test suite on drone

---

tests/acceptance/customCommands/waitForAjaxCallsToStartAndFinish.js
tests/acceptance/features/webUIFiles/fileDetails.feature
tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/features/webUIUpload/upload.feature
tests/acceptance/stepDefinitions/generalContext.js
tests/acceptance/stepDefinitions/notificationsContext.js
tests/acceptance/stepDefinitions/sharingContext.js

1) there was a `Given` step starting `Given the user "userxxx"...` - remove `the` so it matches the usual form.
2) Other minor typos fixed
Make acceptance tests great again.
CI

Adjust 'the user' steps

---

apps/files/src/components/FileActions.vue

Added close button and trigger close action on route change for file action menu.
- Fixes #2078
1. Open file actions menu by clicking on file name
2. Close the menu with close button
3. Repeat step 1
4. Navigate to some other route

Add more close options to file actions menu

---

apps/files/src/components/FilesApp.vue
apps/files/src/components/FilesAppBar.vue
apps/files/src/components/UploadMenu.vue
apps/files/src/components/UploadProgress.vue
apps/files/src/mixins.js
apps/files/src/store/actions.js
apps/files/src/store/getters.js
apps/files/src/store/mutations.js
apps/files/src/store/state.js
tests/acceptance/pageObjects/filesPage.js

Removed upload spinner and added progress bar to make it more visible to user that upload is in progress.
1. Upload files or folder

Added progress bar for upload

---

apps/files/src/components/FileList.vue
apps/files/src/store/actions.js
apps/files/src/store/getters.js
apps/files/src/store/mutations.js
apps/files/src/store/state.js
src/plugins/phoenix.js

Use spinner to show that item has action in progress and remove download from upload menu
Upload menu was now restructured and the download doesn't fit there anymore and since actions in general and their feedback is going to be reworked (already were some mockups for this but haven't been worked on it since) and quick solution is needed now it doesn't make too much sense to me to spend now a lot of effort to try to keep them together in a nice way in the upload menu.
1. Download any file

Download feedback spinner

---

apps/files/src/mixins.js
apps/files/src/store/actions.js

Delete and rename operations did not handle error conditions at all before this PR.
While it is UX-wise far from good - this is better then nothing.
The whole error handling flow as well as the user confirmation flow is under review at the moment.
As say: better then nothing
- Lock a file using webdav locks (cadaver or manual insert into database)
- try to delete or rename
- see error notification

Handle errors while deleting and renaming files

---

tests/acceptance/pageObjects/FilesPageElement/filesList.js

wait for at least one item in the list, but do not fail if there is none, so that an empty list can be reported back
noticed when working on #2008 with saucelabs the timing was different and so some faivorites tests would fail
stabilise tests

[accentance tests] wait for at least one file to appear in the list

---

apps/files/src/components/FilesApp.vue
tests/acceptance/pageObjects/filesPage.js

With `v-if` were an issue in displaying the progress bar too late.
1. Upload a folder

Switch to show instead of if in upload progress bar

---

src/services/auth.js
src/store/user.js

Due to programming error two token refresh calls are issued to the IdP.
This is fixed now and more logging information is written to the console.
- to test with a true OpenId Connect IdP - e.g. PingId

Prevent duplicate token refresh calls

---

apps/files/src/components/FileLink.vue
apps/files/src/components/FileLinkForm.vue

- Immediate icon change if the link is protected (or not)
- Allow removing the password from the form.
- Fixes https://github.com/owncloud/phoenix/issues/1999
- Fixes https://github.com/owncloud/phoenix/issues/2000
See issues
Manual test

Fix password handling in public links

---

src/pages/accessDenied.vue

Due to https://github.com/Polyconseil/vue-gettext#caveat-when-using-v-translate-with-vue-components-or-vue-specific-attributes it is not *yet* possible to bind events on translated elements

Fix exit link on access denied page

---

.drone.starlark
.drone.yml
README.md
apps/draw-io/webpack.common.js
apps/markdown-editor/webpack.config.js
apps/pdf-viewer/webpack.common.js
nightwatch.conf.js
tests/acceptance/customCommands/clearValueWithEvent.js
tests/acceptance/customCommands/setValueBySingleKeys.js
tests/acceptance/features/webUIFiles/createFolders.feature
tests/acceptance/features/webUIUpload/upload.feature
tests/acceptance/features/webUIUpload/uploadEdgecases.feature
tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
tests/acceptance/features/webUIWebdavLockProtection/upload.feature
tests/acceptance/helpers/navigationHelper.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/pageObjects/favoritesPage.js
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/pageObjects/publicLinkFilesPage.js
tests/acceptance/pageObjects/sharedWithMePage.js
tests/acceptance/pageObjects/sharedWithOthersPage.js
tests/acceptance/pageObjects/trashbinPage.js
tests/acceptance/setup-drone.js
tests/acceptance/stepDefinitions/sharingContext.js

add drone and nightwatch configuration for running acceptance tests in internet explorer using saucelabs.
- Related issue #2008

[POC] Run phoenix tests on internet explorer

---

apps/files/src/components/FileList.vue

Using index as a key can cause troubles with rendering of elements.

Change key of file action buttons to ariaLabel

---

apps/files/src/mixins.js

With previous structure we were getting sometimes empty strings leading to duplicate slashes in the path for folders.
+ In Edge
+ In Chrome
+ In Firefox
1. Upload folder with subfolders

Fixed structure of folders in folder upload

---

apps/files/src/mixins.js

Move addToProgress into its own function and trigger it before the folders creation.
Since we wait until all folders are created and those promises are being processed one by one it would take quite some time before the actual progress bar is shown. This takes care of that. We need to figure out though how to handle if some specific folder fails.
1. Upload a folder with a lot of subfolders

Trigger add to progress before the folders creation

---

apps/files/src/FileUpload.js
apps/files/src/mixins.js
apps/files/src/store/actions.js
apps/files/src/store/mutations.js

Move remove from progress into its own method, use id instead of name to find the right progress and call the action on requests loadend event.
1. Upload one file
2. Upload multiple files
3. Upload folder

Handle remove from progress in its own mutation

---

apps/files/src/components/FilesAppBar.vue
apps/files/src/store/actions.js
src/plugins/phoenix.js
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/helpers/sharingHelper.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/pageObjects/publicLinkFilesPage.js
tests/acceptance/pageObjects/publicLinkPasswordPage.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/publicLinkContext.js
tests/acceptance/stepDefinitions/sharingContext.js

Disable quota for public links and pass header for upload in password-protected links.
- Fixes #1891
1. Rename file in folder shared with public link
2. Delete file in folder shared with public link
3. Upload file into folder shared with public link

Fix public links actions

---

tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/stepDefinitions/filesContext.js

the existence of that resource was not checked correctly because there has not been a heading line
remove :snake: :oil_drum:

check if a resource really exists

---

.drone.starlark
.drone.yml
tests/acceptance/features/webUIResharing/reshareUsers.feature
tests/acceptance/features/webUISharingPermissions/sharePermissionsUsers.feature
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/loginContext.js
tests/acceptance/stepDefinitions/sharingContext.js

This adds different resharing options. 
Part of #1614 
More tests are required, which is blocked by, not being able to click the permissions' button when multiple collaborators are present.

Test resharing with different permissions

---

tests/acceptance/stepDefinitions/generalContext.js

delete all locks after every test scenario
#2240
sometimes UI tests break because of not released locks after user deletion.
e.g. https://drone.owncloud.com/owncloud/phoenix/5772/15/11
```
{"reqId":"f5d7cc12-203b-449e-ae2d-224f0b108c3c","level":4,"time":"2019-10-17T03:05:23+00:00","remoteAddr":"192.168.80.4","user":"user1","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/trash-bin\/user1\/5278","message":"Exception: HTTP\/1.1 423 \"files\/4ba94e5b88b19d9c0e3c178dda39c1dc\" is locked: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Message\":\"\\\"files\\\/4ba94e5b88b19d9c0e3c178dda39c1dc\\\" is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(411): …
```

clear filelocks after test run

---

src/plugins/phoenix.js

After the request for a file has been finished in download action, remove the file from the progress queue.
- Fixes #2286
- test environment: IE11, Chrome, FF, Safari
1. Download a file

Remove file from progress after download on IE11

---

apps/draw-io/src/app.js
apps/files/src/components/FilesApp.vue
apps/files/src/components/FilesAppBar.vue
apps/files/src/mixins.js
apps/markdown-editor/src/app.js
src/store/apps.js

App can register new file handlers
- #274

Add new file menu entries for different file types.

---

tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
tests/acceptance/pageObjects/sharedWithMePage.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/sharingContext.js

Add acceptance test for accept/decline an offered(pending) shares
:robot:

Acceptance test to receive shares with same name from different users

---

src/Phoenix.vue
src/components/SkipTo.vue

Unfortunately vue-router has problem with the usual approach to implent skip link functionality, with links `<a href="#main">Skip to main content</a>`.  Issues around this are open for years ([#1668 being the main and original one](https://github.com/vuejs/vue-router/issues/1668). But none of the workarounds listed there are actually moving focus to the container with the "#"-provided id (they are rather meddling with window.history or scrolling things into visible viewport, both of which hasn't reliable influence on the keyboard focus). So I solved the skipTo functionality with a button, which is not ideal, but at least a comprehensible way (compared to changes in the router itself). Once/if this behaviour will be resolved we could easily swap the `<skip-to>` component with a link. …

Add skip to component, id attribute for <main>

---

nightwatch.conf.js
tests/acceptance/customCommands/waitForAnimationToFinish.js
tests/acceptance/customCommands/waitForCSSPropertyEquals.js
tests/acceptance/customCommands/waitForElementEnabled.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js

after file deletion we sometimes get
```
Error while running .clickElement() protocol action: element click intercepted: Element <button aria-label="show-file-actions" class="oc-button uk-button-default uk-hidden@m uk-open" id="files-file-list-action-button-small-resolution-4" aria-expanded="false">...</button> is not clickable at point (702, 170). Other element would receive the click: <div id="delete-file-confirmation-dialog" uk-modal="" class="uk-modal" style="display: block;">...</div>
```
I guess that even `waitForElementNotVisible`  reports the item to have gone the animation is still in the process of disappearing
so lets wait till the CSS property "display" is set to "none"
bonus: a new function `waitForElementEnabled()` it waits till an element is clickable. For the fading in …

wait till animations are finished after deleting file

---

apps/files/src/components/FilesApp.vue

Removed the uk-flex property on the basic files app content element
- Refs #1763
Mobile response
- test it by selecting "select all elements" on narrow screens

Remove flex property on app content to provide a proper appbar

---

apps/files/src/components/FileList.vue

Improves labels in FileList component, see #2332 
- **Dependency to https://github.com/owncloud/owncloud-design-system/pull/524**
- **Dependency to https://github.com/owncloud/owncloud-design-system/pull/525**
- **Dependency to https://github.com/owncloud/owncloud-design-system/pull/498**
- Fixes #2332
Improve screen reader operability
Firefox Accessibility Web Inspector Pane, Chrome Accessibility Web Inspector Pane (to visualize Accessibility Tree)
**Needs proper user testing!**
1. This table header item/column header conains just an unlabel checkbox, therefore no text information that could serve as label
2. This table header item/column header is completely empty
3. This checkbox is not labelled
4. This star image is semantically speaking not a control but a clickable div (covered in …

Add labels to checkboxes, table heads

---

apps/files/src/components/FileLink.vue

Replaced method for copying the public link from old package to the new one.
1. Create public link
2. Copy the link with the clipboard icon
3. Navigate to the public link

Fixed wrong method for copy action of public link

---

tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/sharingContext.js

Add acceptance test to assert user from a shareapi excluded group is not able to share files and folders
:robot:

Test that user from an excluded group cannot share resource

---

apps/files/src/mixins.js
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/features/webUIUpload/upload.feature
tests/acceptance/features/webUIUpload/uploadEdgecases.feature
tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/publicLinkContext.js

This adds tests for files and folder uploads in root and inside subdirectory, with a password, and without a password. This also fixes bug when a folder is uploaded via a public link when the password is set. (ref: #2402 ).
- Related to #2222

Test public link uploads with/without password

---

tests/acceptance/customCommands/initAjaxCounters.js

Use `loadend` event listener instead of `load` in `waitForOutStandingAjaxCalls` in order to handle ajax calls that may fail.
- Fixes #2437
The `load` event is only fired when the XHR request is successful. In case of failure the function `waitforOutstandingAjaxCalls` will wait for very long time as the event is never fired.

Acceptance tests: Fix function waitForOutstandingAjaxCalls to handle xhr failures

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature

Adds a test for public link files and folder uploads without password
- Related to #2222 

Test Files drop without password

---

tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalGroups/shareWithGroupsEdgeCases.feature
tests/acceptance/helpers/webdavHelper.js
tests/acceptance/stepDefinitions/filesContext.js

Adds acceptance tests for group sharing.
CI

group sharing acceptance tests

---

tests/acceptance/pageObjects/filesPage.js

Acceptance test for createFolder feature is re-implemented because of some asynchronous commands issue. Some commands of the command queue were skipped due to asynchronous timing reasons which was causing CI failure.
It's because CI was failing multiple times on same step.
:robot:

Fix failing createFoldersTest

---

src/services/auth.js
src/store/index.js

Switched the storage of the auth service from local to session storage.
- Fixes https://github.com/owncloud/phoenix/issues/2407
If the browser will be closed and therefore the session ends the user should start a new auth flow.

switched to sessionStorage

---

tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/pageObjects/sharedWithMePage.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/sharingContext.js

Acceptance test to share a folder or file with group and a member performs actions on received share.The test to assert auto-completion is not present for a  group that is excluded from receiving shares is also added.

Acceptance test to share a folder or file with group and a member performs actions on received share

---

Makefile.release

Tar ball is now holding the top level folder named phoenix

App tar balls need to contain top level folder named like the app itself

---

apps/files/src/components/Collaborators/AdditionalPermissions.vue
apps/files/src/components/Collaborators/AutocompleteItem.vue
apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/Collaborators/CollaboratorsEditOptions.vue
apps/files/src/components/Collaborators/NewCollaborator.vue
apps/files/src/components/Collaborators/RolesSelect.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/helpers/collaboratorRolesDefinition.js
apps/files/src/helpers/collaborators.js
apps/files/src/mixins/collaborators.js
apps/files/src/store/actions.js
package.json
tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
tests/acceptance/features/webUIRenameFiles/renameFiles.feature
tests/acceptance/features/webUIResharing/reshareUsers.feature
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPermissionMultipleUsers/shareWithMultipleUsers.feature
tests/acceptance/features/webUISharingPermissionsGroups/sharePermissionsGroup.feature
tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/helpers/sharingHelper.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
yarn.lock

Introduced helper functions roleToBitmask and bitmaskToRole, separated collaborators into smaller components and small refactoring.
- Refs #1897
- Fixes #1837 
Cleaner code
1. Share with user
2. Share with group
3. Edit existing share

Refactor collaborators to use helper classes and to map permissions

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature

Due to a merge clash, the permissions were still the old ones as they
came from another parallel merge.
@LukasHirt

Fix permission name used in tests

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js

test if password enforcement on public links works correctly when editing an existing public link
part of https://github.com/owncloud/phoenix/issues/2075
when editing a public link the password should be enforced if the enforcement setting for the selected role is enabled but if the enforcement setting is set for other roles the password should not be enforced

test password enforcement when changing public links

---

tests/acceptance/features/webUIFiles/search.feature

Adds acceptance test to verify that search from trashbin page and favorites page does the search in global scope
https://github.com/owncloud/phoenix/issues/1726
- CI
- Manual

Acceptance tests: search from trashbin page and favorites page does search in the global scope

---

tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js

Don't fail the test when the save button does not disappear
when the save fails e.g. there are issues in the input data (password missing or similar) the save button disappears and comes back again, depending when we are checking it might be there (again)

do not fail test when saving button of public link does not disappear

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

test if public link creation / edit works correctly when the expiration date is enforced
on top of #2529 (review only the second commit)
part of #2075

tests for creating public links when the expiry date is enforced

---

apps/files/src/components/FileDetails.vue
apps/files/src/components/FileLink.vue
apps/files/src/components/FilesAppBar.vue
tests/acceptance/features/webUIFiles/copyPrivateLinks.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js

Removed private links icon next to breadcrumb as well as the file destails and added it instead in… the links section
- Fixes #2218 
- tested on chrome, firefox and small devices
- as I didn't change any functionality, everything should work as expected

Moved private link icon to "links" section

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/stepDefinitions/privateLinksContext.js
tests/acceptance/stepDefinitions/publicLinkContext.js

In phoenix, when we create a public link for some resource, we get a button that copies the public link uri in clipboard and then we can paste it on browser and view shared items. WebUI acceptance test for this scenario has been added.
- Fixes #2525
:robot:

Add acceptance test for copying public link URL and assert shared resource

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/stepDefinitions/publicLinkContext.js

Acceptance test for multiple public links with same name for same file/folder
- Fixes issue #2526
-

Acceptance test for multiple public links with same name for same file/folder

---

tests/acceptance/features/webUIFiles/breadcrumb.feature
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/generalContext.js

When ```rootFolder``` is set in ```dist/config.json```, then breadcrumb is not seen one level below the root directory. For more info check this issue: https://github.com/owncloud/phoenix/issues/2538
https://github.com/owncloud/phoenix/issues/2538
- CI
- Manual

Acceptance test: breadcrumb is not seen one level below root directory when rootFolder is set

---

apps/files/src/components/Collaborators/NewCollaborator.vue
tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature

The autocomplete for adding collaborators was filtering results that
were already filtered on the server side.
This makes the filterRecipients function return true as no filtering is
necessary.
Fixes https://github.com/owncloud/phoenix/issues/2509
Manual test with "user1", "user11" and "user2".
Typing "user1" properly filters out "user2" as it's done on the server already.
Also tested "user@x" to make sure a federated share appears in the list as expected in #2509 
Expecting that all autocomplete tests in CI will still pass.

Don't re-filter autocomplete collaborators results for remote user

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

When public link share is accessed, ```collaborators```, ```links``` and ```versions``` tabs are visible. This PR adds an acceptance test to verify this scenario, which is a bug as addressed in this issue: https://github.com/owncloud/phoenix/issues/2090
https://github.com/owncloud/phoenix/issues/2090
CI

Acceptance test: check for the tabs displayed in details of public share page

---

tests/acceptance/features/webUIFiles/breadcrumb.feature
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/generalContext.js

Browsing inside problematic folder that contains ```%2F``` for eg ```folder%2Fwith%2FSlashes``` and then clicking on breadcrumb displays error message. This PR verifies this issue: https://github.com/owncloud/phoenix/issues/1883
https://github.com/owncloud/phoenix/issues/1883
Manual
CI

Selecting breadcrumb and reloading inside problematic folder

---

tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/sharingContext.js

All the assertions from `filesPage` of `page-objects` are moved to respective contexts.
To make our code more powerful and managed!
:robot:

Refactoring files-page page object for assertion management

---

tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/stepDefinitions/publicLinkContext.js

All the assertions from `publicLinksDialog` of `page-objects` are moved to respective contexts.
Better management of code-base
:robot:

Refactoring publicLinksDialog page-object for assertion management

---

tests/acceptance/pageObjects/ownCloudLoginPage.js
tests/acceptance/stepDefinitions/loginContext.js

All the assertions from **ownCloudLoginPage** `page-objects` are moved to `respective contexts`.
CI

Refactor ownCloudLoginPage for assertion management

---

apps/files/src/components/PublicLinks/FilesDrop.vue
apps/files/src/mixins.js

Limit concurrent uploads to one to avoid clogging the network queue of the browser.
The progress bar is still added before the upload actually starts, but the SDK upload method is called only once the p-queue triggers it when it's its turn.
Fixes https://github.com/owncloud/phoenix/issues/2594
Unclog the browser network queue
- Test case 1: upload many files in regular files view and observe the network console:
- before the fix: a lot of pending entries, laptop fan going crazy
- after the fix: only one pending upload network call at a time
- Test case 2: like test case 1 but using the "upload-only" public link share (aka files-drop) because this has another code path

Limit concurrent uploads to one

---

apps/files/src/components/FileLink.vue
apps/files/src/mixins.js

Gets rid of share id type checking
Reva id's are strings, therefore this guard is preventing them from being rendered.
✋

Checks on resourceid (Public Links)

---

apps/files/src/components/AllFilesList.vue

Hide quota in mounted folders.
1. Navigate to a mounted folder
2. See no quota

Hide quota on external storage

---

tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

All the assertions from **filesPage** `page-objects` are moved to `respective contexts`.
CI

Refactor filesPage page-object for assertion management

---

tests/acceptance/features/webUIFiles/filter.feature
tests/acceptance/helpers/filesFoldersHelper.js
tests/acceptance/helpers/path.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

Add acceptance test to filter files and folders and hidden elements using keyword in files page
- Fixes  #2589

Add acceptance test to filter files and folders using keyword in the files page

---

.drone.starlark
.drone.yml

pin the selenium container to a version known to work
the latest version of the selenium container has a problem to create screenshots and crashes
:robot:

pin selenium container version to 3.141.59-xenon

---

tests/acceptance/pageObjects/publicLinkPasswordPage.js
tests/acceptance/stepDefinitions/publicLinkContext.js

All the assertions from **publicLinkPasswordPage** `page-objects` are moved to `respective contexts`.
CI

Refactor publicLinkPasswordPage for assertion management

---

apps/files/src/components/FileUpload.vue
apps/files/src/components/FilesApp.vue
apps/files/src/components/UploadProgress.vue
apps/files/src/mixins.js

Regarding: progressbar, to listwrapper on complete
Improves upload user flow for screen reader users by making them programmatically aware of 
* the interstitial interface state of an upload in progress
* the end of mentioned upload progress
- Fixes https://github.com/owncloud/owncloud-design-system/issues/536
- Hard dependency on https://github.com/owncloud/owncloud-design-system/pull/556
While visual users can comprehend that an (larger) upload is running and get visual clues about its end, screen readers stay silent during the progress. This PR tackles this issue by adding two steps:
1. When the upload starts programmatic focus will be sent to the progressbar. In the related ODS PR `OcProgress` is improved with aria states/information about the upload so screen reader can pick its …

Add focus management for uploads

---

apps/files/src/components/Collaborators/NewCollaborator.vue
apps/files/src/components/FileSharingSidebar.vue

Regarding: Buttons, autocomplete, hidden panels in tab
* Make controls regarding contributor actions proper buttons
* Improve autocomplete
* Prevent getting keyboard focus into hidden part of the "Collaborators" tab
- Fixes #2593
* This PR needs https://github.com/owncloud/owncloud-design-system/pull/557 to be merged
The share flow was one particular user flow suffering from poor keyboard and screen reader accessibility.

Fix aspects of share flow accessibility

---

apps/files/src/components/FileOpenActions.vue
apps/files/src/components/FilesApp.vue
apps/files/src/default.js
apps/files/src/fileactions.js
src/store/apps.js

Prototype to show how #2573 could work
For the file action POC please add this json snippet to config.json
```json
"files": {
// ....
"actions": [
{
"icon": "/documents/office.svg",
"url": "/documents/edit/{PATH}",
"title": {
"en": "Edit in Awesome Office™",
"de": "Mit Awesome Office™ bearbeiten"
},
"extensions": [
"docx", "xlsx"
]
},
{
"icon": "/office365/office.svg",
"url": "/office365/edit/{FILEID}",
"title": {
"en": "Edit in Office 365™",
"de": "Mit Office 365™ bearbeiten"
},
"extensions": [
"docx", "xlsx"
]
}
]
```
#2573 
- test case 1:
- test case 2:
- ...
Now with external svg icon:

File actions can be defined using config settings

---

apps/files/src/components/FilesAppBar.vue

Usage of `buttonHidden` prop in `oc-search-bar`, context: https://github.com/owncloud/owncloud-design-system/pull/512/files#diff-5f4324b6a0a736af3ec6c1a6a5388987R102

Change oc-search-bar implementation, see ODS PR #512

---

apps/files/src/components/Collaborators/SharedFilesList.vue

If the shared with an entry is not group, hide parentheses
- Fixes #2442
- test case 1: Share item with user
- test case 2: Share item with group

Remove empty parentheses in shared with others list

---

apps/files/src/components/Collaborators/NewCollaborator.vue
tests/acceptance/features/webUISharingInternalGroups/shareWithGroupsEdgeCases.feature

Do not hide collaborator if another entry with the same name exists if they are not the same type.
- Fixes #2419
- test environment: Acceptance tests

Fixed existing collaborators in autocomplete

---

tests/acceptance/pageObjects/phoenixPage.js
tests/acceptance/stepDefinitions/notificationsContext.js

All the assertions from **phoenixPage** `page-objects` are moved to `respective contexts`.
CI

Refactor phoenixPage for assertion management

---

tests/acceptance/helpers/sharingHelper.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

All the assertions from sharingDialog of `page-objects` are moved to `respective contexts`.
Better Code = Life GooD
CI

Refactoring sharingDialog page-object for assertion management

---

apps/draw-io/yarn.lock
apps/files/yarn.lock
apps/markdown-editor/yarn.lock
apps/media-viewer/yarn.lock
apps/pdf-viewer/yarn.lock
package.json
yarn.lock

Upgrade all libs across the apps, except ODS (which has a bug that breaks Phoenix https://github.com/owncloud/phoenix/pull/2727#issuecomment-566599789)
None
Reduce the number of open dependabot PRs
- test case 1:
- test case 2:
- ...

Upgrade all libs except ODS

---

tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
tests/acceptance/pageObjects/sharedWithMePage.js
tests/acceptance/stepDefinitions/sharingContext.js

All the assertions from **sharedWithMePage** `page-objects` are moved to `respective contexts`.
CI

Assertion refactor shared with me page

---

tests/acceptance/features/webUIFiles/createFile.feature
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

Remove duplicate methods to create new file in the acceptance test
- Fixes #2710 
This PR removes the duplicate methods present for the creation of files in the acceptance tests to make the codes tidy.

Remove duplicate methods to create new file in the acceptance test

---

config.json.dist
config.json.sample
src/Phoenix.vue
src/components/ApplicationsMenu.vue
src/components/Avatar.vue
src/components/Menu.vue
src/components/MessageBar.vue
src/components/Top-Bar.vue
src/components/UserMenu.vue
src/phoenix.js
src/store/app.js
src/store/config.js
tests/acceptance/helpers/loginHelper.js
tests/acceptance/pageObjects/phoenixPage.js

- App switcher now appears on the top right, items need to be configured in config.json's "menu/items" section
- Account + Logout now appear in the new User menu on the top right under the user's avatar
- Left sidebar now only contains the current apps' menu items
Fixes https://github.com/owncloud/phoenix/issues/2650
See ticket
- test case 1:
- test case 2:
- ...

Separate app switcher from app navigation sidebar

---

.drone.starlark
.drone.yml
tests/acceptance/features/webUISharingExternal/federationSharing.feature
tests/acceptance/features/webUITrashbin/trashbinRestore.feature
tests/acceptance/helpers/backendHelper.js
tests/acceptance/helpers/sharingHelper.js
tests/acceptance/helpers/webdavHelper.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/generalContext.js
tests/acceptance/stepDefinitions/notificationsContext.js
tests/acceptance/stepDefinitions/provisioningContext.js
tests/acceptance/stepDefinitions/sharingContext.js
tests/acceptance/stepDefinitions/webdavContext.js

Implements federation sharing tests and has made following changes to the tests:
- Refactor to add `http://` if the scheme does not exist for local and remote backend.
- Refactor to not set the remote backend if it does not exist.
- Remove `retry` for local test run.
- Remove unnecessary helpers from `backendHelper` such as `getBackendUrl()` (can be accessed through `client.globals`) and `changeBackend` (which was unused).
- Refactor `runOnRemoteBackend` to take variadic arguments and pass it directly to the function (first arg).
- Track config so as to rollback for remote backends.
- Refactor `assertUserHasShareWithDetails` to accept `%...%` (percent-enclosed values).
- Use `getCurrentBackendUrl()` on `propfind` and `uploadFileWithContent`.
- Use single setup entrypoints (previously, we …

Implement all (except one) federation sharing tests

---

tests/acceptance/setup.js

asyncExecute is used in test since https://github.com/owncloud/phoenix/pull/2280
On saucelabs we often get timeouts with it
```
Error while running .executeScriptAsync() protocol action: Timeout expired waiting for async script (WARNING: The server did not provide any stacktrace information)
```
so increase the timeout and hope for the best
run IE tests on this PR (usually only run nightly)

Timeouts async script

---

.drone.starlark
.drone.yml
nightwatch.conf.js

obey the `SELENIUM_HOST` env. variable even when running on saucelabs
when trying to connect from a local development machine to saucelabs (e.g. through sc-proxy) we need to be able to set the `SELENIUM_HOST` manually
run IE tests on PR

 allow to set the selenium host by env. variable when running on saucelabs

---

apps/files/src/components/FilesAppBar.vue
tests/acceptance/features/webUIFiles/breadcrumb.feature

In case the root folder has been set with no value, keep the first item in the breadcrumbs.
- Fixes #2538
1. Set the rootFolder in config.json to ""
2. Navigate into a subfolder

Display breadcrumb if rootFolder is set with no value

---

apps/files/src/components/Collaborators/AutocompleteItem.vue
apps/files/src/components/Collaborators/Collaborator.vue
package.json
src/components/Avatar.vue
src/components/UserMenu.vue
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
yarn.lock

Pass in the user display name for the fallback logic that displays
letter.
Quick fix for alignment of avatar in top bar.
Update ODS for the fix for setting avatar size.
Use avatar placeholder component also in collaborator autocomplete and list.
None raised
Top bar looking shitty without proper alignment.
Avatar placeholder had missing letters.

Include avatar placeholder in relevant places

---

apps/files/src/components/FileList.vue
apps/files/src/components/FilesLists/RowActionsDropdown.vue
apps/files/src/components/Trashbin.vue
tests/acceptance/pageObjects/FilesPageElement/filesList.js

Re-use FileList component with the virtual scroll inside of trash bin.
- Fixes #2723
- test environment: Drone

Implemented virtual scroll in trash bin

---

src/components/UserMenu.vue
tests/acceptance/features/webUIAccount/userProfile.feature
tests/acceptance/pageObjects/accountPage.js
tests/acceptance/pageObjects/phoenixPage.js
tests/acceptance/pageObjects/profilePage.js
tests/acceptance/stepDefinitions/loginContext.js

Add acceptance test to view user profile
- Fixes #2807 
- test case 1:
- test case 2:
- ...

Acceptance test to view user profile

---

.drone.star

The pipeline publish-npm-and-demo-system was not executed on tag

Build release on push event - otherwise it cannot be uploaded

---

src/phoenix.js

Register a store module even if it was imported into extension instead of required.
Don't enforce how the store is included in the extension.

Register store which is imported instead of required

---

apps/files/src/components/AllFilesList.vue
apps/files/src/components/Collaborators/SharedFilesList.vue
apps/files/src/components/FileList.vue
apps/files/src/components/Trashbin.vue

- Fixes #2726
- test case 1: Check console in all files page

Display files list only if there is at least one item

---

README.md

Add section about running acceptance tests on macOS when selenium is running in a Docker container. In that case it is not sufficient to configure `localhost` as phoenix url.
Improve clarity of setup instructions.

Add section about running acceptance tests on macOS

---

apps/files/src/components/FilesAppBar.vue
src/pages/account.vue
tests/acceptance/pageObjects/accountPage.js

Transformed spans the held the page title to actual h1 elements. In the case of the file list a h1 is existing for accessibility reasons, but can only be perceived via a screen reader (is "visually-hidden").
- Fixes #1651
Screen reader users navigate by large extent by a documents or web apps headline structure. At least one level 1 headline should exist to make the pages (routes) purpose, content or function clear.
*work in progress*

Transform route titles into real h1's, for #1651

---

tests/acceptance/helpers/config.js
tests/acceptance/helpers/httpHelper.js
tests/acceptance/helpers/occHelper.js
tests/acceptance/helpers/sharingHelper.js
tests/acceptance/stepDefinitions/generalContext.js
tests/acceptance/stepDefinitions/notificationsContext.js
tests/acceptance/stepDefinitions/provisioningContext.js
tests/acceptance/stepDefinitions/sharingContext.js

core requires now the 'OCS-APIREQUEST' header to be set in OCS requests, see https://github.com/owncloud/core/pull/36762
fix CI
:robot:

send OCS-APIREQUEST header for OCS requests in tests

---

.drone.star

Fix Changelog generator for forked repos
The changelog clone step clones the working repo and checks out the source branch.
If you are merging a branch from a forked repo, the repo slug is different.
Drone CI

Fix Changelog generator for forked repos

---

apps/draw-io/src/app.js
apps/files/src/components/FilesAppBar.vue
apps/markdown-editor/src/app.js
changelog/unreleased/2902

Replace "Create new" with "New" as it makes it look less cluttered when
trying to spot a matching entry.
Added changelog entry for this one and also another column header
change.
None raised, quick fix.
See description
Manual test, see screenshot

Adjust labels in "new" menu in files app

---

apps/files/src/components/AllFilesList.vue
apps/files/src/components/Collaborators/NewCollaborator.vue
apps/files/src/helpers/path.js
apps/files/src/helpers/shareTypes.js
apps/files/src/store/actions.js
apps/files/src/store/getters.js
apps/files/src/store/mutations.js
apps/files/src/store/state.js
changelog/unreleased/2877
tests/acceptance/features/webUISharingExternal/federationSharing.feature
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/filesContext.js

1. Setup a new OC 10.4 server
1. Run the script from https://github.com/owncloud/product/pull/40
1. Open Phoenix
1. Login as "bob" with password "test"
1. Browse the folders and enjoy the share indicators
Ref: https://github.com/owncloud/owncloud-design-system/pull/607
For story: https://github.com/owncloud/enterprise/issues/3701
Fixes https://github.com/owncloud/phoenix/issues/2060
Fixes https://github.com/owncloud/phoenix/issues/2894
@pmaier1 FYI

Share indicator for direct and indirect shares in file list

---

apps/files/src/components/FileSharingSidebar.vue
apps/files/src/fileSortFunctions.js
apps/files/src/helpers/textUtils.js
changelog/unreleased/2900
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

In the collaborators sidebar, the users and groups were two separate lists. This PR joins all collaborators into a single list. In oc10 the collaborators were sorted by ids (ASC), now they are sorted by displayName (lower case, ascending), on equal names, groups are shown first.
This also fixes a visual offset to the left when displaying group shares.
- Fixes https://github.com/owncloud/phoenix/issues/2900
Manual check in Chrome + Firefox and selenium tests with sharing context.

Join users and groups in collab sidebar

---

apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/mixins/collaborators.js
apps/files/src/store/actions.js
apps/files/src/store/mutations.js
apps/files/src/store/state.js
tests/acceptance/features/webUIResharing/reshareUsers.feature
tests/acceptance/features/webUISharingExternal/federationSharing.feature
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/sharingContext.js

Added share owner and resharer display for direct shares
- Added incomingShares in state, requested whenever the collaborators
panel is opened, and used to retrieve the owner and resharer
information.
- Share file owner and resharers are now displayed on top of the
collaborators list for shares from the currently selected resource
- Added skipped tests for the next steps of related features.
- Partial fix for https://github.com/owncloud/phoenix/issues/2898 (only addresses direct shares)

Added collaborator entries for owner and resharer

---

apps/files/src/components/Collaborators/AutocompleteItem.vue
apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/Collaborators/EditCollaborator.vue
apps/files/src/mixins/collaborators.js
apps/files/src/store/actions.js
changelog/unreleased/2921
src/components/Avatar.vue
src/components/UserMenu.vue
src/phoenix.js

Refactored avatar component logic to be located only in Phoenix core.
Moved spinner into the avatar component.
Adjusted spinner size to match the one of the avatar to avoid layout shifting
Fix #2921 
- test case 1:
- test case 2:
- ...

Fix avatar spinner size

---

apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/Collaborators/EditCollaborator.vue
apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/store/state.js
changelog/unreleased/2898
package.json
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js
yarn.lock

Display collaborator entries for indirect shares (inherited from parent resources) for owner and resharer.
Follow up of https://github.com/owncloud/phoenix/pull/2915
Fixes https://github.com/owncloud/phoenix/issues/2898
- visual check in collaborators panel
- acceptance tests for the new cases

Also show owner and resharer for indirect shares

---

apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
apps/files/src/default.js
changelog/unreleased/1907
tests/acceptance/features/webUIFiles/fileDetails.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js

Remaining adjustments for the links sidebar from the linked issue.
- Fixes remaining tasks from https://github.com/owncloud/phoenix/issues/1307
Make links sidebar UI fully consistent with collaborators sidebar UI.
Manually with chrome + firefox and acceptance tests in docker selenium. Stumbled upon some more reasonable test scenarios - will raise separate issues for adding those tests.

Link panel styling improvements

---

apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/FileSharingSidebar.vue
changelog/unreleased/2897
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature

The collaborators panel now has an additional section that displays the list of collaborators from outgoing shares that exist via one of the parent resources.
- Partial fix for https://github.com/owncloud/phoenix/issues/2897 (collaborators part, not links)
- manual test

Display indirect outgoing shares in collaborators panel

---

apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/FileSharingSidebar.vue

Templates of file link and sharing sidebars had minor issues regarding
- misuse of `aria-hidden` and `inert` instead of proper `v-if` or `v-show`+`aria-hidden` usage
- modifying variable directly in click binding -> moved to method
- view switching based on strings instead of constants
- a missing translation in an `aria-label`
* local Chrome and Firefox

Fix template issues in both link and sharing sidebar.

---

apps/files/docs/extensionpoints.adoc
apps/files/src/components/AllFilesList.vue
apps/files/src/components/FilesLists/StatusIndicators/DefaultIndicators.vue
apps/files/src/components/FilesLists/StatusIndicators/StatusIndicators.vue
changelog/unreleased/2895-1
changelog/unreleased/2895-2
src/store/apps.js
src/store/config.js
themes/owncloud.json

Move sharing indicators into smaller components, enable disabling of default indicators and add extension point for new indicators.
- Fixes #2895
1. Disable default indicators inside of theme
2. Create new indicators (example https://github.com/LukasHirt/phoenix-status-indicators) or add a custom indicators into already existing extension

Move sharing indicators into own component and add extension point

---

apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
apps/files/src/store/actions.js
changelog/unreleased/2897
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/stepDefinitions/publicLinkContext.js

Display indirect link shares in the links panel when link shares exist on any parent resource.
Fixes https://github.com/owncloud/phoenix/issues/2897
(the PR is based on top of the two PRs)
- manual test web UI

Display indirect shares for links

---

apps/files/src/components/Collaborators/AutocompleteItem.vue
apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/components/FilesLists/StatusIndicators/DefaultIndicators.vue
apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
tests/acceptance/pageObjects/FilesPageElement/filesList.js

- Fixes https://github.com/owncloud/phoenix/issues/2938
See https://github.com/owncloud/phoenix/issues/2938
- manual test in web UI
- Reshare/via are now respectively on the top/bottom.
- Removed section headers
- No more lock icon but empty space instead

Styling tweaks for share indicators and indirect share entries

---

apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/Collaborators/CollaboratorsEditOptions.vue
apps/files/src/components/Collaborators/EditCollaborator.vue
apps/files/src/components/Collaborators/NewCollaborator.vue
apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
apps/files/src/mixins/collaborators.js
apps/files/src/store/actions.js
apps/files/src/store/getters.js
apps/files/src/store/mutations.js
apps/files/src/store/state.js
changelog/unreleased/2937

Collaborator and link forms (adding/editing) unnecessarily trigger mutations on loading states (`SHARES_LOADING` and `LINKS_LOADING`). This causes animations for adding and removing collaborators/links to fail in the respective panels. While fixing this, some old code has been cleaned up as well.
- Fixes https://github.com/owncloud/phoenix/issues/2937
Fix animations and clean up old code.
- local in Chrome and Firefox

Fix add/remove animations for collaborators and links

---

apps/files/src/components/FileList.vue
changelog/unreleased/2974
tests/acceptance/pageObjects/FilesPageElement/filesList.js

Removed the inline file action buttons, they are now always available
under the three dots button.
Fixes https://github.com/owncloud/enterprise/issues/3740
Manual test in regular and responsive mode: the three dots button still works.

File actions now always appear in dropdown form

---

apps/files/src/components/Collaborators/NewCollaborator.vue
apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/store/actions.js
apps/files/src/store/getters.js
apps/files/src/store/mutations.js
apps/files/src/store/state.js
tests/acceptance/features/webUISharingExternal/federationSharing.feature
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/publicLinkContext.js
tests/acceptance/stepDefinitions/sharingContext.js

After making changes to shares or links in the share panel, the share indicators in the file list are now automatically updating.
Shares and links data structure used to be separated but they really come from the same API calls. In this PR we have merged the data structures together into a single state array, but kept the accessors to deliver filtered results to be able to split between user/group/remote shares and link shares.
Fixes https://github.com/owncloud/phoenix/issues/2939
- acceptance tests to confirm that the refactoring didn't break anything
- acceptance test for the indicator update ?
- manual test

Update share indicator in file row after changes in panel

---

apps/files/src/components/Collaborators/Collaborator.vue
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

Add tests for the reshare indicator in the collaborators list.
Add tests for the additional user info (aka extra fields) in the collaborators list.
None raised.
These tests were missing and their absence were discovered while working on #2918 
Acceptance tests

[tests-only] Tests for reshare and additional user info in collaborators list

---

tests/acceptance/features/webUISharingExternal/federationSharing.feature
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/stepDefinitions/sharingContext.js

Enable more tests for sharing details panel.
These were forgotten while working on #2918 
None
Forgotten tests must be enabled.
- test case 1:
- test case 2:
- ...

[tests-only] Enable tests for sharing details

---

apps/files/src/components/FileInfoVersions.vue

Added file type icon.
Removed border for buttons.
None raised
We already have other buttons without border and they look nice, so why not here as well.
Manual test

Improve design of versions tab a bit

---

package.json
yarn.lock

Upgrade ODS to most recent version so that auto-clear of input field in collaborators add view can be used. Bonus: this slightly speeds up some tests, because they were waiting for collaborator results for concatenated inputs, finding none, waiting, clearing the input field and re-enter the search. Example: `tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature:62`
- manually in Chrome and Firefox on autocomplete-field in NewCollaborators component.

Upgrade ODS to most recent version

---

changelog/unreleased/2989

Added changelog item for collection of ODS changes that directly affected Phoenix.
- Fixes https://github.com/owncloud/phoenix/issues/2989
ODS has no changelog, yet and we want to have some sort of documentation of ODS changes that affected Phoenix.
- not necessary as only changelog changes

Changelog for ODS

---

apps/files/src/components/FilesAppBar.vue
apps/files/src/components/Trashbin.vue

Use `$ngettext` instead of `$gettext` for messages with pluralization. This allows to make messages context sensitive, like `delete 1 file` and `delete 42 files` in one translation. Apparently, there are only 2 occurrences in the whole files app, where this is relevant.
Checked in easygettext that `$ngettext` is supposed to be exported to transifex as well, so I expect no problems in that matter.
Correct pluralization of messages.
Checked the two messages manually in the browser.

Use `$ngettext` for pluralization in i18n

---

apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/Collaborators/CollaboratorsEditOptions.vue
apps/files/src/components/Collaborators/EditCollaborator.vue
apps/files/src/components/Collaborators/NewCollaborator.vue
apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/components/FilesLists/StatusIndicators/DefaultIndicators.vue
apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
apps/files/src/components/Roles/RoleItem.vue
apps/files/src/components/Roles/RolesSelect.vue
apps/files/src/helpers/shareTypes.js
apps/files/src/store/getters.js
changelog/unreleased/1186-1
changelog/unreleased/1186-2
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

This fixes the remaining UI/UX issues from the linked issue.
- Showing avatars for selected collaborators on a new share and fixed styling/layouting of said collaborators in the list.
- Added sensible margins on text about missing permissions for re-sharing in the sharing sidebar.
- Fixed alignment of displayed collaborator in editing view for collaborators.
- Removed separators from the forms that were cluttering the view.
- Moved role description on role selection (links and collaborators) into the form element. Not shown below the form element anymore.
- Fixed margins on spacers between sections in both sidebar panels.
- Removed animations for the initial loading of a links or shares list. Only the changes (adding or removing a share/link) have a transition now.
- Introduced sorting by …

Collaborator panel tweaks

---

.drone.star
tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature

Splitted suite webUISharingFolderPermissionMultipleUsers
- Part of https://github.com/owncloud/phoenix/issues/2874
The test suite webUISharingFolderPermissionMultipleUsers took more than 45 minutes so it was splitted into 2 smaller suites so that CI runs with less time.
- :robot:

Splitted suite webUISharingFolderPermissionMultipleUsers

---

.drone.star
tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature

Splitted suite webUISharingFolderAdvancedPermissionsGroups into following new suites:
- webUISharingFolderPermissionsGroups
- webUISharingFolderAdvancedPermissionsGroups
Part of #2874
Test for suite webUISharingFolderPermissionsGroups took longer than 45 minutes. So, to make the CI run faster the webUISharingFolderPermissionsGroups suite is splitted. 
- :robot:

Splitted suite webUISharingFolderAdvancedPermissionsGroups

---

apps/files/src/components/AllFilesList.vue
apps/files/src/components/Collaborators/SharedFilesList.vue
apps/files/src/components/FileList.vue
apps/files/src/components/FilesAppBar.vue
apps/files/src/components/NoContentMessage.vue
apps/files/src/components/Trashbin.vue
apps/files/src/default.js
changelog/unreleased/1910
tests/acceptance/features/webUICreateFilesFolders/createFolderEdgeCases.feature
tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
tests/acceptance/features/webUIFavorites/favoritesFile.feature
tests/acceptance/features/webUIFiles/fileDetails.feature
tests/acceptance/features/webUIFiles/fileList.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/filesContext.js

Add empty folder indicator
Fixes https://github.com/owncloud/phoenix/issues/1910
- test case 1:
- test case 2:
- ...

Add empty folder indicator

---

Makefile
apps/files/src/components/Collaborators/SharedFilesList.vue
apps/files/src/store/actions.js
changelog/unreleased/3012

Fixes https://github.com/owncloud/phoenix/issues/3012
Run `make l10n-read` and see that the error is gone.

Fix l10n process

---

config.json.sample

`config.json.sample` contains a double-double quote which doesn't belong there.
Provide working sample config.

Fix malformed config.json.sample (removed double quote)

---

apps/files/src/components/FilesApp.vue
apps/files/src/components/UploadMenu.vue
apps/files/src/components/UploadProgress.vue
changelog/unreleased/3742

- Changed the layout of the upload progress to be a narrow standalone full width row below the app top bar.
- Transformed textual information into a single row below the progress bar and made it very clear that it can be clicked to show upload progress details.
- Changed layout of upload progress details list items, so that the progress bars always have the same width.
- Changed visuals of all progress bars in upload context to have a narrow outline and the percentage numbers inside of the progress bars.
- Fixed the calculation of the overall upload progress to be weighted by file sizes instead of just adding up percentages and dividing by number of uploads.
- Fixes https://github.com/owncloud/enterprise/issues/3742
Improve upload UX
- locally in chrome and firefox

Change layout and styling for upload progress

---

apps/files/src/default.js
changelog/unreleased/2746
src/Phoenix.vue
src/components/ApplicationsMenu.vue
src/components/Top-Bar.vue
src/phoenix.js
src/plugins/phoenix.js

In the sidebar is now only extension-specific navigation and into the apps switcher are automatically injected extensions which have at least one nav item. In the case that extension has only one nav item, the menu button is replaced by the name of the extension.
- Fixes #2746

Separated navigation

---

apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue

When showing the public link sidebar, the attribute lines about an active expiration date or password protection were only textual. Now they show xsmall icons as well.
UI polishing

Add icons for public link expiration and password protection

---

apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/FileOpenActions.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/components/PublicLinks/FilesDrop.vue
apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
changelog/unreleased/3032

Don't escape translations in case they contain resource name or user name. Escape everything else.

Escaping translations

---

apps/files/src/components/AllFilesList.vue
apps/files/src/components/FileList.vue
apps/files/src/components/FilesLists/RowActionsDropdown.vue
apps/files/src/components/FilesLists/StatusIndicators/StatusIndicators.vue
changelog/0.4.0_2020-02-14/2974
changelog/unreleased/2998
package.json
src/phoenix.js
yarn.lock

~~Removed uk-width-small and now using the icon width for column
alignment. This gives more space in responsive mode for the file name
column.
Removed the "More" column header label which felt redundant.
Adjusted file actions button id to not mention size any more, now that
we only have a single size.~~
- Removed uk-width-small and now using the icon width for column
alignment. This gives more space in responsive mode for the file name
column.
- Removed the "More" column header label which felt redundant.
- Adjusted file actions button id to not mention size any more, now that
we only have a single size.
- Share indicator column now always present even when indicators are not
rendered, for consistency with the header.
- On resize, copy the table body row width to the header row to make …

Fix filename column width in responsive mode

---

apps/files/src/components/FileOpenActions.vue
changelog/unreleased/3039
src/components/ApplicationsMenu.vue
src/components/UserMenu.vue

Some aria labels were set to static text while using $gettext() inside,
fixed by adding a colon in front.
None raised
Manual test by evaluating the aria-label attributes in the UI in the affected places

Fix broken aria labels

---

apps/files/src/components/FilesAppBar.vue
changelog/unreleased/3041

Fixed console warning about the search query attribute not being available
whenever the search fields are not visible, for example when
accessing a public link page.
None raised
No one likes console errors!
Open any public link and observe the console log while switching folders inside the public page.
Before: error shown about "query" param not being settable on undefined.
After: no errors :tada:

Fix console warning about search query in public page

---

tests/acceptance/features/webUIUpload/uploadEdgecases.feature
tests/acceptance/stepDefinitions/generalContext.js

Upload file when a folder with same name already exists
https://github.com/owncloud/phoenix/issues/3015
Bug reproduce for the issue https://github.com/owncloud/phoenix/issues/3015
:robot:

[Tests-only] Uploading a file with a name with same folder name exist

---

tests/acceptance/features/webUICreateFilesFolders/createFile.feature
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

Fixing test code for error message 
Fixes issue https://github.com/owncloud/phoenix/issues/3055
- The step definition was not reasonable.
- Repetition of work. 
:robot:

[Tests-only] addressing issue 3055

---

tests/acceptance/features/webUITrashbin/trashbinRestore.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/filesContext.js

- Restore files from trashbin with same name as folder
- Restore folder from trashbin with same name as file
https://github.com/owncloud/phoenix/issues/1723
- To restore file from trashbin with same name as folder
- To restore folder from trashbin with same name as file
- :robot:

[Tests-Only] Restore files and folder from trashbin with same name

---

tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/publicLinkContext.js
tests/acceptance/stepDefinitions/sharingContext.js

Function `closeSidebar()` is moved into appSideBar PageObject
appropriate placements for different PO methods and elements
- locally

[Tests-Only] Refactored closeSidebar function from PO filesList to appSideBar

---

apps/files/src/mixins.js
changelog/unreleased/2986

Display decimals in resource size column only for MBs or higher and display only once decimal instead of two.
- Fixes #2986

Display decimals only for MB and higher

---

tests/acceptance/features/webUIFiles/search.feature

Search a file in 'All Files' that has same name as a deleted file in trashbin 
#3044 
- Bug reproduced for issue https://github.com/owncloud/phoenix/issues/3044
- To search for a file in 'All Files' and delete it, which has same name as a deleted file in trashbin. 
- :robot:

[Tests-Only] Acceptance test for deleting file from search list

---

tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUIFavorites/favoritesFile.feature
tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
tests/acceptance/features/webUIFiles/breadcrumb.feature
tests/acceptance/features/webUIFiles/download.feature
tests/acceptance/features/webUIRenameFiles/renameFiles.feature
tests/acceptance/features/webUIRenameFolders/renameFolders.feature
tests/acceptance/features/webUIResharing/reshareUsers.feature
tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
tests/acceptance/features/webUITrashbin/trashbinDelete.feature
tests/acceptance/features/webUITrashbin/trashbinRestore.feature
tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
tests/acceptance/stepDefinitions/generalContext.js

Fix confusing error message step wordings
Fixes issue https://github.com/owncloud/phoenix/issues/3062
The steps looked similar so it was difficult to decide which step to use in certain scenario.
:robot:

[Tests-only] Addressing issue 3062

---

apps/files/src/components/FilesAppBar.vue
apps/files/src/mixins.js
package.json
yarn.lock

Since we now include the "path" library, we don't need the "join-path"
library which only provides a subset of its features.
Fixes https://github.com/owncloud/phoenix/issues/2922
- Manual test of relevant code pieces

Replace join-path usages with the path library

---

apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/FileSharingSidebar.vue
changelog/unreleased/3808
tests/acceptance/features/webUIResharing/reshareUsers.feature
tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature
tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/stepDefinitions/sharingContext.js

Display current user in collaborators list

---

tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/sharingContext.js

Function `isSidebarTabPresent` and related methods/elements are moved into appSideBar PageObject
- locally

[Tests-Only] Moved isSidebarLinksTabPresent command into appSideBar

---

apps/files/src/mixins.js
changelog/unreleased/3047
tests/acceptance/features/webUIUpload/upload.feature
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/generalContext.js

If versioning is enabled, display "Do you want to create new version?" message.
- Fixes #3047
- test environment: Drone

Different description in overwrite dialog when versioning is enabled

---

tests/acceptance/stepDefinitions/filesContext.js

This PR fixes the error arisen due to the call of the function closesidebar of appsidebar page from fileslist page
There was an error due to the call of the function "closeSideBar" which does not exist on the filesList page but on the appSideBar page.

[Tests-Only] Use closeSideBar function of appSideBar page

---

tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/FilesPageElement/versionsDialog.js
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

1. Separate page-object for versions dialog box is created
2. related commands/elements are placed in versionsDialog
- :rabbit:

[Tests-Only] Created versionsPanel PO & moved related commands/elements

---

tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

Function `deleteShareWithUserGroup` and related methods are moved from sharingDialog PageObject into collabratorsDialog.
#2677 
- locally

[Tests-Only] Moved deleteShareWithUserGroup command into collabratorsDialog

---

tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

Function `clickCreateShare` and related methods are moved from sharingDialog PageObject into collabratorsDialog.
#2677 
Appropriate placements for different PO methods and elements.
- locally

[Tests-Only] Moved clickCreateShare command into collaboratorsDialog

---

tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

Function `clickEditShare` and related methods are moved from sharingDialog PageObject into collaboratorsDialog.
#2677 
Appropriate placements for different PO methods and elements.
- locally

[Tests-Only] Moved clickEditShare command into collaboratorsDialog 

---

apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/Collaborators/EditCollaborator.vue
apps/files/src/components/Collaborators/NewCollaborator.vue
apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/components/FilesLists/StatusIndicators/DefaultIndicators.vue
apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
apps/files/src/store/actions.js
apps/files/src/store/mutations.js
changelog/unreleased/3850
tests/acceptance/features/webUIResharing/reshareUsers.feature
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/stepDefinitions/sharingContext.js

For received shares, the resharers user display names are now shown
on top of the owner entry in the collaborators list, with a reshare
icon, instead of having their own entry in the collaborators list.
Moved reshare related tests to the reshare feature file.
- Fixes https://github.com/owncloud/enterprise/issues/3850
Based on feedback after reviewing the feature.
- manual test
- acceptance test

Resharers now visible on top of owner entry

---

tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/stepDefinitions/privateLinksContext.js

Function `copyPrivateLink()` with related methods/elements are moved from filesList to publicLinksDialog pageObject
- locally

[Tests-Only] Refactored copyPrivateLink command into publicLinksDialog

---

tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

Function `getCollaboratorsList` and `getCollaboratorsListNames` along with their related methods are moved from sharingDialog PageObject into collabratorsDialog.
#2677 
- locally

[Tests-Only] Moved getCollaboratorsList and getCollaboratorsListNames command into collabratorsDialog

---

changelog/unreleased/3858
src/components/Menu.vue

Moved sidebar navigation under top bar

---

apps/files/src/components/Collaborators/SharedFilesList.vue
apps/files/src/components/FilesLists/StatusIndicators/DefaultIndicators.vue
apps/files/src/components/FilesLists/StatusIndicators/StatusIndicators.vue
apps/files/src/store/actions.js
changelog/unreleased/2924
tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/sharedWithMePage.js
tests/acceptance/stepDefinitions/sharingContext.js

When sharing with multiple targets, they must all be listed there instead of a single entry. This is fixed by replacing the code that make share entries unique into an aggregation that has been inspired by the one used in OC core.
Also includes group shares and link shares now.
Added avatars and icons for the displayed collaborators in the column.
Fixes https://github.com/owncloud/phoenix/issues/2924
Just doing a bugfix was too boring, but also the column contents didn't look very nice, so adding avatars there was a good move IMO.
Manual test
Acceptance tests

Improve collaborators and owner columns in shared file lists

---

tests/acceptance/features/webUIFiles/search.feature
tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
tests/acceptance/features/webUITrashbin/trashbinRestore.feature
tests/acceptance/stepDefinitions/webdavContext.js

See https://github.com/owncloud/core/pull/37047
Make the trashbin acceptance test steps consistently use "in the trashbin".
CI

[Tests-Only] Change acceptance test steps to consistently say 'in the trashbin'

---

tests/acceptance/features/webUIFiles/copyPrivateLinks.feature
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/sharingContext.js

Acceptance test for 'copy current path as a permanent link' which was previously under skip tag has been unskipped.
Fixes issue https://github.com/owncloud/phoenix/issues/3072
:robot:

[Tests-Only]Unskip test for copy permalinks

---

apps/files/src/components/Collaborators/SharedFilesList.vue
apps/files/src/default.js
changelog/unreleased/3116

Adjust icon in files app navigation bar and also in the file actions
dropdown to use the group icon.
Fixes https://github.com/owncloud/enterprise/issues/3858
- test case 1:
- test case 2:
- ...

Change share icons to collaborators

---

apps/files/src/components/Collaborators/SharedFilesList.vue
apps/files/src/components/FileList.vue
changelog/unreleased/3100
tests/acceptance/pageObjects/FilesPageElement/filesList.js
webpack.dev.js

A recent library update in ODS for the recycle scroller seem to have
changed the logic or calculation of the height.
This fix accomodates for that change and restores the row height to a
correct value.
Fixes https://github.com/owncloud/phoenix/issues/3099
- test case 1:
- test case 2:
- ...

Adjust recycle scroller item size

---

tests/acceptance/pageObjects/FilesPageElement/publicLinksDatePicker.js
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/stepDefinitions/publicLinkContext.js

Function related to  setting up expiry date and associated elements are moved from `publicLinksDialog` PageObject to `publicLinksDatePicker`.
#2677 
- locally

[Tests-Only] Moved commands for setting up date for public links into publicLinksDatePicker

---

tests/acceptance/pageObjects/FilesPageElement/filesList.js

For testing, `findItemInFilesList` is used to locate those resource in webUI viewport which have to be scrolled.
Inside function `findItemInFilesList` two wrapper elements were used, and different were used to calculate `scrollDistance` and `visiblePosition`
This PR removes un-necessary wrapper defined inside the function and use functional wrapper element.
- Fixes #3089
To make CI great again
- :robot:
- (Running suite multiple times in CI) https://github.com/owncloud/phoenix/pull/3120

[Tests-Only] Used only virtualScrollWrapper inside findItemInFilesList

---

tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/publicLinkContext.js
tests/acceptance/stepDefinitions/sharingContext.js

Moved `fileActions` commands and related elements to separate PO `fileActionsMenu`
- :robot:

[Tests-Only] Added pageObject for fileActionsMenu

---

apps/files/src/components/Collaborators/AutocompleteItem.vue
apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/mixins/collaborators.js
changelog/unreleased/3130
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

Moved additional info of collaborator to own row, removed row with the type of collaborator, included type as an aria-label and refactored related tests.
- test environment: Acceptance tests

Moved collaborators additional info into own row

---

apps/files/src/components/Collaborators/Collaborator.vue
changelog/unreleased/3158

The expiration date was being set to the beginning of the day but the share expires at the end of the day instead.

Use end of the day in expiration date

---

apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/store/actions.js
changelog/unreleased/3136
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature

- Fixes https://github.com/owncloud/enterprise/issues/3852

Changed sort order for collaborators and public links

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/stepDefinitions/publicLinkContext.js

PageObject for public links date-picker is equally applicable for collaboration sharing too. So, refactors are made so that expiration PO is more general to work with.
Also, function `isExpiryDateDisabled` is adjusted to accept proper `Date` type arg.
-  fixes #3166 
- locally

[Tests-Only] Refactor expiration date picker

---

apps/files/src/components/AllFilesList.vue
apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/store/actions.js
apps/files/src/store/getters.js
changelog/unreleased/3040
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js

When open the share panel of other flat file lists like the favorites,
the collaborators list and link list are now showing the same entries like
in the "All files" list, which includes indirect shares (via) that were
previously missing.
Fixes https://github.com/owncloud/phoenix/issues/3040

Indirect share info now visible in favorite and other file lists

---

apps/files/src/components/AllFilesList.vue
apps/files/src/components/Collaborators/SharedFilesList.vue
apps/files/src/components/FileList.vue
apps/files/src/components/FilesLists/StatusIndicators/DefaultIndicators.vue
apps/files/src/components/Trashbin.vue
changelog/unreleased/3163

Aligned columns to the right and hide indicators which are inactive.
- Fixes #3036
Easy comparison between rows for the user.

Align columns to right

---

tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

Acceptance test added for changing existing expiration date of an existing user/group share
- Part of #3132
- locally

[Tests-Only] Added acceptance test for changing existing expiration date on collaborator share

---

apps/files/src/components/Collaborators/SharedFilesList.vue
changelog/unreleased/3137
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature

The collaborators appears a the column in the "shared with others" section are now sorted: first by share type (user, group, remote, link) and then by display name using natural sort.
Additionally, if there is more than one public link for the resource, the text "Public" only appears once in the collaborators column.
Fixes https://github.com/owncloud/phoenix/issues/3137
- manual test in UI
- acceptance test
None

Sort collaborators column, deduplicate public

---

tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/publicLinkContext.js
tests/acceptance/stepDefinitions/sharingContext.js

Acceptance test added for enforced expiration date on a user/group share
- Part of #3132
- locally

[Tests-Only] Add acceptance tests for enforced expiration on collaborators share

---

webpack.dev.js

Disable symlink resolution in webpack to prevent it to try and linkt the
minified files from the linked node modules.

Fix issue when debugging ODS with yarn link

---

package.json
yarn.lock

Brings in a fix for OcIcon to refresh when updating its url property.

Update ODS to 1.1.1

---

apps/files/src/components/AllFilesList.vue
apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/FileList.vue
apps/files/src/components/FilesLists/RowActionsDropdown.vue
apps/files/src/store/actions.js
changelog/unreleased/3214

When using OCIS as backend, the ids of resources is a string instead of
integer. So we cannot embed those into DOM node ids and need to use
another alternative. This fix introduces a unique listId which is only
there to provide uniqueness across the current list and should not be
used for any data related operation.
This fixes the file actions menu when using OCIS as backend.
Fixes https://github.com/owncloud/phoenix/issues/3214
Fixes https://github.com/owncloud/ocis-phoenix/issues/51
Manual test with OCIS backend (see https://github.com/owncloud/phoenix/pull/3212 for setup)
Manual test with OC 10 backend just in case, also to test the "stime" sorting change which can currently only be tested with OC 10.

Use alternative temporary ids for uniqueness in views

---

.drone.star
tests/drone/identifier-registration.yml

In CI right now we use the ocis binary to run phoenix service for acceptance tests. This PR changes that to ocis-phoenix binary so that we can catch error even earlier.

[Tests-only] Use ocis-phoenix for running tests in drone

---

apps/files/src/components/FileItem.vue
changelog/unreleased/3274

Follow up on #3187. The first char of etag was being removed when stripping away double quotes.

Do not remove first char in etag

---

tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/FilesPageElement/filesRow.js
tests/acceptance/stepDefinitions/filesContext.js

Function `markAsFavorite` and related methods/elements are moved into filesRow PageObject
- locally

[Tests-Only]Moved markAsFavorite command into filesRow

---

changelog/unreleased/logout_redirect_uri.md
src/services/auth.js

ocis-konnectd has several trusted redirect urls. They don't have a trailing slash.
When we logout in phoenix konnectd tries to verify if the provided redirect uri from phoenix is trusted. But since the provided uri contains a trailing slash it doesn't match the configured once.
So the solution is to remove the trailing slash 
Fix logout
locally

remove trailing slash from redirect uri

---

tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

A new test scenario has been added to check for the error message in contributor share with respect to the changes made in https://github.com/owncloud/phoenix/pull/3241
locally

[Tests-Only]Test for share error message

---

apps/media-viewer/src/Mediaviewer.vue
changelog/unreleased/fix_media_viewer_on_private_pages.md

I've made the mediaviewer app depend only on this.isAuthenticated instead of this.publicPage().
publicPage() is always true because (at least I assume so) it's rendered in its own route that is always public. In my tests I could use isAuthenticated to determine whether it was loaded from a private page or from a public link e.g.
It feels hackish, happy to hear if there's a better API to use.
- Fixes https://github.com/owncloud/phoenix/issues/3287
- test case 1: I looked at the picture from regular files view
- test case 2: I looked at the file from public link view
- ...

Fix media-viewer on private pages

---

apps/files/src/components/FilesApp.vue
apps/files/src/fileactions.js
apps/media-viewer/src/Mediaviewer.vue
apps/media-viewer/src/app.js
apps/media-viewer/src/mixins/loader.js
changelog/unreleased/app_state_in_urls.md
src/plugins/phoenix.js

Hey everyone,
I'm sorry this PR addresses a bunch of separate issues/topics at once.
I wanted to figure out what can be done and what is possible in which scope. I would like to discuss the overall approach here, if desired I can send more fine grained PRs for individual aspects.
Commits can obviously still be cleaned up a bit :) 
Loader is also obviously a stupid name for the mixin, any better ideas?
I specifically tried to encapsulate all folder loading logic there so it can be reused in other apps, what do you think about that? Where could we put that? 
This includes the commit from #3288.
This PR adds state to app routes (i.e. the context from which they were opened and the file they open). They are accessible as `contextRouteName` and `filePath`.
Moreover it adds a local history to …

mediaviewer: add state to urls

---

apps/files/src/components/Collaborators/EditCollaborator.vue
apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
apps/files/src/store/actions.js
changelog/unreleased/3176
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/publicLinkContext.js
tests/acceptance/stepDefinitions/sharingContext.js

As pointed out in the linked issue we were not showing errors when saving shares in an invalid state. Instead we were going back to the sidebar panel, leaving the user with the impression that the share was saved successfully. Now we show errors that were raised when saving the share - same style as in the public link editing sidebar panel.
While fixing this I noticed, that the public link editing sidebar panel didn't react properly to forced expiration dates anymore (calendar plugin was not picking up the enforced date and the input field was missing the `(required)` label). So I fixed that as well and applied the same (code) style as in the collaborators editing sidebar panel.
- Partially fixes https://github.com/owncloud/phoenix/issues/3176
Saving shares should show errors if any were …

Fix share expiration date change

---

apps/files/src/components/FilesAppBar.vue
apps/files/src/components/ocDialogPrompt.vue
changelog/unreleased/1906
package.json
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/pageObjects/phoenixPage.js
yarn.lock

Make error messages in dialog prompts less annoying.
Within the dialog prompt for several small tasks (e.g. creating a new folder) there are three things changed:
1. the error message is now shown below the input field, using new properties from `oc-text-input` in ODS.
2. the changes on error messages are debounced for 400 milliseconds. As a result error messages that would appear during typing (like if you type a folder name which contains a blank in between two words) are not shown at all (if you type more than 1 character every 400 milliseconds).
- Fixes https://github.com/owncloud/phoenix/issues/1906
UX improvement

Dialog prompt message fix

---

apps/files/src/components/ocDialogPrompt.vue
changelog/unreleased/3342

Somehow the old `oc-alert` snuck in in the dialog prompt. When squashing the recent PR which added the new error message in `oc-text-input` I dropped a commit - I suppose that removing the old `oc-alert` was part of that commit and I've probably missed that... This PR fixes the dialog prompt by removing it again.
Dialog prompt shows the error message twice right now. Once within the oc-text-input component and once as an alert below. Obviously the alert has to be removed.
Locally in Chrome and Firefox.

Remove obsolete (and duplicate) error alert

---

webpack.common.js

Resolve path of src folder in `include` in babel-loader.
- Fixes #3338

Transpile with babel only src folder in core

---

tests/drone/identifier-registration.yml

for the logout to work correctly with kopano, we need the `/` at the end of the uri
avoiding future confusion
:robot:

[Tests-only] add slash at the end of redirect_uri to allow correct logout

---

apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
apps/files/src/store/actions.js
changelog/unreleased/3297
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/stepDefinitions/publicLinkContext.js

owncloud-js-client was parsing empty link name xml attribute as empty object. Empty object was changed with an empty string in store action.
Also, now FileLinkSidebar shows token string as name for the link shares without a name.
- Fixes #2517 
- Tested with issue steps.

show token string if link name is empty in FileLinkSidebar

---

changelog/unreleased/3376
src/components/Top-Bar.vue

With the edge case of a broken app in config.json, the top bar is broken, because `appInfo` can't be loaded. This PR makes ocis-web more robust by just showing the extension id when the appInfo is not available.
Make ocis-web more robust.
Locally with chrome and firefox.

Fix extension name for top bar on broken applications

---

apps/files/src/store/actions.js
apps/files/src/store/mutations.js
changelog/unreleased/3266
tests/acceptance/features/webUIFiles/search.feature
tests/acceptance/stepDefinitions/filesContext.js

Deleted file removed from `filesSearched` state by adding a new mutation. Also, filter condition in remove file mutations changed from object reference to unique file id.
- Fixes https://github.com/owncloud/phoenix/issues/3044
- Fixes https://github.com/owncloud/phoenix/issues/3043
Applied the described steps in the issues.

remove deleted files from search result

---

.drone.star

CI failed when trying to make a screenshot, seems to be an issue in chromedriver, see https://github.com/SeleniumHQ/selenium/issues/8218
reverting selenium to 3.141.59-20200326
make CI stable agail

[Tests-only] revert selenium chrome docker image to 3.141.59-20200326

---

package.json

I added engines information in package.json so other developers know which node version to use. This was after one of my colleague tried with node 14 and spent some time thinking about what the issue was.
I think it's a bit overkill to create an issue for this?
Developers trying to run phoenix with the wrong node version and spend a lot of time trying to figure out what is wrong in their setups.
Only information added, project builds.
Updated information.
-  Unit tests added - can't add unit tests for this
-  Acceptance tests added - can't add acceptance tests for this

Add engines information

---

apps/files/src/components/AllFilesList.vue
apps/files/src/components/FilesLists/Indicators.vue
changelog/unreleased/3324

When clicking on a share indicator inside a file list row, the correct share panel will now be displayed.
Fixes https://github.com/owncloud/phoenix/issues/3324
Manual test

Fix share indicators click to open the correct panel

---

changelog/unreleased/3454
config.json.sample-ocis

With oCIS, everything has to run through the proxy (not critical now, but in the near future, when we need the proxy to append data to request headers). Changed default config for oCIS to reflect that.
- by running ocis single binary with env variable `PHOENIX_WEB_CONFIG` set to the `config.json.sample-ocis` file.

Configure ocis proxy as default entry point

---

docs/testing.md
package.json

`--network=host` option does not work in Mac https://docs.docker.com/network/host/

[Test-only] Create selenium command with port forwarding for mac

---

tests/acceptance/features/webUICreateFilesFolders/createFolderEdgeCases.feature
tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUIFiles/fileList.feature
tests/acceptance/features/webUIRenameFiles/renameFiles.feature
tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
tests/acceptance/features/webUIRenameFolders/renameFolders.feature
tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
tests/acceptance/features/webUIUpload/uploadEdgecases.feature

Unskip ocis related tests skipped due to https://github.com/owncloud/ocis-reva/issues/122
- Fixes https://github.com/owncloud/ocis-reva/issues/122

[Tests-Only] Unskip tests for renaming and file list

---

tests/acceptance/features/webUIUpload/upload.feature
tests/acceptance/stepDefinitions/webdavContext.js

Instead of doing an illegal GET request use PROPFIND instead.
Extracted from https://github.com/owncloud/phoenix/pull/3457

[Tests-only] Fix folder existence check in tests

---

.drone.star
.gitignore
tests/acceptance/features/webUIUpload/upload.feature
tests/acceptance/features/webUIUpload/uploadEdgecases.feature

Reverts owncloud/phoenix#3443, the problem should be fixed through https://github.com/cs3org/reva/pull/734 which was updated in ocis-reva through https://github.com/owncloud/ocis-reva/pull/192

[Tests-only] Reenable upload related tests

---

tests/acceptance/features/webUIUpload/upload.feature
tests/acceptance/helpers/webdavHelper.js
tests/acceptance/stepDefinitions/webdavContext.js

Replaced depth:2 with depth:infinity for gathering deep folder contents
Fixes https://github.com/owncloud/phoenix/issues/3458

[Tests-only] Fix invalid depth header for recursion

---

changelog/unreleased/3484-1
changelog/unreleased/3484-2
config.json.sample-ocis
package.json
src/Phoenix.vue
src/store/index.js
src/store/settings.js
src/store/user.js
yarn.lock

This PR depends on https://github.com/owncloud/owncloud-sdk/pull/475, so this has to stay WIP until the SDK-PR is merged and released.
We have a settings service, that is supposed to be integrated in Phoenix like described [in the docs](https://owncloud.github.io/extensions/ocis_settings/)
This PR uses settings values, coming from the settings service, to adapt the Phoenix UI for the authenticated user. At the moment, only the `language` setting is used: Changing the language in the settings frontend (has to be configured as a Phoenix app) results in having another language in Phoenix. In the future we can make use of this for a variety of customization:
- chosen theme
- notification preferences
- preferences regarding the shown elements in the files list (e.g. different quick actions)
- …

Fetch settings values from sdk and use language code

---

apps/files/src/mixins.js
changelog/unreleased/3377

Aligns with the behavior of OC 10 which itself was aligned with the
behavior of the desktop client.
Fixes https://github.com/owncloud/phoenix/issues/2969
See https://github.com/owncloud/phoenix/issues/2969

Send mtime with uploads

---

apps/files/src/mixins.js
changelog/unreleased/3568
src/plugins/upload.js

Use the chunk size from the capabilities if it is higher than the
locally configured one.
Use HTTP method override mode if the TUS capabilities says so.
For https://github.com/owncloud/ocis-reva/issues/177.
Requires https://github.com/owncloud/ocis-reva/pull/228 for testing the capabilities
Requires https://github.com/cs3org/reva/pull/792 for testing the method override.
I've tested with the above PRs and the upload is using the correct chunk value and is also setting `overridePatchMethod` whenever the matching capability is set.
Note: merging this should be safe due to default values.

Use chunk size and method override from caps

---

apps/files/src/components/FilesAppBar.vue
src/Phoenix.vue
src/components/SearchBar.vue
src/components/Top-Bar.vue
tests/acceptance/pageObjects/phoenixPage.js

Moved search bar from app bar into top bar

Search bar in top bar

---

apps/files/src/components/FilesApp.vue
apps/files/src/mixins/deleteResources.js
changelog/unreleased/trashbin-delete-confirmation-question-mark

Follow up on #3378. The mentioned PR got merged before addressing comments about `self` key in data and missing question mark. This PR fixes that.

Add missing question mark in trashbin delete dialog

---

apps/files/src/components/AllFilesList.vue
apps/files/src/components/FilesLists/Indicators.vue
changelog/unreleased/unite-status-indicators

Merge direct and indirect status indicators in the files list to one indicator.
The important information for the user is that the file is shared. If it is direct or indirect comes secondary and so it doesn't necessarily need to be visible at first glance. By uniting those two indicators we are saving space and removing one additional feature that the user might need to learn. The difference between the shares is still available in the sidebar.

Unite direct and indirect indicators

---

changelog/unreleased/dynamic-nav-items
src/Phoenix.vue
src/phoenix.js
src/store/index.js
src/store/navigation.js

NavItems now live in a `navigation` store module in phoenix core. They are internally separated into static and dynamic navItems. Static is for the navItems loaded from an extension config. Dynamic is for dynamically loaded navItems (most likely from loaded data). A known limitation of this implementation is, that only statically loaded navItems (the ones coming from appInfo) lead to the extension appearing in the app switcher. As the app switcher is likely to change in the near future, we can touch this separately.
- Fixes https://github.com/owncloud/phoenix/issues/3497 
We need dynamically loaded navItems that are based on loaded data, not on configuration.
For now with Chrome and Firefox locally, with code in settings ui depending on this change (injecting navItems through the store). …

Move navItems into a store module

---

apps/files/package.json
apps/files/src/components/AllFilesList.vue
apps/files/src/components/Collaborators/SharedFilesList.vue
apps/files/src/components/FileList.vue
apps/files/src/components/FilesLists/QuickActions.vue
apps/files/src/components/Trashbin.vue
apps/files/src/default.js
apps/files/src/quickActions.js
apps/files/yarn.lock
changelog/unreleased/load-and-display-quick-actions
src/components/MessageBar.vue
src/phoenix.js
src/store/app.js
tests/acceptance/features/webUIFiles/fileList.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/FilesPageElement/filesRow.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/publicLinkContext.js

Adding an extension point into files apps for quick actions.
By creating and exporting object called quickActions, developers can define an action which will be then displayed in the files list.

Load and display quick actions

---

tests/acceptance/pageObjects/filesPage.js

`waitForElementVisible('@newFileMenuButton', 500000)` does not make the execution to wait for 500000 ms. Here the element `newFileMenuButton` is the selector of the file menu button when it is enabled. So instead of waiting for the enabled element, I modified the code to wait for the file menu button in any state, and when it is visible wait for that element to be enabled.
- Fixes https://github.com/owncloud/phoenix/issues/3500
- https://github.com/owncloud/phoenix/pull/3584

[Tests-Only]Intermittent fails is fixed on scenario Create a folder with default name

---

changelog/unreleased/fix-empty-settings.md
package.json
yarn.lock

We've updated owncloud-sdk to version 1.0.0-638 which makes sure that an empty array gets returned whenever there are no settings values for the authenticated user. Previously having no settings values broke our detection of whether settings values finished loading.
- Fixes https://github.com/owncloud/ocis-settings/issues/24
Fixes a bug
Local chrome + firefox.

Upgrade owncloud-sdk

---

.drone.star

Use the `owncloudci/nodejs:11` docker image for all pipeline steps.
(Both `owncloudci/nodejs:10` and `owncloudci/nodejs:11` docker images are currently based on Ubuntu 16.04, but we can update that separately later e.g. https://github.com/owncloud-ci/nodejs/pull/6 )
CI

[Tests-Only] Use owncloudci nodejs 11 docker image

---

tests/acceptance/features/webUILogin/login.feature
tests/acceptance/pageObjects/ocisLoginPage.js
tests/acceptance/stepDefinitions/loginContext.js

Added acceptance test for redirect URL with state attribute and selector for the error message in `try to login with invalid credentials` has been updated
https://github.com/owncloud/phoenix/issues/3285
- locally

[Tests-Only] Test for redirect URL with state attribute

---

apps/files/src/default.js
apps/files/src/fileactions.js
changelog/unreleased/removed-sidebar-quick-access
tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/sharingContext.js

- Refs https://github.com/owncloud/product/issues/80
Cleaner code and less extension points to maintain.

Remove sidebar quickAccess extension point

---

changelog/unreleased/rework-account-dropdown
src/components/UserMenu.vue
tests/acceptance/pageObjects/accountPage.js
tests/acceptance/pageObjects/phoenixPage.js
tests/acceptance/pageObjects/profilePage.js

We've removed user avatar, user email and version from the account dropdown.
The log out button has been changed into a link.
All links in account dropdown are now inside of a list.
- Fixes https://github.com/owncloud/product/issues/82
Keep focus only on the actionable items inside of the dropdown.

Rework account dropdown

---

apps/files/src/components/FileDetails.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/components/FilesApp.vue
apps/files/src/components/FilesLists/QuickActions.vue
apps/files/src/quickActions.js
apps/files/src/store/mutations.js
apps/files/src/store/state.js
changelog/unreleased/add-collaborators-quick-action
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

Added a new quick action which opens the new collaborators tab in the files list sidebar.
- Refs https://github.com/owncloud/product/issues/80
- test environment: Acceptance tests

Add collaborators quick action

---

docs/testing.md

the path was wrong in this place 
part of https://github.com/owncloud/phoenix/issues/3633

[skip-ci] fix path of example config file in documentation

---

.drone.star
tests/drone/identifier-registration-oc10.yml
tests/drone/ocis-config.json

(build and) use single-binary ocis app when running phoenix UI tests in the phoenix app
https://github.com/owncloud/ocis/issues/303

[Tests-Only]Use single-binary ocis app for ocis tests

---

.drone.star

Specify the `ocisBranch` and `ocisCommit` to use for the drone CI pipelines that test phoenix against an OCIS server.
Part of https://github.com/owncloud/ocis/issues/303
CI

[Tests-Only] Add drone CI code to allow specifying OCIS Commit

---

apps/files/src/components/FileList.vue
apps/files/src/components/FilesAppBar.vue
changelog/unreleased/move-create-button
tests/acceptance/pageObjects/filesPage.js

Adjusted also a bit the spacing around table header.

Move create new button

---

apps/files/src/mixins.js
changelog/unreleased/file-type-icons-for-uppercase-file-extensions

Uppercase file extensions now receive proper icon
- upload file.PDF and see the proper pdf icon
Just wrong icon ...

Apply proper file type icons also for uppercase file extensions

---

apps/files/src/components/AllFilesList.vue
apps/files/src/components/Collaborators/SharedFilesList.vue
apps/files/src/components/FileItem.vue
apps/files/src/components/FileList.vue
apps/files/src/components/FilesLists/Indicators.vue
apps/files/src/components/Trashbin.vue
changelog/unreleased/move-indicators-under-resource
tests/acceptance/pageObjects/FilesPageElement/filesList.js

Better separation from quick actions -> probably only temporarily solution (will be tested with real users).

Move indicators under resource name

---

apps/files/src/components/FileDetails.vue
apps/files/src/quickActions.js
changelog/unreleased/set-default-permissions
changelog/unreleased/set-empty-object-when-resetting-current-tab

Set default perms in public link quick action and use empty object when resetting current sidebar tab
- Fixes #3675
- Fixes #3676

Fixed quick actions

---

apps/files/src/mixins.js
changelog/unreleased/public-link-keep-mtime.md

This will tell the server to set that mtime for publicly uploaded files,
when available. This aligns the implementation with the regular upload.
Found while working on https://github.com/owncloud/enterprise/issues/3883
- test case 1:
- test case 2:
- ...

Add X-OC-Mtime header for public link upload

---

apps/files/src/components/FileItem.vue
changelog/unreleased/resource-line-width

The width of the resource name in the files list was expanded over its actual content. This caused triggering the open action instead of displaying sidebar. Now the width does not exceed the content width.

Do not expand resource name width over its content

---

apps/files/src/components/FileItem.vue
changelog/unreleased/indicators-label

Instead of "State" we've started using the "Shared with" as a label for the indicators in the files list.
This is only intermediate solution because the indicators can be extended by other indicators which don't have to be related to sharing.
"State" has not been met with positive feedback.

Use 'Shared With' as a label for indicators

---

.drone.star

PR #2914 implemented tags for `skipOnOC10` `skipOnOCIS` etc.
https://github.com/owncloud/phoenix/pull/2914/files#diff-74dc60589e0610c07e491b31f8693b2bR75
But it had the wrong logic for the iPhone resolution pipeline. This resulted in no test scenarios actually being run in that pipeline.
Note: the XGA pipeline has it correct
https://github.com/owncloud/phoenix/pull/2914/files#diff-74dc60589e0610c07e491b31f8693b2bR66
CI

[Tests-Only] Actually run acceptance test scenarios in iPhone resolution

---

apps/files/src/components/FilesAppBar.vue
changelog/unreleased/fix-breadcrumb.md
tests/acceptance/features/webUIFiles/breadcrumb.feature
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

This PR removes the anchor on the last breadcrumb segment.
- Fixes https://github.com/owncloud/phoenix/issues/3722
- Partly fixes https://github.com/owncloud/phoenix/issues/1883
Comply with common sense
- locally in chrome and firefox

Fix breadcrumb last element

---

apps/files/src/components/FileDetails.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/mixins.js
src/store/modal.js

Using Nullish coalescing operator and optional changing resulted in syntax errors in translations sync.
- Refs #3603
Passing translations sync
Run `make l10n-read`

Stop using nullish coalescing operator and optional chaning

---

.drone.star

With this PR
Existing bug on osixia openldap https://github.com/osixia/docker-openldap/issues/198

[Tests-Only] Updated openldap to 1.4.0

---

.drone.star

PR #3738 bumped `osixia/openldap` to 1.4.0
Actually we can unpin the version so that we get whatever is the latest docker image. That way we do not have to mess about checking and updating the version ourselves in the future.

[Tests-Only] Unpin osixia/openldap version in CI

---

apps/pdf-viewer/src/PdfViewer.vue
apps/pdf-viewer/src/app.js
changelog/unreleased/file-editors-path
src/store/apps.js

When opening a file in a editor or a viewer the path was falling back to an appId.
This made it impossible to navigate via the file actions into an app which doesn't have duplicate appId in the route.
We've stopped falling back to this value and in case that the route of the file action is not defined, we use the root path of the app.
- Fixes https://github.com/owncloud/ocis/issues/356
- Refs https://github.com/owncloud/product/issues/69
- open pdf file
- open md file

Do not fallback to appId if the file action route is not defined

---

apps/files/src/components/FilesApp.vue
changelog/unreleased/files-list-outline

The files list was displaying an outline when it received focus after a click.
Since the focus is meant only programmatically, the outline was not supposed to be displayed.
- Fixes #3747
- Fixes #3551
Click on a row in files list or in the header whitespace.

Remove outline around files list

---

apps/files/src/components/FileDetails.vue
apps/files/src/default.js
apps/files/src/fileactions.js
changelog/unreleased/favorites-capabilities
src/store/navigation.js

We've added a check of favorites capabilities to enable disabling of favorites list and favorite action.
- Refs https://github.com/owncloud/ocis/issues/354
- Requires https://github.com/owncloud/core/pull/37673

Add favorites capabilities

---

apps/files/src/components/LocationPicker/LocationPicker.vue

I forgot and sneaked in an optional chaining operator again even though it fails the translation sync. This PR removes it.
- Refs #3603
Make translations sync job green again
Run `make l10n-read`

Do not use optional chaining in location picker

---

docs/releasing.md

- test case 1:
- test case 2:
- ...

Add docs for releasing Phoenix assets

---

changelog/unreleased/docs-releasing.md
docs/releasing.md

This PR fixes a few typos from the most recent documentation changes.

Fix typo in docs

---

tests/acceptance/features/webUIFiles/copy.feature
tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/locationPicker.js
tests/acceptance/stepDefinitions/filesContext.js

This PR adds acceptance tests to move/copy to a folder where a user does not have enough permissions.
- https://github.com/owncloud/phoenix/issues/3750
CI

[Tests-Only] Add acceptance tests to move files/folders into a folder with no change permissions

---

tests/acceptance/features/webUIFiles/breadcrumb.feature
tests/acceptance/features/webUIFiles/copy.feature
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

This PR adds acceptance tests for breadcrumbs with double quotes and edits selector accordingly
- Fixes https://github.com/owncloud/phoenix/issues/3734

[Tests-Only]Add acceptance tests for breadcrumbs with double quotes

---

apps/files/src/components/FileItem.vue
changelog/unreleased/remove-shared-with

;)
Please check whether that works ^_^
Closes https://github.com/owncloud/product/issues/123
Closes https://github.com/owncloud/ocis/issues/408

Remove "Shared with:" from file list rows

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/helpers/sharingHelper.js

Run public link tests on ocis
- Fixes https://github.com/owncloud/phoenix/issues/3755
- Part of https://github.com/owncloud/ocis/issues/400
- https://github.com/owncloud/ocis/pull/382

[Tests-Only] Access last created public link with OCIS

---

apps/media-viewer/src/Mediaviewer.vue
apps/media-viewer/src/app.js
changelog/unreleased/media-viewer-presigned-urls
changelog/unreleased/media-viewer-presigned-urls copy
package.json
yarn.lock

Enable previewing videos in media viewer. This is POC. There are still missing features which need to be implemented.

Play videos in media viewer

---

.drone.star
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature

https://github.com/owncloud/openidconnect/pull/89 introduced a new setting to accept insecure certificates, so in CI use the new setting and not debug
should help with https://github.com/owncloud/phoenix/pull/3797

[tests-only] use openid-connect insecure  and not debug setting

---

.drone.star
apps/files/src/components/FileInfoVersions.vue
changelog/unreleased/url-signing.md
package.json
src/plugins/phoenix.js
yarn.lock

Get URL of the file, use sdk to pre-sign it and then download the file via it.
No need to fetch the files first.

Use pre-signed URLs to download files

---

apps/media-viewer/src/Mediaviewer.vue
apps/media-viewer/src/app.js
changelog/unreleased/media-viewer-video-playback

This PR fixes a typo in a video file extension (`webn` instead of `webm`) and renames all occurrences of `image` and `images` as variable names to `medium` and `media`, since the mediaviewer is actually about multiple media types now (images and videos).
Code readability

Media viewer video fixes

---

apps/media-viewer/src/Mediaviewer.vue
apps/media-viewer/src/mixins/loader.js
changelog/unreleased/media-viewer-presigned-urls
changelog/unreleased/media-viewer-video-playback

This PR fixes loading videos in a public context (public link) within the mediaviewer.
- Fixes https://github.com/owncloud/phoenix/issues/3832
Bugfix

Media viewer public context

---

apps/media-viewer/src/Mediaviewer.vue
changelog/unreleased/media-viewer-video-playback

This PR fixes the navigation between video elements in media viewer. When navigating back and forth between two videos, the shown video stayed the same before. Now it actually switches to the desired video.
As a bonus, this PR fixes animations. There were glitches during switching from one medium to the next/previous, where the loaded medium was shown at the bottom of the screen and then jumped back up after load. That is solved by switching the `template` to a `div` tag. Also, the animations need each element to have a unique key, otherwise the animation will not appear at all. That is solved by adding the file-id to the respective key (which was needed for videos anyway).
- Fixes https://github.com/owncloud/phoenix/issues/3831
Fixing bugs...

Media viewer video navigation

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/stepDefinitions/sharingContext.js

The test `Scenario: user edits the password of an already existing public link and tries to access with old password` was failing because two shares were created fast with the same `stime`.  So, a new function is created to wait for at least one second between the creation of shares.
- Fixes https://github.com/owncloud/phoenix/issues/3830
- :robot:

[Tests-Only]Fixed failing test on public link share

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/stepDefinitions/publicLinkContext.js

This PR runs public share tests with ocis backend
- Fixes https://github.com/owncloud/ocis/issues/400
- https://github.com/owncloud/ocis/pull/425

[Tests-Only] Run public share tests on ocis

---

changelog/unreleased/differentiate-between-id-and-username
changelog/unreleased/fix-displayname
src/Phoenix.vue
src/pages/account.vue
src/store/user.js

With oCIS user-id and username are not the same as is the case in ownCloud 10.
We've started differentiating between them to correctly display all information in the accounts page.
If the username is not available (oC10), we fall back to using user-id as the username.
- Fixes https://github.com/owncloud/ocis/issues/440
- test environment: oC10 and oCIS

Differentiate between username and user-id

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/stepDefinitions/filesContext.js

Added Acceptance test for the enabled `+ New` button on OCIS. This behavior is different than that of OC10.
- https://github.com/owncloud/product/issues/130
- :robot: 
- https://github.com/owncloud/ocis/pull/447

[Tests-Only]Added test for the existing enabled + New button on public link in OCIS

---

tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js

make the fuction to rename a file work async as other are already
https://github.com/owncloud/ocis/issues/450
nightwatch would crash ugly when `waitForElementNotVisible` fails and the reported error would not be helpful
:robot: 
trying failing test with https://github.com/owncloud/ocis/pull/409

[tests-only] make rename function in tests async

---

tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature

this PR is on top of #3944
1. check that no error messages are displayed after deleting https://github.com/owncloud/ocis/issues/451
2. create a file via webDAV API, to speed up tests, also no need to check if the file is listed, that is done in other tests
small improvements to the tests

[tests-only] Improve delete tests

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature

Tests need adjustment after https://github.com/owncloud/ocis-reva/issues/439
Enable test that was fixed by issue-ocis-reva-389.
Tagged test issue-ocis-reva-372.
Note: I deleted some test that was proving a bug as the bug is not happening any more.
However the test tagged by issue-ocis-reva-372 still doesn't fully pass as indirect shares are not working due to https://github.com/owncloud/ocis-reva/issues/372, so I let it be.

[Tests-only] Enable fixed public link deletion test

---

tests/acceptance/pageObjects/filesPage.js

make sure we wait for some ajax calls to start and then to finish
failing tests seen in https://github.com/owncloud/ocis/pulls/409
the popup might be gone, but the DELETE calls are still fired and the DOM is updating
:robot:

[tests-only] wait for ajax calls when batch deleting

---

tests/acceptance/stepDefinitions/filesContext.js

- This PR Fixes random failure related to breadcrumb when files/folders are copied to a folder
- Fixes https://github.com/owncloud/phoenix/issues/3941

[Tests-Only] Fix random failure related to breadcrumb

---

changelog/unreleased/adapt-to-settings-data-model.md
package.json
src/Phoenix.vue
src/phoenix.js
src/store/apps.js
src/store/settings.js
yarn.lock

The data model in ocis-settings has changed. Because of that we need to align our usage of it.
until that is merged, you can run `yarn build:system` in owncloud sdk on your local machine and then `yarn link` it in phoenix.

Fix settings

---

changelog/unreleased/default-external-apps-ocis.md
config.json.sample-ocis

This PR adds the accounts ui as external app for the default ocis config.json sample.

Default external apps for ocis

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature

Reverts owncloud/phoenix#3954
For https://github.com/owncloud/product/issues/161
So we can use the commit id to confirm.

Revert "[tests-only] skip public link tests on ocis"

---

apps/files/src/components/FilesApp.vue
apps/files/src/components/FilesAppBar.vue
changelog/unreleased/multi-select-info
tests/acceptance/features/webUIFavorites/favoritesFile.feature
tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js

We've added information about the number of selected items and their size above the files list next to batch actions.
- Fixes https://github.com/owncloud/product/issues/122
- Select multiple resources in different files lists.

Add info about number of selected items and their size

---

tests/acceptance/features/webUIUpload/uploadEdgecases.feature

This PR merges similar scenarios together after the skip tag was removed after the related issue is fixed
There were two similar scenarios in uploadEdgeCases feature file. One of them was previously skipped on OCIS because of an issue. After the issue was fixed, the skip tag was removed which left two similar scenarios splitted. These scenarios are therefore merged together in this PR.

merge similar scenarios together in uploadEdgeCases feature file

---

tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUIFavorites/favoritesFile.feature
tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
tests/acceptance/stepDefinitions/filesContext.js

Changed the test step `Then there should be N files/folders listed on the webUI` to `Then the count of files and folders shown on the webUI should be N`
- Fixes https://github.com/owncloud/phoenix/issues/3950
- :robot:

[Tests-Only] Changed wording of "there should be x files/folders listed on the webUI" test step

---

tests/acceptance/helpers/userSettings.js

This PR adds the default admin user of ocis-accounts to the `userSettings.js` helper.

[tests-only] Add ocis-accounts default admin user to tests

---

nightwatch.conf.js
tests/acceptance/features/webUIFavorites/favoritesFile.feature

1. by default use port 9200 as `BACKEND_HOST` for OCIS, otherwise users will not get created
2. typo in tag name

[tests-only] small fixes in the tests

---

docs/testing.md

that setting needs to be set always, we need to make sure ocis and the test-runner access the same config file

[tests-only] fix documentation about acceptance tests

---

tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature

This test blows up a test pipeline in ocis. Skipping for now to unblock merging features. Needs to be fixed soon (as in this or next sprint), as other people are reporting in the chat that they experience the same issues in real environments.
Tracked in this ticket: https://github.com/owncloud/ocis/issues/532

[tests-only] Skip a test that blows up the environment on ocis

---

docs/testing.md
package.json

This PR adjusts the testing document to run phoenix on ocis backend without ldap setup.
- Fixes https://github.com/owncloud/phoenix/issues/4034

Readjust the testing docs to run phoenix on ocis backend with no ldap setup

---

apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/Collaborators/NewCollaborator.vue
apps/files/src/components/Collaborators/SharedFilesList.vue
apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/mixins/filesListIndicators.js
apps/files/src/quickActions.js
changelog/unreleased/rename-collaborators-to-people
tests/acceptance/features/webUIFiles/fileDetails.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/sharingContext.js

Rename "collaborator" to "person".
Rename "collaborators" to "people".
Rename "Add Collaborator" to "share".
Part 1 and part 4a of https://github.com/owncloud/product/issues/231
- test case 1:
- test case 2:
- ...

Rename collaborator/s to person/people

---

apps/files/src/components/FileLinkSidebar.vue
changelog/unreleased/wording-create-public-link

The label of the button for creating public links in the links panel has been shortened to "Public link" instead of "Add public link"
since the plus sign already implies adding. An Aria label has been added for clarification when using screen readers.
Part 4b of https://github.com/owncloud/product/issues/231
- test case 1:
- test case 2:
- ...

Shortened button label for creating public links

---

apps/files/src/components/FileItem.vue
changelog/unreleased/fix-file-previews-size

Fix file preview to prevent overflowing vertically and also added CSS
property to make sure the ratio is preserved.
Fixes https://github.com/owncloud/product/issues/232
- test case 1:
- test case 2:
- ...

Make file previews properly fit

---

apps/files/src/components/FilesAppBar.vue
apps/files/src/components/Trashbin.vue
apps/files/src/default.js
apps/files/src/store/actions.js
changelog/unreleased/change-wording-trashbin
tests/acceptance/features/webUITrashbin/trashbinDelete.feature

Part 5 of https://github.com/owncloud/product/issues/231
Manual test, visually

Rename "trash bin" to the "deleted files".

---

apps/files/src/components/PublicLinks/PublicLink.vue
changelog/unreleased/fix-public-link-password-field

The UX of the public link password field has been improved.
The field is focussed automatically and the enter key submits the password.
Also, in case of wrong password, an error message is now displayed.
Part 8a of https://github.com/owncloud/product/issues/231
Manual test

Adjust behavior of public link password field

---

apps/files/src/components/FileList.vue
apps/files/src/components/PublicLinks/PublicLink.vue
apps/files/src/store/getters.js
apps/files/src/store/mutations.js
changelog/unreleased/public-link-remember-password-on-refresh

Simpler alternative to https://github.com/owncloud/phoenix/pull/4083
When refreshing the page in the file list of a public link share,
the user doesn't need to enter the password again. This only applies for the current page
and the password is forgotten by the browser again upon closing or switching to another site.
Part 8b of owncloud/product#231
After entering password on public link page:

Remember public link password on page refresh (alternative)

---

changelog/unreleased/external-links
src/Phoenix.vue
src/components/ApplicationsMenu.vue
yarn.lock

We have added an option to set the link target in external application links (defaults to `_blank`). The app switcher now shows all native extensions first and items based on application links last.
- Fixes https://github.com/owncloud/product/issues/227
Make switch between classic and new frontend as easy as possible.
✋

Improve oc10 link

---

apps/files/src/fileactions.js
changelog/unreleased/default-action

Align wording for opening PDFs with file actions involving extensions (`Open in Mediaviewer` etc).
Consistent naming.

Change wording of file action for opening PDFs in browser

---

.drone.star
tests/acceptance/helpers/httpHelper.js
tests/acceptance/stepDefinitions/generalContext.js
tests/acceptance/stepDefinitions/provisioningContext.js

Improve error handling in test code for creating users and reading config file.
- Fixes https://github.com/owncloud/phoenix/issues/4035
:robot:

[Tests-Only] Improve error handling in tests and update ocis commit id

---

apps/files/src/components/AllFilesList.vue
apps/files/src/components/Collaborators/NewCollaborator.vue
apps/files/src/components/Collaborators/SharedFilesList.vue
apps/files/src/components/FileList.vue
apps/files/src/components/FilesApp.vue
apps/files/src/components/Trashbin.vue
apps/files/src/store/actions.js
apps/files/src/store/mutations.js
changelog/unreleased/files-list-loader

We removed the oc-loader component at the top of the different variations of the files list view and introduced a spinner + one line of text to the center of the screen.
Drone

Files lists loading state

---

.drone.star
tests/acceptance/features/webUISharingPermissionToRoot/shareAdvancePermissionsGroup.feature
tests/acceptance/features/webUISharingPermissionToRoot/shareFileWithMultipleUsers.feature
tests/acceptance/features/webUISharingPermissionToRoot/shareFolderWithMultipleUsers.feature
tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFileGroup.feature
tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFoldersGroup.feature
tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsUsers.feature
tests/acceptance/features/webUISharingPermissionToRoot/sharedFolderWithMultipleUsersAdvancedPermissions.feature

Refactor webui test scenarios for using the Shares folder and root folder for shares.
Shares in ocis are received in Shares folder by default. To test that we need this refactor.
:robot:

[Tests-Only] refactor permission tests for shares folder

---

tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature

Refactor webui test scenarios for using the Shares folder and root folder for shares.
Shares in ocis are received in Shares folder by default. To test that we need this refactor.
:robot:

[Tests-Only] Refactor restrict sharing and auto completion tests

---

.drone.star
tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroupsEdgeCases.feature

Refactor webui test scenarios for using the Shares folder and root folder for shares.
Shares in ocis are received in Shares folder by default. To test that we need this refactor.
:robot:

[Tests-Only] refactor sharing with groups tests for shares folder

---

.drone.star
tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
tests/acceptance/helpers/sharingHelper.js
tests/acceptance/stepDefinitions/sharingContext.js

Refactor webui test scenarios for using the Shares folder and root folder for shares.
Shares in ocis are received in Shares folder by default. To test that we need this refactor.
:robot:

[Tests-Only] refactor federation sharing tests for shares folder

---

.drone.star
tests/acceptance/features/webUISharingNotificationsToRoot/notificationLink.feature
tests/acceptance/features/webUISharingNotificationsToRoot/shareWithGroups.feature
tests/acceptance/features/webUISharingNotificationsToRoot/shareWithUsers.feature

Refactor `webUISharingNotifications` to use Root and Shares folder for shares.
- Part of https://github.com/owncloud/ocis/issues/518
- CI

[Tests-Only] Refactor webUISharingNotifications to use Shares folder

---

apps/files/src/components/FileList.vue
apps/files/src/default.js
changelog/unreleased/user-menu.md
src/Phoenix.vue
src/components/ApplicationsMenu.vue
src/components/Top-Bar.vue
src/components/UserMenu.vue
src/mixins/navigationMixin.js
src/pages/account.vue
src/store/navigation.js
src/store/user.js
tests/acceptance/features/webUIAccount/logout.feature
tests/acceptance/pageObjects/accountPage.js
tests/acceptance/stepDefinitions/accountContext.js

This PR makes navigation items customizable with regard to which menu they appear in. By default, anything appears in the app switcher. You can define a `menu: "user"` in applications in config.json or in the exported navItems of applications. With a separate PR for ocis, the settings and accounts UI will appear in the user menu by default.
Also:
- We took the chance to add icons to menu items and rename the `Manager your account` menu item to `Profile` - which is a better fit, because it just shows read only information.
- We replaced the `Logout` button on the profile page with an `Edit` button which links to the oc10 personal settings if those are available and to the settings UI if that is available.
In case you want to add a nav item to the user menu manually, you can do so via the …

Customizable user menu

---

changelog/unreleased/login-autoredirect
src/pages/login.vue
src/phoenix.js
src/store/config.js
tests/acceptance/features/webUILogin/login.feature
tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature
tests/acceptance/helpers/loginHelper.js
tests/acceptance/pageObjects/ocisLoginPage.js
tests/acceptance/pageObjects/ownCloudAuthorizePage.js
tests/acceptance/stepDefinitions/loginContext.js
themes/owncloud.json

We've added a key into the theme to enable auto-redirect to the IdP when entering ocis-web instead of displaying the login page first. The default value is set to true.

Enable autoredirect to IdP

---

.drone.star

MySQL and oc10 are not needed for the ocis related tests
- Fixes  #4148
use less :electric_plug: , safe the :earth_asia: 
:robot:

[tests-only] don't run DB & oC service when testing ocis

---

l10n/Makefile

Transifex job is broken because pdf-viewer doesn't exist anymore.

Remove pdf-viewer from transifex job

---

changelog/unreleased/default-apps-in-example-configs
config.json.sample-oc10
config.json.sample-ocis

We only want to have "files" and "media-viewer" as default apps in the example configs.

Default apps in example configs

---

apps/files/src/store/actions.js
changelog/unreleased/flashy-messages-when-loading-folders

It seems that the `finally` method was being called too early. Moving the switch of loading into `then` and `catch` solved the flashy empty folder messages.
- Fixes https://github.com/owncloud/product/issues/263

Move folder loading switch outside of finally method

---

.drone.star
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
tests/acceptance/helpers/sharingHelper.js
tests/acceptance/helpers/userSettings.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/generalContext.js
tests/acceptance/stepDefinitions/provisioningContext.js
tests/acceptance/stepDefinitions/sharingContext.js

Enable sharing tests for `webUISharingInternalUsers` and `webUISharingPermissionsUsers` suites in CI.
More tests=less bug
:robot:

[CI] enable files sharing tests for ocis

---

tests/acceptance/stepDefinitions/provisioningContext.js

`userId` is a single value array e.g. `[user1]`, to transform it into a string before sending it to the next function
`join()` function fails with `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array`
:robot:

[tests-only] make sure userId is used as string

---

.drone.star
tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature

- tag the tests with the correct issue id (the main reason these tests will not run is the lack of group sharing)
- still add the tests to the CI pipeline, so they don't get forgotten when they will be enabled one day
part of https://github.com/owncloud/ocis/issues/518

[tests-only]  add webUISharingAutocompletion to drone-CI

---

.drone.star
tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature

1. make multiuser / sharing permission tests demonstrate and work despite owncloud/product#203 & owncloud/ocis#717
2. enable sharing permission suites to run in CI (
part of owncloud/ocis#518
1. make tests work to avoid further regressions
2. have tests that demonstrate the current behaviour
3. even some suites don't have any actual tests, we will not forget them to add to drone when tests are enabled
:robot:

[tests-only] enable sharing permission tests

---

tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/stepDefinitions/provisioningContext.js

1. make sharing with user tests demonstrate and work despite owncloud/product#203
1. adjust one test, so it does not fail because of https://github.com/owncloud/ocis/issues/719 (in that test the renaming is not essential to the test, and the test does not check the renaming)
1. small improvement is error output
part of owncloud/ocis#518
1. make tests work to avoid further regressions
2. have tests that demonstrate the current behaviour
:robot:

[tests-only] add tests demonstrating issue-product-203 in shareWithUsers scenarios

---

changelog/unreleased/fix-logout
src/components/UserMenu.vue
src/services/auth.js
src/store/user.js

Open signout URL directly.
- Fixes https://github.com/owncloud/product/issues/266

Fix logout with OIDC

---

tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/filesContext.js

when checking that an item does not exist, the code returned too early (before the list got rendered) and also did not scroll down trying to find the item. To reduce false-positives use the existing `waitForFileVisible` method
:robot:

[tests-only] improve waiting when checking the not-existance on an item

---

tests/acceptance/features/webUIFiles/copy.feature
tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
tests/acceptance/features/webUIRenameFolders/renameFolders.feature
tests/acceptance/stepDefinitions/filesContext.js

Rephrase `the following file/folder should be listed on the webUI` step
- Fixes https://github.com/owncloud/phoenix/issues/4215
- :robot:

[Tests-Only] Rephrase "following file should be listed on the webUI" step

---

.drone.star
tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
tests/acceptance/stepDefinitions/filesContext.js

test public links with OCIS backend in CI
part of owncloud/ocis#518
fixes #4213
1. make tests work to avoid further regressions
2. have tests that demonstrate the current behaviour
:robot:

[tests-only] run public link tests on OCIS in CI

---

apps/draw-io/src/DrawIoEditor.vue
apps/files/src/components/AllFilesList.vue
apps/files/src/components/FilesAppBar.vue
apps/files/src/components/LocationPicker/LocationPicker.vue
apps/files/src/components/Trashbin.vue
apps/files/src/fileactions.js
apps/files/src/mixins.js
apps/files/src/mixins/deleteResources.js
apps/files/src/quickActions.js
apps/files/src/store/actions.js
apps/media-viewer/src/mixins/loader.js
changelog/unreleased/autoclose-alerts
src/components/Notifications.vue
src/components/SearchBar.vue
src/plugins/phoenix.js
src/store/app.js
src/store/settings.js

We've added a property which enables alerts to be automatically closed.
When enabling the auto-close, it will get assigned timeout of 5 seconds.
Default timeout can be overwritten inside of the `autoClose` object.
- Fixes https://github.com/owncloud/owncloud-design-system/issues/766

Add auto-close capability to alerts

---

apps/files/src/components/Collaborators/CollaboratorsEditOptions.vue
apps/files/src/components/Collaborators/EditCollaborator.vue
apps/files/src/components/FileSharingSidebar.vue
apps/files/src/helpers/collaboratorRolesDefinition.js
apps/files/src/helpers/collaborators.js
apps/files/src/mixins/collaborators.js
apps/files/src/store/actions.js
changelog/unreleased/share-permission
src/pages/account.vue
src/store/app.js
tests/acceptance/features/webUIResharing/reshareUsers.feature
tests/acceptance/features/webUIResharingToRoot/reshareUsers.feature
tests/acceptance/features/webUISharingExternal/federationSharing.feature
tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature
tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
tests/acceptance/features/webUISharingPermissionToRoot/shareFileWithMultipleUsers.feature
tests/acceptance/features/webUISharingPermissionToRoot/shareFolderWithMultipleUsers.feature
tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFileGroup.feature
tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFoldersGroup.feature
tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsUsers.feature
tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature

We've attached the share permission of collaborators to roles. There is no longer a share additional permission. In oCIS, the share permission is hidden as it is not yet possible to enable re-sharing.

Attach share permission to roles

---

nightwatch.conf.js
tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
tests/acceptance/helpers/navigationHelper.js
tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/phoenixPage.js
tests/acceptance/pageObjects/publicLinkPasswordPage.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/sharingContext.js

1. when waiting for something that should not be there use shorter timeouts
2. don't wait so long for the progress-bar to appear (it might have been there but gone again)
3. in mobile view the breadcrumbs are completely different, so don't wait for them but just for the "NEW" button to appear
4. get rid of multiple ways to check for an empty file list
5. skip a tests that fails because of owncloud/core/issues/38039 (I think it used to fail before, but the other steps would not notice)
- Fixes 4231
quicker CI runs
:robot:

[tests-only] use shorter timeout for 'should not be listed' steps

---

apps/files/src/components/UploadProgress.vue

With the recent migration to replace **uk-** styles with **oc-** styling, I found this one was missed.
See Above.
Does not affect the UI visually (in typical cases that I can see).

Updating uk-margin-remove to use oc-m-rm

---

apps/files/src/components/Collaborators/AutocompleteItem.vue
apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/Collaborators/NewCollaborator.vue
apps/files/src/mixins/collaborators.js
changelog/unreleased/collaborator-type
tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js

We've added a new line into the collaborators autocomplete and list in the sidebar to display their type.
- Closes #3804

Display collaborators type

---

tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/filesContext.js

This PR readjusts the message used for assertions in the webui tests.
- Fixes https://github.com/owncloud/phoenix/issues/4115
- CI

[Tests-Only]Adjust the assertion message for the UI tests

---

.drone.star
tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
tests/acceptance/features/webUIPreview/imageMediaViewer.feature

use the same naming and splitting of ocis tests as for oc10 tests
- Fixes  #4223
reduce confusion

[tests-only] split and name ocis suites the same as oc10 suites

---

changelog/unreleased/fix-browse-to-files-page
tests/acceptance/helpers/navigationHelper.js
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

In the selenium tests when browsing to the files list page the tests were not waiting for the files to load.
I found this issue in this PR https://github.com/owncloud/ocis/pull/638 I don't know why it worked before.
- Fixes https://github.com/owncloud/phoenix/issues/4281

[Tests-Only] fix browse to files page

---

.gitignore
changelog/unreleased/openid-connect-dynamic-client-registration
src/phoenix.js
src/version.ejs

This adds dynamic client registration to phoenix according to https://openid.net/specs/openid-connect-registration-1_0.html
????
```
"openIdConnect": {
"authority": "https://ocis-bridge.owncloud.works",
"scope": "openid profile email offline_access",
"dynamic": true
},
```

Add dynamic client registration

---

yarn.lock

Refer to issue: https://github.com/owncloud/phoenix/issues/4279
See issue: https://github.com/owncloud/phoenix/issues/4279
As described: https://github.com/owncloud/phoenix/issues/4279
I have been using this for a number of weeks without incident and done a test build before and after modifying `yarn.lock` and it produces no change in the number or size of any files in the `/dist` folder when running `yarn dist` on a clean checkout of `master`.

Update yarn.lock to remove duplicate versions of vue.js library

---

tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

This PR removes `@skipOnOCIS` tag from a scenario of `moveFiles.feature` test so that it passes on ocis.
- part of https://github.com/owncloud/phoenix/issues/4269
- :robot:

[tests-only]remove skipOnOCIS tag from moveFiles test

---

changelog/unreleased/fix-login-as-user
tests/acceptance/helpers/loginHelper.js

~~waitForAllThumbnailsLoaded wasn't correctly waiting. It would return immediately if the files list was not loaded yet.~~
loginAsUser wasn't correctly waiting for the files list. waitForAllThumbnailsLoaded returns immediately if the list or loader takes longer to appear.
Found here https://drone.owncloud.com/owncloud/ocis/1342/32/7
https://github.com/owncloud/phoenix/blob/572da6eeef637ce304cec5a366b9e423affb4772/tests/acceptance/helpers/loginHelper.js#L32

fix loginAsUser

---

changelog/unreleased/openid-connect-dynamic-client-registration
src/phoenix.js

There was a bug where page load was failing when not using oidc, but plain oauth2 instead. This PR fixes it.

Fix dynamic client registration

---

apps/files/src/components/FilesAppBar.vue
apps/files/src/mixins/fileActions.js
changelog/unreleased/editor-handler
src/store/apps.js

In case the editor defines a custom handler instead of a route when opening a file, trigger the handler.

Use handler of the file editor

---

tests/acceptance/stepDefinitions/filesContext.js

the order of arguments for `assert.strictEqual` is actual, expected
reduce confusion when seeing test log output

[tests-only] fix order of arguments in assert

---

tests/acceptance/helpers/webdavHelper.js
tests/acceptance/stepDefinitions/filesContext.js

the waiting before an upload or delete had an issue
the code waited before the upload in https://github.com/owncloud/phoenix/blob/034efba13d429b26b2cad7562d928866dfc84fe8/tests/acceptance/stepDefinitions/filesContext.js#L97
and after the waiting `timeOfLastUploadOperation` is set but the upload hasn't even started, so if the upload is slow the waiting will be too short in the next upload
this PR f makes sure the time variable is only set after the upload or delete
besides that there have been two functions uploading files with content, I've deleted one of them
- Fixes #4301

[tests-only] Fix waiting between upload & deletes

---

tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

reduce the timeout when checking if a particular tab/accordion item is open in the side panel and we expect its not.
- Fixes https://github.com/owncloud/phoenix/issues/4312
reduce CI time
:robot:

[tests-only] reduce timeout when checking if sidebar tabs are open

---

tests/acceptance/features/webUIFiles/fileDetails.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/helpers/timeoutHelper.js
tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/sharingContext.js

fixing a couple of issues I noticed when working on #4355
cleaner code
:robot:

[tests-only] cleanup various issues with the sidebar tests

---

.drone.star

To the current https://github.com/owncloud/ocis/commits/master
This will show that the current Phoenix and OCIS master branches work together.
Then we can look at why https://github.com/owncloud/ocis/pull/868 is having trouble.

[tests-only] Bump OCIS commit id

---

tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature

There are two tests failing in ocis PR https://github.com/owncloud/ocis/pull/823
Skipped them for now, until https://github.com/owncloud/ocis/issues/891 is resolved.

[tests-only] Skip two sharing tests on ocis

---

apps/files/src/components/FileLinkSidebar.vue
changelog/unreleased/fix-edit-link-view

Do not overlap the edit public link view with the versions accordion.

Fix edit link view

---

apps/files/src/fileTypeIconMappings.json
changelog/unreleased/fix-icons

The file type icon mapping contained two mappings to non-existing icon files. This PR changes those mappings to other, existing icons.
- drone

Fix icon mappings for non-existing icon files.

---

apps/files/src/mixins/fileActions.js
changelog/unreleased/editor-handler
src/phoenix.js
src/store/apps.js
src/store/config.js

Extensions can now define own config object in the `external_apps` in config.json

Load extension config

---

.drone.star

This PR reverts a commit that breaks changelogs on CI. Needs some changes on top.

Revert "[CI] Fix CI trigger on push and heads/master"

---

apps/markdown-editor/src/MarkdownEditor.vue
apps/markdown-editor/src/MarkdownEditorAppBar.vue
changelog/unreleased/text-editor-file-path-label

There might be cases where the markdown editor stripped the first actual character of a file or folder name. It was supposed to strip a leading slash/backslash. This PR only trims leading slashes or backslashes. As a quick win it also sets aria labels for components that were complaining in the JS console about not having aria labels.
- Fixes https://github.com/owncloud/ocis/issues/428
Hardening.
- drone

Text editor file path label

---

src/phoenix.js
src/vue.js

Previously the Vue class wouldn't be assigned to the window object. To do so, we have to move Vue import into own file and assign the class there.

Bootstrap Vue

---

tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature

Updated tests for https://github.com/owncloud/ocis/pull/994

[Tests-only] Edit tests related to 'shared with me'

---

tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature

…now that issue-product-203 is fixed
PR #4413 moved to an OCIS commit id where issue-product-203 is fixed (or at least improved). The scenario concerned was adjusted to the new correct behaviour. Actually the good scenario above it should now be used.
This PR put the Examples that pass on both oC10 and OCIS into a single "good behaviour" scenario outline.
Examples that still only pass on oC10 are in a 2nd scenario tagged `skipOnOCIS`
Examples of bad behaviour on OCIS due to issue-ocis-717 are in a 3rd scenario tagged `skipOnOC10`
#4418 
CI

[tests-only] Adjust scenarios in sharedFolderWithMultipleUsersAdvancedPermissions

---

src/store/app.js

Every time phoenix calls the notifications endpoint it tries to do a json parse of the response content.
But there is no response content and therefore the parsing fails and log a message to the console.
This pr tries to prevent that so that the console doesn't get spammed with unnecessary logs.

check content length before trying to parse the content

---

apps/files/src/components/FilesAppBar.vue
apps/files/src/default.js
apps/files/src/quickActions.js
changelog/unreleased/fix-public-link-issues

This PR fixes some public link issues.
- batch actions were not available for public links
- creating a folder in a public link context showed an error
- quick actions for sharing are not available in public links (by design) but showed an error on the capabilities check.
- Fixes https://github.com/owncloud/ocis/issues/1028 https://github.com/owncloud/phoenix/issues/3744
Hardening
- drone

Public link fixes

---

.drone.star
apps/files/src/components/Collaborators/Collaborator.vue
apps/files/src/components/FileLinkSidebar.vue
apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
apps/files/src/components/PublicLinksSidebar/LinkActions.vue
apps/files/src/components/PublicLinksSidebar/LinkInfo.vue
apps/files/src/components/PublicLinksSidebar/PrivateLinkItem.vue
apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
apps/files/src/store/mutations.js
apps/files/src/store/state.js
changelog/unreleased/share-info-labels
changelog/unreleased/visible-links
package.json
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/stepDefinitions/sharingContext.js
yarn.lock

- Use `oc-tag` component to display share info
- Display public and private links
- Refactor public links sidebar components
Requires release and update of ODS with new icons and fixed `router-link` variation of `oc-tag` https://github.com/owncloud/owncloud-design-system/pull/975.
- Drone

Display collaborator info in labels

---

apps/files/src/components/Collaborators/SharedFilesList.vue
changelog/unreleased/accepted-shares-status.md

We need to add 'Accepted' to the translations.
Fixes https://github.com/owncloud/ocis/issues/985

add status text for accepted shares

---

changelog/unreleased/fix-nav-item-state
src/store/navigation.js
webpack.dev.js

fix: https://github.com/owncloud/ocis/issues/1031

Copy nav item state

---

apps/files/src/components/Collaborators/SharedFilesList.vue
changelog/unreleased/accepted-shares-decline.md

Declined shares could be accepted retroactively but accepted shares could not be declined.
Implements https://github.com/owncloud/ocis/issues/985

add the option to retroactively decline an accepted share

---

apps/files/src/mixins/fileActions.js
changelog/unreleased/fix-file-action-route-checks
src/store/apps.js

The checks on which route an extension is enabled were not active (and inverted). We fixed this so that editors only appear on configured routes now.
- Fixes  https://github.com/owncloud/ocis/issues/986
Hardening
- drone

Fix file editor actions

---

apps/draw-io/src/DrawIoEditor.vue
apps/draw-io/src/app.js
apps/draw-io/webpack.common.js
changelog/unreleased/drawio-custom-configuration
changelog/unreleased/drawio-vsdx-support
config.json.sample-oc10
config.json.sample-ocis

1. This PR allows to import .vsdx (Microsoft Visio files) directly from OC.
2. Once the file is open, if saved, a new `<filename>_<timestamp>.drawio` file is created with the modifications. (This avoids overwriting the original file with XML content). A message informing this should be shown ( #4335 )
3. By default, the draw-io app now points to `https://embed.diagrams.net` (The official embed-specific draw.io server)
4. If specified, the configuration in `config.json` will be used for the connections to draw.io (server url, autosave and theme)
```json
{
...
"applications": [
{
"title": {
"en": "draw-io"
},
"url": "https://custom.draw.io.url",
"autosave": true,
"theme": "atlas"
}
]
}
```
- Closes #4327 
- Closes #4328 
- Privacy reasons
- Flexibility
- Support for more formats
- test …

[draw.io] Deployment config + .vsdx support

---

.drone.star

The last update was from 3 Dec 2020, which is ages in the current fast-moving software environment.

[tests-only] Bump OCIS commit id for CI

---

.drone.star

Change from webhippie to ownCloud CI image.
- Pipeline fails: https://drone.owncloud.com/owncloud/web/12153/3/3
```
1 | latest: Pulling from webhippie/hugo
-- | --
2 | Digest: sha256:d720aa7a4149cecb8ad2f602ac23c3ff54e51fd36fd8411a57ea3e97801b0b0c
3 | Status: Downloaded newer image for webhippie/hugo:latest
4 | + cd hugo
5 | + \thugo
6 | ERROR 2020/12/11 08:09:14 HUGO-GEEKDOC theme does not support Hugo version 0.55.5. Minimum version required is 0.65.0
7 | Building sites … Total in 61 ms
8 | Error: Error building site: logged 1 error(s)
```
Fix Pipeline

[CI ONLY] bump hugo version

---

changelog/unreleased/fix-nav-item-state
changelog/unreleased/fix-navigation-rendering
changelog/unreleased/fix-object-mutations
changelog/unreleased/phoenix-ui-is-ready
src/Phoenix.vue
src/store/index.js
src/store/navigation.js
src/store/user.js

partially fixes: https://github.com/owncloud/ocis/issues/1043
fixes: https://github.com/owncloud/ocis/issues/884

fix ocis-1043

---

docs/_index.md
docs/deployments/_index.md

This makes the Phoenix section and the Phoenix/Deployments sections collapseable in the docs https://owncloud.github.io/.
- was already done for oCIS https://github.com/owncloud/ocis/pull/1046
- make docs more nice

[docs-only] add collapse section in docs

---

.drone.star
tests/acceptance/features/webUIFavorites/favoritesFile.feature
tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
tests/acceptance/ocis-mac-config.json
tests/drone/config.json
tests/drone/identifier-registration-oc10.yml
tests/drone/identifier-registration.yml
tests/drone/ocis-config.json

PR https://github.com/owncloud/ocis/pull/1041 switched `owncloud/ocis` to having a `web` extension, rather than `ocis-phoenix`
Adjust CI here so that it understands the changes in `owncloud/ocis`
CI

[tests-only] Change more phoenix to web now that owncloud/ocis has web extension

---

Makefile
Makefile.release

To keep the web app compatible with our default build and signing process
https://gitea.owncloud.services/devops/releasescripts
BTW: @jnweiger you need to update that and recreate your build container. ownCloud web needs node 12
- We need to add a `dist` target on the default makefile.

[tests-only] add legacy dist target

---

changelog/unreleased/default-apps
config.json.dist

When release tarballs are created, we are copying the config.json.dist into them as a default config. This file had so far only "files" app enabled. This adds also "media viewer" and "draw-io" into apps enabled by default.

Add media viewer and draw-io to default apps

---

.drone.star

Remove the last mention of `phoenix` from `.drone.star` - it seems to be an accidental leftover.
IMO `WEB_OIDC_CLIENT_ID` is not used in the drone test environment of oC10 and in OCIS it defaults to "web" nowadays. So we should not need to mention it at all.
CI

[tests-only] Remove WEB_OIDC_CLIENT_ID phoenix from .drone.star - not used

---

apps/files/src/mixins/fileActions.js
apps/media-viewer/src/app.js
changelog/unreleased/editors-new-tab

When opening the editors view in a new tab, we were using the origin of location. This would break in case we have Web deployed to a different path than root e.g. `http://owncloud/apps/web`.

Fix opening editors in new tab

---

.drone.star
tests/acceptance/expected-failures-with-oc10-server.txt
tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.txt
tests/acceptance/run.sh

If `EXPECTED_FAILURES_FILE` env var is defined, then read a list of expected-failing test scenarios from that file.
drone runs the script `tests/acceptance/run.sh` That runs the test scenarios, and then parses the output to find the scenarios that failed. It then compares that to the expected-failures. It reports both:
- scenarios that failed but are not in expected-failures. These are unexpected failures.
- scenarios that are in expected-failures but did not fail. These are unexpected passes.
Empty expected-failures files are provided for when running the tests against oC10 and against OCIS with owncloud storage.
After this code is merged, we can unskip the test scenarios that are skipped on OCIS, and add the ones that fail to the expected-failures file for OCIS.
We can also do similar …

[tests-only] Support an EXPECTED_FAILURES_FILE

---

apps/files/src/components/AllFilesList.vue
changelog/unreleased/disable-previews
docs/getting-started.md
src/store/config.js

This PR introduces a config option for disabling previews in file list views.
- drone

Introduce config option for disabling previews in list views.

---

changelog/unreleased/server-url
src/store/config.js

This PR adds a check upon loading the config, if the server url has a trailing slash and adds it if missing. This was leading to wrong paths and therefor unresolved resources before (see screenshot).
- manually

Be more forgiving with the server url

---

tests/acceptance/features/webUIResharing/reshareUsers.feature
tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature

The scenarios mentioned with issues https://github.com/owncloud/product/issues/203, but skipped due to some other differences between oc10 and ocis behaviour are gotten rid of issue tag `issue-ocis-203`.
- Part of https://github.com/owncloud/web/issues/4418
- CI

[Tests-Only] Adjust UI test scenarios related to product issue 203

---

.drone.star

https://github.com/owncloud/web/pull/4410/commits/a30718bd6847ba271326938e1c97c1a8eccb692f changed the docker image from `owncloudci/nodejs:11` to `webhippie/nodejs:latest` and that was merged 16 days ago. But "something happened" only a few days ago where the BusyBox `cp` command started spitting out help instead of doing the copy. (see issue)
This PR changes back to the `owncloudci/nodejs:12` - use version 12 which was created by https://github.com/owncloud-ci/nodejs/pull/7 a couple of days ago.
Magic - it works.
TBH I have no iddea why the BusyBox `cp` problem started to happen.
Fixes #4549 
CI

[tests-only] Use owncloudci/nodejs:12 instead of webhippie/nodejs:latest

---

tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
tests/acceptance/pageObjects/webPage.js
tests/acceptance/stepDefinitions/generalContext.js

This PR adds acceptance tests for:
- restoring a trashbin file whose parent folder is renamed
- restoring a trashbin file whose parent folder is not restored
Also, the method to assert the error/success message is changed in this or. Previously, when the expected error/success message and the actual displayed error/success message in the webUI were different, the error thrown was not clear about what was actually found. Can be seen in this: https://drone.owncloud.com/owncloud/web/12372/44/20 . With the recent change, even when the expected and actual text do not match, we can at least find out what was been expected and what was actually found, as in this: https://drone.owncloud.com/owncloud/web/12407/44/20
- Fixes https://github.com/owncloud/ocis/issues/1057
- CI

[Tests Only] Add acceptance tests to restore a trashbin file whose parent folder is renamed or is not restored

---

tests/acceptance/expected-failures-with-oc10-server.txt
tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.txt
tests/acceptance/features/webUILogin/login.feature
tests/acceptance/pageObjects/loginErrorPage.js
tests/acceptance/stepDefinitions/loginContext.js
tests/acceptance/stepDefinitions/provisioningContext.js

Add webUI tests for https://github.com/owncloud/ocis/issues/1129
The tests currently doesn't passes due to https://github.com/owncloud/web/issues/4564
🤖

[Tests-Only] Add ui test for checking the browser session of deleted user

---

tests/acceptance/pageObjects/filesPage.js
tests/acceptance/run.sh
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/generalContext.js
tests/acceptance/stepDefinitions/notificationsContext.js

While enabling more of the web UI tests on OCIS I discovered these things. The changes can be made in the existing code.
1) sleep at end of test run - the same as https://github.com/owncloud/core/pull/38250 - sync at end of tests to get all test log output
2) Avoid runOcc on OCIS - when enabling test scenarios on OCIS, if they use a step that currently calls `runOcc` then that gets an error that stops the whole test suite. I changed those so that they do nothing if running on OCIS. The "occ" setting will not happen when running on OCIS and the test scenario should fail in some later step, because the system behaviour will not be what is expected. But at least the test suite will continue and report the failed scenarios in a controlled way. In future we will need to sort out what to do …

[tests-only] Refactor for oCIS

---

changelog/unreleased/fix-burger-menu
src/components/Top-Bar.vue

The button for hiding/showing the left sidebar (burger menu) was not fully clickable. We fixed this by removing a negative margin that pulled the rest of the topbar over the button.
This bug was only taking effect when the search input field is hidden. This is why this was only a known bug in oCIS, not with oc10 backend (because we typically keep the search input when running with oc10). 
- Fixes https://github.com/owncloud/web/issues/4130
- drone and manual

Fix burger menu button

---

Makefile.release
appinfo/app.php
appinfo/routes.php
changelog/unreleased/oc10-app-config-endpoint
changelog/unreleased/oc10-app-controllers
docs/deployments/oc10-app.md
lib/Application.php
lib/Controller/ConfigController.php
lib/Controller/FilesController.php
src/web.js

When ownCloud Web is deployed as an app, we need to read the config from the config folder, instead of from within the app folder. Otherwise we'll have issues with the signing.

Set up a php oc10 controller for reading the config.json from the config folder

---

tests/acceptance/features/webUIFiles/fileDetails.feature
tests/acceptance/features/webUIFiles/fileFolderActionMenu.feature
tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
tests/acceptance/stepDefinitions/filesContext.js

- added webui tests for checking actions menu's different `options` available while selecting different file types or folder
-  added webui test for checking `file details` panel closes while opening a folder
closes https://github.com/owncloud/web/issues/4244
- local environment

[tests-only] Add webui tests for checking different available options of actions menu

---

.drone.env

There is nothing really exciting changed in OCIS, but I wanted to check anyway that all is good. PR https://github.com/owncloud/ocis/pull/1176 going the other way has some "bonus" failing tests to look into.

[tests-only] Bump OCIS_COMMITID as at 2021-01-06AM

---

tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.txt
tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
tests/acceptance/helpers/webdavHelper.js

Adds webUI tests for deleting and restoring a file inside a received share folder
- Fixes https://github.com/owncloud/ocis/issues/1124
- :robot:

[Tests-only] Adds webUI tests for deleting and restoring a file inside a received share folder

---

apps/files/src/components/LocationPicker/LocationPicker.vue
changelog/unreleased/copy-action-label

We've changed the label of the confirmation button in copy view. Instead of "Copy here", we used "Paste here".
Be closer to desktop explorers

Rename copy confirmation button

---

tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.txt
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
tests/acceptance/stepDefinitions/filesContext.js

Adds tests for sharing file after renaming it 
- tests for https://github.com/owncloud/web/issues/4192
- :robot:

[Tests-Only] Adds webUI tests for sharing file after renaming it 

---

tests/acceptance/features/webUISharingExternal/federationSharing.feature
tests/acceptance/stepDefinitions/sharingContext.js

Shares folder appears only after reloading page when using share_folder and accepting remote share via notification 
-test for https://github.com/owncloud/web/issues/4247
:robot:

[Tests-only] Add webUI test for share folder while federation sharing

---

tests/acceptance/features/webUIFiles/copy.feature
tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/filesPage.js
tests/acceptance/stepDefinitions/filesContext.js

Added test for performing cancel action while moving and copying a file
- closes https://github.com/owncloud/web/issues/4417
:robot:

[Tests-Only] Add webUI tests for performing cancel action while copying and moving a files/folders

---

tests/acceptance/run.sh

Be more specific in matching the format `[someSuite/someFeature.feature:42]` of an expected-failure.
Do not assume that it is preceded by a `-` and a single space. Codacy in `owncloud/ocis` complains a lot about `.md` file format and insists on particular spacing. So we do not want to depend on the exact spacing of this sort of thing.
- https://github.com/owncloud/ocis/issues/1193
CI

[tests-only] Be more specific matching an expected-failure

---

l10n/Makefile

The path references in the l10n Makefile contained some wrong placed `/`. This PR fixes that. Behaviour was correct before, it just looks weird in the terminal.

Fix paths in l10n Makefile

---

tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
tests/acceptance/run.sh

The expected-failures processing in `tests/acceptance/run.sh` was not finding unexpected passing scenarios. I had used regex with `\S` and `\d` to try to match non-whitespace and digits. But they were not working in the Bash regex. (Maybe the `\` were getting stripped out somewhere in the Bash command processor before going to the regex or... Maybe I could add more `\` to escape the `\`! I don't really care to know, because that would get too complex for future readers anyway)
Specify the actual character ranges to be matched. `[a-zA-Z0-9]` (alpha-numeric) and `[0-9]` (digit). That is more readable and it works - double bonus!
I tested locally by making some changes to the expected-failures files and seeing that I could get "unexpected passes" reported.
Now CI has found 2 scenarios in the …

[tests-only] Adjust regex for SUITE_SCENARIO in acceptance tests

---

docs/testing.md

The env var `BACKEND_HOST` was spelled wrong. Also fix a few other not-so-important typos that my IDE noticed.

[docs-only] Fix typos in testing.md

---

nightwatch.conf.js

PR #4632 tried demonstrate making a visual regression test fail. But the threshold is bit high, and a "significant" change to the top-bar image did not trigger failure.
Lowering the threshold did trigger failure, which is what we want. Commit the lower threshold.
CI

[tests-only] change visual regression threshold to 0.002

---

tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature

The trashbin delete problem has been fixed in `cs3org/reva` and `owncloud/ocis` is being updated in PR https://github.com/owncloud/ocis/pull/1372 - that correctly causes the bug-demo scenario to now fail.
It will be easiest to remove the scenario now, and that will avoid having to add it to expected-failures in the OCIS PR.
CI

[tests-only] remove trashbinDelete bug demo scenario

---

tests/acceptance/expected-failures-with-oc10-server.md
tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
tests/acceptance/features/webUIPreview/imageMediaViewer.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/filesContext.js

This PR adjusts the preview image assertion such that the presence of the image is checked strictly.
- part of https://github.com/owncloud/ocis/issues/1370
The preview of image is not visible but the tests were passing after checking the `preview-loaded` attribute's value and asserting it's true. So the step implementation is adjusted such that when the preview-loaded returns true, the presence of image is also checked.

[Tests-Only] Strictly check for the image for media viewer preview

---

tests/acceptance/expected-failures-with-oc10-server.md
tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
tests/acceptance/features/webUIPreview/imageMediaViewer.feature
tests/acceptance/stepDefinitions/previewContext.js

This PR adds media viewer test scenarios for files with upper case extensions. Also, the `When` step implementation is improved.
- Part of: https://github.com/owncloud/web/issues/4647

[Tests-Only]Add tests for media viewer files with upper case file extensions

---

tests/acceptance/helpers/webdavHelper.js

deleting a not-existent parameter from the docs block
there is no `server` parameter in the function, so get rid of it from the docs block 
comments are love-letters to your future self, they should be correct

[tests-only] delete wrong doc comment

---

tests/acceptance/expected-failures-with-oc10-server.md
tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
tests/acceptance/features/webUILogin/login.feature
tests/acceptance/stepDefinitions/loginContext.js

This PR adds webUI test for user session of a deleted user should not be valid for newly created user of same name.
- https://github.com/owncloud/ocis/issues/904
- CI

[Tests-Only] add webUI tests for user session of a deleted user

---

tests/acceptance/features/webUITrashbinFilesFolders/trashbinFilesFolders.feature

Trashbin restore was fixed in reva
See https://github.com/owncloud/ocis/pull/1588

[tests-only] Adjust passing error tests 

---

changelog/unreleased/invalidConfig
package.json
packages/web-runtime/src/configHelper.js
packages/web-runtime/src/index.js
packages/web-runtime/src/pages/missingOrInvalidConfig.vue
tests/unit/specs/loadConfig.spec.js
yarn.lock

Show a nice error message not only when the config is missing but also when the config could not be parsed
- Fixes #4636 
make it easier for the user to find our what is wrong if an error was made writing the config
- unit tests
- load the app with missing config
- load the app with an ivalid config

show error message if config could not be parsed

---

tests/acceptance/run.sh

If a test fails after retrying then the failure text includes "(attempt 2)". When filtering the test output to find the failures, just match the lines that have "(attempt 2)", for example:
```
5) Scenario: try to login with invalid username (attempt 1, retried) # tests/acceptance/features/webUILogin/login.feature:67
5) Scenario: try to login with invalid username (attempt 2) # tests/acceptance/features/webUILogin/login.feature:67
```
- Fixes #4728 
See demonstration in PR #4736 - comment https://github.com/owncloud/web/pull/4736#issuecomment-779781747 details some example results.

[tests-only] Only count fails on attempt 2

---

changelog/unreleased/search-in-additional-info
packages/web-app-files/src/components/Collaborators/NewCollaborator.vue

Fix searching in additional info when listing potential sharees.
- Fixes https://github.com/owncloud/ocis/issues/1656
- manually - needs tests
- add tests...

Search for sharees in additional info

---

tests/acceptance/run.sh

CI should fail if tests failed but there was no expected to fail file to compare against
test fail in https://drone.owncloud.com/owncloud/web/13234/52/14 but the CI run is still green
evergreens are great as songs and as plants but not as tests

[tests-only] fail CI when there is no expected-to-fail file but some tests failed

---

changelog/2.0.1_2021-02-18/fix-php-controller
package.json
packages/web-integration-oc10/appinfo/info.xml
packages/web-integration-oc10/lib/Controller/FilesController.php

This PR fixes the oc10 app deployment of the new folder structure after the switch to rollup. The new folder structure was not reflected in the list of allowed folders in the FilesController.
- drone

Fix allowed folders and CSP in oc10 app

---

changelog/unreleased/surpress-redirect-error
packages/web-runtime/src/store/user.js

We've suppressed the error appearing in the console which warned about redirect happening after the oidc callback page. This error is being shown because after the oidc callback has successfully processed the authorization request we are redirecting to the `/` path which immediately does another redirect to the extension set as default one. In the context of Vue router, this is considered an error even though for us it is a valid use case. The error is only informative thus no issue is going to surface if we suppress it. This way we are getting closer to a clean console without errors.

Supress redirect error

---

package.json
rollup.config.js
yarn.lock

Preserve symlinks so we can use local links for development. Increase the limit for node version to < 15.

Preserve symlinks

---

tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature

We currently don't have an acceptance test to assign a password to an already existing public share so this PR adds an acceptance test for that.
-  https://github.com/owncloud/web/issues/4614
- Manual
- CI

[Tests-Only] Acceptance test for password protected public share

---

tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js

Test step `Then "user" "Alice Hansen" should not be listed in the autocomplete list on the webUI` was passing even when it is expected to fail.
- Fixes https://github.com/owncloud/web/issues/4770
- :robot:

[Tests-Only]Fixed sharing tests that passed even when they were expected to fail

---

changelog/unreleased/fix-remove-unsupported-shareType
packages/web-app-files/src/helpers/shareTypes.js

Removes unsupported shareType of 'userGroup' (formerly 'contact').
Stumbled upon this by chance - we don't support 'userGroup' (originally 'contact', shareType `2`) on the backend side anymore, so it can be deleted on the frontend, too.

Delete shareType of 'userGroup'

---

changelog/unreleased/a11y-improvements-for-meta-attributes
packages/web-runtime/src/App.vue

- For a11y the html language attribute will be set dynamically <html **lang="xx"**/>
- For a11y the title will be set automatticaly following the schema : sub item (e.G file) - route (e.g All Files) - general  name (e.g ownCloud)
- https://jira.owncloud.com/browse/WEB-100
- https://jira.owncloud.com/browse/WEB-134
- test case 1:
- test case 2:
- ...

A11y improvements for meta attributes

---

changelog/unreleased/fix-node-env
rollup.config.js

NODE_ENV is always set to production
- Fixes #4819
have NODE_ENV set correct to current env

set NODE_ENV based on rollup build type

---

changelog/unreleased/public-link-download
packages/web-app-files/src/mixins/actions/fetch.js
packages/web-app-files/src/store/actions.js
packages/web-app-files/src/store/state.js
packages/web-app-media-viewer/src/App.vue
packages/web-app-media-viewer/src/mixins/loader.js
packages/web-runtime/src/plugins/web.js
tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md

Replaced the blob download with normal downloads using pre-signed urls provided by the backend.
The blob download had some disadvantages like delayed download for big files and high memory consumption.
- locally using the OC10 backend

download password protected public shared files using pre-signed url

---

changelog/unreleased/enhancement-live-region-updates
packages/web-runtime/src/App.vue
packages/web-runtime/src/router/index.js

Enhancement: Implement live region updates on route changes
- Fixes https://github.com/owncloud/web/issues/4346
- test case 1:
- test case 2:
- ...

added route change announcement

---

changelog/unreleased/bugfix-only-one-main-tag
packages/web-app-draw-io/src/App.vue
packages/web-app-files/src/App.vue
packages/web-app-markdown-editor/src/App.vue
packages/web-app-media-viewer/src/App.vue
packages/web-container/index.html.ejs
packages/web-runtime/src/App.vue

As explained in #1652 we only can have one `<main>` tag per HTML document. This PR removes the ones in `web-container` and `web-runtime` and adds one to each extension (files-list, mediaviewer, markdowneditor, drawio) since they can't be loaded at the same time.
- Fixes #1652
Important for accessibility-compliance (and to produce valid HTML)

Remove <main> tags from container & runtime and move them to extension level

---

.drone.star
docs/testing.md
nightwatch.conf.js
tests/acceptance/features/webUIAccount/accountInformation.feature
tests/acceptance/features/webUIAccount/userProfile.feature
tests/acceptance/features/webUIComments/comments.feature
tests/acceptance/helpers/config.js
tests/acceptance/setup.js
tests/acceptance/stepDefinitions/provisioningContext.js

Modified user creation logic to comply with/without skeleton files loading
Since we are specifying the size of skeleton files (or create a user without skeleton files), web tests should be modified accordingly and we can no longer put skeleton file creation logic on the Before scenario.
- :robot:

[Tests-Only]Modified user creation logic to comply with/without skeleton files loading

---

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-oc10-server-openid-login.md

Updates expected-failures file for the tests in `imageMediaViewer` and `shareByPublicLink` that are passing now
- webUIPreview/imageMediaViewer.feature:33
- webUIPreview/imageMediaViewer.feature:24
- webUIPreview/imageMediaViewer.feature:110
- webUISharingPublic/shareByPublicLink.feature:61
- https://github.com/owncloud/web/issues/4878

[Tests-Only] Fix unexpected passes of `imageMediaViewer` and `shareByPublicLink` tests

---

tests/acceptance/stepDefinitions/provisioningContext.js

If the test is running in OCIS, then the user creation and adding user to the group was done using `ldap` which is no longer valid. So, this logic has been fixed.
- locally

[Tests-Only]Logic for create group and add user to group in ocis has been fixed

---

tests/acceptance/customCommands/waitForAjaxCallsToStartAndFinish.js
tests/acceptance/pageObjects/personalPage.js

- only wait for 1sec for the upload progress bar to appear
- reduce timeout when waiting to ajax calls to start
1. reduce the timeout waiting for the upload progress bar to appear, for small uploads we are checking too late
2. reduce timeout when waiting to ajax calls to start, when the call started and is already finished we are checking too late and there is no need to wait for so long then
I found these issues while running random tests, it has not been a search for all issues
speed up CI

[tests-only] speed up web tests by reducing timeouts

---

tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
tests/acceptance/features/webUITrashbinFilesFolders/trashbinFilesFolders.feature
tests/acceptance/stepDefinitions/filesContext.js

This PR adjusts the function to assert deleted elements are not listed such that all types of resources are checked.
- Fixes https://github.com/owncloud/QA/issues/664
- CI

[Tests-Only]Adjusts the function to assert deleted Elements are not listed

---

tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/filesContext.js

Sharing indicator is sometimes displayed after few seconds. So, tests checking for this indicator fail intermittently. This PR checks if the indicator is displayed and if it's not displayed it waits for few seconds and then checks it again. This process continues three times.
- Part of https://github.com/owncloud/web/issues/4878
- CI

Sharing indicator fail fix

---

changelog/unreleased/bugfix-parent-paths
packages/web-app-files/src/helpers/path.js
packages/web-app-files/tests/helpers/path.spec.js

We had a bug that caused loading incoming and outgoing shares of the current folder twice (leading to two extra requests). Fixed it by cleaning up the helper for building parent paths. Added unit tests.
- Fixes https://github.com/owncloud/web/issues/4860
Bugfixing
- unit tests + looking at the network tab and not seeing duplicate share listing requests anymore for the current folder.

Fix loading shares of the current folder twice

---

packages/web-app-files/src/store/actions.js
packages/web-runtime/src/components/ApplicationsMenu.vue
packages/web-runtime/src/pages/account.vue
packages/web-runtime/themes/owncloud/theme.json
tests/acceptance/features/webUIAccount/accountInformation.feature
tests/acceptance/stepDefinitions/accountContext.js

Related to accessibility & translations
- Changed "Groups membership" => "Group memberships"
- Changed the way extension titles are rendered in the appSwitcher, so they hopefully don't show up as `{{ n.title }}` in Transifex anymore

Update appSwitcher titles & fix typo in group memberships

---

changelog/unreleased/enable-toggleable-search-bar
packages/web-runtime/src/components/TopBar.vue
packages/web-runtime/tests/components/TopBar.spec.js
packages/web-runtime/tests/components/__snapshots__/TopBar.spec.js.snap

Simply the ability to toggle on and off the search bar in the files app per-route, so you can customise the interface further depending on what you are showing as content (ie. a file preview or other viewer).
See description.
Tested working locally, it's very simple change.
**With**
**Without**

Add ability for route meta options to hide search bar

---

.drone.star
tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
tests/acceptance/features/webUIRenameFiles/renameFiles.feature
tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
tests/acceptance/features/webUITrashbinFilesFolders/trashbinFilesFolders.feature
tests/acceptance/helpers/config.js
tests/acceptance/stepDefinitions/generalContext.js

This PR adds a before scenario to disable Previews for the tests with disable previews tag. The `disablePreviews` tags are added in the intermittent failing tests of deleteFilesFolders, moveFiles, renameFiles, shareByPublicLinkDifferentRoles and shareByPublicLink.feature
- CI

[Tests-Only]DisablePreviews for the tests with disable previews tag

---

.drone.star
tests/acceptance/stepDefinitions/generalContext.js

This PR reverts the config system setup done in drone.star in this PR https://github.com/owncloud/web/pull/4908 as it is not necessary.  Also, the use of `oldPreviewSetting` is redundant as the configs set in the before steps are rolled back again with the previously existing function.

[Tests-Only]Remove enable previews in setup in drone.star

---

changelog/unreleased/people-list
packages/web-app-files/src/components/Collaborators/NewCollaborator.vue
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js

We've changed the HTML elements in the people accordion when adding new people. People added via people autocomplete are now displayed in a list element to use correct structure for screen readers.
- Fixes #4788

Use list element to display added people

---

changelog/unreleased/enhancement-use-ods-translations
packages/web-runtime/src/index.js

Needs another ODS release (4.4.0) to work and a rebase after the ODS release is in web master, but should be good to go
Edit: Depends on #4940

Import ODS translations & merge with web translations

---

changelog/unreleased/bugfix-improve-web-container
packages/web-container/index.html.ejs
rollup.config.js

- A `meta` element with an `http-equiv` attribute whose value is X-UA-Compatible must have a content attribute with the value `IE=edge`. (fixed in rollup)
- Element `h3` not allowed as child of element `span` in this context.
- The type attribute is unnecessary for JavaScript resources.

Update web container

---

tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
tests/acceptance/features/webUIAccount/accountInformation.feature
tests/acceptance/features/webUIAccount/logout.feature
tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
tests/acceptance/features/webUIComments/comments.feature
tests/acceptance/features/webUICreateFilesFolders/createFile.feature
tests/acceptance/features/webUICreateFilesFolders/createFolderEdgeCases.feature
tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature

refactor steps for user creation with appropriate skeleton files.
Following suites have been refactored: 
- webUIAccount
- webUIAdminSettings
- webUIComments
- webUICreateFilesFolders
- webUIDeleteFilesFolders
- 🤖

[Tests-Only]refactor steps for user creation with appropriate skeleton files.

---

tests/acceptance/features/webUISharingInternalUsersToRootCollaborator/shareWithUsers.feature

Removed duplicated scenario share a file with another internal user via collaborators quick action. The same scenario was in https://github.com/owncloud/web/blob/d901d2e67dda7ce024917bc5f94f705fdb4714ca/tests/acceptance/features/webUISharingInternalUsersToRootCollaborator/shareWithUsers.feature#L53 and https://github.com/owncloud/web/blob/d901d2e67dda7ce024917bc5f94f705fdb4714ca/tests/acceptance/features/webUISharingInternalUsersToRootCollaborator/shareWithUsers.feature#L121
- 🤖

[Tests-Only]Removed duplicated scenario in shareWithUsers feature

---

.drone.star

Removes the pipelines of sharingToRoot from oCIS acceptance test
- Closes https://github.com/owncloud/web/issues/4955

[Tests-Only] Remove sharingToRoot test pipelines from oCIS acceptance test

---

changelog/unreleased/enhancement-accessibility-improvements
packages/web-app-files/src/components/AppBar.vue

A recent PR changed the route for the "all files" view from `personal` to `all`. Breadcrumbs baseUrl was missed in that PR.
- test case 1:
- test case 2:
- ...

Adapt breadcrumbs baseUrl according to recent route changes

---

.drone.star
tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRootBlacklisted/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRootCollaborator/shareWithUsers.feature

Refactor  `webUIResharing` and `webUIResharingToRoot`  tests to not use skeleton files:
- webUIInternalUsersToRoot
- webUIInternalUsersToRootBlacklisted
- webUIInternalUsersToRootCollaborator
https://github.com/owncloud/QA/issues/659
- test environment: :robot:

[Tests-Only] Refactor `webUIInternalUsersToRoot` tests to not use skeleton files (part 1)

---

tests/acceptance/stepDefinitions/filesContext.js

create files and folders one by one
maybe that would help avoid 500 errors that @kulmann encounters

[tests-only] create testfiles/folders async

---

tests/acceptance/features/webUISharingExternal/federationSharing.feature
tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/provisioningContext.js
tests/acceptance/stepDefinitions/sharingContext.js

Refactor  `webUISharingExternal`  tests to not use skeleton files:
- webUISharingExternal
- webUISharingExternalToRoot
https://github.com/owncloud/QA/issues/659
- test environment: :robot:

[Tests-Only] Refactor `webUISharingExternal` tests to not use skeleton files

---

tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js

```
When the user renames file "lorem.txt" to "newName.txt" using the webUI
```
The above step failed few times. The screenshots show that the rename dialog box has not been closed, so I suspect that the click event may have been fired before the button is clickable.
So, this PR is a proposed solution to wait for `Rename` button to be enabled (from disabled state) before firing click event.
Tested with multiple run of rename test suite:
https://drone.owncloud.com/owncloud/web/14880/6/14
- part of https://github.com/owncloud/web/issues/4919
- test environment: :robot:

[Tests-Only] Wait for Rename button to be in enabled state

---

.drone.star
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/stepDefinitions/filesContext.js

This PR adds functionality to try to get share indicator of a resource a second time when the first try fails
Hopefully, it will prevent intermittent fails of the sharing-indicator tests that occur due to the unavailability of share indicators.
- part of https://github.com/owncloud/web/issues/4919
- test environment: :robot:

[Tests-Only] Get share indicators of a resource with retry

---

.drone.star

switch to official Redis docker image in CI
- None
Use only maintained docker images

switch to official redis

---

changelog/unreleased/enhancement-direct-delete
packages/web-app-files/src/mixins/deleteResources.js

Implement a proper delete action for a single file. Previously this was being handled via selecting the file. This also solves the issue with the checkbox being checked when opening the delete modal, which was not a11y compliant.
Honestly I'm not quite sure about the approach, it seems too easy... but it works well on my side 🤷

Implement a proper direct delete

---

changelog/unreleased/enhancement-focus-management
packages/web-app-files/src/App.vue
packages/web-app-files/src/components/Sidebar.vue
packages/web-runtime/src/App.vue
packages/web-runtime/src/components/UserMenu.vue
packages/web-runtime/src/index.js
packages/web-runtime/src/mixins/focusMixin.js
packages/web-runtime/src/mixins/lifecycleMixin.js
packages/web-runtime/tests/mixins/focusMixin.spec.js
packages/web-runtime/tests/mixins/lifecycleMixin.spec.js

to get a better background why this is needed please read #4992 beforehand.
- Fixes #4992 
This pr introduces the concept of user driven focus management.
This is helpful when a user navigates using the keyboard and the given context switches, for example the sidebar or and a modal opens which has a different tabindex and the user will never get there (more or less). 
Now it's possible to decide which item should be focused after a given action (modal open, sidebar show). 
The important part here is that those interactions need to be able to be rolled back.  (replayed in a reverse order).
- if a user closes a modal, the focus should jump back to the exact position where he started.
- if a sidebar opens the focus should jump into the sidebar or vice versa if it gets closed.
following worst …

Focus-Management

---

changelog/unreleased/enhancement-real-location-picker-title
packages/web-app-files/src/views/LocationPicker.vue

We've added real page titles to the location picker. The title is consisted of the current action, target and product name.

feat: use real titles in location picker

---

rollup.config.js

After changing the way dependencies in ODS were declared some weeks ago, running `yarn link owncloud-design-system` failed due to a PostCSS config error. This change re-enables linking & testing locally between `web` and `owncloud-design-system`

Re-enable yarn link ods by disabling postcss-config in rollup

---

tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
tests/acceptance/features/webUILogin/adminBlocksUser.feature
tests/acceptance/features/webUILogin/oauthLogin.feature
tests/acceptance/features/webUILogin/openidLogin.feature
tests/acceptance/features/webUIMarkdownEditor/markdownFile.feature
tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature

Refactor the following suite tests to not use skeleton files:
- webUILogin
- webUIMarkdownEditor
- webUIMoveFilesFolders
- webUINotifications
- CI

[Tests-Only] Refactor webUI scenarios to prevent unnecessary skeleton file creation

---

changelog/unreleased/enhancement-h-tags
packages/web-app-files/src/index.js
packages/web-app-files/src/views/FilesDrop.vue
packages/web-app-files/src/views/PrivateLink.vue
packages/web-app-files/src/views/PublicLink.vue
packages/web-runtime/src/pages/accessDenied.vue
packages/web-runtime/src/pages/account.vue
packages/web-runtime/src/pages/login.vue
packages/web-runtime/src/pages/oidcCallback.vue
packages/web-runtime/src/router/index.js

The [last PR](https://github.com/owncloud/web/pull/5004) was not paying attention to actual page titles. With this PR the h1 tags reflect the relevant bit of the page title.
- Fixes https://github.com/owncloud/web/issues/5003

Sync page title and h1 tag

---

tests/acceptance/features/webUIFilesList/fileList.feature

disabling preview on multi-selection tests as it seems preview sometimes unselect the selected file when preview appears.
part of https://github.com/owncloud/web/issues/4919

[Tests-Only] Debug filesList intermittent fails

---

CHANGELOG.md
changelog/unreleased/enhancement-files-sidebar-accessibility
packages/web-app-files/src/components/AppBar.vue
packages/web-app-files/src/components/Sidebar.vue
packages/web-app-files/src/components/Sidebar/ActionsAccordion.vue
packages/web-app-files/src/mixins/actions/copy.js
packages/web-app-files/src/mixins/actions/delete.js
packages/web-app-files/src/mixins/actions/download.js
packages/web-app-files/src/mixins/actions/favorite.js
packages/web-app-files/src/mixins/actions/fetch.js
packages/web-app-files/src/mixins/actions/move.js
packages/web-app-files/src/mixins/actions/navigate.js
packages/web-app-files/src/mixins/actions/rename.js
packages/web-app-files/src/mixins/actions/restore.js
packages/web-runtime/src/App.vue
packages/web-runtime/src/directives/clickOutside.js
packages/web-runtime/src/index.js
tests/acceptance/features/webUIFilesActionMenu/fileFolderActionMenu.feature
tests/acceptance/pageObjects/FilesPageElement/appSideBar.js

* Transform file name to `h2` element
* Transform `Open folder` action to link instead of button
* Add a more descriptive close button label
* Close sidebar when clicking outside of it
* Remove `aria-label` on the action buttons as they already include proper labels
* Transform the favorite-star in sidebar to a button-element, adjust `aria-label`
* Add a hint for screen readers if an action opens a new window/tab

Improve accessibility for the files sidebar

---

tests/acceptance/features/webUIRenameFiles/renameFiles.feature
tests/acceptance/features/webUITrashbinFilesFolders/trashbinFilesFolders.feature

This Pr unskips trashbinFilesFolders tests. Also, the intermittent failing rename files tests are tagged with `disablePreviews` tag
- https://github.com/owncloud/web/issues/4919

[Tests-Only]Unskip trashbinFilesFolders tests

---

changelog/unreleased/bugfix-navigation-in-private-links
packages/web-app-files/src/views/PrivateLink.vue

We've fixed that the navigation in the left sidebar is visible for a resolved private link as well
- test environment: Chrome
- test case 1: Visit a private link for resource in the root level
- test case 2: Visit a private link for a nested resource

fix: display navigation for resolved private link

---

changelog/unreleased/enhancement-extension-config
packages/web-runtime/src/store/apps.js

This PR makes the config object of an `external_apps` object (if one was provided) available in the global vuex `apps` getter.
- drone

Make external app config available in `apps` getter

---

changelog/unreleased/bugfix-navigation-in-private-links
changelog/unreleased/enhancement-move-breadcrumbs-out-of-location-picker-heading
packages/web-app-files/src/views/LocationPicker.vue
packages/web-app-files/src/views/PrivateLink.vue

We've moved the breadcrumbs element out of the location picker heading and moved it under it.
The heading is now also reflecting the page title.
We've also decreased the size of both breadcrumbs and action buttons so that they fit better together.

Move breadcrumbs out of location picker heading

---

changelog/unreleased/bugfix-hide-navigation-on-route-change
packages/web-runtime/src/App.vue

On smaller screens, the left sidebar containing the extension navigation is collapsed. We've fixed that when the user expanded the sidebar and navigated to a different route the sidebar is collapsed again.

Fix: hide navigation on route change

---

changelog/unreleased/bugfix-quick-action-ids
packages/web-app-files/src/components/FilesLists/QuickActions.vue
tests/acceptance/pageObjects/FilesPageElement/filesRow.js

27042021 quick action id to class

---

.drone.star
docs/backend-oc10.md

`dav.enable.tech_preview` was used in about ownCloud server 10.4. We don't need to use that setting in CI any more, so remove it.
CI

[tests-only] Remove tech_preview setting from CI and docs

---

.drone.star
docker/Dockerfile
docker/overlay/usr/bin/healthcheck

Add back a minimal healtchcheck script as the new docker base image does not ship a default one anymore.
- local docker run and build

fix: add missing healthcheck script

---

changelog/unreleased/enhancement-trashbin-a11y
packages/web-app-files/src/components/BatchActions.vue

Add more context to the empty trash bin button text and only render it, if resources are present.
- test case 1:
- test case 2:
- ...

Enhancher Trashbin a11y

---

changelog/unreleased/enhancement-share-action-buttons
packages/web-app-files/src/views/SharedWithMe.vue

Changed the appearance of the "accept/decline share" buttons in the "Shared With Me" file list so they actually look like buttons.

Change appearance of the share action buttons

---

tests/acceptance/helpers/webdavHelper.js

`trashData` gets object instead of array when there are no any files/folders in the trashbin, so trashData.map() will cause error if trashData gets object
- Closes https://github.com/owncloud/web/issues/5064

[tests-only] Refactor webdavHelper:getTrashBinElements function

---

changelog/unreleased/bugfix-new-file-menu-z-index
packages/web-app-files/src/App.vue

Removed the z-index on the files-app-bar because it prevented the new file menu from having a higher z-index than the table headers. As a result the new file menu was being overlapped by them.

Fix z-index on the new file menu

---

changelog/unreleased/enhancement-new-file-menu-a11y
packages/web-app-files/src/components/AppBar.vue
packages/web-app-files/src/components/FileUpload.vue
packages/web-app-files/src/components/FolderUpload.vue

We now use buttons instead of a-tags in the new file menu. Also fixed the double-focus per item when navigating via tab.

Improve accessibility on new file menu

---

.drone.star

- Format DroneCI Starlark definition with Buildifier (from Bazelbuild)
- Add CI step to enforce DroneCI Starlark to be properly formatted in PRs 
- None
Have a nice formatted CI defintion

Format starlark definition

---

docs/testing.md

After the use of `ocis` server with `ocis storage driver`, _redis_ usage is not required. With this PR that information is also removed from the testing documentation
- https://github.com/owncloud/ocis/issues/2008

[Tests-Only] removed redis information from web testing docs

---

changelog/unreleased/enhancement-accessibility-improvements
packages/web-app-files/src/components/AppBar.vue

Live region update about file/folder selection with checkboxes was lacking a hint that actions for the selection are available above the table. This PR adds those hints.
- drone

Add hints about actions above table to live region update

---

changelog/unreleased/bugfix-editors-for-all-routes
packages/web-app-files/src/mixins/fileActions.js

If an extension doesn't define valid routes it should be allowed for all routes by default. That behaviour was not working properly and is fixed with this PR.
- drone

Skip editors route check on empty array

---

changelog/unreleased/enhancement-files-sidebar-shares
packages/web-app-files/src/components/Collaborators/Collaborator.vue
yarn.lock

29042021 move tags into lists

---

changelog/unreleased/bugfix-sharee-tag
packages/web-app-files/src/components/FileSharingSidebar.vue

Role setting didn't look up parent file ownership and announced the current user as "owner" even though they might've only been viewer, editor etc. This has been fixed now

Fix collaborator tag for currentUser in sidebar

---

tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js

fix xpaths in filespage to fix intermittent tests.
currently xpaths use `aria-label` and seem like aria labels are not  loaded everytime in the DOM. and it cannot find the elements.
- Fix https://github.com/owncloud/web/issues/4919#issuecomment-831680401

[Tests-Only] fix xpaths in filespage to fix intermittent tests

---

changelog/unreleased/enhancement-files-sidebar-shares
packages/web-app-files/src/mixins/fileActions.js

Found another untranslated string

Transalte fileActions opener

---

changelog/unreleased/bugfix-navigate-to-share-parent
packages/web-app-files/src/components/Collaborators/Collaborator.vue

The "Via" button in the collaborators according section in the sidebar sends you to the parent of the share entry, while it actually should send you the to share entry itself.
- Fixes #5082

Fix indirect via-share in collaborator sidebar section

---

changelog/unreleased/change-use-slots-in-sidebar
packages/web-runtime/src/App.vue

In the new sidebar content is defined solely via slots. We've moved all the content into those slots so that the sidebar still gets displayed correctly.

feat: use slots in sidebar

---

tests/acceptance/features/webUIUpload/upload.feature

Add disablePreviews tag for webUIUpload/upload.feature:130 to fix intermittent failure.
- Fixes intermittent failure for webUIUpload/upload.feature:130
Sometimes when the previews loading the file becomes locked and it becomes impossible to write it. as a result, this test was failing in CI intermittently. So disabling previews for this make this test pass consistently.

[Tests-Only] disable preview to fix failing upload test

---

changelog/unreleased/enhancement-people-focus
packages/web-app-files/src/components/FileSharingSidebar.vue

We've started sending the focus to "Add people" button after the Add or Edit panels in the people accordion have been closed.

feat: send focus to add people btn

---

changelog/unreleased/bugfix-scrolling-overflow
packages/web-app-files/src/App.vue
packages/web-app-files/src/mixins/filesListPositioning.js
packages/web-app-files/src/views/LocationPicker.vue
packages/web-runtime/src/App.vue

In cases where the browser-window space was not enough to render all views
the ui ended up with weird scrolling behavior.
This has been fixed by restructuring the dom elements and giving them proper styles.
get the ui rendered correct even on smaller screens
- local

fix layout scrolling issue

---

.drone.star

- reduce Apache output log for tests
- reduce ocis log level
these logs are usually not needed and with that change we will save a couple of hundreds lines of log output in every step of the pipeline

[tests-only] reduce log output in tests

---

tests/acceptance/features/webUIRenameFiles/renameFiles.feature
tests/acceptance/features/webUIRenameFolders/renameFolders.feature

This PR adjusts the tries to step in rename files/folders tests such that the rename is actually performed when the result of the step is expected for the resource to be renamed successfully.
- https://github.com/owncloud/web/issues/4933
- CI

[Tests-Only]Adjust the tries to steps for rename files/folders

---

tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/stepDefinitions/filesContext.js
tests/acceptance/stepDefinitions/publicLinkContext.js

This PR adjusts steps that try to edit public link shares.
Also, few adjustments is made in the changes made by this pr https://github.com/owncloud/web/pull/4824
- https://github.com/owncloud/web/issues/4933
- CI

[Tests-Only]Adjust steps that try to edit public link shares

---

changelog/unreleased/enhancement-oc-tooltip
packages/web-app-files/src/components/AppBar.vue
packages/web-app-files/src/components/Collaborators/Collaborator.vue
packages/web-app-files/src/components/Collaborators/CollaboratorsEditOptions.vue
packages/web-app-files/src/components/FileInfoVersions.vue
packages/web-app-files/src/components/FilesLists/QuickActions.vue
packages/web-app-files/src/components/PublicLinksSidebar/LinkActions.vue
packages/web-app-files/src/components/PublicLinksSidebar/LinkInfo.vue
packages/web-app-files/src/components/PublicLinksSidebar/PrivateLinkItem.vue
packages/web-runtime/src/components/ApplicationsMenu.vue
packages/web-runtime/src/components/Notifications.vue
packages/web-runtime/src/index.js

update all tooltips to use oc-tooltips which will land in the next version of ods (6.4.0)
- https://github.com/owncloud/web/pull/5055
- https://github.com/owncloud/web/issues/4654
- https://github.com/owncloud/web/issues/2623
- https://github.com/owncloud/web/issues/4597
- https://github.com/owncloud/web/issues/4332
- https://github.com/owncloud/web/issues/4300
uitooltip is not accessible, a11y audit requires this.
- local installation

update all uikit tooltips to use v-oc-tooltip

---

changelog/unreleased/bugfix-quick-action-ids
changelog/unreleased/bugfix-unique-ids
changelog/unreleased/enhancement-button-appearance
changelog/unreleased/enhancement-share-action-buttons
packages/web-app-files/src/components/BatchActions.vue
packages/web-app-files/src/components/Collaborators/Collaborator.vue
packages/web-app-files/src/components/InfoSelectedResources.vue
yarn.lock

- IDs in people shares in the sidebar were created inside a loop and needed an appendix to make sure they're unique
- Changed the selector of the `collaborator-list` `<ul>` CSS selector to class to avoid a11y offenses
- Outlined button in the batch actions (not the most beautiful solution on some viewports with the sidebar expanded)
*Edit / Side note:* ` vue-axe@^2.4.4` appeared as a duplicate in the `yarn.lock`, perhaps due to some rebase earlier - this is why I commited the change

Unique IDs in people shares sidebar & outline button in batch actions

---

changelog/unreleased/enhancement-people-focus
packages/web-app-files/src/components/FileSharingSidebar.vue

Fixes the details I missed when merging https://github.com/owncloud/web/pull/5129 the other day

25052021 share focus mngmnt

---

changelog/unreleased/enhancement-hide-navbar-if-no-navitems
packages/web-runtime/src/App.vue

Felt surprisingly easy, I'd vote in favor of only hiding the navigation (and not the whole sidebar) to keep the iconic CI blue plus OC logo present for public links though...

[debatable] Hide left sidebar if no navitems present

---

changelog/unreleased/bugfix-copy-to-clipboard-with-keyboard
changelog/unreleased/enhancement-copy-link-toasts
packages/web-app-files/src/components/FileLinkSidebar.vue
packages/web-app-files/src/components/PublicLinksSidebar/CopyToClipboardButton.vue
packages/web-app-files/src/components/PublicLinksSidebar/LinkInfo.vue
packages/web-app-files/src/components/PublicLinksSidebar/PrivateLinkItem.vue
packages/web-runtime/package.json
packages/web-runtime/src/index.js
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
yarn.lock

This PR introduces confirmation toasts for copying (private/public) links to the clipboard. Refactored into a `CopyToClipboardButton` component. We can decide later on if we want to move it to ODS (would need to extract the confirmation message then, as that needs to stay in web, and replace it with just emitting an event).
a11y improvements
- drone

Action toasts

---

.drone.star
changelog/unreleased/continuously-deployed-demo-instance
deployments/continuous-deployment-config/ocis_web/latest.yml
deployments/examples/ocis_web/.env
deployments/examples/ocis_web/README.md
deployments/examples/ocis_web/config/ocis/entrypoint-override.sh
deployments/examples/ocis_web/config/ocis/proxy-config.json
deployments/examples/ocis_web/docker-compose.yml
deployments/examples/ocis_web/monitoring_tracing/docker-compose-additions.yml

Adds a continuously deployed oCIS with the latest (master) Web UI. First deployment already online at https://ocis.ocis-web.latest.owncloud.works/.
Fixes #5150 
[x] Add secrets
[x] add docs to https://owncloud.dev/ocis/deployment/continuous_deployment/ -> see https://github.com/owncloud/ocis/pull/2076
[x] setup drone cron schedule

add example deployment

---

changelog/unreleased/enhancement-oc-tooltip
packages/web-app-files/src/components/AppBar.vue

Add tooltip/ariaLabel for New Button if user has permissions to upload/create resources

Add tooltip/ariaLabel for New Button if user has permissions

---

changelog/unreleased/bugfix-hide-new-link-button
packages/web-app-files/src/components/FileLinkSidebar.vue

Hides "Create public link" button if user has insufficient share permissions. Debatable if we should only hide the "Create" button and if users with e.g. view/edit rights should be at least displayed links (even if they can't edit/create/delete them)
- Fixes #5080

Hide new public link share button if user lacks permissions

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

Add test for sharing share_folder
- Related https://github.com/owncloud/web/issues/5152
:robot:

[Tests-Only] add tests for sharing the shares_folder

---

tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
tests/acceptance/pageObjects/personalPage.js
tests/acceptance/stepDefinitions/filesContext.js

This PR adjusts the test step that tries to create files and folder, meaning that the resource creation process is supposed to be unsuccessful.
The changes made by this PR and how they work
- When the user creates a resource using the web UI and it's supposed to be successful the parameter `expectedToSucceed` in
` createFolder/createFile` function is set to `true` by default and the user will successfully create a folder
- When the user tries to creates a resource then same function  ` createFolder/createFile` is called but we set `expectedToSucceed` to `false` . In this case we check if the name of the resource in `inputTextField` is in `red colour` and if the `create button` has been `disabled`, as these are the actual behavior that should take place when resource creation is supposed …

[tests-only] Adjust steps that try to create files/folder

---

changelog/unreleased/enhancement-focus-breadcrumb-on-route-change
packages/web-app-files/src/mixins/accessibleBreadcrumb.js
packages/web-app-files/src/views/Personal.vue
packages/web-app-files/src/views/PublicFiles.vue

Focus current active breadcrumb on route change and announce contents of current folder to screenreader

Focus breadcrumb on route change

---

tests/acceptance/stepDefinitions/privateLinksContext.js

This PR adjusts the test step that tries to navigate private link, meaning that the navigation process is supposed to be unsuccessful.
The changes made by this PR and how they work
- When a user `tries to` navigate a private link which they don't have permission to , they shouldn't be able to do so and should be redirected to the login page. When a user with permission accesses the private link then `#webContainer` should be visible to them and they shouldn't be logged out . But for user trying to access it without permission  `#webContainer` shloudn't be present and they should be redirected to login page. This PR adds that extra check
- part of : https://github.com/owncloud/web/issues/4933
These changes were necessary because previously in steps dealing with `tries to` we used to check …

[tests-only] Adjust steps that try to navigate private links

---

.drone.star

With this PR, a developer can mention `full-ci` in the PR title, and that will override the `earlyFail` behavior.
Normally when the first UI test pipeline fails, it cancels the whole build, to save CI resources.
But now, if you mention `full-ci` in the PR title, then the UI tests pipelines will all run to completion, even if one or more of them fails. That can help a developer to see all the fails "at once". And they can do it without actually editing `.drone.star` - so the PR can be merged when it passes (there will be no need to revert an edit of `.drone.star`)
Fixes #5183 
CI

[tests-only] [full-ci] Do not do earlyFail in CI if full-ci requested

---

.drone.star

`github_token` should be a global secret that is available for all drone runs, so use that.
Demonstrated in #5187 - test fails do still get reported in GitHub comments.

[tests-only] Use github_token for posting comments

---

.drone.star

Bump node & ubuntu images in `.drone.star`

[tests-only] Bump nodejs (12->14) and ubuntu (16.04->20.04) in .drone.star

---

.drone.star

If ordinary UI test scenarios fail for "ordinary" reasons, and there are no Visual Regression Test diffs, then the `build-github-comment-vrt` pipeline step was failing, complaining that `cd /var/www/owncloud/web/tests/vrt/diff` does not exist. The step would be marked with a red "x" on the drone UI. That was a bit misleading - there was nothing wrong with that step. The actual acceptance tests step was the only step that really failed.
This PR adds some extra checks for existence of the `diff` directory structure, and the step exits early if the directory structure does not exist.
PR #5192 demostrates this. It introduces some failing tests. The drone pipeline https://drone.owncloud.com/owncloud/web/15916/6/18 looks better now - only the `webui-acceptance-tests` step is showing a red "x".

[tests-only] [full-ci] Exit early from build-github-comment-vrt if there are no diffs

---

.drone.env
.drone.star
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/helpers/sharingHelper.js

This PR bumps core and ocis commit id to see if any tests are failing and add them to expected to fail file according
- part of : owncloud/QA#662
- :robot:

 [tests-only] [full-ci] Bump core and ocis commit id

---

.drone.star
package.json
tests/acceptance/run.sh

- Implements divide and parts system in `run.sh`
- Fixes https://github.com/owncloud/ocis/issues/2107
We need to be able to run all suites, but running them all takes too long, so we want to divide and parallelize the test runs. In web repo, we simply run one suite in a drone job. But when doing that for apps, we need to be able to divide the test run without knowing how many and which suites are available.
- `./tests/acceptance/run.sh --part 1 70` runs first part out of 70 parts without any tags
- `TEST_TAGS=@magic ./tests/acceptance/run.sh --part 1 70` runs first part out of 70 parts with provided tag
- `TEST_TAGS=@magic ./tests/acceptance/run.sh` filter whole acceptance test dir by tags
- `TEST_PATHS='tests/acceptance/features/webUIPreview tests/acceptance/features/webUIPrivateLinks …

[Tests-Only] Run tests with parts

---

tests/acceptance/features/webUISharingExternal/federationSharing.feature

When running tests with the "run parts" feature implement in PR #5188 the logic just runs all the suites that it can find. But from OCIS we currently do not run tests that use a federated server.
Add a filter tag to federated server tests, so that there is an easy way to skip those whenever we need to do that.
Part of https://github.com/owncloud/ocis/issues/2107
CI

[tests-only] Add test tag federated-server-needed

---

tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/personalPage.js

- `getAttribute("selector", "innerText", callback)` is throwing `result` with `null` even if the element is already visible on the dom
- `getText` is used to get element
https://github.com/owncloud/web/issues/4919#issuecomment-856434313

[Tests-Only] used get text instead of getAttribute

---

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIFilesActionMenu/versions.feature

webUIFilesActionMenu/versions.feature:14 was behaving differently on CI because the file was being locked and the test was put in `expected to fail file`
This PR addresses that , makes it run as desired on CI and removes it from `expected to fail file` .
- Fixes : https://github.com/owncloud/web/issues/5022
This PR adds `@disablePreviews` tag at the top of the failing scenario which solved the issue
- locally
- :robot:

[tests-only] Remove webUIFilesActionMenu/versions.feature:14 from expected to fail and fix the issue

---

tests/acceptance/pageObjects/locationPicker.js

Fixes `webUIMoveFilesFolders/moveFiles.feature:140` and hopefully reduces code complexity a bit (I didn't really grok what was happening there before)

Change how the root breadcrumb on move page is detected for abs path

---

packages/web-app-files/src/components/FileLinkSidebar.vue
packages/web-app-files/src/components/FileSharingSidebar.vue
tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

- Removed duplicate selector
- Added class to "You have no permission" paragraph 
- Refactored test to expect "You have no permission" string instead of a failure notification
Fixes `webUISharingPublicBasic/publicLinkCreate.feature:195`

Update handling of no permission in link reshare

---

.gitattributes

Hides all the `.feature` files from linguist so this repo isn't shown as a (mainly) Gherkin project

Hide end-to-end test definitions in GH repo language statistics

---

deployments/continuous-deployment-config/ocis_web/latest.yml

Nightly deployment / rebuild of the deployment example fails because of a wrong path: https://drone.owncloud.com/owncloud/web/16102/66/3

[CI-only] fix path in continuous deployed example

---

.drone.star

even after #5235 the example deploy https://ocis.ocis-web.latest.owncloud.works/ is not pruned during the Drone CI Cron run, because prior pipeline steps are failing (https://drone.owncloud.com/owncloud/web/16150/66/1). On cron we do not need to wait for build artifacts from prior pipelines to do the actual deploy so we don't need to add the dependencies on the other pipelines. Therefore the examples deploy will always executed for crons even if tests fail.

[CI-only] run example deploys always on cron

---

packages/web-app-files/src/components/Collaborators/Collaborator.vue

Doesn't really feel like it deserves a dedicated Changelog item, just adding a utility class here
- Fixes #5240

Add more spacing between edit and delete collaborator icons

---

packages/web-runtime/tests/components/Notification.spec.js

testing `Notifications.vue`
- test if the notification message is displayed
- test if the action button is not displayed when actions are not set in `activeNotifications`
- if action button is displayed if actions is present in `activeNotifications`
- Part of https://github.com/owncloud/web/issues/5217
https://github.com/owncloud/web/pull/5206
- 🤖

[tests-only] unit tests for Notifications.vue

---

.drone.star

If PR title contains `unit-tests-only` then the acceptance tests suite is turned off.
Do not run acceptance tests if only unit test files are changed
- Part of https://github.com/owncloud/web/issues/5217
- Part of https://github.com/owncloud/web/issues/5231

[test-only][unit-tests-only] Do not run acceptance tests if only unit tests are changed

---

changelog/unreleased/bugfix-remove-vuex-circular-init
packages/web-app-files/src/views/LocationPicker.vue
packages/web-runtime/src/index.js
packages/web-runtime/src/plugins/mediaSource.js
packages/web-runtime/src/router/index.js
packages/web-runtime/src/store/index.js
packages/web-runtime/tests/store/config.spec.js

We've moved the create Vuex store logic into the index file of Web runtime to prevent initialising the store multiple times.

fix: do not call vuex create store multiple times

---

changelog/unreleased/enhancement-editor-mode
packages/web-app-files/src/components/AppBar.vue
packages/web-app-files/src/mixins/fileActions.js

We've added a parameter called `mode` to the different ways of opening a file editor. The mode can be `edit` or `create` and reflects whether the file editor was opened in an editing mode or in a creation mode.
Resisted the urge to refactor anything, as the extension loading and handling will get an urgently needed overhaul soon anyway.
- Fixes https://github.com/owncloud/web/issues/5226
Enable extension developers to react differently to edit and create actions.

Add mode prop for opening file editors

---

changelog/unreleased/bugfix-typeerror-fileTypeIcon
packages/web-app-files/src/mixins.js
packages/web-app-files/tests/mixins.spec.js

unit tests for `fileTypeIcon` function and a small fix for the case if the extension is not a string
part of #5236
`yarn test:unit`

unit tests for packages/web-app-files/src/mixins.js:fileTypeIcon

---

packages/web-app-files/src/components/Collaborators/AutocompleteItem.vue
packages/web-app-files/tests/components/Collaborators/AutocompleteItem.spec.js

unit tests for the AutocompleteItem component
part of #5234
more tests === more better

[unit-tests-only] unit tests for AutocompleteItem

---

changelog/unreleased/bugfix-show-0-when-negative-quota-given
packages/web-runtime/src/helpers/resource.js
packages/web-runtime/tests/components/SidebarQuota.spec.js
packages/web-runtime/tests/helpers/resource.spec.js
tests/unit/stubs/index.js

- unit tests for SidebarQuota.vue
- show `0 B of 2 GB` as quota in case of a negative number given as used quota and not only ` of 2 GB`
part of #5217
increase unit test coverage

unit tests for SidebarQuota.vue

---

packages/web-app-files/tests/components/Collaborators/Collaborator.spec.js

first part of testing the collaborator component
this PR tests:
- the correct display of the image/icon according to the shareType
- setting of username and userid for the collaborator avatar
- various parts of the collaborator text
part of #5234

[unit-tests-only] Unit tests for Collaborator component (1)

---

packages/web-app-files/tests/components/Collaborators/Collaborator.spec.js

test that if the collaborator is not the current user the indicator `(me)` should not be shown
part of #5234

[unit-tests-only] test collaborator additional info when collaborator is not current user

---

changelog/unreleased/enhancement-files-sidebar-accessibility
packages/web-app-files/src/components/Sidebar.vue

Sticky sidebar header (changes in `web` are minimal and just reflect what has changed in the ODS)
- Fixes #2019
See changelog item in https://github.com/owncloud/owncloud-design-system/pull/1384 and #2019

Accommodate sticky sidebar header

---

.drone.star
tests/drone/setup-server-and-app.sh

We want to make smarter CI that can minimize test pipelines depending on what has changed in a PR etc.
For that, we want to be able to easily decide whether to run the commands in a pipeline step, or not.
In the current `.drone.star` we have steps that have quite a long list of individual commands embedded directly in the starlark.
It will be easier to control if we extract those lists of commands into script files that can be executed as a single command from the starlark.
This PR does the first "extraction".
1) Remove the duplication of `/var/www/owncloud/*` through the starlark (we want to be able to pass that string around)
2) Put the setupServerAndApp commands into a script and call the script from the starlark.
CI

[tests-only] [full-ci] Put setupServerAndApp commands into a script

---

packages/web-app-files/tests/unit/mixins/collaborators.spec.js

unit tests for the collaborator type in the collaborators mixins
part of #5234

[unit-tests-only] collaboratorType() of packages/web-app-files/src/mixins/collaborators.js

---

packages/web-app-files/tests/unit/views/SharedWithMe.setup.js

stub also the new `oc-pagination` component
follow up of #5224
tests would pass but show a warning
```
[Vue warn]: Unknown custom element: <oc-pagination> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
---> <Anonymous>
<Root>
```

[unit-tests-only] stub oc-pagination in SharedWithMe tests

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature

These bug-demo scenarios were left behind after the bugs were fixed. The corresponding good scenarios are all in the feature files, and are passing on OCIS (as well as on oC10)
This PR deletes the bug-demo scenarios and adjusts the expected-failures.
- Fixes #4601 
CI

[tests-only] [full-ci] Remove old OCIS bug-demo scenarios

---

changelog/unreleased/enhancement-add-pagination
packages/web-app-files/src/views/LocationPicker.vue
packages/web-app-files/src/views/Personal.vue
packages/web-app-files/src/views/PublicFiles.vue

This PR fixes an implementation detail of the pagination that we brought in https://github.com/owncloud/web/pull/5224: on pagination the resources were reloaded entirely. If the set of resources didn't change (which can be expected when only the page number is different to the route from before) this is unnecessary network traffic.
Performance

Don't reload resources when going to a different page on the same route/resource

---

changelog/unreleased/enhancement-resource-field-update
packages/web-app-files/src/components/AppBar.vue
packages/web-app-files/src/helpers/statusIndicators.js
packages/web-app-files/src/store/actions.js
packages/web-app-files/src/store/mutations.js
packages/web-app-files/src/views/LocationPicker.vue

when a lot of files are displayed in files table, the web ui lacks.
This happens because we update a reference to a files object, even if we clone the collection by using the spread operator
`[...this.object]` child objects are still passed by [reference not value](https://www.oreilly.com/library/view/javascript-the-definitive/0596000480/ch04s04.html). 
The update event then gets triggered multiple times even if it's not needed.... resulting with a frozen ui.
This only happens in dev mode because of strict mode and outside mutation: https://github.com/owncloud/web/blob/39cdc0993c0a55a13f790ced1f40f2e7a92494da/packages/web-runtime/src/store/index.js#L28
we also hammer vuex by adding the full resource on every mutation, this pr also adds the ability to update certain resource keys only.
- …

Fix reactivity overload (frozen UI when displaying lots of files while developing in web-app-files)

---

.drone.star

Adjust the drone acceptance test pipeline names so that they consistently start with `oC10` or `oCIS` to indicate which back-end system they are testing against.
- Fixes #5323 
CI

[tests-only] [full-ci] Adjust drone pipeline names

---

.drone.star

When acceptance tests fail, a GitHub comment is posted to notify about which test pipeline failed. Currently that shows a dropdown for "details" but actually there are no extra details. There is also no link to the failing drone job.
This PR:
- removes the `details` section
- adds a link to the drone job and pipeline stage that failed. The link goes to step 1 of the pipeline.
The available `DRONE*` env vars are documented at https://docs.drone.io/pipeline/environment/reference/
CI - see demo PR #5332 
Comment https://github.com/owncloud/web/pull/5332#issuecomment-865649142 has a working link to the drone pipeline stage that failed.

[tests-only] Improve failed acceptance test GitHub comment

---

.drone.star
tests/drone/build-glauth.sh
tests/drone/build-idp.sh
tests/drone/build-ocis-web.sh
tests/drone/build-web-app.sh
tests/drone/build-web.sh
tests/drone/copy-files-for-upload.sh
tests/drone/get-ocis.sh
tests/drone/setup-fed-server-and-app.sh
tests/drone/setup-graph-api-oidc.sh
tests/drone/setup-integration-web-app.sh
tests/drone/setup-notifications-app.sh
tests/drone/setup-oauth2.sh
tests/drone/setup-server-and-app.sh

PR #5336 demonstrates changing only a unit test in a PR.
When the drone starlark tries to skip the acceptance test steps, it gets problems with `fixPermissions()` and `fixPermissionsFederated()` - those try to `cd` into the server or federated dorectory first. And that `cd` fails. There is potential for a similar problem in `runWebuiAcceptanceTests()`. The starlark should also skip the `cd` commands when acceptance tests are not required.
This PR:
- combines the `cd` and next command into a single bash command line, so it is all encapsulated by the bash `if` test.
- changes all the "Bye!" messages that happen when a step is skipped. More informative message text has been added.
CI

[tests-only] Refactor skipping of acceptance test steps

---

changelog/unreleased/bugfix-unnecessary-webdav-propfind
packages/web-app-files/src/views/Favorites.vue
packages/web-app-files/src/views/SharedViaLink.vue
packages/web-app-files/src/views/SharedWithMe.vue
packages/web-app-files/src/views/SharedWithOthers.vue

in the the files-app views `Favorites`, `SharedViaLink`, `SharedWithMe` and `SharedWithOthers`
we did a unnecessary propfind request to obtain the rootFolder which is not required there.
- Fixes #5337
less requests
- local test with ocis and oc10

Remove unnecessary Propfind requests

---

.drone.star

If someone puts `full-ci` in the PR  title, or sets `earlyFail` to false, then we should run all the CI - even if they only changed unit tests.
CI

[tests-only] Respect interaction between full-ci and calculateDiffContainsUnitTestsOnly

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUILogin/openidLogin.feature
tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature
tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFileGroup.feature
tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
tests/acceptance/stepDefinitions/provisioningContext.js

Some steps were missed while refactoring scenarios to avoid the use of skeleton as much as possible. Those missed steps has been fixed in this PR. Also, since the step `Given('user {string} has been created with default attributes', async function(userId)` is being no longer used, I have removed that step definition.
- 
- 🤖

[full-ci][tests-only]Changed some steps that were creating user with default attributes

---

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
tests/acceptance/features/webUISharingPublicBasic/publicLinkPublicActions.feature
tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
tests/acceptance/features/webUISharingPublicManagement/publicLinkShareByEmail.feature
tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
tests/acceptance/features/webUITags/createTags.feature
tests/acceptance/features/webUITags/tagsSuggestion.feature
tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/acceptance/stepDefinitions/publicLinkContext.js

remove @yetToImplement from tests and add them to expected-failures if required features not implemented yet
- part of 
https://github.com/owncloud/web/issues/4977

[full-ci][tests-only] Remove @yetToImplement tags from tests (Part-3)

---

.drone.env
.drone.star
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md

1) Bump the commit ids for the servers used in tests. In particular, this will include https://github.com/owncloud/ocis/pull/2210 reva 1.9.0 that was merged into OCIS.
2) Fix storage name in expected-failures-with-ocis-server-ocis-storage.md like done in https://github.com/owncloud/ocis/pull/2206
3) Rationalize reporting of drone build link in GitHub comments  - put the link to the drone CI pipeline directly after the top line of the comment "Results for..."
CI

[full-ci] [tests-only] Bump test commit ids

---

tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/helpers/webdavHelper.js
tests/acceptance/stepDefinitions/generalContext.js

reviewed and removed the step
```
Then('as {string} the content of {string} should be the same as the original {string}', function(
user,
remoteFile,
skeletonFile
) {
return assertRemoteFileSameAsSkeletonFile(user, remoteFile, skeletonFile)
})
```
- 🤖

[full-ci][tests-only]Removed unused step for comparing with files in skeleton directory

---

tests/drone/setup-fed-server-and-app.sh
tests/drone/setup-server-and-app.sh

As all the tests in web are independent to the skeleton directory, the command `'php occ config:system:set skeletondirectory --value=/var/www/owncloud/server/apps/testing/data/webUISkeleton',` is not necessary.
- Fixes https://github.com/owncloud/QA/issues/659
-  Fixes https://github.com/owncloud/QA/issues/628
- 🤖

[full-ci][tests-only]Removed skeletondirectory from system config

---

packages/web-runtime/src/components/TopBar.vue
packages/web-runtime/tests/unit/components/__snapshots__/TopBar.spec.js.snap

Purely a CSS change to make the Top Bar more consistent in.  It looked strange before.
As above.
Tested in Edge and Chrome.
Note - the only change is on the hamburger, even though the pointer is on the space between.
Before
After

Improve size of hamburger icon in condensed width (medium and less responsive view) top section

---

tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
tests/acceptance/stepDefinitions/provisioningContext.js

This PR removes the incorrect test step and replaces it with the new one and also removes the unused step-definition
- part of : https://github.com/owncloud/QA/issues/659
We had a issue to remove the use of skeleton files and use the correct ones when needed. This file seem to have been missed during that refactoring process.
- locally
-  CI

[tests-only] Use correct skeleton file in tests

---

tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-oc10-server-openid-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUILogin/oauthLogin.feature
tests/acceptance/features/webUIPreview/imageMediaViewer.feature
tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature
tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
tests/acceptance/features/webUITrashbinFilesFolders/trashbinFilesFolders.feature
tests/acceptance/features/webUIUpload/upload.feature
tests/acceptance/features/webUIUpload/uploadEdgecases.feature

- test case 1:
- test case 2:
- ...

[full-ci] [tests-only] choose-tests-for-ocisSmokeTest: add tag ocisSmokeTest

---

docs/deployments/oc10-app.md

Fix wrong type in the docs
```php
'web.rewriteLinks' => 'true',
'web.rewriteLinks' => true,
```
I will not have an effect because `'true'` is not false (it is just a string with the word "true") but semantically it is incorrect.

[docs-only]  Wrong type in config.php value

---

sonar-project.properties

ignore test related files for sonar cloud analysis
maybe they could also be moved into the `tests` folder and by that they would be ignored altogether see #5412
correct sonarcloud coverage report

[unit-tests-only] ignore mocks and fixtures for coverage

---

.drone.env

Bump core and ocis commit ids
part of https://github.com/owncloud/QA/issues/662

[full-ci][tests-only] Bump commit ids for tests

---

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/run.sh

If a test that was expected to fail passes then CI should report it and the build should be cancelled but it was not happening. This PR solves that problem and makes the CI report unexpected passes and removes the passing tests from expected to fail file.
- Fixes https://github.com/owncloud/web/issues/5356
As unexpected passes were not reported it was confusing to see tests failing out of nowhere. We weren't sure if the line of test-step has been changed or new tests were failing , we also didn't know about the passing test that were in expected to fail file.
The changes made in this PR 
- Add new variable `SUITE_IN_RUN` which contains the suite that is in run ie `webUILogin`, previously  we had `SUITE_IN_THIS_RUN` which contained the full path of the test suite which was the reason …

[full-ci] [tests-only] investigate unexpected passes not reporting

---

packages/web-app-files/src/helpers/resource/asset.ts
packages/web-app-files/src/helpers/resource/index.ts
packages/web-app-files/src/store/actions.js
packages/web-app-files/tests/unit/helpers/resource/asset.spec.ts
packages/web-app-files/tests/unit/helpers/resource/privatePreviewBlob.spec.ts

in the past loadPreview only was needed from within vuex store, with the upcoming preview feature and search // filter it is required to be able to use preview loading outside the store too. This pr utilize loadPreview and make it available as a helper.
- required for https://github.com/owncloud/web/pull/5415
- required for https://github.com/owncloud/web/issues/5161
extract more and more logic out of vuex
- local installation and unit tests
- ...
-
-

extract loadPreview into helper

---

packages/web-integration-oc10/lib/Controller/FilesController.php

These edits must be included in the request https://github.com/owncloud/web/pull/5420
It is possible to connect ONLYOFFICE with a relative path. https://github.com/onlyoffice/docker-onlyoffice-owncloud
Then the address for the editor is relative `/ds-vpath/`:
https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud/blob/790ef3ccf88ec0a5ec856f703c5066fd3997e074/run.sh#L10
The old solution has a similar action:
https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/34f69c833ee4b00880d538aed1ecc48025ac8791/controller/editorcontroller.php#L762
@kulmann @pmaier1 Thanks

Allow onlyoffice on the same domain

---

packages/web-integration-oc10/lib/Controller/FilesController.php

These edits can be included in the request #5420
I suggest using the method from the onlyoffice application, instead of duplicating a piece of code into your application
@kulmann

getting onlyoffice address from the app

---

changelog/unreleased/bugfix-delete-batch-action-in-viewer-shares
packages/web-app-files/src/components/AppBar/SelectedResources/BatchActions.vue
packages/web-app-files/src/helpers/resources.js
packages/web-app-files/tests/unit/components/BatchActions.spec.js

This PR fixes that we showed the batch action for deleting files/folders for read only shares. Additionally we return early in the batch action availability checks.

Fix delete batch action in read only shares

---

changelog/unreleased/enhancement-add-view-options
packages/web-app-files/src/components/AppBar/AppBar.vue

This PR makes the `view options` button less prominent by giving it a `raw` appearance, making the gap size of the button smaller and shrinking the width of the drop to the actually needed size.

Make view options button less prominent

---

changelog/unreleased/enhancement-update-ods-8.0.0
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/components/FilesList/ListInfo.vue
packages/web-app-files/src/components/SideBar/Links/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/constants.ts
packages/web-app-files/src/store/actions.js
packages/web-app-files/src/views/Favorites.vue
packages/web-app-files/src/views/LocationPicker.vue
packages/web-app-files/src/views/Personal.vue
packages/web-app-files/src/views/PublicFiles.vue
packages/web-app-files/src/views/SharedViaLink.vue
packages/web-app-files/src/views/SharedWithMe.vue
packages/web-app-files/src/views/SharedWithOthers.vue
packages/web-app-files/src/views/Trashbin.vue
packages/web-app-files/tests/unit/components/AppBar.spec.js
packages/web-app-files/tests/unit/views/Favorites.spec.js
packages/web-runtime/package.json
packages/web-runtime/src/App.vue
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
yarn.lock

Updates ODS to v8.0.0-rc2 and does all the necessary changes for it. Also introduces the `ImageType` constants which are later on needed in the details in the right sidebar.

Update ODS to v8.0.0-rc2

---

.github/CODEOWNERS
changelog/unreleased/enhancement-details-in-sharing-sidebar
changelog/unreleased/enhancement-update-ods-8.0.0
packages/web-app-draw-io/src/App.vue
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkEdit.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/NewCollaborator.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/index.js
packages/web-app-files/src/mixins.js
packages/web-app-files/src/store/actions.js
packages/web-app-files/src/views/Favorites.vue
packages/web-app-files/src/views/Personal.vue
packages/web-app-files/src/views/PublicFiles.vue
packages/web-app-files/src/views/SharedWithMe.vue
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
packages/web-runtime/package.json
yarn.lock

Details accordion needs some more polishing
Additional: Update codeowners, unify data-test(-)ids, remove dead code
- Works towards closing #5466

Polish details in right sidebar

---

tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature

Fix links for issuesin expected failure files
- Fixes https://github.com/owncloud/web/issues/5372
:robot:

[Tests-Only] Fix links for issuesin expected failure files

---

changelog/unreleased/enhancement-oc10-web-csp
packages/web-integration-oc10/lib/Controller/FilesController.php

The iframe integrations of the documentserver coming from onlyoffice / richdocuments need certain CSP rules. With this PR we're extracting the respective documentserver domains from the two apps. We'll work on a generic solution when it becomes relevant.
Enable onlyoffice to build an integration of their documentserver into a web extension.

Apply CSP rules for onlyoffice and richdocuments

---

packages/web-pkg/tests/unit/cache/cache.spec.ts
packages/web-pkg/tests/unit/http/client.spec.ts
packages/web-pkg/tests/unit/observer/visibility.spec.ts
packages/web-pkg/tests/unit/utils/encodePath.spec.ts
packages/web-pkg/tests/unit/utils/objectKeys.spec.ts

move tests to unit test folder, following the pattern set by #5224 and finally decided by #5425
fixes #5471
after this PR all spec files should be in the right place:
```
find -name *spec.* | grep -v node_modules
./packages/web-pkg/tests/unit/utils/encodePath.spec.ts
./packages/web-pkg/tests/unit/utils/objectKeys.spec.ts
./packages/web-pkg/tests/unit/observer/visibility.spec.ts
./packages/web-pkg/tests/unit/cache/cache.spec.ts
./packages/web-pkg/tests/unit/http/client.spec.ts
./packages/web-app-files/tests/unit/views/Favorites.spec.js
./packages/web-app-files/tests/unit/mixins.spec.js
./packages/web-app-files/tests/unit/mixins/collaborators.spec.js
./packages/web-app-files/tests/unit/services/client.spec.ts
./packages/web-app-files/tests/unit/services/cache.spec.ts …
```

[unit-tests-only] move typescript tests to unit folder

---

.drone.star

When CI is running for a "tag" event, then we do not want to do any `calculate-diff` step. That step calculates if nothing else was changed, and short-circuits the running of acceptance tests. But for a "tag" event, nothing has changed, but we do want to run all the tests.
- Fixes #5500 
CI

[tests-only] [full-ci] Run all acceptance tests on tag event

---

.drone.env
tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md

Gets the commit ids right up-to-date. No real change to expected-failures - I removed some white-space to make all the headings format consistent.
CI

[tests-only] [full-ci] Bump commit ids for tests

---

tests/acceptance/helpers/webdavHelper.js

Dont crash the test build if dav properties are not found
So that we dont get crashes such as https://drone.owncloud.com/owncloud/ocis/5976/52/6
- Fixes tests on ocis
🤖

[Tests-Only] Dont crash the test build if dav properties are not found

---

tests/acceptance/helpers/webdavHelper.js

change default depth for dav requests from 2 to infinity
webdav doesn't allows depth to be 2. only 0, 1 and infinity are allowed as depth.
https://datatracker.ietf.org/doc/html/rfc4918#section-9.1

[Tests-Only] change default depth for dav requests from 2 to infinity

---

packages/web-app-files/tests/unit/components/FilesList/NoContentMessage.spec.js

- Unit tests added for `NoContentMessage` component
- component testing
- 🤖 
- 👨🏼‍🎨

[unit-tests] Added unit tests for NoContentMessage component

---

changelog/unreleased/bugfix-unnecessary-quota-requests
packages/web-app-files/src/views/Favorites.vue
packages/web-app-files/src/views/SharedViaLink.vue
packages/web-app-files/src/views/SharedWithMe.vue
packages/web-app-files/src/views/SharedWithOthers.vue

We were fetching the user quota on views where it is not needed as part of an outdated component structure of the frontend. Removing the unnecessary parts for now, we'll have to (re-)introduce them somewhere else when implementing spaces sometime soon
- Fixes #5337
Less
Manually

Remove quota requests where not needed

---

changelog/unreleased/enhancement-prevent-bind-to-loopback-address
rollup.config.js

This is required when running the acceptance tests on Windows, it allows the selenium docker containers to access the frontend due to the host binding in rollup (when running `yarn serve`).  I have considered the implications but can't see any downside to having this as the default, it doesn't break any existing functionality.
As above.
Tested on Windows with WSL2 and also on MacOS.

Prevent binding to only loopback IP when running in watch mode

---

packages/web-app-files/tests/unit/components/FilesList/QuickActions.spec.js

- added unit tests for `QuickActions` component from `FilesList` view
- every component should be tested
- :robot:
- 💇🏼‍♂️

[unit-tests] add unit tests for QuickActions component

---

changelog/unreleased/bugfix-send-cookie-manifests-json
packages/web-container/index.html.ejs

Requests to manifest.json are performed without any authorization / cookies.
- https://github.com/w3c/manifest/issues/535
For the ownCloud 10 to oCIS migration strategy we want to utilize cookies, to decide where to route requests. Therefore every request needs to send the cookie, also manifest.json.
- test environment: dev setup  (add a cookie and see if it was added to the manifest.json request)

send cookie on manifest.json

---

changelog/unreleased/bugfix-oc10-web-oidc-csp
packages/web-integration-oc10/lib/Controller/FilesController.php

One can currently not use ownCloud Web with ownCloud 10 and OpenID connect, because proper content policies are missing and calls to the OIDC provider will fail.
- none
The oCIS migration strategy requires to run ownCloud 10 with OIDC and Web. This is currently not possible.
- https://github.com/owncloud/ocis/pull/2302

make openidconnect in oC10 possible

---

deployments/examples/ocis_web/docker-compose.yml

Simplifies the deployment example by using a global http to https redirect. (This will also be done for oCIS deployment examples: https://github.com/owncloud/ocis/pull/2306)
- none
Simplify the deployment example
- on dev machine by running `docker-compse up -d` in the deployment example directory

[deployment example] simplify traefik configuration

---

packages/web-app-files/tests/unit/helpers/collaboratorRolesDefinition.spec.js

Added unit tetsts for `collaboratorRoleDefinition` helper 
- part of #5236 
- unit tests coverage
- 💇🏼‍♂️ 
- 🤖

[unit-tests] Added unit test for collaborator role definition helper

---

packages/web-app-files/tests/unit/components/AppBar/Upload/FolderUpload.spec.js

Adds unit  tests for `FolderUpload` component

[tests-only][unit-tests] Add unit tests for FolderUpload component

---

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIFilesActionMenu/versions.feature

A test is written that demonstrates the error. The test will work when the bug is fixed
Steps to reproduce the behavior:
User1 creates file and shares file to User2
User2 accepts file and try to upload file with some name
Or run test: yarn run test:acceptance:ocis tests/acceptance/features/webUIUserJourney/journey1.feature:29
Created new version
403 Forbinden
Please describe how you started the server and provide a list of relevant environment variables.
OCIS_VERSION=v1.9.0 reachable at https://localhost:9200
BRANCH=v1.9.0-rc1

[tests-only] change the file content of a received share
