- README.md
> Adding screenshots

- apps/files/src/components/File-Sharing-Default-Modal.vue
- apps/files/src/components/File-Sharing-Public-Link-Modal.vue
- apps/files/src/components/File-Sharing.vue
- apps/files/src/components/Files-App.vue
- src/default.js
- Implement the navigation within directories
- Add back navigation
- Implement file loading on page reload
> Implement file browsing

- .gitignore
- apps/files/src/components/File-Details-Buttonrow.vue
- apps/files/src/components/File-Details.vue
- apps/files/src/components/Files-App.vue
This will only start working after the PR #66 of js-owncloud-client is merged
> Implement file downloading

- apps/files/src/components/Files-App.vue
This PR correctly implement the breadcrumbs fixing the back navigation issue : owncloud/phoenix#150
> Fix back navigation with breadcrumbs

- apps/files/package-lock.json
- tests/acceptance/features/login.feature
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/pageObjects/loginPage.js
- tests/acceptance/stepDefinitions/loginContext.js
some improvements of acceptance tests as we learn how to deal with nightwatch
1. check that not only the files table exists, but also contains rows
2. fix login by correctly select the first element in the dropdown list
3. wait for the loading indicator to disappear
> improve login acceptance test

- README.md
New Demo Link (for now) http://dev.felix.click/OWC.007.16/0.1.0/
> Update link to demo

- apps/files/src/components/File-Details-Buttonrow.vue
- apps/files/src/components/Files-App.vue
- src/components/Login.vue
- src/default.js
This change replaces the func().then(...) constructs with the async/await pattern introduced by ES2017. 
While it is not too obvious in this change, this makes the code more readable and more intuitively understandable.  A good example here is the login code where we do two asynchronous API calls in succession which in the original required nested "then".
This will not cause compatibility problems as async/await is syntactic sugar and will for the time being be transpiled by babel into more traditional code.
> Use ES2017 async/await pattern

- apps/files/src/components/Files-App.vue
- apps/servstat/package-lock.json
- package-lock.json
This PR implements filtering of the files and directories. 
**TODO :** Filtering of the hidden files is not a part of this PR as the hidden file feature is not yet added to Phoenix.
> Implement the file filter

- Makefile
- Makefile.release
- package-lock.json
- package.json
- webpack.dev.js
author Marlin Baumgart marlin.baumgart@serv3r.de 1538982006 +0200
committer Carsten Schildknecht carsten.schildknecht@serv3r.de 1538996991 +0200
Added webpack-dev-server and adjusted npm run watch to fit the needs.
Referring Issue #257
[Original Commit](https://github.com/serv3r/phoenix/commit/bee3485c9db3d5eb41427254f4e899d5f3dcd3bd)
> webpack-dev-server as npm run watch

- index.html
- package-lock.json
- package.json
Added Accessibility tests with axe-cli.
Usage:
` npm run accessibility-tests localhost:8300`
Regarding Issue https://github.com/owncloud/phoenix/issues/252
> added axe-cli as accessibility-test and fixed violations

- config.json.dist
- config.json.sample
- src/default.js
- src/services/auth.js
- src/store/auth.js
- src/store/index.js
* adjusted sample config, containing the oAuth api url & token
* inject config into vuex
* use oAuth config from vuex
* mutation names adopted
> refs #302 use oAuth config from vuex

- .gitignore
- nightwatch.conf.js
- tests/acceptance/setup-local.js
- tests/acceptance/stepDefinitions/loginContext.js
Fixes webUI accepectence tests to run tests locally. 
Now, there will be no need to run `selenium-server` separately.
> Fix webUI accepectance tests to run tests locally

- src/components/Menu.vue
> Apps can be opened in tab on their own

- README.md
- fixed typo
- set install steps into unnumbered list
- dev server: changed make to yarn
> README.md dev server correction

- .githooks/pre-commit/eslint.sh
- package.json
- yarn.lock
eslint will verify the code style before commit.
#268
> Add pre-commit hook to lint the code

- apps/files/src/components/Files-App.vue
- apps/files/src/store.js
Little fix for the store
Not yet...
> get js-oc-client into store

- apps/files/src/components/Files-App.vue
- apps/files/src/store.js
The user can set or remove the favorite marker
- :construction:
> Favorite a file

- apps/files/src/components/DirTable.vue
- apps/files/src/components/FileDetails.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/store.js
- src/default.js
> Implementing delete of selected files

- apps/files/src/components/FileDetails.vue
- src/store/user.js
Files can now be downloaded
- manual
> Implement download

- apps/files/src/FileUpload.js
- apps/files/src/components/DirTable.vue
- apps/files/src/components/FileDetails.vue
- apps/files/src/components/FileUpload.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/default.js
- apps/files/src/mixins.js
- apps/files/src/store.js
- apps/files/webpack.common.js
Adding upload capability for a single file
- refs #166 
- upload a file
- see the progress spinner
- see the file appearing
> implement single file upload

- apps/files/package.json
- apps/files/yarn.lock
Bumped all dependencies of file app manually 
- Closes #145 
- Closes #177 
- Closes #179  
N/A
N/A
> Bump all filesApp dependencies

- src/pages/login.vue
- src/services/auth.js
- src/store/index.js
- src/store/user.js
improve security by detecting invalid oauth token.
improve dataflow in vuex auth wrapper, derive default auth state to provide fallback values instead of re-init the vue-authenticate lib inside getters
security fixes & cleanup in auth service wrapper
- login
- delete vue auth cookie
- reload
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Code changes
> Improve security by detecting expired oauth token in vue-authenticate wrapper

- src/services/auth.js
ownCloud will support OpenID Connect in the future. This adds the support to phoenix
Phoenix is used as first test client in the OpenId Connect analysis phase
> Add support for OpenId Connect

- .drone.yml
- Dockerfile
One docker image to rule them all .... well - Phoenix
https://github.com/owncloud/storage/issues
- within docker-compose in https://github.com/owncloud/storage
> Add simply Dockerfile - config.json has to be mounted

- apps/markdown-editor/package.json
- apps/markdown-editor/yarn.lock
- package.json
- yarn.lock
bump vuex in core & markdown-editor
- skip dependabot & test locally
> bump vuex as core dependencies

- apps/pdf-viewer/package.json
- apps/pdf-viewer/yarn.lock
- tests/drone/config.json
markdown-editor and pdf-viewer shall be built on drone as well
> Build markdown-editor and pdf-viewer in drone

- src/components/Top-Bar.vue
- src/default.js
- src/pages/login.vue
- src/store/config.js
- static/config.default.json
- themes/owncloud.json
- webpack.common.js
Fixes 'Whitescreen of Death' when no config.json is existing or some apps are missing but mentioned in config.json. If missing this will be displayed on login page. If apps are missing or corrupted phoenix will tell the user, by displaying a red info icon next to the user-icon, on click a menu will show additional information.
- Fixes #515 
- Closes #520 
The Whitescreen is not userfriendly and doesnt offer a good UX
- :hand:
> fix whitescreen of death

- .drone.yml
Building the docker image should be part of the CI process ... later we can even use the image for testing ....
- :robot:
> Use docker plugin to build the image

- apps/markdown-editor/src/MarkdownEditor.vue
Topbar in Markdown-Editor now is visible again and markdown-editor can be used again.
- Fixes #519
I want to write markdown files in live-preview mode again.
- :hand:
> Fix missing Top Menu in Markdown-Editor

- tests/acceptance/features/webUIFiles/createFolderEdgeCases.feature
- tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
- tests/acceptance/features/webUIFiles/fileDetails.feature
- tests/acceptance/features/webUIFiles/hiddenFile.feature
- tests/acceptance/features/webUIFiles/scrollMenuIntoView.feature
This PR adds features files from core. 
These files add tests for file operations in Pheonix app. 
#498 
🤖
> Add feature files for filesApp tests

- apps/files/package.json
- apps/files/yarn.lock
- apps/markdown-editor/package.json
- apps/markdown-editor/yarn.lock
- apps/pdf-viewer/package.json
- apps/pdf-viewer/yarn.lock
- package.json
- yarn.lock
* vue-loader 15.6.0 -> 15.6.2
- Fixes #558
- Fixes #559
- Fixes #560
- Fixes #561  
- :hand:
> bump vue-loader

- tests/acceptance/features/webUILogin/login.feature
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/loginContext.js
improve acceptance-tests
about 70% of all drone build fails...
force-push to restart the pipeline builds is no solution!
The race condition in our acceptance tests was really time-expensive for all of our developers, but i may fixed it.
- 42 times `yarn acceptance-tests`
- 23 times `yarn acceptance-tests` on @tempelgogo notebook
> remove race condition in acceptance tests

- apps/files/src/components/FileList.vue
- apps/files/src/components/FilesApp.vue
- src/store/user.js
Allow Bookmarking of directorys from FilesApp in your browser! Working DeepLinks for Directorys :)
`localhost:8300/#/files/list/Foldername` is now fully working, if it's no file linked.
Rewritten for OIDC
- close #547
- replace & close #551
DeepLinks for folder yeah
by calling the URI mentioned before. You should own a directory "Foldername" on your OC. It should contain files for the sense of achievement, if you see them on reload :)
> remove encoded slash from file uri & allow directory deep links

- apps/files/src/components/FileUpload.vue
Add error handling for file upload. 
If file exists on Client and Server decline upload. Open notification with error message.
- Refs #476
- :hand:
> add conflict handling for existing files

- apps/files/src/components/FileDetails.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesTopBar.vue
- apps/files/src/default.js
- apps/markdown-editor/package.json
- apps/markdown-editor/src/MarkdownEditor.vue
- apps/markdown-editor/src/MarkdownEditorTopbar.vue
- apps/markdown-editor/src/app.js
- apps/markdown-editor/src/store.js
- apps/markdown-editor/webpack.config.js
- apps/markdown-editor/yarn.lock
- apps/pdf-viewer/src/PdfViewer.vue
- apps/pdf-viewer/src/PdfViewerTopbar.vue
- apps/pdf-viewer/src/app.js
- apps/pdf-viewer/src/store.js
- apps/pdf-viewer/webpack.common.js
- index.html
- src/Phoenix.vue
- src/components/Menu.vue
- src/components/OcAppTopBar.vue
- src/components/Top-Bar.vue
- src/router/index.js
* New Topbar component. 
* Less vuetify. 
* Apps got their own topbars
* named routes
* appContent
* appTopbar
* fullscreen
* fixed markdown-editor open bug
- Fixes #590
- Refs #576
- Refs #577
- Refs #579
- :hand:
> Fixed topbar and named routes

- apps/files/package.json
- apps/files/yarn.lock
- apps/markdown-editor/package.json
- apps/markdown-editor/yarn.lock
- apps/pdf-viewer/package.json
- apps/pdf-viewer/yarn.lock
- package.json
- yarn.lock
bump webpack.
- Fixes #634 
- Fixes #635  
- Fixes #637  
- Fixes #636
> bump dependencies

- README.md
adopt `README.md` to new npm script names.
- `yarn run`
- read list
> adopt README to new run script names

- apps/files/src/components/FilesTopBar.vue
The upload spinner was no longer displayed - regression in #660 
- Fixes #667 
- upload multiple files
- see the spinner
> Show upload spinner

- apps/files/src/components/FileDetails.vue
- apps/files/src/components/FileInfoVersions.vue
- apps/files/src/components/FileactionsTab.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/default.js
- apps/files/src/store.js
- src/Phoenix.vue
- src/components/OcAppContent.vue
- src/components/OcList.vue
This PR will introduce the Versions-Tab to the Files-App.
- Refs #639  
- Fixes #579
> introduce file versions

- apps/files/src/components/FilesTopBar.vue
Remove text from upload menu
- fixes #578
> Remove header from upload menu

- apps/files/src/components/FileactionsTab.vue
Fixes download file action
- click on a file
- see actions tab sliding in
- click download
- see download happen
> Add getter getToken to file action tab to fix download

- apps/files/src/components/FileList.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesTopBar.vue
- apps/files/src/mixins.js
- apps/files/src/store.js
- nightwatch.conf.js
- src/components/form/SearchBar.vue
- tests/acceptance/stepDefinitions/loginContext.js
follow up of https://github.com/owncloud/phoenix/pull/666
> Files global search 3

- apps/files/webpack.common.js
- apps/files/webpack.dev.js
- apps/markdown-editor/src/app.js
- apps/markdown-editor/webpack.config.js
- apps/pdf-viewer/webpack.common.js
- apps/pdf-viewer/webpack.dev.js
- nightwatch.conf.js
- src/default.js
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
Pseudocode: `ESLint --fix *.js`
- refs #697
it's hard to auto-fix files if people are collaborating on it.
There's no PR against this files open currently, so I've used the chance.
- drone :+1: 
Hopefully nothing changed
> lint-fix webpack files

- apps/files/src/components/FileInfoSidebar.vue
- apps/files/src/components/FileInfoVersions.vue
- apps/files/src/store.js
- src/Phoenix.vue
- src/components/OcAppSideBar.vue
- src/components/OcAppTopBar.vue
- src/components/OcList.vue
Fix Sidebar behavior on smaller screens and sidebar confusion if multiple files selected as descriped in #672 
- Fixes #672 
- test resolution: 1024x768 768x1024
> fix sidebar behavior on smaller screens

- src/components/Top-Bar.vue
Primary theme color is not respected in the top bar
- use example theme in config.json
- :eye:
> Allow theming of top bar

- apps/files/src/components/FileList.vue
- apps/files/src/mixins.js
- apps/files/src/store.js
- Fixes https://github.com/owncloud/phoenix/issues/651
- test case 1:
- test case 2:
- ...
> Added rename function to files and folders

- src/Phoenix.vue
- src/components/OcAppSideBar.vue
We need a larger side bar -> 500px for now. Will not work on mobile -> known ...
> Use 500px width on sidebar

- apps/files/src/components/FileDetails.vue
- apps/files/src/components/FileFilterMenu.vue
- apps/files/src/components/FileList.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesTopBar.vue
- apps/files/src/components/ocDialogPrompt.vue
- apps/files/src/mixins.js
- apps/files/src/store.js
- src/Phoenix.vue
- src/components/Menu.vue
- src/components/OcAppSideBar.vue
- src/components/form/SearchBar.vue
Fix some issues based on review by @hodyroff 
fixes #781 
- :hand:
> Fix sidebar width once more, fix sidebar close and fix tab open

- apps/files/src/components/FileList.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesTopBar.vue
- apps/files/src/components/ocDialogPrompt.vue
- nightwatch.conf.js
- package.json
- tests/acceptance/features/webUIFiles/createFolders.feature
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/setup-drone.js
- tests/acceptance/setup-local.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/loginContext.js
- tests/acceptance/stepDefinitions/provisioningContext.js
- yarn.lock
Implementing first acceptance scenario
Scenario: Create a folder inside another folder
- refs #682 
Quite simple: we need tests to protect the project from regressions and ensure to meet the acceptance criteria
- run the acceptance tests local
- or watch :robot:
> [ACCEPTANCE] Scenario: Create a folder inside another folder

- tests/acceptance/features/webUIFiles/createFolderEdgeCases.feature
- tests/acceptance/pageObjects/filesPage.js
test cases for folders with special characters
part of #844
> Create folder edge cases

- tests/acceptance/pageObjects/filesPage.js
to navigate into a subfolder click on the folder item
part of #844 
testing the UI we want to see if the clicking on a folder item takes the user where it should
so far the tests modified the URL, but no user does that
> click on folder item to navigate in tests

- nightwatch.conf.js
- tests/acceptance/customCommands/initAjaxCounters.js
- tests/acceptance/customCommands/waitForAjaxCallsToStartAndFinish.js
- tests/acceptance/customCommands/waitForOutstandingAjaxCalls.js
- tests/acceptance/features/webUIFiles/hiddenFile.feature
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
tests to show hidden files/folders
part of #844
> [acceptance tests] Create hidden folder

- apps/files/src/components/FilesApp.vue
- apps/markdown-editor/src/MarkdownEditor.vue
- apps/markdown-editor/src/MarkdownEditorTopbar.vue
Fixed opening selected file with markdown editor and replaced old vuetify components with oc components and UIkit.
- [ Fix problem with CORS after attempting to save the file ] ...
> Fixed opening file with markdown editor and replaced vuetify

- README.md
- package.json
- webpack.common.js
- yarn.lock
grabbing ods from 
https://www.npmjs.com/package/owncloud-design-system
> Add ods from npmjs.com

- apps/files/src/components/FileList.vue
- src/components/Avatar.vue
- src/store/user.js
Added :value to checkboxes to get rid of selection (), added condition for resetting of selection and fixed problems causing errors in compilation.
> Fixed checking all boxes when using checkbox in top bar

- apps/files/src/components/FilesTopBar.vue
Fixed clearing the search query by calling search function in ods search component and added a condition to loading to prevent infinite loading when the searchTerm is empty.
> Removed value of search and added condition for loading

- apps/files/src/FileUpload.js
Removed FormData from file upload. I'm not sure if this was a good thing to do so I would like to discuss it here. After testing everything still worked fine and it actually fixed the problem with extra content in text files after uploading. I came up with this solution after seeing this - https://stackoverflow.com/questions/55420393/form-boundary-is-being-written-to-my-file-when-i-upload-to-server-making-it-cor
- Fixes #889 
> Fixed file upload

- apps/files/src/components/OcCollaborationStatus.vue
well - translate some strings ...
> Translate user facing strings

- apps/files/src/components/FileDetails.vue
- apps/files/src/components/FileInfoVersions.vue
- apps/files/src/components/FileList.vue
- apps/files/src/mixins.js
- apps/files/src/store.js
File version sidebar is back now ...
- :hand:
> Bring back file versions

- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
feature files for renaming files and folders
part of #844 
features were copied from core and are currently skipped here, most steps will have to be implemented in JS
> feature descriptions for renaming files and folders

- apps/files/src/components/FileList.vue
- tests/acceptance/customCommands/initAjaxCounters.js
- tests/acceptance/customCommands/waitForAnimationToFinish.js
- tests/acceptance/customCommands/waitForOutstandingAjaxCalls.js
- tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/webdavContext.js
test if deleting files & folders works correctly
- part of #844
> tests to delete files

- tests/acceptance/features/webUIFiles/versions.feature
feature files for the versions feature
part of #844 
features were copied from core and are currently skipped here, as the versions tab is not implemented in phoenix yet and also the test steps need to be implemented in nightwatch.js
> descriptions for the versions feature

- tests/acceptance/features/webUIFiles/search.feature
feature files for the search feature
part of #844 
features were copied from core and are currently skipped here, as the test steps need to be implemented in nightwatch.js
also the system-tags feature is not yet implemented in phoenix
> descriptions for the search feature

- tests/acceptance/features/webUIFavorites/favoritesFile.feature
- tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
feature files for the favorites feature
part of #844 
features were copied from core and are currently skipped here, as the favorites page is not implemented in phoenix yet and also the test steps need to be implemented in nightwatch.js
> feature descriptions for favorites

- tests/acceptance/features/webUIComments/comments.feature
feature files for the comments feature
part of #844 
features were copied from core and are currently skipped here, as the feature is not implemented in phoenix yet
> feature descriptions for comments

- tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
- tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
feature files for the moving feature
part of #844 
features were copied from core and are currently skipped here, as moving via drag&drop is not implemented in phoenix yet and also the test steps need to be implemented in nightwatch.js
> descriptions for the moving feature

- tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
- tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
- tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
feature files for the various sharing restriction features
part of #844 
features were copied from core and are currently skipped here, as the sharing tab is not implemented in phoenix yet and also the test steps need to be implemented in nightwatch.js
> descriptions of various sharing restriction features

- tests/acceptance/features/webUITags/createTags.feature
- tests/acceptance/features/webUITags/tagsSuggestion.feature
feature files for the tags feature
part of #844 
features were copied from core and are currently skipped here, as the tags feature is not implemented in phoenix yet and also the test steps need to be implemented in nightwatch.js
> descriptions of the tags feature

- tests/acceptance/features/webUITrashbin/trashbinDelete.feature
- tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
- tests/acceptance/features/webUITrashbin/trashbinRestore.feature
feature files for the trashbin feature
part of #844 
features were copied from core and are currently skipped here, as the trashbin page is not implemented in phoenix yet and also the test steps need to be implemented in nightwatch.js
> descriptions of the trashbin feature

- tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
- tests/acceptance/features/webUISharingExternal/federationSharing.feature
- tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalGroups/shareWithGroupsEdgeCases.feature
- tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/features/webUISharingNotifications/notificationLink.feature
- tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature
- tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
feature files for the various sharing features
part of #844 
features were copied from core and are currently skipped here, as the sharing feature is not implemented in phoenix yet and also the test steps need to be implemented in nightwatch.js
> descriptions of various sharing features

- tests/acceptance/features/webUIUpload/upload.feature
- tests/acceptance/features/webUIUpload/uploadEdgecases.feature
- tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
feature files for the upload feature
part of #844 
features were copied from core and are currently skipped here, as the test steps need to be implemented in nightwatch.js
> descriptions of the upload feature

- src/components/Avatar.vue
- src/components/Top-Bar.vue
> Use oc-nav-bar to implement Top-Bar

- package.json
- src/components/Menu.vue
- yarn.lock
basically imports ODS changes https://github.com/owncloud/owncloud-design-system/pull/217
> Use new application menu design

- apps/files/src/components/FilesTopBar.vue
Used upload menu component from ODS.
- Fixes #901 
> Added upload menu component

- README.md
update the documentation to the current status
prepare for tomorrows training
> update documentation about running tests

- apps/files/src/store/actions.js
Added curly brackets to fix import of map
- Fixes #967 
> Fixed map import

- README.md
some small changes and clarifications about acceptance tests
enable others to use the magic
> improve documentation about running acceptance tests

- tests/acceptance/features/webUIFiles/search.feature
- tests/acceptance/helpers/httpHelper.js
- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/stepDefinitions/provisioningContext.js
- tests/acceptance/stepDefinitions/searchContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
some acceptance tests for the search feature
part of #844
> Search tests

- apps/files/src/components/FilesApp.vue
- apps/markdown-editor/src/MarkdownEditor.vue
- apps/markdown-editor/src/MarkdownEditorTopbar.vue
- apps/markdown-editor/src/store.js
- package.json
- src/phoenix.js
- yarn.lock
Use https://www.npmjs.com/package/owncloud-sdk instead of git clone
- refs #891 
- :hand:
> Use owncloud-sdk from npmjs.com

- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesTopBar.vue
- apps/pdf-viewer/src/PdfViewer.vue
- src/pages/oidcSilentRedirect.vue
- src/phoenix.js
- src/store/user.js
- tests/acceptance/features/webUIFiles/createFolders.feature
The elipsis character shall be used in favor for 3 dots.
Have proper text
> Use elipsis character instead of 3 dots

- apps/files/package.json
- apps/files/src/components/FileDrop.vue
- apps/files/src/components/FileUpload.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesTopBar.vue
- apps/files/src/mixins.js
- apps/files/src/store/actions.js
- apps/files/src/store/getters.js
- apps/files/src/store/mutations.js
- apps/files/src/store/state.js
- apps/files/yarn.lock
Added support for drag and drop and moved upload into mixins so it can be used by it without duplicating the functions. First needs to be merged oc-dropzone component in ods.
- Fixes #880 
> Added drag and drop

- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
Remove `@skip` from tests that are passing currently.
#844
Add more tests
🤖
> Remove skips from tests that are passing

- tests/acceptance/features/webUIAdminSettings/adminAppsSettings.feature
- tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
- tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
- tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
- tests/acceptance/features/webUIAdminSettings/helpAndTips.feature
Add features files for testing admin settings page
#844
Add more tests
🤖
**Note** This features are yet to be implemented in Phoenix.
> Add description feature files for adminSettings page tests

- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
just added a tag for clarification
> tag test that is skiped because of #965

- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesTopBar.vue
- apps/files/src/default.js
- apps/pdf-viewer/src/PdfViewer.vue
- apps/pdf-viewer/src/PdfViewerTopbar.vue
- tests/acceptance/features/webUIFiles/createFolderEdgeCases.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
- tests/acceptance/pageObjects/filesPage.js
> allow folders to be named <home>

- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/pageObjects/phoenixPage.js
> test to rename to names containing a '/'

- src/pages/oidcCallback.vue
Reused components from login page at redirection page.
> Reused login components at redirection

- apps/files/src/store/getters.js
Until now the file list was unsorted. With this change the file list is sorted ascending by the file name.
- :hand:
> Apply basic sorting to file list

- tests/acceptance/features/webUIUpload/upload.feature
- tests/acceptance/features/webUIUpload/uploadEdgecases.feature
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/generalContext.js
more tests for uploading files. specially for edge cases and bug files
even chunking upload is not implemented yet the upload should work and should work the same after chunking upload is implemented
part of #844
> upload test for edge cases and big files

- apps/files/src/components/FileUpload.vue
Hotfix for usage of oc-nav-item in upload file component.
> Used oc-nav-item component

- tests/acceptance/customCommands/toggleCheckbox.js
- tests/acceptance/features/webUIFiles/filter.feature
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
Add webUI tests for file/folder filter.
#844
Add more tests
🤖
> Add tests for file/folder filter

- tests/acceptance/customCommands/toggleCheckbox.js
- tests/acceptance/customCommands/uploadLocalFile.js
- tests/acceptance/helpers/httpHelper.js
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/pageObjects/phoenixPage.js
Use jsDoc string for better code readability and understanding function better. 
🤖
> Use jsDoc string in test code functions

- tests/acceptance/features/webUIFavorites/favoritesFile.feature
- tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
Add webUI tests file/folder favorite
#844
Add more tests
🤖
> Add tests for file/folder favorite

- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesTopBar.vue
- apps/files/src/mixins.js
- apps/files/src/store/actions.js
- apps/pdf-viewer/src/PdfViewer.vue
Replaced type prop with status and its value from error with danger in notifications to display correct variation.
> Fixed notifications status prop

- .drone.yml
Only run build-docker-image on pull request merge
#844
Make drone faster
🤖
> Only run build docker image on merge

- .drone.yml
- package.json
Split acceptance tests into different drone matrix
to run them in parallel
#1056
Decrease test run time
🤖
- [] Acceptance tests added
> Add drone matrix to run tests in parallel

- tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
- tests/acceptance/helpers/httpHelper.js
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/stepDefinitions/provisioningContext.js
Upload a file that would exceed the set quota
> tests for upload that would exceed the quota

- config.json.dist
- config.json.sample
Fix invalid auth key in config.json
Make drone faster
🤖
> Fix auth url in config.json sample

- apps/files/src/components/FileDetails.vue
- apps/files/src/components/FileList.vue
- apps/files/src/components/FileSharingSidebar.vue
- apps/files/src/components/ocDialogPrompt.vue
- src/components/Menu.vue
- src/pages/login.vue
- tests/acceptance/pageObjects/filesPage.js
Moved strings from text and title props inside of components.
> Moved strings inside of components

- src/services/auth.js
This fixes https://phoenix.owncloud.com/custom/phoenix/index.html#/login
Fix demo for @michaelstingl 
- start local instance using localhost:8300/index.html
- auth flow shall work
> index.html needs to be cut from the url when building the redirect uri

- apps/files/package.json
- apps/files/src/components/FileInfoSidebar.vue
- apps/files/src/components/FileList.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/mixins.js
- apps/files/src/store/actions.js
- apps/files/src/store/mutations.js
- package.json
- src/mixins/pluginHelper.js
- src/phoenix.js
- src/store/app.js
- src/store/apps.js
- yarn.lock
Removed lodash from the package.json and replaced it with ES6 syntax
- Fixes https://github.com/owncloud/phoenix/issues/1111
- tested for console errors while calling every "new" method
> Removed lodash

- .gitignore
- apps/files/src/components/FileList.vue
- apps/files/src/components/FileSharingSidebar.vue
- apps/files/src/default.js
- apps/files/src/store/actions.js
- src/services/auth.js
- tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/loginContext.js
- tests/acceptance/stepDefinitions/provisioningContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
Sharing with groups is now possible
- refs #583 
- :hand:
> Add group sharing

- src/store/config.js
Set `String` types instead of `null` values in config store.
No annoying error in menu component anymore.
> Set String types instead of null values in config store

- tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/loginContext.js
- tests/acceptance/stepDefinitions/provisioningContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
Add acceptance tests for sharing with a user and sharing with the group.
Note: there are some features still missing like sharee cannot see who shared the file/folder with them, Hence those steps are skipped.
#844
Add more tests
🤖
> Add tests for sharing

- tests/acceptance/features/webUIFavorites/favoritesFile.feature
- tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/pageObjects/favoritesPage.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/loginContext.js
- tests/acceptance/stepDefinitions/webdavContext.js
1. implement tests for favorites
2. refactor FilesPage so that the files list gets into its own pageObject. This is because the list is already on two "pages" and will be used on more later
> more tests for favorites feature

- src/components/Menu.vue
- src/components/Top-Bar.vue
- src/pages/account.vue
- src/router/index.js
Created basic account page where user can preview his username, display name, email and groups, logout button at account page and replaced button with oc-button in top-bar.
> Personal settings

- apps/files/src/components/FileList.vue
- apps/files/src/components/FilesTopBar.vue
- apps/files/src/components/ocDialogPrompt.vue
- tests/acceptance/features/webUIFiles/createFolders.feature
- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/generalContext.js
It's now impossible to create folder (names) containing "/"
- Fixes https://github.com/owncloud/phoenix/issues/1047 and https://github.com/owncloud/phoenix/issues/965
- tried to create a folder containing "/" somewehere
- tried to create a folder starting with "./" "../"
- tried to force creation illegally by clicking the button and pressing enter
> Validate folder names

- apps/files/src/components/FilesApp.vue
> Moved dropzone trigger into files list wrapper

- src/components/Menu.vue
Added watcher for route change that calls action for closing menu.
- test case 1: Open menu and navigate to other route
> Close menu after change of route

- apps/files/src/default.js
> Fixed link for files list

- src/services/auth.js
- src/store/config.js
- src/store/user.js
Some OpenIdConnect setups require a very detailed confguration.
- :running_man:
> Allow more detailed configuration of OpenIdConnect

- apps/files/src/components/FileInfoVersions.vue
Fix download of file versions in IE11
- Fixes #1250 
- :hand:
> Fixes #1250 - fix download of a file version

- apps/files/src/mixins.js
Skip rename when user didn't change the file/folder name
- Fixes #1233 
Bugfix :P 
- create folder 'A'
- create file 'B.txt'
- rename file 'B.txt' to 'B.txt' (no changes)
- rename dialog prompt should close without any changes
- rename file 'B.txt' to 'A'
- error message that 'A' already exists should appear
> Skip rename when user didn't change the file/folder name

- package.json
retry tests that are failing
currently using directly the branch with the fix, waiting for it to be merged https://github.com/cucumber/cucumber-js/pull/1205
make CI more stable
that how it looks when it failed also the second time
> retry failing acceptance tests

- src/services/auth.js
- src/store/user.js
Properly trigger sign-out-url upon logout
- Fixes #1262
> On logout trigger OAuth/OpenIdConnect sign-out-url

- .drone.yml
- apps/files/src/components/FileList.vue
- package.json
- tests/acceptance/features/webUIFiles/hiddenFile.feature
- tests/acceptance/features/webUIUpload/upload.feature
- tests/acceptance/features/webUIUpload/uploadEdgecases.feature
- tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/generalContext.js
- tests/acceptance/stepDefinitions/loginContext.js
ability to run UI tests in various resolutions
currently running full screen of selenium docker (1360x882) and 800x600
I've also added a tag for skipping tests that fail in the lower resolution
currently only smoke tests run in the lower resolution
- Fixes #1198
> running smoke tests in low resolution

- apps/files/src/components/ocDialogPrompt.vue
Disabled confirm events(click and enter press) for the rename, new folder, new file dialog prompts 
- Fixes #1231 
- Tried to create a new folder without any input in the dialog prompt by pressing enter and clicking confirm
- Tried to create a new file without any input in the dialog prompt by pressing enter and clicking confirm
- Tried to rename a  file/folder without any input in the dialog prompt by pressing enter and clicking confirm
> Disable confirm event if oc dialog input value is empty

- apps/markdown-editor/src/MarkdownEditorTopbar.vue
Fixed the markdown editor app bar offset unit to fix the components visibility 
- Fixes #1229 
- Created a new .txt file
- Opened with markdown editor app
- Checked if the markdown input textarea got rendered fully
> Fixed markdown app topbar offset

- src/store/user.js
Added trigger of login action in case the redirect promise fails at the callback page.
If user goes back to the callback page he doesn't get stuck now.
> Fix callback page

- apps/files/src/store/actions.js
No idea why I made viewer role consist of read, write and delete ... has been a while since I fell deeply in love with bitfcking ... oh wait ... that never happened ...
> parse viewer role properly

- .drone.yml
just make it easier to find the failed job
> show link to drone job when tests failed

- tests/acceptance/features/webUIFiles/hiddenFile.feature
- tests/acceptance/features/webUIUpload/upload.feature
- tests/acceptance/features/webUIUpload/uploadEdgecases.feature
- tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
- tests/acceptance/pageObjects/phoenixPage.js
this should have been fixed in #1331 so let the test run
- #1270
> unskip tests that were skipped because of #1270

- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/stepDefinitions/filesContext.js
this code was added in #1196 but never used, so better get rid of it
deleted code is debugged code
:robot: 
CI passing == code not needed
> delete unneeded code

- apps/files/src/components/FilesAppBar.vue
- apps/files/src/mixins.js
Prevent creation/rename of folder/file if the name is equal to "." or "..".
- Fixes #1327
- test case 1: Try to create a file with name "." or ".."
- test case 2: Try to create a folder with name "." or ".."
- test case 3: Try to rename a folder or a file with name "." or ".."
> Check if the name is equal to . or ..

- .drone.yml
- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesAppBar.vue
- apps/files/src/mixins.js
- apps/files/src/store/actions.js
- apps/pdf-viewer/src/PdfViewer.vue
- src/Phoenix.vue
- src/components/MessageBar.vue
- src/components/Notifications.vue
- src/components/Top-Bar.vue
- src/store/app.js
- tests/acceptance/features/webUIFavorites/favoritesFile.feature
- tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
- tests/acceptance/features/webUIUpload/upload.feature
- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/stepDefinitions/generalContext.js
- tests/acceptance/stepDefinitions/notificationsContext.js
Created notifications panel and store
- Fixes #1154 
- Generate a command using the cli: `./occ notifications:generate -u admin -l http://owncloud.org -- 'Phoenix has been updated to version 215.34' 'This is an unbelievable cool feature'`
- Phoenix should fetch every 30 seconds for new notifications
- Tested link behavior as well
> Created notifications panel and store

- apps/files/src/components/FileSharingSidebar.vue
- tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/stepDefinitions/provisioningContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
Added webui Acceptance test for checking the delete share button works.
:robot:
> Add acceptance test for deleting share

- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesAppBar.vue
- apps/files/src/components/Trashbin.vue
- apps/files/src/default.js
- apps/files/src/store/actions.js
- apps/files/src/store/getters.js
- apps/files/src/store/mutations.js
- apps/files/src/store/state.js
- package.json
- src/Phoenix.vue
- src/store/config.js
- src/store/user.js
- yarn.lock
Added trashbin into Phoenix
- Fixes #273 
- test case 1:
- test case 2:
- ...
> Added trashbin

- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesAppBar.vue
- apps/files/src/default.js
- src/store/config.js
- tests/drone/config.json
Added root folder into configuration store and allowed it to be changed.
> Allow change of root folder

- apps/files/src/components/FileDetails.vue
- apps/files/src/components/FilesApp.vue
We already talked in channel that the width needs to be adjusted because of acls. I even think it was done but it's gone so here we go again.
Fixes #1344 
> Adjusted width of sidebar and allowed scroll in it

- nightwatch.conf.js
be smart and add the protocol if its not there
be more gracious
> add protocol to LOCAL_LAUNCH_URL if its not given

- src/router/index.js
The account page did not display anything
- :hand:
> Fix account page

- apps/files/src/components/FileList.vue
Removed hide and show classes from drop component in file list actions to prevent permanent visibility and position.
> Fix dropdown in file list actions

- src/mixins/imageSrc.js
- src/phoenix.js
Easy authenticated image loading.
Usage:
```html
```
> Add simple auth image loader

- apps/files/src/components/FilesAppBar.vue
Fixed bug with uploading a file to the root of file list instead of newly set root folder.
> Fix creation and upload of files in root folder

- apps/files/src/components/FilesApp.vue
Moved oc-scroll-offset from file list into app content container to ensure right height for every child.
> Fixed height of app content

- .gitignore
- package.json
- src/components/Menu.vue
- src/version.ejs
- webpack.common.js
- yarn.lock
Version and build information are displayed in the menu bottom now
- Fixes #1294 
- :hand:
> Adding version, git hash and build time to menu

- apps/files/src/mixins.js
Different messages have been used in different code locations.
This PR syncs them
> Use the same messages - less work for translators then

- apps/files/src/components/FileList.vue
- apps/files/src/components/FilesAppBar.vue
- apps/files/src/mixins.js
- apps/files/src/store/actions.js
- apps/files/src/store/getters.js
- apps/files/src/store/mutations.js
- apps/files/src/store/state.js
- apps/files/yarn.lock
- apps/markdown-editor/yarn.lock
- apps/pdf-viewer/yarn.lock
- yarn.lock
Multiple files can now be selected and deleted
- :hand:
> Support deleting multiple files in files app

- apps/files/src/components/FilesAppBar.vue
> Stop loading if search failed

- .drone.yml
use MySQL as database for acceptance tests
- Fixes #1492 
:robot:
> use MySQL for acceptance tests

- tests/acceptance/features/webUITrashbin/trashbinDelete.feature
Skip failing test due to file lock issue (https://github.com/owncloud/phoenix/issues/1502)
> Skip failing trashbin test due to file lock issue

- apps/files/src/components/FileList.vue
- tests/acceptance/customCommands/toggleCheckbox.js
- tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
Add tests to batch delete files/folders
🤖
> Add tests for deleting multiple files/folder at once

- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
Reimplements test for renaming a file to "." and ".." with correct error message
https://github.com/owncloud/phoenix/issues/1507
> Reimplementation for renaming a file to "." and ".."

- package.json
- tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
- tests/acceptance/features/webUITrashbin/trashbinRestore.feature
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/webdavContext.js
Add more tests related to trashbin.
- Related issue #1488 
:robot:
> Add trashbin related tests

- tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
- tests/acceptance/stepDefinitions/provisioningContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
```    Given these users have been created but not initialized:``` doesn't add password, displayname and email information while creating user. This test make sure these informations are also added while creating user.
This test also includes test to make sure that a particular user is not displayed in the autocomplete list of sharing dialog.
https://github.com/owncloud/phoenix/issues/1476
> adding password, displayname, email in given step where users are created but not initialized

- tests/acceptance/features/webUITrashbin/trashbinDelete.feature
- tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
- tests/acceptance/features/webUITrashbin/trashbinRestore.feature
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/stepDefinitions/filesContext.js
Includes remaining implementation of ```webUITrashbin```
https://github.com/owncloud/phoenix/issues/1488
> trashbin features 

- apps/files/src/components/FileSharingSidebar.vue
Moved heading outside of accordion.
> Fixed opening group accordion in collaborators

- apps/files/src/components/Collaborators/Collaborator.vue
- tests/acceptance/features/webUISharingExternal/federationSharing.feature
- tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
- tests/acceptance/features/webUIWebdavLocks/locks.feature
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/stepDefinitions/provisioningContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
re-enable and refactor the very basic check & delete collaborators tests, much more tests need to be done
- Fixes #1570 
:robot:
> Test deleting collaborators

- src/plugins/mediaSource.js
Removed name MediaSource from export in the directive and moved install inside of export.
Working iOS 🙂 
> Fixed error about missing variable MediaSource

- apps/files/yarn.lock
- apps/markdown-editor/yarn.lock
- apps/media-viewer/yarn.lock
- apps/pdf-viewer/yarn.lock
- yarn.lock
> Upgrade dependencies 20190725

- tests/drone/config.json
This adds media-viewer to the test config which is also used to build the release which is pushed to the demo system
> Load media-viewer

- src/pages/missingConfig.vue
- src/phoenix.js
- webpack.common.js
In case config.json couldn't be loaded, use alternative function which will render missingConfig page.
- Refs #1153
- Rename config.json to different name
- Try to open Phoenix
> Added missing config page

- src/store/user.js
In case the token is refreshed we need to re-initialize the owncloud-sdk
> Re-init owncloud-sdk on token refresh

- apps/files/src/components/Collaborators/Collaborator.vue
- apps/files/src/components/Collaborators/mixins.js
- apps/files/src/components/FileSharingSidebar.vue
- apps/files/src/store/actions.js
- apps/files/src/store/getters.js
- apps/files/src/store/mutations.js
- apps/files/src/store/state.js
Added custom role in collaborators to allow selecting specific permissions.
- Fixes #1186 
> Added custom role

- apps/files/src/components/FileSharingSidebar.vue
Enable adding multiple users/groups via autocomplete in collaborators.
> Select multiple users/groups in collaborators

- apps/files/src/mixins.js
Return null in rename title in case no file is selected.
No translations warning
> Fixed translations warning in rename title

- apps/files/src/components/Collaborators/Collaborator.vue
Hide resharer in case he is the logged in user.
- Refs #1186
> Hide resharerer

- config.json.sample
Updated config.json.sample containing basic oauth without the client id.
Can work as a example for setting up Phoenix.
> Updated config.json.sample

- apps/files/src/components/Collaborators/mixins.js
By clicking on switch changing permission trigger also start of editing of collaborator
- Refs #1186 
> Allow save after clicking on permissions

- .drone.yml
stable10-qa no longer exists -> see https://github.com/owncloud/core/issues/35777
https://github.com/owncloud/core/issues/35777
> Switch to master-qa tar ball for the server

- apps/files/src/components/FileSharingSidebar.vue
Filter results also by emails to allow adding collaborators by their email address.
- Refs #1186
> Search by email

- apps/files/src/components/FilesAppBar.vue
- apps/files/yarn.lock
- apps/markdown-editor/yarn.lock
- apps/media-viewer/yarn.lock
- apps/pdf-viewer/yarn.lock
- yarn.lock
Current folder in breadcrumbs leads to reload
> Current folder in breadcrumbs leads to reload

- apps/files/src/components/FileList.vue
- apps/files/src/components/FilesAppBar.vue
- apps/files/src/mixins.js
- apps/files/src/store/actions.js
- package.json
- yarn.lock
- refs #1307 
- requires #1617
- create a public link in oc10 with the option 'download, view and upload'
- open the link in a private window
- see the folder contents
- upload files and folders and create folders and files
> PublicLinks: allow upload and creation of files and folders

- .drone.yml
double quoted lines 400 & 407 and ran `drone convert --save .drone.yml`
part of #1731
make CI pass
:robot:
> convert .drone.yml to drone 1.0

- apps/files/src/components/Collaborators/NewCollaborator.vue
- apps/files/src/store/actions.js
- Fixes #1718
1. Share file with other user with role `Viewer`
2. Change role of collaborator from `Editor` to `Viewer`
> Renamed perms key to permissions

- apps/files/src/components/ocDialogPrompt.vue
Added boolean hepler to detect clicks
- Fixes #1537 
- try to force the confirm button to send an other delete request when in the dialog prompt
> Block more then one click when deleting

- apps/files/src/components/ocDialogPrompt.vue
Added boolean hepler to detect clicks
- Fixes #1537 
- try to force the confirm button to send an other delete request when in the dialog prompt
> Block more then one click

- apps/files/src/components/FileDetails.vue
Added item id as a key to sidebar to ensure info is properly re-rendered after selecting different item.
1. Select a folder
2. Select a file
> Change icon in sidebar after selecting different item

- apps/files/src/components/FileDetails.vue
- apps/files/src/default.js
- Fixes #1751
1. Click on file row
2. Click on folder row
> Hide versions tab for folders

- apps/files/src/components/FileDrop.vue
- apps/files/src/components/FilesAppBar.vue
- apps/files/src/components/FolderUpload.vue
- apps/files/src/mixins.js
Added the base url when creating a folder
- Fixes https://github.com/owncloud/phoenix/issues/1587
- upload a folder via drag&drop/upload button in any folder which is not the base folder
> Respect folder structure when uploading

- apps/files/src/components/FileList.vue
- apps/files/src/components/FilesAppBar.vue
- apps/files/src/store/actions.js
- apps/files/src/store/getters.js
- apps/files/src/store/mutations.js
- apps/files/src/store/state.js
Added number of results, used space, last modification and total size to the bottom of the list.
Users now have more available informations.
> Added params to the end of the list

- apps/files/src/store/actions.js
1. Share file with multiple users and groups
> Check file id instead of share id in shared with others list

- tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/helpers/loginHelper.js
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/loginContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
add checks to make sure collaborator roles are set correctly
- tests for issues like #1718
- test case 1:
- test case 2:
- ...
> check collaborators permissions 

- apps/files/src/components/FileInfoVersions.vue
- Fixes #1722
- Fixes #1721
1. Select a file
2. Select different file
3. Click on restore version
> Reload versions after revert or selecting different file

- apps/files/src/components/Collaborators/SharedFilesList.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/default.js
- apps/files/src/mixins.js
- apps/files/src/store/actions.js
- Refs #1186 
1. Share file with user
2. Log in as that user
3. Navigate into Shared with me list
4. Accept pending share
5. Decline pending share
6. Accept pending share after declining it first
> Shared with me list

- apps/files/src/mixins.js
After delete action is done, clear highlighted file to close the sidebar.
- Fixes #1775
1. Select a file
2. Delete the file
> Close sidebar after delete action

- apps/files/src/components/Collaborators/Collaborator.vue
- apps/files/src/components/Collaborators/mixins.js
- apps/files/src/components/FileSharingSidebar.vue
- Refs #1186
1. Assign avatar to a user
2. Add collaborator with avatar
3. Add collaborator without avatar
4. Add group of collaborators
5. Delete collaborator which is under another collaborator
> Added avatars to collaborators list

- src/store/user.js
> Load groups in store

- src/pages/accessDenied.vue
> Update messages on access denied page

- apps/files/src/components/Collaborators/NewCollaborator.vue
Use first role as a default role
- Refs #1186
> Add default selected role for new collaborators

- apps/files/src/components/Collaborators/Collaborator.vue
- apps/files/src/store/actions.js
Recalculate roles based on permissions when saving.
- Fixes #1786 
Bugix
- checkout the description of #1786
> update collaborator role changes immediately

- apps/files/src/FileUpload.js
- apps/files/src/components/FilesAppBar.vue
- apps/files/src/mixins.js
Removed all unnecessary /'s in the upload path
https://github.com/owncloud/phoenix/issues/1586
Just a small bugfix
- Upload a folder using the folder upload button / drag & drop
- The upload path shouldn't contain unnecessary /'s
> Encode upload path

- apps/files/src/components/FileSharingSidebar.vue
Resets the collaboration edit vuex state when mounted
- Fixes #1796 
Small bugfix
- checkout the description of #1796 
- it should be fixed xD
> Unblock unfinished sharing input

- apps/files/src/components/Collaborators/NewCollaborator.vue
- tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- Fixes #1788
- Fixes #1787
1. Share a file with other user with role Editor
> Fixed permissions of editor

- apps/files/src/components/FileSharingSidebar.vue
- Fixes #1752
User knows he doesn't have sufficient permissions to reshare.
- test environment: Manual
> Added no permission for reshare message

- apps/files/src/components/Collaborators/Collaborator.vue
- tests/acceptance/customCommands/angryClick.js
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/stepDefinitions/sharingContext.js
check if changing the collaborators type works correctly
these tests are specifically for #1840
#1786
> tests for changing collaborators roles

- package.json
- yarn.lock
Adding new icons and datepicker
> Update ODS dependency

- apps/files/src/components/FilesAppBar.vue
- test environment: Manual
1. Mount external storage
2. Set quota to 0
3. Try to create or upload
> Ignore quota in external storage

- apps/files/src/components/Collaborators/AutocompleteItem.vue
- apps/files/src/components/Collaborators/NewCollaborator.vue
- apps/files/src/components/Collaborators/mixins.js
- apps/files/src/components/FileSharingSidebar.vue
- apps/files/src/store/actions.js
Add remote users into results of autocomplete and don't show them until they have the right format as mentioned in the requirements.
- Refs #1186
> Allow sharing with remote users

- apps/files/src/components/FileLink.vue
- apps/files/src/components/FileLinkForm.vue
- apps/files/src/store/actions.js
- package.json
- yarn.lock
Closes: https://github.com/owncloud/phoenix/issues/1307
Todos below are drawn from https://github.com/owncloud/phoenix/issues/1307#issuecomment-521319641
- To be continued
> Extend link functionality

- tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/helpers/sharingHelper.js
This PR changes ```update``` permission to ```change``` permission to make it consistent with the webUI of Phoenix
CI
> "update" permission changed to "change" permission to make it consistent with the webui

- README.md
Reorganize the sections in logical reading order.
Add more detailed and up to date information about setting up Phoenix.
This was adjusted based on my own first experience of setting up everything, and based on the few hurdles I bumped against. I hope this will be helpful for newcomers to get set up more quickly.
> [Docs] Improve README with more setup information

- .drone.yml
trashbin WebDAV API and new public link webdav API are disabled by default but needed for phoenix, so enable them
make CI green again
> add dav.enable.tech_preview to CI runs

- README.md
just a small addition to the documentation
> add SCREEN_RESOLUTION setting for acceptance tests

- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/stepDefinitions/sharingContext.js
Adds collaborators test for changing share permissions
CI
> collaborators tests added

- src/components/Menu.vue
- src/phoenix.js
Additional menu items for the nav bar can be added via config.json
This is helpful to leverage integration with other web applications.
> Add bookmarks to nav menu

- CHANGELOG.md
- appinfo/info.xml
- package.json
> Adjust changelog and version for the new release

- apps/files/src/components/FileLinkForm.vue
- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/pageObjects/publicLinkFilesPage.js
- tests/acceptance/stepDefinitions/publicLinkContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
1. setting ids in the public link dialog
2. infrastructure and first set of tests for public links
3. renaming and moving  `closeSharingDialog()` function to the correct page object
> acceptance tests for public links

- tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/sharedWithMePage.js
- tests/acceptance/pageObjects/sharedWithOthersPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/loginContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
Add acceptance tests for checking if `shared with me` and `shared-with-others` pages work correctly.
- Related Issue #1983 
:robot:
> Add acceptance tests for shared with me and shared with others page

- apps/files/src/components/PublicLinks/FilesDrop.vue
- Use the correct computed property for the link password.
- When refreshing the page and no auth exist, redirect to the password
entry page
Fixes https://github.com/owncloud/phoenix/issues/1982
> Fix files drop when link password is set

- apps/media-viewer/webpack.common.js
Fix mediaviewer to run in IE11
> IE11 support for media-viewer

- .drone.yml
- nightwatch.conf.js
use apache to serve phoenix files
should make the tests faster and (hopefully) more reliably by serving requests in parallel
> run phoenix on apache for UI tests

- tests/acceptance/helpers/loginHelper.js
- tests/acceptance/pageObjects/loginPage.js
- tests/acceptance/pageObjects/ownCloudAuthorizePage.js
- tests/acceptance/pageObjects/ownCloudLoginPage.js
- tests/acceptance/stepDefinitions/loginContext.js
This refactors login helper into their respective page objects. This also adds a retry
on `AuthorizeButton` during the authentication process. 
- Fixes #2108
- locally
> Refactor login helper into respective page objects

- apps/files/src/default.js
- apps/files/yarn.lock
- apps/markdown-editor/yarn.lock
- apps/media-viewer/yarn.lock
- apps/pdf-viewer/yarn.lock
- yarn.lock
> Upgrade deps

- tests/acceptance/stepDefinitions/filesContext.js
Await deletion requests.
- Fixes #2091 
- locally
> Await trashbin deletion requests

- package.json
- tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/stepDefinitions/sharingContext.js
This PR adds acceptance tests for adding multiple collaborators (users and groups) on sharing a file/folders.
- Fixes #2001 
- locally
- :robot:
> Test multiple collaborators on share on a single share

- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/stepDefinitions/sharingContext.js
adds collaborator tests for file
- Fixes https://github.com/owncloud/phoenix/issues/1768
This tests adds collaborator test for file sharing
CI
> check required permissions are displayed for files

- tests/acceptance/features/webUIFiles/fileDetails.feature
- tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
add acceptance tests for checking if `shared with me` and `shared-with-others` pages work.
- Related Issue #1983
:robot:
> Add acceptance tests for checking files sidebar in shared with me page

- .drone.yml
Remove references to unused env vars in the existing `.drone.yml` to clean it up a bit before converting to starlark.
(this will make it easier for me to see any differences when I generate the drone matrix with starlark code)
CI
> Remove unused env variables from .drone.yml

- .drone.yml
- apps/files/src/components/FileDetails.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesAppBar.vue
- package.json
- src/phoenix.js
- src/router/index.js
- src/store/index.js
- src/store/links.js
- src/store/user.js
- tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature
- tests/acceptance/helpers/loginHelper.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/privateLinksContext.js
- yarn.lock
Handle private link redirection in the authentication steps, persist the state in the session storage instead of locale one to fix the issue with multiple tabs and use only id in the store instead of the whole path.
- Refs #2021
- Fixes #2115
With previous implementation the load folder function got triggered twice leading to sometimes overwriting the private link folder with the root one.
1. Navigate to private link authorised
2. Navigate to private link unauthorised
3. Navigate to private link in anonymous window
4. Open two tabs with Phoenix unauthorised and navigate at the same moment to two different private links
5. Navigate to private link unauthorised in IE11
> Fix redirection to private link after authorisation

- apps/files/src/components/Collaborators/mixins.js
- apps/files/src/components/FileInfoVersions.vue
- apps/media-viewer/src/Mediaviewer.vue
- apps/pdf-viewer/src/PdfViewer.vue
- src/components/Avatar.vue
- src/plugins/mediaSource.js
All requests must contain the header X-Requested-With: XMLHttpRequest
> Send header X-Requested-With: XMLHttpRequest in all requests

- tests/acceptance/stepDefinitions/generalContext.js
just some extra info about the test scenario making it easy to rerun locally
easier to debug tests
> show file and line number for every test scenario

- .drone.starlark
- .drone.yml
no need to try to create and post screenshots to github if its not a PR
> do and upload screenshots only on PRs

- tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
- tests/acceptance/features/webUITrashbin/trashbinDelete.feature
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/stepDefinitions/filesContext.js
Add acceptance test for deleting single file from trashbin
> Add acceptance test for deleting single file from trashbin

- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/stepDefinitions/filesContext.js
Add acceptance test to check that the delete button is disabled when deletion is prohibeted during sharing.
- Related to #1614
:robot:
> Add test for checking delete button state when prohibiting deleting in share

- apps/files/src/components/FilesAppBar.vue
- Fixes #2195
1. Define root folder in config
2. Navigate into subfolder inside of root folder
3. See only subfolder in breadcrumbs
> Use currentFolder path in breadcrumbs and remove root folder from it

- apps/markdown-editor/src/MarkdownEditor.vue
Sanitize the rendered content of markdown editor.
1. Enter some code into file in markdown editor
> Added sanitization to markdown editor

- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/helpers/occHelper.js
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/generalContext.js
Add acceptance tests for deleting the shared files.
- Part of #1614 
:robot:
> Add acceptance tests for deleting shared files and deleting shares

- package.json
- yarn.lock
Switch back to upstream repo and update to 1.9.0
- potentially fixes observed issues with state handling
> Use oidc-client 1.9.1

- tests/acceptance/helpers/navigationHelper.js
- tests/acceptance/pageObjects/favoritesPage.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/pageObjects/publicLinkFilesPage.js
- tests/acceptance/pageObjects/sharedWithMePage.js
- tests/acceptance/pageObjects/sharedWithOthersPage.js
- tests/acceptance/pageObjects/trashbinPage.js
Fix the function in navigation helper to dynamically select locate strategy
There was a bug in this function because of which it gave error like in https://drone.owncloud.com/owncloud/phoenix/5726/10/13 even though the tests didnt failed.
> [acceptance tests] Fix navigationHelper function for navigate and wait till loaded

- tests/acceptance/stepDefinitions/filesContext.js
maximum delete one item per second in acceptance tests
- related to https://github.com/owncloud/core/issues/23151
deleting files more often can result in duplicated files in the trashbin
> only delete 1/sec in acceptance tests

- tests/acceptance/features/webUISharingPermissions/sharePermissionsUsers.feature
- tests/acceptance/stepDefinitions/sharingContext.js
Change the name of the step to change the custom permission for a share.
The original name was misleading as it said `Changes the permission` which implies change all the permission when it changes only the custom permissions that appear below the role dropdown in the dialog.
> Rename acceptance test step for changing custom permission of a share

- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
Refactor function to set share permissions in collaborators.
- Related to #1614 
The function that sets the custom permission for the share is too big and difficult to understand. This code is also rewritten in another function. This refactor aims to reuse code, make the code more easier to understand and future usage of same function more easy.
> Refactor Test function for setting collaborator permissions

- apps/files/src/components/FilesAppBar.vue
- package.json
- yarn.lock
If a user clicks on the "x" icon next to the text inside of search bar the value gets now deleted.
- Fixes #2120
1. Enter some text into search bar
2. Click on the "x" icon
3. See icon disappear and the text being deleted
4. Enter some text into search bar and hit enter
5. Repeat step 2. after search has been completed.
6. Repeat with mobile search
> Reset search value on clear action

- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
Add new function `changeCollaboratorRoleInDropdown` to change the role of collaborator in `sharingDialog` page element.
The code for setting permissions is being rewritten in some functions. This PR reuses the function `expandInformationSelector` in some places where it can be.
> Improve tests functions for sharing related tests

- .drone.starlark
- .drone.yml
- tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
- tests/acceptance/pageObjects/sharedWithMePage.js
- tests/acceptance/stepDefinitions/generalContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
add acceptance test for asserting pending status of shared file when automatic accept incoming shares is disabled
:robot:
> Add acceptance tests for disabling automatic accept shared files

- .htaccess
Added X-Frame-Options and Content-Security-Policy.
For security reasons it is better to set these headers as this.
> Added X-Frame-Options and Content-Security-Policy

- tests/acceptance/features/webUIFiles/createFile.feature
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
Added acceptance tests for creating new files
:robot:
> Add acceptance test for creating new files

- tests/acceptance/helpers/httpHelper.js
- tests/acceptance/helpers/occHelper.js
This pr checks for 200 ocs status code
- Fixes https://github.com/owncloud/phoenix/issues/2315
```runOcc``` function of ```tests/acceptance/helpers/occHelper.js``` only checks for status (if it's ok). This pr also adds check for ocs status code to be ```200```
CI
> check for 200 ocs status code

- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
- tests/acceptance/helpers/xpath.js
- tests/acceptance/stepDefinitions/filesContext.js
Acceptance test added for the renaming operations over phoenix file system.
Various conflicting renaming issues are tested
:robot:
> Add acceptance test for renaming of  folders

- tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
Testing permission upgrades in Phoenix.
- Fixes #1614
- locally and :robot:
> Check for permission upgrade

- tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
This fixes the wordings that were suggested in the review of #2266, which I merged when it was green (:smile:). 
- locally
> Fix rewording scenario for sharePermissionsUsers

- .drone.starlark
- .drone.yml
- tests/acceptance/features/webUIResharing/reshareUsers.feature
- tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
- tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
- tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
- tests/acceptance/helpers/objects.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/stepDefinitions/generalContext.js
- tests/acceptance/stepDefinitions/loginContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
Add tests to check file/folder can't be reshared when allow_resharing is disabled.
https://github.com/owncloud/phoenix/issues/1614
CI
> Test resharing attempts when resharing is disabled

- src/components/Menu.vue
Check if the current route name is active
- Fixes #2259
- check if active menu element gets set as active (active css is coming from the ods, so have a look at https://owncloud.github.io/owncloud-design-system/#/Elements/oc-nav-item)
> Adding missing menu state when active

- .drone.starlark
- .drone.yml
- tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature
- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/stepDefinitions/notificationsContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
Acceptance test to share files and folders with internal groups
:robot:
> Add acceptance test to assert notification about new share is displayed when files and folders are shared with internal groups

- .drone.starlark
- .drone.yml
Add step `make vendor` in CI to build the oauth2 app.
- Fixes #2383
> Add step to build oauth2 app in ci

- .drone.starlark
- .drone.yml
- README.md
- nightwatch.conf.js
- package.json
- tests/acceptance/stepDefinitions/filesContext.js
This PR adds an npm script to run selenium container via `yarn run selenium` command.
It respects all the environment variable that affects selenium container. This PR makes the script
the recommended way of running selenium, changes the default of `LOCAL_UPLOAD_DIR` to be `/uploads` and adds documentation
- Related to #2222 
Make it easier to run the tests
- locally
> Add npm script for running selenium in docker

- tests/acceptance/features/webUILogin/login.feature
- tests/acceptance/pageObjects/ownCloudLoginPage.js
- tests/acceptance/stepDefinitions/loginContext.js
Add acceptance tests for incorrect login credentials
CI
> acceptance test for incorrect login credentials

- apps/draw-io/yarn.lock
- apps/files/yarn.lock
- apps/markdown-editor/yarn.lock
- apps/media-viewer/yarn.lock
- apps/pdf-viewer/yarn.lock
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/stepDefinitions/filesContext.js
- yarn.lock
Updating dependencies
- :robot:
> deps 20191107

- tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/pageObjects/sharedWithMePage.js
- tests/acceptance/stepDefinitions/sharingContext.js
Add acceptance test to accept previously declined share, and decline an accepted share
:robot:
> Add acceptance test to accept previously declined share and vice-versa

- tests/acceptance/features/webUIFiles/versions.feature
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/generalContext.js
Acceptance test to check the versions of an uploaded file
> Acceptance test to check the versions of an uploaded file

- tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
- tests/acceptance/stepDefinitions/filesContext.js
Acc acceptance tests for checking deletion of files with special characters.
:robot:
> Acceptance tests: Tests for checking deletion of file with special characters

- tests/acceptance/customCommands/waitForElementEnabled.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/setup-drone.js
- tests/acceptance/stepDefinitions/filesContext.js
This PR handles retrying to click the popup dialog which has been failing quite a lot. 
- Workaround for #1728. Requires further investigation. 
- locally, and CI
> Retry clicking on delete confirmation popup

- tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
- tests/acceptance/stepDefinitions/filesContext.js
Adds acceptance test for file and folder delete operations from shared with me and shared with others and favorites page
CI
> file and folder delete from favorites, shared with me and shared with others page

- tests/acceptance/pageObjects/ownCloudLoginPage.js
In login function of acceptance tests, use `waitforOutstandingAjaxCalls()` instead of `waitforAjaxCallstoStartAndfinish()`
- Related #2420
> Acceptance tests: don't wait for Ajax calls while login

- tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
- tests/acceptance/pageObjects/sharedWithMePage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
add acceptance test for declining and accepting shared files
> Add acceptance test for declining and accepting shared files

- tests/acceptance/features/webUIFavorites/favoritesFile.feature
- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/stepDefinitions/filesContext.js
Add Extra acceptance test scenarios to check that renaming files to various valid and invalid names work properly.
:robot:
> Acceptance tests: Renaming files and folders to valid and invalid names

- tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
- tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
Adds acceptance test for resharing attempts from favorites, shared-with-me and shared-with-others page when resharing is disabled
CI
> test resharing attempts from different pages when resharing is disabled

- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/stepDefinitions/filesContext.js
adds acceptance test for file/folder rename from favorites, shared with me and shared with others page
https://github.com/owncloud/phoenix/issues/2460
CI
> file rename from favorites, shared-with-me and shared-with-others page

- tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/generalContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
Add acceptance test to assert autocomplete list is not present when not enough characters are typed
> Test user is not displayed on autocompletion when less than the default minimum characters are typed

- tests/acceptance/customCommands/useStrategy.js
- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/pageObjects/filesDropPage.js
- tests/acceptance/pageObjects/publicLinkFilesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/publicLinkContext.js
This adds a test for files-drop upload with or without password.
- Related to #2222
- CI and locally
> Test file uploads in files-drop

- tests/acceptance/features/webUIFiles/createFolderEdgeCases.feature
- tests/acceptance/stepDefinitions/webdavContext.js
Add acceptance tests for creating sub folders inside folders with scpecial characters in their names.
:robot:
> Acceptance tests: Check creating sub folders inside folders with special characters

- yarn.lock
Includes some SDK update as well which is needed for https://github.com/owncloud/phoenix/pull/2239
> Update dependencies 20191114

- tests/acceptance/features/webUIResharing/reshareUsers.feature
Adds acceptance test for resharing of file and folder from favorites, shared-with-me and shared-with-others page
https://github.com/owncloud/phoenix/issues/2460
> resharing file and folder from different pages

- tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/stepDefinitions/notificationsContext.js
Acceptance test for accept and decline actions performed for offered shares in the notifications
> Acceptance test for accept and decline actions performed for offered shares in the notifications

- .drone.starlark
- .drone.yml
- tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
- tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature
Add new test suite for `SharingAutocompletion`
Add tests for checking autocompletion for users with username containing special characters (eg, `-_@.`)
:robot:
> Add test for autocompletion for users with special characters

- tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
Delete duplicate test for file deletion from share with others page
https://github.com/owncloud/phoenix/issues/2482
CI
> remove file deletion duplicate test

- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
Add acceptance test for share with user implemented scenarios
https://github.com/owncloud/phoenix/issues/2482
CI
> acceptance test for shared with users implemented features

- apps/files/src/components/FilesApp.vue
- Fixes #2436 
Urgent bugfix
- follow #2436 and check if scrolling is possible
> Fix scroll behavior on mozilla firefox

- .drone.starlark
- .drone.yml
> Fix steps order on release/publish

- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
- tests/acceptance/stepDefinitions/publicLinkContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
check that the password enforcement works correctly when creating new public link
part of  #2075
> check passwords are enforced when creating new public share

- tests/acceptance/helpers/userSettings.js
- tests/acceptance/stepDefinitions/provisioningContext.js
A replaceInlineCode function is added for user password in acceptance test for uninitialized user
- Fixes https://github.com/owncloud/phoenix/issues/1475
This is needed for the scenarios where users are created but not initialized as in this scenario which had been implemented already https://github.com/owncloud/phoenix/blob/34bfa32c15ae920739cb3ffc05b100c90c6ab16a/tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature#L14
> Add function for user password in acceptance test for uninitialized user

- apps/files/src/components/FileLink.vue
- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
- tests/acceptance/pageObjects/publicLinkPasswordPage.js
- tests/acceptance/stepDefinitions/publicLinkContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
Acceptance tests for public link sharing are add.
Some of the scenarios has still not been implemented due to some issues like not implemented features
Fixes #2479
:robot:
> Add acceptance test for public link sharing

- .drone.starlark
- .drone.yml
> Use drone docker plugin

- tests/acceptance/features/webUIUpload/upload.feature
- tests/acceptance/pageObjects/filesPage.js
This PR adds test for overwriting file uploads and removes redundant scenarios.
- Related to #2222
https://github.com/owncloud/phoenix/pull/2400#issuecomment-553954959
- locally
> Test: Overwrite file uploads, remove redundant scenarios

- tests/acceptance/features/webUIUpload/upload.feature
Rename `change` permission to `update`.
- Fixes broken CI
Making CI happy again :)
- locally
> Test: Rename change permission to update

- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
- tests/acceptance/helpers/sharingHelper.js
tests for setting default expiry date on public links
part of #2075
> test set default expiration date for public links

- tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/pageObjects/sharedWithMePage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
Add acceptance tests for actions performed on received/offered shares.All the scenarios that have  been implemented in these PR:#2292 and #2290 have also been deleted to get rid of duplication
- Fixes issue #2478
> Acceptance tests for actions performed on received shares

- apps/files/src/components/Collaborators/Collaborator.vue
- apps/files/src/components/Collaborators/CollaboratorsEditOptions.vue
- apps/files/src/components/Collaborators/EditCollaborator.vue
- apps/files/src/components/Collaborators/NewCollaborator.vue
- apps/files/src/components/FileDetails.vue
- apps/files/src/components/FileSharingSidebar.vue
- apps/files/src/store/actions.js
- apps/files/src/store/mutations.js
- tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
- tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
- tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature
- tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature
- tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
- tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalGroups/shareWithGroupsEdgeCases.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/features/webUISharingPermissionMultipleUsers/shareWithMultipleUsers.feature
- tests/acceptance/helpers/userSettings.js
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/sharingContext.js
- yarn.lock
Fixes https://github.com/owncloud/phoenix/issues/1908
> New collaborators flow

- tests/acceptance/features/webUIFiles/createFolders.feature
- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/stepDefinitions/filesContext.js
Add acceptance test to create a folder with special characters in its name and then browse to that folder 
- Related to #2467
> Test folder with special characters in name

- tests/acceptance/helpers/path.js
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/publicLinkContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
- tests/acceptance/stepDefinitions/webdavContext.js
This introduces some path helpers (`resolve`, `normalize` and `join`) to use in our acceptance tests.
This is because, we have some specific requirements (such as there's no difference between `/path` and `path`, and we will always love to work with the one without slashes and not being tied to os filesystem,i.e only lexical path transformation).
- Related to #2499 
- locally
> Test: Use path helpers in acceptance tests

- tests/acceptance/features/webUIFavorites/favoritesFile.feature
- tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
- tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
- tests/acceptance/features/webUIFiles/download.feature
- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/generalContext.js
Add acceptance tests for performing files action on files and folders that has been deleted from different client.
- Related Issue #1720
:robot:
> Acceptance tests: perform file actions on the files and folders that doesnot exist

- tests/acceptance/stepDefinitions/generalContext.js
just a stupid copy-paste naming issue
> fix parameter name

- tests/acceptance/features/webUITrashbin/trashbinRestore.feature
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
Add acceptance to restore a file from trashbin whose parent folder is renamed
-Related to issue : https://github.com/owncloud/phoenix/issues/1753
> Acceptance test to restore a file from trashbin whose parent folder is renamed

- .drone.starlark
- .drone.yml
- tests/acceptance/features/webUIAccount/accountInformation.feature
- tests/acceptance/pageObjects/accountPage.js
- tests/acceptance/stepDefinitions/accountContext.js
Add acceptance test to view account information on the account page on the webUI 
- Related to issue #2566 
The feature to view the account information on the account page was implemented in the phoenix but no tests were written for that feature. This PR adds acceptance test scenarios for that feature implemented in phoenix.
> Add acceptance test to view account information on the account page

- README.md
- package.json
- tests/acceptance/helpers/config.js
- tests/acceptance/setup-drone.js
- tests/acceptance/setup-local.js
- tests/acceptance/stepDefinitions/generalContext.js
This PR sets `skeletondirectory` when running tests. Sadly, `client` is not ready when`BeforeAll` runs, so I have to run this in `Before`.
- Fixes #2568
Make it easier to run tests for everyone, and one less thing for me to remember
- locally
> Test: Set skeletondirectory when running tests

- tests/acceptance/features/webUIAccount/logout.feature
- tests/acceptance/pageObjects/accountPage.js
- tests/acceptance/stepDefinitions/accountContext.js
Add acceptance test to logout user from the account page
-Related to issue #2566 
The feature for logging out from the account page was implemented in phoenix but no tests were written for that feature. This PR adds acceptance test scenarios for that feature.
> Acceptance test to logout user from the account page

- tests/acceptance/features/webUITrashbin/trashbinDelete.feature
- tests/acceptance/pageObjects/trashbinPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/generalContext.js
Add acceptance test to clear trashbin
- Fixes issue #2581
> Add acceptance test to clearTrashbin

- apps/draw-io/yarn.lock
- apps/files/yarn.lock
- apps/markdown-editor/yarn.lock
- apps/media-viewer/yarn.lock
- apps/pdf-viewer/yarn.lock
- package.json
- yarn.lock
> Upgrade all libs

- .drone.starlark
- .drone.yml
Currently, we are using nodejs-v8.x.x for running acceptance tests which comes from https://github.com/owncloud-ci/php. This PR adds https://github.com/owncloud-ci/nodejs as docker image to run acceptance tests.
- Fixes https://github.com/owncloud/phoenix/issues/2345
CI
> Update: run acceptance test with newer nodejs version

- tests/acceptance/pageObjects/FilesPageElement/filesList.js
This PR handles retrying to click delete popup dialog inside the trashbin page, which has been failing quite a lot.
https://github.com/owncloud/phoenix/issues/1728
CI
> Retry clicking on delete immediately popup in trashbin

- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
- tests/acceptance/stepDefinitions/sharingContext.js
fix wording according to our standard
- Fixes  #2537
> correct step wording

- .drone.starlark
- .drone.yml
- nightwatch.conf.js
- tests/acceptance/customCommands/setValueBySingleKeys.js
- tests/acceptance/features/webUISharingExternal/federationSharing.feature
- tests/acceptance/helpers/backendHelper.js
- tests/acceptance/helpers/occHelper.js
- tests/acceptance/helpers/userSettings.js
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/stepDefinitions/generalContext.js
- tests/acceptance/stepDefinitions/provisioningContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
- tests/acceptance/stepDefinitions/webdavContext.js
Add tests for sharing and receiving a file with federated cloud share using phoenix.
- Related #2477
locally
> Add acceptance tests for federation sharing

- apps/files/src/components/Trashbin.vue
Made the trashbin table responsive. (the same way the files list looked like)
- Fixes #1760 
- delete a file
- check it on a mobile phone
> Responsive trashbin table

- apps/files/src/components/FileDetails.vue
- apps/files/src/components/FileSidebarWebComponent.vue
- apps/files/src/default.js
- package.json
- src/phoenix.js
Prototype to show how #2573 could work
To get the web component working please build this web component https://github.com/DeepDiver1975/phoenix-demo-web-component and place it somewhere reachable.
The config will look like this:
```json
"files": {
"sidebars": [
{
"tabTitle": "Web Component Demo I",
"componentName": "my-custom-element",
"componentUrl": "external/dist/my-custom-element.js"
},
{
"tabTitle": "Web Component Demo II",
"componentName": "my-custom-element",
"componentUrl": "external/dist/my-custom-element.js"
}
],
```
This will add new tabs with the web component inside. Data of the currently selected file will be transferred into the component.
#2573 
- test case 1:
- test case 2:
- ...
> Files sidebars can now be loaded as Web Components via the config file

- package.json
- yarn.lock
For https://github.com/owncloud/phoenix/issues/2694
> Revert ODS to 1007

- apps/files/src/components/Collaborators/AdditionalPermissions.vue
- apps/files/src/components/FileFilterMenu.vue
- apps/files/src/components/FileList.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesAppBar.vue
- apps/files/src/components/Trashbin.vue
- apps/files/src/components/ocDialogPrompt.vue
- package.json
- src/components/Avatar.vue
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/pageObjects/phoenixPage.js
- yarn.lock
Failing tests because of uilit version are now passing locally after sticking it to 3.2.3. Let's see if drone will be fine with it as well.
> Updated ODS + related bugfixes

- .drone.starlark
- .drone.yml
- nightwatch.conf.js
They were not that useful anyway as we need deeper debugging anyway.
Note: I'm not familiar with Starlark so not sure if the change makes sense
> Disable CI screenshots

- tests/acceptance/features/webUISharingNotifications/sharedWithMeFilter.feature
- tests/acceptance/features/webUISharingNotifications/sharedWithOthersFilter.feature
- tests/acceptance/helpers/filesFoldersHelper.js
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/stepDefinitions/filesContext.js
Add acceptance test to filter files. folders and hidden elements in the shared-with-others page using keyword
- Fixes #2705
> Filter shared with others resources using keyword

- tests/acceptance/helpers/filesFoldersHelper.js
- tests/acceptance/stepDefinitions/filesContext.js
Edit the methods used in the acceptance tests to filter the resources using keyword
- Fixes  #2679
> Edit the methods used in the acceptance tests to filter the resources using keyword

- tests/acceptance/features/webUIFavorites/favoritesFilter.feature
- tests/acceptance/helpers/filesFoldersHelper.js
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/stepDefinitions/filesContext.js
Acceptance test to filter files, folders and hidden elements using keyword in the favourites page
- Fixes #2709
> Acceptance test to filter resources using keyword in the favourites page

- .drone.starlark
- .drone.yml
Enable logging of federated server in drone.
- Fixes https://github.com/owncloud/phoenix/issues/2741
> Setup log for federated server in drone

- tests/acceptance/pageObjects/FilesPageElement/filesList.js
This PR creates enum like reference for file actions like delete, share, download, etc
- Fixes https://github.com/owncloud/phoenix/issues/2567
CI
> Create enum like reference for file actions

- apps/files/src/components/Collaborators/NewCollaborator.vue
- apps/files/src/components/FileFilterMenu.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesAppBar.vue
- package.json
- yarn.lock
Update ODS to revision 1059.
Added search bar labels as required.
Fix buttonHidden value to be a real boolean.
Fix null label in rename dialog, as only string is allowed for the
label.
None
Open web browser on files app:
- before the fix: lots of warnings about label
- after the fix: no more such warnings (except for virtual scroll, raised separately #2726)
> Update ODS to fix labels

- .drone.starlark
- .drone.yml
- tests/acceptance/features/webUISharingPermissionMultipleUsers/shareWithMultipleUsers.feature
Due to a typo, the tests were not running on the drone.
- CI and locally
> Fix typo of suite webUISharingPermissionMultipleUsers

- tests/acceptance/helpers/occHelper.js
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/pageObjects/accountPage.js
- tests/acceptance/pageObjects/favoritesPage.js
- tests/acceptance/pageObjects/filesDropPage.js
- tests/acceptance/pageObjects/loginPage.js
- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/pageObjects/publicLinkFilesPage.js
- tests/acceptance/pageObjects/sharedWithMePage.js
- tests/acceptance/pageObjects/sharedWithOthersPage.js
- tests/acceptance/pageObjects/trashbinPage.js
- tests/acceptance/stepDefinitions/generalContext.js
- tests/acceptance/stepDefinitions/notificationsContext.js
- tests/acceptance/stepDefinitions/provisioningContext.js
Path join is used in the urls used in the acceptance tests
- Fixes #2649
> Use path join methods in fetch

- tests/acceptance/features/webUIFavorites/favoritesFilter.feature
- tests/acceptance/features/webUIFiles/filter.feature
- tests/acceptance/features/webUISharingNotifications/sharedWithMeFilter.feature
- tests/acceptance/features/webUISharingNotifications/sharedWithOthersFilter.feature
- tests/acceptance/features/webUITrashbin/trashbinFilter.feature
- tests/acceptance/stepDefinitions/filesContext.js
The test scenarios written for filter feature have been refactored to make the steps more clear
- Fixes #2787
> Refactor test scenarios written for filter feature

- nightwatch.conf.js
- tests/acceptance/helpers/browserConsole.js
- tests/acceptance/setup.js
This PR adds a browser console logging in case the scenario fails. Currently, it does not fail the tests in case of console.error.
> Show browser log

- .eslintrc.json
- apps/files/src/components/Trashbin.vue
- tests/acceptance/helpers/filesFoldersHelper.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/pageObjects/phoenixPage.js
- tests/acceptance/stepDefinitions/filesContext.js
Remove unnecessary await, and a check in eslint. 
- locally
> Remove unnecessary async-await

- tests/acceptance/features/webUIFiles/breadcrumb.feature
Follow up on https://github.com/owncloud/phoenix/pull/2811#discussion_r363147312
- test environment: Drone
> Removed extra steps from breadcrumbs tests

- Makefile.release
> Fix tar creation

- Makefile.release
missing in #2830 - THX @LukasHirt
> Add htaccess file to the tar ball

- .drone.star
Upon creating a tag the built release is uploaded as github release by drone
> Upload releases to github upon tagging

- config.json.sample
- src/components/ApplicationsMenu.vue
If the extension lives inside of Phoenix SPA and not in it's own SPA let's take advantage or router-link instead of redirecting to a new tab.
> Internal links in app switcher

- tests/acceptance/helpers/codify.js
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/helpers/userSettings.js
- tests/acceptance/setup.js
- tests/acceptance/stepDefinitions/generalContext.js
- tests/acceptance/stepDefinitions/notificationsContext.js
- tests/acceptance/stepDefinitions/provisioningContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
This PR adds a custom parameter type `code` that replaces percent-coded strings with suitable values. This also introduces `replaceInlineTable` helper that can replace everything inside the table (with a hack :stuck_out_tongue: ).
Note: You'll lose better auto-completion/navigation (ctrl-clicking) for the step using `{code}` parameter in Webstorm/PHPStorm. 
Parsing/handling at the highest level
- locally
> Test: Introduced coded param, and replaceInlineTable helper

- package.json
- yarn.lock
For https://github.com/owncloud/owncloud-design-system/pull/615
> Update ODS to fix icon sizes

- changelog/unreleased/2681
We have a new process for generating changelog items.
Pr #2681 was merged during that change.
This adds an item for it.
- by Drone CI
> Add changelog item for #2681

- .drone.star
- tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
- tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
Split test suites into smaller parts as SharingFilePermissionMultipleUsers and SharingFolderPermissionMultipleUsers.
- Fixes #2874 
SharingPermissionMultipleUsers test suite usually take very long time to complete. Splitting it into two smaller parts would help to complete it in time.
- test case 1:
- test case 2:
- ...
> Split test suites into smaller parts for Sharing Permission Multiple Users

- apps/files/src/components/AllFilesList.vue
Just a wording change to make it look less technical :)
> Change "Modification Time" column name to "Updated"

- README.md
Add documentation about running federation tests
- Fixes #2906 
It is possible to run federation tests in owncloud. However, documentation about running federation tests is not available in the ownCloud README file.This PR adds documentation for running federation tests in ownCloud.
- test case 1:
- test case 2:
- ...
> Add documentation about running federation tests

- apps/draw-io/yarn.lock
- apps/files/yarn.lock
- apps/markdown-editor/yarn.lock
- apps/media-viewer/yarn.lock
- apps/pdf-viewer/yarn.lock
- yarn.lock
Ran `yarn upgrade-all` as we usually do :-)
> Upgrade all deps

- apps/files/src/components/Collaborators/Collaborator.vue
- apps/files/src/components/Collaborators/EditCollaborator.vue
- apps/files/src/components/Collaborators/NewCollaborator.vue
- apps/files/src/components/PrivateLink.vue
- apps/files/src/components/PublicLinks/FilesDrop.vue
- apps/files/src/components/PublicLinks/PublicLink.vue
- apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
- apps/files/src/components/PublicLinksSidebar/PublicLinkListItem.vue
- package.json
- src/components/Avatar.vue
- yarn.lock
Grabbing most recent version of ODS and use the (new) spinner sizes so that they work well along with icons. `oc-spinner` and `oc-icon` sizes are now identical, so that a spinner replacing and icon (or vice versa) doesn't cause layout flickering anymore.
This PR makes sure that such cases are now fixed by setting sensible spinner- and icon-sizes. Also, the `xsmall` spinner size has be chosen where spinners were inline with texts, which now looks less intrusive.
While being at this, I also resolved some more missing aria-label warnings on spinners.
- Fixes https://github.com/owncloud/owncloud-design-system/issues/631
UI/UX improvement.
- manually with Chrome and Firefox
> Use new ODS and adjust spinner sizes.

- src/pages/account.vue
- src/pages/login.vue
- tests/acceptance/pageObjects/accountPage.js
Parametrize product name in welcome message.
Add space in "Log out" to be consistency with another location.
> Text tweaks for translation

- apps/files/package.json
- package.json
- Refs #2967
1. Try and build Phoenix
> Adjusted browserslist to exclude IE 11

- apps/files/src/components/AllFilesList.vue
- apps/files/src/components/FileList.vue
- changelog/unreleased/1952
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/stepDefinitions/filesContext.js
> Fixed files table header

- apps/draw-io/yarn.lock
- apps/files/yarn.lock
- apps/markdown-editor/yarn.lock
- apps/media-viewer/yarn.lock
- apps/pdf-viewer/yarn.lock
- yarn.lock
> Upgrade all libs post 0.4.0

- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/filesPage.js
Following functions inside page-objects filesPage and filesList were used by nothing, thus removed!
-  getAllListedResources
- isActionDisabled
- getListedFilesFolders
> [Tests-Only] Removed unused functions

- .drone.star
- .gitignore
- Makefile
- docs/_index.md
- docs/building.md
- docs/getting-started.md
- tests/acceptance/helpers/ldapHelper.js
- tests/acceptance/stepDefinitions/provisioningContext.js
- Add Developer Docs build with hugo
`make docs`
`cd hugo`
`hugo server -D`
Then check the result at `http://localhost:1313/`
> Add Developer Docs

- README.md
Add documentation for running phoenix acceptance test using OCIS.
- Fixes #3155
> Add doc in README.md for running tests with ocis

- tests/acceptance/features/webUIFiles/versions.feature
Update test tags on version related tests.
- Related #3129
> [Tests-only] update skip tag issue number on version tests

- tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
- tests/acceptance/features/webUITrashbin/trashbinRestore.feature
Update issue numbers in trashbin tests
- Related #3129
> [Tests-only] update skip tag issue number on trashbin tests

- tests/acceptance/stepDefinitions/provisioningContext.js
Remove ocis data directory asynchronously while running tests with ocis
> [Tests-only] Remove data directory asynchronously on ocis tests

- .drone.star
Update Konnectd config env variables updated in https://github.com/owncloud/ocis-konnectd/pull/52
- Failing OCIS tests
CI :heavy_check_mark:
> [Tests-only] Update konnectd configuration variables in drone

- tests/acceptance/helpers/ldapHelper.js
Fix the changes in konnectd config from https://github.com/owncloud/ocis-konnectd/pull/55
The data root for any user will be `<OCIS_REVA_DATA_ROOT>/data/<userid>`
The login attribute (or user id) used by konnectd used to be `uid` attribute from the ldap server but
after https://github.com/owncloud/ocis-konnectd/pull/55 it seems to use `cn` as login attribute and the data directory also changes with that. But the tests still try to create and clean old data directory and they are failing.
This PR uses same value for `cn` and `uid` while creating users in ldap server which fixes the issue.
- Broken CI
- CI :heavy_check_mark:
> [Tests-only] Fix the cn of user on ldap while creating user

- .drone.star
- nightwatch.conf.js
Add option to upload screenshots to github comments from drone CI on acceptance tests failure.
For better debugging of test failures
> [Tests-only] Add option to enable screenshots while running acceptance tests

- .drone.star
Dont run ocis tests in drone.
- Broken CI
Currently the ocis tests are very unstable and since the onging development of the ocis system the configuration keeps on changing which keeps blocking the development process in phoenix. So for time being we should not run the ocis tests on every PR.
> [Tests-only] Dont run ocis tests in CI

- tests/acceptance/helpers/config.js
- tests/acceptance/helpers/httpHelper.js
- tests/acceptance/helpers/occHelper.js
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/stepDefinitions/generalContext.js
- tests/acceptance/stepDefinitions/notificationsContext.js
- tests/acceptance/stepDefinitions/provisioningContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
- tests/acceptance/stepDefinitions/webdavContext.js
This PR adds a wrapper around the `node-fetch` that we have been using in our tests.
- Fixes https://github.com/owncloud/phoenix/issues/2500
- CI
> [Tests-only] Fetch wrapper

- .drone.star
- tests/acceptance/features/webUICreateFilesFolders/createFolderEdgeCases.feature
- tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
- tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
- tests/acceptance/features/webUIFiles/fileList.feature
- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
- tests/acceptance/features/webUITrashbin/trashbinDelete.feature
- tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
- tests/acceptance/features/webUITrashbin/trashbinRestore.feature
- tests/acceptance/features/webUIUpload/uploadEdgecases.feature
Some reva config variables were changed in the reva update in https://github.com/owncloud/ocis-reva/pull/113/files This was causing the CI to fail in
This PR updates the config variables for reva while running tests in drone.
- Broken CI
> [Tests-only] Update the config variables used in for reva in CI

- .drone.star
- nightwatch.conf.js
Update the chrome browser to the latest version to run the accetance tests
- Fixes #2743
> Update chrome browser for UI tests

- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/stepDefinitions/sharingContext.js
- https://github.com/owncloud/phoenix/issues/3132
> [Tests-Only] Add acceptance tests for collaborators share expiration date

- apps/files/src/components/Collaborators/EditCollaborator.vue
- apps/files/src/components/PublicLinksSidebar/EditPublicLink.vue
- apps/files/src/store/actions.js
- changelog/unreleased/3176
- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
- tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
- tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
- tests/acceptance/stepDefinitions/publicLinkContext.js
test has been modified to cope with the changes made in share expiration date changes
Changes in the code was causing the CI to fail since previously noticed error message do not appear anymore. So, test scenario has been modified accordingly.
locally
> [Tests-Only] Test for fix share expiration date changes

- changelog/unreleased/logout_redirect_uri.md
- src/services/auth.js
The redirect uri contains the full path to the login route.
- Fixes #3285 
After logging out the idp sends a redirect uri containing a queryparameter.
The vue router has problems with queryparameters and hash mode.
The url would be incorrectly assembled and further routing would lead to errors.
- locally
- login and logout then login again
> fix logout redirect uri

- changelog/unreleased/3292
- package.json
- yarn.lock
Update owncloud-sdk 1.0.0-544
- refs #2016
- :hand: - fire it up and see file list loaded
- :robot: will do the rest
> Update owncloud-sdk 1.0.0-544

- .drone.star
- nightwatch.conf.js
Run tests without openid connect by default.
> [Tests-only] Run tests without openId login by default

- .github/settings.yml
> Provide correct link to demo instance in settings.yml

- .drone.star
core has dropped PHP 7.1
Change the drone CI  so it uses PHP  7.3 images rather than 7.1 - IMO we may as well go straight to 7.3
> [Tests-Only] Use PHP 7.3 in drone

- package.json
- yarn.lock
Brings in new modal dialog component: https://github.com/owncloud/owncloud-design-system/pull/723
> Update to ODS version 1.3.0

- package.json
- yarn.lock
Fixes unsafe header warnings with the TUS header detection: https://github.com/owncloud/owncloud-sdk/pull/463
> Update owncloud-sdk to revision 608

- docs/testing.md
- package.json
fix test documentation to work with ocis and use simpler selenium setup
part of https://github.com/owncloud/ocis/issues/211
> [Tests-only] improve testing documentation

- tests/acceptance/features/webUICreateFilesFolders/createFile.feature
- tests/acceptance/features/webUIFiles/sort.feature
- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
- tests/acceptance/features/webUIUpload/upload.feature
- tests/acceptance/features/webUIUpload/uploadEdgecases.feature
After an update in ocis-reva many tests are failing in phoenix. More details in https://github.com/owncloud/ocis-reva/issues/188
This Pr skips those tests.
The tests mostly failing due to this change are 
- Uploading
- Creating file with webUI
- Renaming the files
- Related https://github.com/owncloud/ocis-reva/issues/188
> [Tests-Only]Skip failing tests in ocis

- .drone.star
- nightwatch.conf.js
Disabling screenshots by default in CI for ocis tests.
Currently we upload screenshots for tests running with OCIS backend. But since there is some problem with screenshots in selenium, this PR disables it by default in CI. 
for debug purposes it can still be enabled by setting `'screenshots': True` in the config section of `.drone.yml`.
- Fixes #3440
> [Tests-Only] Disable screenshots by default in drone

- README.md
Currently https://phoenix.owncloud.com/custom/phoenix/index.html#/login URL returns a 404
> update readme file with valid url for online demo

- docs/testing.md
improve documentation to reduce confusion
- Fixes #3444
- followed the doc and ran the tests successfully
> [Tests-only] improve ocis tests documentation

- tests/acceptance/features/webUICreateFilesFolders/createFile.feature
- tests/acceptance/features/webUIFiles/sort.feature
- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
Reenable all tests related to issue-ocis-reva-188
except the upload ones which have unrelated timeout issues.
This is a piece of https://github.com/owncloud/phoenix/pull/3457
> [Tests-only] Reenable tests disabled by issue-ocis-reva-188

- tests/acceptance/features/webUIAccount/accountInformation.feature
- tests/acceptance/features/webUICreateFilesFolders/createFolderEdgeCases.feature
- tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
- tests/acceptance/features/webUIFiles/breadcrumb.feature
- tests/acceptance/features/webUIFiles/fileDetails.feature
- tests/acceptance/helpers/ldapHelper.js
Unskip more passing tests in CI
> [Tests-Only] Unskip passing tests in CI

- .drone.star
- package.json
Split ocis tests into multiple pipelines in drone
Since there are about 100 scenarios running in ocis now, it takes a lot of time to complete.
Splitting this will bring the CI runtime
> [Tests-Only] split ocis test pipelines

- .drone.star
Refactor .drone.star file to remove the nested if else statements in the acceptance test step.
- test case 1:
- test case 2:
- ...
> [Tests-Only] Refactor .drone.star file in acceptance test step

- .drone.star
Reverts owncloud/phoenix#3599
This change seems to have broken phoenix tests with ocis. The tests are not running right now. need more time to look in to it. So just reverting it for now.
> Revert "[Tests-Only] Refactor .drone.star file in acceptance test step"

- .drone.star
Do not start oc10 services while testing ocis in CI. It was done to use the skeleton files that come with the qa-tarball of oc10 but now we just clone the testing app.
- Fixes #3635
make CI a little bit faster.
:robot:
> [Tests-Only] Dont start oc service while testing ocis in CI

- .drone.star
This PR reverts to previous version of `ocis-glauth` to make CI green again
- https://github.com/owncloud/phoenix/issues/3655
- CI
> [Tests-Only] Revert back to previous commit of ocis-glauth to make CI green

- tests/acceptance/setup.js
Show the browser logs in ocis tests on failure.
For more debugging options for failing tests.
> [Tests-Only] show browser logs in ocis on failure

- apps/files/src/components/Collaborators/CollaboratorsEditOptions.vue
- changelog/unreleased/set-expiration-date-only-if-supported
- Fixes #3674
No error message in the console.
> Set expiration date only if it is supported

- apps/files/src/components/LocationPicker/LocationPicker.vue
- changelog/unreleased/location-picker-root-target
Removed extra space in the root route in location picker
> Fix location picker navigation to root

- tests/acceptance/features/webUICreateFilesFolders/createFile.feature
- tests/acceptance/features/webUICreateFilesFolders/createFolderEdgeCases.feature
- tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
- tests/acceptance/features/webUIFavorites/favoritesFile.feature
- tests/acceptance/features/webUIFiles/download.feature
- tests/acceptance/features/webUIFiles/search.feature
- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/features/webUITrashbin/trashbinDelete.feature
- tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
- tests/acceptance/features/webUITrashbin/trashbinRestore.feature
- tests/acceptance/features/webUIUpload/upload.feature
- tests/acceptance/filesForUpload/file,with,comma,.txt
This PR adds tests for operations on files with commas in the filename
- https://github.com/owncloud/core/issues/37664
CI
> [Tests-Only] Add acceptance tests for files with commas in the filename

- tests/acceptance/features/webUICreateFilesFolders/createFolderEdgeCases.feature
- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
This PR merges similar scenarios together which were split due to certain issues, but now the skip tags were already removed.
There were more than one scenario present for similar scenarios because of some issues in the past. The skip tags relating to those issues where removed some times ago but still those scenarios where not merged together, which creates confusion.
> [Tests-Only]Merge similar scenarios after the issue is solved and skip tags are removed

- tests/acceptance/helpers/navigationHelper.js
- tests/acceptance/pageObjects/filesPage.js
Wait for the new file button to be loaded when browsing to the files page instead of the progress bar which disappears immediately and sometimes not found.
- Fixes #3660
if the progress bar is not found, the test just waits for 10 seconds until timeout which reduces the test execution time very greatly.
> [Tests-only] Adjust browse to files page method to reduce waiting time

- tests/acceptance/features/webUIFiles/options.feature
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/generalContext.js
Add UI tests for hiding search bar option
- Fixes #3818
:robot:
> [Tests-Only] Add test for hiding search bar config option

- tests/acceptance/features/webUIPreview/imageMediaViewer.feature
- tests/acceptance/helpers/webdavHelper.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/FilesPageElement/offCanvasPage.js
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/previewContext.js
Added webUI tests for viewing image in media viewer
- https://github.com/owncloud/phoenix/issues/3807
- CI
> [Tests-Only] webUI test for media viewer 

- tests/acceptance/features/webUIPreview/imageMediaViewer.feature
- tests/acceptance/stepDefinitions/previewContext.js
This PR adds acceptance test for video playback in public share
- https://github.com/owncloud/phoenix/issues/3842
- CI
- manual
> [Tests-Only]Acceptance test for video playback in public share

- apps/draw-io/yarn.lock
- apps/files/yarn.lock
- apps/markdown-editor/yarn.lock
- apps/media-viewer/yarn.lock
- apps/pdf-viewer/yarn.lock
- yarn.lock
> Update all deps

- apps/files/src/components/AllFilesList.vue
- apps/files/src/components/FileList.vue
- apps/files/src/components/FilesApp.vue
- apps/files/src/components/FilesAppBar.vue
- apps/files/src/components/SidebarQuota.vue
- apps/files/src/helpers/resources.js
- apps/files/src/mixins.js
- apps/files/src/store/actions.js
- apps/files/src/store/mutations.js
- apps/files/src/store/state.js
- changelog/unreleased/information-about-current-folder-under-files-list
- changelog/unreleased/quota-in-sidebar
- package.json
- src/Phoenix.vue
- src/store/sidebar.js
- yarn.lock
- Fixes https://github.com/owncloud/product/issues/120
- Fixes https://github.com/owncloud/product/issues/121
- Set quota to user
- Fill quota above 80%
- Fill full files list with resources
> Display quota in sidebar and move information about current folder below files list

- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
skip these tests because of https://github.com/owncloud/ocis/issues/458
get https://github.com/owncloud/ocis/pull/409 merged
https://cloud.drone.io/owncloud/ocis/1178/7/1
> [tests-only] skip public link tests on ocis

- tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
Disable for ocis reva issue 442
This is randomly failing in https://github.com/owncloud/ocis/pull/409.
Will be reenabled as part of https://github.com/owncloud/ocis-reva/issues/442
> [Tests-only] Disable test for partial deletion

- docs/testing.md
This PR edits testing doc to run tests without ldap server
- https://github.com/owncloud/product/issues/176
> [Tests-Only] Adjust testing doc to run tests without ldap server

- tests/acceptance/helpers/userSettings.js
Add default ocis users to the available users list in the test suite
> [Test-Only] Update available users to include default users from ocis

- tests/acceptance/features/webUICreateFilesFolders/createFile.feature
- tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
- tests/acceptance/features/webUIFavorites/favoritesFile.feature
- tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
- tests/acceptance/features/webUIFiles/copyPrivateLinks.feature
- tests/acceptance/features/webUIFiles/download.feature
- tests/acceptance/features/webUIFiles/sort.feature
- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
- tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
- tests/acceptance/features/webUITrashbin/trashbinRestore.feature
- tests/acceptance/features/webUIUpload/uploadEdgecases.feature
- tests/acceptance/features/webUIWebdavLocks/unlock.feature
- tests/acceptance/stepDefinitions/filesContext.js
- tests/acceptance/stepDefinitions/sharingContext.js
With this PR:
- API steps made not to use `client.globals.currentUser` rather always mention `username` inside the step
- Fixes https://github.com/owncloud/phoenix/issues/3946
> See the related issue
- :robot:
> [Tests-Only] Modified API steps to always mention username

- .drone.star
- tests/acceptance/features/webUITrashbin/trashbinDelete.feature
- tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
- tests/acceptance/features/webUITrashbin/trashbinRestore.feature
Run trashbin webui tests on ocis
- https://github.com/owncloud/product/issues/139
- https://github.com/owncloud/ocis/pull/475
https://github.com/owncloud/phoenix/pull/3982/files
> [Tests-Only] Run trashbin tests on ocis

- tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature
- tests/acceptance/pageObjects/loginPage.js
- tests/acceptance/stepDefinitions/loginContext.js
- tests/acceptance/stepDefinitions/privateLinksContext.js
Added test scenario for `Access the private link anonymously`
- Fixes https://github.com/owncloud/phoenix/issues/2084
:robot:
> [Tests-Only]Added test for accessing a permalink anonymously

- apps/files/src/components/Roles/RoleItem.vue
- apps/files/src/components/Roles/RolesSelect.vue
- changelog/unreleased/adjust-roles-selection-dropdown
Remove roles description text from the roles selection button, but keep it in the dropdown list.
Add chevron icon on the right.
Part 10 of https://github.com/owncloud/product/issues/231
Manual test
> Tweak roles selection dropdown

- tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
Skip failing autocompletion tests.
These are new tests added recently and are failing very often in CI. This may be blocker for some PRs. 
New issue for this created to look into it in
https://github.com/owncloud/phoenix/issues/4122
> [Tests-Only] skip failing autocompletion tests

- tests/acceptance/pageObjects/filesPage.js
Fix the xpath of new button in files page for UI tests.
- Fixes test performance by some margin
Since the element didn't exist the tests would wait for 10 seconds every time
```
Given the user has browsed to the files page
Timed out while waiting for element <//button[@id="new-file-menu-btn" and contains(@class, "uk-button-primary")]> to be present for 10000 milliseconds. - expected "found" but got: "not found" (10005ms)
```
:robot:
> [Tests-Only] fix xpath of newfile button in filespage in ui tests

- .drone.star
Enable preview tests for mediaviewer
- Fixes preview tests not being run on CI
Preview tests were not running on drone
:robot:
> [Tests-Only] enable preview tests in drone

- .drone.star
Group the CI pipelines in drone to improve the overall runtime.
- Fixes Drone agent not being available when there are many builds running at same time.
Since there is no  easy way to share the build products between pipelines, each pipeline has to run a very long setup process to set up the system under test. This make the overall runtime of the CI very long. By grouping the suites that have very less tests, we can run multiple suites on a same build process. 
:robot:
> [Tests-Only] group test suites in drone to improve test runtime

- .drone.star
- tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
Refactor `webUISharingInternalUsers` to use Root and Shares folder for shares.
- Part of https://github.com/owncloud/ocis/issues/518
- CI
> [Tests-Only] Refactor webUISharingInternalUsers to use Shares folder

- tests/acceptance/features/webUISharingPublic/sharingPublicSession.feature
- tests/acceptance/helpers/httpHelper.js
- tests/acceptance/helpers/loginHelper.js
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/pageObjects/publicLinkPasswordPage.js
- tests/acceptance/stepDefinitions/publicLinkContext.js
Add UI tests for public link browser session for password protected public links.
- Fixes #4091
:robot:
> [Tests-Only] Add tests for browser session for public link tests

- tests/acceptance/helpers/loginHelper.js
[Tests-Only] maximize the window after starting new session for ui tests
> [Tests-Only] maximize the window after starting new session for ui tests

- .drone.star
Remove ci trigger from `develop-*` and `release-*` branches
- Fixes #4136
> [CI] Fix CI trigger on push and heads/master

- .drone.star
- tests/acceptance/features/webUIResharing/reshareUsers.feature
- tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
- tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
- tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
- tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
- tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
Add more sharing test suites in CI.
- related https://github.com/owncloud/ocis/issues/518
more tests = less bugs
:robot:
> [tests-only] Enable more sharing suites

- tests/acceptance/features/webUISharingExternal/federationSharing.feature
- tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
- tests/acceptance/features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature
- tests/acceptance/features/webUISharingFilePermissionsGroups/sharePermissionsGroup.feature
- tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
- tests/acceptance/features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature
- tests/acceptance/features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature
- tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
- tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalGroups/shareWithGroupsEdgeCases.feature
- tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroupsEdgeCases.feature
correcting some tags of issues in the sharing tests
part of https://github.com/owncloud/ocis/issues/518
make sure the tags show the correct issue why the tests are failing
:robot:
> [tests-only] correct issue tag id in sharing tests

- tests/acceptance/features/webUIResharing/reshareUsers.feature
make tests demonstrate and work despite https://github.com/owncloud/product/issues/203 & https://github.com/owncloud/ocis/issues/717
part of https://github.com/owncloud/ocis/issues/518
1. make tests work to avoid further regressions
2. have tests that demonstrate the current behaviour 
:robot:
> [tests-only] add tests demonstrating issue-product-203 issue-ocis-717

- .drone.star
- tests/acceptance/features/webUISharingNotifications/notificationLink.feature
- tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature
- tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
1. fix the issue that causes these tests to fail
1. add missing tests to drone, so that they will not be forgotten when the feature is finished
1. regroup tests to make CI faster
part of owncloud/ocis#518
> [tests-only] fix Notification UI tests

- .drone.star
run tests on the current ocis master
https://jira.owncloud.com/browse/OCIS-706
:robot:
> [tests-only] bump ocis-commit id and adjust settings

- apps/files/src/mixins.js
- changelog/unreleased/default-icon
> Change default file icon

- changelog/unreleased/update-ods-1.12.2
- package.json
- yarn.lock
This PR updates ODS to v1.12.2.
> Update ODS to 1.12.2

- apps/files/src/components/FileLinkSidebar.vue
- apps/files/src/mixins/deleteResources.js
Just a suggestion and a correction of a type I came along as I was translating in transifex.com
> Smirta patch 1

- tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature
Unskip tests that were skipped in CI.
- Fixes #4122
> Unskip failing autocompletion tests in ci

- docs/building.md
- docs/testing.md
Some minor changes to the build and test docs.
The main change is to correct the information about `phoenixBranch` and `phoenixCommit` in the OCIS repo starlark.
> [tests-only] Minor docs changes for building and testing

- .drone.star
Update the ocis commit id for running tests.
- ocis server out of date
> [Tests-Only] update ocis commitid for running acceptance tests

- tests/acceptance/features/webUIPreview/imageMediaViewer.feature
- tests/acceptance/pageObjects/FilesPageElement/mediaViewerPage.js
- This PR adds `@issue-4295` tag in `imageMediaViewer.feature` for scenario https://github.com/owncloud/phoenix/blob/645d91f0dadde314b3173afafe30eb3cff12bf59/tests/acceptance/features/webUIPreview/imageMediaViewer.feature#L27 
- Fixes previously failing test https://github.com/owncloud/phoenix/blob/645d91f0dadde314b3173afafe30eb3cff12bf59/tests/acceptance/features/webUIPreview/imageMediaViewer.feature#L36
- part of https://github.com/owncloud/phoenix/issues/4269
- :robot:
> [tests-only] added issue tag in imageMediaViewer test

- tests/acceptance/setup.js
fix max listeners execceded warning in ui tests
- Fixes https://github.com/owncloud/phoenix/issues/4004
> [Tests-Only] fix max listeners execceded warning in ui tests

- tests/acceptance/helpers/webdavHelper.js
Currently we need to wait between file uploads and deletes to avoid conflict for same file names. This PR fixes to wait only for filename matches to last upload.
- Fixes https://github.com/owncloud/phoenix/issues/4350
> [Tests-Only] only wait for upload/delete if for same user and file

- apps/files/src/components/FilesAppBar.vue
- changelog/unreleased/new-file-icon
> Add icon to new file menu

- README.md
README.md documentation link redirects to the web/getting-started documentation instead of general ocis docs
- Fixes https://github.com/owncloud/phoenix/issues/4397
- test case 1:
- test case 2:
- ...
> README.md documentation link redirects to the web/getting-started documentation

- .drone.star
- tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature
Update ocis commit id to most recent master for tests.
> [tests-only] Update ocis commit id for tests

- changelog/unreleased/hide-modals
- src/store/user.js
fix https://github.com/owncloud/ocis/issues/1064
> hide modals on logout

- appinfo/info.xml
Please check @micbar @dragotin @phil-davis
> Update info.xml for release

- changelog/unreleased/update-ods-2.0.3
- package.json
- yarn.lock
This ODS update brings the bugfix with the breadcrumbs breaking to a new line after the home icon.
> Update ODS to 2.0.3

- changelog/unreleased/main-position
- src/App.vue
together with 
https://github.com/owncloud/owncloud-design-system/pull/1002
it fixes 
https://github.com/owncloud/ocis/issues/1052
> Dom relative main

- appinfo/info.xml
> Fix typo in info.xml

- apps/files/docs/extensionpoints.adoc
- apps/files/src/helpers/collaboratorRolesDefinition.js
- apps/files/src/helpers/resources.js
- apps/files/src/helpers/route.js
- src/mixins/navigationMixin.js
- src/plugins/web.js
- src/web.js
- tests/acceptance/filesForUpload/file,with,comma,.txt
- tests/acceptance/helpers/path.js
- tests/acceptance/helpers/sharingHelper.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/stepDefinitions/filesContext.js
These are in tests and comments only, so no changelog needed.
I found them a few days ago in #4470 while I just wanted to run a test of CI. May as well commit them.
> [tests-only] Fix random typos

- tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
- tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
fixes issue #4437
- local environment
> [tests-only] Fix: Delete file in trashbin UI test step not working #4437

- tests/acceptance/run.sh
Use an associative array with the failed scenarios as keys. That will ensure that each failed scenario occurs only once in the report after the test run.
- Fixes #4518 
Demo of unexpected passes and fails in #4521
> [tests-only] Only report the unique failed scenarios in a test run

- src/store/modal.js
I noticed this typo `inputPlacehodler` - what good thing is going to happen with this typo fixed?
I have no idea what to write in a changelog, or even if to write a changelog?
CI
> Fix typo of inputPlaceholder

- tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
There are some functionally duplicate object props in `fileActionsMenu`
This PR clears such duplicates.
- local environment
> [tests-only] clean code duplication

- .drone.env
- .drone.star
- docs/testing.md
Doing a similar thing to OCIS PR https://github.com/owncloud/ocis/pull/1149
https://github.com/owncloud/ocis/issues/1132
CI
> [tests-only] remove commit id from .drone.star file

- tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature
Added issue tag for owncloud/web issue https://github.com/owncloud/web/issues/4310
- https://github.com/owncloud/web/issues/4310
- test case 1:
- test case 2:
- ...
> [tests-only] Added issue tag for scenario showing indirect shared indicator issue (owncloud/web)

- tests/acceptance/features/webUIFiles/fileList.feature
- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/stepDefinitions/filesContext.js
This PR adds webui tests for
1. folder creation in public share
2. batch deletion in public share
3. file/folder selection and clear selection in files page and in public share
4. assert that `roles dropdown of public share` changes in accordance with the user's selection
- Fixes https://github.com/owncloud/web/issues/4426
- CI
- Manual
> [Tests-Only] Add webui tests for various file operations by public in public share

- tests/acceptance/pageObjects/loginErrorPage.js
change import to require in loginErorrPage.js
- Fixes CI in ocis
the test infrastructure is also used in ocis to test the extensions (eg. accounts and setting), using import doesn't work there because of the way we import this code.
:robot:
> [Tests-Only] fix import statement in loginErrorPage

- tests/acceptance/features/webUIPreview/imageMediaViewer.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/stepDefinitions/filesContext.js
This PR adds webui test for image previews in file list view
- Fixes https://github.com/owncloud/web/issues/4514
- CI
> [Tests-Only] Add webui tests for previews in list view

- tests/acceptance/features/webUISharingExternal/federationSharing.feature
- https://github.com/owncloud/web/issues/4246
> [tests-only] Add webui test for checking accepted share from remote user is listed in shared-with-me page

- .drone.env
- tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.txt
This updates CI to use the latest OCIS code.
After this is merged, I will work on issue #4601 to sort out the extra test scenarios that became expected-failures here.
> [tests-only] Update OCIS_COMMITID for tests

- .drone.star
- tests/acceptance/features/webUIMarkdownEditor/markdownFile.feature
- tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js
- tests/acceptance/pageObjects/filesPage.js
- tests/acceptance/pageObjects/markdownEditorPage.js
- tests/acceptance/stepDefinitions/markdownEditorContext.js
- tests/acceptance/stepDefinitions/webdavContext.js
Adds webui tests for markdown editor
> [tests-only] Add webui tests for markdown editor

- appinfo/info.xml
- docs/releasing.md
Since we forgot to set the correct version in the oc10 appinfo we need a new release. This time with the correct version. Also updating the release process docs.
> [docs-only] Bump version for oc10 app

- docs/deployments/oc10-app.md
Fixing some smaller issues in the oc10 app deployment docs.
> [docs-only] Fix docs for oc10 app

- .github/CONTRIBUTING.md
Changed the broken URL with my educated guess on where it should link to instead
- Fixes #4655 
Potential contributor onboarding
Needs confirmation that I've added the correct URL
> [docs-only] Fixes #4655 (link to developer manual in CONTRIBUTING.md)

- tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
"OCIS extension" repos were archived. So, the issues in these archived repos have been moved to ocis. This PR adjust the link to issues in expected-failure file
- https://github.com/owncloud/ocis/issues/1215
- test case 1:
- test case 2:
- ...
> [Tests-Only] Adjust the links in the expected-failures file

- .drone.env
- .drone.star
- tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
- tests/drone/config.json
Konnectd has been renamed to IdP in the ocis repo. This PR adjusts drone accordingly.
> [tests-only] Follow renaming of konnectd to idp from ocis repo

- tests/acceptance/expected-failures-with-oc10-server.md
- tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
This PR changes issue number tagged for this test scenario. https://github.com/owncloud/web/blob/fb92fed62c2ff2cd6d379a00257f64f1feab1285/tests/acceptance/features/webUILogin/login.feature#L62
- Currently this test fails because of issue https://github.com/owncloud/web/issues/4677
- CI
> [Tests-Only] Change issue number in expected failure file forlogin test

- tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
- tests/acceptance/features/webUIAdminSettings/adminBlocksUser.feature
- tests/acceptance/features/webUILogin/adminBlocksUser.feature
- tests/acceptance/pageObjects/loginPage.js
- tests/acceptance/stepDefinitions/provisioningContext.js
This PR adds webUI test for disabling user by admin and preventing user from accessing any file.
- https://github.com/owncloud/ocis/issues/902
- CI
> [Tests-Only] add webUI tests for disabling user

- .drone.star
This PR updates the version of selenium used in drone ci.
- Fixes https://github.com/owncloud/web/issues/4672
- CI
> [Tests-only] Update selenium version

- .github/CONTRIBUTING.md
This PR updates the contributing guidelines to have proper content that matches this repo.
Partly fixes https://github.com/owncloud/web/issues/4666 (at least for this repo)
Fixes https://github.com/owncloud/web/issues/4655
> Rewrite contributing guidelines to proper content for this repo

- docs/testing.md
remove quotation marks escaping in docs
> fix testing docker command in docs

- Makefile
- packages/web-runtime/l10n/Makefile
- packages/web-runtime/package.json
- yarn.lock
Use correct paths in l10n makefile after switching to rollup
> Fix l10n paths

- tests/acceptance/stepDefinitions/provisioningContext.js
fix createUser function to handle users without email
- Fixes https://github.com/owncloud/web/issues/4679
- test case 1:
- test case 2:
- ...
> [Tests-Only] fix createUser function to handle users without email

- .drone.star
[CI] fix uploading screenshots to github on test failure
- Fixes https://github.com/owncloud/web/issues/4744
> [CI] fix uploading  screenshots to github on test failure

- .drone.env
> [tests-only] bump ocis commit id

- tests/acceptance/stepDefinitions/generalContext.js
to match changes being made in https://github.com/owncloud/owncloud-test-middleware/pull/6
> [tests-only] Refactor some function and var names

- .drone.env
This PR bumps to the latest ocis commit id
- https://github.com/owncloud/QA/issues/662
> [tests-only] Bump ocis commit id 2021-03-09

- docs/testing.md
Improve dos for running acceptance tests
- Fixes https://github.com/owncloud/web/issues/4775
> [docs-only] Improve docs for running acceptance tests

- .drone.env
- tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
- tests/acceptance/features/webUIPreview/imageMediaViewer.feature
This PR bumps to the latest ocis commit id
- https://github.com/owncloud/QA/issues/663
> [tests-only] Bump ocis commit id 2021-03-11

- docs/backend-ocis.md
- docs/getting-started.md
- docs/releasing.md
Found two broken links and spotted an opportunity to provide the reader with more information / a better context regarding web releases.
> [docs-only] Fix broken links & add more details

- tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
- tests/acceptance/features/webUIFiles/copy.feature
- tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
- tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
- tests/acceptance/stepDefinitions/filesContext.js
Some of the scenarios that had `tries to` in its step and didn't follow the normal workflow of the UI , weren't described in a detail manner .This PR tries to explain those kind of scenarios in a more detailed manner of the UI workflow.
- https://github.com/owncloud/web/issues/4680
- :robot:
> [tests-only] Adjusts webUI test scenarios with tries to in its step while canceling copy and move

- packages/web-runtime/l10n/Makefile
it should be OUT_DIR not OUTDIR in the makefile
> fix typo in makefile

- .drone.env
Bump OCIS_COMMITID to the commit at the end of 2021-03-17
> [tests-only] Bump OCIS_COMMITID to 2021-03-17

- changelog/unreleased/moment-js-set-locale-for-i18n
- packages/web-runtime/src/App.vue
This PR allows us to render translated moment-js strings e.G for the updated column in the all files list
- Fixes https://jira.owncloud.com/browse/WEB-184
> set momentjs locale to current langCode

- .drone.env
That was easy - no changes needed to expected-failures.
> [tests-only] Bump commit id for tests

- changelog/unreleased/fix-missing-tanslations-in-applications-menu
- packages/web-runtime/src/components/ApplicationsMenu.vue
Application names in the application switcher has not been translated, but will now.
- Fixes https://jira.owncloud.com/browse/WEB-184
> Fix missing translations in ApplicationsMenu Component

- packages/web-runtime/l10n/Makefile
translation step doesnt run because step isn't market as phony
get translations
- local setup
> mark translation steps as make phony

- changelog/unreleased/a11y-improvements-for-files-app-bar
- packages/web-app-files/src/components/FilesAppBar.vue
- Fixes https://github.com/owncloud/web/issues/4786
- test case 1:
- test case 2:
- ...
> Added announcer for selected files in files app bar

- packages/web-runtime/src/index.js
Log app loading failures.
Right now syntax errors like ReferenceErrors and alike are silently swallowed which makes it incredibly hard to debug why your app did not load.
(Obviously it would be nice to catch those errors in Rollup but that's a separate story)
- test case 1:
- test case 2:
- ...
> Do not swallow errors when loading extensions

- packages/web-app-files/src/components/PublicLinksSidebar/EditPublicLink.vue
- packages/web-app-files/src/components/Roles/RolesSelect.vue
- test case 1:
- test case 2:
- ...
> Text input refactor public link

- packages/web-app-files/src/components/Collaborators/NewCollaborator.vue
- test case 1:
- test case 2:
- ...
> refactor new collaborator component

- Makefile
Fix build release Makefile target for official build servers
Make it compatible with our processes
- manually
> fix missing makefile target for build systems

- .drone.env
- .drone.star
> [Tests-Only]Bump commit id for tests

- .drone.star
Use the same Go docker image as in https://github.com/owncloud/ocis
- Fixes #4890 
- test case 1:
- test case 2:
- ...
> switch to owncloudci/golang

- package.json
- rollup.config.js
- yarn.lock
This adds the livereload plugin to the rollup config.
I understand that this is a feature maybe not everyone likes. So we might want to make it optional if we add it at all.
Just sending a PR to further discuss it here.
What do you think?
Unfortunately this is not a true module hot reload like webpack offers, but at least I have to press F5 less often 😇 
- test case 1:
- test case 2:
- ...
> Add livereload plugin to rollup

- tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
- tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
- tests/acceptance/features/webUILogin/adminBlocksUser.feature
- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
- tests/acceptance/features/webUIResharing/reshareUsers.feature
- tests/acceptance/features/webUIResharingToRoot/reshareUsers.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
- tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsUsers.feature
- tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
- tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
- tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
- tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
- tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
- tests/acceptance/features/webUIUpload/upload.feature
- tests/acceptance/features/webUIUpload/uploadEdgecases.feature
Fix test scenarios with same title on same file
- Fixes scenarios with the same name
this will help an automated tool to update expected failure files
> [Tests-Only] Fix test scenarios with same title on same file

- tests/acceptance/features/webUIFiles/copy.feature
- tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
- tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/locationPicker.js
- tests/acceptance/pageObjects/personalPage.js
- tests/acceptance/stepDefinitions/filesContext.js
This PR
1. Refactors webUI scenarios with "tries to copy" & "tries to move" steps. 
2. Removes unused functions that was previously used in "tries to" step
- https://github.com/owncloud/web/issues/4680
- CI
> [Tests-Only] Refactor webui scenarios with 'tries to'

- tests/acceptance/stepDefinitions/provisioningContext.js
use path.join to construct skeleton directory path in acceptance tests.
> [Tests-Only] use path.join to construct skeleton dir path

- tests/acceptance/features/webUIFavorites/favoritesFile.feature
- tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- tests/acceptance/features/webUIRenameFolders/renameFolders.feature
- tests/acceptance/features/webUIResharing/reshareUsers.feature
- tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
- tests/acceptance/features/webUISharingExternal/federationSharing.feature
- tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
- tests/acceptance/features/webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature
- tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
- tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
- tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
- tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
- tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
- tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
- tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
- tests/acceptance/features/webUIUserJourney/journey1.feature
- tests/acceptance/features/webUIWebdavLocks/locks.feature
- tests/acceptance/features/webUIWebdavLocks/unlock.feature
Replace consequent scnearios with same type (eg. Then, Then) to and
To make scenarios more consistent
> [Tests-Only] replace consequent test steps with same type as And

- packages/web-integration-oc10/appinfo/info.xml
we accidentally bumped the oc10 integration version withou having the release finished.
- test case 1:
- test case 2:
- ...
> decrease oc10 integration version number

- .drone.env
Bumped ocis commit id in the web.
> [Tests-Only] Bumped ocis commit id in web

- .github/CONTRIBUTING.md
- .github/settings.yml
- README.md
- docs/backend-ocis.md
- docs/building.md
- docs/releasing.md
- packages/web-app-files/src/store/actions.js
- packages/web-integration-oc10/appinfo/info.xml
- change references from owncloud.github.io to owncloud.dev
- fix some dead urls
> change from owncloud.github.io to owncloud.dev and fix dead urls

- tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
- tests/acceptance/features/webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature
- tests/acceptance/features/webUIUpload/upload.feature
- tests/acceptance/features/webUIUpload/uploadEdgecases.feature
- tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
- tests/acceptance/features/webUIUserJourney/journey1.feature
- tests/acceptance/features/webUIWebdavLockProtection/delete.feature
- tests/acceptance/features/webUIWebdavLockProtection/move.feature
- tests/acceptance/features/webUIWebdavLockProtection/upload.feature
- tests/acceptance/features/webUIWebdavLocks/locks.feature
- tests/acceptance/features/webUIWebdavLocks/unlock.feature
refactor upload tests to not use skeleton files
- Related https://github.com/owncloud/QA/issues/659
> [Tests-Only] refactor upload tests to not use skeleton files

- .drone.star
split ocis Files test suite in CI
- Faster CI
To get CI completed under 30 mins
> [CI] split ocis Files test suite in CI

- docs/backend-ocis.md
link directly to oCIS demo users instead to getting started
- Possible after https://github.com/owncloud/ocis/pull/1907
> [docs-only] direct link to demo users

- .drone.star
Fix the screenshots cache url.
- Fixes https://github.com/owncloud/web/issues/4952
> [CI] Update screenshots cache server endpoint

- tests/acceptance/helpers/config.js
- tests/acceptance/helpers/occHelper.js
- tests/acceptance/setup.js
Remove use of plimit from the acceptance tests.
Delete `share_folder` system config before running tests.
- Intermittent test failures in `xgaPortrait` test suite.
> [Tests-Only] Remove promise limit and delete share_folder config on before

- tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
- tests/acceptance/features/webUITags/createTags.feature
- tests/acceptance/features/webUITags/tagsSuggestion.feature
- tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
- tests/acceptance/features/webUITrashbinFilesFolders/trashbinFilesFolders.feature
- tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
Refactor trashbin tests to remove the use of skeleton files
- Related https://github.com/owncloud/QA/issues/659
> [Tests-Only] refactor tags and trashbin tests to not use skeleton files

- tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
- tests/acceptance/expected-failures-with-oc10-server-openid-login.md
- tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
- tests/acceptance/features/webUIPreview/imageMediaViewer.feature
- tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature
- tests/acceptance/features/webUIRestrictSharing/disableSharing.feature
- tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
- tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
- tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
Refactor scenarios for not using skeleton files
- webUIPreviews
- webUIPrivateLinks
- webUIRestrictSharing
- Related owncloud/QA#659
🤖
> [Tests-Only] refactor restrict sharing tests to not use skeleton files

- changelog/unreleased/change-bump-ods-version
- docs/getting-started.md
- docs/releasing.md
- docs/theming/_index.md
- packages/web-app-files/src/components/AppBar.vue
- packages/web-app-files/src/components/Sidebar.vue
- packages/web-app-files/src/components/UploadProgress.vue
- packages/web-app-files/src/views/LocationPicker.vue
- packages/web-runtime/package.json
- packages/web-runtime/src/App.vue
- yarn.lock
Update ODS to v6.0.0 and adapt CSS color variables & docs to the changes
> Update ods to 6.0.0

- .drone.env
This PR bumps to the latest ocis commit id
- https://github.com/owncloud/QA/issues/662
> [tests-only] Bump ocis commit id 2021-04-22

- changelog/unreleased/enhancement-h-tags
- packages/web-app-files/src/index.js
- packages/web-app-files/src/views/FilesDrop.vue
- packages/web-app-files/src/views/PrivateLink.vue
- packages/web-app-files/src/views/PublicLink.vue
- packages/web-runtime/src/pages/accessDenied.vue
- packages/web-runtime/src/pages/account.vue
- packages/web-runtime/src/pages/login.vue
- packages/web-runtime/src/pages/missingOrInvalidConfig.vue
- packages/web-runtime/src/pages/oidcCallback.vue
Make sure that pages have an h1 tag and streamline the h-tag hierarchy a bit (not complete, but making it better).
- Partly fixes https://github.com/owncloud/web/issues/5003
> Finetune h-tags

- packages/web-runtime/src/components/ApplicationsMenu.vue
* Fix aria-expand on the button, which was set to false, while opening the oc-drop
* Wrap app switcher in nav element
* Use list element for items
* Replace the visible function with UI Kit functions because i did not work at all  
- test case 1:
- test case 2:
- ...
> Enhance a11y on app-switcher

- changelog/unreleased/enhancement-bump-ods-version
- packages/web-app-files/src/components/AppBar.vue
- packages/web-app-files/src/views/LocationPicker.vue
- packages/web-runtime/package.json
- packages/web-runtime/src/App.vue
- tests/acceptance/pageObjects/personalPage.js
- yarn.lock
ODS needs to be bumped to 6.2.0 before this can be merged
> Bump ODS to 6.2.0 & add necessary changes

- changelog/unreleased/enhancement-account-definition-list
- packages/web-runtime/src/pages/account.vue
- tests/acceptance/pageObjects/accountPage.js
> Use a proper definition list for the account settings page

- changelog/unreleased/enhancement-focustrap-in-modal
- packages/web-runtime/package.json
- packages/web-runtime/src/App.vue
Enables focus-trap in oc-modal, needs an ODS release & version bump (=> yarn.lock) before merge
> [WIP] Enable focustrap in modal

- .drone.env
This PR bumps to the latest ocis and core commit id
- https://github.com/owncloud/QA/issues/662
> [Tests-Only]Bump commit IDs on web 2021-04-26

- changelog/unreleased/enhancement-accessibility-improvements
- packages/web-app-files/src/components/FileLinkSidebar.vue
- packages/web-app-files/src/components/FilesLists/QuickActions.vue
See code/changelog item. Found another unsused CSS class (deleted by the evil PR ™️ ) that we could let go
> Translate quick action labels/tooltips

- packages/web-app-files/src/components/AppBar.vue
- packages/web-app-files/src/views/LocationPicker.vue
Tiny style alignments for the location picker and the All files page.
> Tiny style improvements

- changelog/unreleased/bugfix-translated-user-menu-items
- packages/web-runtime/src/components/UserMenu.vue
> Translate user menu items correctly

- packages/web-runtime/package.json
- yarn.lock
ods uses focus-trap as peerDependency. This PR adds it to the runtime
- test case 1:
- test case 2:
- ...
> Focus trap

- .eslintrc.json
- packages/web-app-files/src/components/Collaborators/Collaborator.vue
- packages/web-app-files/src/components/Collaborators/NewCollaborator.vue
- packages/web-app-files/src/components/FileLinkSidebar.vue
- packages/web-app-files/src/components/FileSharingSidebar.vue
- packages/web-app-files/src/components/FolderUpload.vue
- packages/web-app-files/src/components/PublicLinksSidebar/LinkInfo.vue
- packages/web-app-files/src/components/PublicLinksSidebar/PrivateLinkItem.vue
- packages/web-runtime/src/pages/missingOrInvalidConfig.vue
- packages/web-runtime/src/pages/oidcCallback.vue
get linter green
to have a linter valid code
- test case 1:
- test case 2:
- ...
> make linter happy

- .drone.star
- tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
- tests/drone/config-oc10-integration-app-oauth.json
With this PR:
- smoke tests are run against web from oc10-integration-app
- Fixes https://github.com/owncloud/web/issues/4887
- increase test range
- :robot:
> [Tests-Only] Run smoke tests with oc10-integration app

- changelog/unreleased/bugfix-sizeable-html-container
- rollup.config.js
> Make html container resize-able

- tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
- tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
- tests/acceptance/run.sh
closes https://github.com/owncloud/web/issues/5026
> [Tests-Only] Include tests with undefined steps in failed list in run.sh

- changelog/unreleased/enhancement-remove-notification-autoclose
- packages/web-app-draw-io/src/App.vue
- packages/web-app-files/src/components/AppBar.vue
- packages/web-app-files/src/components/BatchActions.vue
- packages/web-app-files/src/views/LocationPicker.vue
- packages/web-app-files/src/views/SharedWithMe.vue
- packages/web-runtime/src/components/Notifications.vue
- packages/web-runtime/src/components/SearchBar.vue
- packages/web-runtime/src/store/app.js
Remove autoclose on notifications as we handle this in the component with https://github.com/owncloud/owncloud-design-system/pull/1247.
> Remove autoclose on notifications

- .drone.star
- nightwatch.conf.js
- tests/acceptance/stepDefinitions/generalContext.js
add skip option in drone.star to skip a test section
use `client.saveScreenshots()` to save screenshots rather than from the config. This allows to have flexible filenames and only generate screenshots on retry
Fixes https://github.com/owncloud/web/issues/4869
Help while debugging acceptance tests in CI
> [Tests-Only] use webdriver api to generate screenshots with proper filename

- tests/acceptance/run.sh
Before actually running the UI acceptance tests, check that the directory for each test suite exists. Fail the run if a suite directory is missing.
- Fixes #5089
CI - demonstration in test PR #5092 - that purposely tries to run invalid test suites. It fails as expected.
> [tests-only] Fail CI if any of the test suites does not exist

- .drone.env
issue https://github.com/owncloud/QA/issues/662
> [tests-only] Bump commit ids for tests

- .drone.star
adds feature to be able to run only specific test suites in CI
Part of https://github.com/owncloud/QA/issues/670
> [tests-only] Feature to debug specific test suites in CI

- .drone.star
use glauth from the monorepo instead of ocis-glauth repo(old version) in CI.
We do not run test using openIdConnect in CI currently, but all the necessary setup for openIdConnect is still in .drone.star.
This is because the setup described in https://owncloud.dev/ocis/deployment/bridge/ doesn't works currently.
This Pr just updates the repo from which glauth for when we again run tests using openIdConnect In CI.
- Fixes https://github.com/owncloud/web/issues/4888
> [CI] use ocis repo for glauth

- changelog/unreleased/bugfix-make-skip-to-visible
- packages/web-runtime/src/components/SkipTo.vue
Increase z-index and use brand background
> fix: make skip to link visible on focus

- tests/acceptance/pageObjects/markdownEditorPage.js
- tests/acceptance/stepDefinitions/markdownEditorContext.js
Wait for markdown editor after opening a file in markdown editor
- Fixes intermittent failure webUIMarkdownEditor/markdownFile.feature:33
> [Tests-Only] wait for markdown page after opening file in markdown editor

- tests/acceptance/features/webUIRenameFiles/renameFiles.feature
- part of : https://github.com/owncloud/web/issues/4919
-  :robot:
> [tests-only] Add correct test step to fix intermittent fail

- changelog/unreleased/enhancement-a11y-colors
- packages/web-app-files/src/components/Sidebar.vue
> improve oc-star color contrast

- .drone.star
- tests/acceptance/run.sh
currently, cache ocis waits for the lint tests to complete, this changes it so that ocis tests can start a bit faster, and while build will complete a bit faster.
Also increase test timeout as sometimes it takes longer to start the ocis server.
- Fixes slow ocis tests
:robot:
> [CI] Run cache ocis pipeline before tests and increase test timeout

- .drone.star
Fix the apache server to host web not starting in CI.
eg https://drone.owncloud.com/owncloud/web/15682/60/5
- Fixes random CI failures
:robot:
> [CI] Fix web not starting in CI

- .drone.env
This PR bumps core and ocis commit id to check if there are any test failing
- part of : owncloud/QA#662
- :robot:
> [tests-only]Bump ocis and core commit id for tests

- packages/web-runtime/src/components/ApplicationsMenu.vue
Updated aria-label for main navigation `<nav>` element
> Change main navigation aria-label

- changelog/unreleased/enhancement-confirmation-link-deletion
- packages/web-app-files/src/components/FileLinkSidebar.vue
- packages/web-app-files/src/components/PublicLinksSidebar/LinkActions.vue
- tests/acceptance/customCommands/uploadRemote.js
- tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
Added confirm modal & notification for public link deletion
- Fixes #3924
> Add delete confirmation for public links

- changelog/unreleased/enhancement-file-previews
- docs/getting-started.md
- packages/web-app-files/src/store/actions.js
- packages/web-runtime/src/store/config.js
Introduce a new config option to configure which file extension get a preview
- Fixes #5079
reduce unnecessary requests
> add option to enable preview for specific files only

- changelog/unreleased/bugfix-make-skip-to-visible
- packages/web-runtime/src/components/SkipTo.vue
> Add focus border to skip-to-main button

- .drone.star
reduce apache output log in tests
these logs are usually not needed and with that change we will save a couple of hundreds lines of log output in every step of the pipeline
> [tests-only] send apache log to /dev/null

- .drone.star
This PR enables fail-early system for tests running in CI. 
When ever a test suite fails, it stops the particular build so that the resources are not wasted.
The `drone.star` is adjusted such that for the suites where `earlyFail` feature is set to `True`, any test failure in that suite stops the build. If we do not want the failing tests in a suite to stop the build, we can adjust `earlyFails = False`  for the particular test suite. 
Whenever a test suite fails, a github comment is generated which helps us identify which test failure actually stopped the build.
- https://github.com/owncloud/QA/issues/672
The drone build seems to be run for all the suites even when a particular suite fails early. To reduce the amount of CI resources used we needed a fail-early system, so that when one …
> [Tests-Only]Early Fail Strategy

- changelog/unreleased/enhancement-bump-ods-version
- packages/web-runtime/package.json
- yarn.lock
> Bump ODS to 7.0.1

- .drone.star
Reduce the number of pipelines running in the CI by merging the suites.
Also add code to check if any test suites are missing in the CI run.
Number of pipelines running before this PR - 100
Number of pipelines running after this PR - 64
When we run multiple pipelines, it needs to setup server, run databases, selenium etc on each pipeline so reducing this number will hopefully reduce the load in CI server
- Fixes https://github.com/owncloud/web/issues/5158
#:robot:
> [CI] Reduce the number of test pipelines in CI

- .drone.star
since #5145 on the nightly cron no more tests are run. This PR will add them again.
> revert removal of tests on cron run (#5145)

- packages/web-app-files/src/helpers/statusIndicators.js
- tests/acceptance/pageObjects/FilesPageElement/filesList.js
Use first `test-data-` attributes in tests.
Test resilience
> Status indicators

- tests/acceptance/pageObjects/FilesPageElement/filesList.js
- tests/acceptance/pageObjects/personalPage.js
- tests/acceptance/pageObjects/sharedWithOthersPage.js
This PR fixes extracting the link name from the OcAvatarLink component.
> Fix link avatar selector

- tests/acceptance/helpers/occHelper.js
Reset opcache after running occ command in acceptance tests
- Fixes https://github.com/owncloud/web/issues/5214
:robot:
> [Tests-Only] reset opcache after running occ commands

- packages/web-app-files/src/components/Collaborators/EditCollaborator.vue
- packages/web-app-files/src/components/FileSharingSidebar.vue
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
Should fix most of the remaining failures in CI
> Linter fixes + screenreader hint to prevent dropdown open on edit collaborator

- packages/web-app-files/src/components/PublicLinksSidebar/LinkInfo.vue
- tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature
- tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/pageObjects/sharedWithMePage.js
- tests/acceptance/pageObjects/webPage.js
Fixed test selectors
Not too sure how the code changes handle the `undefined` scenario when getting the expiration date so opened a separate PR
> [full-ci] Fix selectors for expiration dates and web container

- .gitattributes
Added the wrong line of code 🥴 now it should work fine
> Fix the way .feature files are handled in .gitattributes

- tests/acceptance/features/webUIFilesCopy/copy.feature
- tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
- tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
- tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
- tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
- tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
- tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
- tests/acceptance/features/webUIUpload/upload.feature
OCIS CI has been changed so that it only runs the `ocisSmokeTest` scenarios, rather than running all `owncloud/web UI ` acceptance tests.
This PR 
- reviews the scenarios tagged `ocisSmokeTest`
- selects other scenarios to tag `ocisSmokeTest`
- Fixes: https://github.com/owncloud/web/issues/5167
To make sure that the basic web behavior is properly covered and tested
- locally
- ci
- https://github.com/owncloud/ocis/pull/2135
> [tests-only] Add ocisSmokeTest tag to tests

- package.json
- packages/web-app-files/tests/views/SharedWithMe.setup.js
- packages/web-runtime/tests/mixins/focusMixin.spec.js
unit tests inside of the packages have not been linted so far, so add them to the list of sources to be linted and fix the issues
clean code
`yarn run lint`
> [tests-only] run lint also on unit-tests inside of the packages

- package.json
- packages/web-runtime/tests/components/UserMenu.spec.js
- tests/unit/stubs/index.js
- yarn.lock
testing UserMenu.vue file
- test if items are displayed when the userId is set
- test if items are hidden when the userId is empty
- test logout button
part of #5217
more unit tests
:robot:
> [tests-only] unit tests for UserMenu.vue

- .drone.star
- packages/web-app-files/src/helpers/resources.js
- packages/web-runtime/package.json
- rollup.config.js
- yarn.lock
- test case 1:
- test case 2:
- ...
> [full-ci] Update owncloud-sdk to latest version

- packages/web-app-files/tests/components/FileUpload.spec.js
unit tests added for the `FileUpload` component
- part of #5234
unit test coverage
> [tests-only] Unit test for FileUpload component

- .drone.star
> ci: replace unmaintained alpine step image

- changelog/unreleased/bugfix-center-mediaviewer-loadingspinner
- packages/web-app-media-viewer/src/App.vue
See changelog item
- Fixes #5196
> Vertically center mediaviewer loadingspinner

- .drone.env
Bumped commit IDs of ocis and core in web.
part of issue https://github.com/owncloud/QA/issues/662
> [full-ci][Tests-Only]Bump web commit ID 2021-06-14

- README.md
not impressive (yet), but still good to see
part of #5217
see progress => get motivated
> [skip-ci] add coverage badge

- docs/theming/_index.md
Following feedback by @micbar I removed the (invalid) comments inside the `.json` examples, added new variables we added in the ODS and updated the documentation which hadn't been communicating the current theming capabilities
> [docs-only] Update theming docs with new variables & capabilities

- .drone.star
- tests/drone/build-glauth.sh
- tests/drone/build-idp.sh
- tests/drone/build-ocis-web.sh
- tests/drone/build-web-app.sh
- tests/drone/build-web.sh
- tests/drone/copy-files-for-upload.sh
- tests/drone/get-ocis.sh
- tests/drone/setup-fed-server-and-app.sh
- tests/drone/setup-graph-api-oidc.sh
- tests/drone/setup-integration-web-app.sh
- tests/drone/setup-notifications-app.sh
- tests/drone/setup-oauth2.sh
large script commands used in different steps are separated to `tests/drone`
- Part of #5231 
- 🤖
> [tests-only] [full-ci] Separated large scripts

- packages/web-app-files/tests/unit/components/Collaborators/Collaborator.spec.js
check if the share type and the icon is displayed correctly in the collaborators component
part of #5234
> [unit-tests-only] display share type in collaborator component

- packages/web-app-files/tests/unit/components/Collaborators/AutocompleteItem.spec.js
- packages/web-app-files/tests/unit/components/Collaborators/Collaborator.spec.js
- packages/web-runtime/tests/unit/components/Notification.spec.js
- packages/web-runtime/tests/unit/mixins/lifecycleMixin.spec.js
- tests/acceptance/features/webUIWebdavLocks/locks.feature
Adjust a few words in unit tests, nostly in the text of `it()` 
CI
> [unit-tests-only] Adjust the text of unit test it() calls

- tests/acceptance/features/webUIPreview/imageMediaViewer.feature
As issue https://github.com/owncloud/web/issues/4295 no longer exist. This PR removes tag `@issue-4295` from test.
- https://github.com/owncloud/web/issues/4295
- :robot:
> [full-ci][Tests-Only]Remove tag @issue-4295
