owncloud/web

.drone.star, tests/drone/build-glauth.sh, tests/drone/build-idp.sh, tests/drone/build-ocis-web.sh, tests/drone/build-web-app.sh, tests/drone/build-web.sh, tests/drone/copy-files-for-upload.sh, tests/drone/get-ocis.sh, tests/drone/if-diff-has-unit-tests-only.sh, tests/drone/setup-fed-server-and-app.sh, tests/drone/setup-graph-api-oidc.sh, tests/drone/setup-integration-web-app.sh, tests/drone/setup-notifications-app.sh, tests/drone/setup-oauth2.sh, tests/drone/setup-server-and-app.sh
With this PR, acceptance test suites are checked before and decided whether to run or skip w.r.t diff. If diff contains unit test files only, acceptance tests steps are skipped.
- Fixes https://github.com/owncloud/web/issues/5231
- 🤖
=> [full-ci] [tests-only] Do not run acceptance tests if only unit tests files are changed

.github/CONTRIBUTING.md, packages/web-runtime/src/pages/missingOrInvalidConfig.vue
=> [docs-only] Reflect channel renaming in talk.owncloud.com in links

packages/web-runtime/package.json, yarn.lock
Fixes language reset in oCIS settings extension
=> Reduce oc-sdk version to make oCIS settings work

.drone.env
Bumped commit IDs of `ocis` and `core`
part of https://github.com/owncloud/QA/issues/662
=> [full-ci][tests-only] Bump commit ids for tests

.drone.star, .gitignore, tests/acceptance/run.sh
Report scenarios that pass on retry to github.
- Related https://github.com/owncloud/web/issues/5257 
There are many intermittent failing tests that fail occasionally in drone but we never know about them because they pass on retry. With this PR we will at least know about scenarios that pass on retry
🤖
=> Report scenarios that pass on retry to github

.drone.star
… complete
- test case 1:
- test case 2:
- ...
=> [CI] start acceptance tests only after unit and integration tests are complete

changelog/unreleased/bugfix-image-source-updates, packages/web-runtime/src/plugins/mediaSource.js
Images loaded via v-image-source are not updated when the url changes.
I'm using it in web-app-ownbrander and it works this way.
=> Fix v-image-source updates

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md, tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md, tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature, tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature, tests/acceptance/features/webUISharingExternal/federationSharing.feature, tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature, tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature, tests/acceptance/stepDefinitions/filesContext.js, tests/acceptance/stepDefinitions/webdavContext.js
- Fixes #5405
- test environment: CI :robot:
=> [full-ci][tests-only] Check resource type in test steps

tests/acceptance/stepDefinitions/webdavContext.js
Refactors code added in PR #5402
=> [full-ci][tests-only] Refactor assertResourceType added in PR #5402

.drone.star, tests/drone/build-ocis.sh
If git diff contains unit tests files only, then cache ocis step on drone ci is skipped
- optimize ci speed
- 🤖
=> [tests-only] skip cache ocis step if diff contains unit tests only

packages/web-app-files/src/components/SideBar/Shares/Collaborators/ShowCollaborator.vue, packages/web-app-files/tests/unit/components/Collaborators/ShowCollaborator.spec.js
Unit tests for resharer information in the collaborator menu
I've added also some basic checks of the resharer data.
to discuss: do we want to have those checks in the code here? Is the data checked somewhere else? Are we trusting the server API to send correct data?
- part of #5234
- 
more unit tests
=> [unit-tests-only] more tests for collaborator component

packages/web-app-files/src/components/AppBar/SelectedResources/BatchActions.vue, packages/web-app-files/tests/components/BatchActions.spec.js, packages/web-app-files/tests/unit/components/BatchActions.spec.js
unit tests added for the `BatchActions` component
- part of #5234
unit test coverage
=> Unit tests for BatchActions component (part1)

tests/acceptance/features/webUISharingExternal/federationSharing.feature, tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature, tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature, tests/acceptance/features/webUISharingInternalGroupsToRoot/shareWithGroups.feature, tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature, tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature, tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature, tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature, tests/acceptance/features/webUIUpload/upload.feature, tests/acceptance/features/webUIUpload/uploadEdgecases.feature, tests/acceptance/features/webUIUserJourney/journey1.feature, tests/acceptance/stepDefinitions/generalContext.js
refactor step defination
https://github.com/owncloud/ocis/issues/2258#issuecomment-873940933
- 🤖
=> [tests-only] Refactored confusing step definition

tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature, tests/acceptance/helpers/httpHelper.js, tests/acceptance/helpers/sharingHelper.js, tests/acceptance/stepDefinitions/provisioningContext.js
Because of a bug in user creation in ocis(https://github.com/owncloud/ocis/issues/2272), few tests fail and only pass on retry.
eg https://github.com/owncloud/web/pull/5463#issuecomment-875304042
This Pr fixes that issue.
- Fixes https://github.com/owncloud/web/issues/5438
:robot:
=> [full-ci][Tests-Only] Fix intermittent failure on user creation

changelog/unreleased/bugfix-details-preview, packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
Fix loading previews in the details accordion in the right sidebar
=> Fix loading previews in the right sidebar

changelog/unreleased/bugfix-view-options-position, packages/web-app-files/src/components/AppBar/AppBar.vue
=> fix: view options position

packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ShowCollaborator.spec.js
test the display of the role of the collaborator
part of #5234
:robot:
=> [unit-tests-only] role of collaborator

tests/acceptance/helpers/webdavHelper.js
Remove unnecessary console.log line in webdavHelper added accidentally in https://github.com/owncloud/web/pull/5511/files#r667860992
=> [Tests-Only] Remove unnecessary console.log line in webdavHelper

docs/deployments/oc10-app.md
=> [docs-only] Fix http->https in OC10 example config docs

packages/web-app-files/tests/unit/components/FilesList/ListInfo.spec.js
Added unit tests for `ListInfo` component
- https://github.com/owncloud/web/issues/5234
- 🤖
=> [unit-tests] Added unit tests for ListInfo component

packages/web-app-files/tests/unit/components/FilesList/NotFoundMessage.spec.js
- unit tests for `NotFoundMessage` component are added
- 🤖 
- 👨🏼‍🎨
=> [tests-only] [unit-tests] Added unit tests for NotFoundMessage component

tests/acceptance/features/webUICreateFilesFolders/createFolders.feature, tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature, tests/acceptance/features/webUIRenameFolders/renameFolders.feature, tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature, tests/acceptance/features/webUITrashbinFilesFolders/trashbinFilesFolders.feature, tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature, tests/acceptance/stepDefinitions/filesContext.js
- Add UI tests for dot in folder name
- Test for https://github.com/owncloud/ocis/issues/2193
=> [Tests-Only]Add UI tests for dot in folder name

packages/web-app-files/src/components/AppBar/SelectedResources/SizeInfo.vue, packages/web-app-files/tests/unit/components/AppBar/SelectedResources/SizeInfo.spec.js
Adds unit  tests for `SizeInfo` component
=> [unit-tests] unit tests for SizeInfo component

packages/web-app-media-viewer/src/App.vue
Media Viewer does not remove red rectangle
- Fixes #4648
It solves the problem that a warning sign won't disappear in image gallery
- tested by programmer
=> Resolve issue #4648

packages/web-app-files/tests/unit/components/AppBar/SelectedResources/BatchActions.spec.js
followup PR of PR #5282
adds more tests in BatchActions component
- part of #5234
unit test coverage
- local
=> Unit tests for BatchActions component (part2)

packages/web-app-files/tests/unit/components/AppBar/Upload/FileDrop.spec.js
Adds unit  tests for `FileDrop` component
=> [unit-tests] unit tests for FileDrop component

.drone.env
This PR bumps core and ocis commit id to make sure that tests ares passing
- part of : https://github.com/owncloud/QA/issues/680
- CI
=> [full-ci][tests-only] bump core and ocis commit id

docs/deployments/oc10-app.md
Documentation on https://github.com/owncloud/web/pull/5536
Document functionality from https://github.com/owncloud/web/pull/5536
- test case 1:
- test case 2:
- ...
=> [docs-only] add OpenID Connect documentation for oC10

packages/web-app-files/tests/unit/components/FilesList/Pagination.spec.js
- added unit tests for `Pagination` component from `FilesList` view
- every component should be tested
- :robot:
- 💇🏼‍♂️
=> [unit-tests] added unit tests for FilesList Pagination component

.drone.env
Bump OCIS and core commit id
- part of : https://github.com/owncloud/QA/issues/680#issuecomment-888057804
- CI
=> [tests-only][full-ci]bump core and ocis commit id

changelog/unreleased/enhancement-filestable-dropdown-actions, changelog/unreleased/enhancement-invite, packages/web-app-files/src/components/SideBar/Shares/Collaborators/AutocompleteItem.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/NewCollaborator.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/RecipientContainer.vue, packages/web-runtime/package.json, tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js, yarn.lock
Replace `OcAutocomplete` in sharing sidebar with Invite.
- test environment: Ubuntu Firefox & Chrome
- test case 1: Share with single user
- test case 2: Share with multiple users
=> [full-ci] feat: add invite instead of autocomplete

.drone.star, tests/acceptance/cancelBuilds.sh
This PR tries to get recent builds for a particular branch. 
- https://github.com/owncloud/QA/issues/674
- [] Acceptance tests added
=> [Tests-Only]Cancel old builds for the same pr

.drone.env
I bumped the commit ids for CI against OCIS and oC10 just to be sure there is nothing unexpected when running against the current master of those server implementations. It passes without having to mess with any expected-failures - good.
CI
=> [tests-only] Bump test commit ids

packages/web-app-files/src/components/FilesList/ContextActions.vue
=> Fix overflow in context-menu links

.drone.star
run unit and integration tests on tags
- Fixes https://github.com/owncloud/web/issues/5620
=> [tests-only] run unit and integration tests on tags

.drone.env, tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
This PR bumps core and ocis commit id to latest to make sure that all the tests pass
- part of : https://github.com/owncloud/QA/issues/684#issue-957724659
- CI
=> [full-ci][tests-only] Bump core and ocis commit id to latest

packages/web-runtime/src/pages/accessDenied.vue
We have had much feedback that the existing message, while not incorrect is confusing for users where their session has expired or been logged out.  There may be multiple scenarios where users come to this page but it should cater for all of these an explain what has happened in a clear way.
Totally open to alterations on this message - it's an important page to communicate what has happened to the user.
=> Improve wording of access denied message to user

tests/acceptance/helpers/webdavHelper.js, tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js, tests/acceptance/pageObjects/FilesPageElement/appSideBar.js, tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js, tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js, tests/acceptance/pageObjects/personalPage.js, tests/acceptance/pageObjects/sharedWithMePage.js, tests/acceptance/stepDefinitions/filesContext.js, tests/acceptance/stepDefinitions/generalContext.js, tests/acceptance/stepDefinitions/privateLinksContext.js
CI is waiting a lot at the moment. This PR tries to reduce that wherever possible. Mainly it fixes an unneeded 10 seconds waiting in the right sidebar for a `back` button when already being in the root panel.
=> [full-ci] Fix ci waiting times

packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js
Adds unit  tests for `AppBar` component
=> [unit-tests-only] Add unit tests for AppBar component

packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/ListItem.spec.js
- added unit tests for `ListItem` component from `web-app-files` package
- add unit tests coverage
- 🤖
=> Added unit tests for link list item component

tests/acceptance/features/webUIMarkdownEditor/markdownFile.feature
- Adds ```@disablePreviews``` in markdown feature to stop flaky test due to locked ```.md``` file
- Fixes https://github.com/owncloud/web/issues/5456
=> [tests-only] @disablePreviews added in markdown feature

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md, tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md, tests/acceptance/features/webUIPreview/imageMediaViewer.feature
Description here: [5324](https://github.com/owncloud/web/issues/5324)
A test is written that demonstrates the error. The test will work when the bug is fixed
=> [full-ci] [tests-only] Open jpeg file in "shared with me page" or "shared with other"

packages/web-app-files/src/components/SideBar/Links/FileLinks.vue, packages/web-app-files/src/components/SideBar/Links/PrivateLinkItem.vue, packages/web-app-files/tests/unit/components/SideBar/Links/CopyToClipboardButton.spec.js, packages/web-app-files/tests/unit/components/SideBar/Links/FileLinks.spec.js, packages/web-app-files/tests/unit/components/SideBar/Links/PrivateLinkItem.spec.js
unit tests added for:
- CopyToClipboardButton
- PrivateLinkItem
- FileLinks
- unit tests coverage
- 🤖
=> Added unit tests for sidebar link components

packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkInfo.vue, packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkInfo.spec.js
Added unit tests for `LinkInfo` component
- 🤖 
- 💇🏼‍♂️
=> [unit-tests] Added unit tests for link info component

changelog/unreleased/enhancement-update-ods, packages/web-runtime/package.json, yarn.lock
This PR updates ODS to version 9.1.0 which brings new icons and some fixes.
- Fixes https://github.com/owncloud/web/issues/5490
- Fixes https://github.com/owncloud/web/issues/5684
- Fixes https://github.com/owncloud/web/issues/5686
- CI
=> Update ODS to version 9.1.0

.drone.env
- Commit id bump
- https://github.com/owncloud/QA/issues/686
=> [tests-only] [full-ci] bump id for core and ocis in web

packages/web-app-files/tests/unit/mixins.spec.js, packages/web-app-files/tests/unit/mixins/actions/acceptShare.spec.js
added unit tests for
- function `checkIfElementEixists` in `packages/web-app-files/src/mixins.js`
- `acceptShare.js` mixin
- part of #5236
- 🤖
=> Added unit tests for files mixin

.drone.star, package.json, tests/acceptance/run.sh
- Move `test:acceptance:drone` command from package.json to tests/*/run.sh to avoid developer confusion
- Remove `develop*` and `release*` branch name rules in .drone.star to avoid duplicate CI runs on release branches
=> Move acceptance test cmd package.json => run_sh, delete unused branch name rules

.drone.env
Bump commit ids for testing.
Part of issue https://github.com/owncloud/QA/issues/686
CI
=> [full-ci] [tests-only] Bump commit ids

changelog/unreleased/enhancement-more-tooltips, package.json, packages/web-app-files/src/components/AppBar/ViewOptions.vue, packages/web-app-files/src/views/PublicFiles.vue
=> Add tooltips to expandSidebar & showViewOptions

tests/acceptance/stepDefinitions/previewContext.js
=> chore: remove console.log from test

tests/acceptance/helpers/sharingHelper.js, tests/acceptance/stepDefinitions/sharingContext.js, yarn.lock
Update the lockfile and fix the failing test due to the error in date calculation in acceptance tests
```
AssertionError [ERR_ASSERTION]: Expected: Expiration date field with Sept 1, 2021, but found Sep 1, 2021
1888 | + expected - actual
1889 |  
1890 | -Sep 1, 2021
1891 | +Sept 1, 2021
1892
```
- Fixes Failing CI
=> update lockfile and fix date calculation in acceptance tests

.drone.env
This PR updates the core and ocis commit ids.
- https://github.com/owncloud/QA/issues/686
- CI
=> [Tests-Only][full-ci]Update core and ocis commit id

packages/web-runtime/tests/unit/components/SkipTo.spec.js
Adds unit  tests for `SkipTo` component
=> [unit-tests-only] Add unit tests for SkipTo component

packages/web-app-files/src/components/Upload/ProgressBar.vue, packages/web-app-files/tests/unit/components/Upload/ProgressBar.spec.js
Adds unit  tests for `ProgressBar` component
=> [unit-tests] Add unit tests for ProgressBar component

packages/web-runtime/tests/unit/components/OcAppContent.spec.js
Adds unit  tests for `OcAppContent` component
=> [unit-tests-only] Add unit tests for OcAppContent component

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md, tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md, tests/acceptance/features/webUIWebdavLockProtection/delete.feature, tests/acceptance/features/webUIWebdavLockProtection/move.feature, tests/acceptance/features/webUIWebdavLockProtection/upload.feature, tests/acceptance/pageObjects/webPage.js
Fixed tests:
- webUIWebdavLockProtection/delete.feature:57
- webUIWebdavLockProtection/move.feature:105, 127
- webUIWebdavLockProtection/upload.feature:75
- Fixed issue https://github.com/owncloud/web/issues/5700
- Tagged issue https://github.com/owncloud/web/issues/5741
- Tagged issue https://github.com/owncloud/ocis/issues/1284
=> [tests-only][full-ci]fixed failed test

packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue, packages/web-app-files/tests/unit/components/SideBar/Versions/FileVersions.spec.js
With this PR
- added unit tests for `FileVersions` component
- #5234 
- 🤖
=> Added unit test for FileVersions component

packages/web-app-files/tests/__fixtures__/fileActions.js, packages/web-app-files/tests/unit/components/SideBar/Actions/FileActions.spec.js, packages/web-app-files/tests/unit/components/SideBar/Actions/__snapshots__/FileActions.spec.js.snap, tests/unit/__fixtures__/fileActions.js
Add unit test for file actions
- Related https://github.com/owncloud/web/issues/5234
=> [unit-tests-only] add unit tests for files actions sidebar

packages/web-runtime/src/components/ApplicationsMenu.vue, packages/web-runtime/tests/unit/components/ApplicationsMenu.spec.js, packages/web-runtime/tests/unit/components/__snapshots__/ApplicationsMenu.spec.js.snap
Adds unit  tests for `ApplicationsMenu` component
=> [unit-tests] Add unit tests for ApplicationsMenu component

packages/web-app-files/src/views/PrivateLink.vue, packages/web-app-files/tests/unit/views/PrivateLink.spec.js, packages/web-app-files/tests/unit/views/__snapshots__/PrivateLink.spec.js.snap, packages/web-app-files/tests/unit/views/views.setup.js
Added unit tests for `PrivateLink` view
- part of #5237
increase unit test coverage
=> [unit-tests-only] Add unit tests for PrivateLink view

packages/web-runtime/tests/unit/components/Avatar.spec.js
Adds unit  tests for `Avatar` component
=> [unit-tests-only] Add unit tests for Avatar component

packages/web-app-files/tests/unit/helpers/route.spec.js
- added todo unit tests for `route` helper
- Part of #5236
=> [unit-tests-only] Added unit tests todo items for route helper

packages/web-app-files/tests/unit/helpers/textUtils.spec.js
- added todo unit tests for `textUtils` helper from `packages/web-app-files/helper`
- Part of #5236
=> [unit-tests-only] Added unit tests todo items for textUtils helper

packages/web-app-files/src/components/SideBar/Details/FileDetailsMultiple.vue, packages/web-app-files/src/components/SideBar/FileInfo.vue, packages/web-app-files/src/components/SideBar/Links/FileLinks.vue, packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkInfo.vue, packages/web-app-files/src/components/SideBar/NoSelection.vue, packages/web-app-files/src/components/SideBar/SideBar.vue, packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
Updated heading structure in the sidebar, removed unused styles and changed some elements to use more semantically correct HTML
=> Update heading & DOM structure in sidebar

changelog/0.12.0_2020-07-10/files-list-outline, changelog/0.2.7_2020-01-14/2838, changelog/0.25.0_2020-11-16/openid-connect-dynamic-client-registration, changelog/0.28.0_2020-12-04/text-editor-file-path-label, changelog/0.4.0_2020-02-14/3032, changelog/0.6.0_2020-03-16/3100, changelog/3.0.0_2021-04-21/enhancement-use-ods-translations, changelog/3.3.0_2021-06-23/enhancement-visibility-observer, docs/custom-apps/_index.md, docs/deployments/oc10-app.md, docs/testing-manual.md, docs/testing.md
Fix some typos in changelogs.
I am mainly doing this to check that the CI logic in PR #5729 is working. The unit tests and acceptance tests should not be run, because this is a docs-only change.
N/A
=> Fix typos in changelogs

tests/acceptance/run.sh
Fix bash script for running the tests in CI
- Fixes issue with waiting for the server in CI.
the script doesnt works as expected currently and waits for 3 minutes regardless of weather the server has started or not.
=> [tests-only] fix bash script for running acceptance tests

docs/testing.md
This is a test pr from the sub-branch. This should be merged into https://github.com/owncloud/web/pull/5864 to see if the changes made in https://github.com/owncloud/web/pull/5864 work as expected.
=> [Tests-Only]Test for merge commit

docs/testing.md
This PR is a test pr to merge into `mergeCommitAdjustments` branch
=> [Tests-Only]Docs only changes to check for merge commit

packages/web-runtime/src/container/bootstrap.ts, packages/web-runtime/src/index.ts
Fixes the import of themes. Before this configuration was not being used anywhere, preventing themes from overwriting the default values.
=> Fix theme import

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md, tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
Fix frequently failing "unshare" test.
- Fixes https://github.com/owncloud/web/issues/5627
CI
=> [tests-only][full-ci] fixes frequently failing unshare test

packages/web-app-files/tests/unit/components/Search/List.spec.js, packages/web-app-files/tests/unit/components/Search/__snapshots__/List.spec.js.snap
Adds unit  tests for `List` component
=> [unit-tests-only] Add unit tests for List component

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, .github/issue_template.md
please have a look if i forget something.
- test case 1:
- test case 2:
- ...
=> update .github files to reflect current process

.drone.env
This PR bumps ocis commit ids to ensure that all the tests pass.
- Part of : https://github.com/owncloud/QA/issues/695
-  CI
=> [tests-only][full-ci]Bump commit id

packages/web-app-files/tests/integration/specs/peopleExpirationDate.spec.js
refactor date selection in integration tests for expiration dates in shares
- Fixes https://github.com/owncloud/web/issues/5964
To make the integration test code less repetitive and cleaner.
=> [Tests-Only] refactor date selection in integration tests for expiration dates in shares

.drone.env
bump ocis commit id
- test case 1:
- test case 2:
- ...
=> Bump commit ocis id

packages/web-app-files/src/helpers/store.ts, packages/web-app-files/tests/unit/helpers/store.spec.ts, packages/web-app-files/tests/unit/helpers/ui/filesList.spec.ts, packages/web-app-files/tests/unit/views/Personal.spec.js, packages/web-app-files/tests/unit/views/PublicFiles.spec.ts, packages/web-app-files/tests/unit/views/views.shared.ts
To get #6020 into the sprint reviews we merged it early with core tests only.
To have a clean unit-test coverage some tests where missing and are included in this late PR.
Changelog is already delivered as part of #6020
- Finalizes #6020
Test all needed cases and edge cases
- jest
=> late deliver of accentuate new files tests

changelog/unreleased/bugfix-capabilites-fetched-when-server-runs-in-subfolder, packages/web-runtime/src/store/user.js
don't overwrite the path to fetch the capabilities if a path is given in the `server` setting of the config e.g. `http://localhost/owncloud-core`
- Fixes #6010 
allow servers to be run in a subfolder
- run server in a folder and login to web
- :robot: will tests it for the case when the server runs in root
- @sakshamgurung please test this fix in your environment
=> fix url to fetch capabilities

tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
Fix for intermittent fail in share-expiration-date related tests.
- Fixes https://github.com/owncloud/web/issues/5992
=> [tests-only] [full-ci] fix for intermittent share-exp-date test fail

.drone.env
Latest ocis commit id bump [Nov 17 2021]
- PR for https://github.com/owncloud/QA/issues/699
=> [tests-only] [full-ci] latest ocis commit id bump

tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
This PR adds `@skipOnOC10` tag on a flaky batch-delete test. 
After analyzing the logs and behavior it seems to be caused by bug in `core` project which introduces deadlock as mentioned in this PR https://github.com/owncloud/core/issues/38221.  
- Discussion in https://github.com/owncloud/web/issues/5439
- Possible cause of flaky test https://github.com/owncloud/core/issues/38221
- Some failed drone logs https://drone.owncloud.com/owncloud/web/20377/44/13
=> [tests-only] [full-ci] adds `@skipOnOC10` tag

.drone.env
part of https://github.com/owncloud/QA/issues/699
=> [tests-only][full-ci] Bump ocis commit id for tests

tests/acceptance/nightwatch.conf.js
Fix the wait for condition timeout to reduce flaky tests in CI.
More information in https://github.com/owncloud/web/issues/6053
https://github.com/owncloud/web/issues/6053#issuecomment-978964065
- Fixes https://github.com/owncloud/web/issues/6053
=> [Tests-Only][full-ci] increase the wait for condition timeout to 10s for acceptance tests

.drone.star, docker-compose.yml, docs/testing-manual.md, docs/testing.md, tests/acceptance/features/webUIFilesList/fileList.feature, tests/acceptance/nightwatch.conf.js, tests/acceptance/stepDefinitions/middlewareContext.js
run the tests in CI using the [owncloud-test-middleware](https://github.com/owncloud/owncloud-test-middleware)
We have all the API steps moved to the middleware now so we can now use test middleware to run the tests on web. Currently the code for those steps are in 2 different place which is not really good for maintainability.
- Related https://github.com/owncloud/web/issues/5132
:robot:
=> [Tests-Only] run tests using middleware in CI

.drone.env
Latest ocis commit id bump.
- Part of https://github.com/owncloud/QA/issues/701
=> [tests-only][full-ci] latest ocis commit id bump

changelog/unreleased/enhancement-update-ods, packages/web-app-files/src/components/AppBar/AppBar.vue, packages/web-app-files/src/components/AppBar/ViewOptions.vue, packages/web-app-files/src/components/FilesList/ContextActions.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.vue, packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ContextActions.spec.js.snap, packages/web-runtime/package.json, packages/web-runtime/src/components/ApplicationsMenu.vue, packages/web-runtime/src/components/Notifications.vue, packages/web-runtime/src/components/UserMenu.vue, packages/web-runtime/tests/unit/components/__snapshots__/ApplicationsMenu.spec.js.snap, yarn.lock
See changelog item, needed for release
=> Bump ODS to v11.3.0

changelog/unreleased/bugfix-extension-casing, packages/web-app-files/src/helpers/resources.js, packages/web-app-files/src/mixins/actions/fetch.js, packages/web-app-files/src/mixins/fileActions.js, packages/web-app-files/src/store/actions.js, packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js, packages/web-app-media-viewer/src/App.vue
... but use toLowerCase() where needed.
I've removed `toLowerCase()` from `_getFileExtension()`, searched through the codebase for `extension` and added `toLowerCase()` where applicable.
It super easy to miss occurances, so I would really like if someone else could check this out and see if I missed something.
Should we do a regression test of some sort?
- Fixes #5339
- test case 1:
- test case 2:
- ...
=> Fix #5339: Do not lowercase resource extensions everywhere

.drone.star
Restructure CI pipelines to make the build times even among the pipelines.
- Fixes #6095 
CI
=> [CI] Restructure CI pipelines to make the CI runtime even

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md, tests/acceptance/features/webUIFilesCopy/copy.feature, tests/acceptance/stepDefinitions/webdavContext.js
Related https://github.com/owncloud/owncloud-test-middleware/issues/61 
Fix the status code check in fileShouldNotExist in acceptance tests
:robot:
=> [tests-only] fix fileNotExists function in acceptance tests

tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
PR https://github.com/owncloud/web/pull/6161 made some changes to fix the failing expiration date through the public link. This PR makes similar changes to fix failing tests in `user` and `groups`
- Fixes: https://github.com/owncloud/web/issues/6171
- locally
- CI
=> [tests-only][full-ci]Fix expiration date failing tests

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md, tests/acceptance/features/webUIRenameFiles/renameFiles.feature, tests/acceptance/pageObjects/FilesPageElement/contextMenu.js, tests/acceptance/pageObjects/FilesPageElement/filesList.js, tests/acceptance/stepDefinitions/filesContext.js
This PR adds fixes for unexpected behavior on test related to file rename 
Adds acceptance test coverage for: https://github.com/owncloud/web/issues/4893
Note: that issue has been fixed, and this test covers the now-good behavior.
- Locally
- CI
=> [tests-only][full-ci]Adds test related to renaming of file

tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature, tests/acceptance/features/webUISharingExternal/federationSharing.feature, tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature, tests/acceptance/features/webUISharingNotifications/notificationLink.feature, tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature, tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature, tests/acceptance/features/webUISharingNotificationsToRoot/notificationLink.feature, tests/acceptance/features/webUISharingNotificationsToRoot/shareWithGroups.feature, tests/acceptance/features/webUISharingNotificationsToRoot/shareWithUsers.feature, tests/acceptance/stepDefinitions/notificationsContext.js
This PR removes the tests present in middleware from notificationsContext.js and makes the necessary changes to test steps.
- part of: https://github.com/owncloud/web/issues/6111
- CI
- locally
- x] Tests
=> [tests-only][full-ci]Remove the tests present in middleware from notificationsContext.js

docs/deployments/oc10-app.md
Updated the proposed app title to make the switch between classic and new design more understandable.
=> updated app  switcher title translations

tests/e2e/cucumber/kindergarten.feature, tests/e2e/cucumber/shareFileJourney.feature, tests/e2e/cucumber/shareFolderJourney.feature, tests/e2e/cucumber/step_definitions/api.ts, tests/e2e/cucumber/step_definitions/app.files.ts, tests/e2e/cucumber/step_definitions/session.ts
This is some suggestions for re-wording steps in the smoke-test user journeys.
I also put some "Then" comments in the scenarios at places where it would be good to check that "the system" has done "something good" at that point. I can remove those, if you like, or we can leave them in for now as "ToDo hints".
These are "user journeys", so we do expect that the scenarios will be long and that there will be a mix of `When` and `Then` steps "back and forth" in a scenario. We want to do parts of the journey (`When` steps), and confirm "along the way" that the system state is as expected (`Then` steps)
CI
=> [tests-only] Reword smoke test journeys

packages/web-runtime/src/components/ApplicationsMenu.vue, packages/web-runtime/src/components/UserMenu.vue
Fixes broken focus management upon opening/closing ApplicationMenu and UserMenu, also deletes dead code in those components. Part of #6213
=> Remove uikit menu listeners

tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature, tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature, tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature, tests/acceptance/features/webUISharingPublicManagement/sharingPublicSession.feature, tests/acceptance/stepDefinitions/middlewareContext.js, tests/acceptance/stepDefinitions/publicLinkContext.js
This PR removes the tests step already present in middleware and reactors the existing test step to use middleware's.
- Part of: https://github.com/owncloud/web/issues/6111
- Locally
- CI
- x] Tests
=> [tests-only][full-ci]Remove and refactor tests present in middleware in publicLink context

tests/acceptance/report/index.js, tests/e2e/README.md
Make some minor typo fixes. I did this to demonstrate that CI is now OK.
CI
=> [tests-only] [full-ci] Fix typos in tests folders

tests/acceptance/features/webUIFiles/batchAction.feature, tests/acceptance/pageObjects/appBarActions.js, tests/acceptance/stepDefinitions/filesContext.js
This PR add tests related to batch action menu in these UI pages:
- Favorites
- Share with me 
- Share with others
- Deleted files
- Locally
- CI
=> [full-ci] [tests-only]Adds tests related to batch action menu

.drone.star
- check webci with owncloud-test-middleware v1.0.0
- https://github.com/owncloud/owncloud-test-middleware/issues/79
- :robot:
=> [tests-only][not-for-merge] test middleware v1.0.0

tests/acceptance/helpers/config.js
This PR removes the duplicate unnecessary function from `config.js` and deletes `path.js`
- Part of https://github.com/owncloud/web/issues/6111
- CI
=> [tests-only][full-ci]Refactor config.js to make use of middleware's functions

changelog/unreleased/enhancement-show-parent-folder
=> add changelog

packages/web-app-files/package.json, packages/web-app-files/src/components/FilesList/QuickActions.vue, yarn.lock
Supersedes #6197 by replacing the dependency alltogether
=> Replace filter-obj dep with lodash-es function

.drone.star, tests/acceptance/nightwatch.conf.js, tests/acceptance/setup.js, tests/acceptance/stepDefinitions/generalContext.js
This PR fixes the screenshot issue.
With this PR, screenshots will be reported if any webUI tests fail on retry.
=> [tests-only][full-ci] Fix screenshots

changelog/unreleased/change-use-remixicons, packages/web-app-files/src/components/ActionMenuItem.vue, packages/web-app-files/src/components/FilesList/QuickActions.vue, packages/web-app-files/src/components/SideBar/Details/FileDetails.vue, packages/web-app-files/src/components/SideBar/SideBar.vue, packages/web-app-files/src/fileSideBars.js, packages/web-app-files/src/helpers/statusIndicators.js, packages/web-app-files/src/index.js, packages/web-app-files/src/quickActions.js, packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ContextActions.spec.js.snap, packages/web-runtime/package.json, packages/web-runtime/src/pages/missingOrInvalidConfig.vue, yarn.lock
Decided that the "line" fill type looks more light.
=> Switch file action icons to fill-type "line"

tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
- Fixes https://github.com/owncloud/web/issues/6227
- test environment: CI
=> [tests-only][full-ci] Fix webUIPrivateLinks/accessingPrivateLinks.feature:17 test

.drone.star
latest `hugo-geekdoc`  package seems not be compatible with `owncloudci/hugo:0.71.0` anymore, therefore, bumping it
See https://drone.owncloud.com/owncloud/web/22119/3/3
- test case 1:
- test case 2:
- ...
=> Bump hugo docker to 0.89.4 in drone file

packages/web-app-files/tests/unit/views/Trashbin.spec.js, packages/web-app-files/tests/unit/views/__snapshots__/Trashbin.spec.js.snap, packages/web-app-files/tests/unit/views/views.setup.js
- added unit tests for trashbin view
- #5237 
- :robot:
=> [unit-tests-only] Added unit tests for trashbin view

tests/acceptance/helpers/webdavHelper.js
When downloading files, sometimes the file will be locked and the download request will return locked error response.
This PR adds wait and retry once ability for file download request.
Fixes https://github.com/owncloud/web/issues/3309
- local & CI
=> [tests-only][full-ci] Retry download if the resource is locked

tests/acceptance/helpers/webdavHelper.js
This PR removes functions present in middleware that are no longer needed in web
- part of: https://github.com/owncloud/web/issues/6111
- CI
=> [tests-only][full-ci]Remove function present in middleware from webDavHelper

packages/web-app-files/src/views/Personal.vue, packages/web-container/index.html.ejs, rollup.config.js
This is a fork of the #5986 PR, removing the last commit which might need more discussion.
@kulmann is it ok to merge this one right away?
=> Up performance simpler

changelog/unreleased/enhancement-add-spaces-actions, packages/web-app-files/src/mixins/spaces/actions/delete.js, packages/web-app-files/src/mixins/spaces/actions/rename.js, packages/web-app-files/src/views/spaces/Projects.vue, packages/web-app-files/tests/unit/mixins/spaces/delete.spec.js, packages/web-app-files/tests/unit/mixins/spaces/rename.spec.js, packages/web-app-files/tests/unit/views/spaces/Projects.spec.js, packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap, packages/web-client/src/index.ts
We added to following actions to the spaces overview:
* Create a new space
* Rename a space
* Delete a space
- part of https://github.com/owncloud/web/issues/6255
get spaces into web
=> Implement space actions

packages/web-app-files/src/views/PublicFiles.vue, packages/web-app-files/tests/unit/views/PublicFiles.spec.ts, packages/web-app-files/tests/unit/views/__snapshots__/PublicFiles.spec.ts.snap
- added unit tests for `PublicFiles` view
- #5237 
- :robot:
=> [unit-tests] added more unit tests for PublicFiles view

docs/development.md, docs/testing/testing.md
Please feel free to push to this branch and/or comment your personal notes
Makes code review easier and helps (new) contributors
=> [docs-only] Development guide && repo conventions

changelog/unreleased/enhancement-redesign-app-switcher, docs/theming/_index.md, packages/web-runtime/src/components/SidebarNav/SidebarNavItem.vue, packages/web-runtime/src/components/Topbar/ApplicationsMenu.vue, packages/web-runtime/src/components/Topbar/TopBar.vue, packages/web-runtime/src/components/Topbar/UserMenu.vue, packages/web-runtime/src/mixins/navigationMixin.js, packages/web-runtime/src/store/config.js, packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNavItem.spec.js.snap, packages/web-runtime/tests/unit/components/Topbar/TopBar.spec.js, packages/web-runtime/tests/unit/components/Topbar/__snapshots__/ApplicationsMenu.spec.js.snap, packages/web-runtime/tests/unit/components/Topbar/__snapshots__/TopBar.spec.js.snap, packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.js.snap, packages/web-runtime/themes/owncloud/theme.json
OcDrop specific tasks will be handled in another ticket/PR in the ODS
- Fixes #6102
=> Redesign AppSwitcher to visually highlight active route

tests/acceptance/features/webUISharingInternalUsersBlacklisted/shareWithUsers.feature, tests/acceptance/features/webUISharingInternalUsersToRootBlacklisted/shareWithUsers.feature, tests/acceptance/helpers/backendHelper.js, tests/acceptance/helpers/httpHelper.js, tests/acceptance/helpers/webdavHelper.js, tests/acceptance/stepDefinitions/sharingContext.js
- Part of: https://github.com/owncloud/web/issues/6111
- CI
=> [tests-only][full-ci] Refactor tests to use middleware's functions

tests/e2e/cucumber/step_definitions/app.files.ts, tests/e2e/support/page/files/allFiles.ts, tests/e2e/support/page/files/index.ts, tests/e2e/support/page/files/version.ts
This PR adds version page object for e2e tests
- Part of https://github.com/owncloud/web/issues/6344
There was no separate version page, this PR makes new version page which makes easier to organize and manage code.
- locally
- ci
=> [tests-only] Adds version page object for e2e tests

changelog/unreleased/enhancement-update-ods, packages/web-app-files/src/components/FilesList/ResourceTable.vue, packages/web-app-files/src/components/Search/Preview.vue, packages/web-app-files/tests/unit/components/Search/Preview.spec.js, packages/web-app-files/tests/unit/views/__snapshots__/SharedWithOthers.spec.js.snap, packages/web-app-files/tests/unit/views/__snapshots__/Trashbin.spec.js.snap, packages/web-runtime/package.json, tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js, yarn.lock
- test case 1:
- test case 2:
- ...
=> [full-ci] Pass folderLink and parentFolderLink to OCResource component

packages/web-app-files/src/components/FilesList/ContextActions.vue, packages/web-app-files/src/components/FilesList/ResourceTable.vue, packages/web-app-files/src/mixins/actions/fetch.js, packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ContextActions.spec.js.snap, packages/web-app-files/tests/unit/components/SideBar/FileInfo.spec.js, packages/web-app-files/tests/unit/components/SideBar/__snapshots__/FileInfo.spec.js.snap, packages/web-app-files/tests/unit/views/__snapshots__/SharedWithOthers.spec.js.snap, packages/web-pkg/package.json, packages/web-runtime/themes/owncloud/theme.json, yarn.lock
Needs https://github.com/owncloud/owncloud-design-system/releases/tag/v12.0.0-alpha18 (or perhaps an alpha19 *to be released*)
- Fixes #6212
=> Redesign contextmenu

tests/acceptance/helpers/userSettings.js
Remove duplicate functions to use middleware's
- part of: https://github.com/owncloud/web/issues/6111
- CI
=> [tests-only][full-ci] Remove duplicate functions to use middleware's

changelog/unreleased/bugfix-reactive-active-route, packages/web-app-files/src/components/AppBar/AppBar.vue, packages/web-app-files/src/router/index.ts, packages/web-app-files/src/router/utils.ts, packages/web-pkg/src/composables/router/useRouteName.ts
Active route helpers are not reactive and need to be updated on route change. This PR does that for the AppBar.
- Fixes https://github.com/owncloud/web/issues/6326
=> Use route helper with current route watcher

.gitignore
Was bothering me for quite a while now.
=> Add vscode folder to the gitignore list

packages/web-app-files/src/router/utils.ts, packages/web-pkg/src/composables/router/index.ts, packages/web-pkg/src/composables/router/useCurrentRoute.ts
the breadcrumb had stopped updating when switching routes
- Base https://github.com/owncloud/web/pull/6370/files
- Fixes https://github.com/owncloud/web/issues/6326
...
- unit tests
=> add reactive useCurrentRoute and fix routeWatcher

.drone.env
https://github.com/owncloud/QA/issues/721
CI
=> [tests-only][full-ci]Bump the commit id for tests

changelog/unreleased/enhancement-redesign-main-layout, packages/web-runtime/src/components/SidebarNav/SidebarNavItem.vue, packages/web-runtime/themes/owncloud/theme.json
- test case 1:
- test case 2:
- ...
=> fix sidebarnavitem text hover color

changelog/unreleased/enhancement-update-ods, packages/web-runtime/package.json, yarn.lock
=> Update ODS to v12.1.0

packages/web-app-draw-io/src/App.vue, packages/web-app-files/src/helpers/resource/common.ts, packages/web-app-files/src/helpers/resource/privatePreviewBlob.ts, packages/web-app-files/tests/unit/helpers/resource/common.spec.ts, packages/web-app-files/tests/unit/helpers/resource/privatePreviewBlob.spec.ts, packages/web-app-files/tests/unit/helpers/resource/publicPreviewUrl.spec.ts, packages/web-pkg/src/composables/appDefaults/useAppFileHandling.ts, packages/web-pkg/src/composables/appDefaults/useAppNavigation.ts, packages/web-runtime/package.json, packages/web-runtime/src/router/index.js, rollup.config.js, yarn.lock
I had to use file paths for importing `qs` because for some reason `import * from 'qs'` gave me `querystring`. I have no idea how to debug this and would love to hand this over to @fschade . Any ideas?
Get rid of query-string lib, as we require the more powerful qs library as a peer dependency of owncloud sdk already.
Simplify implementation of `convertRouteParamsToContextQuery` and `convertContextQueryToRouteParams`.
Makes it also easy to switch between [] and . syntax for nested query params
- test case 1:
- test case 2:
- ...
=> Support nested query params in router

tests/e2e/cucumber/shareFolderJourney.feature, tests/e2e/cucumber/step_definitions/app.files.ts, tests/e2e/filesForUpload/PARENT/simple.pdf, tests/e2e/support/page/files/version.ts
This PR adds steps for file old version restore in feature file and implementation of steps to restore the old version of file. Also, confirms whether file is restored or not.
- Part of https://github.com/owncloud/web/issues/6344
- locally
- ci
=> [tests-only] Added implementation for file old version restore, check file is restored

tests/e2e/cucumber/publicLinkToFolderJourney.feature, tests/e2e/cucumber/step_definitions/app.files.ts, tests/e2e/support/page/files/index.ts, tests/e2e/support/page/files/publicLink.ts, tests/e2e/support/utils/datePicker.ts
This PR adds when step implementation for creating public link to a folder with role, expiration_date, link_name, password
- Part of https://github.com/owncloud/web/issues/6389
This PR adds when steps implementation for creating public link as it was not implemented before.
- CI
- Locally
=> [tests-only] Add e2e test for creating public link

.drone.star
move usage of `bucket: owncloud` to `cache_public_s3` bucket
- Fixes https://github.com/owncloud/web/issues/6441
- :robot:
=> [tests-only] updated artifact upload location to `cache_public_s3`

docs/testing/testing.md
adds unit test spec file structure information
part of https://github.com/owncloud/web/issues/5744
=> [docs] add unit test spec file structure information

tests/acceptance/stepDefinitions/filesContext.js
- Closes (https://github.com/owncloud/web/issues/6488)
=> [tests-only] Refactor accessingPrivateLinks tests

.drone.env, packages/web-runtime/src/components/SidebarNav/SidebarNavItem.vue, tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md, tests/acceptance/features/webUILogin/oauthLogin.feature, tests/acceptance/features/webUIUserJourney/journey1.feature, tests/acceptance/nightwatch.conf.js, tests/acceptance/pageObjects/accountPage.js, tests/acceptance/pageObjects/favoritesPage.js, tests/acceptance/pageObjects/filesDropPage.js, tests/acceptance/pageObjects/loginErrorPage.js, tests/acceptance/pageObjects/loginPage.js, tests/acceptance/pageObjects/personalPage.js, tests/acceptance/pageObjects/publicLinkFilesPage.js, tests/acceptance/pageObjects/sharedViaLinkPage.js, tests/acceptance/pageObjects/sharedWithMePage.js, tests/acceptance/pageObjects/sharedWithOthersPage.js, tests/acceptance/pageObjects/trashbinPage.js, tests/acceptance/pageObjects/webPage.js, tests/e2e/support/page/files/allFiles.ts, tests/e2e/support/page/files/publicLink.ts, tests/e2e/support/page/files/sharedWithMe.ts, tests/e2e/support/page/runtime.ts
Bump oCIS commit id to latest for the tests
part of https://github.com/owncloud/QA/issues/726
- test environment: CI
=> [tests-only][full-ci] Bump oCIS commit id for the tests

packages/web-app-files/tests/unit/mixins/spaces/delete.spec.js, packages/web-app-files/tests/unit/mixins/spaces/disable.spec.js, packages/web-app-files/tests/unit/mixins/spaces/editDescription.spec.js, packages/web-app-files/tests/unit/mixins/spaces/editReadmeContent.spec.js, packages/web-app-files/tests/unit/mixins/spaces/rename.spec.js, packages/web-app-files/tests/unit/mixins/spaces/restore.spec.js, packages/web-app-files/tests/unit/mixins/spaces/setImage.spec.js, packages/web-app-files/tests/unit/mixins/spaces/setReadme.spec.js, packages/web-app-files/tests/unit/mixins/spaces/uploadImage.spec.js, packages/web-app-files/tests/unit/views/spaces/Project.spec.js, packages/web-app-files/tests/unit/views/spaces/__snapshots__/Project.spec.js.snap
* Suppress error logs in space tests that expect errors
* Adjust mocks for the space project view tests to fix warnings
=> [tests-only] Clean up space test warning- and error-logs

.drone.env, tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
Bump ocis
- Needs https://github.com/owncloud/ocis/pull/3228 
- Fixes https://github.com/owncloud/web/issues/6478
=> Bump ocis commit id

changelog/unreleased/enhancement-files-search-result-list, packages/web-app-draw-io/src/App.vue, packages/web-app-files/src/index.js, packages/web-app-files/src/router/common.ts, packages/web-app-files/src/router/router.ts, packages/web-app-files/src/search/sdk/index.ts, packages/web-app-files/src/views/SharedViaLink.vue, packages/web-app-files/src/views/Trashbin.vue, packages/web-app-files/tests/unit/search/sdk.spec.ts, tests/acceptance/features/webUIUpload/upload.feature
- Fixes #6496
- Fixes #6507
- Works towards #5644
=> [full-ci] Sidebar on search results

tests/acceptance/pageObjects/personalPage.js
Signed-off-by: jkoberg <jkoberg@owncloud.com>
Waits for the upload button to be not disabled before clicking it
- Fixes failing UI test that were clicking the button before it was enabled
- test case 1:
- test case 2:
- ...
=> Wait for upload button to be not disabled

changelog/unreleased/bugfix-no-auth-popup-on-password-protected-public-links, packages/web-runtime/package.json, yarn.lock
This updates owncloud-sdk to the latest 2.1.0-alpha.3 which includes a change to send the `X-Requested-With` header, needed to fix #5727.
- Fixes #5727
- test case 1:
- test case 2:
- ...
=> Fix #5727: Do not show auth popup for password protected links in oC 10

packages/web-app-files/src/views/SharedWithMe.vue
This enables thumbnails only for accepted shares.
- Fixes #5310
- test case 1:
- test case 2:
- ...
=> Fix #5310: Load thumbnails only for accepted shares

changelog/unreleased/bugfix-accepted-share-thumbnails
Follow-up on https://github.com/owncloud/web/pull/6534
=> Add changelog for 6534

changelog/unreleased/enhancement-contextmenu-hover-background, packages/web-app-files/src/components/FilesList/ContextActions.vue, packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ContextActions.spec.js.snap
Finalization of #6553
Closes #6560
=> Contextmenu hover background

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md, tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md, tests/acceptance/features/webUIFilesDetails/fileDetails.feature, tests/acceptance/features/webUIUpload/uploadEdgecases.feature, tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js, tests/acceptance/pageObjects/FilesPageElement/appSideBar.js, tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js, tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js, tests/acceptance/pageObjects/FilesPageElement/filesList.js, tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js, tests/acceptance/pageObjects/personalPage.js, tests/acceptance/pageObjects/webPage.js, tests/acceptance/stepDefinitions/filesContext.js, tests/acceptance/stepDefinitions/generalContext.js, tests/acceptance/stepDefinitions/sharingContext.js
suppress the NoSuchElementError when the element is expected not to be visible or if there is conditional actions
- Fixes (https://github.com/owncloud/web/issues/6463)
Clean log
=> [tests-only][full-ci] Suppress NoSuchElementError on isVisible whenever expected not to be visible

packages/web-container/manifest.json
Path to app.png needs to be relative...
=> Fix app.png path from absolute to relative

changelog/unreleased/enhancement-spaces-people-sharing, packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
=> Fix share panel loading for resources within a shared folder

packages/web-app-files/tests/unit/views/PrivateLink.spec.js, packages/web-app-files/tests/unit/views/spaces/Project.spec.js, packages/web-app-files/tests/unit/views/spaces/__snapshots__/Project.spec.js.snap, packages/web-app-files/tests/unit/views/views.setup.js
=> [tests-only] Clean up unit test logs

.drone.env
This PR bumps ocis commit id to latest
- Part of: https://github.com/owncloud/QA/issues/731
- CI
=> [full-ci][tests-only]Bump ocis commit id for tests

changelog/unreleased/enhancement-update-ods, packages/web-app-files/src/components/AppBar/AppBar.vue, packages/web-app-files/src/components/AppBar/CreateAndUpload.vue, packages/web-app-files/src/components/FilesList/ResourceTable.vue, packages/web-app-files/src/components/Search/Preview.vue, packages/web-app-files/src/index.js, packages/web-app-files/src/views/Trashbin.vue, packages/web-app-files/tests/unit/views/shares/__snapshots__/SharedWithOthers.spec.js.snap, packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap, packages/web-pkg/src/composables/capability/useCapability.ts, packages/web-runtime/package.json, packages/web-runtime/src/layouts/Application.vue, tests/acceptance/stepDefinitions/filesContext.js, yarn.lock
Also adds capability-driven "All files" vs "Personal" distinction in ResourceTable, Files app navItems, Breadcrumbs and Search results preview
=> [full-ci] Update ODS to v13.0.0-rc.6 & add differentiation between All files & Personal Space

.drone.env
This PR bumps oCIS commit id to match the latest
- part of (https://github.com/owncloud/QA/issues/735)
=> [full-ci] [tests-only] Bump ocis commit id

packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
=> Fix button alignments if 'Create folder' is displayed

changelog/5.2.0_2022-03-03/enhancement-add-quick-rename-button, packages/web-app-files/src/components/FilesList/ResourceTable.vue, packages/web-app-files/tests/unit/components/FilesList/ResourceTable.spec.js, packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.js.snap, packages/web-app-files/tests/unit/components/TrashBin.spec.js, packages/web-app-files/tests/unit/components/__snapshots__/TrashBin.spec.js.snap, packages/web-app-files/tests/unit/components/components.setup.js, packages/web-app-files/tests/unit/mixins/actions/emptyTrashBin.spec.js, packages/web-app-files/tests/unit/views/Favorites.spec.js, packages/web-app-files/tests/unit/views/LocationPicker.spec.js, packages/web-app-files/tests/unit/views/Personal.spec.js, packages/web-app-files/tests/unit/views/PublicFiles.spec.ts, packages/web-app-files/tests/unit/views/shares/SharedViaLink.spec.js, packages/web-app-files/tests/unit/views/shares/SharedWithMe.spec.js, packages/web-app-files/tests/unit/views/shares/SharedWithOthers.spec.js, packages/web-app-files/tests/unit/views/shares/__snapshots__/SharedWithOthers.spec.js.snap, packages/web-app-files/tests/unit/views/spaces/Project.spec.js, packages/web-app-files/tests/unit/views/spaces/Projects.spec.js, packages/web-app-files/tests/unit/views/spaces/Trashbin.spec.js, packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap, packages/web-app-files/tests/unit/views/views.setup.js, packages/web-app-files/tests/unit/views/views.shared.ts, packages/web-runtime/package.json, tests/unit/stubs/index.js, yarn.lock
See https://github.com/owncloud/web/issues/6626
- Fixes https://github.com/owncloud/web/issues/6626
=> Add quick rename

packages/web-app-user-management/src/components/Groups/CreateGroupModal.vue, packages/web-app-user-management/src/components/Users/CreateUserModal.vue
Set focus to the first input element in createUserModal and createGroupModal 
- test case 1:
- test case 2:
- ...
=> Set inital focus on CreateUserModal and CreateGroupModal

packages/web-app-files/src/components/FilesList/ContextActions.vue, packages/web-app-files/src/components/Search/List.vue, packages/web-app-files/src/components/TrashBin.vue, packages/web-app-files/src/composables/resourcesViewDefaults/useResourcesViewDefaults.ts, packages/web-app-files/src/helpers/resource/resource.ts, packages/web-app-files/src/views/Favorites.vue, packages/web-app-files/src/views/Personal.vue, packages/web-app-files/src/views/PublicFiles.vue, packages/web-app-files/src/views/shares/SharedViaLink.vue, packages/web-app-files/src/views/shares/SharedWithMe.vue, packages/web-app-files/src/views/shares/SharedWithOthers.vue, packages/web-app-files/src/views/spaces/Project.vue, packages/web-app-files/src/views/spaces/Projects.vue, packages/web-app-files/src/views/spaces/Trashbin.vue, packages/web-app-files/tests/unit/components/Search/List.spec.js, packages/web-app-files/tests/unit/views/Personal.spec.js, packages/web-app-files/tests/unit/views/shares/SharedWithOthers.spec.js
- test case 1:
- test case 2:
- ...
=> DRY selectedResources and isResourceInSelectedResources

changelog/unreleased/bugfix-accessible-breadcrumb-itemcount, changelog/unreleased/bugfix-hide-sidebartoggle-spaces-projects-page, changelog/unreleased/enhancement-permission-based-upload-create-buttons, changelog/unreleased/enhancement-spaces-name-breadcrumb, packages/web-app-files/src/App.vue, packages/web-app-files/src/components/AppBar/CreateAndUpload.vue, packages/web-app-files/src/components/AppBar/Upload/FileDrop.vue, packages/web-app-files/src/components/FilesList/QuickActions.vue, packages/web-app-files/src/mixins/accessibleBreadcrumb.js, packages/web-app-files/src/views/spaces/Projects.vue, packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap, packages/web-runtime/src/layouts/Application.vue, tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature, tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature, tests/acceptance/pageObjects/personalPage.js, tests/acceptance/stepDefinitions/filesContext.js
Code cleanup, changelog addition and a fixes issue
- Fixes #5618
- Fixes https://github.com/owncloud/web/issues/5591
- Fixes #6022
=> [full-ci] Small fixes

packages/web-app-user-management/src/components/Users/CreateUserModal.vue, packages/web-app-user-management/tests/unit/components/Users/CreateUserModal.spec.js
- test case 1:
- test case 2:
- ...
=> Add validation for username cannot contain whitespace and not start with numeric value

changelog/unreleased/bugfix-unsticky-appbar-position, changelog/unreleased/enhancement-update-ods, package.json, packages/web-app-files/src/components/AppBar/AppBar.vue, packages/web-runtime/package.json, packages/web-runtime/src/components/SidebarNav/SidebarNav.vue, packages/web-runtime/tests/unit/components/Topbar/__snapshots__/ApplicationsMenu.spec.js.snap, packages/web-runtime/themes/owncloud/theme.json, yarn.lock
- Fixes #6696
After this I'd suggest we tag a `web` release candidate for ownBrander staging & oCIS
=> Bump ODS to 13.1.0 rc.1, fix issue #6696

tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature, tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature, tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature, tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
- test case 1:
- test case 2:
- ...
=> [tests-only] shares folder only present if shares exist

packages/web-runtime/src/layouts/Application.vue
Enable TypeScript for the application layout (made me discover a little var reference issue 💪🏻 ) and revert a change from #6690 which added a dependency on files app into web-runtime which bit us in ownBrander.
We're just assuming this fixes the following issues in ownBrander 2.0 staging:
Not at all, I cannot reproduce this in local development builds.
=> Fix sidebar without files app

changelog/unreleased/enhancement-full-scree-apps, packages/web-app-external/src/App.vue, packages/web-app-external/tests/unit/__snapshots__/app.spec.js.snap
Transfering a CERN PR to be able to fix acceptance tests myself
=> Allow full screen external apps (i.e presentation mode) (#6688)

packages/web-app-files/tests/unit/components/AppBar/SharesNavigation.spec.js
define routes in the tests
get rid of log outputs like
```
console.warn
[vue-router] Route with name 'files-shares-with-me' does not exist
22 |   return comparatives
23 |     .map((comparative) => {
> 24 |       const { href: comparativeHref } = router.resolve({
|                                                ^
25 |         ...comparative
26 |         // ...(comparative.name && { name: resolveRouteName(comparative.name) })
27 |       })
at warn (node_modules/vue-router/dist/vue-router.common.js:18:47)
at Object.match (node_modules/vue-router/dist/vue-router.common.js:1594:9)
at VueRouter.match (node_modules/vue-router/dist/vue-router.common.js:2940:23)
at VueRouter.resolve (node_modules/vue-router/dist/vue-router.common.js:3094:20)
at map …
```
=> [tests-only] define routes in SharesNavigation unit tests

packages/web-app-files/tests/unit/views/Favorites.spec.js, packages/web-app-files/tests/unit/views/views.setup.js, packages/web-app-files/tests/unit/views/views.shared.ts
add routes to view unit tests
get rid of logs about missing routes
running unit tests
=> [tests-only] fix routes in view unit tests

package.json
- test case 1:
- test case 2:
- ...
=> Adjust excluded name from mediaviewer to preview for license checker

deployments/examples/ocis_web/.env, deployments/examples/ocis_web/docker-compose.yml
demo users are now opt in and therefore re-enabled in this PR
- test case 1:
- test case 2:
- ...
=> reintroduce demo users to the deployment example

tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature, tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature
These tests are failing nightly and sometimes in local PRs as well so they are skipped. 
See issue https://github.com/owncloud/web/issues/6419
https://github.com/owncloud/web/issues/6321#issuecomment-1057813530 for more context
- CI
-
=> [tests-only] Skip test related to sharing the shares folder

packages/web-app-user-management/src/components/Users/SideBar/DetailsPanel.vue, packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue, packages/web-app-user-management/src/components/Users/UsersList.vue, packages/web-app-user-management/src/views/Users.vue, packages/web-app-user-management/tests/unit/components/Users/SideBar/DetailsPanel.spec.js, packages/web-app-user-management/tests/unit/components/Users/SideBar/EditPanel.spec.js, packages/web-app-user-management/tests/unit/components/Users/UsersList.spec.js, packages/web-app-user-management/tests/unit/views/Users.spec.js
- test case 1:
- test case 2:
- ...
=> Purge userRoles lookup

changelog/unreleased/enhancement-introduce-web-app-user-management
- test case 1:
- test case 2:
- ...
=> Add changelog item for web-app-user-management

config/config.json.dist, config/config.json.sample-oc10, config/config.json.sample-ocis
Update config samples to reflect currently bundled apps.
was raised in rocketchat
=> Update config samples to reflect currently bundled apps

deployments/examples/ocis_web/config/ocis/proxy.yaml, deployments/examples/ocis_web/docker-compose.yml
fixes the latest oCIS with latest Web deployment example. One couldn't upload files anymore.
- test case 1:
- test case 2:
- ...
=> fix deployment example and update proxy config

packages/web-pocs/src/components/OcTable/OcTable.vue
fix: on table data change update groupedData copy
=> Cleanup & fixes

changelog/unreleased/bugfix-do-not-load-from-cache, packages/web-app-draw-io/src/App.vue, packages/web-pkg/src/composables/appDefaults/useAppFileHandling.ts, tests/drone/setup-server-and-app.sh
* Do not load files from cache
* changelog
This is a rebase of #6481 to see exactly what fails in current CI. We will look at the results in the morning.
CI
=> Do not load files from cache (#6447)

changelog/unreleased/enhancement-make-rename-resource-icon-always-visible, packages/web-app-files/src/components/FilesList/ResourceTable.vue
Always show rename resource icons
- Fixes https://github.com/owncloud/web/issues/6755
- test case 1:
- test case 2:
- ...
=> Always show rename resource icons + style adjustments

packages/web-runtime/package.json, yarn.lock
we had weird checksum issues with the commit hash. trying with an
archive now.
=> Switching over to a git tag of easygettext

changelog/unreleased/enhancement-uppy-service-event-bus, packages/web-runtime/src/services/uppyService.ts
Tiny issue that was introduced by https://github.com/owncloud/web/pull/6853
=> Fix issue where upload events couldn't unsubscribe from the bus

tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature, tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js, tests/acceptance/stepDefinitions/publicLinkContext.js
- https://github.com/owncloud/web/issues/6826
- Locally
- CI
=> [full-ci][tests-only]Refactor test related to public link edit

changelog/unreleased/enhancement-enable-search-all-files, packages/web-app-files/src/components/Search/Preview.vue
- test case 1:
- test case 2:
- ...
=> Fix previews in search not working 

packages/web-app-files/tests/unit/composables/upload/spec/index.ts, packages/web-app-files/tests/unit/composables/upload/useUploadHelpers.spec.ts, packages/web-runtime/src/composables/upload/useUpload.ts, packages/web-runtime/tests/unit/components/UploadInfo.spec.js, packages/web-runtime/tests/unit/components/__snapshots__/UploadInfo.spec.js.snap, packages/web-runtime/tests/unit/composables/upload/spec/index.ts, packages/web-runtime/tests/unit/composables/upload/useUpload.spec.ts
Continuation of https://github.com/owncloud/web/pull/6202
=> [tests-only] Add unit tests for the uppy implementation

docs/getting-started.md
Adds documentation for new behavior added in #6820
=> Add docs for sidebar.shares.showAllOnLoad configuration option

changelog/unreleased/bugfix-space-image-not-shown-if-name-contains-blanks, packages/web-app-files/src/helpers/resources.ts
Bugfix: Space image not shown if file name contains blanks
- Fixes https://github.com/owncloud/web/issues/6874
- test case 1:
- test case 2:
- ...
=> Fix space image with blank space not shown

packages/web-app-files/src/components/SideBar/Shares/Links/CreateForm.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/FileLinks.spec.js
Cleanup `FileLinks` component unit test run warnings
- Fixes https://github.com/owncloud/web/issues/6337
- :robot:
=> cleanup FileLinks component unit test run warnings

changelog/unreleased/enhancement-redesign-link-sharing, config/config.json.sample-ocis, dev/docker/ocis.entrypoint.sh, dev/docker/ocis.web.config.json, packages/web-app-files/src/components/SideBar/Shares/Links/NameAndCopy.vue
See commits :neckbeard: 
Fixes #6872
=> Fix docker setup, remove accounts.js from configs and add tooltips for links in sidebar

changelog/unreleased/enhancement-enable-search-all-files, packages/web-app-files/src/search/filter/preview.ts, packages/web-app-files/src/search/sdk/index.ts, packages/web-app-files/src/search/sdk/preview.ts
- test case 1:
- test case 2:
- ...
=> Hide hidden files in search, if setting "Show hidden files" is not active 

changelog/unreleased/enhancement-enable-search-all-files, packages/web-app-files/src/components/Search/Preview.vue, packages/web-app-files/tests/unit/components/Search/Preview.spec.js
- test case 1:
- test case 2:
- ...
=> Search: check if configuration allows previews

.drone.star, package.json, packages/web-app-files/src/store/actions.js, packages/web-app-files/src/store/getters.js, packages/web-app-files/src/store/mutations.js, packages/web-app-files/src/store/state.js, packages/web-runtime/src/plugins/web.js
Not much to see here, feels good nonetheless
=> Move unit test coverage calculation to CI && Remove dead code in files store

packages/web-app-files/src/components/AppBar/CreateSpace.vue, packages/web-app-files/src/components/Spaces/QuotaModal.vue, packages/web-app-files/src/mixins/deleteResources.js, packages/web-runtime/src/components/MessageBar.vue, packages/web-runtime/src/components/Topbar/Notifications.vue
- Fixes https://github.com/owncloud/web/issues/3984
- test case 1:
- test case 2:
- ...
=> Remove $gettext func from MessageBar.vue

packages/web-app-files/src/index.js
No more beta for spaces 🥳 
- Fixes https://github.com/owncloud/web/issues/6900
=> Remove the beta-label from the spaces nav-item

packages/web-app-files/src/index.js
- Fixes https://github.com/owncloud/web/issues/2459
- test case 1:
- test case 2:
- ...
=> Disable sharing nav entry if sharing api is disabled

packages/web-app-files/src/index.js
- test case 1:
- test case 2:
- ...
=> Don't load spaces on startup if not  in capabilties

packages/web-app-files/tests/unit/components/FilesList/ResourceTable.spec.js, packages/web-app-files/tests/unit/components/components.setup.js, packages/web-app-files/tests/unit/mixins/actions/rename.spec.js
=> [tests-only] Clean up unit test error logs

tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js, tests/acceptance/stepDefinitions/publicLinkContext.js
This PR 
- removes the steps that are no longer in use
- follow-up of: https://github.com/owncloud/web/pull/6869
- CI
=> [tests-only][full-ci]Refactor tests related to public link

tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
see if #1502 is still an issue and if not enable those tests
- Fixes #1502
- tried manually
- CI (10 runs in https://drone.owncloud.com/owncloud/web/25453)
=> [tests-only] unskip tests to batch delete files from trashbin

changelog/unreleased/bugfix-share-hint-with-disabled-federation, packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.spec.js
- Fixes https://github.com/owncloud/web/issues/5261
=> Remove federated sharing hint if federation is disabled

changelog/unreleased/bugfix-remove-links-from-share-notifications, packages/web-runtime/src/components/Topbar/Notifications.vue
As described in https://github.com/owncloud/web/issues/5227#issuecomment-1061683197.
- Fixes https://github.com/owncloud/web/issues/5227
=> Remove private links from share notifications

config/config.json.dist, config/config.json.sample-oc10, config/config.json.sample-ocis
=> Remove invalid commas at the end of the config dist files

changelog/unreleased/enhancement-update-sdk
- test case 1:
- test case 2:
- ...
=> Update update-sdk changelog item

tests/e2e/support/objects/app-files/page/public.ts, tests/e2e/support/objects/app-files/page/shares/withMe.ts, tests/e2e/support/objects/app-files/page/spaces/personal.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/utils.ts, tests/e2e/support/objects/app-files/share/actions.ts
This PR 
-  moves the selector name to constants
- https://github.com/owncloud/web/issues/6908
- CI
=> [tests-only] Refactored e2e test to move selector name to constant [Part 1]

packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/AutocompleteItem.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/RecipientContainer.vue
Truncates the user suggestions
Fix overflow of too long user name / display name
- Fixes https://github.com/owncloud/web/issues/6004
- test case 1:
- test case 2:
- ...
=> Fix "share with people" overflow

changelog/unreleased/bugfix-link-permission-enforced-password
See title or https://github.com/owncloud/web/pull/6989#pullrequestreview-975784375
=> Add changelog for #6989

changelog/unreleased/bugfix-share-with-people-overflow-on-long-names
- test case 1:
- test case 2:
- ...
=> Add changelog item for issues/6004

changelog/unreleased/bugfix-spaces-breadcrumbs
- test case 1:
- test case 2:
- ...
=> Add changelog item for issues/6866

deployments/examples/ocis_web/config/ocis/proxy.yaml
fixes deployment example by fixing ocs proxy route
- `docker-composee up -d`
=> fix deployment example by fixing ocs proxy route

changelog/unreleased/enhancement-new-webdav-endpoints-for-uploads, packages/web-app-files/src/components/AppBar/CreateAndUpload.vue, packages/web-app-files/src/composables/upload/useUploadHelpers.ts
This is basically another continuation of the [sharing jail PR](https://github.com/owncloud/web/pull/6593).
- Fixes https://github.com/owncloud/web/issues/6970
=> Use new WebDAV endpoints for uploads when spaces are enabled

.drone.star
run CI with the latest version of oC10, so that we don't have to remember to change it here when a new version of oc10 is released as requested in https://github.com/owncloud/web/pull/7020#pullrequestreview-981285858
please note that this means that CI in web can break any time when a new version of oC10 is released as happened before https://github.com/owncloud/web/pull/7016
=> [full-ci][tests-only] run tests with latest oC10

README.md
no URL was given and so the link was pointing to a 404 page https://github.com/owncloud/web/blob/master
=> [docs-only][skip-ci] fix URL to the docs folder

.drone.env
Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>
Update ocis commit id to the latest up to `2022-05-25`
- https://github.com/owncloud/QA/issues/742
- :robot:
=> [tests-only][full-ci] Bump ocis commit id to the latest upto 2022-05-25

.drone.env
- Part of: https://github.com/owncloud/QA/issues/742
- test case 1:
- test case 2:
- ...
=> [full-ci][tests-only] Bump ocis commit id for tests

changelog/unreleased/enhancement-copy-move-conflict-dialog, packages/web-app-files/src/helpers/resource/copyMove.ts, packages/web-app-files/tests/unit/helpers/resource/copyMove.spec.ts
Prevent recursive copy/move
- Fixes https://github.com/owncloud/web/issues/7148
- unit test
=> Prevent recursive copy in copy/move helper

deployments/examples/ocis_web/docker-compose.yml
updates both Collabora and OnlyOffice in the WOPI deployment example to have up to date versions. This needed config changes on both document servers.   
- Same as owncloud/ocis#3994
- test case 1:
- test case 2:
- ...
=> update collabora and onlyoffice in the deployment example

tests/e2e/cucumber/environment/index.ts, tests/e2e/cucumber/features/integrations/spaces/participantManagement.ocis.feature, tests/e2e/cucumber/steps/app-files/page/public.ts, tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts, tests/e2e/cucumber/steps/app-files/resource.ts, tests/e2e/support/objects/app-files/page/public.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts, tests/e2e/support/objects/app-files/share/actions.ts, tests/e2e/support/objects/app-files/spaces/actions.ts, tests/e2e/support/objects/app-files/spaces/index.ts
- part of: https://github.com/owncloud/web/issues/7035
- locally
- CI
=> [tests-only] Add e2e tests for participant management(spaces)

tests/e2e/cucumber/features/integrations/spaces/project.ocis.feature, tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts, tests/e2e/support/objects/app-files/spaces/actions.ts, tests/e2e/support/objects/app-files/spaces/index.ts
- Created e2e test for setting space image
=> E2e test.  set space image

.drone.star, tests/acceptance/nightwatch.conf.js, tests/acceptance/setup.js
Can't remember a browser-specific issue that could've been detected in CI (except for the fact that there is no efforts or discussions to going back to using SauceLabs AFAIK)
- Fixes #7186
=> Remove sauceLabs from acceptance tests

changelog/unreleased/enhancement-pdf-viewer-app-toolbar, packages/web-app-pdf-viewer/src/App.vue
- Fixes https://github.com/owncloud/web/issues/7205
- test case 1:
- test case 2:
- ...
=> Use oc-resource instead of plain text

changelog/unreleased/bugfix-error-when-pasting-empty-clipboard, packages/web-app-files/src/store/actions.js
- Fixes https://github.com/owncloud/web/issues/7146
- test case 1:
- test case 2:
- ...
=> Fix console error when pasting with empty clipboard

changelog/unreleased/bugfix-hide-empty-trash-bin-modal-on-error, packages/web-app-files/src/mixins/actions/emptyTrashBin.js
- Fixes https://github.com/owncloud/web/issues/7129
- test case 1:
- test case 2:
- ...
=> Hide empty trash bin modal on success and on error

packages/web-app-files/src/store/actions.js
- test case 1:
- test case 2:
- ...
=> emit spaceRef

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md, tests/acceptance/features/webUIFilesActionMenu/versions.feature
This PR skips the tests related to issue https://github.com/owncloud/ocis/issues/1310 in ocis and removes them from expected to fail as they aren't relevant for OCIS. The tests pass for `OC10`
- https://github.com/owncloud/ocis/issues/1310
- Locally
- CI
=> [tests-only][full-ci]Skip tests related to issue-ocis-1310 on ocis

tests/e2e/support/objects/app-files/spaces/actions.ts
This PR refactors:
```console
await page.locator(editSpacesDescription).click()
await waitForUpdate()
```
to
```console
await Promise.all([waitForUpdate(), page.locator(editSpacesDescription).click()])
```
- Part of https://github.com/owncloud/web/issues/7244
- Related to https://github.com/owncloud/web/issues/7244#issuecomment-1179929816
- Locally
- CI
=> [full-ci] [tests-only] Refactored promise on edit description of space

tests/e2e/support/objects/app-files/resource/actions.ts
This PR refactors:
```console
await page.locator(actionConfirmationButton).click()
await page.waitForResponse(
(resp) => resp.url().includes(encodeURIComponent(resourceName)) && resp.status() === 204
)
``` 
to 
```console
await Promise.all([
page.waitForResponse(
(resp) =>
resp.url().includes(encodeURIComponent(resourceName)) &&
resp.status() === 204 &&
resp.request().method() === 'DELETE'
),
page.locator(actionConfirmationButton).click()
])
```
- Part of https://github.com/owncloud/web/issues/7276
Deleting resources step is failing sometimes on CI and most of the time locally. This PR might fix that issue.
- CI
- Locally
=> [full-ci] [tests-only] Refactored promise on deleting resource

.drone.env
This PR bumps OCIS commit id for tests
- Part of : https://github.com/owncloud/QA/issues/753
- CI
=> [tests-only][full-ci]Bump OCIS commit id for tests

changelog/unreleased/bugfix-shared-with-others-and-via-link-resource-links, packages/web-app-files/src/components/FilesList/ResourceTable.vue
Bugfix: "Shared with others" and "Shared via Link" page resource links not working
We've fixed a bug where resource links in "Shared with others" and "Shared via Link" page stopped working.
- Fixes https://github.com/owncloud/web/issues/7303
- test case 1:
- test case 2:
- ...
=> Set storageId to spaceId

changelog/unreleased/bugfix-access-details-shown-for-all-space-members, changelog/unreleased/enhancement-redesign-shared-with-list, packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.js, packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.js.snap
- Fixes https://github.com/owncloud/web/issues/7305
- test case 1:
- test case 2:
- ...
=> Use uuid instead of space.id

changelog/unreleased/bugfix-context-menu-misplaced-triggered-by-keyboard-navigation, packages/web-app-files/src/components/FilesList/ResourceTable.vue
- Fixes https://github.com/owncloud/web/issues/7302
- test case 1:
- test case 2:
- ...
=> Fix rightclick-context menu appears always next to 3-dots-quickaction

changelog/unreleased/enhancement-ocis-resharing, packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue, packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
Followup for https://github.com/owncloud/web/pull/7086.
- Fixes https://github.com/owncloud/web/issues/7311
=> Prevent share permissions from being exceeded

changelog/unreleased/bugfix-files-pagination-scroll-to-top, packages/web-app-files/src/components/FilesList/Pagination.vue
- Fixes https://github.com/owncloud/web/issues/7138
- test case 1:
- test case 2:
- ...
=> Fixes: Pagination - New pages should start at the top

changelog/unreleased/enhancement-ocis-resharing, packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue, packages/web-app-files/src/components/SideBar/Shares/FileShares.vue, packages/web-app-files/src/components/SideBar/SideBar.vue, packages/web-app-files/src/services/folder/spaces/loaderShare.ts
* Fixed sidebar (& shares) not loading in sharing jail root folders (context menu via breadcrumb)
* Fixed sharesTree console errors in share jail
- Fixes https://github.com/owncloud/web/issues/7223
=> Resharing followup

changelog/unreleased/bugfix-left-sidebar-active-item-wrong-cursor, packages/web-runtime/src/components/SidebarNav/SidebarNavItem.vue
- Fixes https://github.com/owncloud/web/issues/7343
- test case 1:
- test case 2:
- ...
=> Fix Left Sidebar - Active navitem pretends to be not clickable

packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue, packages/web-app-files/src/components/SideBar/Shares/FileShares.vue, packages/web-app-files/src/components/SideBar/Shares/SharesPanel.vue, packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue, packages/web-app-files/src/helpers/statusIndicators.js, packages/web-app-files/src/mixins/actions/createQuicklink.js, packages/web-app-files/src/mixins/actions/showShares.js, packages/web-app-files/src/quickActions.js, packages/web-app-files/tests/unit/components/SideBar/Shares/FileLinks.spec.js, packages/web-app-files/tests/unit/components/SideBar/Shares/SharesPanel.spec.js, packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.js.snap, packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/SpaceMembers.spec.js.snap, packages/web-pkg/src/components/sidebar/SideBar.vue
- Fixes https://github.com/owncloud/web/issues/6968
- test case 1:
- test case 2:
- ...
=> Fix: click on share-indicator in files list should scroll

changelog/unreleased/bugfix-spaces-missing-quick-actions, packages/web-app-files/src/views/spaces/Project.vue
- Fixes https://github.com/owncloud/web/issues/7339
- test case 1:
- test case 2:
- ...
=> Fix: Space-  Missing Quickactions

changelog/unreleased/enhancement-right-sidebar-fixed-width, packages/web-app-files/src/components/FilesList/ResourceTable.vue
Regression due to https://github.com/owncloud/web/pull/7371
=> Fix action menu layout while sidebar being opened

changelog/unreleased/bugfix-context-menu-misplaced-triggered-by-keyboard-navigation, packages/web-app-files/src/components/FilesList/ResourceTable.vue
Regression due to https://github.com/owncloud/web/pull/7314
=> Fix action menu placement when opened via context menu

tests/acceptance/features/webUIFilesCopy/copy.feature, tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature
PR https://github.com/owncloud/web/pull/7413 bumps middleware version but it didn't run full-ci. So this is the test PR to run full-ci and see if the test skipped in PR https://github.com/owncloud/web/pull/7323 pass or not. https://github.com/owncloud/web/blob/b7da812dc0ac484a02a9c2a10e43026f8fb55408/tests/acceptance/features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature#L80 passes
Some tests were failing because the users weren't being cleaned up properly
- Follow up of:
-  https://github.com/owncloud/web/pull/7413
- https://github.com/owncloud/web/pull/7323
- https://github.com/owncloud/owncloud-test-middleware/issues/120
- local
- CI
=> [tests-only][full-ci] Unskip some passing tests

changelog/unreleased/bugfix-quicklinks-not-shown, packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
- Fixes https://github.com/owncloud/web/issues/7406
- test case 1:
- test case 2:
- ...
=> Fix quick link not shown if available

packages/web-app-files/src/components/AppBar/CreateAndUpload.vue, packages/web-app-files/src/mixins/actions/restore.ts, packages/web-app-files/src/mixins/deleteResources.js
- test case 1:
- test case 2:
- ...
=> Fix wrong mutations/getters

changelog/unreleased/bugfix-user-management-app-close-sidebar-throws-error, packages/web-app-files/src/App.vue, packages/web-app-user-management/src/components/AppTemplate.vue, packages/web-app-user-management/src/components/Groups/GroupsList.vue, packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue, packages/web-app-user-management/src/components/Users/UsersList.vue, packages/web-app-user-management/src/views/Groups.vue, packages/web-app-user-management/src/views/Users.vue, packages/web-app-user-management/tests/unit/views/Groups.spec.js, packages/web-app-user-management/tests/unit/views/Users.spec.js, packages/web-pkg/src/components/QuotaSelect.vue, packages/web-pkg/src/components/sidebar/SideBar.vue, packages/web-pkg/src/components/sidebar/types.ts, packages/web-pkg/tests/unit/components/QuotaSelect.spec.js, tests/acceptance/pageObjects/FilesPageElement/appSideBar.js, tests/e2e/support/objects/app-files/utils/sidebar.ts
- Added AppTemplate.vue component as design template
- General refactoring (less code, bugfixing)
- Add maxQuota property to QuotaSelect.vue
- test case 1:
- test case 2:
- ...
=> [full-ci] Improve user-management-app and add max-quota to QuotaSelect.vue component

changelog/unreleased/bugfix-file-size-not-updated-while-restoring-file-version, packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
- Fixes https://github.com/owncloud/web/issues/7438
- test case 1:
- test case 2:
- ...
=> Call update resource on file version restore

changelog/unreleased/bugfix-drag-drop-no-selection, packages/web-app-files/src/components/FilesList/ResourceTable.vue
See https://github.com/owncloud/web/issues/7447
- Fixes https://github.com/owncloud/web/issues/7447
=> Bugfix: Dragging a file causes no selection

packages/web-app-files/src/views/Personal.vue
- Fixes https://github.com/owncloud/web/issues/7222
- test case 1:
- test case 2:
- ...
=> Avoid NavigationDuplicated error in console

changelog/unreleased/enhancement-users-table-small-screens, packages/web-app-user-management/src/components/Users/UsersList.vue, packages/web-app-user-management/src/index.js, packages/web-app-user-management/src/views/Users.vue
We've improved the layout of the users table on small screens.
- Fixes https://github.com/owncloud/web/issues/7439
=> Improve users table layout on small screens

.drone.star
In this PR, short-term artifacts are cached into the cache bucket and more than 1-day old cached artifacts are purged after the build is completed with status success or failure.
- Part of https://github.com/owncloud/QA/issues/757
- CI
=> [full-ci] [tests-only] Short term cache stored in cache bucket

packages/web-runtime/src/components/Topbar/UserMenu.vue
Before:
After:
- test case 1:
- test case 2:
- ...
=> User menu too long display name and email are overflowing

packages/web-app-files/src/components/Spaces/QuotaModal.vue, packages/web-app-files/tests/unit/components/Search/List.spec.js, packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js, packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue, packages/web-app-user-management/tests/unit/components/Users/SideBar/EditPanel.spec.js, packages/web-runtime/src/index.ts, packages/web-runtime/src/store/spaces.ts
- test case 1:
- test case 2:
- ...
=> Fetch and show quota limitations

changelog/unreleased/enhancemnet-user-management-edit-quota, packages/web-pkg/src/components/QuotaSelect.vue
- test case 1:
- test case 2:
- ...
=> Fix console error, while enter 0

.drone.star
Some drone pipeline doesn't contain **WEB_UI_CONFIG** env variable. 
- [Fix WEB_UI_CONFIG message emitted in CI](https://github.com/owncloud/web/issues/7452)
=> [Full-ci] [tests-only] Add config file path in drone pipeline

.drone.env
Bump commit id of ocis to latest.
- Part of https://github.com/owncloud/QA/issues/763
- CI
=> [full-ci] [tests-only] Bump ocis commit id to latest

changelog/unreleased/enhancement-update-ods, packages/web-runtime/package.json, yarn.lock
Updates the owncloud-design-system to v14.0.0-alpha.17.
=> chore: update ODS to v14.0.0-alpha.17

packages/web-app-user-management/src/components/Groups/SideBar/EditPanel.vue, packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue, packages/web-app-user-management/src/components/Users/SideBar/GroupAssignmentsPanel.vue, packages/web-pkg/src/components/sideBar/CompareSaveDialog.vue
- Fixes https://github.com/owncloud/web/issues/7585
- test case 1:
- test case 2:
- ...
=> Change save dialog placement

changelog/unreleased/bugfix-add-language-param-open-external-app, packages/web-app-external/src/App.vue, packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue, packages/web-app-user-management/src/components/Users/SideBar/GroupAssignmentsPanel.vue
See https://github.com/owncloud/web/issues/7419
- Fixes https://github.com/owncloud/web/issues/7419
=> Add language param

deployments/examples/ocis_web/config/ocis/proxy.yaml
fix the deployment example by updating the proxy routes configuration
- Fixes broken https://ocis.ocis-web.latest.owncloud.works
have a working deployment example with latest web
- docker-compose up -d locally
=> update proxy config of the deployment example

packages/web-app-files/src/components/SideBar/TagsPanel.vue
Redo of https://github.com/owncloud/web/pull/7614
- test case 1:
- test case 2:
- ...
=> Change style of TagsPanel compare-save-dialog

.drone.env, tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
This PR bumps the ocis commit id for tests
- Part of: https://github.com/owncloud/QA/issues/766
- CI
=> [tests-only][full-ci]Bump commit id for tests

packages/web-app-search/src/portals/SearchBar.vue
- test case 1:
- test case 2:
- ...
=> Fix search reacts on enter event if not active

packages/web-app-pdf-viewer/src/App.vue, packages/web-app-preview/src/App.vue, packages/web-app-search/src/portals/SearchBar.vue, packages/web-app-text-editor/src/App.vue
- Fixes https://github.com/owncloud/web/issues/7591
- test case 1:
- test case 2:
- ...
=> Enable keyboard nav

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
This PR check the expected to failure file and make sure there is not any tests that is not mentioned to an issue.
Also cleans up some description and lines to make maintain format consistency.
https://github.com/owncloud/QA/issues/716
=> [tests-only][full-ci]Check for issue not mentioned to a test in expected to failure

tests/e2e/cucumber/features/integrations/share.ocis.feature, tests/e2e/cucumber/steps/app-files/resource.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts
I have added:
- creating txt md drawio file
- editing txt and md files
- opening a pdf file and an image in a viewer
=> [tests-only]Share file story

.drone.star
While I was checking the `.drone.star` changes of PR #7642 I made these very minor changes to:
- keep list of test suite names in alphabetical order (made it easier for me when checking that they are all there)
- fixed a couple of minor typos that do not effect functionality
CI
=> [tests-only] [full-ci] Minor changes to .drone.star

package.json, packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js, packages/web-app-search/src/portals/SearchBar.vue, packages/web-app-search/tests/unit/portals/SearchBar.spec.ts, packages/web-runtime/tests/unit/pages/account.spec.js, yarn.lock
- test case 1:
- test case 2:
- ...
=> Refactor search tests

tests/e2e/cucumber/features/integrations/search.feature
Some tests steps were commented due to this issue https://github.com/owncloud/web/issues/7629 , but seems like it's fixed now, so enabling them again
- Part of: https://github.com/owncloud/web/issues/7395
- locally
- CI
=> [tests-only] Enable the e2e test steps related to issue-7629

.vscode/extensions.json, .vscode/settings.json
- test case 1:
- test case 2:
- ...
=> Provide default settings for vscode

packages/web-app-search/src/views/List.vue
- test case 1:
- test case 2:
- ...
=> Fix multiple call search

changelog/unreleased/bugfix-align-more-tags-counter, packages/web-app-files/src/components/FilesList/ResourceTable.vue
See issue/changelog
- Fixes #7708
=> Fix #7708, align more tags counter

.eslintrc.json, .vscode/extensions.json, .vscode/settings.json
Add more default settings for vscode:
- use prettier for json formatting
- recommend volar as vue extension
- use eslint to format vue files (specifically not volar)
- test case 1:
- test case 2:
- ...
=> [CI SKIP] Add more default settings for VS Code

tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
From investigation, it was found that sometimes the `collaboratorAccessDetailsDrop` doesn't resolve up to the time limit 300ms used by this
``` 
await this.waitForElementNotPresent(
'@collaboratorAccessDetailsDrop',
this.api.globals.waitForNegativeConditionTimeout
)
```
that result `.share-access-details-drop` element to be visible. So replace  waitForNegativeConditionTimeout with waitForConditionTimeout.
For detail visit https://github.com/owncloud/web/pull/7671#discussion_r993341501
- Fixes [webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature:51 in OC10 failed in nightly and needs further investigation](https://github.com/owncloud/web/issues/7666)
- locally.
=> [full-ci][tests-only] Wait more for element collaboratorAccessDetailsDrop not to be present

packages/web-client/tests/unit/helpers/space/functions.spec.ts
Follow-up for https://github.com/owncloud/web/pull/7768.
=> [tests-only] Add unit tests for project space role assignments

changelog/unreleased/change-drive-aliases-in-urls, packages/web-app-files/src/router/public.ts, packages/web-app-files/src/router/spaces.ts, packages/web-app-files/src/router/trash.ts, packages/web-app-files/src/views/spaces/GenericSpace.vue, packages/web-app-files/src/views/spaces/GenericTrash.vue, packages/web-pkg/src/composables/appDefaults/useAppDocumentTitle.ts, packages/web-pkg/src/composables/appDefaults/useDocumentTitle.ts, packages/web-pkg/src/composables/eventBus/index.ts, packages/web-pkg/src/composables/eventBus/useEventBus.ts, packages/web-runtime/src/App.vue, packages/web-runtime/src/index.ts
Allow apps to set document titles and have them announced via the runtime.
- Fixes https://github.com/owncloud/web/issues/7718
- test case 1:
- test case 2:
- ...
=> [full-ci] Document titles

.drone.env
This PR bumps OCIS commit id to latest.
- Part of https://github.com/owncloud/QA/issues/767
- :robot:
=> [tests-only] [full-ci] Bump ocis commit id to latest

changelog/unreleased/enhancement-add-x-request-id, packages/web-app-external/src/store/index.ts, packages/web-app-user-management/src/views/Users.vue, packages/web-pkg/src/services/client/client.ts, packages/web-pkg/tests/unit/services/client.spec.ts, packages/web-runtime/src/components/Avatar.vue, packages/web-runtime/src/composables/upload/useUpload.ts, packages/web-runtime/src/container/bootstrap.ts, packages/web-runtime/src/helpers/config.js, packages/web-runtime/src/helpers/theme.js, packages/web-runtime/src/plugins/mediaSource.js, packages/web-runtime/src/plugins/web.js, packages/web-runtime/src/services/auth/authService.ts, packages/web-runtime/src/services/auth/userManager.ts, packages/web-runtime/src/services/clientRegistration.js
`X-Request-ID` headers have been added to all outgoing requests to make the tracing of requests easier.
- Fixes https://github.com/owncloud/web/issues/4675
=> Add 'X-Request-ID' header to all outgoing requests

packages/web-app-files/src/components/Shares/SharedWithMeSection.vue, packages/web-app-files/src/mixins/actions/declineShare.ts
- Fixes https://github.com/owncloud/web/issues/7779
- test case 1:
- test case 2:
- ...
=> Change decline share icon

changelog/unreleased/bugfix-cut-and-copy-for-current-folder, packages/web-app-files/src/components/FilesList/KeyboardActions.vue, packages/web-app-files/src/mixins/actions/copy.js, packages/web-app-files/src/mixins/actions/move.js, packages/web-app-files/src/store/actions.ts, packages/web-app-files/src/store/mutations.ts
The "Cut" and "Copy" actions for the current folder have been fixed.
- Fixes https://github.com/owncloud/web/issues/7784
=> Fix Cut and Copy actions for current folder

changelog/unreleased/enhancement-design-polishing, packages/web-app-files/src/components/Spaces/SpaceHeader.vue, packages/web-app-files/src/views/spaces/GenericSpace.vue, packages/web-app-files/src/views/spaces/Projects.vue, packages/web-app-files/tests/unit/components/Spaces/SpaceHeader.spec.ts, packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap, packages/web-pkg/src/components/NoContentMessage.vue, packages/web-test-helpers/src/mocks/defaultComponentMocks.ts
* Fix position of empty space frontpage
* Hide space image on small screens with open sidebar
* Fix space image fit on space frontpage
* Fix space name truncation on spaces overview
- Fixes https://github.com/owncloud/web/issues/7693
- Fixes https://github.com/owncloud/web/issues/7773
- Fixes https://github.com/owncloud/web/issues/7804
=> Spaces design polish follow-up

dev/docker/ocis.web.config.json
Add the preview app back to the ocis dev config.
=> fix: ocis dev config

.drone.star
- test case 1:
- test case 2:
- ...
=> Do not restore playwright cache for build

.drone.env
Bump oCIS commit id to the latest
Part of https://github.com/owncloud/QA/issues/768
=> [tests-only][full-ci] Bump oCIS commitid

.npmrc
- test case 1:
- test case 2:
- ...
=> Make eslint packages available to IDEs

packages/web-runtime/l10n/Makefile
fix translation steps by updating l10n make node_modules path
=> fix node_modules path for l10n make steps

package.json, packages/web-runtime/package.json, pnpm-lock.yaml, tests/unit/config/jest.init.js
Looking at https://github.com/owncloud/web/pull/7857 I wondered if we need `sync-fetch` and `cross-fetch`.
CI will tell us...
- test case 1:
- test case 2:
- ...
=> Remove sync-fetch and cross-fetch

packages/web-runtime/src/helpers/additionalTranslations.ts
=> add additional translation strings

changelog/unreleased/bugfix-spaces-on-share-via-link-page, packages/web-app-files/src/components/SideBar/SideBar.vue, packages/web-app-files/src/mixins/actions/showDetails.ts, packages/web-app-files/src/mixins/spaces/actions/showMembers.js, packages/web-app-files/src/views/spaces/Projects.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/SharesPanel.spec.js, packages/web-app-files/tests/unit/mixins/actions/showDetails.spec.ts
- Fixes https://github.com/owncloud/web/issues/7869
=> Fix space member loading on 'Shared via link'-page

packages/web-app-user-management/src/components/Groups/CreateGroupModal.vue, packages/web-app-user-management/src/components/Groups/GroupsList.vue, packages/web-app-user-management/src/components/Groups/SideBar/EditPanel.vue, packages/web-app-user-management/src/components/Users/CreateUserModal.vue, packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue, packages/web-app-user-management/src/components/Users/UsersList.vue
- Fixes https://github.com/owncloud/web/issues/7906
- test case 1:
- test case 2:
- ...
=> Turn autocomplete off

changelog/unreleased/enhancement-add-search-field-for-space-members, package.json, packages/web-app-files/package.json, packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/SpaceMembers.spec.js.snap, pnpm-lock.yaml
- Fixes https://github.com/owncloud/web/issues/7746
- test case 1:
- test case 2:
- ...
=> Add space member filter

packages/web-app-files/src/components/AppBar/AppBar.vue, packages/web-app-files/src/components/AppBar/CreateAndUpload.vue, packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js, packages/web-app-files/tests/unit/components/AppBar/__snapshots__/AppBar.spec.js.snap, tests/acceptance/features/webUIFiles/batchAction.feature, tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/utils/sidebar.ts
Superseds https://github.com/owncloud/web/pull/6351.
=> [full-ci] Hide batch actions if only 1 resource has been selected

changelog/unreleased/enhancement-batch-actions-display
Follow-Up for https://github.com/owncloud/web/pull/7904.
=> [CI SKIP] Add changelog item for PR #7904

packages/web-app-files/src/views/spaces/Projects.vue
- Fixes https://github.com/owncloud/web/issues/7608
- test case 1:
- test case 2:
- ...
=> open context menu on right click

.drone.env
Bump ocis commit id to latest.
- Part of https://github.com/owncloud/QA/issues/772
- CI
=> [tests-only][full-ci]Bump `OCIS` latest commit

tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
see https://github.com/owncloud/web/issues/7513
=> [tests-only] Skip flaky date picker test for oC10

.drone.env
Bump `ocis` latest commit id on web
https://github.com/owncloud/QA/issues/772
=> [tests-only][full-ci]Bump ocis latest commit-id

README.md
This PR updates the readme to link to the hosted documentation first and to the source files of the documentation last.
Should make it easier to understand where to get started if someone is interested in contributing to the project.
Supersedes #8000
=> Update readme docs reference

packages/web-app-text-editor/src/App.vue
Adds new translations after https://github.com/owncloud/web/pull/8023 has been merged to master.
=> Add new translations after merging stable-6.0

packages/web-pkg/tests/unit/helpers/datetime.spec.ts, tests/unit/config/jest.config.js
Add unittests for datetime helper functions
=> Add DateTime helpers unittests

changelog/unreleased/bugfix-search-repeating-no-results-message, packages/web-app-search/src/portals/SearchBar.vue
See https://github.com/owncloud/web/issues/8054
- Fixes https://github.com/owncloud/web/issues/8054
=> Bugfix: Search repeating no results message

changelog/unreleased/enhancement-increase-searchbar-height, packages/web-app-search/src/portals/SearchBar.vue
We increased the searchbar height to fit the design better.
When comparing with other web services our search input
Before:
After:
=> [full-ci] Enhancement: Increase SearchBar height

tests/drone/config-oc10-integration-app-oauth.json, tests/e2e/cucumber/features/smoke/share.oc10.feature, tests/e2e/cucumber/features/smoke/share.ocis.feature, tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature, tests/e2e/cucumber/features/smoke/upload.feature, tests/e2e/cucumber/steps/ui/public.ts, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts
This PR 
- adds tests scenario related to uploading resources
- refactored createResource() function to create base resource if  it doesn't exist in the resource create step
- add app "text-editor" in oc10 config
- added a visible option while pressing the text-editor save button because sometime saveTextFileInEditorButton doesn't save the edited file 
-  merge and replace buttons has the same class so same action is used for both cases
while uploading duplicate folders merge option is available while in duplicate file upload `replace` option available 
- Fixes <[e2e. upload.feature](https://github.com/owncloud/web/issues/7885)>
- test environment: Locally
=> [tests-only][e2e][full-ci] Add e2e upload resources tests scenario

.drone.star
This PR add code to report test failure in 4 different comment i.e e2e ocis, e2e oc10, oc10 acceptance, ocis acceptance
- Fixes https://github.com/owncloud/web/issues/7943
- https://github.com/owncloud/web/pull/8070
=> [tests-only][full-ci]Refactor GitHub comment

.vscode/extensions.json, .vscode/settings.json
Change the recommended vscode formatter.
The other ones, or at least `dbaeumer.vscode-eslint`, seem to have stopped working, when we switched to `pnpm`. `rvest.vs-code-prettier-eslint` seems to work just fine for me.
It would be nice to have it in `stable-6.0`, as we are going to have to maintain that branch for quite some time still and it's nice to have the settings in the repository, so one does not need to mess with workspace/user settings - but that would be possible as well, so it would also be okay to merge this only to master, if you have any concerns...
- test case 1:
- test case 2:
- ...
=> Change recommended vscode formatter

.drone.env
Bump ocis-master commit it latest.
Part of https://github.com/owncloud/QA/issues/785
=> [full-ci] [tests-only] Bump ocis commit id to latest `ocis-master`

packages/web-app-files/tests/unit/components/FilesList/KeyboardActions.spec.ts, packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts
=> [tests-only] Add unit-tests for the KeyboardActions component

tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md, tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md, tests/acceptance/expected-failures-with-oc10-server-openid-login.md, tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md, tests/acceptance/features/webUIFilesCopy/copy.feature, tests/acceptance/features/webUIFilesCopy/copyPrivateLinks.feature, tests/acceptance/features/webUIFilesDetails/fileDetails.feature, tests/acceptance/features/webUILogin/adminBlocksUser.feature, tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature, tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature, tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature, tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature, tests/acceptance/pageObjects/loginPage.js
This PR backports the tests related changes that have made into master branch recently to the `stable-6.0` branch as well
- https://github.com/owncloud/web/issues/7392
- https://github.com/owncloud/web/issues/7896
- CI
=> [tests-only][full-ci]Backport test related changes from master to stable branch

packages/web-app-files/src/components/AppBar/CreateAndUpload.vue, packages/web-app-files/src/components/AppBar/CreateSpace.vue, packages/web-app-files/src/components/FilesList/NotFoundMessage.vue, packages/web-app-files/src/components/Shares/SharedWithMeSection.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue, packages/web-app-files/src/views/FilesDrop.vue, packages/web-app-files/tests/unit/components/AppBar/__snapshots__/CreateAndUpload.spec.ts.snap, packages/web-app-files/tests/unit/components/FilesList/NotFoundMessage.spec.ts, packages/web-app-user-management/src/views/Groups.vue, packages/web-app-user-management/src/views/Users.vue, packages/web-pkg/src/components/sideBar/CompareSaveDialog.vue, packages/web-runtime/src/App.vue, packages/web-runtime/src/components/Topbar/UserMenu.vue, packages/web-runtime/src/pages/account.vue, packages/web-runtime/src/pages/login.vue, packages/web-runtime/src/pages/missingOrInvalidConfig.vue, packages/web-runtime/src/pages/resolvePrivateLink.vue, packages/web-runtime/src/pages/resolvePublicLink.vue, packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.ts.snap, packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap, packages/web-runtime/tests/unit/pages/__snapshots__/resolvePublicLink.spec.ts.snap
It's been long discouraged (see docs/development.md) and is broken in vue-gettext in @vue/compat, let's get rid of it.
- test case 1:
- test case 2:
- ...
=> Do not use translate component

packages/web-app-files/src/components/AppBar/CreateAndUpload.vue, packages/web-app-files/src/components/AppBar/CreateSpace.vue, packages/web-app-files/src/components/FilesList/NotFoundMessage.vue, packages/web-app-files/src/components/Shares/SharedWithMeSection.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue, packages/web-app-files/src/views/FilesDrop.vue, packages/web-app-files/tests/mocks/useScrollToMock.ts, packages/web-app-files/tests/unit/components/AppBar/__snapshots__/CreateAndUpload.spec.ts.snap, packages/web-app-files/tests/unit/components/FilesList/KeyboardActions.spec.ts, packages/web-app-files/tests/unit/components/FilesList/NotFoundMessage.spec.ts, packages/web-app-user-management/src/views/Groups.vue, packages/web-app-user-management/src/views/Users.vue, packages/web-pkg/src/components/sideBar/CompareSaveDialog.vue, packages/web-runtime/src/App.vue, packages/web-runtime/src/components/Topbar/UserMenu.vue, packages/web-runtime/src/pages/account.vue, packages/web-runtime/src/pages/login.vue, packages/web-runtime/src/pages/missingOrInvalidConfig.vue, packages/web-runtime/src/pages/resolvePrivateLink.vue, packages/web-runtime/src/pages/resolvePublicLink.vue, packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.ts.snap, packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap, packages/web-runtime/tests/unit/pages/__snapshots__/resolvePublicLink.spec.ts.snap, packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts
Bring `stable-6.0` changes @ `4b08e733103511c6a9baac6db7f95a69700d1374` to master.
=> Merge stable 6.0 to master

packages/design-system/l10n/.tx/config, packages/web-app-draw-io/l10n/.tx/config, packages/web-app-external/l10n/.tx/config, packages/web-app-files/l10n/.tx/config, packages/web-app-pdf-viewer/l10n/.tx/config, packages/web-app-preview/l10n/.tx/config, packages/web-app-search/l10n/.tx/config, packages/web-app-text-editor/l10n/.tx/config, packages/web-app-user-management/l10n/.tx/config, packages/web-client/l10n/.tx/config, packages/web-pkg/l10n/.tx/config, packages/web-runtime/l10n/.tx/config, packages/web-runtime/l10n/Makefile
Fix translation sync. https://github.com/owncloud-ci/transifex/pull/52
- test case 1:
- test case 2:
- ...
=> fix: fix syntax after switching to golang tx client

.drone.env
Bump latest ocis master commit id.
Part of https://github.com/owncloud/QA/issues/791
=> [full-ci] [tests-only] Bump ocis master latest commit id

pnpm-lock.yaml
pnpm lockfile got broken by https://github.com/owncloud/web/pull/8100 🤨
=> deps: fix broken lockfile

tests/drone/config-oc10-integration-app-oauth.json, tests/e2e/cucumber/features/smoke/share.oc10.feature, tests/e2e/cucumber/features/smoke/share.ocis.feature, tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature, tests/e2e/cucumber/features/smoke/upload.feature, tests/e2e/cucumber/steps/ui/public.ts, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts
This PR 
- adds tests scenario related to uploading resources
- refactored createResource() function to create base resource if  it doesn't exist in the resource create step
- add app "text-editor" in oc10 config
- added a visible option while pressing the text-editor save button because sometime saveTextFileInEditorButton doesn't save the edited file 
-  merge and replace buttons has the same class so same action is used for both cases
while uploading duplicate folders merge option is available while in duplicate file upload `replace` option available 
- Fixes <[e2e. upload.feature](https://github.com/owncloud/web/issues/7885)>
- https://github.com/owncloud/web/pull/7929
- test environment: Locally
=> [tests-only][e2e][full-ci]Backport test related changes from master to stable branch

.drone.env
Bump latest `ocis-master` commit id to `web-master`
https://github.com/owncloud/QA/issues/791
=> [tests-only][full-ci]Bump latest ocis-master commit-id on web master

changelog/unreleased/enhancement-preview-app-image-preloading, packages/web-app-preview/package.json, packages/web-app-preview/src/App.vue, packages/web-app-preview/src/tests/unit/views/app.spec.ts, pnpm-lock.yaml
- test case 1:
- test case 2:
- ...
=> init unit tests for image preloading

tests/e2e/cucumber/features/smoke/copyMove.feature, tests/e2e/cucumber/features/smoke/share.oc10.feature, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts
- This PR backport adding move/copy related tests scenario in e2e tests 
-  https://github.com/owncloud/web/pull/8164
=> [tests-only][full-ci] Backport move/copy related changes from master to stable branch 

.drone.env
This Pr bumps `ocis/stable-2.0` commit id to `web/stable-6.0` for tests
- Part of: https://github.com/owncloud/QA/issues/792
- CI
=> [tests-only][full-ci]Bump `ocis/stable-2.0` commit id to `web/stable-6.0` for tests

.drone.env, changelog/unreleased/enhancement-share-group-members, changelog/unreleased/enhancement-share-group-recipient
* bump ocis
* update group members changelog
=> Housekeeping, update group share changelog and bump ocis

changelog/unreleased/enhancement-spaces-list-in-admin-settings, packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue, packages/web-app-admin-settings/tests/unit/components/Spaces/SpacesList.spec.ts, packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap, packages/web-app-admin-settings/tests/unit/views/Spaces.spec.ts
- test case 1:
- test case 2:
- ...
=> Add filter

tests/e2e/support/objects/app-files/resource/actions.ts
This PR is the fix for the fail in the `upload.feature` which was seen in nightly and also in most of the PRs specially in `oc10`. The details or finding or reason behind the failure can be found in this issue. https://github.com/owncloud/web/issues/8189
This issue is faling mostly in `stable-6.0` and also sometimes in `master` branch
https://github.com/owncloud/web/issues/8189
=> [tests-only][full-ci]E2E failure in upload resource in `oc10`

tests/e2e/support/objects/app-files/resource/actions.ts
This PR back ports the changes of `stable-6.0` branch to master for this PR https://github.com/owncloud/web/pull/8191
=> [tests-only][full-ci]Back port changes of `stable-6.0` to `master`

changelog/unreleased/change-update-vue, packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
- Fixes https://github.com/owncloud/web/issues/8210
=> Prevent collaborator store object from being mutated directly

.drone.env
This PR bumps commit id of `ocis/stable-2.0` for tests
- Part of: https://github.com/owncloud/QA/issues/792
- CI
=> [tests-only][full-ci] Bump commit id for tests-stable

changelog/unreleased/enhancement-spaces-list-in-admin-settings, packages/web-app-admin-settings/src/components/AppTemplate.vue, packages/web-app-admin-settings/tests/unit/components/AppTemplate.spec.ts, packages/web-app-admin-settings/tests/unit/views/Spaces.spec.ts, packages/web-pkg/src/composables/appDefaults/useAppDefaults.ts, packages/web-pkg/src/composables/appDefaults/useAppDocumentTitle.ts, packages/web-pkg/src/composables/translations/useTranslations.ts
- test case 1:
- test case 2:
- ...
=> Page title: Use custom route title if no current file is set 

changelog/unreleased/enhancement-spaces-list-in-admin-settings, packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersPanel.vue, packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersRoleSection.vue, packages/web-app-admin-settings/src/views/Spaces.vue, packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/MembersPanel.spec.ts, packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/MembersRoleSection.spec.ts, packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/__snapshots__/MembersPanel.spec.ts.snap, packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/__snapshots__/MembersRoleSection.spec.ts.snap
- https://github.com/owncloud/web/issues/8222
=> Add filter to the space member panel in space management

docker-compose.yml
Fixes dockerized dev setup for current oCIS
=> Add GRAPH_APPLICATION_ID to oCIS in docker-compose dev setup

docker-compose.yml
Fix regression form https://github.com/owncloud/web/pull/8237.
=> Revert change of `GRAPH_LDAP_BIND_PASSWORD`

tests/e2e/cucumber/features/smoke/share.ocis.feature, tests/e2e/cucumber/steps/ui/shares.ts, tests/e2e/support/objects/app-files/link/actions.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/share/actions.ts, tests/e2e/support/objects/app-files/share/index.ts, tests/e2e/support/objects/app-files/share/utils.ts
This PR extends the story of shares for declined shares.
Added steps:
1. Before accept, checking that we cannot open file or folder
`Then "Brian" should not be able to open the folder "folder_to_shared"`
`Then "Brian" should not be able to open the file "shareToBrian.txt"`
2. After accept, copying the quicklink
`And "Brian" copies quick link of the resource "decline_shared_folder" from the context menu`
3. Decline share from the status section for accepted share and pending share
`And "Brian" declines the following share`
4. Decline share from quick action
`And "Brian" declines the following share from the context menu`
5. Accept share from quick action
`When "Brian" accepts the following share from the context menu`
- Part of https://github.com/owncloud/web/issues/6895
- Locally
- …
=> [full-ci] [e2e] [tests-only] Steps added in e2e test for share decline

tests/e2e/support/api/davSpaces/spaces.ts
Backport this PR https://github.com/owncloud/web/pull/8205 from `stable-6.0` to `master` branch
=> [tests-only][full-ci]Backport refactor to folder creation from `stable-6.0` to `master` branch

packages/web-runtime/tests/unit/components/Topbar/FeedbackLink.spec.ts
See https://github.com/owncloud/web/issues/8244
=> [tests-only] Skip the flaky FeedbackLink unit test

.drone.env, changelog/unreleased/enhancement-update-libregraph, packages/web-client/src/generated/api.ts, packages/web-client/src/graph.ts, tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
update libre-graph and add new application api to the graph.
✅  needs https://github.com/owncloud/libre-graph-api/pull/87 to be mergeable.
=> [full-ci] update libre-graph

pnpm-lock.yaml, tests/e2e/cucumber/features/smoke/reshare.feature, tests/e2e/cucumber/steps/api.ts, tests/e2e/package.json, tests/e2e/support/api/share/index.ts, tests/e2e/support/api/share/share.ts
This PR adds API step for accepting share `And "Brian" accepts the following share using API`
- Part of https://github.com/owncloud/web/issues/8101
- Local
- :robot:
=> [full-ci] [tests-only] Add apisteps accepting shared resources stable 6.0

tests/e2e/cucumber/features/smoke/reshare.feature, tests/e2e/cucumber/features/smoke/share.oc10.feature, tests/e2e/cucumber/steps/ui/shares.ts, tests/e2e/cucumber/steps/ui/spaces.ts, tests/e2e/support/objects/app-files/share/actions.ts, tests/e2e/support/objects/app-files/share/collaborator.ts, tests/e2e/support/objects/app-files/share/index.ts, tests/e2e/support/objects/app-files/spaces/actions.ts, tests/e2e/support/objects/app-files/spaces/index.ts
This PR backport this PR changes https://github.com/owncloud/web/pull/7910 from master to stable 6.0
These files were renamed:
`tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts` -> `tests/e2e/cucumber/steps/ui/spaces.ts`
`tests/e2e/cucumber/steps/app-files/share.ts` -> `tests/e2e/cucumber/steps/ui/shares.ts`
- Part of https://github.com/owncloud/web/pull/7910
- test case 1:
- test case 2:
- ...
=> [tests-only][full-ci][e2e] Backport extend resharing tests scenario

packages/design-system/package.json, pnpm-lock.yaml
It's not used anymore and causes problems on installation for some people because it pulls in deasync which depends on node-gyp
- test case 1:
- test case 2:
- ...
=> chore: Remove vue-jest from design-system devDependencies

tests/e2e/cucumber/features/smoke/share.ocis.feature, tests/e2e/cucumber/steps/ui/shares.ts, tests/e2e/support/objects/app-files/link/actions.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/share/actions.ts, tests/e2e/support/objects/app-files/share/index.ts, tests/e2e/support/objects/app-files/share/utils.ts
This PR backport https://github.com/owncloud/web/pull/8142 pr changes from master to stable
- Part of https://github.com/owncloud/web/pull/8142
- test case 1:
- test case 2:
- ...
=> [full-ci][tests-only][e2e] Backport e2e test for share decline

tests/e2e/cucumber/features/smoke/copyMove.feature, tests/e2e/cucumber/features/smoke/search.feature, tests/e2e/cucumber/steps/api.ts, tests/e2e/cucumber/steps/ui/application.ts, tests/e2e/support/api/davSpaces/index.ts, tests/e2e/support/api/davSpaces/spaces.ts
This PR adds API steps to upload files in All files (`oc10`) and in personal space for (`oCIS`).
https://github.com/owncloud/web/issues/8101
=> [tests-only][full-ci]Add API step to upload file in personal space

tests/e2e/cucumber/features/smoke/share.oc10.feature, tests/e2e/cucumber/features/smoke/share.ocis.feature, tests/e2e/cucumber/steps/ui/shares.ts, tests/e2e/support/objects/app-files/share/index.ts, tests/e2e/support/objects/app-files/share/utils.ts
This PR backports the changes of PR https://github.com/owncloud/web/pull/8174 on master to `stable-6.0`
=> [tests-only][full-ci] Backport `Add remove sharee step in share.ocis.feature` to `stable-6.0`

changelog/unreleased/enhancement-tags-support, packages/web-app-files/src/components/SideBar/TagsPanel.vue, packages/web-client/src/helpers/space/functions.ts
- Fixes https://github.com/owncloud/web/issues/8220
- Fixes https://github.com/owncloud/web/issues/8253
- Fixes https://github.com/owncloud/web/issues/8254
=> Properly disable editing tags for space resources

changelog/unreleased/change-update-vue, packages/web-app-admin-settings/src/components/Groups/CreateGroupModal.vue, packages/web-app-admin-settings/src/components/Groups/SideBar/EditPanel.vue, packages/web-app-admin-settings/src/components/Users/CreateUserModal.vue, packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
Regression form the Vue 3 upgrade.
- Fixes https://github.com/owncloud/web/issues/8295
- Fixes https://github.com/owncloud/web/issues/8225
=> Fix input validation for users and groups

packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue, packages/web-app-files/src/components/SideBar/Shares/Links/CreateQuickLink.vue, packages/web-app-files/tests/unit/components/SideBar/Actions/SpaceActions.spec.ts, packages/web-app-files/tests/unit/components/SideBar/NoSelection.spec.ts, packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditDropdown.spec.ts, packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/EditDropdown.spec.ts.snap, packages/web-app-files/tests/unit/components/SideBar/Shares/Links/CreateQuickLink.spec.ts, packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/CreateQuickLink.spec.ts.snap, packages/web-app-files/tests/unit/components/SideBar/Shares/Shared/RoleItem.spec.ts, packages/web-app-files/tests/unit/components/SideBar/Shares/Shared/__snapshots__/RoleItem.spec.ts.snap, packages/web-app-files/tests/unit/components/SideBar/__snapshots__/NoSelection.spec.ts.snap
=> [tests-only] Add missing sidebar unit tests

tests/e2e/cucumber/features/smoke/copyMove.feature, tests/e2e/cucumber/features/smoke/search.feature, tests/e2e/cucumber/steps/ui/application.ts
This PR backports this PR https://github.com/owncloud/web/pull/8200 changes from `stable-6.0` to `master` branch 
Most of the changes were rebased from this PR https://github.com/owncloud/web/pull/8303
=> [tests-only][full-ci]Backport create file in personal space into `master` 

packages/web-app-admin-settings/src/components/Groups/GroupsList.vue, packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue, packages/web-app-admin-settings/tests/unit/components/Groups/GroupsList.spec.ts, packages/web-app-admin-settings/tests/unit/components/Spaces/SpacesList.spec.ts, packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap, packages/web-app-files/src/components/FilesList/ResourceTable.vue, packages/web-pkg/src/components/ContextActions/ContextMenuQuickAction.vue, packages/web-pkg/tests/unit/components/ContextActions/ContextMenuQuickAction.spec.ts, packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ContextMenuQuickAction.spec.ts.snap
... to reduce boilerplate code. We need it in the users list soon as well.
=> Refactor quick action for the context menu to a dedicated component

.drone.star
The drone file is refactored so the acceptance test gets to run in nightly for stable-6.0 branch.
Fixes https://github.com/owncloud/web/issues/8312
=> [full-ci] [tests-only] Run acceptance test in nightly

.drone.env
Bump ocis master commit id to latest.
Part of https://github.com/owncloud/QA/issues/795
=> [full-ci] [tests-only] Bump ocis master commit id to latest

changelog/unreleased/bugfix-resolving-interal-file-links, packages/web-app-files/src/views/shares/SharedWithMe.vue, packages/web-runtime/src/pages/resolvePrivateLink.vue
Resolving internal file links when the original file is a shared resource has been fixed.
- Fixes https://github.com/owncloud/web/issues/8284
=> Fix resolving internal file links

changelog/unreleased/enhancement-admin-settings-users-role-graph-api-usage, packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue, packages/web-app-admin-settings/src/views/Users.vue
- test case 1:
- test case 2:
- ...
=> Fix compare save dialog in user managerment

tests/e2e/cucumber/features/journeys/kindergarten.oc10.feature, tests/e2e/cucumber/features/journeys/kindergarten.ocis.feature, tests/e2e/cucumber/features/smoke/link.feature, tests/e2e/cucumber/features/smoke/share.oc10.feature, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/resource/actions.ts
This PR forward ports https://github.com/owncloud/web/pull/8264 this PR to `master` branch
=> [tests-only][full-ci]Forward port expansion of kinder garden to `master`

changelog/unreleased/enhancement-admin-settings-user-details-improvement, packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue, packages/web-app-admin-settings/tests/unit/components/Users/SideBar/DetailsPanel.spec.ts
- test case 1:
- test case 2:
- ...
=> Enhancements

packages/design-system/src/components/OcButton/OcButton.spec.ts, packages/design-system/src/components/OcButton/OcButton.vue, packages/design-system/src/components/OcGrid/OcGrid.spec.ts, packages/design-system/src/components/OcImage/OcImage.spec.ts, packages/design-system/src/components/OcNotificationMessage/OcNotificationMessage.spec.ts, packages/design-system/src/components/OcNotifications/OcNotifications.spec.ts, packages/design-system/src/components/OcPagination/OcPagination.spec.ts, packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts, packages/web-runtime/src/pages/resolvePublicLink.vue, packages/web-runtime/tests/unit/mixins/lifecycleMixin.spec.ts, packages/web-runtime/tests/unit/pages/__snapshots__/resolvePublicLink.spec.ts.snap, packages/web-runtime/tests/unit/pages/resolvePublicLink.spec.ts
=> [tests-only] Un-skip unit tests

tests/e2e/cucumber/features/smoke/internalLink.ocis.feature, tests/e2e/cucumber/steps/api.ts, tests/e2e/cucumber/steps/ui/links.ts, tests/e2e/cucumber/steps/ui/session.ts, tests/e2e/support/api/share/share.ts, tests/e2e/support/environment/actor/actor.ts, tests/e2e/support/objects/app-files/page/shares/withMe.ts, tests/e2e/support/types.ts
Forward port of https://github.com/owncloud/web/pull/8260
=> [tests-only][full-ci] Add e2e tests related to internal link in personal space (port)

.drone.env
Part of: https://github.com/owncloud/QA/issues/797
=> [tests-only][full-ci]Bump commit id for tests in stable branch

packages/web-pkg/src/mixins/spaces/restore.ts
While translating in Transifex, I found this error.
=> fixed typo

tests/e2e/cucumber/features/journeys/kindergarten.oc10.feature, tests/e2e/cucumber/features/journeys/kindergarten.ocis.feature, tests/e2e/cucumber/features/smoke/share.oc10.feature, tests/e2e/cucumber/features/smoke/share.ocis.feature, tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature, tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature, tests/e2e/cucumber/steps/ui/public.ts, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/page/public.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts
This PR is the forward port of the PR of `stable-6.0` https://github.com/owncloud/web/pull/8348
=> [tests-only][full-ci]Forward port to delete serveral `(objects|resources)`

docker-compose.yml
This prevents the user from getting logged out every 5 minutes, which is pretty annoying during development. It happens due to a bug, once it is resolved, we can remove this again.
=> Increase IDP access token expiration in dockerized setup

tests/acceptance/pageObjects/textEditorPage.js
Forward port of PR https://github.com/owncloud/web/pull/8394
Fixes https://github.com/owncloud/web/issues/8329
=> [tests-only][full-ci] Wait until file saving is finished (forward port)

.drone.star, package.json, packages/babel-preset/package.json, packages/design-system/package.json, packages/eslint-config/package.json, packages/prettier-config/package.json, packages/tsconfig/package.json, packages/web-app-admin-settings/package.json, packages/web-app-draw-io/package.json, packages/web-app-external/package.json, packages/web-app-files/package.json, packages/web-app-pdf-viewer/package.json, packages/web-app-preview/package.json, packages/web-app-search/package.json, packages/web-app-text-editor/package.json, packages/web-client/package.json, packages/web-pkg/package.json, packages/web-runtime/package.json, packages/web-runtime/src/container/application/index.ts, pnpm-lock.yaml, tests/unit/config/jest.config.ts, vite.config.ts
This PR will enable us to release individual packages from `packages/` to NPM.
It does not handle changelogs so far
We want to make it possible to develop external apps without copying a ton of boilerplate, so we want to publish web-client, web-pkg and a bunch of config packages (tsconfig, eslint-config, prettier-config, etc)
- I created release tags in this PR
=> [full-ci] NPM publishing

tests/acceptance/pageObjects/personalPage.js
This PR forward port the intermittent failure fix related to upload resources scenario
- https://github.com/owncloud/web/pull/8393
- test case 1:
- test case 2:
- ...
=> [tests-only][full-ci] Forward port fix upload success check

changelog/unreleased/enhancement-admin-change-spaces-quota-batch-action, packages/web-app-admin-settings/src/views/Users.vue, packages/web-pkg/src/mixins/spaces/editQuota.ts
Fixed a bug, where clicking info or edit action had no effect after a user had been selected before 
- test case 1:
- test case 2:
- ...
=> Fix user selection and simplify code

changelog/unreleased/enhancement-resources-tiles-view, packages/web-app-files/src/components/FilesList/ResourceTiles.vue, packages/web-app-files/src/composables/resourcesViewDefaults/useResourcesViewDefaults.ts, packages/web-app-files/src/composables/sort/useSort.ts, packages/web-app-files/src/helpers/ui/index.ts, packages/web-app-files/src/helpers/ui/resourceTiles.ts, packages/web-app-files/src/views/shares/SharedWithMe.vue, packages/web-app-files/src/views/spaces/GenericSpace.vue, packages/web-app-files/src/views/spaces/Projects.vue, packages/web-app-files/tests/mocks/useResourcesViewDefaultsMock.ts, packages/web-app-files/tests/unit/components/FilesList/ResourceTiles.spec.ts, packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap, packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
- Fixes https://github.com/owncloud/web/issues/8370
=> Implement sorting for resource tiles

changelog/unreleased/enhancement-admin-change-spaces-quota-batch-action, packages/web-app-admin-settings/src/components/Spaces/SideBar/ActionsPanel.vue, packages/web-app-admin-settings/src/views/Spaces.vue, packages/web-app-admin-settings/src/views/Users.vue, packages/web-app-files/src/components/Spaces/SpaceContextActions.vue, packages/web-pkg/src/components/Spaces/QuotaModal.vue, pnpm-lock.yaml
See https://github.com/owncloud/web/pull/8387
Fixes https://github.com/owncloud/web/issues/8417
=> #8387 Spaces/User admin list edit quota batch actions - Followup

changelog/unreleased/enhancement-configurable-topbar, packages/web-runtime/src/components/Topbar/TopBar.vue, packages/web-runtime/tests/unit/components/Topbar/__snapshots__/TopBar.spec.ts.snap
This creates a vue portal to allow apps to render on the top bar right icons side.
=> Up configurable topbar

.drone.env
Part of https://github.com/owncloud/QA/issues/799
=> [full-ci] [tests-only] Bump ocis commit id stable

changelog/unreleased/enhancement-resources-tiles-view, packages/design-system/src/components/OcTile/OcTile.vue, packages/web-app-files/src/components/FilesList/ResourceTiles.vue, packages/web-app-files/tests/unit/components/FilesList/ResourceTiles.spec.ts
Random find, worth the fix I suppose
=> Fix fileExtensionShown toggle for ResourceTiles

changelog/unreleased/change-streamline-editor-new-tabs, docs/getting-started.md, packages/web-app-draw-io/src/index.ts, packages/web-app-files/src/mixins/fileActions.ts, packages/web-app-files/tests/__fixtures__/fileActions.ts, packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts, packages/web-runtime/src/store/apps.ts, packages/web-runtime/src/store/config.ts, tests/e2e/support/objects/app-files/resource/actions.ts
=> Change: Globally configurable extension new tab handling

changelog/unreleased/bugfix-archiver-public-link, packages/web-app-files/src/mixins/actions/downloadArchive.ts, packages/web-app-files/src/services/archiver.ts, packages/web-app-files/tests/unit/services/archiver.spec.ts, packages/web-pkg/src/helpers/download.ts, packages/web-pkg/src/helpers/index.ts, packages/web-runtime/src/plugins/web.ts, packages/web-runtime/src/services/auth/publicLinkManager.ts
Fixes downloading multiple resources as archive in protected public links.
- Fixes https://github.com/owncloud/web/issues/6423
=> [full-ci] Fix archiver for protected public links

changelog/unreleased/enhancement-notification-bell, packages/web-pkg/src/composables/capability/useCapability.ts, packages/web-runtime/src/components/Topbar/NotificationBell.vue, packages/web-runtime/src/components/Topbar/Notifications.vue, packages/web-runtime/tests/unit/components/Topbar/Notification.spec.ts, packages/web-runtime/tests/unit/components/Topbar/NotificationBell.spec.ts, packages/web-runtime/tests/unit/components/Topbar/__snapshots__/NotificationBell.spec.ts.snap
Implement notification badge counter for bell icon.
Set
`notifications: {
'ocs-endpoints': ['list', 'get', 'delete']
}`
Animation:
[screen-capture.webm](https://user-images.githubusercontent.com/786551/219460758-911fe2db-b73b-4411-8b0d-b16ce3e7f8c5.webm)
=> [full-ci] Notification bell badge count

changelog/unreleased/enhnacement-respect-max-quota, packages/web-app-admin-settings/src/components/Spaces/ContextActions.vue, packages/web-app-admin-settings/src/components/Spaces/SideBar/ActionsPanel.vue, packages/web-app-admin-settings/src/components/Users/ContextActions.vue, packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue, packages/web-app-admin-settings/src/views/Spaces.vue, packages/web-app-admin-settings/src/views/Users.vue, packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue, packages/web-app-files/src/components/Spaces/SpaceContextActions.vue, packages/web-pkg/src/components/QuotaSelect.vue, packages/web-pkg/src/components/Spaces/QuotaModal.vue, packages/web-pkg/src/composables/capability/useCapability.ts, packages/web-pkg/tests/unit/components/QuotaSelect.spec.ts
- Fixes https://github.com/owncloud/web/issues/8490
- test case 1:
- test case 2:
- ...
=> Apply max quota to users and spaces 

changelog/unreleased/enhancement-user-role-filter, packages/web-app-admin-settings/src/views/Users.vue, packages/web-app-admin-settings/tests/unit/views/Users.spec.ts
=> Add role filter to users view

changelog/unreleased/enhancement-tags-support, packages/web-app-files/src/components/SideBar/TagsPanel.vue, packages/web-app-files/tests/unit/components/SideBar/TagsPanel.spec.ts
- Fixes https://github.com/owncloud/web/issues/8426
- Fixes https://github.com/owncloud/web/issues/8427
=> Prevent blank tags from being created

.drone.star
- test case 1:
- test case 2:
- ...
=> Add extension-sdk to the list of releasable packages

.drone.star
For some reason the old approach stopped working 🙈 
Setting the env var via drone directly or via export did not work, using `env` was the only approach I could make this work with ...
- test case 1:
- test case 2:
- ...
=> Fix pnpm publish

tests/e2e/cucumber/features/smoke/link.feature, tests/e2e/support/environment/actor/shared.ts, tests/e2e/support/objects/app-files/share/actions.ts
Forward port of PR #8499
Closes https://github.com/owncloud/web/issues/8347
=> [tests-only][full-ci] Add a e2e test for quick link (#8499)

.drone.env
This PR bumps ocis master commit id to latest.
- Part of https://github.com/owncloud/QA/issues/802
- :robot:
=> [full-ci] [tests-only] Bump ocis-master commit id to latest `master`

.drone.env
This PR bumps ocis stable-2.0 commit id to latest.
- Part of https://github.com/owncloud/QA/issues/802
- :robot:
=> [full-ci] [tests-only] Bump ocis stable commit `stable-6.0`

.drone.env, tests/e2e/cucumber/features/smoke/notifications.oc10.feature, tests/e2e/cucumber/features/smoke/notifications.ocis.feature, tests/e2e/cucumber/steps/ui/notifications.ts, tests/e2e/support/objects/runtime/application.ts
Follow-up for https://github.com/owncloud/web/pull/8518.
=> [tests-only] Add notification e2e tests

changelog/unreleased/bugfix-group-members-sorting, packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
- Fixes https://github.com/owncloud/web/issues/8592
=> Fix group members sorting

changelog/unreleased/enhancement-admin-change-spaces-quota-batch-action, packages/web-app-admin-settings/src/components/Users/ContextActions.vue, packages/web-app-admin-settings/src/views/Users.vue, packages/web-pkg/src/components/Spaces/QuotaModal.vue
- Fixes https://github.com/owncloud/web/issues/8572
=> Fix quota modal text for users

packages/web-runtime/src/router/helpers.ts, packages/web-runtime/src/services/auth/authService.ts
=> Fix the 'details' query-param for private links

tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature, tests/e2e/cucumber/features/smoke/reshare.feature, tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature, tests/e2e/cucumber/steps/api.ts, tests/e2e/cucumber/steps/ui/adminSettings.ts, tests/e2e/support/objects/app-admin-settings/users/actions.ts, tests/e2e/support/objects/app-admin-settings/users/index.ts
=> [test-only] Add and remove user to groups

tests/e2e/cucumber/features/smoke/copyMove.feature, tests/e2e/support/objects/app-files/resource/actions.ts
=> [test-only] fix moving test

tests/e2e/cucumber/features/smoke/notifications.oc10.feature, tests/e2e/cucumber/features/smoke/notifications.ocis.feature, tests/e2e/cucumber/features/smoke/search.feature, tests/e2e/cucumber/features/smoke/spaces/internalLink.ocis.feature, tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature, tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature, tests/e2e/cucumber/features/smoke/tags.ocis.feature, tests/e2e/cucumber/features/smoke/tiles.feature, tests/e2e/cucumber/features/smoke/upload.feature
This PR fixes the formatting of the feature so that they all follow a similar pattern.
=> [tests-only]Fix formatting of feature files

tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature, tests/e2e/cucumber/steps/ui/adminSettings.ts, tests/e2e/support/objects/app-admin-settings/users/actions.ts, tests/e2e/support/objects/app-admin-settings/users/index.ts
=> [test-only] delete users test

tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature, tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature, tests/e2e/cucumber/steps/ui/adminSettings.ts, tests/e2e/support/objects/app-admin-settings/spaces/actions.ts, tests/e2e/support/objects/app-admin-settings/spaces/index.ts
This PR extends the tests to be able to edit space changing following using a context menu
- rename project space
- edit quota of a project space
- enable project space
- Part of: https://github.com/owncloud/web/issues/8601
- locally 
- ci
=> [tests-only] Adds e2e tests for managing space admin settings via context menu

.drone.env, packages/web-runtime/src/services/auth/abilities.ts, packages/web-runtime/tests/unit/services/auth/abilities.spec.ts
use Drive.ReadWriteQuota.Project from https://github.com/owncloud/ocis/pull/5662/commits/8e4bf92a94b89d4a89c553432ffc230593e91adb
- Needed by https://github.com/owncloud/ocis/pull/5662
=> Use new Drive.ReadWriteQuota.Project Permission

tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature, tests/e2e/cucumber/steps/ui/adminSettings.ts, tests/e2e/support/objects/app-admin-settings/spaces/actions.ts, tests/e2e/support/objects/app-admin-settings/spaces/index.ts
This PR does the following
- extends the tests to be able to enable spaces with batch actions
- extends the tests to be able to set quota with batch actions
- makes code DRY
- Part of: https://github.com/owncloud/web/issues/8601
-  CI
- e2e
=> [tests-only] Adds e2e tests for enabling and setting quota of spaces with batch-action

tests/e2e/cucumber/features/smoke/admin-settings/groups.ocis.feature, tests/e2e/cucumber/steps/ui/adminSettings.ts, tests/e2e/support/api/graph/userManagement.ts, tests/e2e/support/objects/app-admin-settings/groups/actions.ts, tests/e2e/support/objects/app-admin-settings/groups/index.ts, tests/e2e/support/types.ts
after creating group user checks that groups are visible on web
=> [test-only] get group test

docker-compose.yml, vite.config.ts
Fix logo upload in vite (and our dev setup in general by mounting the dist folder rw to the ocis container)
=> Vite: Fix logo upload

tests/e2e/cucumber/features/smoke/admin-settings/groups.ocis.feature, tests/e2e/cucumber/steps/ui/adminSettings.ts, tests/e2e/support/objects/app-admin-settings/groups/actions.ts, tests/e2e/support/objects/app-admin-settings/groups/index.ts
=> [test-only] delete group

tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature, tests/e2e/cucumber/steps/ui/adminSettings.ts, tests/e2e/support/objects/app-admin-settings/users/actions.ts, tests/e2e/support/objects/app-admin-settings/users/index.ts
This Pr adds tests for opening the edit panel via quick action and context menu
- part of: https://github.com/owncloud/web/issues/8601
- locally
- CI
=> [tests-only]Add tests for opening edit panel via quick action and context menu

packages/web-app-admin-settings/src/components/Users/GroupsModal.vue, packages/web-app-admin-settings/src/composables/actions/groups/useGroupActionsDelete.ts, packages/web-app-admin-settings/src/composables/actions/users/useUserActionsDelete.ts, packages/web-app-admin-settings/src/views/Users.vue, packages/web-pkg/src/components/Spaces/QuotaModal.vue, packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDelete.ts, packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDisable.ts, packages/web-pkg/src/composables/actions/spaces/useSpaceActionsRestore.ts
- Fixes https://github.com/owncloud/web/issues/8579
- Fixes https://github.com/owncloud/web/issues/8639
- test case 1:
- test case 2:
- ...
=> Admin settings modals unify

tests/e2e/cucumber/steps/ui/adminSettings.ts, tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
PR https://github.com/owncloud/web/pull/8661 didn't add assertions in then step, maybe I messed up while rebasing and removed the assertion so this PR fixes that.
=> [tests-only]Add assertion in a e2e tests

tests/e2e/support/objects/app-files/spaces/actions.ts
description flaky here: https://github.com/owncloud/web/issues/8648#issuecomment-1479440513
checking all responses when creating a space
=> [test-only] check alll responses when create space

tests/e2e/support/objects/app-files/utils/sidebar.ts
This is a fixing PR for the issue where  `sidebar panel close button` selector resolves to multiple elements. The selector for `sidebar panel closing button` is changed.
Proof of work: 
```
100 scenarios (100 passed)
2700 steps (2700 passed)
134m56.717s (executing steps: 134m50.655s)
```
https://drone.owncloud.com/owncloud/web/34162/10/16
- Fixes https://github.com/owncloud/web/issues/8564
- locally
- :robot:
=> [full-ci] [tests-only] Fixes for e2e test failure

tests/e2e/cucumber/features/smoke/tiles.feature, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts
fix flaky https://github.com/owncloud/web/issues/8648#issuecomment-1482314140
=> [test-only] fix flaky tiles tests

docs/deployments/oc10-app.md
- test case 1:
- test case 2:
- ...
=> docs(oc-10-app); fix the wrong url

tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
At scenario `Scenario: list members via sidebar`, user is not logged out
```feature
Scenario: list members via sidebar
Given "Admin" creates following users using API
| id      |
| Alice   |
...
Then "Alice" should see the following users in the sidebar panel of spaces admin settings
| user    | role    |
...
| Richard | viewer  |
```
This causes the next scenario `Scenario: user login can be managed in the admin settings` to fail every time
```feature
Scenario: user login can be managed in the admin settings
Given "Admin" creates following user using API
| id    |
| Alice |
When "Admin" logs in
And "Admin" opens the "admin-settings" app
And "Admin" navigates to the users management page
And "Admin" forbids the login for the following user "Alice" using the sidebar panel
And "Admin" logs …
```
=> [full-ci][tests-only] Logout user properly at the end of the scenario

changelog/unreleased/bugfix-dropdown-nooptions-height, packages/design-system/src/components/OcSelect/OcSelect.vue
- Fixes https://github.com/owncloud/web/issues/8716
=> fix nooptions select option

tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/cucumber/steps/ui/spaces.ts, tests/e2e/support/objects/app-admin-settings/spaces/actions.ts, tests/e2e/support/objects/app-admin-settings/users/actions.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts, tests/e2e/support/objects/app-files/spaces/actions.ts, tests/e2e/support/objects/app-files/spaces/index.ts, tests/e2e/support/objects/app-files/spaces/utils.ts
related https://github.com/owncloud/web/pull/8709#issuecomment-1484874600
I changed `isVisible()` to `expect(locator).toBeVisible` or `expect(locator).not.toBeVisible`
=> [test-only] get rid of isVisible()

packages/design-system/src/components/OcBreadcrumb/OcBreadcrumb.spec.ts, packages/design-system/src/components/OcBreadcrumb/OcBreadcrumb.vue, packages/web-app-admin-settings/tests/unit/views/__snapshots__/Spaces.spec.ts.snap, packages/web-app-files/src/components/AppBar/AppBar.vue
Regression from https://github.com/owncloud/web/pull/8682.
- Fixes https://github.com/owncloud/web/issues/8747
=> Fix context menu showing for root breadcrumb items

tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/share/collaborator.ts
ocis Ci is red again:
fix creating drawio file
https://drone.owncloud.com/owncloud/ocis/20983/68/10
https://drone.owncloud.com/owncloud/ocis/20982/68/10
=> [test-only] fix creating drawio file

tests/e2e/support/objects/app-files/share/collaborator.ts
Wait for responses that hit after adding sharees
https://github.com/owncloud/web/issues/8648#issuecomment-1482614610
=> [tests-only][full-ci] Fix space share expiration test

tests/e2e/cucumber/features/smoke/createSpaceFromSelection.ocis.feature
Skipped temporarily to get the oCIS pipeline green: https://drone.owncloud.com/owncloud/ocis/21165
Maybe the issues will be solved via https://github.com/owncloud/web/pull/8781, but we can try that later.
=> [tests-only] Skip space shortcut e2e tests temporarily

packages/web-app-files/src/components/Search/List.vue, packages/web-app-search/src/portals/SearchBar.vue
- Fixes https://github.com/owncloud/web/issues/8644
- test case 1:
- test case 2:
- ...
=> Clear search bar after leaving result page

packages/web-app-files/src/components/FilesList/ResourceTable.vue, packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
…t show a result
- test case 1:
- test case 2:
- ...
=> Fix clicking on a tag in the files list that contains a space, doesn't show a result

packages/web-app-files/src/components/SideBar/TagsPanel.vue, packages/web-app-files/tests/unit/components/SideBar/TagsPanel.spec.ts
- Fixes https://github.com/owncloud/web/issues/7972
- test case 1:
- test case 2:
- ...
=> Show message if edit tags fail

packages/web-app-files/src/components/AppBar/ViewOptions.vue, packages/web-app-files/tests/unit/components/AppBar/ViewOptions.spec.ts
- Fixes https://github.com/owncloud/web/issues/8807
- test case 1:
- test case 2:
- ...
=> Fix: Page size selection has no effect

packages/web-app-admin-settings/src/components/Groups/CreateGroupModal.vue, packages/web-app-admin-settings/src/components/Groups/SideBar/EditPanel.vue, packages/web-app-admin-settings/src/components/Users/CreateUserModal.vue, packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue, packages/web-app-admin-settings/tests/unit/components/Groups/CreateGroupModal.spec.ts, packages/web-app-admin-settings/tests/unit/components/Groups/SideBar/EditPanel.spec.ts, packages/web-app-admin-settings/tests/unit/components/Users/CreateUserModal.spec.ts, packages/web-app-admin-settings/tests/unit/components/Users/SideBar/EditPanel.spec.ts, packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/Links/DetailsAndEdit.spec.ts
- Part of https://github.com/owncloud/web/issues/8589
- test case 1:
- test case 2:
- ...
=> Add char len max 255 validation

packages/web-app-admin-settings/src/components/Users/LoginModal.vue, packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue, packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap, packages/web-app-files/src/components/AppBar/ViewOptions.vue
- Fixes https://github.com/owncloud/web/issues/8813
- test case 1:
- test case 2:
- ...
=> Fix pagesize not highlighted

packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue, tests/e2e/support/objects/app-admin-settings/users/actions.ts
- Fixes https://github.com/owncloud/web/issues/8767
- test case 1:
- test case 2:
- ...
=> Fix revert in user edit panel not working

packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/Links/DetailsAndEdit.spec.ts
- Fixes https://github.com/owncloud/web/issues/8589
- test case 1:
- test case 2:
- ...
=> Enable link password length validation

changelog/unreleased/enhancement-adjust-no-reshare-perm-message, packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
We've changed the missing reshare permission message to be more clear.
For more details see conversation: https://github.com/owncloud/web/issues/8701
- Fixes https://github.com/owncloud/web/issues/8701
=> Adjust missing reshare permissions message

packages/web-app-admin-settings/src/components/Users/LoginModal.vue
Follow-up for https://github.com/owncloud/web/pull/8812. This solution is a bit nicer.
=> Improve current value selection for the edit login action

tests/e2e/cucumber/environment/index.ts, tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature, tests/e2e/support/api/graph/index.ts, tests/e2e/support/api/graph/spaces.ts, tests/e2e/support/api/http.ts
This issue clean-up the spaces after the test scenario run. 
- https://github.com/owncloud/web/issues/8662
- locally
=> [full-ci] [tests-only] Cleanup spaces created by test scenario after execution of tests

packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue, packages/web-app-files/src/components/SideBar/Shares/FileShares.vue, packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue, packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue, packages/web-app-files/src/components/SideBar/SideBar.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/DetailsAndEdit.spec.ts.snap, packages/web-app-files/tests/unit/components/SideBar/Shares/SpaceMembers.spec.ts, packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/SpaceMembers.spec.ts.snap, packages/web-client/src/helpers/space/functions.ts
I actually packed a few smaller fixes in here:
- Fixes https://github.com/owncloud/web/issues/8642
- Fixes https://github.com/owncloud/web/issues/8830
- Fixes https://github.com/owncloud/web/issues/8181
=> Hide sharing for disabled spaces

tests/e2e/support/objects/app-files/resource/index.ts, tests/e2e/support/objects/app-files/share/utils.ts
https://drone.owncloud.com/owncloud/ocis/21380/68/10
https://drone.owncloud.com/owncloud/ocis/21392/88/9
and more ....
click by 'body' https://github.com/owncloud/web/blob/master/tests/e2e/support/objects/app-files/resource/index.ts#L73-L74 hit right on the button `decline`
cc @kobergj 
second commit - to accelerate the test
=> [test-only] flaky e2e while uploading

tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature, tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature, tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature, tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature, tests/e2e/support/store/user.ts
This PR replaces "marie" and "richard" because this user is a demo user
- Fixes https://github.com/owncloud/web/issues/8821
- Locally
=> [tests-only][full-ci] Replace dummy user "marie" and "richard"

packages/design-system/src/components/OcSwitch/OcSwitch.vue
- Fixes https://github.com/owncloud/web/issues/7542
Before:
After:
=> Fix alignment of the active oc-switch

packages/design-system/src/components/OcModal/OcModal.vue
- Fixes https://github.com/owncloud/web/issues/8843
=> Fix z-index of the OcModal background

packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap, packages/design-system/src/components/OcSelect/OcSelect.vue, packages/design-system/src/components/OcTextInput/OcTextInput.vue, packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue, packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/__snapshots__/MembersPanel.spec.ts.snap, packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap, packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap, packages/web-app-admin-settings/tests/unit/components/Users/__snapshots__/GroupSelect.spec.ts.snap, packages/web-app-admin-settings/tests/unit/components/Users/__snapshots__/LoginModal.spec.ts.snap, packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/SpaceMembers.spec.ts.snap, packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap, packages/web-runtime/tests/unit/pages/__snapshots__/resolvePublicLink.spec.ts.snap
- Needed for https://github.com/owncloud/web/issues/8840
- test case 1:
- test case 2:
- ...
=> Enable readOnly prop for OcSelect and OcTextInput

dev/docker/oc10.web.config.json, docs/deployments/oc10-app.md, tests/drone/config-oc10-integration-app-oauth.json
- Fixes https://github.com/owncloud/web/issues/8678
- test case 1:
- test case 2:
- ...
=> Fix lang code for zh

changelog/unreleased/enhancement-custom-translations
- test case 1:
- test case 2:
- ...
=> fix changelog entry 

.drone.env
Bump ocis latest commit id to web master.
https://github.com/owncloud/QA/issues/806
=> [tests-only][full-ci]Bump latest ocis commit to web

changelog/unreleased/enhancement-add-expiration-date-hint-to-public-links, changelog/unreleased/enhancement-fix-quicklink-icon-alignment, packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/DetailsAndEdit.spec.ts.snap
For more details see: https://github.com/owncloud/web/issues/8211
- Fixes https://github.com/owncloud/web/issues/8211
=> Display remaining link time

packages/design-system/src/components/OcModal/OcModal.vue, packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap, packages/web-app-admin-settings/tests/unit/components/Users/__snapshots__/LoginModal.spec.ts.snap, packages/web-app-files/src/composables/actions/files/useFileActionsCreateSpaceFromResource.ts
- Fixes https://github.com/owncloud/web/issues/8838
- test case 1:
- test case 2:
- ...
=> Enhance create space from ... dialog - alternative

packages/web-app-files/src/views/trash/Overview.vue
- Fixes https://github.com/owncloud/web/issues/8881
- test case 1:
- test case 2:
- ...
=> Don't show disabled spaces in the trash overview

changelog/unreleased/bugfix-sidebar-header-after-deleting-resource, packages/web-app-files/src/components/SideBar/SideBar.vue
- Fixes https://github.com/owncloud/web/issues/8880
=> Remove sidebar header when deleting the currently selected resource

packages/web-app-admin-settings/src/views/Groups.vue, packages/web-app-admin-settings/src/views/Users.vue, packages/web-app-files/src/helpers/contextualHelpers.ts, packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/SpaceMembers.spec.ts.snap
Minor changes to translatable strings while checking translations.
=> Adapt translations

dev/docker/ocis.idp.config.yaml
file picker oidc redirect uris have changed... also adjusting here.
=> chore: adjust file picker client redirect uris

packages/web-app-files/src/components/SideBar/Shares/Links/CreateQuickLink.vue, packages/web-app-files/src/components/SideBar/Shares/Links/NameAndCopy.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/NameAndCopy.spec.ts.snap
- Fixes https://github.com/owncloud/web/issues/8890
- test case 1:
- test case 2:
- ...
=> Change appeareance of link copy button

packages/web-runtime/src/pages/account.vue
- test case 1:
- test case 2:
- ...
=> Change string

packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
- test case 1:
- test case 2:
- ...
=> Fix show more show less link collapse

.drone.star
It seems they got disabled accidentally yesterday.
=> Re-enable e2e-tests in pipeline

packages/web-app-search/src/portals/SearchBar.vue
=> Translate search provider string in search results dropdown

packages/web-app-files/src/store/actions.ts
When adding shares or links, we always assumed that we do that for the currently selected item. When adding a link however, this doesn't need to be the case (as described in https://github.com/owncloud/web/issues/8933). Therefore we need to check for this edge case and handle it a bit differently by:
* Setting `indirect` to `true` because the currently selected item now got an indirect share via its parent (parent = the item that actually got the new share)
* Updating the `ancestor` which can't be found by the currently selected item, but by the item that received the new share
- Fixes https://github.com/owncloud/web/issues/8933
=> Fix shares when creating a link for the current folder via context menu

packages/web-app-files/src/components/FilesList/ResourceTiles.vue, packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
- Fixes https://github.com/owncloud/web/issues/8931
- test case 1:
- test case 2:
- ...
=> Fix appeareance of tile sorting

packages/web-pkg/src/composables/actions/files/useFileActionsSetReadme.ts, packages/web-pkg/tests/unit/composables/actions/files/useFileActionsSetReadme.spec.ts
- Fixes https://github.com/owncloud/web/issues/8937
- test case 1:
- test case 2:
- ...
=> Fix space readme

packages/design-system/src/components/OcDatepicker/OcDatepicker.vue, pnpm-lock.yaml
- Fixes https://github.com/owncloud/web/issues/8955
- test case 1:
- test case 2:
- ...
=> Visualize disabled dates in oc datepicker 

packages/web-runtime/src/pages/account.vue
- Fixes https://github.com/owncloud/web/issues/8895
- test case 1:
- test case 2:
- ...
=> Set select value to browser lang if not set in accounts service

packages/web-app-files/src/composables/actions/files/useFileActionsSetImage.ts, packages/web-pkg/src/composables/actions/files/useFileActionsSetReadme.ts, packages/web-pkg/tests/unit/composables/actions/files/useFileActionsSetReadme.spec.ts
- test case 1:
- test case 2:
- ...
=> Create hidden space folder if not present

packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/RoleDropdown.spec.ts.snap
- Fixes https://github.com/owncloud/web/issues/8954
=> Prevent share roles from line breaking

changelog/unreleased/enhancement-notifications-ocis, packages/web-runtime/src/components/Topbar/Notifications.vue
This reverts PR https://github.com/owncloud/web/pull/8912. See https://github.com/owncloud/web/issues/8976 for the reasoning behind it.
=> Revert "Handle 401 error when fetching notifications"

packages/design-system/src/styles/theme/helper.scss
- test case 1:
- test case 2:
- ...
=> Fix pill style

packages/web-runtime/src/helpers/settings.ts, packages/web-runtime/src/pages/account.vue, packages/web-runtime/tests/unit/pages/account.spec.ts
Follow-up for https://github.com/owncloud/web/pull/8972.
=> Improve settings interface names

.drone.env, tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature, tests/acceptance/pageObjects/FilesPageElement/filesList.js, tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js, tests/acceptance/pageObjects/personalPage.js, tests/acceptance/stepDefinitions/filesContext.js, tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature, tests/e2e/cucumber/steps/ui/public.ts, tests/e2e/support/api/graph/userManagement.ts, tests/e2e/support/api/userManagement.ts, tests/e2e/support/environment/userManagement.ts, tests/e2e/support/objects/app-admin-settings/users/actions.ts, tests/e2e/support/objects/app-admin-settings/users/index.ts
Backporting some test related adjustments from `master` to the `stable-7.0` branch...
=> [full-ci] Backport test adjustments

changelog/unreleased/bugfix-endless-lazy-loading-when-sorting, changelog/unreleased/bugfix-limit-concurrent-tus-requests, changelog/unreleased/enhancement-add-expiration-date-hint-to-public-links, changelog/unreleased/enhancement-add-notifications-setting, changelog/unreleased/enhancement-notifications-ocis, package.json, packages/design-system/src/components/OcSelect/OcSelect.vue, packages/design-system/src/composables/useIsVisible/index.ts, packages/design-system/src/styles/theme/helper.scss, packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue, packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue, packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue, packages/web-app-files/src/components/Spaces/SpaceHeader.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/RoleDropdown.spec.ts.snap, packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/DetailsAndEdit.spec.ts.snap, packages/web-runtime/src/components/Topbar/Notifications.vue, packages/web-runtime/src/helpers/settings.ts, packages/web-runtime/src/pages/account.vue, packages/web-runtime/src/services/uppyService.ts, packages/web-runtime/tests/unit/pages/account.spec.ts, sonar-project.properties
Merge `stable-7.0` @ `eb8ce91735af2e174e84c18c6412f757d062d58d` to `master`.
=> Merge `stable 7.0` to `master`

packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
- Fixes https://github.com/owncloud/web/issues/8995
=> Fix error log when de-selecting a file while right sidebar is open

packages/web-pkg/src/composables/sort/useSort.ts
- Fixes https://github.com/owncloud/web/issues/8981
- test case 1:
- test case 2:
- ...
=> Fix sorting with custom query params

packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/RoleDropdown.spec.ts.snap, packages/web-client/src/helpers/share/permission.ts
See https://github.com/owncloud/web/issues/8999
=> Wording rename custom permissions update to edit

packages/web-app-files/src/components/FilesList/KeyboardActions.vue, packages/web-app-files/src/components/FilesList/ResourceTable.vue, packages/web-app-files/tests/unit/components/FilesList/KeyboardActions.spec.ts
Fixing:
The Select all checkbox in the table header doesn't get checked
If you deselect one of the items again via click on the checkbox, the Select all checkbox gets checked (indicating that all items are selected) although one item is now deselected.
See https://github.com/owncloud/web/issues/8989#issuecomment-1538355977
- Fixes https://github.com/owncloud/web/issues/8989#issuecomment-1538355977
=> Bugfix: Keyboard shift + click selection selects file double 

tests/e2e/cucumber/steps/ui/adminSettings.ts
=> [tests-only][full-ci]f Fix e2e code lint

tests/e2e/cucumber/steps/ui/public.ts, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/link/index.ts, tests/e2e/support/objects/app-files/page/public.ts, tests/e2e/support/objects/app-files/resource/actions.ts
- added step for checking deleted link
related https://github.com/owncloud/web/issues/9004
=> e2e test. check deleted link

.drone.env, packages/web-app-files/src/components/SideBar/Shares/Links/CreateQuickLink.vue, tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature, tests/e2e/cucumber/steps/ui/links.ts, tests/e2e/support/objects/app-files/link/actions.ts
https://github.com/owncloud/ocis/pull/6271
https://github.com/owncloud/ocis/issues/6278
Sharing of project space root via public link does no longer work -> I changed test to enable e2e tests again
=> [test-only] e2e.Delete creating link to space step

dev/docker/oc10.entrypoint.sh, tests/drone/setup-server-and-app.sh, tests/e2e/cucumber/features/smoke/personalSpacePagination.feature, tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature, tests/e2e/cucumber/steps/api.ts, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts
This PR backports: https://github.com/owncloud/web/pull/9008
=> [tests-only][full-ci]Backport/tests/e2e test pagination files

tests/e2e/cucumber/features/smoke/spaces/pagination.ocis.feature, tests/e2e/cucumber/steps/api.ts, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts
- Part of: https://github.com/owncloud/ocis/issues/5013
- locally
- CI
=> [tests-only]Add tests for pagination in spaces

tests/e2e/cucumber/features/smoke/spaces/pagination.ocis.feature, tests/e2e/cucumber/steps/api.ts, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts
Forward port: https://github.com/owncloud/web/pull/9040 
part of: https://github.com/owncloud/ocis/issues/5013
=> [tests-only][full-ci]Add tests for pagination in spaces

.drone.env
This PR bumps ocis commit id for tests.
part of : https://github.com/owncloud/QA/issues/809
=> [tests-only][full-ci] Bump commit id for tests 

.drone.env, changelog/unreleased/enhancement-disable-change-password-via-capability, changelog/unreleased/enhancement-disable-create-and-delete-users-via-capabilities, packages/web-app-admin-settings/src/composables/actions/users/useUserActionsDelete.ts, packages/web-app-admin-settings/src/views/Users.vue, packages/web-app-admin-settings/tests/unit/components/Users/SideBar/EditPanel.spec.ts, packages/web-app-admin-settings/tests/unit/composables/actions/users/useUserActionsDelete.spec.ts, packages/web-app-admin-settings/tests/unit/composables/actions/users/useUserActionsEditLogin.spec.ts, packages/web-app-admin-settings/tests/unit/views/Users.spec.ts, packages/web-pkg/src/composables/capability/useCapability.ts, packages/web-runtime/src/pages/account.vue, packages/web-runtime/tests/unit/pages/account.spec.ts
- Fixes https://github.com/owncloud/web/issues/9060
- Fixes https://github.com/owncloud/enterprise/issues/5715
- test case 1:
- test case 2:
- ...
=> Additional users env vars

tests/e2e/cucumber/features/smoke/upload.feature, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/page/public.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts, tests/e2e/support/objects/app-files/resource/utils.ts, tests/e2e/support/utils/dragDrop.ts
Added e2e test for uploading files via drag and drop action
Part of https://github.com/owncloud/ocis/issues/5013
- x ] Tests
=> [tests-only][full-ci] Add files drop upload e2e tests

tests/e2e/cucumber/features/smoke/upload.feature, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/page/public.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts, tests/e2e/support/objects/app-files/resource/utils.ts, tests/e2e/support/utils/dragDrop.ts
forward port https://github.com/owncloud/web/pull/9065
=> [tests-only][full-ci] Add files drop upload e2e tests (#9065)

changelog/unreleased/enhancement-show-detailed-error-messages-while-upload-fails, packages/web-runtime/src/components/UploadInfo.vue, packages/web-runtime/src/helpers/additionalTranslations.ts
- Fixes https://github.com/owncloud/web/issues/9002
- test case 1:
- test case 2:
- ...
=> Handle upload errors

changelog/unreleased/enhancement-search-advanced-button, changelog/unreleased/enhancement-search-breadcrumb, packages/design-system/src/components/OcSearchBar/OcSearchBar.spec.ts, packages/design-system/src/components/OcSearchBar/OcSearchBar.vue, packages/web-app-files/src/components/Search/List.vue, packages/web-app-files/tests/unit/components/Search/List.spec.ts, packages/web-app-search/src/portals/SearchBar.vue, packages/web-app-search/tests/unit/portals/SearchBar.spec.ts
- Fixes https://github.com/owncloud/web/issues/9072
=> Add search page breadcrumbs and advanced search icon

changelog/unreleased/bugfix-preview-app-mimetypes, packages/web-app-preview/src/App.vue
- Fixes https://github.com/owncloud/web/issues/9050
=> Fix preview app not detecting all supported mime types

changelog/unreleased/enhancement-enable-download-on-spaces, packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue, packages/web-app-files/src/components/Spaces/SpaceContextActions.vue, packages/web-app-files/src/composables/actions/files/useFileActionsDownloadArchive.ts, pnpm-lock.yaml
- Fixes https://github.com/owncloud/web/issues/9056
- test case 1:
- test case 2:
- ...
=> Enable download action on spaces (archive)

tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/api/graph/spaces.ts, tests/e2e/support/objects/account/actions.ts, tests/e2e/support/objects/account/index.ts, tests/e2e/support/objects/app-admin-settings/general/index.ts, tests/e2e/support/objects/app-admin-settings/groups/index.ts, tests/e2e/support/objects/app-admin-settings/spaces/index.ts, tests/e2e/support/objects/app-admin-settings/users/index.ts, tests/e2e/support/objects/app-files/link/index.ts, tests/e2e/support/objects/app-files/page/public.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts, tests/e2e/support/objects/app-files/share/index.ts, tests/e2e/support/objects/app-files/spaces/index.ts, tests/e2e/support/objects/app-files/trashbin/index.ts
Refactor e2e test code
- remove unnecessary async
- import all with `*` at once
=> [tests-only] Refactor: remove unnecessary async and use import all 

tests/e2e/cucumber/features/smoke/link.feature, tests/e2e/cucumber/features/smoke/share.oc10.feature, tests/e2e/cucumber/steps/ui/accountMenu.ts, tests/e2e/cucumber/steps/ui/adminSettings.ts, tests/e2e/cucumber/steps/ui/public.ts, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/cucumber/steps/ui/session.ts, tests/e2e/cucumber/steps/ui/shares.ts, tests/e2e/cucumber/steps/ui/spaces.ts, tests/e2e/support/environment/actor/actors.ts, tests/e2e/support/objects/account/actions.ts, tests/e2e/support/objects/app-admin-settings/groups/actions.ts, tests/e2e/support/objects/app-admin-settings/spaces/actions.ts, tests/e2e/support/objects/app-admin-settings/users/actions.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/share/collaborator.ts, tests/e2e/support/objects/app-files/share/utils.ts, tests/e2e/support/objects/app-files/spaces/actions.ts
Refactored step definitions:
- to use simpler expression (cucumber expression)
- remove unwanted word/character match
- remove unnecessary await
=> [tests-only] Refactor step definitions

tests/e2e/cucumber/features/smoke/link.feature, tests/e2e/cucumber/features/smoke/share.oc10.feature, tests/e2e/cucumber/steps/ui/accountMenu.ts, tests/e2e/cucumber/steps/ui/adminSettings.ts, tests/e2e/cucumber/steps/ui/public.ts, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/cucumber/steps/ui/session.ts, tests/e2e/cucumber/steps/ui/shares.ts, tests/e2e/cucumber/steps/ui/spaces.ts, tests/e2e/support/environment/actor/actors.ts, tests/e2e/support/objects/account/actions.ts, tests/e2e/support/objects/app-admin-settings/groups/actions.ts, tests/e2e/support/objects/app-admin-settings/spaces/actions.ts, tests/e2e/support/objects/app-admin-settings/users/actions.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/share/collaborator.ts, tests/e2e/support/objects/app-files/share/utils.ts, tests/e2e/support/objects/app-files/spaces/actions.ts
Forward port PR https://github.com/owncloud/web/pull/9109
=> [tests-only] Refactor step definitions (#9109)

tests/e2e/cucumber/steps/ui/session.ts, tests/e2e/support/objects/app-admin-settings/general/actions.ts, tests/e2e/support/objects/app-admin-settings/page/general.ts, tests/e2e/support/objects/app-admin-settings/page/groups.ts, tests/e2e/support/objects/app-admin-settings/page/spaces.ts, tests/e2e/support/objects/app-admin-settings/page/users.ts, tests/e2e/support/objects/app-admin-settings/spaces/actions.ts, tests/e2e/support/objects/app-admin-settings/users/actions.ts, tests/e2e/support/objects/app-files/link/actions.ts, tests/e2e/support/objects/app-files/page/public.ts, tests/e2e/support/objects/app-files/page/shares/withMe.ts, tests/e2e/support/objects/app-files/page/spaces/projects.ts, tests/e2e/support/objects/app-files/page/trashbin/overview.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/resource/index.ts, tests/e2e/support/objects/app-files/resource/utils.ts, tests/e2e/support/objects/app-files/share/collaborator.ts, tests/e2e/support/objects/app-files/share/utils.ts, tests/e2e/support/objects/app-files/spaces/actions.ts, tests/e2e/support/objects/runtime/application.ts
Forward port PR https://github.com/owncloud/web/pull/9120
=> [tests-only][full-ci] Replace page.waitForSelector with locator.waitFor (#9120)

changelog/unreleased/bugfix-notifications-link-overflow, packages/web-runtime/src/components/Topbar/Notifications.vue
See https://github.com/owncloud/web/issues/9053
- Fixes https://github.com/owncloud/web/issues/9053
=> Bugfix: Long links in notifications are cut off

.drone.star
Split oCIS e2e pipeline into two pipelines
- `oCIS-1` `~10mins`: features from `features/journeys/*.feature` and `features/smoke/*.feature`
- `oCIS-2` `~6mins`: features from `features/smoke/spaces/*.feature` and `features/smoke/admin-settings/*.feature`
NOTE: we need to be careful when adding new subfolders in the `features` folder. new subfolders MUST be added in the `featurePaths` pipeline config to make it run in the CI
```py
...
"featurePaths": [
"tests/e2e/cucumber/features/smoke/{spaces,admin-settings}/*[!.oc10].feature",
"tests/e2e/cucumber/features/<new-sub-folder>"
],
...
```
- Fixes https://github.com/owncloud/web/issues/9107
=> [tests-only] Split ocis e2e tests pipeline

.drone.star
Forward port PR https://github.com/owncloud/web/pull/9149
=> [tests-only] Split ocis e2e tests into smoke and spaces (#9149)

tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
Backport of PR: https://github.com/owncloud/web/pull/9132
=> [tests-only][full-ci]Backport admin manage space

tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature, tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature
Backport of PR https://github.com/owncloud/web/pull/9154
=> [full-ci] [tests-only] Refactor steps order

docker-compose.yml
Fixes error
```
invalid interpolation format for services.traefik.entrypoint.[]: "[ -f /certificates/server.key ] && ./entrypoint.sh $@ || (apk add openssl && openssl req -subj '/CN=ocis.test' -x509 -sha256 -nodes -days 3650 -newkey rsa:2048 -keyout /certificates/server.key -out /certificates/server.crt && chmod -R 777 /certificates && ./entrypoint.sh $@)". You may need to escape any $ with another $
```
on GNU/Linux 
- test case 1:
- test case 2:
- ...
=> escape $ on docker compose traefik entrypoint

packages/web-app-files/src/composables/actions/files/useFileActionsDownloadArchive.ts
- Fixes https://github.com/owncloud/web/issues/9164
- test case 1:
- test case 2:
- ...
=> Avoid download multiple spaces as archive

dev/docker/ocis.idp.config.yaml, tests/e2e/cucumber/features/smoke/spaces/internalLink.ocis.feature, tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature, tests/e2e/cucumber/steps/ui/links.ts, tests/e2e/support/objects/app-files/link/actions.ts
=> [test-only] Returning space link test

changelog/unreleased/bugfix-app-loading, packages/web-runtime/src/container/application/index.ts
We don't want to backport the whole PR #9079 from master because it's too invasive, but backporting the injections gives us some level of compatibility already, which is good enough for now
- test case 1:
- test case 2:
- ...
=> Backport app dependency injections from #9079

tests/e2e/support/objects/app-admin-settings/groups/actions.ts, tests/e2e/support/objects/app-admin-settings/users/actions.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/share/actions.ts, tests/e2e/support/objects/app-files/share/collaborator.ts, tests/e2e/support/objects/app-files/spaces/actions.ts, tests/e2e/support/objects/runtime/application.ts
Refactor the order of action and waitForResponse in Promise.all and removed unnecessary awaits
=> [tests-only] Make proper use of Promise.all

packages/web-integration-oc10/appinfo/info.xml
Port of PR #9251 from `master` to `stable-7.0`
CI
=> bump info.xml to 7.0.2 -- it still said 6.0.0 all the time since 6.0.0

tests/e2e/support/objects/app-admin-settings/groups/actions.ts, tests/e2e/support/objects/app-admin-settings/users/actions.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/share/actions.ts, tests/e2e/support/objects/app-files/share/collaborator.ts, tests/e2e/support/objects/app-files/spaces/actions.ts, tests/e2e/support/objects/runtime/application.ts
Port PR https://github.com/owncloud/web/pull/9116
=> [tests-only] Make proper use of Promise.all (#9116)

deployments/examples/ocis_web/config/ocis/app-registry.yaml, deployments/examples/ocis_web/config/ocis/proxy.yaml, deployments/examples/ocis_web/config/onlyoffice/entrypoint-override.sh, deployments/examples/ocis_web/config/onlyoffice/local.json, deployments/examples/ocis_web/docker-compose.yml
Ports changes from the ocis_wopi deployment example in oCIS
Keep the deployment examples working
- docker-compose up -d
=> basic maintenance for the deployment example

packages/design-system/package.json, packages/eslint-config/package.json, packages/prettier-config/package.json, packages/web-pkg/src/composables/router/types.ts, pnpm-lock.yaml
... to support the typescript satisfies operator
Update `prettier` and `@typescript-eslint` packages.
I want to be able to use the `satisfies` operator in TypeScript which requires `prettier >= 2.8`
- test case 1:
- test case 2:
- ...
=> Update prettier and typescript-eslint packages

docker-compose.yml
Certain requests (archiver e.g.) won't work in vite dev mode otherwise.
=> fix: set access-controll-expose headers to * to fix requests in vite

changelog/unreleased/enhancement-cloud-import, packages/web-runtime/src/services/uppyService.ts
Seems to be a regression of https://github.com/owncloud/web/pull/9173.
- Fixes https://github.com/owncloud/web/issues/9202
=> fix: resume upload after cancel

tests/e2e/cucumber/features/smoke/uploadResumable.ocis.feature, tests/e2e/support/objects/app-files/resource/actions.ts
Forward Port this PR https://github.com/owncloud/web/pull/9190 from `stable-7.0` to `master` branch
=> [tests-only][full-ci]Uncomment steps for pause and resume upload

changelog/unreleased/enhancement-add-batch-actions-to-search-result-list, packages/web-app-files/src/components/AppBar/CreateSpace.vue, packages/web-app-files/src/components/Search/List.vue, packages/web-app-files/src/composables/actions/files/useFileActionsCopy.ts, packages/web-app-files/tests/unit/components/Search/List.spec.ts, packages/web-app-files/tests/unit/composables/actions/files/useFileActionsCopy.spec.ts, packages/web-app-files/tests/unit/composables/actions/files/useFileActionsDelete.spec.ts, packages/web-app-files/tests/unit/composables/actions/files/useFileActionsDownloadArchive.spec.ts, packages/web-pkg/tests/unit/composables/spaces/useGetMatchingSpace.spec.ts
- test case 1:
- test case 2:
- ...
=> [full-ci] search batch actions follow up

changelog/unreleased/enhancement-access-denied-page-change-message, packages/design-system/src/components/OcInfoDrop/OcInfoDrop.vue, packages/web-app-files/src/components/AppBar/AppBar.vue, packages/web-app-files/src/components/Spaces/SpaceHeader.vue, packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/SpaceMembers.spec.ts.snap, packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap, packages/web-pkg/src/components/ViewOptions.vue, packages/web-runtime/src/components/SidebarNav/SidebarNav.vue, packages/web-runtime/src/container/bootstrap.ts, packages/web-runtime/src/helpers/theme.ts, packages/web-runtime/src/pages/accessDenied.vue, packages/web-runtime/src/store/config.ts, packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.ts.snap, packages/web-runtime/tests/unit/helpers/theme.spec.ts, packages/web-runtime/tests/unit/store/config.spec.ts, tests/acceptance/pageObjects/loginErrorPage.js
Forward port `stable-7.0` to master.
=> Merge stable 7.0 to master

docs/getting-started.md
FYI @fschade @diocas @elizavetaRa @labkode
=> [docs-only] Add runningOnEos note && document custom script and styles

tests/e2e/cucumber/features/smoke/fullTextSearch.ocis.feature, tests/e2e/cucumber/steps/api.ts, tests/e2e/support/api/davSpaces/index.ts, tests/e2e/support/api/davSpaces/spaces.ts, tests/e2e/support/api/graph/spaces.ts, tests/e2e/support/api/graph/utils.ts
This PR adds step implementation of assigning tag on resources using API.
```
And "Alice" adds the following tags for the following resources using API
| resource        | tags      |
| fileToShare.txt | alice tag |
```
- https://github.com/owncloud/web/issues/9157
=> [tests-only] [full-ci] added api step to assign tag on resources

changelog/unreleased/enhancement-search-fulltext-filter, packages/web-app-files/src/router/common.ts
- Fixes https://github.com/owncloud/web/issues/9242
- test case 1:
- test case 2:
- ...
=> Fix fulltext search not persisted after closing editor

docs/getting-started.md
fix wrong docs  hosts ip, thx for the hint @grimmoc
=> fix: fix docs hosts address

packages/web-app-pdf-viewer/src/App.vue
- Fixes   https://github.com/owncloud/web/issues/9309
- test case 1:
- test case 2:
- ...
=> only load pdf files

packages/web-app-files/src/index.ts
- Fixes https://github.com/owncloud/web/issues/8017
- test case 1:
- test case 2:
- ...
=> Disable deleted files nav item if trash bin app is disabled in oc10

packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue, packages/web-app-files/src/index.ts
If the share role is not defined in frontend but is technically possible like with permissions 3, we show 'Select a role' and fix that web breaks (exception)
- Fixes https://github.com/owncloud/web/issues/7164
- test case 1:
- test case 2:
- ...
=> Don't break if Share role is not defined in frontend 

.drone.star
Remove special PR-based drone actions from CI to enable running pipelines again.
=> [full-ci] ci: remove special PR-based drone actions from CI

tests/e2e/cucumber/features/smoke/languageChange.ocis.feature, tests/e2e/cucumber/steps/ui/accountMenu.ts, tests/e2e/support/objects/account/actions.ts, tests/e2e/support/objects/account/index.ts
=> [test-only] e2e test. change language

.drone.env, .drone.star
Bump ocis commit id to latest.
- Part of https://github.com/owncloud/QA/issues/815
- :robot:
=> [full-ci] [tests-only] Remove special PR-based drone actions from CI

packages/web-app-files/src/components/AppBar/CreateSpace.vue
- test case 1:
- test case 2:
- ...
=> Show message after space creation

changelog/unreleased/bugfix-space-editors-see-empty-trashbin-and-delete-actions-in-space-trashbin, packages/web-app-files/src/composables/actions/files/useFileActionsDelete.ts, packages/web-app-files/src/composables/actions/files/useFileActionsEmptyTrashBin.ts, packages/web-client/src/helpers/resource/types.ts, packages/web-client/src/helpers/space/functions.ts
- Fixes https://github.com/owncloud/web/issues/9385
- test case 1:
- test case 2:
- ...
=> Only allow space managers to empty trash bin

changelog/unreleased/enhancement-tag-comma-separation, packages/web-app-files/src/components/SideBar/TagsPanel.vue
Tags containing commas are now split up into separate tags on client side to match server side processing behaviour.
- implements https://github.com/owncloud/web/issues/9224
=> 9224 comma separation

packages/web-runtime/src/components/UploadInfo.vue
Upload bar spinner didn't change to pause same as files in detail.
Pause icon has been added to display instead of spinner if uploads are paused.
- Fixes https://github.com/owncloud/web/issues/9086
Keeping consistency of UI
=> Adding icon to paused upload state

tests/e2e/support/objects/app-files/link/actions.ts, tests/e2e/support/objects/app-files/share/actions.ts, tests/e2e/support/objects/app-files/share/utils.ts
Reducing unnecessary waits from the e2e tests
=> [tests-only] Reduce unnecessary waits

.drone.star
removed downstream step from CI as done in master https://github.com/owncloud/web/commit/10bbf6db482730cc72bf3fda7acdeac31e693081
=> ci: remove downstream stream step from ci

packages/web-pkg/src/composables/spaces/useGetMatchingSpace.ts
- Fixes https://github.com/owncloud/web/issues/9387
- test case 1:
- test case 2:
- ...
=> Fix spaces not in computed

packages/web-app-files/src/helpers/resources.ts
When combining shares, it takes the first time that came from the server, which doesn't have to be the latest. 
Condition checking for a later time has been added to replace the previous time.
- Fixes https://github.com/owncloud/web/issues/8496
=> "Shared on" set the latest time

changelog/unreleased/enhancement-ambiguation-for-url-view-mode-params, packages/web-app-files/src/components/AppBar/AppBar.vue, packages/web-app-files/src/composables/resourcesViewDefaults/useResourcesViewDefaults.ts, packages/web-app-files/src/views/spaces/GenericSpace.vue, packages/web-app-files/src/views/spaces/Projects.vue, packages/web-app-files/tests/unit/components/AppBar/__snapshots__/AppBar.spec.ts.snap, packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap, packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap, packages/web-pkg/src/components/ViewOptions.vue
show tiles view in projects spaces per default, changed route+storage params to be different from one another 
- Implements https://github.com/owncloud/web/issues/9337
=> 9337 tiles view for projects spaces + ambiguation for URL view mode params 

packages/design-system/changelog/unreleased/enhancement-add-dismiss-button-to-oc-notification-message-component, packages/design-system/src/components/OcNotificationMessage/OcNotificationMessage.vue
- Fixes https://github.com/owncloud/web/issues/9420
- test case 1:
- test case 2:
- ...
=> Add dismiss button to oc-notification-message

.drone.env, .drone.star, docker-compose.yml, tests/acceptance/features/webUIFilesSearch/search.feature, tests/e2e/cucumber/features/smoke/fullTextSearch.ocis.feature, tests/e2e/cucumber/features/smoke/search.ocis.feature, tests/e2e/cucumber/features/smoke/searchProjectSpace.ocis.feature, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/support/objects/app-files/resource/actions.ts
- added test for using `current folder` filter
=> e2e test. search using current folder filter

.drone.env, .drone.star, docker-compose.yml, tests/acceptance/features/webUIFilesSearch/search.feature, tests/e2e/cucumber/features/smoke/fullTextSearch.ocis.feature, tests/e2e/cucumber/features/smoke/search.ocis.feature, tests/e2e/cucumber/features/smoke/searchProjectSpace.ocis.feature, tests/e2e/cucumber/steps/ui/resources.ts, tests/e2e/cucumber/steps/ui/search.ts, tests/e2e/support/objects/app-files/link/actions.ts, tests/e2e/support/objects/app-files/resource/actions.ts, tests/e2e/support/objects/app-files/search/actions.ts, tests/e2e/support/objects/app-files/search/index.ts, tests/e2e/support/objects/app-files/share/actions.ts, tests/e2e/support/objects/app-files/share/utils.ts
port #9427 #9398 to stable-7.1
=> Port e2e tests #9427 #9398

tests/e2e/cucumber/features/smoke/search.ocis.feature, tests/e2e/cucumber/steps/ui/session.ts, tests/e2e/support/objects/runtime/application.ts
Porting https://github.com/owncloud/web/pull/9433 and https://github.com/owncloud/web/pull/9440
=> [tests-only][e2e] Fetch notifications by page reload - do not wait

packages/web-app-files/src/composables/actions/files/useFileActionsEmptyTrashBin.ts
Check if files exist to display "Empty trash bin" action.
- Fixes https://github.com/owncloud/web/issues/9431
=> Display empty trash bin if deleted files

.drone.env
Bump ocis latest commit to web-master
related issue https://github.com/owncloud/QA/issues/821
=> [tests-only][full-ci] bump latest ocis commit to web master

.drone.env
Bump ocis latest commit to web-stable-7.1
related issue https://github.com/owncloud/QA/issues/821
=> [tests-only][full-ci] bump latest ocis commit to web stable

changelog/unreleased/enhancement-cloud-import, packages/web-app-importer/src/extensions.ts, packages/web-app-importer/tests/unit/extensions.spec.ts
- Fixes https://github.com/owncloud/web/issues/9486
=> fix: respect supportedClouds config

packages/web-app-files/src/views/FilesDrop.vue
HTML element is not available as target due to load. Watching for load to initialize drop zone.
In case there would be need to invoke load again (which would loose possibility of drop zone), it will be removed and initialized again after loading is done.
- Fixes https://github.com/owncloud/web/issues/9464
=> Initialize Drop Target after load time

packages/web-pkg/src/composables/keyboardActions/useKeyboardActions.ts, tests/e2e/support/objects/app-files/resource/actions.ts
Making primary key lowercase disabled keyboard arrows, rather than comparing 2 lowercased values I've kept the case sensitivity and made keys in test lowercase
=> removing toLowerCase useKeyboardActions, fixing test

docker-compose.yml, package.json, packages/web-app-importer/l10n/.tx/config, packages/web-runtime/src/services/uppyService.ts, pnpm-lock.yaml
Adds missing translations fro the cloud importer.
=> Cloud importer translations

packages/web-runtime/src/pages/resolvePublicLink.vue
…ource is deleted or disabled (space)
- Fixes https://github.com/owncloud/web/issues/9497
- test case 1:
- test case 2:
- ...
=> Show error message while accessing a public link which originated resource is deleted or disabled (space)

packages/web-pkg/src/apps/types.ts
The issue occurred because we now have translations in the importer app.
=> fix: ApplicationTranslations type

packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue, packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
Added breakpoints which make width 100% for smaller screens and keep 400px for larger screens
- Fixes https://github.com/owncloud/web/issues/9321
Keeping mobile responsive
=> Share links, Roles, mobile view fix

.drone.env
Bump latest ocis commit id to web `master`
Part of: https://github.com/owncloud/QA/issues/821
=> [tests-only][full-ci] bumped ocis commit id for tests

packages/web-client/src/graph.ts, packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDelete.ts, packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDisable.ts, packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsDisable.spec.ts
- Fixes https://github.com/owncloud/web/issues/6394
- test case 1:
- test case 2:
- ...
=> Move purge header into graph.ts for disable / delete space

docs/deployments/oc10-app.md
The search app is missing from the documented example. That is why I never see a search bar in my setups. :-(
The config.json snippet hear lists
```
"apps" : [
"files",
"preview",
"draw-io"
],
```
It should include `search` - 
As is, the the product does not have the search feature, described here in the documentation.
```
"options": {
"hideSearchBar": false
},
```
Is that expected?
=> [QA] Update example config.json in oc10-app.md

tests/e2e/cucumber/features/smoke/fullTextSearch.feature
Bug https://github.com/owncloud/web/issues/9428 was fixed so enabling this test
=> [tests-only] Enable passing e2e test

CHANGELOG.md
Follow-up after https://github.com/owncloud/web/pull/9551.
=> chore: update CHANGELOG.md for v7.0.3

packages/design-system/src/components/OcSelect/OcSelect.vue
- test case 1:
- test case 2:
- ...
=> Fix faulty import

changelog/unreleased/enhancement-tags-form, packages/web-app-files/src/components/SideBar/TagsPanel.vue
- Fixes (https://github.com/owncloud/web/pull/9525#pullrequestreview-1558711045)
- test case 1:
- test case 2:
- ...
=> fixed tag not showing up after removal when using "x" button

tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
part of https://github.com/owncloud/web/issues/9571
=> [test-only]open link in authenticated context in the project space

packages/web-app-files/src/components/Search/List.vue, packages/web-pkg/src/components/ItemFilter.vue
See https://github.com/owncloud/web/issues/9281
- Fixes https://github.com/owncloud/web/issues/9281
=> Close on click stable fix

.drone.star, tests/drone/app-registry.yaml, tests/drone/onlyoffice/local.json, tests/drone/wopiserver/wopiserver.conf, tests/e2e/cucumber/features/smoke/app-provider/officeSuites.feature, tests/e2e/cucumber/steps/api.ts, tests/e2e/support/objects/app-files/resource/actions.ts
This PR make the test run in CI  merged at https://github.com/owncloud/web/pull/9265 for app-provider office suites.
https://github.com/owncloud/web/issues/9191
=> [tests-only][full-ci]setup app provider in `CI`

packages/web-app-files/src/helpers/contextualHelpers.ts, packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap, packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/SpaceMembers.spec.ts.snap
- test case 1:
- test case 2:
- ...
=> ct perm link

dev/docker/ocis-appprovider-onlyoffice/entrypoint-override.sh, dev/docker/ocis.entrypoint.sh, dev/docker/ocis/app-registry.yaml, dev/docker/onlyoffice/entrypoint-override.sh, dev/docker/onlyoffice/local.json, dev/docker/wopiserver/entrypoint-override.sh, dev/docker/wopiserver/wopiserver.conf.dist, docker-compose.yml, tests/e2e/cucumber/features/smoke/app-provider/officeSuites.feature, tests/e2e/cucumber/steps/ui/public.ts, tests/e2e/support/objects/app-files/page/public.ts, tests/e2e/support/objects/app-files/resource/actions.ts
Backport of PR https://github.com/owncloud/web/pull/9265
=> [tests-only][full-ci]Added docker compose for `colabora` and `onlyoffice`

.drone.star, tests/drone/app-registry.yaml, tests/drone/onlyoffice/local.json, tests/drone/wopiserver/wopiserver.conf, tests/e2e/cucumber/features/smoke/app-provider/officeSuites.feature, tests/e2e/support/objects/app-files/resource/actions.ts
Backport of PR - https://github.com/owncloud/web/pull/9373
=> [tests-only][full-ci]Back portsetup app provider in `CI`
