changelog/unreleased/enhancement-share-recipients-number
docs/getting-started.md
packages/web-app-files/src/components/SideBar/Shares/Collaborators/NewCollaborator.vue
packages/web-runtime/src/store/config.js

the oc-select or share recipients only had only shown 200 users even if the backend has way more. This introduces a option to decide in configuration how many items should be there.
- Fixes #5499
let the user decide how many users should be shown in the recipients dropdown
- unit tests
- local oc10 installation with openLDAP and 1k users

add option to define how many share recipients should be shown

---

changelog/unreleased/enhancement-load-only-opened-panels
packages/web-app-files/src/components/SideBar/SideBar.vue

Do not load panels in the Files extension sidebar until they are opened.
I've chosen here a slightly different approach than via events. I would still like to use animation events listeners instead of the observer but in a separate PR.

[full-ci] feat: load only opened panels

---

changelog/unreleased/enhancement-filestable-dropdown-actions
packages/web-app-files/src/components/FilesList/ContextActions.vue
packages/web-app-files/src/mixins/actions/createPublicLink.js
packages/web-app-files/src/mixins/actions/download.js
packages/web-app-files/src/mixins/actions/favorite.js
packages/web-app-files/src/mixins/actions/navigate.js
packages/web-app-files/src/mixins/actions/rename.js
packages/web-app-files/src/mixins/actions/restore.js
packages/web-app-files/src/mixins/actions/showActions.js
packages/web-app-files/src/mixins/actions/showDetails.js
packages/web-app-files/src/mixins/actions/showShares.js
packages/web-app-files/src/quickActions.js
packages/web-app-files/tests/unit/components/FilesList/ContextActions.spec.js
tests/acceptance/pageObjects/FilesPageElement/appSideBar.js
tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js

This PR restructures the context menu to not just list the actions from the right sidebar but instead to bring the structure that was proposed in https://github.com/owncloud/web/issues/5160
- Fixes https://github.com/owncloud/web/issues/5160
- test case 1:
- test case 2:
- ...

[full-ci] Restructure context menu items

---

.drone.env
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIRenameFiles/renameFiles.feature
tests/acceptance/features/webUIRenameFolders/renameFolders.feature

Now that https://github.com/owncloud/ocis/pull/2334 has been merged, the invalid file/folder name rules are:
- file and folder names containing a backslash `\` are invalid on both oC10 and OCIS
- .htaccess is invalid on oC10 but valid on OCIS
Sort out the acceptance test scenarios so that they test these combinations.
- Fixes #5595 
CI

[tests-only] [full-ci] Adjust invalid file and folder name tests

---

packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkActions.spec.js

- added unit tests for `LinkActions` component from `web-app-files` package
- unit tests coverage
- 💇🏼‍♂️ 
- 🤖

[unit-tests] Added unit tests for link actions component

---

changelog/unreleased/bugfix-load-folder-in-media-viewer
packages/web-app-media-viewer/src/App.vue
packages/web-app-media-viewer/src/mixins/loader.js

[full-ci] fix: load folder in media viewer

---

.drone.star

if the PR title has `unit-tests-only` then only the minimum pipelines will be executed in CI
Minimum Pipelines for unit-tests-only: 
- lint-test
- stop-recent-builds
- unit-and-integration-tests
- check-starlark
- Fixes https://github.com/owncloud/web/issues/5421
Optimize the CI build duration
- test environment: CI

[unit-tests-only] Run minimum pipelines for unit tests only PRs

---

.drone.star
Makefile

Checks for `[docs-only]` in PR title and if found, unit and acceptance test pipelines won't run
- part of https://github.com/owncloud/web/issues/5637
- test environment: CI

[docs-only] Do not run unit and acceptance test pipelines for docs only PRs

---

.drone.star

the `stop-recent-builds` pipeline fails for forks because drone.owncloud.com doesn't know that repo (comming from `ctx.build.source_repo`). Instead we always need to use `ctx.repo.slug` since this acts as identifier for the target repo in drone.
Example
PR from fork to oCIS failed in this step:
```
alpine: Pulling from drone/cli
--
2 | Digest: sha256:29517295f5c1dd9ef78645f08afe360a47bc3e2bbac70c7dd755c61551b4202f
3 | Status: Image is up to date for drone/cli:alpine
4 | + drone build ls ishank011/ocis --status running > /drone/src/recentBuilds.txt
5 | client error 404: {"message":"Not Found"
```
- same as https://github.com/owncloud/ocis/pull/2368

fix stop-recent-builds for forks

---

changelog/unreleased/bugfix-escape-file-path-in-media-viewer
packages/web-app-media-viewer/src/App.vue
packages/web-app-media-viewer/src/mixins/loader.js

We've started escaping the file name in the Media viewer extension so that a file with special characters in the name can still be loaded.
- fixes #5593

[full-ci] fix: escape image name in media viewer

---

packages/web-app-files/tests/unit/mixins/resources.spec.js

added unit tests for `resources` mixin
- Part of #5217 
- 🤖

Added unit tests for resources mixin

---

.drone.env
tests/acceptance/features/webUIUpload/upload.feature

oCIS PR https://github.com/owncloud/ocis/pull/2385 has just been merged. It updates reva in oCIS.
Bump the commit id here in `owncloud/web` so that we test against that latest oCIS.
`webUIUpload/upload.feature:99` was failing intermittently. I have tagged it `@disablePreviews` like other similar upload-overwrite scenarios.
Part of issue https://github.com/owncloud/QA/issues/684
CI

[full-ci] [tests-only] Bump commit id for oCIS

---

changelog/unreleased/change-enable-live-reload-for-themes
rollup.config.js

Owncloud has done a great job allowing customisations of themes without needing to make modifications directly to the **owncloud-design-system** 👍 
This PR allows you to live reload in local development mode as you go through and change any theme(s) you are working on.  (Eg. changing the colour of `swatch-brand-default`.)
My understanding for why it does not work by default is because the application will load the theme file via **fetch** at runtime from the location defined in the `config.json` which, typically, would be defined as follows (on the same domain as a relative url):
```
"theme": "themes/aarnet/theme.json",
```
This content is generated from `packages/web-runtime/themes/<theme_name>/theme.json` and compiled by rollup into the `dist` folder, but because it's not part of the …

chore: enable live reload for changes to themes

---

changelog/unreleased/bugfix-handle-errors-when-loading-themes
packages/web-runtime/src/helpers/theme.js
packages/web-runtime/tests/unit/helpers/theme.spec.js

There are multiple conditions where a custom theme will fail to load eg.
1. If the file extension does not end in `.json`
2. If the file is not found
3. If there is any other error attempting to fetch the file from network
4. If the file is not a valid JSON file format
Currently only (1), (2) and (3) are handled by returning the default owncloud extension.
This fix adds error handling for (4) and also refactors the code a little.  Currently (4) will break the application with:
```
web-runtime.js:5504 SyntaxError: Unexpected token d in JSON at position 584
``` 
as there is no catch around the json parsing.
With the fix, it will show the following on the console:
```
web-runtime.js:5262 Failed to load theme 'themes/aarnet/theme.json' is not a valid JSON file, using default theme.
```
This …

fix: handle loading and parsing errors when loading themes

---

packages/web-app-files/tests/unit/helpers/permissions.spec.js

Added unit tests for permissions helper
- Part of #5236 
🤖

Added unit tests for permissions helper

---

.drone.star
tests/drone/if-diff-has-unit-tests-only.sh

- do not set unit-tests mode if diff contains nothing ( used for nightly builds )
- only run diff calculation for `pull_requests` events
- 🤖

[CI] Fix diff calculation for drone builds

---

changelog/unreleased/enhancement-signout-icon
packages/web-runtime/src/components/UserMenu.vue

Based on user feedback that @rpocklin received and forwarded to us, this PR changes the signout icon in the personal menu. Previous one was not clear enough. See screenshots for before and after comparison.
UX
- CI

Change signout icon

---

changelog/unreleased/enhancement-refresh-list-via-breadcrumbs
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/views/Personal.vue
packages/web-app-files/src/views/PublicFiles.vue
packages/web-app-files/tests/integration/specs/appBar.spec.js

[full-ci] feat: refresh list on breadcrumb click

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUILogin/openidLogin.feature

Scenario: try to login with valid username and invalid password
That scenario had steps demonstrating previously bad behavior. This fixes the scenario to expect the correct behavior, and it passes.
CI

[tests-only] [full-ci] Fix openIdLogin scenario for login with invalid password

---

changelog/4.1.0_2021-08-19/bugfix-load-folder-in-media-viewer
packages/web-app-media-viewer/src/mixins/loader.js

mediaViewer still used davProperties from component scope, updated to
use shared DavProperties

[full-ci] fix(media-viewer): fix davProperties

---

packages/web-app-files/tests/unit/views/Favorites.spec.js
packages/web-app-files/tests/unit/views/views.setup.js

Favorites spec uses hard coded selecotors and used the `mount` method in every scenario which we can manage a little bit with a `getWrapper` helper.
WIth this PR:
- make more general `views.setup.js`
- refactored favorites spec to use helper functions and selectors from variables
- Part of #5237 
- 💇🏼‍♂️

[unit-tests-only] Refactored favorites spec to use helper functions and variable selectors

---

packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkEdit.vue
packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkEdit.spec.js
packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/__snapshots__/LinkEdit.spec.js.snap

- added unit tests for `LinkEdit` component in web-app-files package
- test web components
- 🤖 
- 👨🏼‍🎨

[unit-tests] Added unit tests for link edit component

---

packages/web-app-files/tests/unit/views/PublicLink.spec.js

- Added unit tests `test.todo` skeleton for `PublicLink` view
- part of #5237

[unit-tests] Added unit test todo skeleton for public link view

---

packages/web-app-files/tests/unit/views/PrivateLink.spec.js

Added `todo` unit tests for `PrivateLink` view
- part fo https://github.com/owncloud/web/issues/5237

[unit-tests-only] Add todo unit tests for PrivateLink view

---

packages/web-app-files/tests/unit/views/SharedViaLink.spec.js

Added `todo` unit tests for `SharedViaLink` view
- part fo https://github.com/owncloud/web/issues/5237

[unit-tests-only] Add todo unit tests for SharedViaLink view

---

changelog/unreleased/enhancement-add-robots-file
packages/web-container/robots.txt
rollup.config.js

Add the robots.txt file
https://github.com/owncloud/ocis/issues/1314
Checked with ocis-web without pulling fresh assets. After generating the embed files and building ocis, the "/robots.txt" is accessible with the contents.
It's expected that a new web release will put everything into the right place.

Add robots.txt file

---

deployments/continuous-deployment-config/ocis_web/latest.yml

This adds developer ssh access to continuously deployed instances, in this case:
`ssh admin@ocis.ocis-web.latest.owncloud.works`.
- Possible after https://github.com/owncloud-devops/continuous-deployment/pull/21/files
- same as https://github.com/owncloud/ocis/pull/2464
Provide SSH access to continuously deployed instances to a wider audience to investigate, debug, ...

add developer ssh access to continously deployed instances

---

.drone.env
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIFilesList/fileList.feature
tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
tests/acceptance/features/webUISharingPublicBasic/publicLinkPublicActions.feature

https://github.com/owncloud/QA/issues/688
CI

[tests-only] [full-ci] Bump OCIS_COMMITID

---

packages/web-app-files/tests/unit/helpers/publicLinkRolesDefinition.spec.js

- added unit tests for files package helper: `publicLinkRolesDefinition.js`
- Part of #5236 
- CI

[unit-tests-only] Add TODO unit tests for publicLinkRolesDefinition helper

---

packages/web-app-files/tests/unit/helpers/publicLinkRolesDefinition.spec.js

- added unit tests for files package helper: `publicLinkRolesDefinition.js`
- Part of #5236 
- local

[unit-tests-only] Add unit tests for publicLinkRolesDefinition helper

---

packages/web-app-files/tests/unit/components/Search/Preview.spec.js

Adds unit  tests for `Preview` component

[unit-tests-only] Add unit tests for Preview component

---

packages/web-app-files/tests/unit/helpers/statusIndicator.spec.js

- Added todo unit tests for `statusIndicator` helper from `packages/web-app-files/helper`
- todo tests for only the exported function is  added
- Part of #5236

[unit-tests-only] Added todo unit tests for statusIndicator helper

---

__fixtures__/files.js
__fixtures__/sharedFiles.js
__mocks__/sdk.js
changelog/unreleased/enhancement-fetch-file-info-in-sidebar
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/FileInfo.vue
packages/web-app-files/src/components/SideBar/Links/FileLinks.vue
packages/web-app-files/src/components/SideBar/Links/PrivateLinkItem.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/fileSideBars.js
packages/web-app-files/src/index.js
packages/web-app-files/src/mixins/actions/favorite.js
packages/web-app-files/src/routes.js
packages/web-app-files/src/store/actions.js
packages/web-app-files/tests/integration/specs/sidebar.spec.js
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
packages/web-app-files/tests/unit/components/SideBar/Links/FileLinks.spec.js
packages/web-app-files/tests/unit/components/SideBar/Links/PrivateLinkItem.spec.js
packages/web-app-files/tests/unit/components/SideBar/SideBar.spec.js
tests/acceptance/features/webUIFavorites/favoritesFile.feature
tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
tests/integration/config/jest.init.js

If a single item is selected, fetch a fileInfo. This gives us information about the item even in shared lists.

[full-ci] feat: fetch file info in the sidebar

---

tests/acceptance/stepDefinitions/filesContext.js

This PR makes sure that the details tab in the sidebar is closed so that the breadcrumb is actually visible for mobile resolution.
- https://github.com/owncloud/web/issues/5790
On mobile resolution, when a resource is copied into a folder, breadcrumb for the current folder is expected to be visible in the tests. But the sidebar takes all the viewport to display the details tab. The sidebar should be closed before we see the breadcrumb for the mobile resolution. However, the tests were passing until now, because the element is there in the DOM, but not visible to us. So it looked like the tests are passing even when the breadcrumb is not visible, so once the details tab is closed by the changes made in this pr, the breadcrumb is actually visible.
However, something might be done so that …

[Tests-Only] Fix implementation for breadcrumb test step in mobile resolution

---

docs/deployments/oc10-app.md

This PR removes (invalid) trailing commas from json snippets in the documentation and adds a hint for using json validators if issues arise accessing ownCloud Web.
- https://central.owncloud.org/t/owncloud-web-4-2-white-page-with-js-typeerror/34063/8
Reduce copy&paste induced issues
- not needed, docs only

[docs-only] Remove trailing commas from json snippets, add validator hint

---

.drone.star

npm-install step is skipped when there are only unit tests changes
https://drone.owncloud.com/owncloud/web/19208/3/3
- Fixes issue: npm install is skipped when there are only unit tests changes

[tests-only] Do not skip npm install when there are only unit test changes

---

tests/acceptance/features/webUIFiles/breadcrumb.feature
tests/acceptance/pageObjects/personalPage.js
tests/acceptance/stepDefinitions/filesContext.js

This PR fixes the implementation for the types of breadcrumbs expected in the tests, so that the breadcrumb tests work as expected in mobile resolution and there is no false positive acceptance tests.
- https://github.com/owncloud/web/issues/5790
- The tests for breadcrumb in mobile resolution passed even when the sidebar covered all the viewport and the breadcrumb was not actually visible to us.
- The non-clickable breadcrumb element is not visible for just present, but still the tests passed when the non-clickable breadcrumb was expected to be visible in the webUI
These resulted in false positive acceptance tests, which needed to be fixed.
- CI

[Tests-Only][full-ci]Adjust the element and implementations to work for mobile breadcrumb

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUISharingExternal/federationSharing.feature
tests/acceptance/features/webUISharingExternalToRoot/federationSharing.feature
tests/acceptance/features/webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature
tests/acceptance/features/webUISharingPublicManagement/publicLinkIndicator.feature

When the preview / thumbnail is loaded the whole row is replaced.
So if the tests check something else in the row during that time, they might crash with a `stale element` error.
For those cases disable previews.
- Fixes #5660

[tests-only full-ci] disable previews in tests that check sharing indicators

---

packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/tests/unit/container/bootstrap.spec.ts

On top of https://github.com/owncloud/web/pull/5752 this PR now brings back that a misconfigured or unreachable app fails silently and only logs the error.

Fix that unreachable applications let the whole system die

---

packages/web-app-files/tests/unit/views/FilesDrop.spec.js
packages/web-app-files/tests/unit/views/__snapshots__/FilesDrop.spec.js.snap
packages/web-app-files/tests/unit/views/views.setup.js

- added unit tests for `FilesDrop` view in `web-app-files` package
- Part of #5237 
- `yarn test:unit`

[unit-tests-only] added unit tests for files drop view

---

changelog/unreleased/enhancement-early-store-init
packages/web-app-files/src/index.js
packages/web-runtime/src/App.vue
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/index.ts
packages/web-runtime/src/store/user.js

Applications need e.g. capabilities in their respective ready() and
mounted() hooks. This commit ensures that they are already loaded when
applications get initialized.
- CI

[full-ci] Init store and auth as early as possible

---

docs/deployments/oc10-app.md
packages/web-runtime/tests/unit/helpers/config.spec.js
tests/drone/config-oc10-integration-app-oauth.json
tests/drone/config-oc10-oauth.json
tests/drone/config-oc10-openid.json
tests/drone/config-ocis.json

When introducing theming, we changed the way themes are getting loaded to either URL- or path-based. I've recently come across a couple of outdated examples that still use a theme-name and hence fail & fall back to the `ownCloud`-default-theme. Fixing them gives dev-/admin-users a better idea of how to actually use this config option and reduces errors in the JS console

Fix theme paths in docs example/drone configs

---

.drone.star
tests/drone/configure-web.sh

build web once and then cache the dist folder. This shaves off ~2 minutes for each pipeline where web needs to be built (now restored from cache)
Additional improvements:
- restructure pipeline scheduling in main function
- use `pipelineDependsOn` and `pipelinesDependsOn` from oCIS CI
- remove redundancy / simplify `stop-recent-builds` pipeline
- remove all `"pull": "always",` since they are not really needed and only cause overhead
- add `pipelineSanityChecks`
- Fixes #5293

build web once - cache dist

---

.drone.star
tests/acceptance/run.sh

PR #5409 tries to report failed scenarios to RocketChat when a scenario fails and has to be rerun. That would be useful in the nightly CI run, because in that case there is no PR to post a comment to on GitHub. But that had difficulty getting a flexible message to be posted (rather than just a pass/fail kind of message)
Rather than keep trying to achieve individual RocketChat notifications for each failed test, this PR simply runs the nightly CI without the `--retry 1` parameter. Any test scenario(s) that fails will cause the drone pipeline to fail. When the whole nightly job finishes it reports overall success or failure to RocketChat already. (That is like what all the other nightly jobs do in other repos). When we see a nightly failure in RocketChat it has a link to drone. We can …

[tests-only] Do not retry failed acceptance tests in cron nightly

---

changelog/unreleased/enhancement-files-sidebar-reduced-width
packages/web-app-files/src/App.vue
packages/web-app-files/src/components/SideBar/FileInfo.vue

The right sidebar now only takes 1/3 of the width on medium and large
viewports and 1/4 of the width on extra large viewports. It doesn't need
more horizontal space. See screenshots.
- Fixes https://github.com/owncloud/web/issues/5981

Reduce sidebar width in files app

---

packages/web-runtime/package.json
packages/web-runtime/src/defaults/vue.js
yarn.lock

We used vue-axe for the accessibility audit (where it was helpful) but can't omit it from the production bundle (and it's not that much of a help currently) hence we'll remove it for now
- Fixes #5342
Reduce bundle size

Remove vue-axe to reduce bundle size

---

changelog/unreleased/enhancement-chunks-folder
rollup.config.js

oCIS uses Go embedd directives to include oC Web into it's binary.
Go embed ignores dot files and files starting with a underscore by default. You can also include them by using a `*` but that is only valid for the current path segment (not for subfolders).
oC Web has  a `_chunks` folder which will not be embedded in this case by default. Therefore we have the extra `assets/js/*` rule.
https://github.com/owncloud/ocis/blob/2c4bd9005ec26cddabefeb63af7e841d67bbd2f9/web/web.go#L7-L9
- https://github.com/owncloud/ocis/pull/2730
I there is no reasoning / convention behind the name of the `_chunks` folder, I would like to rename it to `chunks` and simplify the Go embed rule on the oCIS side.
- CI

rename _chunks folder to chunks folder

---

deployments/examples/ocis_web/docker-compose.yml

Use selfhosted icons for the office apps in the deployment example.
- Same as https://github.com/owncloud/ocis/pull/2736
Don't fetch the image from a third party

make deployment example use selhosted icons for office apps

---

.drone.env
.drone.star
deployments/examples/ocis_web/docker-compose.yml
docker-compose.yml

use `OCIS_INSECURE` flag after owncloud/ocis#2745. oCIS has a breaking change in that PR where all insecure options default to false. But there is one new flag to set them all to true.
- Caused by  owncloud/ocis#2745
- test case 1:
- test case 2:
- ...

use `OCIS_INSECURE` flag after owncloud/ocis#2745

---

changelog/unreleased/bugfix-search-app-translations
packages/web-app-draw-io/src/index.js
packages/web-app-files/src/components/FilesList/QuickActions.vue
packages/web-app-files/src/index.js
packages/web-app-files/src/mixins/actions/createPublicLink.js
packages/web-app-files/src/quickActions.js
packages/web-app-files/tests/unit/components/FilesList/QuickActions.spec.js
packages/web-app-search/src/index.ts

Fixes that the search app was not exporting its translations in the app manifest.
- Fixes https://github.com/owncloud/web/issues/5955

Export translations of search app

---

changelog/unreleased/enhancement-oc10-apps-in-app-switcher
changelog/unreleased/enhancement-update-ods
docs/deployments/oc10-app.md
packages/web-integration-oc10/lib/Controller/ConfigController.php
packages/web-runtime/package.json
yarn.lock

With this change, oC10 apps will be listed in the app switcher menu.
2 things that are not so good with the current approach:
* ~We only have full URLs to the icons. The config on the other hand expects a string to load the icons. Therefore the `application` icon is the default for now.~ -> we use the [extension icon](https://fonts.google.com/icons?selected=Material+Icons:extension:) 
* ~The app name we get from `\OC::$server->getNavigationManager()->getAll()` is already translated. To overcome this, we currently load the app + 3 different l10n instances to provide proper solutions based on the original name... super ugly. Is there a way to use the already translated string for OC web?~ -> That's okay for now.
- Fixes https://github.com/owncloud/web/issues/5980

Automatically show oC10 apps in app switcher menu

---

packages/web-app-files/tests/unit/helpers/route.spec.js

- implemented `todo` unit tests for `route` helper
- #5236

[unit-tests-only] Implemented `todo` unit tests for route helper

---

deployments/examples/ocis_web/config/ocis/proxy-config.json

The archiver does not work on https://ocis.ocis-web.latest.owncloud.works due the missing `/archiver` route.
- Fixes https://github.com/owncloud/web/issues/6026

add archiver route to deployment examples

---

changelog/unreleased/enhancement-app-provider-defaults
packages/web-app-external/src/App.vue
packages/web-app-external/src/index.js
packages/web-app-files/src/mixins/fileActions.js

Switch to early returns when evaluating the default action for a file. Also use the app provider without `app` param so that the app provider can decide on its own which app to use.
- Fixes https://github.com/owncloud/web/issues/5962
Improve default action handling for files.

Use default app from app provider and early returns in fileActions

---

packages/web-app-files/src/mixins.js

processDirectoryEntryRecursively was removed earlier, this is needed to upload nested folders.
@ScharfViktor can you please have a look and decide if it's worth writing a test.

revert processDirectoryEntryRecursively

---

deployments/examples/ocis_web/docker-compose.yml

This PR switches to the new configuration environment variable for the app provider
- needs owncloud/ocis#2811 first
- is needed after owncloud/ocis#2812
Make the app provider in the deployment example work after owncloud/ocis#2812

[deployment examples] rename app provider environment variables

---

changelog/unreleased/bugfix-pagination
packages/web-app-files/src/store/modules/pagination.js

Pagination was broken on page 2 and following because the `items per page` were referenced as strings. `firstElementIndex + itemsPerPage` for `firstElementIndex=0` and `itemsPerPage="100"` resulted in `0100`.
Bugfix
- CI

Fix pagination on page 2 and following

---

changelog/unreleased/enhancement-breadcrumb-context-menu
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/mixins/actions/delete.js
packages/web-app-files/src/mixins/actions/rename.js
packages/web-app-files/src/mixins/deleteResources.js
packages/web-app-files/src/store/actions.js
packages/web-app-files/tests/unit/mixins/actions/delete.spec.js
packages/web-app-files/tests/unit/mixins/actions/rename.spec.js
packages/web-app-files/tests/unit/mixins/deleteResources.spec.js
packages/web-runtime/package.json
packages/web-runtime/tests/unit/components/__snapshots__/ApplicationsMenu.spec.js.snap
yarn.lock

The last element of the breadcrumb now has a context menu which gives the user the possibility to perform actions on the current folder.
Requires https://github.com/owncloud/owncloud-design-system/pull/1786 to work.
- Fixes https://github.com/owncloud/web/issues/6030

Implement breadcrumb context menu

---

.drone.star

PR #6063 test against the `10.9.0-beta1` oC10 tarball. That name is longer than when we test against `latest`. The names of the acceptance test pipelines include the oC10 system-version-under-test. Pipeline names in drone are limited to 50 characters. Some generated pipeline names exceeded this limit, for example:
```
$ drone starlark
Error: generated stage name of length 51 is not supported. The maximum length is 50. oC10SharingInternalGroupsToRoot-chrome-10.9.0-beta1
2021/11/27 17:32:20 starlark evaluation error:
Traceback (most recent call last):
.drone.star:716:47: in main
.drone.star:757:38: in stagePipelines
.drone.star:1251:17: in acceptance
```
This PR reduces the longer names so that we can avoid this annoying limit for most future test runs.
CI

[tests-only] Shorten pipeline names

---

packages/web-app-files/src/views/PublicLink.vue
packages/web-app-files/tests/unit/components/FilesList/Pagination.spec.js
packages/web-app-files/tests/unit/views/PublicLink.spec.js
packages/web-app-files/tests/unit/views/__snapshots__/PublicLink.spec.js.snap

- implemented todo unit tests for `PublicLink` view
- Part of #5237 
- `yarn test:unit`

[unit-tests] Implemented todo unit tests for public link view

---

changelog/unreleased/enhancement-relative-date-tooltips
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/FileInfo.vue
packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkInfo.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ShowCollaborator.vue
packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
packages/web-app-files/src/mixins.js
packages/web-app-files/tests/unit/components/SideBar/FileInfo.spec.js
packages/web-runtime/package.json
yarn.lock

* Add tooltips with absolute dates to relative dates
* Make tooltips a11y compliant
* Use absolute date in sidebar file infos
Also see https://github.com/owncloud/owncloud-design-system/pull/1787 for the related changed in the files table.
- Fixes https://github.com/owncloud/web/issues/5672

Add tooltips with absolute dates to relative dates

---

tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js

This PR fixes the expiration-related tests that were failing because it's almost end of the year and the `selecting this year 2021` button is disabled in the UI. The PR check if the month of the expiration date is `December` directly day of the expiration is selected and this fixes the issue
- Fixes : https://github.com/owncloud/web/issues/6071
- Locally
- CI

[tests-only][full-ci]Fix failing expiration dates tests

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIFilesActionMenu/versions.feature
tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
tests/acceptance/helpers/webdavHelper.js

Some of the tests that are still valid were accidentally removed by PR https://github.com/owncloud/web/pull/5973. This PR re-adds those tests. One of the added tests relating to versions was flaky so a little pause time is added and the function is refactored accordingly
- referenced in: https://github.com/owncloud/web/issues/5853#issuecomment-976224333
- Locally
- CI

[tests-only][full-ci]Add valid tests that were removed by PR `#5973`

---

tests/acceptance/helpers/webdavHelper.js

PR https://github.com/owncloud/web/pull/6047 made some changes in the upload of the file. This PR enhances the changes made by that PR by storing time of upload only after the file has completely been uploaded.
- Fixes https://github.com/owncloud/web/issues/6081
- Locally
- CI

[tests-only]Store upload time after the upload is completed

---

.drone.star

Use the `owncloudci/wait-for:latest` docker image to check and wait for the backend server (oC10 or oCIS) to really be available before starting any test scenarios.
- Fixes #6079 
CI

[tests-only] wait for oC10 or oCIS docker to be up before starting smoke tests

---

deployments/examples/ocis_web/docker-compose.yml

The proxy config was no longer picked up after https://github.com/owncloud/ocis/pull/2708. It will now picked up automatically from `/etc/ocis/proxy.json`.
(Also the persistent volume /var/tmp/ocis did change some time ago)

fix deployment example

---

.drone.star

`restoreBuildArtifactCache(ctx, "playwright", ".playwright")` was being dome as a step in the nightwatch acceptance tests. That uses some time and is not needed. This PR removes it.
CI

[tests-only] Playwright cache is not needed in nightwatch test pipelines

---

changelog/unreleased/change-adopt-oc-table-files
changelog/unreleased/enhancement-adopt-oc-table-files
changelog/unreleased/enhancement-update-ods
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/constants.ts
packages/web-app-files/src/views/Favorites.vue
packages/web-app-files/src/views/LocationPicker.vue
packages/web-app-files/src/views/Personal.vue
packages/web-app-files/src/views/PublicFiles.vue
packages/web-app-files/src/views/SharedViaLink.vue
packages/web-app-files/src/views/SharedWithMe.vue
packages/web-app-files/src/views/SharedWithOthers.vue
packages/web-app-files/src/views/Trashbin.vue
packages/web-app-files/tests/unit/components/FilesList/ResourceTable.spec.js
packages/web-app-files/tests/unit/components/FilesList/ResourceTableSort.spec.js
packages/web-app-files/tests/unit/components/Search/List.spec.js
packages/web-app-files/tests/unit/views/Favorites.spec.js
packages/web-app-files/tests/unit/views/Personal.spec.js
packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
packages/web-runtime/package.json
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/sharedWithOthersPage.js
tests/smoke/support/cta/files/sidebar.ts
yarn.lock

ods oc-table-files always contained concrete web-app-files logic, to make development more agile and keep things close
oc-table-files was renamed to resource-table and relocated to live in web-app-files from now on.
- https://github.com/owncloud/owncloud-design-system/pull/1817
its unnecessarily much work if oc-table-files live in ODS, to have it relocated makes development easier
- unit tests
- integration tests

relocate oc-table-files from ods to web-app-files

---

.drone.star
tests/smoke/features/shareFileJourney.feature
tests/smoke/features/shareFolderJourney.feature
tests/smoke/support/page/files/allFiles.ts

- Added a check that a new version has been created. Added waitForControl before my "favorite" flaky methods "page.$" or "page.$$". 
- ~~Added retry 1 to CI **to unlock CI**~~
- I continue to watch, identify, and fix flaky places

[tests-only] Reduce flakyness in smoke tests

---

changelog/unreleased/bugfix-user-email-initialization
packages/web-runtime/src/store/user.js

Stumbled upon this in #1749 and figured it's worth adding the quick fix.
User should see their email address (if set) in the accounts page even if they used their username in the login form.

Use webdav email for user store initialization

---

packages/web-app-files/src/views/PublicFiles.vue

Due to a little issue (possibly a refactoring issue?) the context menu in public links  did not work.
- Does *not* fix https://github.com/owncloud/web/issues/4615, but stumbled over this issue while investigating that one
- created a public share in my development instance and checked the context menu was working after this change

Fix context menu on public files

---

.drone.env
changelog/unreleased/bugfix-contextmenu-public-links
changelog/unreleased/bugfix-file-rename
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/helpers/resources.js
packages/web-app-files/src/store/mutations.js
packages/web-app-files/src/views/PublicFiles.vue
packages/web-app-files/tests/unit/components/SideBar/SideBar.spec.js
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIFilesCopy/copy.feature
tests/smoke/support/cta/files/sidebar.ts
tests/smoke/support/page/files/allFiles.ts

Make sure filenames (and extensions) are properly updated in file list and sidebar after rename.
- Fixes #4893 
- test case 1:
- test case 2:
- ...

[full-ci] Fix #4893: Make sure filenames (and extensions) are properly updated in file list and sidebar after rename

---

changelog/unreleased/bugfix-no-context-menu-app-provider
changelog/unreleased/bugfix-no-scroll-app-provider
changelog/unreleased/enhancement-app-provider-feedback
packages/web-app-external/src/App.vue
packages/web-app-external/src/components/ErrorScreen.vue
packages/web-app-external/tests/unit/__snapshots__/app.spec.js.snap
packages/web-app-external/tests/unit/components/__snapshots__/ErrorScreen.spec.ts.snap
packages/web-app-files/src/mixins/fileActions.js

This PR fixes 2 bugs for the app-provider extension and adds error messages to the UI.
- Fixes #5960 
- Fixes #6002 
- Manually

Improvements for app provider

---

__mocks__/sdk.js
changelog/unreleased/bugfix-expiry-date-inconsistencies
packages/web-app-files/src/components/SideBar/Links/FileLinks.vue
packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkActions.vue
packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkEdit.vue
packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkInfo.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.vue
packages/web-app-files/src/helpers/resources.js
packages/web-app-files/tests/integration/helpers/date.js
packages/web-app-files/tests/integration/specs/linkExpirationDate.spec.js
packages/web-app-files/tests/integration/specs/peopleExpirationDate.spec.js
packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkEdit.spec.js
packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkInfo.spec.js

* Share expiry dates now always refer to the end of the given day. This change allows users to select the current day as expiry date.
* Displayed expiry dates have been aligned to ensure their consistency.
* Existing expiry dates for public links can now be removed again.
* We now use the Luxon `DateTime` object more consistently across the code base (replacing JavaScript's `new Date()`).

[full-ci] Fix inconsistencies in share expiry dates

---

changelog/unreleased/bugfix-open-in-browser-on-public-files
packages/web-app-files/src/mixins/actions/fetch.js

When #4615 was created, using "open in browser" on public links indeed resulted in the described behavior.
In https://github.com/owncloud/web/pull/4689 the behavior was changed to open the download url in a new tab, that in turn did not open the file in the browser (for me, Chromium 95) but instead downloaded it with a random/hash filename. 
The code path for private files achieves the correct result: it opens the file in a new tab and displays it.
We can align the behavior for public files with that by simply using the downloadUrl in the XHR download.
- Fixes #4615
- Fixes #6128

Fix #4615: Use downloadUrl for 'Open in browser' on public files

---

dev/docker/oc10.web.config.json
dev/docker/ocis.web.config.json
tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-oc10-server-openid-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIFilesList/fileList.feature
tests/acceptance/features/webUIPreview/imageMediaViewer.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRootPreviews/shareWithUsers.feature
tests/acceptance/features/webUISharingPublicBasic/publicLinkPublicActions.feature
tests/acceptance/stepDefinitions/filesContext.js
tests/drone/config-oc10-integration-app-oauth.json
tests/drone/config-ocis.json

smoke test suite runs too fast, the sharing is flaky because playwright is faster then 250ms which is the [default debounce time in web](https://github.com/owncloud/web/blob/5c43bc693b57ca628d62ea36b44abfb69623b8f8/packages/web-app-files/src/views/Personal.vue#L369).
Following happens:
* user (playwright) uploads file
* user shares file via the context menu
* sidebar opens in sharing dialogue
* user enters sharee name
* vue waited 250 ms and loads the resource thumbnail
* vue updates the resource with the thumbnail info
* vue gets a reactive trigger on the resource
* vue updates the sidebar view [due the update](https://github.com/owncloud/web/blob/5c43bc693b57ca628d62ea36b44abfb69623b8f8/packages/web-app-files/src/components/SideBar/Shares/FileShares.vue#L90)
* user loosing focus of the …

[full-ci] Fix temporarily flaky smoke tests

---

packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/helpers/store.ts
packages/web-app-files/src/store/mutations.js
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.js.snap
packages/web-app-files/tests/unit/components/SideBar/FileInfo.spec.js
packages/web-app-files/tests/unit/helpers/store.spec.ts
packages/web-app-files/tests/unit/store/mutations.spec.js

- go to shared with me
- select a file
- open sidebar
with oc10 backend:
- see correct share date
- see share owner
with oCIS backend:
- see share date being unix timestamp 0
- see no owner
The store did not mutate the `sharesTree` state in a reactive way.
The FileDetails (maybe for that reason) watched the `sharesTreeLoading` state, which is not a good event source as mutiple loading processes can be started simultaneously and do not trigger multiple watch runs (when they set loading to false one after another).
For that reason I fixed the store mutation and made the FileDetails watch the sharesTree itself instead.
- No issue as I noticed this while working on another bug
Without this fix:

oCIS: Fix share date and share owner in shared-with-me sidebar

---

changelog/unreleased/bugfix-extension-img
changelog/unreleased/bugfix-hide-files-by-default
changelog/unreleased/bugfix-order-extensions
changelog/unreleased/enhancement-build-options
changelog/unreleased/enhancement-feedback-on-startup
packages/web-app-files/src/components/ActionMenuItem.vue
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/mixins/fileActions.js
packages/web-app-files/tests/unit/components/ActionMenuItem.spec.js
packages/web-container/index.html.ejs
packages/web-runtime/src/pages/oidcCallback.vue
packages/web-runtime/src/store/apps.js
rollup.config.js

Just a bunch of (I hope) fixes:
- I've made the hidden files hidden by default. This is the current behavior in oc10 and I believe should be the same in web;
- Generate sourcemap. We did this to make it easier to debug, let me know if you think this should not be pushed to production (**edit:** made it configurable)
- ~~Clean paths for drawio~~ (opened a diff PR with this fix)
Some more debatable fixes:
~~I've changed the default title of the html page from "owncloud" to "loading" (not translated). Ofc this changes to the configured title once the app loads, but if something fails or takes a long time to load, users get confused.~~ (**edit:** made the title configurable instead)
In the same spirit, I've added information that is displayed before the app loads:  ~~a loading message~~ a …

[full-ci] Small fixes

---

tests/smoke/support/cta/files/misc.ts
tests/smoke/support/page/files/allFiles.ts
tests/smoke/support/page/files/sharedWithMe.ts

as title says, wait for responses before move forward.
- (Temporarily, hopefully for quite a while) Fixes https://github.com/owncloud/web/issues/6082
trust!
- test smoke tests

[tests-only] Reduce smoke test flakiness by waiting for action responses

---

changelog/unreleased/bugfix-extension-img
changelog/unreleased/bugfix-hide-files-by-default
changelog/unreleased/bugfix-order-extensions
changelog/unreleased/enhancement-build-options
changelog/unreleased/enhancement-default-markdown-mediaviewer-extensions
changelog/unreleased/enhancement-feedback-on-startup
packages/web-app-files/src/components/ActionMenuItem.vue
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/mixins/fileActions.js
packages/web-app-files/tests/unit/components/ActionMenuItem.spec.js
packages/web-app-markdown-editor/src/index.js
packages/web-app-media-viewer/src/index.js
packages/web-container/index.html.ejs
packages/web-runtime/src/pages/oidcCallback.vue
packages/web-runtime/src/store/apps.js
rollup.config.js
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUIRenameFiles/renameFiles.feature
tests/acceptance/features/webUIRenameFolders/renameFolders.feature
tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature

Taking over and finalizing #6088

[full-ci] Upstream small CERNbox fixes

---

changelog/unreleased/bugfix-new-file-handler
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/helpers/route.js
packages/web-runtime/src/store/apps.js

If we have more than one new file handler in the extensions, we never check the routes associated with them.
If, for example, we need different routes in order to distinguish internal and public links (i.e #6125), without this fix we would see both entries in the "new" menu.
In the past I only added a single "new handler" to avoid seeing 2 entries, but then when I create a new file, the opening action will match the route it belongs to.

Ensure route config is honored for new file handlers

---

changelog/unreleased/bugfix-no-context-menu-app-provider
changelog/unreleased/bugfix-no-scroll-app-provider
changelog/unreleased/enhancement-app-provider-feedback
packages/web-app-external/src/App.vue
packages/web-app-external/src/components/ErrorScreen.vue
packages/web-app-external/tests/unit/__snapshots__/app.spec.js.snap
packages/web-app-external/tests/unit/app.spec.js
packages/web-app-external/tests/unit/components/ErrorScreen.spec.ts
packages/web-app-external/tests/unit/components/__snapshots__/ErrorScreen.spec.ts.snap
packages/web-app-files/src/components/Upload/ProgressBar.vue
packages/web-app-files/src/mixins/fileActions.js
packages/web-app-files/tests/unit/components/Upload/ProgressBar.spec.js

Finalizes #6003, should take care of fixing the external app (snapshot) tests
- Fixes #5960 
- Fixes #6002

External apps errorhandling

---

.drone.star

If only smoke test code in `tests/smoke` has changed, then acceptance tests will not be run.
If only acceptance test code in `tests/acceptance` has changed, then smoke tests will not be run.
- Fixes #6150 
See demo in #6154 and #6155

[tests-only] do not run acceptance tests if only smoke tests changed

---

tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js

as described in https://github.com/owncloud/web/issues/6158 it is problematic to select a date if the month of date is not in focus, this is fixed by using (hacking) the vue dom api and request the datepicker to focus on given date. Lets see iof this works in future and is a final solution
- Fixes #6158
- needed #6160
...

set visible month to requested month in expiry date-picker

---

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIFilesActionMenu/versions.feature
tests/acceptance/pageObjects/FilesPageElement/versionsDialog.js
tests/acceptance/stepDefinitions/filesContext.js

A test for existing error [2261](https://github.com/owncloud/ocis/issues/2261) is written
And added to expected-failures

[tests-only] add test download previos version

---

changelog/unreleased/enhancement-print-version
packages/web-runtime/src/App.vue
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/container/versions.ts
packages/web-runtime/src/index.ts
packages/web-runtime/src/pages/missingOrInvalidConfig.vue
packages/web-runtime/tests/unit/container/versions.spec.ts
rollup.config.js

With this PR the web ui prints the package version and the backend version (if available) to the javascript console and sets them as meta generator tag in the html head. See screenshots below. There are some (known) situations where the backend version is not available. Those need to be fixed separately, this PR just makes use of the information. Only consequence is that the backend doesn't show up, so it's not an issue to fix it separately. The version of the web ui always gets shown, as it is included in the bundling process.
The `product` key in the version doesn't exist, yet, so for now it'll always fall back to `ownCloud`. I'll provide an oCIS PR so that oCIS will announce itself as `product: "oCIS"` in the future. For ownCloud 10 we don't need to change anything as the fallback is …

Show version numbers

---

packages/web-app-files/tests/unit/views/Personal.spec.js
packages/web-app-files/tests/unit/views/PublicFiles.spec.ts
packages/web-app-files/tests/unit/views/views.setup.js
packages/web-app-files/tests/unit/views/views.shared.ts

Some unit tests for `views` were using `VueRouter` for mounting.
- VueRouter is complex to integrate
- Uses external library for the tests
With this PR,
- `VueRouter` usages are replaced with the mocked `route` and `router`
- Also, `getStore` method from `view.setup.js` is used to get the store
- #5237 
- :robot:

[unit-tests] make use of mocked router rather using vue router

---

.drone.star

The playwright tests folder was recently renamed from `smoke` to `e2e`. Do similar in drone CI to avoid future confusion.
CI

[tests-only] Change smoke test to e2e test in .drone.star

---

changelog/unreleased/enhancement-lazy-resource-table
dev/docker/oc10.web.config.json
dev/docker/ocis.web.config.json
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/tests/integration/specs/pagination.spec.js
packages/web-app-files/tests/unit/components/FilesList/ResourceTable.spec.js
packages/web-app-files/tests/unit/views/views.setup.js
packages/web-runtime/src/store/config.js
rollup.config.js
tests/drone/config-oc10-integration-app-oauth.json
tests/drone/config-oc10-oauth.json
tests/drone/config-oc10-openid.json
tests/drone/config-ocis.json
tests/unit/config/jest.config.js

since lazy table cell rendering has landed in ODS we also should use it in web. the feature is enabled by default, but can be disabled via the configuration (`"resourceTableLazy": false`). 
- part of https://github.com/owncloud/web/issues/6046, store needs further optimization
as written in linked issue, current views kinda slow and should be snappy instead. This is just one piece of it and wiill need further investigation.
- local installation, unit tests and integration tests.

[full-ci] enable lazy table cells and fix tests

---

changelog/unreleased/enhancement-redesign-main-layout
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-runtime/src/App.vue
packages/web-runtime/src/components/TopBar.vue
packages/web-runtime/tests/unit/components/TopBar.spec.js
tests/acceptance/pageObjects/webPage.js

This PR fixes some small issues from the first redesign iteration:
- topbar stays visible on pages that don't require authentication, but with a reduced set of items
- margins around and in between `browser top edge` <-> `topbar` <-> `app container` <-> `browser bottom edge` are now all equal
- white border artifact on the left of the sidebar nav is fixed
- scrollbar issues are fixed
- height issue in app provider is fixed
- bonus: fixes a console warning about type check failures when passing `undefined` into `OcResourceSize` inside `ResourceTable`
- Works towards https://github.com/owncloud/web/issues/6203 
Finetune the main layout
- manually in chrome and firefox

Redesign small fixes

---

changelog/unreleased/bugfix-open-folder-context-menu
packages/web-app-files/src/components/ActionMenuItem.vue
packages/web-app-files/src/mixins/actions/navigate.js
packages/web-app-files/tests/__fixtures__/fileActions.js

- public and personal route were flipped, fixed that
- route was not correctly created in the context menu
- moved logic for creating the full route into the file action instead
of building the route in the component (make components dumb again)
- Fixes https://github.com/owncloud/web/issues/6187
Fix context action for opening folders

Fix open folder file action

---

tests/acceptance/features/webUIFiles/batchAction.feature
tests/acceptance/stepDefinitions/middlewareContext.js

PR #6105 wrote a step in a scenario:
`And user "Alice" has created folder "simple-folder"  in the server`
notice that it has 2 spaces before "in the server"
This PR changes the regex for such steps so that there must be only a single space, and removes excess space from test steps.
CI

[tests-only] [full-ci] allow only one space before "in the server"

---

.drone.star
Makefile
tests/e2e/cucumber/shareFolderJourney.feature
tests/e2e/support/cta/files/sidebar.ts

I added the display of error trace in the github comments. 
The trace, in my opinion, gives a very good understanding of the cause of the error. You can see all the steps, the console and the network. 
Trace can be open in Trace Viewer in two ways:
- download zip file. and open file in console `npx playwright show-trace Downloads/file.zip`
- copy link to console (without downloading zip file): `npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/file.zip`
I did not upload a video or har so as not to make the message too big. It might make sense to include video via headers

[full-ci][tests-only] Add trace error to github comment

---

tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUIWebdavLockProtection/delete.feature
tests/acceptance/features/webUIWebdavLockProtection/move.feature
tests/acceptance/features/webUIWebdavLockProtection/upload.feature
tests/acceptance/features/webUIWebdavLocks/locks.feature
tests/acceptance/features/webUIWebdavLocks/unlock.feature
tests/acceptance/stepDefinitions/filesContext.js

This PR refactors the scenarios related to renaming and locking to use the steps of middleware. These are the leftovers of this PR https://github.com/owncloud/web/pull/6172
- part of:  #6111
- Locally
- CI

[tests-only][full-ci]Refactor files related to renaming and locking to match the steps of middleware

---

changelog/unreleased/enhancement-spaces-default-sorting
packages/web-app-files/src/views/spaces/Projects.vue

Spaces will now be sorted by their name by default. This is only temporary. Later, spaces will be sorted via API.
- Fixes https://github.com/owncloud/web/issues/6253

Add default sorting to the spaces list

---

packages/web-pkg/src/composables/useAppDefaults/index.ts
packages/web-pkg/src/composables/useAppDefaults/useAppFileHandling.ts

Removes a nonsense check from `publicLinkPassword` computed.
The code was just introduced and never released, so we don't need a changelog entry imho.
The second change is unrelated but I stumbled upon this while debugging why files could not be shown in mediaviewer...
It seemed to still work even with the double encoding, so I'm not even sure how to use it to break something, so again no changelog needed imho.
- test case 1:
- test case 2:
- ...

Fix publicLinkPassword in apps

---

changelog/unreleased/bugfix-application-config
packages/web-runtime/src/store/apps.js

- Fixes #6296 
The config is loaded before the actual app, so when the old code tried to persist the setting inside the application object inside the store it was not available. That's why we now cache the config and copy it into the app object, once it becomes available. This should be a true drop in change and I don't expect any side effects as we did not change the internal structure of the object in the store.
- test case 1:
- test case 2:
- ...

Fix #6296: Make app config available to app again

---

changelog/unreleased/enhancement-drawio
packages/web-app-draw-io/src/App.vue

A couple of improvements to Drawio:
- Honor the autosave configuration, and actually _save_
- Show error messages to the user, currently all failures are silent
- Enable opening from public links without being authenticated
Let me know if this strategy for public links is ok. I was thinking of applying the same logic into the app provider/external app, as this is also not working properly with public links.
Maybe the mixin `fileAcess` that I created here can be moved somewhere else and re-used? Where do you suggest? `web-pkg`?

Drawio improvements

---

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIFilesActionMenu/versions.feature
tests/acceptance/pageObjects/webPage.js
tests/acceptance/stepDefinitions/generalContext.js

Scenario `user downloads a previous version of the file` works for `oC10` server. 
`Then as "Alice" the content of "lorem.txt" should be the same as the content of local file "lorem.txt"` step is not relevant for that scenario.
I have removed that step and implemented a step that checks for error popup which is done for other download scenarios:
```
...
When the user downloads file "sample.txt" using the webUI
Then no message should be displayed on the webUI
```

[tests-only][full-ci] Fix version download acceptance test

---

.drone.star

Bump middleware docker image from 1.2.0 to 1.2.1 for tests

[tests-only][full-ci] Bump middleware image from 1.2.0 to 1.2.1

---

.drone.env
.drone.star
tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
tests/acceptance/stepDefinitions/previewContext.js

Test scenarios are adjusted to take into account that the `Shares` folder is always displayed when running on oCIS, even before a user has received any incoming share.
This also means  that test scenarios that try to "select all" and then "delete all" at the top (root) level a a user's file system do not pass. The `Shares` folder gets selected, but it cannot be deleted. See issue #6305 for discussion of this.
Also, the media viewer test code has been enhanced to `waitForMediaViewerLoaded` to help be sure that the resource has been properly loaded at each point in the test steps.
- CI

[tests-only][full-ci]Bump the commit id for tests

---

changelog/unreleased/enhancement-app-provider-create-files
packages/web-app-files/src/components/AppBar/AppBar.vue

In order to avoid another rebase and review cycle this PR supersedes https://github.com/owncloud/web/pull/5890
Allow creation of files for mimetypes with set flag "allow_creation"

App provider create files

---

.drone.star

Bump owncloud-test-middleware version to v1.3.0
- :robot:

[full-ci][tests-only] bumped middleware version to v1.3.0

---

deployments/examples/ocis_web/config/ocis/entrypoint-override.sh
deployments/examples/ocis_web/docker-compose.yml

fix basic auth escaping and remove proxy restart workaround (since no longer needed)
sometimes only the proxy started on the continuously deployed server

[deployment-examples] fix basic auth and remove proxy restart

---

changelog/unreleased/enhancement-context-route-auth-redirect
packages/web-app-external/src/components/LoadingScreen.vue
packages/web-app-external/src/index.js
packages/web-app-files/src/mixins/fileActions.js
packages/web-runtime/src/router/index.js

This PR includes the contextRoute of the next route when checking if authentication is required.
In the (hopefully very near) future this can be expanded to public links with password protection. But for now this simple PR solves the case of bookmarks to editors having a file open from a private context.
- Fixes #6045
- Fixes #6069
- manually... I don't see much room for tests in the current state of the implementation.

Context route auth redirect

---

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature

Adjust the test for "delete all" batch action to take into account that the `Shares` folder cannot be deleted.
The test workflow now does "select all" and then unselects the `Shares` folder, then deletes the remaining items.
See issue comment https://github.com/owncloud/web/issues/6305#issuecomment-1022217793 and the other discussion in the issue.
#6305 
CI

[tests-only] [full-ci] Adjust test to avoid issue 6305

---

packages/web-app-files/tests/unit/views/SharedWithOthers.spec.js
packages/web-app-files/tests/unit/views/__snapshots__/SharedWithOthers.spec.js.snap

- added unit tests for `SharedWithOthers` view
- #5237 
- :robot:

[unit-tests-only] Added unit tests for shared with others view

---

packages/web-app-files/src/views/LocationPicker.vue
packages/web-app-files/tests/unit/views/LocationPicker.spec.js
packages/web-app-files/tests/unit/views/__snapshots__/LocationPicker.spec.js.snap
packages/web-app-files/tests/unit/views/views.setup.js

Added unit tests for `LocationPicker` view
- Part of #5237 
- `yarn test:unit`

[unit-tests] added unit tests for LocationPicker view 

---

changelog/unreleased/bugfix-favorite-action
changelog/unreleased/bugfix-favorite-star-sidebar
packages/web-app-files/src/components/SideBar/FileInfo.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/mixins/actions/favorite.js
packages/web-app-files/src/mixins/fileActions.js
packages/web-app-files/src/store/actions.js
packages/web-app-files/src/store/mutations.js

The favorite star in the right sidebar caused an error on click and didn't update itself then. This PR fixes that. Used to chance to clean up some code fragments on the way.
- Fixes #6328
Hardening

Fix update of favorite star in right sidebar after click

---

tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
tests/acceptance/features/webUISharingPublicManagement/shareByPublicLink.feature
tests/acceptance/features/webUIUpload/upload.feature
tests/acceptance/features/webUIUpload/uploadEdgecases.feature
tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
tests/acceptance/features/webUIUserJourney/journey1.feature
tests/acceptance/stepDefinitions/middlewareContext.js

- added `in the middleware` as middleware capture string for gherkin steps
- refactored content assertion steps including local files and files from the server
- Fixes https://github.com/owncloud/owncloud-test-middleware/issues/96
- :robot:

[tests-only] Refactor local file involving steps

---

docs/backend-oc10.md
docs/getting-started.md
docs/testing/acceptance-tests-all.md

This fixes the currently broken docs build / publish process (https://drone.owncloud.com/owncloud/owncloud.github.io/2667/1/4), because referencing the file "building.md" is ambiguous (comes also from another repo). Therefore we reference this file with relative paths to make it unambiguous.

resolve docs build error by referencing building.md with a relative path

---

.drone.star
tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIUpload/upload.feature
tests/acceptance/stepDefinitions/middlewareContext.js

Fix local file creating & uploading scenario with sub-folders
- added simple passing scenario involving all non-empty subfolders
- added a failing scenario involving empty subfolders
- part of https://github.com/owncloud/owncloud-test-middleware/issues/97
- reported https://github.com/owncloud/web/issues/6348

[tests-only] Update local file create scenario using v1.3.1 middleware

---

.drone.env

Bump oCIS commit id to the latest for the tests
part of  https://github.com/owncloud/QA/issues/715

[tests-only][full-ci] Bump oCIS commit id for the tests

---

changelog/unreleased/enhancement-darkmode-themeswitcher
packages/web-app-files/tests/unit/components/AppBar/ViewOptions.spec.js
packages/web-pkg/src/composables/localStorage/useLocalStorage.ts
packages/web-runtime/src/components/Topbar/ThemeSwitcher.vue
packages/web-runtime/src/composables/index.ts
packages/web-runtime/src/composables/theme/index.ts
packages/web-runtime/src/composables/theme/useDefaultThemeName.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/tests/unit/components/Topbar/ThemeSwitcher.spec.js
packages/web-runtime/tests/unit/components/Topbar/__snapshots__/ThemeSwitcher.spec.js.snap

~~Code doesn't read that nicely but does what it should~~ (comment from before we switched to composition api)
- Fixes #6242

Save preferred theme in localStorage

---

tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md

Fix errors in the feature file links in expected-failures files. A few have got out-of-date line numbers, wrong feature file names etc.
I have a PHP script that I used to parse locally and find these. I will think about where to put that so that we can automatically find these accidental errors. They don't cause an actual problem for CI, it is just confusing for real people if they look at or click a link that is wrong.
Similar PR for oCIS is https://github.com/owncloud/ocis/pull/3091
CI

[tests-only] [full-ci] Fix expected-failures references

---

.drone.star

Adjust the nightwatch acceptance test suite pipelines to keep the longest pipeline at about 20 minutes.
There are comments below about what I did as I shuffled test suites and pipelines.
Fixes #6356 
CI

[tests-only] [full-ci] Adjust CI pipelines to reduce acceptance test elapsed time

---

changelog/unreleased/enhancement-redesign-main-layout
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/views/LocationPicker.vue
packages/web-runtime/src/App.vue
packages/web-runtime/src/components/SidebarNav/SidebarNav.vue

Left sidebar now has rounded corners on the right. Also removed some unneeded css classes and styles.
- Works towards https://github.com/owncloud/web/issues/6280
Redesign

Add rounded corners to left sidebar

---

.drone.star

Owncloud Test Middleware's default entry point assumes the container to be run with a docker volume `uploads`. In this directory, all the files necessary for uploading jobs are copied. Also, the local files to be created during the test runs are also uploaded to this one by the middleware.
With this PR:
- middleware will use the shared vol. directory as a directory for `REMOTE_UPLOAD_DIR`

[tests-only] Removed duplicated volume from middleware start script

---

changelog/unreleased/change-drop-editor-routes-whitelist
packages/web-app-draw-io/src/index.js
packages/web-app-external/src/store/index.ts
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/mixins/fileActions.js
packages/web-app-markdown-editor/src/index.js
packages/web-app-media-viewer/src/index.js
packages/web-app-skeleton/src/app.js
packages/web-runtime/src/container/api.ts
packages/web-runtime/src/container/bootstrap.ts

This PR kills the `routes` key from the editor app manifests. It has only ever been used as a weird way to disable editors in the trashbin view. Since that logic belongs in the files app, not in the editors, I've converted this to a hardcoded check in the fileActions mixin (all the file actions do hardcoded route checks anyways). This gets us rid of the hassle to update a route whitelist in all applications out there (and internally). Which is the case for the upcoming spaces feature already (i.e. no apps being available in spaces folder listings, which is unnecessary effort).
Also used the chance to get rid of some console noise, namely:
- vue router deprecation warnings of `addRoutes` (use `addRoute` instead)
- warnings about a non-existing `files-spaces-storage` route name (deleted as …

Ignore routes whitelist and reduce console noise

---

packages/web-app-external/src/App.vue
packages/web-app-external/src/index.js
packages/web-app-external/tests/unit/app.spec.js
packages/web-app-files/src/mixins/fileActions.js
packages/web-pkg/src/composables/appDefaults/index.ts
packages/web-pkg/src/composables/appDefaults/types.ts
packages/web-pkg/src/composables/appDefaults/useAppDefaults.ts
packages/web-pkg/src/composables/appDefaults/useAppNavigation.ts
packages/web-pkg/src/composables/router/index.ts
packages/web-pkg/src/composables/router/types.ts
packages/web-pkg/src/composables/router/useRouteQuery.ts
packages/web-pkg/src/composables/router/useRouteQueryPersisted.ts
tests/acceptance/features/webUICreateFilesFolders/createFile.feature

This adds `params` of the source context route to the `query` of app routes and converts them back to params when routing back to the origin.
For example, if I open `/Memes/itssomething.jpg` in my personal files in the mediaviewer, the URL will look like this:
`https://host.docker.internal:9200/#/mediaviewer/files-spaces-personal-home/Memes/itssomething.jpg?params%5Bstorage%5D=home&params%5Bitem%5D=Memes`
Unfortunately there does not seem to be a built-in way for `vue-router` to handle maps in `query`, that makes everything a bit ugly and especially it does not allow us to *not* *escape* `[]`. We could potentially implement [parseQuery/stringifyQuery](https://router.vuejs.org/api/#parsequery-stringifyquery) to make the handling code less awkward and to allow a url like: …

[full-ci] Context Route Params

---

packages/web-runtime/package.json
packages/web-runtime/src/defaults/index.ts
yarn.lock

print fontawesome-free attributions to browser console. This is a quick workaround and should be moved to ODS in one of the next releasees.
- Fixes https://github.com/owncloud/web/issues/6369

add fontawesome-free attributions console message

---

packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/composables/index.ts
packages/web-app-files/src/composables/router/index.ts
packages/web-app-files/src/composables/router/useActiveLocation.ts
packages/web-app-files/src/router/index.ts
packages/web-app-files/src/router/utils.ts
packages/web-pkg/src/composables/router/index.ts
packages/web-pkg/src/composables/router/useRoute.ts
packages/web-pkg/src/composables/router/useRouteName.ts

Moved the `watchActiveLocation` helper to a `useActiveLocation` composable to make clearer that it is to be used in context of composition API only.
Also renamed the useCurrentRoute composable to useRoute to stay
consistent with naming and refactored the useRouteName composable to use
the new useRoute composable internally, which reduces code complexity
and actually makes it reactive.
Clean code...

Move the watchActiveLocation helper to a useActiveLocation composable

---

packages/web-app-files/tests/unit/views/spaces/Projects.spec.js

mock `setModalInputErrorMessage` so that it does not show an error while running the unit tests
get rid of this log output
```
console.error
[vuex] unknown action type: setModalInputErrorMessage
at Store.dispatch (node_modules/vuex/dist/vuex.common.js:499:15)
at Store.boundDispatch [as dispatch] (node_modules/vuex/dist/vuex.common.js:408:21)
at VueComponent.mappedAction (node_modules/vuex/dist/vuex.common.js:1066:20)
```
:robot:

[tests-only] mock setModalInputErrorMessage in Projects.spec.js

---

tests/acceptance/setup.js

While running acceptance tests using scripts from package.json file, the command will fail because `report` dir will not be available.
This PR creates `report` folder if not exists before tests run.
**Or we can remove `-f json:report/cucumber_report.json` from the command. (I don't know how we are using `cucumber_report.json`)**
- Fixes https://github.com/owncloud/web/issues/6388

[tests-only][full-ci] Create report directory if not exists

---

tests/e2e/cucumber/environment/index.ts
tests/e2e/cucumber/step_definitions/session.ts
tests/e2e/support/environment/actor/actor.ts
tests/e2e/support/environment/actor/actors.ts
tests/e2e/support/environment/actor/shared.ts

Step 1:
**reduce traces**
The following logic used to work:
- if the test fails and is retry=n, then trace is enabled. 
- Tracing records the next test run (is correct) but continues on the next tests as well
I changed this by adding retry counter. 
logic:
- first test run does not record trace
- after the test falls and Retry = n, in the "After" function enables trace recording for the next run
- trace records for the next run (regardless of whether test passes or falls)
- after all attempts, the recording is turned off
see block diagram: 
Step 2:
**add more details to github comments:**
our trace look like: `npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/21580/2022-1-5-09-24-50-Alice.zip` 
- add feature name in drone.star is difficult. We know …

Reduce notification to github 

---

packages/web-runtime/tests/unit/container/bootstrap.spec.ts

the `mocked` util function is now deprecated and has been moved to Jest repository, see https://github.com/facebook/jest/pull
the log output is probably there since bumping jest to 27.x 7fa3b712
alternative is to disable the warning with `process.env.DISABLE_MOCKED_WARNING=true` but I don't see why that should be good
@pascalwengerter (you have bumped jest) @fschade (you have written the tests) opinions?
- part of https://github.com/owncloud/web/issues/6337
get rid of this log output
```
`mocked` util function is now deprecated and has been moved to Jest repository, see https://github.com/facebook/jest/pull/12089. In `ts-jest` v28.0.0, `mocked` function will be completely removed. Users are encouraged to use to Jest v27.4.0 or above to have `mocked` function available from `jest-mock`. …
```

[tests-only] use jest.mocked instead of mocked from ts-jest/utils

---

packages/web-runtime/tests/unit/components/Topbar/ApplicationsMenu.spec.js
packages/web-runtime/tests/unit/components/Topbar/__snapshots__/ApplicationsMenu.spec.js.snap

stub the `oc-list` element that was added recently
@pascalwengerter you have added the element in f9f17d610316f760ba181bf1af79296174403d3b , any reason not to stub it?
reduce log output saying
`[Vue warn]: Unknown custom element: <oc-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
- running unit tests locally
- :robot:

[tests-only] stub oc-list element in ApplicationsMenu unit tests

---

CHANGELOG.md
changelog/unreleased/enhancement-spaces-overview-design-refinement
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap

- Fixes https://github.com/owncloud/web/issues/6333
- Fixes https://github.com/owncloud/web/issues/6400
- test case 1:
- test case 2:
- ...

Spaces overview refinement

---

packages/web-app-files/tests/unit/components/SideBar/FileInfo.spec.js
packages/web-app-files/tests/unit/components/SideBar/__snapshots__/FileInfo.spec.js.snap

mock the date/time functions in all tests, not only in some
@JammingBen @dschmidt you have been working on these tests, please review. How much do we care about the string? If we don't we can reduce the complexity a bit more.
```
Cannot evaluate expression: timeRelative
console.warn
Cannot evaluate expression: timeRelative
57 |         obj.timeRelative = this.formRelativeDateFromRFC(obj.sourceTime)
58 |
> 59 |         obj.infoString = this.$gettextInterpolate(obj.infoString, obj)
| ^
60 |         obj.ariaLabel = this.$gettextInterpolate(obj.ariaLabel, obj)
61 |         return obj
62 |       }
at Object.evalInContext (node_modules/vue-gettext/dist/vue-gettext.js:280:21)
at node_modules/vue-gettext/dist/vue-gettext.js:293:28
at String.replace (<anonymous>)
at …
```

[tests-only] mock date/time functions in FileInfo unit test

---

packages/web-app-files/tests/unit/views/SharedViaLink.spec.js

mock the 'files-spaces-personal-home' route
@fshade you have added the route to the tests in d0b2b84a7999c7a5b823a0baa1d5b1a5454782ed, any reason we should not mock the route?
- part of  #6337
get rid of these log output:
```
console.warn
[vue-router] Route with name 'files-spaces-personal-home' does not exist
at warn (node_modules/vue-router/dist/vue-router.common.js:18:47)
at Object.match (node_modules/vue-router/dist/vue-router.common.js:1594:9)
at VueRouter.match (node_modules/vue-router/dist/vue-router.common.js:2940:23)
at VueRouter.resolve (node_modules/vue-router/dist/vue-router.common.js:3094:20)
at Proxy.render (node_modules/vue-router/dist/vue-router.common.js:1099:22)
at node_modules/@vue/composition-api/dist/vue-composition-api.common.js:1892:35
at activateCurrentInstance …
```

[tests-only] mock files-spaces-personal-home route in SharedViaLink unit tests

---

packages/web-app-files/tests/unit/components/SideBar/SideBar.spec.js

- use only shallowMount in SideBar unit tests (I cannot see why a full mount would be needed here, but I might be wrong)
- mock observer in SideBar unit tests
get rid of log outputs like
```
[Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'replace')"`
[vuex] unknown getter: Files/sharesTree
[vuex] unknown getter: Files/versions
[Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'length')"
[Vue warn]: Error in nextTick: "TypeError: this.intersectionObserver.observe is not a function"
```
- running unit tests locally
- :robot:

[tests-only] reduce log output when running unit tests of SideBar

---

changelog/unreleased/bugfix-error-message-move
packages/web-app-files/src/views/Personal.vue
packages/web-app-files/tests/unit/views/Personal.spec.js

the variable name should be `error.resourceName`, `error.resource` is not used anywhere
- Fixes #6412 
found when cleaning up unit test log messages:
```
console.warn
Cannot evaluate expression: resourceName
356 |         title = this.$gettext('Failed to move "%{resourceName}"')
357 |         this.showMessage({
> 358 |           title: this.$gettextInterpolate(title, { resourceName: errors[0]?.resourceName }, true),
| ^
359 |           status: 'danger'
360 |         })
361 |         return
at Object.evalInContext (node_modules/vue-gettext/dist/vue-gettext.js:280:21)
at node_modules/vue-gettext/dist/vue-gettext.js:293:28
at String.replace (<anonymous>)
at Function.interpolate (node_modules/vue-gettext/dist/vue-gettext.js:247:24)
at _callee5$ …
```

fix variable name in error object

---

package.json
packages/web-app-files/tests/unit/composables/pagination/usePagination.spec.ts
packages/web-app-files/tests/unit/views/spaces/Project.spec.js
tests/unit/config/jest.init.js

- if there is an unhandled rejection throw an exception
otherwise node 14 will only show a warning
this leads to many crap tests, see #6337
- mock `@files/src/composables` to make the failing tests pass
- ~~blocked by #6337~~
don't allow crap tests
- :robot:

[tests-only] throw an exception on uhandled exception in unit tests

---

packages/web-app-files/tests/unit/views/LocationPicker.spec.js
packages/web-app-files/tests/unit/views/__snapshots__/SharedViaLink.spec.js.snap
packages/web-app-files/tests/unit/views/spaces/Project.spec.js
packages/web-app-files/tests/unit/views/spaces/Projects.spec.js
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Project.spec.js.snap
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap
packages/web-app-files/tests/unit/views/views.setup.js
tests/unit/config/jest.init.js

- mock $ngettext & $pgettext
- shallowMount in Project.spec.js
- mock `<translate>` in Projects.spec.js & LocationPicker.spec.js
- mock v-translate directive
part of #6337
reduce log output in unit tests
`yarn run test:unit 2>&1 | wc -l`
before this PR: 2641
after this PR: 583

[tests-only] remove language related log outputs in unit-tests

---

changelog/unreleased/enhancement-spaces-use-store
packages/web-app-files/src/helpers/resources.js
packages/web-app-files/src/mixins/spaces/actions/delete.js
packages/web-app-files/src/mixins/spaces/actions/disable.js
packages/web-app-files/src/mixins/spaces/actions/editDescription.js
packages/web-app-files/src/mixins/spaces/actions/rename.js
packages/web-app-files/src/mixins/spaces/actions/restore.js
packages/web-app-files/src/views/spaces/Project.vue
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/mixins/spaces/delete.spec.js
packages/web-app-files/tests/unit/mixins/spaces/rename.spec.js
packages/web-app-files/tests/unit/views/spaces/Project.spec.js
packages/web-app-files/tests/unit/views/spaces/Projects.spec.js
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap

Using the store for spaces integrates them seamlessly in our ecosystem and makes it easier to develop spaces even further. E.g. the properties of a space can now be altered without fetching all spaces again. This was achieved by introducing a "buildSpace" method, that transforms a space into a more generic resource object (just like regular files or shares).
Groundwork for https://github.com/owncloud/web/issues/6284 (and basically all space-related issues)

Use the Vue store for spaces

---

changelog/unreleased/bugfix-catch-router-view-names
packages/web-runtime/src/layouts/Application.vue

Apps had to define their route components for named views in the past, either
```js
components: {
app: ComponentName
}
```
or
```js
components: {
fullscreen: ComponentName
}
```
We've removed the named routes in https://github.com/owncloud/web/pull/6401 so that routes now need to be defined as
```js
component: ComponentName
```
This broke "old" apps with an unrendered state, because the router-view with the respective name could not be found anymore.
This PR defines identical router-views for the `default` name and for the old `app` and `fullscreen` names, but all rendered in the same way (inside the app container, because we don't allow apps without topbar anymore).
Also added a deprecation warning. We can basically revert this commit once we release the next major version.
App …

App compatibility for old named routes

---

.drone.star

bump middleware version to v1.4.0
https://github.com/owncloud/owncloud-test-middleware/issues/104

[tests-only] Bumped test middleware version to v1.4.0

---

packages/web-app-files/tests/unit/views/FilesDrop.spec.js
packages/web-app-files/tests/unit/views/__snapshots__/FilesDrop.spec.js.snap

I've fixed an incorrect mock that triggered a code path which requires a working router in `FilesDrop.spec.js`.
As it wasn't the actual purpose of the test, I did not bother to add the router to make that code path work.
If we want to test the behavior for the error condition, we should create a new test case for that.
- Fixes https://github.com/owncloud/web/issues/6130
This was incredibly annoying during development because there were javascript errors in the snapshot that are not stable between node versions. As I'm using node v16 and our CI uses v14 I could not simply commit the adjusted error messages in the snapshot 😜 
- this is a unit test fix ... yarn test:unit

Fix #6130: fix test and remove errors from FilesDrop.spec.js

---

changelog/unreleased/bugfix-return-to-search
packages/web-app-files/src/mixins/fileActions.js
packages/web-app-search/src/index.ts
packages/web-pkg/src/composables/appDefaults/types.ts
packages/web-pkg/src/composables/appDefaults/useAppDefaults.ts
packages/web-pkg/src/composables/appDefaults/useAppNavigation.ts

This allows to define `contextQueryItems` on `route.meta` to specify which query items of the current route should be serialized as `contextQuery` in app urls.
On a less abstract level: this fixes `closeApp` in apps like the `mediaviewer` for search results. Without this change you are redirected to an empty search page, with this you are redirected to the original search.
- needs oC 10, because currently there is no search for oCIS
- search for Portgual in all files, click Portugal.jpg, see mediaviewer opens and closing returns back to search

Context Query Items

---

changelog/unreleased/enhancement-search-context-menu
packages/web-app-files/src/components/AppBar/SelectedResources/BatchActions.vue
packages/web-app-files/src/components/FilesList/ContextActions.vue
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/components/SideBar/Actions/FileActions.vue
packages/web-app-files/src/composables/useIsFilesAppActive.ts
packages/web-app-files/src/mixins/actions/downloadArchive.js
packages/web-app-files/src/mixins/actions/downloadFile.js
packages/web-app-files/src/mixins/actions/favorite.js
packages/web-app-files/src/mixins/actions/navigate.js
packages/web-app-files/src/mixins/actions/showActions.js
packages/web-app-files/src/mixins/actions/showDetails.js
packages/web-app-files/src/mixins/actions/showShares.js
packages/web-app-files/tests/unit/components/Search/List.spec.js

Enable/disable certain file actions outside of the file application.
- Fixes #6293 
Several file actions (currently) work or don't work outside the files app. In general anything that just interacts with the backend works fine, actions that rely on e.g., the sidebar, don't work in the search app for instance.
- needs oC 10
Decide whether we want to make the search results selectable in the ResourcesTable, to prepare for multi select and archive download.
Currently we have no search in oCIS and `isDownloadAsArchiveAvailable` is false on oC 10, so currently it's probably just confusing for no benefit... tying this to `isDownloadAsArchiveAvailable` would be possible, but feels weird as well ... happy to hear other opinions :) 
Adding a check whether

Fix search context menu

---

packages/web-app-files/src/components/AppBar/AppBar.vue

When #6287 got merged, you forgot to update `addAppProviderFile`, so creating files via app provider would fail when stating.
edit: the normal creation of files was also broken in public links

Fix file creation

---

changelog/unreleased/enhancement-spaces-sidebar
packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue
packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/components/SideBar/SpaceInfo.vue
packages/web-app-files/src/components/SpaceQuota.vue
packages/web-app-files/src/fileSideBars.js
packages/web-app-files/src/mixins/spaces/actions/delete.js
packages/web-app-files/src/mixins/spaces/actions/disable.js
packages/web-app-files/src/mixins/spaces/actions/editDescription.js
packages/web-app-files/src/mixins/spaces/actions/rename.js
packages/web-app-files/src/mixins/spaces/actions/restore.js
packages/web-app-files/src/mixins/spaces/actions/showDetails.js
packages/web-app-files/src/router/spaces.ts
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/components/SideBar/Details/SpaceDetails.spec.js
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/SpaceDetails.spec.js.snap
packages/web-app-files/tests/unit/components/SideBar/SpaceInfo.spec.js
packages/web-app-files/tests/unit/components/SideBar/__snapshots__/SpaceInfo.spec.js.snap
packages/web-app-files/tests/unit/components/SpaceQuota.spec.js
packages/web-app-files/tests/unit/components/__snapshots__/SpaceQuota.spec.js.snap
packages/web-app-files/tests/unit/mixins/spaces/disable.spec.js
packages/web-app-files/tests/unit/mixins/spaces/editDescription.spec.js
packages/web-app-files/tests/unit/mixins/spaces/rename.spec.js
packages/web-app-files/tests/unit/mixins/spaces/restore.spec.js
packages/web-app-files/tests/unit/mixins/spaces/showDetails.spec.js
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap
packages/web-client/src/index.ts
packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.js.snap
tests/unit/stubs/index.js

This PR introduces the basic space sidebar. Some things that need to come later:
* People- and Link-Management (will be a separate PR as this is a bigger story)
* Edit Image, Subtitle, Description (see https://github.com/owncloud/web/pull/6410)
* Permissions (also a separate PR, needs to be done everywhere for spaces)
- https://github.com/owncloud/web/issues/6284

Implement right sidebar for spaces

---

packages/web-app-files/src/components/FilesList/ContextActions.vue

We've had an visual bug in the context menu that caused any text break to center the text,
which looked off and weird.
Is now fixed by text-align:left which causes the break part of the text to start at the same position
as the first part

[full-ci]Too long text breaks incorrectly

---

changelog/unreleased/enhancement-history-mode

in the Changelog for VUE history mode i mentioned the wrong base-tag attribute.
This fixes it.

fix changelog

---

changelog/unreleased/bugfix-breadcrumb-root-path
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/views/Personal.vue

Point `All Files` breadcrumb link to `/` instead of the configured homeFolder.
- Fixes https://github.com/owncloud/web/issues/6327
https://github.com/owncloud/web/issues/6327
- unit tests

revert all files breadcrumb link to /

---

changelog/unreleased/bugfix-do-not-load-from-cache
packages/web-app-draw-io/src/App.vue
packages/web-pkg/src/composables/appDefaults/useAppFileHandling.ts

When apps (i.e Drawio) try to load a file, the browser caches the request.
If the file was modified somewhere else, this causes inconsistent results which prevent saving any changes until the cache is properly cleared.
We had observed this is the past in our text editor, hence the `noCache` addition to the SDK. Now we also saw it in Drawio.

Do not load files from cache

---

changelog/unreleased/bugfix-update-file-list-on-new-file
changelog/unreleased/enhancement-redesign-create-upload-buttons
package.json
packages/web-app-draw-io/src/index.js
packages/web-app-files/src/components/ActionMenuItem.vue
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/components/AppBar/Upload/FileUpload.vue
packages/web-app-files/src/components/AppBar/Upload/FolderUpload.vue
packages/web-app-files/src/index.js
packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js
packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.js
packages/web-app-files/tests/unit/components/AppBar/Upload/FolderUpload.spec.js
packages/web-app-markdown-editor/src/index.js
packages/web-runtime/package.json
tests/acceptance/features/webUIFilesSearch/search.feature
tests/acceptance/pageObjects/personalPage.js
tests/e2e/support/page/files/allFiles.ts
yarn.lock

[full-ci] Redesign New- and Upload-Buttons

---

tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature

after unsharing resources, with this pr:
- check for the resources state in the shared with me declined view
- then only browse to the files page and check for the presence of the unshared resource
with this order, the tests are passing solid. see demonstration at https://github.com/owncloud/web/pull/6112
- Fixes https://github.com/owncloud/web/issues/6097

[test-only] check in shared with me page first after unsharing

---

docs/deployments/oc10-app.md

Fixes https://talk.owncloud.com/channel/general?msg=2Dff3wJCg74kNqviG

Fix old appSwitcher icon in OC10 deployment docs

---

tests/acceptance/features/webUIFiles/download.feature

Refactor the scenarios so that the needed file(s) are created on the server before Alice logs in. That should ensure that the file(s) are definitely listed on the web UI files page.
In the issue, it seems that sometimes the expected file does not appear on the files page. The failure does not happen often, so is not possible to reproduce. The changes here should improve it.
- Fixes #6001 
CI

[tests-only] [full-ci] Refactor download.feature to make it more reliable

---

changelog/unreleased/enhancement-redesign-create-upload-buttons
packages/web-app-files/src/views/Personal.vue
packages/web-app-files/src/views/PublicFiles.vue

"+ New" button is now "New" and "Upload", this PR adjusts CTA wording accordingly.

Fix wording of create/upload CTA after "+ new" button split

---

changelog/unreleased/bugfix-password-protected-public-link-capabilities
packages/web-app-files/src/views/PublicFiles.vue

as title says, enable capability loading for password protected public links.
- Fixes #5863
- Needs: https://github.com/owncloud/ocis/pull/3229
https://github.com/owncloud/web/issues/5863
- unit & integration tests

[full-ci] enable capability loading for password protected public links

---

changelog/unreleased/bugfix-readme-content-modal-test-write-error-output
packages/web-app-files/tests/unit/components/Spaces/ReadmeContentModal.spec.js

Bugfix: Don't write error message on passing ReadmeContentModal.spec.js test
ReadmeContentModal.spec.js test doesn't write error output anymore while passing
- Fixes #6337

Don't write error message on passing ReadmeContentModal.spec.js test

---

__mocks__/sdk.js
changelog/unreleased/bugfix-app-file-handling
packages/web-app-files/src/helpers/resource/resource.ts
packages/web-app-files/src/helpers/resources.js
packages/web-app-files/tests/unit/helpers/resource/sameResource.spec.ts
packages/web-app-media-viewer/src/App.vue
packages/web-pkg/src/composables/appDefaults/useAppFileHandling.ts
packages/web-runtime/src/router/index.js

This PR fixes a bunch of scenarios where mediaviewer (and possibly other apps) were broken:
- `getUrlForResource` was using an ugly hack to retrieve a webdav url before `webDavPath` was introduced in https://github.com/owncloud/web/pull/6287, we could now get rid of that hack and make this function work for spaces and a bunch of other contexts work as well (Kudos for that PR!!)
- mediaviewer: clicking next/previous updated the url with the resource `path` instead of the `webDavPath`: that broke reloading
- router.parseQuery: our `qs.parse` invocation was missing the `allowDots` option, so nested objects in query were not correctly parsed and closing the apps, at least on public links was broken 
There are two oCIS bugs left, which cause the mediaviewer to fail
- for images in spaces …

[full-ci] Fix several file handling issues for apps

---

changelog/unreleased/enhancement-space-quota
packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue
packages/web-app-files/src/components/Spaces/QuotaModal.vue
packages/web-app-files/src/mixins/spaces/actions/editQuota.js
packages/web-app-files/src/views/spaces/Project.vue
packages/web-app-files/tests/unit/components/Spaces/QuotaModal.spec.js
packages/web-app-files/tests/unit/components/Spaces/ReadmeContentModal.spec.js
packages/web-app-files/tests/unit/mixins/spaces/editQuota.spec.js
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Project.spec.js.snap
packages/web-runtime/package.json
yarn.lock

Enhancement: Allow updating space quota
We have implemented a way to update the space's quota
- Fixes https://github.com/owncloud/web/issues/6470
- test case 1:
- test case 2:
- ...

Space quota

---

packages/web-runtime/src/pages/account.vue
packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.js.snap
packages/web-runtime/tests/unit/pages/account.spec.js
tests/acceptance/features/webUIAccount/accountInformation.feature
tests/acceptance/pageObjects/accountPage.js
tests/acceptance/stepDefinitions/accountContext.js

- added unit tests for the account page
- removed accounts page related acceptance tests other than verifying the successful page load
- Part of https://github.com/owncloud/web/issues/6475
- :robot:

[tests-only] add unit tests for the account page and minimize coverage from acceptance tests

---

changelog/unreleased/enhancement-add-space-share-panel-watcher
packages/web-app-files/src/components/SideBar/Shares/SpaceShares.vue
packages/web-app-files/src/views/spaces/Project.vue
packages/web-app-files/src/views/spaces/Projects.vue

We've added a watcher for the share panel of a space to ensure seamless navigation via the share indicator.
- See comment: https://github.com/owncloud/web/pull/6455#discussion_r820598017

Add a watcher for the share panel of a space

---

changelog/unreleased/enhancement-space-update-store
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/components/SideBar/Shares/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/SpaceShares.vue
packages/web-app-files/src/helpers/resources.js
packages/web-app-files/src/store/actions.js
packages/web-app-files/tests/integration/specs/peopleExpirationDate.spec.js
packages/web-app-files/tests/unit/store/actions.spec.js

We now update the stored space after its members have been changed. Also, the permission-object of a built space has been simplified in the course of this.
Currently the only way to update the space object is by fetching the space again because the response from the OCS-API gives us no usable information. As soon as UUIDs have been introduced to the OCS-API, we could use those instead.
Note that there is still a caching bug in OCIS. E.g. when navigating between space's share panels via the share indicator, and adding/removing members, and then switching back and forth between the share panels again, the change seems to be lost. A reload reveals that this is actually not the case.
- Groundwork for https://github.com/owncloud/web/pull/6531

Update the stored space object after members have been changed

---

changelog/unreleased/enhancement-account-page-loading
packages/web-runtime/src/pages/account.vue
packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.js.snap
packages/web-runtime/tests/unit/pages/account.spec.js

As a followup of https://github.com/owncloud/web/pull/6522 I've removed code duplication in the template and limited the loading spinner to the part of the template where actual loading happens (only the group membership info). The rest of the account info page now loads immediately.
- unit tests

Cleaned up account info page

---

changelog/unreleased/enhancement-spaces-permissions
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/fileSideBars.js
packages/web-app-files/src/helpers/resources.js
packages/web-app-files/src/mixins/spaces/actions/delete.js
packages/web-app-files/src/mixins/spaces/actions/disable.js
packages/web-app-files/src/mixins/spaces/actions/editDescription.js
packages/web-app-files/src/mixins/spaces/actions/editQuota.js
packages/web-app-files/src/mixins/spaces/actions/editReadmeContent.js
packages/web-app-files/src/mixins/spaces/actions/rename.js
packages/web-app-files/src/mixins/spaces/actions/restore.js
packages/web-app-files/src/mixins/spaces/actions/setImage.js
packages/web-app-files/src/mixins/spaces/actions/setReadme.js
packages/web-app-files/src/mixins/spaces/actions/uploadImage.js
packages/web-app-files/src/views/spaces/Project.vue
packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js
packages/web-app-files/tests/unit/components/FilesList/ContextActions.spec.js
packages/web-app-files/tests/unit/mixins/spaces/delete.spec.js
packages/web-app-files/tests/unit/mixins/spaces/disable.spec.js
packages/web-app-files/tests/unit/mixins/spaces/editQuota.spec.js
packages/web-app-files/tests/unit/mixins/spaces/editReadmeContent.spec.js
packages/web-app-files/tests/unit/mixins/spaces/restore.spec.js
packages/web-app-files/tests/unit/mixins/spaces/setImage.spec.js
packages/web-app-files/tests/unit/mixins/spaces/setReadme.spec.js
packages/web-app-files/tests/unit/views/spaces/Projects.spec.js
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Project.spec.js.snap
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap
packages/web-runtime/src/store/user.js

We've implemented the spaces permission concept and improved the code structure for further permission changes.
Note that this PR does not yet include the permission check for the "Create New Space"-button. The permission for this is bound to the current user role, which needs some more in-depth work.
- Related to https://github.com/owncloud/web/issues/6283

Implement the spaces permission concept

---

changelog/unreleased/bugfix-space-member-count
packages/web-app-files/src/helpers/resources.js
packages/web-app-files/src/views/spaces/Project.vue
packages/web-app-files/tests/unit/views/spaces/Project.spec.js

We've fixed a bug where opening the sidebar for a file inside a space caused the member count of the space to disappear.
Also reduced the complexity a bit by removing the `loadSharesTask` within a space. Counting the members can now be done via the space object itself thanks to https://github.com/owncloud/web/pull/6545.

Prevent the member count inside a space from disappearing

---

changelog/unreleased/bugfix-resolve-private-link
changelog/unreleased/enhancement-private-link-routing
packages/web-app-files/src/views/PrivateLink.vue

For private links to a folder: route directly into the folder instead of the parent. Routing to parent is only valid for files.
- Fixes https://github.com/owncloud/web/issues/5533
- CI

Route into folders instead of parents in private links

---

packages/web-app-files/src/components/FilesList/ContextActions.vue

Changes the hover effect from underline to background-color 
- Fixes https://github.com/owncloud/owncloud-design-system/issues/2004
We find, color hover fits better for actions than the underline effect which is commonly used for links.

Change hover effect for context menu to background-color change

---

changelog/unreleased/enhancement-load-space-images-as-preview
packages/web-app-files/src/services/thumbnail.ts

The context menu in public links file lists was broken due to an initialization issue of the new `thumbnailService`. This PR only fixes the symptom, not the initialization which is still not being called. Context menu is functional again.
Hardening

Fix context menu in public links

---

.drone.env

This PR bumps OCIS commit id to match the latest
- part of: https://github.com/owncloud/QA/issues/731
- CI

[full-ci] [tests-only] Bump ocis commit id

---

changelog/unreleased/bugfix-space-permission-destructing
packages/web-app-files/src/helpers/resources.js

We fixed TypeErrors when trying to destruct undefined properties in the space permissions checks by providing a default value.
They appeared e.g. when navigating into a subfolder within a space.

Fix TypeErrors when trying to destruct undefined properties

---

changelog/unreleased/bugfix-public-link-sidebar-panels
packages/web-app-files/src/fileSideBars.js

Hide people, links and versions on public links... again.
- Fixes https://github.com/owncloud/web/issues/2090
CI

Hide people, links, versions in public links

---

changelog/unreleased/bugfix-resize-observer-errors
packages/web-app-files/src/views/spaces/Project.vue

We've fixed a bug where the resize observer crashes within subfolders of a space because there is no element to observe.

Fix resize observer errors within subfolders of a space

---

changelog/unreleased/enhancement-move-share-indicators
changelog/unreleased/enhancement-update-ods
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/tests/unit/views/__snapshots__/Trashbin.spec.js.snap
packages/web-runtime/package.json
tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
yarn.lock

- Fixes #5976
- test case 1:
- test case 2:
- ...

[full-ci] Move OcStatusIndicators in separate column

---

__fixtures__/sidebarNavItems.js
changelog/unreleased/bugfix-iframe-border
changelog/unreleased/enhancement-shares-overview
package.json
packages/web-app-files/src/components/AppBar/SharesNavigation.vue
packages/web-app-files/src/components/AppBar/ViewOptions.vue
packages/web-app-files/tests/unit/components/AppBar/__snapshots__/SharesNavigation.spec.js.snap
packages/web-runtime/package.json
packages/web-runtime/src/App.vue
tests/acceptance/pageObjects/appBarActions.js
yarn.lock

Improve sharing tab style & add icons

---

tests/e2e/cucumber/publicLinkToFolderJourney.feature
tests/e2e/cucumber/step_definitions/app.files.ts
tests/e2e/support/cta/files/index.ts
tests/e2e/support/cta/files/misc.ts
tests/e2e/support/cta/files/publicLink.ts
tests/e2e/support/page/files/publicLink.ts
tests/e2e/support/page/publicLinkPage.ts

This PR adds step implementation for testing 
- unauthorized users opening the public link of a folder.
- unauthorized user uploads new file
- unauthorized user refreshes page. (page is empty)
Folder public link was created with name, password, expiration date, and **`role: uploader`**
- Before merging this PR,  https://github.com/owncloud/web/pull/6422 PR must be merged.
- Part of https://github.com/owncloud/web/issues/6389
This PR adds tests step for unauthorized user accessing the last created public link of a folder
- CI
- Locally

[tests-only] Add e2e test for unauthorized user opening public link

---

packages/web-app-files/src/services/folder/loaderPersonal.ts

Fixes issue that was introduced by https://github.com/owncloud/web/pull/6563/files. `SET_QUOTA` does not live under the `Files` namespace.

Fix SET_QUOTA call in the loader for the personal files list

---

changelog/unreleased/enhancement-move-share-indicators
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.js.snap

See https://github.com/owncloud/web/issues/5976

[full-ci] Use OcStatusIndicators for FileDetails

---

changelog/unreleased/enhancement-polish-viewoptions
packages/web-app-files/src/components/AppBar/ViewOptions.vue
packages/web-runtime/themes/owncloud/theme.json

See https://github.com/owncloud/web/issues/6492

Polish ViewOptions hover effect

---

tests/e2e/support/objects/app-files/share/actions.ts
tests/e2e/support/objects/app-files/share/index.ts

Visiting the personal space failed often in the e2e tests after a share was accepted. This PR fixes that behavior by removing an earlier workaround which is no longer needed.
- Fixes https://github.com/owncloud/web/issues/6610

fix flaky share accept e2e test action

---

changelog/unreleased/enhancement-improve-space-resource-loading
packages/web-app-files/src/services/folder/loaderProject.ts
packages/web-app-files/src/views/spaces/Project.vue

I recently noticed some issues when navigating within spaces when is comes to loading the image & readme also also (once again) the resize observer. So I improved the loading of resources within a space. This enhances performance and overall stability within spaces.
* A new parameter was introduced to determine if a space needs to be fetched or not. Route changes within a space do not require the space to be fetched again. This also ensures that the space image and readme won't be fetched in subfolders.
* The space now gets set at the end of the loading task. This ensures that the space task has finished as soon as the image and readme get loaded.

Improve resource loading within spaces

---

changelog/unreleased/change-context-route-name-in-query
packages/web-app-draw-io/src/index.js
packages/web-app-external/src/index.js
packages/web-app-files/src/mixins/fileActions.js
packages/web-app-markdown-editor/src/index.js
packages/web-app-media-viewer/src/index.js
packages/web-pkg/src/composables/appDefaults/useAppDefaults.ts
packages/web-pkg/src/composables/appDefaults/useAppNavigation.ts
packages/web-runtime/src/router/index.js

This removes `contextRouteName` from app parameters. It's handled fully automatically in the url query, so apps can just use the provided `useAppDefaults` composable and don't need to mess with urls themselves for something they really should not have to care about.
Nice sideeffect is that it's now visible further in the back of the url and hopefully less confusing for users.
Make everything more streamlined and straightforward for developing file editors/viewers.
I've also taken care that changing the query item name is also just a two line patch, as we plan to adjust the naming in the near future.
- test case 1:
- test case 2:
- ...

[full-ci] Remove contextRouteName from app params and add it to the query instead

---

changelog/unreleased/enhancement-share-inheritance-indicators
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.js.snap
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.js.snap

We've implemented the share inheritance indicators in the share sidebar panel. They indicate whether a resource is shared indirectly via one of its parent folders.
- Fixes https://github.com/owncloud/web/issues/6528

Implement the share inheritance indicators

---

changelog/unreleased/bugfix-sort-order
packages/web-app-files/src/composables/sort/useSort.ts
packages/web-app-files/tests/unit/composables/sort/useSort.spec.ts

Fix sorting to respect natural sort order again. Also used the chance to switch over to `Intl.Collator` which is considered to be a performance improvement, compared to `localeCompare`. 
- Fixes https://github.com/owncloud/web/issues/6532
Added an example for non-natural order being sorted to natural sort order to the existing unit test for the sorting composable.

Fix natural sort order

---

changelog/unreleased/bugfix-rename-parent
packages/web-app-files/src/mixins/actions/rename.js
packages/web-app-files/tests/unit/mixins/actions/rename.spec.js

Fetching fileinfo during parent folder rename had malformed webdav paths. Fixed it...
- Fixes https://github.com/owncloud/web/issues/6516

Fix parent folder rename

---

changelog/unreleased/enhancement-editor-role
changelog/unreleased/enhancement-optional-ui-elements
packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkEdit.vue
packages/web-app-files/src/components/SideBar/Shares/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/RoleDropdown.vue
packages/web-app-files/src/helpers/resources.js
packages/web-app-files/src/helpers/share/role.ts
packages/web-app-files/src/mixins/actions/delete.js
packages/web-app-files/src/mixins/actions/emptyTrashBin.js
packages/web-app-files/src/mixins/actions/rename.js
packages/web-app-files/tests/unit/components/SideBar/Shares/RoleDropdown.spec.js
packages/web-app-files/tests/unit/helpers/share/role.spec.ts
packages/web-app-files/tests/unit/mixins/actions/delete.spec.js

As we discussed, I'm trying to push some of our changes, in particular I refactored the code to make some parts optional. 
Renaming a share, permanently deleting files and showing the custom permissions role are now optional. By default, it keeps the same behavior as the current master.
Added the possibility to add "tags" while searching for users (as we discussed).
Also as discussed, I've added the "editor" role for single files public links. This seems not to be possible with oc10, so I've added a check to enable it only for oCIS.
(this needs another fix... I saw the "rename" button on the file and I shouldn't, but at least if fails when I tried to do it)
@elizavetaRa is still working on the css for the drop down menus.
Fixes #6324
Fixes #5913

[full-ci] Multiple fixes

---

changelog/unreleased/bugfix-oc10-navigation-entry-names
packages/web-integration-oc10/lib/Controller/ConfigController.php

When fetching navigation entries from oC10, we previously used the app's names. This caused issues when the navigation entry ID and the app ID differ. Also, the navigation entries did not match with the ones in the classic UI.
This has been fixed as we now use the navigation entry name, which falls back to the app name if not given.
- Fixes https://github.com/owncloud/web/issues/6585

Use oC10 navigation entry names

---

changelog/unreleased/enhancement-spaces-link-sharing
packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue
packages/web-app-files/src/components/SideBar/Links/FileLinks.vue
packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkActions.vue
packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkEdit.vue
packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkInfo.vue
packages/web-app-files/src/components/SideBar/Shares/SpaceShares.vue
packages/web-app-files/src/fileSideBars.js
packages/web-app-files/src/mixins/actions/createPublicLink.js
packages/web-app-files/src/quickActions.js
packages/web-app-files/src/services/folder/loaderProject.ts
packages/web-app-files/src/store/actions.js
packages/web-app-files/tests/integration/specs/linkExpirationDate.spec.js
packages/web-app-files/tests/integration/specs/sidebar.spec.js
packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkEdit.spec.js
packages/web-app-files/tests/unit/components/SideBar/Links/PublicLinks/LinkInfo.spec.js
packages/web-app-files/tests/unit/store/actions.spec.js
packages/web-runtime/package.json
yarn.lock

Spaces and their resources can now be shared via links.
~Needs https://github.com/owncloud/owncloud-sdk/pull/1027 to work properly.~ -> included via the SDK version bump.
- https://github.com/owncloud/web/issues/6283

Implement link sharing for and in spaces

---

tests/acceptance/customCommands/isAnyElementVisible.js
tests/acceptance/pageObjects/FilesPageElement/appSideBar.js

This PR adds a new Nightwatch custom command `.isAnyElementVisible`. It takes a selector that may resolve multiple elements and checks the visibility of each element until found true.
For example:
selector in `isSideBarOpenForResource` resolves more than 2 elements (from sidebar: `details`, `actions`,`people`,`links`,`versions`). In order to check the visibility of the sidebar for a resource, `isVisible` API won't work as it only checks the visibility of the first element which means if `details` panel is the first element and `actions` is the second one then `isVisible` will return `false` whenever the `actions` sidebar for a resource is open. So that we have to check through all the resolved elements and return visible `true` if any of the element is visible (i.e. side-bar is open for a …

[tests-only][full-ci] Flaky private link acceptance tests

---

changelog/unreleased/enhancement-spaces-group-sharing
packages/web-app-files/src/components/SideBar/Shares/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/store/actions.js

Resources within a space can now be shared with user groups. Spaces themselves can't be shared with groups, therefore those have been removed from the autocomplete results when adding members to a space.
Needs `owncloud-sdk` version `3.0.0-alpha.4` to work. However, it's not included in this PR as we already bump it via https://github.com/owncloud/web/pull/6633.
- https://github.com/owncloud/web/issues/6283

Implement group sharing for resources within spaces

---

tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js

The issue with #6594 was that different files/folders were selected for actions.
This was due to scrolling from `waitForFileVisible`. Custom scrolling is not required as the Nightwatch APIs will scroll elements into view before performing actions.
Fixes https://github.com/owncloud/web/issues/6594

[full-ci][tests-only] Fix waitForFileVisible function

---

changelog/unreleased/enhancement-spaces-overview-topbar
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/components/AppBar/CreateSpace.vue
packages/web-app-files/src/components/AppBar/ViewOptions.vue
packages/web-app-files/src/router/spaces.ts
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/components/AppBar/CreateSpace.spec.js
packages/web-app-files/tests/unit/views/spaces/Projects.spec.js
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap

Align the topbar layout of the spaces overview with the other pages. In the course of this: 
* Moved the "Create Space"-button to its own component which is then used by the topbar
* Included the sidebar quick action
- Fixes https://github.com/owncloud/web/issues/6641
old:
new:

Adjust the topbar layout on the spaces overview

---

.eslintrc.js
package.json
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/views/Personal.vue
packages/web-runtime/src/App.vue
tsconfig.json
yarn.lock

This enables typescript in `.vue` files and adjusts the linter to deal with it properly.
As you can see we need to wrap components in `defineComponent` from `composition-api` to make the type checking work at all. Before you ask: yes, it's completely valid to wrap components that use only options api.
After I have replaced the old Vetur extension with the new [Volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar) extension in VS Code (this PR is mostly based on its README), I have some basic autocompletion and type checking working in `.vue` files. 
It works very well in the templates, not so much in the `script` part of the SFC. For some reason autocompletion and typechecking seems to only really work in the `data()` function, not in setup(), not in methods, not …

Enable typescript in single file components

---

packages/web-app-files/src/App.vue
packages/web-app-files/src/components/SideBar/Actions/FileActions.vue
packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/Details/FileDetailsMultiple.vue
packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue
packages/web-app-files/src/components/SideBar/Links/FileLinks.vue
packages/web-app-files/src/components/SideBar/NoSelection.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/components/SideBar/Shares/SpaceShares.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
packages/web-app-files/src/fileSideBars.ts
packages/web-app-files/src/helpers/resource/resource.ts
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/helpers/share/index.ts
packages/web-app-files/src/helpers/share/share.ts
packages/web-app-files/src/helpers/user/index.ts
packages/web-app-files/src/helpers/user/types.ts
packages/web-app-files/tests/unit/components/SideBar/SideBar.spec.js
packages/web-app-files/tests/unit/composables/sort/useSort.spec.ts
packages/web-pkg/src/components/sidebar/SideBar.vue
packages/web-pkg/src/components/sidebar/index.js
packages/web-pkg/src/components/sidebar/types.ts

- Fixes #6658 
Make SideBar reusable.
- test case 1:
- test case 2:
- ...

[full-ci] Fix #6658: split SideBar into separate view and business logic components

---

changelog/unreleased/enhancement-full-scree-apps
packages/web-app-external/src/App.vue
packages/web-app-external/tests/unit/__snapshots__/app.spec.js.snap

This allows for example presentation apps to enter full screen.

Allow full screen external apps (i.e presentation mode)

---

changelog/unreleased/enhancement-shared-with-column-shared-with-me
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/views/shares/SharedWithMe.vue

Supersedes https://github.com/owncloud/web/pull/6699
Adds "Shared with" column for incoming shares
- Fixes https://github.com/owncloud/web/issues/6140
Incoming shares can also have a group as sharee, the information about it can be relevant information for the user.

Shared with on shared with me

---

packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js

fix unit test log output of FileShares.spec.js
get rid of these log outputs, make the tests work correctly
```
console.error
[Vue warn]: The setup binding property "sharesLoading" is already declared.
found in
---> <FileShares>
<Root>
at Object.warn (node_modules/vue/dist/vue.runtime.common.dev.js:621:15)
at warn (node_modules/@vue/composition-api/dist/vue-composition-api.common.js:427:18)
at asVmProperty (node_modules/@vue/composition-api/dist/vue-composition-api.common.js:1764:13)
at node_modules/@vue/composition-api/dist/vue-composition-api.common.js:2006:17
at Array.forEach (<anonymous>)
at initSetup (node_modules/@vue/composition-api/dist/vue-composition-api.common.js:1982:39)
at VueComponent.wrappedData (node_modules/@vue/composition-api/dist/vue-composition-api.commo …
```

[tests-only] fix log output of unit test in FileShares.spec

---

packages/web-app-user-management/tests/unit/views/Users.spec.js

declare roles and userAssignments props in Users view unit tests
get rid of log output like
```
console.error
[Vue warn]: Invalid prop: type check failed for prop "userAssignments". Expected Array, got Undefined 
found in
---> <UsersList>
<Anonymous>
<Root>
at warn (node_modules/vue/dist/vue.runtime.common.dev.js:621:15)
at assertProp (node_modules/vue/dist/vue.runtime.common.dev.js:1702:5)
at validateProp (node_modules/vue/dist/vue.runtime.common.dev.js:1628:5)
at loop (node_modules/vue/dist/vue.runtime.common.dev.js:4664:17)
at initProps (node_modules/vue/dist/vue.runtime.common.dev.js:4695:33)
at initState (node_modules/vue/dist/vue.runtime.common.dev.js:4638:21)
at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:5001:5)
```
- running unit tests

[tests-only] set extra props in unit tests

---

packages/web-app-files/tests/unit/views/views.shared.ts

mock v-translate here also, simmilar to https://github.com/owncloud/web/pull/6404/files#diff-0dd79c75d790d047f8dde209581a57ea4dc2708fcda916ad00f5aee313d7e02dR38
- part of #6337 
get rid of warnings like
```
console.warn
No translations found for en_US
at Object.getTranslation (node_modules/vue-gettext/dist/vue-gettext.js:357:19)
at updateTranslation (node_modules/vue-gettext/dist/vue-gettext.js:700:33)
at bind (node_modules/vue-gettext/dist/vue-gettext.js:756:7)
at callHook$1 (node_modules/vue/dist/vue.runtime.common.dev.js:6702:7)
at _update (node_modules/vue/dist/vue.runtime.common.dev.js:6623:7)
at Array.updateDirectives (node_modules/vue/dist/vue.runtime.common.dev.js:6604:5)
at invokeCreateHooks (node_modules/vue/dist/vue.runtime.common.dev.js:6093:22)
at createElm …
```

[tests-only] mock v-translate directive in views tests

---

.drone.star

fixes the unit and integration tests for forks (where the master branch is not up to date)
- Unblocks https://github.com/owncloud/web/pull/6727
- test case 1:
- test case 2:
- ...

fix fork handling for unit and integration tests

---

packages/web-container/index.html.ejs

We discussed this some weeks ago. Noop change, since when the app loads it will change it.
But with this, while the app is not loaded, we see the spinner centered.
---
Can we also commit a hover effect to the quick actions on the files table? The idea is to hide them and only show on hover, like so:

Vertically centered loading spinner or error message on startup

---

changelog/unreleased/enhancement-simple-editor
packages/web-runtime/src/container/bootstrap.ts

The `markdown-editor` has recently been renamed to [`simple-editor`](https://github.com/owncloud/web/pull/6667). In order to not break old configs this PR adds an alias for the app bootstraping (i.e. when `markdown-editor` gets found in a config.json it gets replaced with `simple-editor` during runtime, before the apps are being loaded).

Add markdown-editor to simple-editor alias for config compatibility

---

packages/web-app-files/src/views/spaces/Project.vue

Fix triggering show members button in project space.
Probably broke in https://github.com/owncloud/web/pull/6689
- Fixes https://github.com/owncloud/web/issues/6757

Fix triggering show members button in project space

---

changelog/unreleased/enhancement-customizable-feedback-link
docs/getting-started.md
packages/web-runtime/src/components/Topbar/FeedbackLink.vue
packages/web-runtime/src/components/Topbar/TopBar.vue
packages/web-runtime/tests/unit/components/Topbar/FeedbackLink.spec.js

Adds configuration options for overwriting feedback link props
- Works towards https://github.com/owncloud/web/issues/6702
- unit tests to test the overrides

Feedback link customization

---

packages/web-app-files/tests/unit/views/shares/SharedWithOthers.spec.js
packages/web-app-files/tests/unit/views/shares/__snapshots__/SharedWithOthers.spec.js.snap

unit test at `packages/web-app-files/tests/unit/views/shares/SharedWithOthers.spec.js`
>SharedWithOthers view › when the wrapper is not loading anymore › when length of paginated resources is greater than zero › should load the resource table with correct props
started failing in recent ci builds. check the related issue for more details
Imo the problem is with the relative sdate used in the `ResourceTable` component used by `SharedWithOthers` view. We use resources from the fixtures with constant stime set.
The calculated relative sdate was 9 months previously and is 10 months now. It will keep on rising every month. So maybe it's better to only assert for props rather matching the whole html snapshot.
With this PR:
- match only props for the `ResourceTable`
- update related screenshots …

[unit-tests] fix failing `packages/web-app-files/tests/unit/views/shares/SharedWithOthers.spec.js`

---

docker-compose.yml

Literally the same as, #6773 but for the local dev env we use. 
`demo users are now opt in and therefore re-enabled in this PR`
- extends #6773

add demo users flag to docker dev env

---

changelog/unreleased/enhancement-replace-deprecated-substr
packages/web-app-files/src/mixins/actions/rename.js
packages/web-app-files/src/mixins/deleteResources.js
packages/web-app-files/src/store/actions.js
packages/web-app-preview/src/App.vue
packages/web-runtime/src/components/Topbar/Notifications.vue
rollup.config.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated .
I tested the return of each statement to make sure it's still the same as before

refactor: replace deprecated String.prototype.substr()

---

packages/web-app-user-management/package.json
packages/web-app-user-management/src/components/Groups/GroupsList.vue
packages/web-app-user-management/src/components/Users/UsersList.vue
packages/web-app-user-management/src/index.js
packages/web-app-user-management/src/search/filter/index.ts
packages/web-app-user-management/src/search/index.ts
packages/web-app-user-management/src/services/index.ts
packages/web-app-user-management/src/services/registry.ts
packages/web-app-user-management/tests/unit/components/Groups/GroupsList.spec.js
packages/web-app-user-management/tests/unit/components/Users/UsersList.spec.js
yarn.lock

handover @JanAckermann 
- Fixes #6674
- test case 1:
- test case 2:
- ...

Add search to usersManagement

---

packages/web-app-text-editor/src/App.vue

This fixes the readonly flag for the texteditor when the backend returns WebDAVPermissions `W` (FileUpdateable)
- Occured during ocis Release
Make Single File Sharing in public links work
- Manually
```xml
<?xml version="1.0"?>
<d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
<d:response>
<d:href>/remote.php/dav/public-files/OWDoMgbKaUcKRAz/</d:href>
<d:propstat>
<d:prop>
<oc:permissions/>
<d:resourcetype>
<d:collection/>
</d:resourcetype>
<oc:public-link-item-type>folder</oc:public-link-item-type>
<oc:public-link-share-datetime>Thu, 14 Apr 2022 10:51:11 GMT</oc:public-link-share-datetime>
<oc:public-link-share-owner>admin</oc:public-link-share-owner>
</d:prop>
<d:status>HTTP/1.1 200 OK</d:status>
</d:propstat>
<d:propstat>
<d:prop> …
```

fix readonly flag in texteditor

---

packages/web-app-draw-io/src/App.vue
packages/web-app-external/src/App.vue
packages/web-app-external/src/index.js
packages/web-app-external/tests/unit/app.spec.js
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/mixins/fileActions.js
packages/web-pkg/src/composables/appDefaults/types.ts
packages/web-pkg/src/composables/appDefaults/useAppDefaults.ts
packages/web-pkg/src/composables/appDefaults/useAppFileHandling.ts
packages/web-pkg/src/composables/appDefaults/useAppNavigation.ts

The pr changes external apps route to take filePath instead of fileId. It extracts fileName from filePath and sets document.title to <fileName> - <appName>
- Fixes https://github.com/owncloud/web/issues/5958
Current document title for external apps is not helpful in understanding, which file is open and with which app. By several open files, it's hard to find the right one.

Show filename and app name in external app tab title

---

changelog/unreleased/enhancement-add-unshare-confirmation-dialog
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/SpaceMembers.spec.js
tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
tests/e2e/support/objects/app-files/share/actions.ts

Enhancement: Add un-share confirmation dialog
We have implemented a confirmation dialog, which pops up if the user clicks the remove share button
- Fixes https://github.com/owncloud/web/issues/6728
- test case 1:
- test case 2:
- ...

[full-ci] Implement unshare confirm dialog

---

changelog/unreleased/enhancement-add-contextual-help
changelog/unreleased/enhancement-bump-ods-13.1.0-rc.5
config/config.json.dist
config/config.json.sample-oc10
config/config.json.sample-ocis
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/helpers/contextualHelpers.js
packages/web-app-files/src/views/shares/SharedViaLink.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/FileLinks.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/SpaceMembers.spec.js
packages/web-app-files/tests/unit/views/shares/__snapshots__/SharedViaLink.spec.js.snap
packages/web-app-files/tests/unit/views/shares/__snapshots__/SharedWithOthers.spec.js.snap
packages/web-runtime/package.json
packages/web-runtime/tests/unit/components/Topbar/__snapshots__/ApplicationsMenu.spec.js.snap
packages/web-runtime/tests/unit/components/Topbar/__snapshots__/FeedbackLink.spec.js.snap
yarn.lock

See https://github.com/owncloud/web/issues/6590
- Fixes https://github.com/owncloud/web/issues/6590

Add Contextual Helpers

---

changelog/unreleased/bugfix-apply-text-selection-range-for-new-files
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue

Bugfix: Apply text selection range for new files
We've fixed a bug, where the text selection range for a new file has not been applied only for the file name but also
for the file extension.
This is now working as in the rename modal and just selects the text for the file name.
- Fixes https://github.com/owncloud/web/issues/6756
- test case 1:
- test case 2:
- ...

Add inputSelectionRange to create new file

---

changelog/unreleased/bugfix-renaming-favorites-issue
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/mixins/actions/rename.js
packages/web-app-files/tests/unit/mixins/actions/rename.spec.js

Bugfix: Rename a file in the favorites list to a file with the same name but in a different folder not possible
We've fixed a bug, where renaming a file in the favorites file list to a file with the same name but in a different
folder was not possible, as the message `The name "..." is already taken` appeared.
- Fixes https://github.com/owncloud/web/issues/1750
- test case 1:
- test case 2:
- ...

Take path into account while renaming a file

---

packages/web-runtime/l10n/Makefile

Note: 
1. The library easygettext, which we are using to extract translations, **is not capable to extract the LOC Number and therefore it is missing in the respective POT file**, see: https://github.com/Polyconseil/easygettext#known-issues
2. Babel and acorn parsers are complaining about the file: packages/web-app-files/src/helpers/share/share.ts, therefore I ignored it, maybe @dschmidt might help later to find the issue:
```[easygettext] could not read: '../../web-app-files/src/helpers/share/share.ts' using babel as parser
Trace: SyntaxError: Line 1, column 13: Unexpected
at report (/home/jan/working/web/node_modules/buntis/dist/buntis.umd.js:4472:21)
at parseModuleSpecifier (/home/jan/working/web/node_modules/buntis/dist/buntis.umd.js:6490:11)
at parseImportDeclaration …
```

l10n for typescript files 

---

changelog/unreleased/bugfix-rename-still-clickable-on-mobile
packages/web-app-files/src/components/FilesList/ResourceTable.vue

See https://github.com/owncloud/web/issues/6767
- Fixes https://github.com/owncloud/web/issues/6767

Bugfix invisible rename is clickable on mobile

---

.drone.env
.drone.star

oCIS switched to libregraph/idm for users and groups. We need the newer
middleware for user provisioning.

[full-ci] Bump ocis commit and test-middleware 

---

packages/web-runtime/l10n/Makefile
packages/web-runtime/package.json
yarn.lock

…from typescript-eslint project instead of outdated buntis parser
buntis is outdated and fails to parse newer javascript/typescript syntax like optional chaining.
There is a [PR ](https://github.com/Polyconseil/easygettext/pull/107) open for porting to the properly maintained typescript-eslint/typescript-estree library, but it hasn't seen any feedback. It does not fix linenumbers anyhow.
I've sent a new PR which also fixes line numbers, I'm not optimistic it will be merged instead ... we should consider creating a fork in owncloud organization. Let's discuss tomorrow...
- Supersedes https://github.com/owncloud/web/pull/6830
It fixes missing line numbers and parse errors in ts files/vue files using typescript.
removed .pot files from .gitignore
used old version to create those files, …

Switch to dschmidt/easygettext to use typescript-estree

---

tests/e2e/README.md
tests/e2e/cucumber/features/integrations/link.oc10.feature
tests/e2e/cucumber/features/integrations/link.ocis.feature
tests/e2e/cucumber/features/integrations/share.feature
tests/e2e/cucumber/features/journeys/kindergarten.feature
tests/e2e/cucumber/steps/app-files/resource.ts
tests/e2e/support/objects/app-files/page/public.ts
tests/e2e/support/objects/app-files/resource/actions.ts

Adds test implementation for step `Alice downloads 2 files as tar.`
- Part of: https://github.com/owncloud/web/issues/6389
- local
- CI

[tests-only] Adds e2e tests for download files batch action

---

changelog/unreleased/enhancement-polish-upload-overlay
packages/web-runtime/src/components/UploadInfo.vue

* Polished the design of the overlay a bit
* Header now shows the amount of successful uploads
Followup for https://github.com/owncloud/web/pull/6202

Polish the upload overlay

---

deployments/examples/ocis_web/config/ocis/entrypoint-override.sh
deployments/examples/ocis_web/docker-compose.yml

uses `ocis init` in the deployment example
- Needed after owncloud/ocis#3551
- test case 1:
- test case 2:
- ...

use `ocis init` in the deployment example

---

changelog/unreleased/bugfix-resetting-store-on-logout
packages/web-runtime/src/store/navigation.js
packages/web-runtime/src/store/user.js

When logging out, only some parts of vuex store were reset to default. This caused bugs by switching to another account that has some other/missing settings. For example, if the account has no quota, the quota of the previously logged in account was shown. We have fixed this by resetting the store on logout with reset function (vuex extensions library).
- Fixes [6549](https://github.com/owncloud/web/issues/6549)
logging in, logging out, logging in
- test case 1: logging in with account with quota, logging out, logging in with account without quota --> quota not shown
- test case 2:  logging in with account with navItems, logging out, logging in with account with another set of navItems --> they are displayed correctly
- ...

Reset store on logout

---

changelog/unreleased/bugfix-spaces-triggerid-invalid
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/src/helpers/resource/resource.ts
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/helpers/statusIndicators.js
packages/web-app-files/src/mixins/filesListScrolling.js
packages/web-app-files/src/views/shares/SharedWithMe.vue
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/components/FilesList/ResourceTable.spec.js
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.js.snap
packages/web-app-files/tests/unit/helpers/resource/resource.spec.ts
packages/web-app-files/tests/unit/views/shares/SharedWithMe.spec.js

See https://github.com/owncloud/web/issues/6845
- Fixes https://github.com/owncloud/web/issues/6845

[full-ci] Bugfix: Spaces Contextmenu trigger id isn't valid

---

changelog/unreleased/enhancement-fixed-aspect-ratio-spaces-image
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap

See https://github.com/owncloud/web/issues/6555 (last point)
- Works towards https://github.com/owncloud/web/issues/6555

Design polishing: Set a fixed aspect ratio for spaces image

---

changelog/unreleased/enhancement-uppy-service-event-bus
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/views/FilesDrop.vue
packages/web-app-files/tests/unit/views/FilesDrop.spec.js
packages/web-runtime/src/components/UploadInfo.vue
packages/web-runtime/src/composables/upload/uppyPlugins/customDropTarget.ts
packages/web-runtime/src/services/uppyService.ts

Instead of extending Vue, the uppy service now uses our custom `EventBus`.
Follow up for https://github.com/owncloud/web/pull/6202

Use our EventBus for upload related actions

---

packages/web-app-files/src/helpers/contextualHelpers.js
packages/web-app-files/src/helpers/share/permission.ts
packages/web-app-files/src/views/LocationPicker.vue
packages/web-app-files/tests/unit/views/__snapshots__/LocationPicker.spec.js.snap
packages/web-app-user-management/src/views/Users.vue
packages/web-runtime/package.json
packages/web-runtime/src/pages/accessDenied.vue
yarn.lock

Fixes some invalid `$gettext` usages.

[full-ci] Fixed some occurences of invalid $gettext usage

---

changelog/unreleased/bugfix-upload-overlay-links
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/views/FilesDrop.vue
packages/web-runtime/src/components/UploadInfo.vue

We've fixed a bug where the folder links in the upload overlay were broken when navigating into another app or file list.
Follow up for https://github.com/owncloud/web/pull/6202

Fix root folder links in the upload overlay

---

changelog/unreleased/enhancement-enable-search-all-files
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/Search/Preview.vue
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/index.js
packages/web-app-files/src/search/sdk/list.ts
packages/web-app-files/src/search/sdk/preview.ts
packages/web-app-files/src/store/actions.js
packages/web-app-files/src/store/mutations.js
packages/web-app-files/src/store/state.js
packages/web-app-files/tests/unit/components/FilesList/ResourceTable.spec.js
packages/web-app-files/tests/unit/components/Search/Preview.spec.js
packages/web-app-files/tests/unit/components/components.setup.js
packages/web-app-files/tests/unit/views/views.setup.js
packages/web-runtime/package.json
yarn.lock

Enhancement: Enable search all files for ocis backend
We've enabled the search all files feature for ocis backend:
* Find files in sub directories
* Find files in other places like project spaces
- test case 1:
- test case 2:
- ...

[full-ci] Search all files with ocis backend

---

changelog/unreleased/bugfix-public-link-edit
docker-compose.yml
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue

Fix expiration date conversion when editing public links with expiry date.
- Fixes https://github.com/owncloud/web/issues/6858
Hardening

[full-ci] Fix public link edit

---

changelog/unreleased/enhancement-space-store-improvements
packages/web-app-files/src/components/AppBar/CreateSpace.vue
packages/web-app-files/src/mixins/spaces/actions/delete.js
packages/web-app-files/src/mixins/spaces/actions/rename.js
packages/web-app-files/src/store/mutations.js
packages/web-app-files/tests/unit/store/mutations.spec.js

Enhancement: Space store improvements
We've improved the space's store, this allows us to keep the search reactive to space changes,
for example, as a project space gets added or renamed.
https://github.com/owncloud/web/pull/6868
- test case 1:
- test case 2:
- ...

Improve space store

---

dev/docker/oc10.Dockerfile

Fixes https://github.com/owncloud/web/issues/6878
While running `docker-compose up oc10`, the command fails with `make: command not found`
Added `make` so that the command will be executed

Install make library

---

.drone.env
changelog/unreleased/enhancement-tus-uploads-on-public-pages
packages/web-runtime/src/composables/upload/useUpload.ts

Continuation of https://github.com/owncloud/web/pull/6202
Can now be done because https://github.com/owncloud/ocis/pull/3703 has been merged.

Enable tus upload for password protected public links

---

changelog/unreleased/bugfix-configuration-options-optional-chaining
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/components/Search/Preview.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/views/Favorites.vue
packages/web-app-files/src/views/Personal.vue
packages/web-app-files/src/views/PublicFiles.vue
packages/web-app-files/src/views/shares/SharedViaLink.vue
packages/web-app-files/src/views/shares/SharedWithMe.vue
packages/web-app-files/src/views/shares/SharedWithOthers.vue
packages/web-app-files/src/views/spaces/Project.vue
packages/web-runtime/src/components/Topbar/TopBar.vue
packages/web-runtime/src/components/UploadInfo.vue

- test case 1:
- test case 2:
- ...

Enable optional chaining on configuration access

---

changelog/unreleased/bugfix-set-space-image-and-readme
packages/web-app-files/src/mixins/spaces/actions/setImage.js
packages/web-app-files/src/mixins/spaces/actions/setReadme.js
packages/web-app-files/src/services/folder/spaces/loaderProject.ts
packages/web-app-files/src/store/getters.js
packages/web-app-files/src/store/mutations.js
packages/web-app-files/src/views/spaces/Project.vue
packages/web-app-files/tests/unit/mixins/spaces/setImage.spec.js
packages/web-app-files/tests/unit/mixins/spaces/setReadme.spec.js
packages/web-app-files/tests/unit/views/spaces/Project.spec.js

* An issue where setting a space-image or -readme would corrupt the file list has been fixed.
* Setting images from within the `.space` folder has been fixed.
* Setting images and readme files with specials characters in their names has been fixed.
- Fixes https://github.com/owncloud/web/issues/6875

Fix several issues when setting image and readme for spaces

---

changelog/unreleased/enhancement-introduce-sharing-jail
changelog/unreleased/enhancement-resumeable-uploads
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/services/folder/spaces/loaderPersonal.ts

Fix personal drive ID in personal space/upload

---

docs/backend-ocis.md

Necessary since the `kill` command has been dropped by infinite scale

Update web&ocis dev docs

---

changelog/unreleased/bugfix-create-space-button-sidebar
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.js.snap

We've fixed a bug where the "Create Space"-button would disappear when opening the sidebar for a space.
- Fixes https://github.com/owncloud/web/issues/6918

Prevent 'Create Space'-button from disappearing when sidebar is open

---

changelog/unreleased/bugfix-spaces-image-without-setting
packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue
packages/web-app-files/src/views/spaces/Projects.vue

We've fixed a bug where an image would show for a space even though no image has been set.
- Fixes https://github.com/owncloud/web/issues/6920

Prevent space image from showing even though no image has been set

---

.drone.env
.drone.star

Should make CI way more reliable since the personal space flock issue has been resolved in Reva.
Also, accounts&glauth service have been removed from oCIS. Now, the oc10 acceptance tests relying on OIDC use an old/outdated oCIS instance for their glauth service, which we should eventually replace with a proper solution

[full-ci] Bump oCIS commit ID after flock fix & glauth/accounts service removal

---

changelog/unreleased/bugfix-use-oc-etag-instead-of-etag-in-text-editor
packages/web-app-text-editor/src/App.vue
packages/web-runtime/package.json
yarn.lock

Bugfix: Use OC-ETag instead of ETag in text editor app
We've fixed a bug, where the ETag instead of OC-ETag in the text editor app was used,
due to server encoding, the ETag might be manipulated and contain the gzip suffix on large text files.
Saving the respective file, might cause an error, as the sent ETag doesn't match the server's ETag.
- Fixes https://github.com/owncloud/web/issues/6947
- Fixes https://github.com/owncloud/web/issues/4605
- test case 1:
- test case 2:
- ...

Use oc-etag instead of etag

---

.drone.env
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIFilesActionMenu/versions.feature
tests/acceptance/pageObjects/FilesPageElement/versionsDialog.js
tests/acceptance/stepDefinitions/filesContext.js
tests/e2e/cucumber/features/integrations/share.oc10.feature
tests/e2e/cucumber/features/integrations/share.ocis.feature
tests/e2e/cucumber/steps/app-files/resource.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

- added step download old version
- deleted old acceptance test (should have worked, but didn't anyway). 
- deleted line in expected failures
- closed issue: https://github.com/owncloud/ocis/issues/2261

e2e tests. Download old version of the file

---

changelog/unreleased/bugfix-share-downloads
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/mixins/actions/downloadArchive.js
packages/web-app-files/src/mixins/actions/downloadFile.js

Single file shares and folder shares didn't have their respective download action available. (note: this is not related to the sharing jail. we just never had downloads on the shared with me page)
- Works towards https://github.com/owncloud/ocis/issues/3760

Fix downloads on shared with me page

---

changelog/unreleased/bugfix-add-root-breadcrumb-to-shared-with-me-page
packages/web-app-files/src/views/shares/SharedResource.vue

- Fixes https://github.com/owncloud/web/issues/6937
- test case 1:
- test case 2:
- ...

Add shares breadcrumb

---

__fixtures__/users.js
changelog/unreleased/bugfix-respect-unlimited-quota
packages/web-runtime/src/components/Topbar/UserMenu.vue
packages/web-runtime/src/store/user.js
packages/web-runtime/tests/unit/components/Topbar/UserMenu.spec.js
packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.js.snap

- Fixes https://github.com/owncloud/web/issues/6913
- https://github.com/owncloud/ocis/issues/3748
- test case 1:
- test case 2:
- ...

fix account-info quota rendering

---

changelog/unreleased/bugfix-require-quick-link-password-if-enforced-in-oC10
packages/web-app-files/src/helpers/share/link.ts
packages/web-app-files/src/quickActions.js

- Fixes https://github.com/owncloud/web/issues/6963
- test case 1:
- test case 2:
- ...

Add set password modal

---

changelog/unreleased/bugfix-indirect-links-should-not-be-editable
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue

See https://github.com/owncloud/web/issues/6964
- Fixes https://github.com/owncloud/web/issues/6964

[full-ci] Indirect links should not be editable

---

changelog/unreleased/enhancement-add-sentry-support
docs/getting-started.md
packages/web-runtime/package.json
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/index.ts
packages/web-runtime/src/store/user.js
yarn.lock

Would you take this? This is quite useful for us to get user's issues without having to wait for a ticket.
I've made it optional and configurable.
But.. Our centrally managed Sentry instance doesn't run the latest version, so the config/package version in here is also not the latest.

Sentry as option

---

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature

This PR has rearranged the given steps so that the WebUI steps come after the server setup steps. Doing so also eliminates the unnecessary use of reloading page steps in the scenarios.
- Fixes https://github.com/owncloud/web/issues/6979

[tests-only][full-ci] Use webUI steps after the server setup steps

---

changelog/unreleased/bugfix-text-color-application-menu-item
changelog/unreleased/enhancement-sort-default-action-first-context-menu
packages/web-app-files/src/components/FilesList/ContextActions.vue
packages/web-app-text-editor/src/App.vue
packages/web-pkg/src/components/sidebar/SideBar.vue
packages/web-runtime/src/components/Topbar/ApplicationsMenu.vue

- text editor textarea gets full height of app
- default action is shown as first action in the context menu, fixes https://github.com/owncloud/web/issues/6971
- application menu items hover: text color fix, fixes https://github.com/owncloud/web/issues/6958
- prevent horizontal scrollbar in sidebar by long emails of sharees, fixes https://github.com/owncloud/web/issues/6973

Multiple fixes

---

tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/personalPage.js
tests/acceptance/stepDefinitions/filesContext.js

This PR adds a functions which closes upload progress bar for files/folders after each upload. 
- https://github.com/owncloud/web/issues/6978
- Locally
- CI

[tests-only][full-ci]Added function to close the filesFolderUploadProgress on each upload

---

tests/e2e/support/objects/app-files/spaces/actions.ts

This PR 
-  moves the selector name to constants [in `tests/e2e/support/objects/app-files/spaces/` folder]
- https://github.com/owncloud/web/issues/6908
- CI

[tests-only] Refactored e2e test to move selector name to constant [Part 2]

---

tests/e2e/support/objects/runtime/application.ts

This PR 
-  moves the selector name to constants [in `tests/e2e/support/objects/app-files/runtime/` folder]
- https://github.com/owncloud/web/issues/6908
- CI

[tests-only] Refactored e2e test to move selector name to constant [Part 3]

---

tests/e2e/cucumber/features/integrations/link.feature
tests/e2e/cucumber/steps/app-files/link.ts
tests/e2e/cucumber/steps/app-files/page/public.ts
tests/e2e/cucumber/steps/app-files/resource.ts
tests/e2e/support/environment/link.ts
tests/e2e/support/objects/app-files/link/actions.ts
tests/e2e/support/objects/app-files/link/index.ts
tests/e2e/support/objects/app-files/page/public.ts
tests/e2e/support/objects/app-files/resource/actions.ts

- part of: https://github.com/owncloud/web/issues/6389
- Locally
- CI

[tests-only] E2e test public link

---

packages/web-app-files/src/services/folder/spaces/loaderProject.ts

- Fixes https://github.com/owncloud/web/issues/6866
- test case 1:
- test case 2:
- ...

Fix missing use of route params in loaderProject

---

changelog/unreleased/enhancement-changes-to-links-in-sidebar
docs/getting-started.md
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.js.snap
packages/web-runtime/src/store/config.js

This PR addresses some additions and fixes to the sidebar links:
* Adds an `isEos` setting into `config.json` as discussed in https://github.com/owncloud/web/issues/6702#issuecomment-1117256159
* Adds direct link to the side bar (maybe related to https://github.com/owncloud/web/issues/6840)
* Adds an eos path to the side bar, shown if `isEos`
* Ellipsizes long links so the sidebar does not get a scrollbar. Along with https://github.com/owncloud/owncloud-design-system/pull/2137, these two should close https://github.com/owncloud/web/issues/6849.
* Normalized some sidebar table method names (some of them were `titleSomething`, all are now `labelSomething`)
* Removed the colons and made the headers of the table `nowrap`. This makes the table looks better, as there is no need to have colons …

Changes to links in sidebar, fix tooltips

---

changelog/unreleased/bugfix-link-permission-enforced-password
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
tests/acceptance/stepDefinitions/publicLinkContext.js

- Fixes https://github.com/owncloud/web/issues/6974
- test case 1:
- test case 2:
- ...

[full-ci] Show password prompt if role change on public link enforces password

---

changelog/unreleased/enhancement-changes-to-links-in-sidebar
changelog/unreleased/enhancement-eos-links-in-sidebar
docs/getting-started.md
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.js.snap
packages/web-runtime/src/store/config.js

This ports #6959 over, with slight adoptions:
- unit tests now run with default disabled EOS, and have cases with eos to make sure the component does what we expect
- "direct links" now also are only visible if EOS ins enabled in the config (pretty sure `web` should have dedicated private links for OC10 and a strong incentive for users to use quicklinks/public links)

Port EOS details to details tab in files sidebar

---

.drone.env
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIFilesSearch/search.feature

This PR:
- Bumps ocis commit id
- removes passing test from expected 
- removes the tag of closed issue
- Part of: https://github.com/owncloud/QA/issues/739
- CI

[tests-only][full-ci]Bump ocis commit id for tests

---

changelog/unreleased/bugfix-breadcrumb-focus
packages/web-app-files/src/mixins/accessibleBreadcrumb.js

We've fixed a bug where the auto focus couldn't be set on the current breadcrumb item when navigating. It also gets rid of all the console errors when navigating: `TypeError: activeBreadcrumbItem.focus is not a function`

[full-ci] Fix breadcrumb auto focus

---

changelog/unreleased/bugfix-search-mess-up-spaces-overview
packages/web-app-files/src/views/spaces/Projects.vue

We've fixed a bug where searching for a file in the search bar messes up the spaces overview and instead of listing
the spaces, and found files according to the search term were shown.
- Fixes https://github.com/owncloud/web/issues/6995
- test case 1:
- test case 2:
- ...

Clear files searched in spaces overview

---

.drone.star

Changes in the recently released oc10 v10.10 break the CI (trashbin changes in combination with the middelware AFAIK)

[tests-only] Pin oc10 to 10.09.1 until middleware for latest is ready

---

changelog/unreleased/bugfix-accept-remote-share-reload
packages/web-pkg/src/composables/appDefaults/useAppFolderHandling.ts
packages/web-runtime/src/components/Topbar/Notifications.vue
tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-oc10-server-oauth2-login-and-web-integration-app.md
tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-oc10-server-openid-login.md

We've fixed a bug where the file list would not reload after accepting a remote share.
- Fixes https://github.com/owncloud/web/issues/1774
- Fixes https://github.com/owncloud/web/issues/4247
- Fixes https://github.com/owncloud/web/issues/4839

[full-ci] Reload file list after accepting a remote share

---

changelog/unreleased/bugfix-space-special-files
packages/web-app-files/src/views/spaces/Project.vue
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/views/spaces/Project.spec.js

Fix webDavPath construction for space image and readme.
Finding the relative webDavPath needs to be a prefix match since the URL has the spaceId as nodeId in
the URL (uniform 3-part id syntax) but the space id we maintain
internally is 2-part.
I will not de-duplicate this code, because we want to use the absolute webDavUrl from the graph response ASAP anyway. And then all this splitting and finding goes away.

Fix webDavPath construction for space image and readme

---

.drone.star
tests/drone/setup-server-and-app.sh

use owncloud 10.10.0 for running tests, enable `dav.propfind.depth_infinity` for oc10 tests
fixed  #7019
follow up in #7029
:robot:

[full-ci][tests-only] pin owncloud 10 to 10.10.0 for tests

---

changelog/unreleased/bugfix-share-permissions-inheritance
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/src/helpers/share/role.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/RoleDropdown.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/RoleDropdown.spec.js.snap
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIResharing1/reshareUsers.feature
tests/acceptance/features/webUIResharingToRoot/reshareUsers.feature

We've fixed a bug where the permissions of a share were not inherited when trying to reshare a resource. We've also disabled the role-select-dropdown if only one role is available for sharing.
- Fixes https://github.com/owncloud/web/issues/2963

[full-ci] Fix inheritance of share permissions on reshares

---

changelog/unreleased/enhancement-cern-features
changelog/unreleased/enhancement-cern-specific-help-in-shares-tooltip
docs/getting-started.md
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/helpers/contextualHelpers.js
packages/web-runtime/src/store/config.js

This PR adds a `cernFeatures` config flag we can use from here on to add our CERN-branded stuff.
Using that flag, we also display different info on the shares tool-tip for CERN users.

CERN-specific config flag + share tooltip captions

---

changelog/unreleased/bugfix-respect-unlimited-quota
packages/web-runtime/src/components/Topbar/UserMenu.vue
packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.js.snap

Reintroducing a "Personal storage" label in the user menu after https://github.com/owncloud/web/pull/6923 was merged. Also, the `used` value for the quota details was broken for 0, as that is somehow `NaN` instead of `0`. Fixed by using `0` as a fallback.
- Fixes https://github.com/owncloud/web/issues/6913

Fix rendering unlimited quota

---

.drone.env
changelog/unreleased/enhancement-productversion-log
packages/web-runtime/src/container/versions.ts
packages/web-runtime/tests/unit/container/versions.spec.ts

oCIS has introduced a new `productversion` field to announce it's correct version while maintaining a fake 10.x.x version in the `versionstring` field to keep clients compatible. We're using the new productversion field when it exists and use versionstring as a fallback. Thus the backend product information prints the correct oCIS version now.
Since it seems to be encouraged to use `capabilities.core.status` this PR switches over to using that instead of the `version` object. 🤷 
- Related to https://github.com/owncloud/ocis/issues/3788
- Related to https://github.com/owncloud/ocis/pull/3805 (needed for manual testing if not yet merged)

Make use of new productversion field if available

---

tests/e2e/cucumber/environment/index.ts

fix https://github.com/owncloud/web/issues/7048
if you re-run  `spaces/project.ocis.feature` you get:
after test we should clear spaceStore

Clear spaceStore after test

---

changelog/unreleased/bugfix-show-message-while-upload-size-exceeds-quota
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.js
packages/web-runtime/src/services/uppyService.ts

Bugfix: Show message while upload size exceeds quota
We fixed a bug where an upload silently failed if the upload size exceeds the space quota. It now displays a detailed message instead
will be shown.
- Fixes https://github.com/owncloud/web/issues/7025
- test case 1:
- test case 2:
- ...

Start implementation of quota exceeded check

---

dev/docker/ocis.entrypoint.sh
docker-compose.yml

This sets all missing environment variables in our docker-compose.yml to make latest ocis launch again.
The ocis config path that was checked in our custom entrypoint is obsolete, it should be /etc/ocis/ocis.yml instead.
But even when the path is fixed:
when the file exists, but our environment variables are incomplete, ocis tells us to run ocis init, which then fails because the file already exists.
@dragonchaser suggested we might setup a drone cron pipeline that syncs the env variables set here https://github.com/owncloud/ocis/blob/master/.vscode/launch.json to our docker-compose.yml file or to a .env file.
- test case 1:
- test case 2:
- ...

Fix docker-compose dev env for latest ocis

---

packages/web-app-files/tests/unit/components/SideBar/Shares/Links/NameAndCopy.spec.js

Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>
`NameAndCopy` component uses `v-oc-tooltip`. It is now mocked for the tests so that no random warning are on the unit test run logs.
- Fixes https://github.com/owncloud/web/issues/6337
- :robot:

[tests-only] tidy up the unit tests logs

---

changelog/unreleased/bugfix-rename-button-visibility
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/tests/unit/components/__snapshots__/TrashBin.spec.js.snap
packages/web-app-files/tests/unit/views/shares/__snapshots__/SharedWithOthers.spec.js.snap
packages/web-runtime/tests/unit/components/__snapshots__/UploadInfo.spec.js.snap

We've fixed a bug where the rename button next to the file name would get covered if there is not enough space available.
- Fixes https://github.com/owncloud/web/issues/7007
Before:
After:

Prevent rename button from getting covered

---

changelog/unreleased/enhancement-resourcetable-shareindicator-rendering
packages/web-app-files/src/store/mutations.js

This is a quick first step towards resolving #7038 (esp. resources that aren't shared, since their rendering gets sped up), further improvements need more sophisticated changes which will happen in a subsequent PR

Prevent LOAD_INDICATORS from modifying store with empty changes

---

changelog/unreleased/bugfix-not-logged-out-if-oC10-backend
config/config.json.sample-oc10
dev/docker/oc10.web.config.json
packages/web-runtime/src/store/user.js

- Fixes https://github.com/owncloud/web/issues/5886
- test case 1:
- test case 2:
- ...

Logout in oc10 while click logout in web 

---

changelog/unreleased/enhancement-add-config-option-hoverable-quick-actions
docs/getting-started.md
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-runtime/src/store/config.js

Adds the possibility to add hover effect for quick actions with the option "hoverableQuickActions" in config.json
The hover effect applies to "edit name", "add people" and "copy quicklink" actions in the corresponding hovered row.
- Fixes https://github.com/owncloud/web/issues/7021
For CERNBox we don't want to show quick actions for each row, just for hovered ones

Config option for hoverable quick actions

---

tests/acceptance/helpers/loginHelper.js

As per the findings in https://github.com/owncloud/web/issues/6999#issuecomment-1141722650, the flakiness in the test might be due to the DELETE action being performed before the files list is loaded completely.
This PR has added a wait for the files container to be loaded.
- Closes https://github.com/owncloud/web/issues/6999

[tests-only][full-ci] Wait for file container to load after login

---

changelog/unreleased/enhancement-enable-contexthelpers-default
config/config.json.dist
config/config.json.sample-oc10
config/config.json.sample-ocis
deployments/continuous-deployment-config/ocis_web/latest.yml
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/FileLinks.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/SpaceMembers.spec.js
packages/web-runtime/src/store/config.js

See changelog item
Remove @refs and update @lookacat keys in the deployment example instance

Make contexthelpers opt-out, update employee keys in deployment example

---

tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js

Closes #7073
The test was failing due to time out while waiting for the `year-selector` to be present for `500 milliseconds`. In this PR, the static wait of `500 milliseconds` has been removed and now the `default timeout` will be used.

[tests-only][full-ci] fixed expiration date related intermittent failure

---

changelog/unreleased/enhancement-upload-time-estimation
packages/web-runtime/src/components/UploadInfo.vue
packages/web-runtime/src/services/uppyService.ts
packages/web-runtime/tests/unit/components/UploadInfo.spec.js

The estimated remaining time for an upload will now be displayed in the upload overlay.
- Part of https://github.com/owncloud/web/issues/7069

Upload progress estimation

---

changelog/unreleased/bugfix-upload-overlay-complete-state
packages/web-runtime/src/components/UploadInfo.vue

We've fixed a bug where the complete-state of the upload overlay would show before the upload even started.
- Fixes https://github.com/owncloud/web/issues/7097

Fix complete-state of the upload overlay

---

changelog/unreleased/bugfix-upload-overlay-public-parent-folder
packages/web-runtime/src/components/UploadInfo.vue

We've fixed a bug where the parent folder link in the upload overlay on public pages would show the link's token instead of "Public link".
- Fixes https://github.com/owncloud/web/issues/7101

Fix parent folder name in the upload overlay on public pages

---

changelog/unreleased/bugfix-space-image-readme-loading
packages/web-app-files/src/views/spaces/Project.vue
packages/web-app-files/src/views/spaces/Projects.vue

We've fixed a bug where the image and/or readme for a space wouldn't reload automatically after being updated.

Fix reload of space image/readme after being updated

---

changelog/unreleased/enhancement-upload-overlay-folder-links
packages/web-runtime/src/components/UploadInfo.vue
packages/web-runtime/tests/unit/components/UploadInfo.spec.js

Uploaded folders can now be clicked in the upload overlay, which navigates the user to the clicked folder.
- Fixes https://github.com/owncloud/web/issues/7102

Implement clickable folder links in upload overlay

---

changelog/unreleased/bugfix-upload-meta-serialization
changelog/unreleased/enhancement-upload-data-during-creation
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/composables/upload/useUploadHelpers.ts
packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.js
packages/web-pkg/src/composables/capability/useCapability.ts
packages/web-runtime/src/components/UploadInfo.vue
packages/web-runtime/src/composables/upload/useUpload.ts
packages/web-runtime/src/services/uppyService.ts

Uploading via tus now uses the `uploadDataDuringCreation` option which saves up one request. Also, we've fixed a serialization error during uploads, saving up another request.
- https://github.com/owncloud/web/issues/7066

Use 'uploadDataDuringCreation' option when uploading via tus

---

changelog/unreleased/enhancement-copy-move-conflict-dialog
packages/web-app-files/src/helpers/extensions/fileExtensions.ts
packages/web-app-files/src/helpers/resource/copyMove.ts
packages/web-app-files/src/store/mutations.js
packages/web-app-files/tests/unit/helpers/resource/copyMove.spec.ts

See https://github.com/owncloud/web/issues/7089
- Fixes https://github.com/owncloud/web/issues/7089

Bugfix: Copy / move file name exists count duplicate

---

changelog/unreleased/enhancement-wordings
packages/web-app-files/src/helpers/resource/copyMove.ts
packages/web-app-files/src/views/LocationPicker.vue
packages/web-app-files/tests/unit/views/__snapshots__/LocationPicker.spec.js.snap

Improved some parts of copy/move wording.

Wording fixes in locationPicker and copy/move conflict

---

packages/web-app-draw-io/src/App.vue
packages/web-app-external/src/App.vue
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-pdf-viewer/src/App.vue
packages/web-app-preview/src/App.vue
packages/web-app-text-editor/src/App.vue
packages/web-container/index.html.ejs
packages/web-pkg/src/composables/appDefaults/types.ts
packages/web-pkg/src/composables/appDefaults/useAppConfig.ts
packages/web-pkg/src/composables/appDefaults/useAppDefaults.ts
packages/web-pkg/src/composables/appDefaults/useAppDocumentTitle.ts
packages/web-pkg/src/composables/appDefaults/useAppFileHandling.ts
packages/web-pkg/src/composables/appDefaults/useAppFolderHandling.ts
packages/web-pkg/src/composables/appDefaults/useAppMeta.ts
packages/web-pkg/src/composables/appDefaults/useAppNavigation.ts
packages/web-pkg/src/composables/appDefaults/useDocumentTitle.ts
packages/web-pkg/src/composables/authContext/index.ts
packages/web-pkg/src/composables/authContext/useAccessToken.ts
packages/web-pkg/src/composables/authContext/usePublicLinkContext.ts
packages/web-pkg/src/composables/authContext/usePublicLinkPassword.ts
packages/web-pkg/src/composables/authContext/usePublicToken.ts
packages/web-pkg/src/composables/authContext/useRequest.ts
packages/web-pkg/src/composables/index.ts

... and move `makeRequest` to its own composable.
This refactors document title setting and moves `makeRequest` into its own composable.
- follow up for https://github.com/owncloud/web/pull/6655
- 
- I've opened files in preview and text-editor app and the title is set correctly
- the only usage of makeRequest in `addAppProviderFile` seems to produce the same request as before the refactor, but my ocis doesn't like either.. so I cannot be 100%. Could anyone with a working wopi setup give this a spin?

[full-ci] Set document title consistently for all apps in useAppDefaults composable

---

changelog/unreleased/enhancement-tus-backend-chunksize
packages/web-runtime/src/composables/upload/useUpload.ts
packages/web-runtime/src/services/uppyService.ts
packages/web-runtime/src/store/config.js

Instead of using the tus chunksize from the web config, we now use the chunksize coming from the backend (if set).

Use tus chunksize from backend

---

changelog/unreleased/bugfix-not-logged-out-if-oC10-backend
packages/web-runtime/src/store/user.js

While already being redirected to the logout URL of oc10 (killing the server side session) we had an intermediate issue of the user in oC Web not being unloaded. As a result, upon next login we still had the previous user available from the session storage. Fixed by not suppressing the user removal inside the oidc-client anymore, but instead deciding inside the `userUnloaded` event if we are in an oauth2 context and then redirect properly.
- Fixes https://github.com/owncloud/web/issues/5886 more than before
Harden the oc10 integration.

[full-ci] Fix unloading user with oc10 backend

---

config/config.json.dist
config/config.json.sample-oc10
config/config.json.sample-ocis
dev/docker/ocis.web.config.json
tests/drone/config-oc10-oauth.json
tests/drone/config-oc10-openid.json
tests/drone/config-ocis.json

The version in our `config.json` is not used. At least not anymore. Removing it from all sample configs and CI configs.

Drop version from sample configs and ci configs (it's unused)

---

changelog/unreleased/enhancement-preview-additional-mimetypes
docs/deployments/oc10-app.md
packages/web-app-preview/src/App.vue
packages/web-app-preview/src/index.js
packages/web-runtime/src/store/apps.js

As a mitigation for supported preview types not being announced by the backend, this PR adds support for adding additional mime types via the config.json.
- Fixes https://github.com/owncloud/web/issues/6933

[full-ci] Allow additional mimeTypes via preview app config

---

tests/acceptance/pageObjects/personalPage.js

Sometimes `uploadFolder` might fail to close the upload-info dialog due to change in element reference (for what may be the reason). In this PR, I have made upload functions to wait for upload-status message to be visible and then only close the dialog.
- Fixes #7143

[tests-only][full-ci] Wait for upload success message

---

changelog/unreleased/enhancement-redesign-link-sharing
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue

- Fixes #7149 (indirect link shares used the currently highlighted resource's isFolder property, which ofc is wrong - an indirect link always exists on one of the parent folders)

Fix issue #7149 (indirect linkShareRole calculation)

---

changelog/unreleased/enhancement-split-sidebar-direct-indirect-linkshares
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/Links/CreateQuickLink.vue
packages/web-app-files/src/components/SideBar/Shares/Links/NameAndCopy.vue
packages/web-app-files/src/helpers/contextualHelpers.js
packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/NameAndCopy.spec.js.snap

Split (in)direct link shares in sidebar into two lists

---

changelog/unreleased/bugfix-preview-mimetype-mapping
packages/web-app-preview/src/App.vue

The preview app only rendered `image/`, `video/` and `audio/` mime types. Now all non-`audio/` and non-`video/` mime types are rendered as images.

Render all non-video and non-audio mime types as images in preview app

---

changelog/unreleased/bugfix-external-app-title
changelog/unreleased/bugfix-external-apps
packages/web-app-external/src/App.vue
packages/web-app-external/tests/unit/app.spec.js
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-pkg/src/composables/appDefaults/useAppDefaults.ts
packages/web-pkg/src/composables/appDefaults/useAppDocumentTitle.ts
packages/web-pkg/src/composables/appDefaults/useAppNavigation.ts

Continuation of https://github.com/owncloud/web/pull/7166 which provides an option to override the application name in the document title (and using it from the external app) to reduce code duplication.

Continue external apps fix

---

changelog/unreleased/bugfix-space-sidebar-sharingindicators
packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/SpaceDetails.spec.js.snap

Fix #6917 - sharing indicators&description for spaces

---

changelog/unreleased/enhancement-share-indicators-performance
packages/web-app-files/src/services/folder/legacy/loaderPersonal.ts
packages/web-app-files/src/services/folder/spaces/loaderPersonal.ts
packages/web-app-files/src/services/folder/spaces/loaderProject.ts
packages/web-app-files/src/store/actions.js
packages/web-app-files/src/store/mutations.js
packages/web-app-files/tests/unit/views/spaces/Project.spec.js

We've improved the performance of share indicators when loading resource tables as well as when adding or removing shares.
In detail:
* Accessing a shared folder: The share indicators now get loaded initially with the resources. The store then gets updated once, including all indicators. Before, the store was updated after the initial load. Also, this happened for each resource, resulting in a re-render of each table row.
* Creating shares & public links: Instead of loading share indicators for all resources in the store, we now only load those for the current file (and files inside a folder).
- https://github.com/owncloud/web/issues/7038
Tests were done with a shared folder including 800 files. Note that the measured time is generally longer when the measurement tool is running. This …

Improve performance of share indicators

---

changelog/unreleased/enhancement-text-editor-block-file-extensions
docs/deployments/oc10-app.md
packages/web-app-text-editor/src/index.js

Allow to block file extensions of the text-editor app
- Works towards https://github.com/owncloud/web/issues/6661

Allow blocking file extensions of text-editor

---

.drone.star

This PR updates the image `meltwater/drone-cache:v1` to official S3 cache plugin `plugins/s3-cache:1`.
Changes done in `.drone.star`:
1. Used official S3 cache plugin image `plugins/s3-cache:1` for cache rebuild, restore, and purge instead of `meltwater/drone-cache:v1` image
2. Refactored the steps settings configuration as per the S3 cache plugin
- Fixes https://github.com/owncloud/web/issues/7185
- CI

[full-ci] [tests-only] Using `plugins/s3-cache:1` instead of `meltwater/drone-cache:v1`

---

changelog/unreleased/bugfix-shared-with-others-page-apps-not-working-oc10
packages/web-app-files/src/helpers/resources.ts
tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md

Bugfix: Shared with others page apps not working with oc10 as backend
We've fixed a bug where apps like preview, pdf-viewer or text-editor weren't working while browsing
the shared with others page with oc10 as backend.
- Fixes https://github.com/owncloud/web/issues/7049
- test case 1:
- test case 2:
- ...

Bugfix: Shared with others page apps not working with oc10 as backend

---

changelog/unreleased/bugfix-token-renewal
packages/web-runtime/src/services/auth/authService.ts

For OIDC auth scenarios the `exit` link on the access denied page was not doing anything. Fixed by redirecting to the post logout redirect uri when logging out a user.

Add exit redirect

---

changelog/unreleased/enhancement-ocis-resharing
packages/web-app-files/src/mixins/actions/createQuicklink.js

with the recent integration of resharing for ocis we missed to update the quicklink creation action mixin.
This is fixed with a fallback chain to retrieve the corresponding storageid.
Fixes #7225

fix quicklink action storageid retrieval

---

.drone.star

In this PR, the `filename` property is used for the `plugins/s3-cache:1` image in a drone to create a different cache file.
- Fixes https://github.com/owncloud/web/issues/7245
- Related to https://github.com/owncloud/web/issues/7185
Rebuiling of cache replace the previous cache file and the wrong cache was restored.
- CI

[full-ci] [tests-only] Used `filename` properties for unique cache name

---

changelog/unreleased/enhancement-ocis-resharing
packages/web-app-files/src/helpers/share/link.ts
packages/web-app-files/src/quickActions.js

- Fixes https://github.com/owncloud/web/issues/7224
- test case 1:
- test case 2:
- ...

[full-ci] Fix wrong space ref

---

.drone.star

When we run tests at night and the tests fail, we don't get a trace https://drone.owncloud.com/owncloud/web/26735/10/12
To find out what happened, I enabled night tracing. 
I didn't make the tracing result public, we can get the tracing from `uploadTracingResult`.

Enable tracing nightly

---

changelog/unreleased/bugfix-repair-navigtion-highlighter
changelog/unreleased/enhancement-show-search-item-in-left-sidebar
packages/web-app-files/src/index.js
packages/web-runtime/src/components/SidebarNav/SidebarNav.vue

- Fixes https://github.com/owncloud/web/issues/7190
- test case 1:
- test case 2:
- ...

Remove nav item & fix greyed out nav item on search

---

.drone.env
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md

This issue https://github.com/owncloud/ocis/issues/3631  is passing on ocis. And is making fail to the ocis CI https://drone.owncloud.com/owncloud/ocis/13427/61/13. This PR removes the issue from expected to failure.
https://github.com/owncloud/ocis/issues/4197

[tests-only] Updated expected to failure as the tests is passing on OCIS

---

tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature

Acceptance test `webUISharingPermissionsUsers/sharePermissionsUsers.feature:122` was failing on the Then step that asserts share properties. The main reason for the failure was that the `permissions` was not changed from 1 to 17 at the time of assertion.
In this PR, I have added a permission check in the webUI after the permission has changed.
- Fixes #7203

[tests-only][full-ci] Check share permissions in the webUI after changing

---

changelog/unreleased/enhancement-add-keyboard-navigation-selection
packages/web-app-files/src/App.vue
packages/web-app-files/src/components/FilesList/KeyboardActions.vue

See https://github.com/owncloud/web/issues/7254 Point 2
- Works towards https://github.com/owncloud/web/issues/7254

Fixed keyboard up/down triggers scroll behaviour for no reason

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIRenameFiles/renameFiles.feature

Issue https://github.com/owncloud/ocis/issues/2249 is not valid for the ocis feature. See comment https://github.com/owncloud/ocis/issues/2249#issuecomment-1184207463
With this PR:
- the related scenario is skipped for the tests running with ocis backend
- the related scenario line is removed from the expected failures list
Related:
- fixes: https://github.com/owncloud/ocis/issues/2249
Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>

[tests-only] skip the scenario related to ocis issue 2249 with ocis backend

---

changelog/unreleased/enhancement-add-keyboard-navigation-selection
packages/web-app-files/src/components/FilesList/KeyboardActions.vue

See https://github.com/owncloud/web/issues/7254 Point 3
- Works towards https://github.com/owncloud/web/issues/7254

Bugfix: Keyboard selection tab

---

changelog/unreleased/bugfix-print-backend-version
packages/web-runtime/src/index.ts

Move announcing the frontend and backend versions (e.g. to browser console) to after the context has been initialized, because we need capabilities for the backend version. Since this is realiably blocking now, we actually also have the backend version printed on the first page load after login (was never working before).
- Fixes https://github.com/owncloud/web/issues/7272

Fix printing backend version to browser console

---

changelog/unreleased/bugfix-oidc-callback-browser-history
packages/web-runtime/src/services/auth/authService.ts

Replace oidc-callback url with redirect url for clean browser history.
- Fixes https://github.com/owncloud/web/issues/3071
- **UX:** We don't want the user to go back to the oidc-callback 
- **Security:** We don't want to leak possibly sensitive data into the browser history

Replace oidc-callback url with redirect url for clean browser history

---

tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js
tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js

The cause of the intermittent failure of `webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:11` test has been reported here https://github.com/owncloud/web/issues/7227#issuecomment-1186802393.
With the latest web, the public link expiration date picker has a new selector. I have changed the selector to a new value in this PR.
Also, the expiration date picker while editing user/group share is in a different dropdown list and this PR has added a new condition to select the correct date picker element while editing user/group share.
It removes error logs like below:
```diff
- Error while running .executeScript() protocol action: An error occurred while executing user supplied JavaScript. – 
- javascript error: Cannot read properties of undefined (rea...
```
With these changes, …

[tests-only][full-ci] Fix expiration date picker element selector

---

changelog/unreleased/bugfix-personal-shares-in-project-space
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/SharesPanel.vue
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/services/folder/spaces/loaderProject.ts

We're using the `fileId` of resources in various requests, but the space lacks a value in the `fileId` field. Fixed in this PR.
Also killed some dead method in the `FileLinks.vue` component.
- Fixes https://github.com/owncloud/web/issues/7268

Use id as fileId in space resource entities

---

changelog/unreleased/bugfix-upload-overlay-progress-bar-spacing
packages/web-runtime/src/components/UploadInfo.vue

We've fixed spacing issues with the upload overlay progress bar.
Before:
After:

Fix spacing of the upload progress bar

---

changelog/unreleased/bugfix-token-renewal-during-upload
packages/web-runtime/src/composables/upload/useUpload.ts
packages/web-runtime/src/services/uppyService.ts

We've fixed the access token renewal during ongoing uploads.
- Fixes https://github.com/owncloud/web/issues/7240

Fix access token renewal during upload

---

changelog/unreleased/bugfix-remove-lazy-table-loading-delay
changelog/unreleased/enhancement-update-ods
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-runtime/package.json
yarn.lock

We've removed the lazy loading delay on the OcTable to improve the overall performance.
- https://github.com/owncloud/web/issues/7038

Remove lazy table loading delay

---

changelog/unreleased/enhancement-redesign-shared-with-list
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/AutocompleteItem.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.js.snap
tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRootCollaborator/shareWithUsers.feature
tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js

- Fixes https://github.com/owncloud/web/issues/7110
- test case 1:
- test case 2:
- ...

Redesign shared with list

---

packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/search/sdk/list.ts
packages/web-app-files/src/search/sdk/preview.ts
packages/web-app-files/tests/unit/components/Search/List.spec.js
packages/web-app-files/tests/unit/search/sdk.spec.ts
packages/web-runtime/package.json
yarn.lock

- Fixes https://github.com/owncloud/web/issues/7192
- test case 1:
- test case 2:
- ...

Fix: Search does not find all files

---

changelog/unreleased/bugfix-remove-lazy-table-loading-delay
changelog/unreleased/bugfix-table-lazy-loading-performance
changelog/unreleased/enhancement-update-ods
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-runtime/package.json
yarn.lock

We've increased the performance of the files table by moving the loading visualization from the OcTd to the OcTr component.
A file list with 1000 files now takes ~1,6 seconds for a complete page load, whereas before it was roughly ~3 seconds.
- https://github.com/owncloud/web/issues/7038

Improve table lazy loading performance

---

changelog/unreleased/bugfix-repair-navigtion-highlighter
packages/web-runtime/src/components/SidebarNav/SidebarNav.vue

ResizeObserver in the sidebar nav highlighter was not set correctly, hence the console error messages when switching to a view without sidebar (see screenshot). Also inverted the early returns into conditional setters, because we **always** want to reach the code block where we add the beforeDestroy event listener.
Keep the browser console clean, correctly terminate resize observer.

fix: resize observer disconnect in sidebar highlighter

---

changelog/unreleased/bugfix-users-list-not-loading-if-user-has-no-role
packages/web-app-user-management/src/components/Users/UsersList.vue
packages/web-app-user-management/src/views/Users.vue

- Fixes https://github.com/owncloud/web/issues/7326
- test case 1:
- test case 2:
- ...

Fix users list doesn't load if user has no role

---

changelog/unreleased/enhancement-redesign-shared-with-list
packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.js.snap
tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js
tests/acceptance/stepDefinitions/sharingContext.js

Moved access details button into  3-dot menu
- test case 1:
- test case 2:
- ...

[full-ci] Redesign share with list followup

---

changelog/unreleased/bugfix-no-redirect-after-disabling-space
packages/web-app-files/src/mixins/spaces/actions/disable.js
packages/web-app-files/src/views/spaces/Projects.vue

- Fixes https://github.com/owncloud/web/issues/7291
- test case 1:
- test case 2:
- ...

Redirect to spaces overview if space get's disabled

---

changelog/unreleased/bugfix-preview-app-filename-hovers-over-image
changelog/unreleased/bugfix-preview-infinite-loading-spinner
packages/web-app-preview/src/App.vue
packages/web-pkg/src/components/AppTopBar.vue

Fixes flickering in App Top Bar when browsing through files quickly. (as the top bar hasn't been released so far, I just added this PR to the according changelog item file)
Fixes infinite loading spinner on invalid filenames in url (e.g. when a bookmark is outdated)
- test case 1:
- test case 2:
- ...

Preview fixes

---

changelog/unreleased/bugfix-link-indicator-shared-via-link-page
changelog/unreleased/enhancement-update-ods
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-runtime/package.json
tests/acceptance/pageObjects/sharedWithOthersPage.js
yarn.lock

We've fixed the icon and the sidebar for the link indicator on the "Shared via link"-page.
- Fixes https://github.com/owncloud/web/issues/7345

Fix link indicator on 'Shared via link'-page

---

changelog/unreleased/bugfix-loading-state-in-views
packages/web-app-files/src/components/TrashBin.vue
packages/web-app-files/src/composables/resourcesViewDefaults/useResourcesViewDefaults.ts
packages/web-app-files/src/views/Favorites.vue
packages/web-app-files/src/views/Personal.vue
packages/web-app-files/src/views/PublicFiles.vue
packages/web-app-files/src/views/shares/SharedResource.vue
packages/web-app-files/src/views/shares/SharedViaLink.vue
packages/web-app-files/src/views/shares/SharedWithMe.vue
packages/web-app-files/src/views/shares/SharedWithOthers.vue
packages/web-app-files/src/views/spaces/Project.vue
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/components/TrashBin.spec.js
packages/web-app-files/tests/unit/views/Favorites.spec.js
packages/web-app-files/tests/unit/views/Personal.spec.js
packages/web-app-files/tests/unit/views/PublicFiles.spec.ts
packages/web-app-files/tests/unit/views/shares/SharedViaLink.spec.js
packages/web-app-files/tests/unit/views/shares/SharedWithMe.spec.js
packages/web-app-files/tests/unit/views/shares/SharedWithOthers.spec.js
packages/web-app-files/tests/unit/views/views.shared.ts
packages/web-runtime/tests/unit/components/SidebarNav/SidebarNavItem.spec.js

Noticed that the `Personal` view showed the `Resource not found` component for a brief moment before the resource loader task was started. This is due to the task API not announcing itself as `isRunning=true` when there is no task instance, yet. Fixed in all views by adding a check for the absence of a loader task instance (in addition to the `isRunning` check).

[full-ci] fix: render loading state before loading starts

---

changelog/unreleased/bugfix-batch-delete-multiple-files
packages/web-app-files/src/mixins/spaces/actions/delete.js
packages/web-app-files/src/store/actions.js
packages/web-app-files/src/store/mutations.js
packages/web-app-files/src/views/Personal.vue
packages/web-app-files/src/views/PublicFiles.vue
packages/web-app-files/src/views/shares/SharedResource.vue
packages/web-app-files/src/views/spaces/Project.vue
packages/web-app-files/tests/unit/components/components.setup.js
packages/web-app-files/tests/unit/views/views.setup.js

We've fixed a bug where deleting many files in a batch action would fail.
- Fixes https://github.com/owncloud/web/issues/7329

Fix batch deleting multiple files

---

changelog/unreleased/enhancement-declined-shares-not-easily-accessible
changelog/unreleased/enhancement-declined-shares-now-easily-accessible
packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
packages/web-app-files/src/views/shares/SharedWithMe.vue
packages/web-app-files/tests/unit/views/shares/SharedWithMe.spec.js
tests/e2e/support/objects/app-files/share/actions.ts

Enhancement: Declined shares are not easily accessible
We've redesigned the 'Shared with me' page,
so the 'Declined shares' section is now displayed under the 'Accepted shares' section.
There is no need to click the toggle button anymore which makes the 'Declined shares' easily accessible.
- Fixes https://github.com/owncloud/web/issues/7342
- test case 1:
- test case 2:
- ...

Rearange declined shares

---

changelog/unreleased/bugfix-loading-state-in-views
packages/web-app-files/src/views/spaces/Projects.vue

Followup of https://github.com/owncloud/web/pull/7325 which introduced a broken loading state for the project spaces overview.

fix: loading state in projects view

---

packages/web-app-files/src/helpers/contextualHelpers.js
packages/web-runtime/package.json
yarn.lock

- Part of https://github.com/owncloud/web/issues/7331
- test case 1:
- test case 2:
- ...

contextual helpers - ods adjustments

---

changelog/unreleased/bugfix-tooltips-not-shown-on-disabled-create-and-upload-button
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue

- Fixes https://github.com/owncloud/web/issues/5937
- test case 1:
- test case 2:
- ...

Fix tooltips are not shown on disabled buttons

---

changelog/unreleased/enhancement-user-management-app-saved-dialog
packages/web-app-user-management/src/components/CompareSaveDialog.vue
packages/web-app-user-management/src/components/Groups/SideBar/EditPanel.vue
packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue
packages/web-app-user-management/src/components/Users/SideBar/GroupAssignmentsPanel.vue
packages/web-app-user-management/src/views/Users.vue
packages/web-app-user-management/tests/unit/views/Users.spec.js

- Fixes https://github.com/owncloud/web/issues/7351
- test case 1:
- test case 2:
- ...

User management bottom bar state saved

---

packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
packages/web-app-files/src/helpers/resource/copyMove.ts
packages/web-app-files/src/mixins/actions/emptyTrashBin.js
packages/web-app-files/src/mixins/spaces/actions/delete.js
packages/web-app-files/src/mixins/spaces/actions/disable.js

While closing https://github.com/owncloud/web/issues/1872#issuecomment-1200886554 I saw that the delete link confirmation dialog was missing the warning icon in the title section of the modal. Added it and checked all other danger variation modals of the files app as well.
Didn't add a changelog item on purpose, because it's only an additional icon that was missing before.
- Related to https://github.com/owncloud/web/issues/1872

fix: add warning icon to delete link confirm dialog

---

changelog/unreleased/bugfix-decline-share-not-possible
changelog/unreleased/bugfix-open-file-on-shared-space-resource-not-possible
changelog/unreleased/bugfix-rename-shared-space-resource-not-possible
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/mixins/actions/declineShare.js
packages/web-app-files/src/mixins/actions/delete.js

- Fixes Part of https://github.com/owncloud/web/issues/6899
- test case 1:
- test case 2:
- ...

Sharing jail followup #1

---

changelog/unreleased/enhancement-user-management-app-saved-dialog
packages/web-app-user-management/src/components/CompareSaveDialog.vue

- Fixes https://github.com/owncloud/web/issues/6914
- test case 1:
- test case 2:
- ...

Break buttons into new line if side bar gets to small

---

changelog/unreleased/enhancement-right-sidebar-fixed-width
packages/web-app-files/src/App.vue
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/tests/unit/components/AppBar/__snapshots__/AppBar.spec.js.snap

We've set a fixed width of 440px to the right sidebar to have better control of its styling and alignment.

[full-ci] Use fixed width for the right sidebar

---

changelog/unreleased/enhancement-drop-menu-styling-right-sidebar
changelog/unreleased/enhancement-update-ods
packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
packages/web-app-files/src/components/SideBar/Shares/Shared/RoleItem.vue
packages/web-app-files/src/helpers/share/role.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/RoleDropdown.spec.js.snap
packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/DetailsAndEdit.spec.js.snap
packages/web-app-files/tests/unit/helpers/share/role.spec.ts
packages/web-runtime/package.json
packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
packages/web-runtime/src/components/Topbar/ApplicationsMenu.vue
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/e2e/support/objects/app-files/link/actions.ts
yarn.lock

We've styled and aligned all the drop menus in the right sidebar to match with the other drop menus. Additionally, we've removed the icon-highlight-box in the application menu and the left navigation.
- Fixes https://github.com/owncloud/web/issues/7335

[full-ci] Align drop menus

---

changelog/unreleased/bugfix-suppress-active-panel-error-log
packages/web-app-files/src/components/SideBar/Shares/SharesPanel.vue

We now suppress error logs which occurred when opening the sidebar without an active panel.

Suppress active panel error logs

---

changelog/unreleased/bugfix-selected-item-bottom-glue
packages/web-app-files/src/mixins/filesListScrolling.js
packages/web-app-files/src/services/folder/legacy/loaderPersonal.ts
packages/web-app-files/src/services/folder/spaces/loaderPersonal.ts
packages/web-app-files/src/views/Personal.vue
packages/web-app-files/src/views/shares/SharedResource.vue

We've fixed a bug where the selected item would be glued to the bottom when scrolling up via keyboard navigation. Also, the scrollTo param has been fixed and is now working again.
- Fixes https://github.com/owncloud/web/issues/7318

Fix selected item bottom glue

---

changelog/unreleased/bugfix-storage-id-shared-parent-directory
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue

We've added the missing storage ID when navigating to a shared parent directory.

Add storage ID when navigating to a shared parent directory

---

changelog/unreleased/enhancement-ocis-resharing
packages/web-app-files/src/helpers/resources.ts

Regression due to https://github.com/owncloud/web/pull/7319 (because it changed how the current Folder is loaded).
- Fixes https://github.com/owncloud/web/issues/7397

Take permissions into account for create/upload buttons in share jail

---

changelog/unreleased/enhancement-add-tags-to-resource-table
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
packages/web-app-files/src/helpers/resources.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-runtime/package.json
yarn.lock

See https://github.com/owncloud/web/issues/7169
Needs: https://github.com/owncloud/owncloud-design-system/pull/2284
- Fixes https://github.com/owncloud/web/issues/7169
- https://github.com/owncloud/owncloud-design-system/pull/2284

Add tags to ResourceTable

---

changelog/unreleased/enhancement-adjust-helper-texts
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/helpers/contextualHelpers.js
packages/web-app-files/src/views/shares/SharedViaLink.vue
packages/web-app-files/tests/unit/views/shares/__snapshots__/SharedViaLink.spec.js.snap

- Fixes https://github.com/owncloud/web/issues/7331
- test case 1:
- test case 2:
- ...

Adjust contextual helpers

---

changelog/unreleased/bugfix-space-quota-permission
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/mixins/spaces/actions/editQuota.js
packages/web-app-files/tests/unit/mixins/spaces/editQuota.spec.js
packages/web-pkg/src/services/permissionManager.ts

By taking the space quota permission into account, we've fixed a bug where a regular space member could see the "Edit space quota" action.
- Fixes https://github.com/owncloud/web/issues/7400

Respect space quota permission

---

.drone.star
tests/drone/build-ocis.sh
tests/drone/check-for-existing-oCIS-cache.sh

Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>
- Remove `unitTestsOnly` file check (removed a long time ago from the drone star)
- Exit the pipeline early without failure if the cache for oCIS is already available
- Skip If Unchanged check for oCIS cache pipeline is removed. Since oCIS is pinned to a commit id, we ping the cache server to decide whether to proceed further or not. The oCIS cache is kept as a long-term cache so that the whole pipeline steps are executed only if the commit id changes.
- ci

[ci] Update build ocis script

---

changelog/unreleased/enhancement-permissionless-links
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/helpers/share/permission.ts
packages/web-app-files/src/helpers/share/role.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Links/DetailsAndEdit.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/DetailsAndEdit.spec.js.snap
packages/web-pkg/src/composables/capability/useCapability.ts
packages/web-pkg/src/constants/share.ts

~Cleaning up my local git stash and came across this draft. Needs concepting how to properly turn this into an oCIS-only feature.~ Update: alias-link capability has landed in oCIS
- Works towards #6844

Add alias links to web UI

---

tests/acceptance/pageObjects/personalPage.js
tests/acceptance/stepDefinitions/filesContext.js

This is a test PR to check if the `Scenario: conflict with a big file (when chunking is implemented this upload should be chunked)` fails or not after waiting for the `Upload complete` dialog if it does then how often it does. 
The PR can be merged only when we have strong evidence to say that the added wait for the `Upload complete` dialog prevents the test scenario to fail.
https://github.com/owncloud/web/issues/7369
As soon as the overwritten file gets uploaded, a tiny `Upload complete` dialog appears on the button right corner of the web UI and IMO we can add a piece of code to check for the appearance of that dialogue too to ensure that the overwritten file gets uploaded successfully. 
So in this PR, I've added that code inside confirmFileOverwrite() function.
- Locally
- On CI

[tests-only][full-ci] wait for `uploadCompleteDialog` to confirm the upload of overwritten file

---

changelog/unreleased/bugfix-re-fetch-quota
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/components/SpaceQuota.vue
packages/web-app-files/src/mixins/actions/restore.js
packages/web-app-files/src/mixins/deleteResources.js
packages/web-app-files/src/services/folder/legacy/loaderPersonal.ts
packages/web-app-files/src/services/folder/spaces/loaderPersonal.ts
packages/web-app-files/tests/unit/components/__snapshots__/SpaceQuota.spec.js.snap
packages/web-app-files/tests/unit/mixins/actions/restore.spec.js
packages/web-app-files/tests/unit/mixins/deleteResources.spec.js
packages/web-runtime/src/components/Topbar/UserMenu.vue
packages/web-runtime/src/services/auth/userManager.ts
packages/web-runtime/src/store/user.ts

**Note: While uploading files with uppy we check the quota of the respective space, this is why we should keep spaces in sync**
Tackling the following issues:
- Uploading or deleting files doesn't update project spaces quota
- Restoring files doesn't update project spaces or personal quota 
- Reload outside of the personal home doesn't show quota in the user menu
- Fixes https://github.com/owncloud/web/issues/6930
- Fixes https://github.com/owncloud/web/issues/7389
- test case 1:
- test case 2:
- ...

update space quota on upload, delete and restore

---

packages/web-app-files/src/mixins/actions/restore.ts
packages/web-app-files/src/mixins/spaces/actions/delete.js
packages/web-app-files/src/mixins/spaces/actions/disable.js
packages/web-app-files/src/mixins/spaces/actions/editDescription.js
packages/web-app-files/src/mixins/spaces/actions/rename.js
packages/web-app-files/src/mixins/spaces/actions/restore.ts
packages/web-app-files/src/mixins/spaces/actions/setImage.js
packages/web-app-files/src/mixins/spaces/actions/uploadImage.js
packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js
packages/web-app-files/tests/unit/components/SideBar/FileInfo.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.js.snap
packages/web-runtime/src/components/Avatar.vue
tests/unit/stubs/index.js

fixes https://github.com/owncloud/web/issues/6337 again

fix: cleanup unit tests, avoid warnings

---

.drone.env
changelog/unreleased/enhancement-add-tags-to-resource-table
changelog/unreleased/enhancement-tags-support
packages/web-app-files/src/components/FilesList/ContextActions.vue
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/TagsPanel.vue
packages/web-app-files/src/fileSideBars.ts
packages/web-app-files/src/helpers/resource/filter.ts
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/mixins/actions/showEditTags.js
packages/web-app-files/src/mixins/fileActions.ts
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.js.snap
packages/web-app-search/src/portals/SearchBar.vue
packages/web-app-search/tests/unit/portals/SearchBar.spec.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-pkg/src/constants/dav.ts
packages/web-runtime/package.json
tests/acceptance/features/webUIFilesActionMenu/fileFolderActionMenu.feature
yarn.lock

EXPERIMENTAL!
Managing files via tags is now possible in web, the feature is experimental and will be only available through a dedicated experimental web build.
Beside that the web version is experimental, it also needs a special experimental ocis version.
Creating Tags, tagging resources and search for tags now is possible and can be used as an alternative way of working and organizing resources.

[full-ci] Tags

---

changelog/unreleased/enhancement-tags-support
packages/web-app-files/src/components/FilesList/ResourceTable.vue

Add tag icon and text truncation.

Truncate tags

---

packages/web-runtime/package.json
packages/web-runtime/src/services/auth/userManager.ts
packages/web-runtime/src/store/settings.js
yarn.lock

Supersedes some dependabot PRs and bumps the SDK's dependencies to their most recent versions (most interesting here is `axios`, originally had the bump included in #7139 but then had unexpected failures in the acceptance tests)

[full-ci] Bump (peer)dependencies

---

changelog/unreleased/enhancement-redesign-shared-with-list
packages/web-app-files/src/components/SideBar/FileInfo.vue

- Fixes https://github.com/owncloud/web/issues/7471
- test case 1:
- test case 2:
- ...

Fix: Sidebar cripples file name which is not visible

---

changelog/unreleased/bugfix-default-to-user-context
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
packages/web-pkg/src/components/AppTopBar.vue
packages/web-pkg/src/composables/appDefaults/useAppNavigation.ts
packages/web-runtime/src/App.vue
packages/web-runtime/src/router/helpers.ts
packages/web-runtime/src/router/setupAuthGuard.ts

We've fixed a bug where routes without explicit `auth` requirement (i.e. user context) and without any context route in the URL were recognized as neither user-context nor public-link-context. In such situations we now expect that the session requires a user and redirect to the login page (instead of staying stuck on a most likely broken page).
We want to provide an endpoint in `ocis` that let's e.g. the desktop client query a URL for opening a document (via app provider / external app) in web. The desktop client has the file id and the app provider is capable of determining a default app if no app name is provided. But neither the desktop client nor the ocis backend know what route the file might have come from if opened via files app. Opening a file in web from the desktop client is …

fix: context fallback to user instead of undefined

---

changelog/unreleased/bugfix-space-share-actions
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/store/actions.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js
packages/web-app-files/tests/unit/store/actions.spec.js

We've fixed a bug where viewers and editors of a space could see the actions to edit and remove shares. We've also improved the error handling when something goes wrong while editing/removing shares.
- Fixes https://github.com/owncloud/web/issues/7436

Hide share actions for space viewers/editors

---

changelog/unreleased/bugfix-user-management-app-close-sidebar-throws-error
packages/web-app-user-management/tests/unit/components/AppTemplate.spec.js

- test case 1:
- test case 2:
- ...

User management -> app template component -> add test

---

tests/e2e/cucumber/features/integrations/spaces/publicLink.ocis.feature
tests/e2e/cucumber/steps/app-files/link.ts
tests/e2e/support/objects/app-files/link/actions.ts
tests/e2e/support/objects/app-files/link/index.ts
tests/e2e/support/objects/app-files/spaces/actions.ts
tests/e2e/support/objects/app-files/spaces/index.ts

This PR adds e2e test for public link spaces story.
https://github.com/owncloud/web/issues/7407
- Locally
- On CI

[full-ci][tests-only] e2e test for spaces publiclink story

---

tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature

Skipping an unstable link expiry test that started to fail on master two days ago, see https://github.com/owncloud/web/issues/7499

[full-ci] ci: skip unstable link expiry test

---

changelog/unreleased/bugfix-shared-via-indicator-for-links
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.js.snap

We've fixed a bug where the "Shared via"-indicator would be empty or not be displayed at all for public links.
- Fixes https://github.com/owncloud/web/issues/7478

Fix 'Shared via'-indicator for links

---

changelog/unreleased/bugfix-space-image-sidebar
packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue

We've fixed a bug where the image of a space was not showing in the sidebar. It was broken because a) the image URL and b) the server URL were wrong. 
- Fixes https://github.com/owncloud/web/issues/7480

Fix missing space image in sidebar

---

changelog/unreleased/enhancement-replace-locationpicker-clipboard
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue

- Fixes https://github.com/owncloud/web/issues/7494

Fix line break for 'Paste here'-button

---

changelog/unreleased/enhancement-permissionless-links
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-client/src/helpers/share/role.ts
packages/web-client/tests/unit/helpers/share/role.spec.ts

The alias link role has not been filtered correctly in case of reshares (fixed by this PR).

fix: use alias link role capability correctly

---

changelog/unreleased/enhancement-resource-name-webdav-property
packages/web-app-files/src/helpers/resources.ts
packages/web-pkg/src/constants/dav.ts

We've added the resource name to the WebDAV properties. It is being used for building the resource (if given).
I also modified the extractFileExtension method to work with it.

Add resource name to the WebDAV properties

---

changelog/unreleased/bugfix-file-name-in-text-editor
packages/web-app-text-editor/src/App.vue

We've fixed a bug in the text editor where the UUID of a shared resource was being displayed instead of the file name.
- Fixes https://github.com/owncloud/web/issues/7292

Fix file name for shared files in text editor

---

changelog/unreleased/bugfix-file-name-in-text-editor
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-pkg/src/helpers/preview/privatePreviewBlob.ts

Fixes preview loading in the right sidebar.
- Fixes https://github.com/owncloud/web/issues/7517

fix: preview loading in share jail

---

changelog/unreleased/bugfix-left-sidebar-app-switch
packages/web-runtime/src/components/SidebarNav/SidebarNav.vue

We've fixed a bug where the active state of the left sidebar would glitch visually when switching apps.
- Fixes https://github.com/owncloud/web/issues/7526

Fix glitchy left sidebar when switching apps

---

changelog/unreleased/bugfix-allow-uploads-outside-users-home-despite-quota-exceeded
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-runtime/src/components/UploadInfo.vue
packages/web-runtime/src/services/uppyService.ts
packages/web-runtime/tests/unit/components/UploadInfo.spec.js

- Fixes https://github.com/owncloud/web/issues/6318
- Fixes https://github.com/owncloud/web/issues/5817
- test case 1:
- test case 2:
- ...

Change quota handling

---

tests/acceptance/pageObjects/personalPage.js
tests/acceptance/stepDefinitions/filesContext.js

This PR might fix this issue https://github.com/owncloud/web/issues/7369 since this issue is continuously failing on nightly. That issue cannot be reproduce locally but fails consistently on CI. I have debugged the scenario in CI and the refactor seems to be more consistent.
Out of 500+ scenarios it failed 183+ times
https://drone.owncloud.com/owncloud/web/27819/10/21
All passed Consistently (500+ scenarios)
https://drone.owncloud.com/owncloud/web/27852
Note: For more info refer above issue.

[tests-only][full-ci]Refactor code for upload nightly fail

---

tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js

The `calendar.move()` (vendor) function returns a promise, so the script that uses it should be run as an async script (with `executeAsync()` command).
I suspect that the intermittent failure reported [here](https://github.com/owncloud/web/issues/7227) is due to the race condition created by running async function using `execute()` command
Moving to `executeAsync()` command, I couldn't reproduce the failure.
- Closes https://github.com/owncloud/web/issues/7227 

[tests-only] Use async script execution command

---

tests/e2e/config.js
tests/e2e/cucumber/features/integrations/spaces/publicLink.ocis.feature
tests/e2e/cucumber/steps/app-files/link.ts
tests/e2e/support/objects/app-files/link/actions.ts
tests/e2e/support/objects/app-files/link/index.ts
tests/e2e/support/objects/app-files/spaces/actions.ts
tests/e2e/support/store/user.ts

e2e test for the public link space stories has been added in this PR. Specifically, this PR adds tests for a manager member regarding his permissions with a public link.
https://github.com/owncloud/web/issues/7407
- test case 1:
- test case 2:
- ...
-

[tests-only]  e2etest for spaces publiclink- Part2

---

tests/e2e/cucumber/features/integrations/reshare.feature
tests/e2e/cucumber/features/integrations/share.oc10.feature
tests/e2e/cucumber/features/integrations/share.ocis.feature
tests/e2e/cucumber/features/integrations/spaces/project.ocis.feature
tests/e2e/cucumber/features/journeys/kindergarten.oc10.feature
tests/e2e/cucumber/features/journeys/kindergarten.ocis.feature
tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts
tests/e2e/cucumber/steps/app-files/share.ts
tests/e2e/support/objects/app-files/share/actions.ts
tests/e2e/support/objects/app-files/spaces/actions.ts

related #7041
- added step share/reshare with group to reshare.ocis.feature 
- enabled re sharing test for oc10

[tests-only] add step sharing with group

---

changelog/unreleased/enhancement-propose-file-name-while-creating-file
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-runtime/src/services/auth/userManager.ts

- Fixes https://github.com/owncloud/web/issues/7539
- test case 1:
- test case 2:
- ...

resolve file duplicate name on creating new file

---

changelog/unreleased/enhancemnet-user-management-edit-quota
packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue
packages/web-app-user-management/src/views/Users.vue
packages/web-app-user-management/tests/unit/components/Users/SideBar/EditPanel.spec.js
packages/web-app-user-management/tests/unit/views/Users.spec.js

- Fixes https://github.com/owncloud/web/issues/7533
- test case 1:
- test case 2:
- ...

Only update changed data 

---

.drone.star

- Add config dict for e2e test pipes
- Early fail on e2e test pipes
- If full-ci then, no early fail on e2e test pipes
- Fixes https://github.com/owncloud/web/issues/7547
- :robot: 
- with no `full-ci` and an intentional error on the e2e pipes: https://drone.owncloud.com/owncloud/web/27928
- with `full-ci` in the PR title and an intentional failure in the e2e suite: https://drone.owncloud.com/owncloud/web/27927
- with `skip` set as True: https://drone.owncloud.com/owncloud/web/27925

[full-ci][tests-only] add a full CI and early fail support for the e2e test pipelines

---

tests/e2e/support/objects/app-files/share/actions.ts
tests/e2e/support/objects/app-files/utils/sidebar.ts

#7566
fix flaky: So far, I've disabled this check for oc10 to stabilize CI 
As soon as we find a better solution, we'll enable it

[test-only] Fix re-sharing flaky

---

changelog/unreleased/enhancemnet-files-list-options-menu-spacing
packages/web-app-files/src/components/AppBar/ViewOptions.vue

We've adjusted the spacing of the files list options menu to visually match with the other menus.
- Fixes https://github.com/owncloud/web/issues/7541

Adjust spacing of the files list options menu

---

changelog/unreleased/bugfix-redirect-space-access-removal
packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
packages/web-app-files/src/mixins/spaces/actions/disable.js
packages/web-app-files/src/store/actions.ts

Two small fixes regarding spaces:
- when leaving a space, don't try to refetch it (causes 404, stops action with an error message)
- when disabling a space match with `projects` route first and return early. the `files-spaces-project` route without a storageId param is a prefix match to the `files-spaces-projects` route, thus it was still trying to redirect to the spaces overview despite already being there.
Fixes https://github.com/owncloud/web/issues/7534

Spaces fixes

---

changelog/unreleased/enhancement-left-sidebar-hover
packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
packages/web-runtime/src/components/SidebarNav/SidebarNavItem.vue

We had a glitchy left sidebar active item animation from a PR merged today. See https://github.com/owncloud/web/pull/7567#issuecomment-1234444330
This PR fixes it. Thanks @diocas for spotting and reporting it!

fix: don't apply hover and focus nav item style to active item

---

packages/web-app-external/tests/unit/app.spec.ts
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/helpers/resource/copyMove.ts
packages/web-app-files/src/store/actions.ts
packages/web-app-files/src/views/FilesDrop.vue
packages/web-app-files/tests/unit/helpers/resource/copyMove.spec.ts
packages/web-app-files/tests/unit/views/FilesDrop.spec.js
packages/web-app-user-management/src/search/filter/index.ts
packages/web-pkg/src/composables/appDefaults/useAppFileHandling.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/index.ts
packages/web-runtime/src/services/uppyService.ts

- test case 1:
- test case 2:
- ...

Decrease linter errors, keep commented tests warnings

---

.drone.star

This PR has implemented using the cached web in the web pipeline and remove unnecessary step from pipelines
[cache build-web-integration-app step in web](https://github.com/owncloud/QA/issues/762)

[full-ci][tests-only]Use cached web in drone pipelines

---

changelog/unreleased/enhancement-search-improvements
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/search/sdk/preview.ts
packages/web-app-files/tests/unit/components/Search/List.spec.js
packages/web-app-files/tests/unit/components/Search/__snapshots__/List.spec.js.snap
packages/web-app-search/src/portals/SearchBar.vue
packages/web-app-search/src/views/List.vue
packages/web-app-search/tests/unit/portals/SearchBar.spec.ts

- Fixes https://github.com/owncloud/web/issues/5644
- Fixes https://github.com/owncloud/web/issues/7587
- test case 1:
- test case 2:
- ...

Common search improvements

---

changelog/unreleased/bugfix-typo-reading-capabilities-pl
packages/web-pkg/src/composables/capability/useCapability.ts

Typo in the capabilities path which prevents showing the extra roles for public links

Fix links capabilities checks

---

changelog/unreleased/enhancement-reduce-pagination-options
packages/web-app-files/src/components/AppBar/ViewOptions.vue

We've reduced the pagination options by removing the options to display 1000 and all files. These may be added again later after further improving the files table performance.
- https://github.com/owncloud/web/issues/7038

Reduce pagination options

---

changelog/unreleased/enhancement-simplify-mime-type-checking
packages/web-integration-oc10/lib/Controller/FilesController.php

This removes the dependency to guzzle.
Supersedes https://github.com/owncloud/web/pull/5933
Maintain compatibility with oc10 (change needed for oc10.11 release).

chore: simplify mime type checking

---

.drone.env
changelog/unreleased/bugfix-search-share-representation
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/Search/Preview.vue
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/search/sdk/list.ts
packages/web-app-files/src/search/sdk/preview.ts
packages/web-app-files/tests/unit/components/Search/Preview.spec.js
packages/web-client/src/helpers/resource/types.ts
packages/web-pkg/src/constants/dav.ts

- Fixes https://github.com/owncloud/web/issues/7043
- test case 1:
- test case 2:
- ...

[full-ci] Add search support for shares

---

.eslintrc.js
Makefile.release
changelog/unreleased/enhancement-remember-selected-ui
docker-compose.yml
packages/web-integration-oc10/appinfo/app.php
packages/web-integration-oc10/appinfo/routes.php
packages/web-integration-oc10/js/app.js
packages/web-integration-oc10/lib/Application.php
packages/web-integration-oc10/lib/Controller/SettingsController.php
packages/web-runtime/src/components/Topbar/ApplicationsMenu.vue
sonar-project.properties

This needs https://github.com/owncloud/core/pull/39600 to work.
- https://github.com/owncloud/enterprise/issues/4694
- Closes #5610

Remember the UI that was last selected via the application switcher

---

packages/web-app-user-management/src/components/Groups/SideBar/EditPanel.vue
packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue
packages/web-app-user-management/src/components/Users/SideBar/GroupAssignmentsPanel.vue

Follow up of https://github.com/owncloud/web/pull/7609
- test case 1:
- test case 2:
- ...

Compare Save Dialog, simplify

---

changelog/unreleased/bugfix-expiration-date-de_DE
packages/web-runtime/src/App.vue

This PR fixes a bug where the expiration date picker in the sharing sidebar wouldn't open at all if the user selected a language with long language code (e.g. `de_DE`). Since this is only possible with oc10.11-rc.1 at the moment this issue didn't surface before testing oc web with that release candidate.
- Fixes https://github.com/owncloud/web/issues/7622

fix: use short language codes

---

changelog/unreleased/bugfix-merge-share-with-group-and-group-member
packages/web-app-files/src/helpers/resources.ts

Sorts the list of incoming shares by path and allows merging of share with group and group member into one share through listing them next to each other
Does sorting by path for all shares. 
- Fixes https://github.com/owncloud/web/issues/7582
If incoming shares are not sorted, shares with group and user - member of this group are not getting merged into one share.
- [] Documentation ticket raised: <link>

Fix: merge share with group and group member into one share

---

tests/e2e/cucumber/features/integrations/search.feature
tests/e2e/cucumber/features/integrations/share.oc10.feature
tests/e2e/cucumber/steps/app-files/resource.ts
tests/e2e/filesForUpload/.hidden-file.txt
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

- Part of: https://github.com/owncloud/web/issues/7395
- locally
- CI

[tests-only] Add e2e tests for searching

---

changelog/unreleased/bugfix-sidebar-toggle-icon
packages/web-app-files/src/components/AppBar/AppBar.vue

We've fixed a bug where the sidebar toggle icon would not detect the "open"-state of the sidebar.

Fix sidebar toggle icon

---

changelog/unreleased/bugfix-upload-modify-time
packages/web-runtime/src/composables/upload/useUpload.ts
packages/web-runtime/src/services/uppyService.ts

We've included the `x-oc-mtime` header in upload requests to tell the backend the proper modify date of uploaded resources.
Fyi: This is not yet being supported for tus by ocis (https://github.com/owncloud/ocis/issues/4559)
- Fixes https://github.com/owncloud/web/issues/7628

Include `x-oc-mtime` header in upload requests

---

changelog/unreleased/bugfix-shares-tree-loading
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/components/SideBar/Shares/SharesPanel.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/composables/parentShare/index.ts
packages/web-app-files/src/composables/parentShare/useIncomingParentShare.ts
packages/web-app-files/src/helpers/path.js
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/helpers/statusIndicators.js
packages/web-app-files/src/mixins/actions/rename.js
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.js.snap
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/RoleDropdown.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/FileLinks.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/SharesPanel.spec.js
packages/web-app-files/tests/unit/helpers/path.spec.js
tests/e2e/support/objects/app-files/share/actions.ts

We've improved loading of the shares tree:
* It now happens more globally in the sidebar component instead of in each sidebar panel.
* Shares won't be loaded for resources without a path anymore.
These changes massively improve the sidebar performance and fix several issues with (re-)share permissions.
Note: Needs ocis with the latest Reva update to include the `shareId`.
- Fixes https://github.com/owncloud/web/issues/7506
- Fixes https://github.com/owncloud/web/issues/7593
- Fixes https://github.com/owncloud/web/issues/7592

[full-ci] Fix sharesTree loading

---

tests/e2e/cucumber/features/integrations/spaces/participantManagement.ocis.feature
tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts
tests/e2e/support/objects/app-files/share/actions.ts
tests/e2e/support/objects/app-files/spaces/actions.ts

- Fixes: https://github.com/owncloud/web/issues/7035
- locally 
- CI

[tests-only]Add step for removing manager

---

changelog/unreleased/bugfix-private-link-alignment
packages/web-app-files/src/components/SideBar/FileInfo.vue

We've fixed the alignment of the "Private link"-button in the sidebar.
- Fixes https://github.com/owncloud/web/issues/7618

Fix 'Private link'-button alignment

---

changelog/unreleased/bugfix-upload-modify-time
packages/web-runtime/src/composables/upload/useUpload.ts
packages/web-runtime/src/services/uppyService.ts

Turns out, headers such as `mtime` have to be passed via `upload-metadata` to tus. See https://github.com/owncloud/ocis/issues/4559#issuecomment-1246512408.
I removed the `header` object from the tus plugin again, as it has no use.

Fix `mtime` header for tus requests

---

changelog/unreleased/enhancement-deny-subfolder-share
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/RoleDropdown.spec.js
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js
packages/web-client/src/helpers/resource/types.ts
packages/web-client/src/helpers/share/permission.ts
packages/web-client/src/helpers/share/role.ts
packages/web-client/src/helpers/space/functions.ts
packages/web-pkg/src/constants/dav.ts
yarn.lock

Porting over https://github.com/cernbox/web/commit/1d75877919e862fdecfdff3bae366ede3951ba1a
See changelog item

[full-ci] Migrate deny-acl UI code from CERNbox

---

packages/web-app-files/src/services/folder/loaderSharedWithOthers.ts
tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature

Remove share filtering, due to https://github.com/owncloud/ocis/issues/3592 is fixed 
- test case 1:
- test case 2:
- ...

Remove not needed share filtering code

---

changelog/unreleased/enhancement-make-keybindings-global
packages/web-app-files/src/components/FilesList/KeyboardActions.vue

Disable keyboard navigation on textarea and input

[full-ci] Keyboard navigation disable for inputs

---

packages/web-pkg/src/composables/translations/index.ts
packages/web-pkg/src/composables/translations/useTranslations.ts

With this composable you can inject our `$gettext` helper functions into code that's not Vue options API (e.g. setup functions, classes, ...).
Usage: `const { $gettext, $gettextInterpolate } = useTranslations()`. cc @lookacat since you needed this in another PR.

feat: add composable for translations

---

changelog/unreleased/bugfix-shares-loading
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/composables/parentShare/useIncomingParentShare.ts
packages/web-app-files/src/store/actions.ts

Shares tree caching is a problem in flat file lists that gather resources from various places (like "Shared with others", "Shared via link", ...). This is an issue because the caching currently happens purely based on the filename. However, these lists can contain multiple resources with the same name.
In the future, we should think about something else that also includes the storage ID. This is necessary anyway because of https://github.com/owncloud/web/issues/7655.
However, we don't have any performance impact by disabling the cache here as we can't navigate into folders anyway.
Followup for https://github.com/owncloud/web/pull/7638

Disable shares tree cache for flat file lists

---

changelog/unreleased/bugfix-spaces-on-share-via-link-page
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/fileSideBars.ts
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/mixins/actions/navigate.ts
packages/web-app-files/src/services/folder/loaderSharedViaLink.ts
packages/web-client/src/helpers/resource/types.ts

Spaces on the "Shared via link"-page are now being displayed correctly. Also, the sidebar for those has been fixed.
- Fixes https://github.com/owncloud/web/issues/7103

[full-ci] Fix spaces on the 'Shared via link'-page

---

changelog/unreleased/bugfix-search-sidebar-shares
packages/web-app-files/src/components/SideBar/SideBar.vue

We've fixed a bug where the sidebar for received shares in the search file list was broken.
- Fixes https://github.com/owncloud/web/issues/7661

Fix sidebar for received shares in search file list

---

changelog/unreleased/bugfix-shares-loading
packages/web-app-files/src/store/actions.ts

This fixes a bug where the loading state of the `sharesTree` was set to `false` once an error occurred. That's not correct as it can happen anytime during the (ongoing) loading process. We already set the loading state to `false` once the tree has been loaded eventually.

Fix `sharesTree` loading state on error

---

dev/docker/oc10.Dockerfile

With the current latest `owncloud/server` image (used in docker compose file), git library is not available. So, running oC10 using docker compose was failing.
This PR adds the missing git library needed for pre-setups.
- Fixes https://github.com/owncloud/web/issues/7672
Able to run oC10 setup using docker compose
- test environment: locally

Add missing git library for oC10 docker compose setup

---

.drone.env
packages/web-app-files/src/components/FilesList/ContextActions.vue
packages/web-app-files/src/mixins/actions/virusScan.ts

experimental feature, since we have virus scanning on ocis experimental we've now also have the ability to scan files "on demand". This PR adds the corresponding context action to do so.
- experimental
users should get the ability to check if files are infected. In theory this shouldnt be needed that often becaused the upload scan removes infected files immediately... but in cases where the virus is not known at the moment of uploading "on demand"  scanning helps. This can happen if the virus database is updated!
- local testing

add on demand virus scanning

---

packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/index.ts

This PR introduces the ability to configure scripts and style resources that will be injected into the SPA application.
This enables for example injection of small self containing scripts or style adjustments without rebuilding web or build a custom application.
needs https://github.com/owncloud/ocis/pull/4664

add option to inject css and js files

---

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature

After a share has been decline we do not require to browse to separate page (declined share page) and reload the page since after decline the decline section is still in that same page. When decline button is clicked then the page immediately reloads  which might be the factor that the share is not declined and still in pending state. So we do not need to reload the page.
https://github.com/owncloud/web/issues/7677
https://github.com/owncloud/web/issues/7677

[tests-only][full-ci] Fix for nightly failure decline share

---

tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js

Following measures were used to reduce the flakiness:
- Wait for the ajax calls that are initialized by the confirm button click
- wait for animations to be finished i.e. settling down the confirm dialog for the custom permissions. 
- Fixes https://github.com/owncloud/web/issues/7705
- :robot:

[tests-only] fix flaky acceptance share perm. scenario

---

changelog/unreleased/enhancement-design-polishing
changelog/unreleased/enhancement-update-ods
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/components/AppBar/CreateSpace.vue
packages/web-app-files/src/components/AppBar/SelectedResources/BatchActions.vue
packages/web-app-files/src/components/Spaces/SpaceHeader.vue
packages/web-app-files/src/mixins/spaces/actions/disable.js
packages/web-app-files/src/mixins/spaces/actions/restore.ts
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/components/AppBar/__snapshots__/AppBar.spec.js.snap
packages/web-app-files/tests/unit/mixins/spaces/disable.spec.js
packages/web-app-files/tests/unit/mixins/spaces/restore.spec.js
packages/web-app-user-management/src/components/AppTemplate.vue
packages/web-app-user-management/src/views/Groups.vue
packages/web-app-user-management/src/views/Users.vue
packages/web-pkg/src/components/NoContentMessage.vue
packages/web-runtime/package.json
packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.js.snap
tests/acceptance/pageObjects/appBarActions.js
tests/acceptance/pageObjects/publicLinkFilesPage.js
tests/e2e/support/objects/app-files/spaces/actions.ts
yarn.lock

- Fixes https://github.com/owncloud/web/issues/7676
- Fixes https://github.com/owncloud/web/issues/6705
- Works towards https://github.com/owncloud/web/issues/7693
- Fixes https://github.com/owncloud/web/issues/7694
- Fixes https://github.com/owncloud/web/issues/7685
- Addresses several issues reported in https://github.com/owncloud/web/issues/7525
* Redesign spaces overview
* Remove text and border line
* Fix breadcrumb alignment
* Show icon for sidebar
* Use fixed width for cards
* Align "Create Space"-button with "New" button in Personal Space
* Use `file-type="line"` for members icon
---
* Align spacing in left sidebar & breadcrumbs:
* Horizontally align breadcrumbs with chevron in the left sidebar
* Horizontally align the entries of the left sidebar with "Create"-Actions
* Fix …

[full-ci] Design polishing

---

changelog/unreleased/bugfix-folder-conflict
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/composables/upload/useUploadHelpers.ts
packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.js

* Fixed "Keep both" and "Skip" options in Firefox
* Fixed "Keep both" and "Skip" options when uploading via the "Upload"-menu
* Fixed broken "Upload"-menu after skipping all files (= no files uploaded)
* Fixed issues when uploading a folder into another folder which has or starts with the same name
- Fixes https://github.com/owncloud/web/issues/7680

Fix folder conflict dialog issues

---

changelog/unreleased/bugfix-spaces-reactivity-on-update
packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/components/SideBar/SpaceInfo.vue
packages/web-app-files/src/components/Spaces/QuotaModal.vue
packages/web-app-files/tests/unit/components/SideBar/SideBar.spec.js
packages/web-app-files/tests/unit/components/SideBar/SpaceInfo.spec.js
packages/web-app-files/tests/unit/components/Spaces/QuotaModal.spec.js

- Fixes https://github.com/owncloud/web/issues/7521
- test case 1:
- test case 2:
- ...

[full-ci] Space root not updated

---

changelog/unreleased/bugfix-copy-quicklink-translations
packages/web-app-files/src/helpers/share/link.ts
packages/web-app-files/src/mixins/actions/createQuicklink.ts
tests/acceptance/features/webUISharingPublicBasic/publicLinkCreate.feature

We've fixed a bug where the translation for the "Copy Quicklink"-notification was not working.
- Fixes https://github.com/owncloud/web/issues/7720
- Fixes https://github.com/owncloud/web/issues/7553

Fix 'Copy Quicklink'-translations

---

changelog/unreleased/bugfix-remove-close-sidebar-calls-on-delete
packages/web-app-files/src/store/actions.ts

We've removed the "close sidebar"-calls when deleting a resource as the mutations are not available as well as not needed anymore.
- Fixes https://github.com/owncloud/web/issues/7699

Remove the 'close sidebar'-calls on delete

---

changelog/unreleased/bugfix-file-name-reactivity
packages/web-app-files/src/components/SideBar/FileInfo.vue

We've fixed a bug where the file name would not update reactively in the sidebar after changing it.
- Fixes https://github.com/owncloud/web/issues/7713

Fix file name reactivity in sidebar

---

changelog/unreleased/bugfix-disappearing-quicklink-in-sidebar
packages/web-app-files/src/store/actions.ts

We've fixed a bug where existing quicklinks would disappear when performing the "Create quicklink"-action.
- Fixes https://github.com/owncloud/web/issues/7736

Fix disappearing quicklink in sidebar

---

changelog/unreleased/bugfix-disable-shares-loading-on-public-and-trash-locations
packages/web-app-files/src/components/SideBar/SideBar.vue

We've disabled shares loading on public and trash locations as it's not needed.
- Fixes https://github.com/owncloud/web/issues/7667

Disable shares loading on public and trash locations

---

changelog/unreleased/bugfix-reload-file-list-after-share-removal
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/store/actions.ts

We've fixed a bug where the file list would not update after removing the last share or link. Also, we now prevent the shares tree from being loaded again if the removed share was not the last one.
- https://github.com/owncloud/KoKo22/issues/69

Reload file list after last share removal

---

changelog/unreleased/enhancement-friendlier-logout-screen
packages/web-runtime/src/pages/accessDenied.vue
packages/web-runtime/src/store/config.js
tests/acceptance/pageObjects/loginErrorPage.js

See changelog item
- Fixes #7744 
@tbsbdr opted for a primary button (since it's the only one on the screen, and using a different one would add extra effort to make it compatible with bright/dark mode).

Fix #7744, make logout screen nicer

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature
tests/acceptance/features/webUISharingPublicManagement/publicLinkIndicator.feature

This PR skips the tests related to `Shares` folder based on this issue https://github.com/owncloud/ocis/issues/4678
Since there is no `Shares` folder generated onwebUI on `ocis` on root like `oc10` those tests fails. The related scenarios can be implemented on playwright (future).
https://github.com/owncloud/ocis/issues/4678#issuecomment-1274369466
https://github.com/owncloud/ocis/issues/4678

[tests-only][full-ci]Skip `Shares` folder on root related tests on ocis

---

tests/e2e/cucumber/features/integrations/search.feature
tests/e2e/cucumber/features/integrations/searchProjectSpace.ocis.feature

- added a new test `searchProjectSpace.ocis.feature` for ocis (project space), where I tried to find an object with special characters. Need add "?" and ":" characters after fixing https://github.com/owncloud/ocis/issues/4745 and https://github.com/owncloud/ocis/issues/4744
- modified the existing test `search.feature`. made it more readable. Changed step "find in current folder" because we don't send PROPFIND request. more detail here: https://github.com/owncloud/web/pull/7730#issuecomment-1268154272

[tests-only] added search test for project spce

---

changelog/unreleased/enhancement-internal-links
changelog/unreleased/enhancement-private-links
packages/web-app-files/src/helpers/resource/resource.ts
packages/web-app-files/src/helpers/resources.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-client/src/helpers/space/functions.ts
packages/web-client/src/helpers/space/types.ts
packages/web-runtime/src/pages/resolveFileLink.vue
packages/web-runtime/src/pages/resolvePrivateLink.vue
packages/web-runtime/src/router/index.ts
packages/web-runtime/tests/unit/pages/resolveFileLink.spec.ts
packages/web-runtime/tests/unit/pages/resolvePrivateLink.spec.ts

This PR adds the (a little bit hacky) ability to resolve private links / public links with "internal" role which point to files/folders within an accepted incoming share.
- Fixes https://github.com/owncloud/web/issues/7707
- Fixes https://github.com/owncloud/web/issues/6844
- Fixes https://github.com/owncloud/web/issues/7304

[full-ci] Resolve internal/private links on shares

---

.drone.star

Run `notify` pipeline after the `build` pipeline is finished. This will also notify about the status of `build` pipeline.
- Fixes https://github.com/owncloud/web/issues/6075

[ci][full-ci] Make notify pipeline dependent on build pipeline

---

changelog/unreleased/bugfix-space-trashbin-actions
packages/web-app-files/src/mixins/actions/delete.js
packages/web-app-files/src/mixins/actions/emptyTrashBin.js
packages/web-app-files/src/mixins/actions/restore.ts
packages/web-app-files/src/views/spaces/GenericTrash.vue
packages/web-app-files/tests/unit/mixins/actions/delete.spec.js
packages/web-app-files/tests/unit/mixins/actions/emptyTrashBin.spec.js
packages/web-app-files/tests/unit/mixins/actions/restore.spec.js
packages/web-client/src/helpers/space/functions.ts
packages/web-client/src/helpers/space/types.ts
tests/e2e/cucumber/steps/app-files/resource.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

Actions in space trash bins are now hidden if the current user has insufficient permissions.
- Fixes https://github.com/owncloud/web/issues/7702

Hide actions in space trash bins in case of insufficient permissions

---

changelog/unreleased/bugfix-trash-bin-sidebar
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/helpers/resources.ts

We've fixed the sidebar in the trash bin which was throwing errors and not showing the right content.
- Fixes https://github.com/owncloud/web/issues/7778

Fix sidebar in trash bin

---

changelog/unreleased/enhancement-id-based-routing
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/components/FilesList/KeyboardActions.vue
packages/web-app-files/src/helpers/resource/actions/transfer.ts
packages/web-app-files/src/mixins/actions/paste.js
packages/web-app-files/src/store/actions.ts

Fixing an issue with file list updates after coyping resources that was introduced when we added path correction based on fileIds.
- Fixes https://github.com/owncloud/web/issues/7774

fix: file list update after copying resources

---

packages/web-app-files/src/components/SideBar/TagsPanel.vue

Resource tags in resource sidebar haven't updated when changing resource.
This PR fixes that behavior and displays the tags for the selected resource.

Update resource tags

---

changelog/unreleased/bugfix-edit-new-created-user
packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue
packages/web-app-user-management/src/views/Users.vue

- Fixes https://github.com/owncloud/web/issues/7761
- Fixes https://github.com/owncloud/web/issues/7805
- test case 1:
- test case 2:
- ...

Change logic how passwordProfile is handled

---

tests/e2e/support/objects/app-files/resource/actions.ts

Sometimes the global search e2e test can fail intermittently due to the fact that after uploading files, the search index takes some time to be updated. If the test runs faster than this "some time", then the test will fail.
It seems that we either need to reload the page or wait for some time in order to get the updated search index. This PR has added `page.reload()` just before performing the search action. `page.reload()` seems to be fasterand reliable than using explicit wait.
The wait was also added in the acceptance test (acceptance) due to same issue, see https://github.com/owncloud/web/commit/f77d04015c66770718637f4668ce293166cb6874
- https://github.com/owncloud/ocis/issues/4849

[tests-only][e2e] Wait until the search indexing is finished

---

changelog/unreleased/bugfix-sidebar-without-highlighted-resource
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/fileSideBars.ts

Sidebar panels that require a resource now won't be loaded without such. This fixes a bug where navigating with an open sidebar would break it.
- Fixes https://github.com/owncloud/web/issues/7781

Fix sidebar when no highlighted resource is present

---

changelog/unreleased/bugfix-hide-search-bar-in-public-links
packages/web-app-search/src/portals/SearchBar.vue
packages/web-app-search/tests/unit/portals/SearchBar.spec.ts

The search bar in a public link context has been hidden because it requires authentication.
- Fixes https://github.com/owncloud/web/issues/7603

Hide search bar in public link context

---

changelog/unreleased/bugfix-share-permissions-for-reshares
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/composables/parentShare/useIncomingParentShare.ts

We've fixed a bug where the selectable roles on a re-share could exceed the parent share's permissions in certain scenarios.
- Fixes https://github.com/owncloud/web/issues/7657

Fix selectable share permissions for re-shares

---

changelog/unreleased/bugfix-link-indicator-shared-with-me
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.ts.snap

Link indicators in the sidebar on the "Shared with me"-page will now be displayed correctly.
- Fixes https://github.com/owncloud/web/issues/7697

Fix link indicator on 'Shared with me'-page

---

changelog/unreleased/bugfix-external-app-error-handling
packages/web-app-external/src/App.vue
packages/web-runtime/src/helpers/additionalTranslations.ts

Axios stopped execution if the response code was not 2xx, in those cases the app error message was never shown as expected. This pr allows axios to continue and does the error handling on its own.

continue on non 2xx responses

---

packages/web-app-external/src/App.vue
packages/web-app-external/tests/unit/__snapshots__/app.spec.ts.snap

Axios blocked all non 200 responses when opening an external application.
This pr allows axios to continue and handles the error cases on its own.

Allow non 200 app external axios responses 

---

changelog/unreleased/bugfix-hide-share-indicators-on-public-page
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.ts.snap

Share indicators are now being hidden on public link pages.
- Fixes https://github.com/owncloud/web/issues/7888

Hide share indicators on public page

---

changelog/unreleased/enhancement-validate-space-names
packages/web-app-files/src/components/AppBar/CreateSpace.vue
packages/web-app-files/src/mixins/spaces/actions/rename.js
packages/web-app-files/tests/unit/components/AppBar/CreateSpace.spec.js
packages/web-app-files/tests/unit/mixins/spaces/rename.spec.js

Spaces names are now being validated when creating or renaming spaces. The following special characters are not allowed: `/ \ . : ? * " > < |`
- https://github.com/owncloud/ocis/issues/4925

Add validation for space names

---

changelog/unreleased/bugfix-share-editing-not-possible
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue

We've fixed a bug where editing or deleting shares in the personal space was not possible if a project space was selected previously.
- Fixes https://github.com/owncloud/web/issues/7872

Fix share editing after selecting a space

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIRestrictSharing/restrictReSharing.feature
tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/features/webUISharingInternalUsersBlacklisted/shareWithUsers.feature

This PR skips tests related to the issue https://github.com/owncloud/ocis/issues/1328 for OCIS as these will be implemented for spaces but not like they are implemented in OC10 now.
- [Check closed issue No command equivalent to occ still exist in expected-to-failure ](https://github.com/owncloud/ocis/issues/4679)
- [Check closed issue [oCIS] Received share cannot be deleted/unshared if not shared with full permissions still exist in expected-to-failure](https://github.com/owncloud/ocis/issues/4683)
- locally
- CI

[full-ci][tests-only]Skip scenario related to occ command in ocis

---

changelog/unreleased/enhancement-optimize-email-validation
packages/web-app-user-management/src/components/Users/CreateUserModal.vue

- Fixes https://github.com/owncloud/web/issues/7806
- test case 1:
- test case 2:
- ...

Enhance email validation proccess

---

changelog/unreleased/enhancement-disable-share-renaming
packages/web-app-files/src/mixins/actions/rename.ts

Renaming of shares has been disabled temporarily until it works as expected. Also see https://github.com/owncloud/ocis/issues/4866
**Note:** We need to merge this before GA if the issue has not been solved until then.

Disable share renaming

---

changelog/unreleased/bugfix-keep-both-conflict-option
packages/web-app-files/src/helpers/resource/actions/upload.ts

We've fixed an issue with the "Keep both"-conflict option where uploaded folders would get mixed up.
- Fixes https://github.com/owncloud/web/issues/7903

Fix issues with the 'Keep both'-conflict option

---

changelog/unreleased/enhancement-capability-share-denial
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.spec.js
packages/web-pkg/src/composables/capability/useCapability.ts

Since https://github.com/owncloud/ocis/pull/4903 has been merged today, web shows the experimental sharing denial feature (via the "No access" role) by default. oCIS added a capability to announce to clients whether or not the feature is available and should be shown to users. With this PR web now respects that capability.

feat: respect denial capability

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature

This PR skipped the closed issued tagged scenario .Currently, the concept of the space is implemented in ocis which behaves differently. Shares are listed inside the shared space. So this scenario fails while uploading the folder inside the Shares directory. We have decided that we won't be adding/updating tests in Nightwatch. 
For more information visit: https://github.com/owncloud/web/issues/7264. 
https://github.com/owncloud/web/issues/6896
we discussed in the developer discussion not adding comments to the feature until it is a bug demonstration.
If the issue tag describes the reason for skipping the tests scenario and well-known changes like spaces implementation in ocis that brings some obvious differences in core and ocis. Such changes-related comments should be avoided in the …

[tests-only][full-ci]Skip Shares folder related tests on ocis of moveFiles.feature

---

changelog/unreleased/enhancement-route-meta-props
packages/web-app-draw-io/src/index.js
packages/web-app-external/src/index.js
packages/web-app-files/src/router/common.ts
packages/web-app-files/src/router/deprecated.ts
packages/web-app-files/src/router/public.ts
packages/web-app-files/src/router/shares.ts
packages/web-app-files/src/router/spaces.ts
packages/web-app-files/src/router/trash.ts
packages/web-app-pdf-viewer/src/index.js
packages/web-app-preview/src/index.js
packages/web-app-search/src/index.ts
packages/web-app-text-editor/src/index.js
packages/web-app-user-management/src/index.js
packages/web-pkg/src/composables/router/types.ts
packages/web-runtime/src/App.vue
packages/web-runtime/src/layouts/Application.vue
packages/web-runtime/src/layouts/Plain.vue
packages/web-runtime/src/pages/accessDenied.vue
packages/web-runtime/src/pages/login.vue
packages/web-runtime/src/pages/logout.vue
packages/web-runtime/src/pages/missingOrInvalidConfig.vue
packages/web-runtime/src/pages/oidcCallback.vue
packages/web-runtime/src/pages/resolvePrivateLink.vue
packages/web-runtime/src/pages/resolvePublicLink.vue
packages/web-runtime/src/router/helpers.ts
packages/web-runtime/src/router/index.ts

This PR introduces a `meta.authContext` prop on routes so that we give fine grained control to extension developers which kind of auth context they want to require from ownCloud Web.
- Fixes https://github.com/owncloud/web/issues/7234
- Fixes https://github.com/owncloud/web/issues/7863

Introduce meta authContext

---

changelog/unreleased/enhancement-xhr-timeout
config/config.json.sample-oc10
config/config.json.sample-ocis
docs/getting-started.md
packages/web-runtime/src/composables/upload/useUpload.ts
packages/web-runtime/src/services/uppyService.ts

The default timeout for XHR uploads has been increased from 30 to 60 seconds. Also, it can now be configured via the `config.json` file (in ms).
- Fixes https://github.com/owncloud/web/issues/7900

Increase default XHR timeout and make it configurable

---

changelog/unreleased/enhancement-webdav-client
packages/web-app-files/src/helpers/resource/actions/transfer.ts
packages/web-app-files/src/mixins/actions/rename.ts
packages/web-app-files/src/mixins/actions/restore.ts
packages/web-app-files/src/services/folder/loaderSpace.ts
packages/web-app-files/tests/unit/helpers/resource/resourcesTransfer.spec.ts
packages/web-app-files/tests/unit/mixins/actions/restore.spec.js
packages/web-client/src/helpers/space/types.ts
packages/web-client/src/webdav/getFileInfo.ts
packages/web-client/src/webdav/listFiles.ts
packages/web-pkg/src/composables/appDefaults/useAppFolderHandling.ts

Refactor webDav listFiles so the result isn't only an array but rather an object containing the requested node and its children.

[full-ci] Refactor webdav listFiles

---

changelog/unreleased/bugfix-prefer-alias-links-over-private-links
packages/web-app-files/src/components/SideBar/FileInfo.vue

Private link capability has been merged in ocis, see https://github.com/owncloud/ocis/pull/4599
The web ui is not supposed to show the `copy private link` button, the private link concept is only supposed to be used for cross-client links to files. The web ui concept for "file pointers" is the new alias link. Hence this PR disables the private link copy button in the web ui when the alias link capability is enabled.

feat: prefer alias links over private links in UI

---

changelog/unreleased/bugfix-edit-text-files-on-public-pages
packages/web-client/src/webdav/getFileContents.ts

We've fixed a bug where editing text files on public pages was not possible with the oC10 backend.
- Fixes https://github.com/owncloud/web/issues/7932

Fix editing text files on public pages

---

changelog/unreleased/bugfix-origin-event-check
changelog/unreleased/enhancement-origin-event-check
packages/web-app-draw-io/src/App.vue

Origin checks have been added to all Draw.io events due to security reasons.
- Fixes https://github.com/owncloud/web/issues/7933

Add origin checks to all Draw.io events

---

changelog/unreleased/bugfix-include-spaces-in-list-info
packages/web-app-files/src/components/FilesList/ListInfo.vue
packages/web-app-files/src/store/getters.ts
packages/web-app-files/src/views/shares/SharedViaLink.vue
packages/web-app-files/tests/unit/components/FilesList/ListInfo.spec.js

Spaces have been included in the list info below file lists that support displaying spaces.
- Fixes https://github.com/owncloud/web/issues/7924

Include spaces in the list info

---

changelog/unreleased/bugfix-paste-without-write-permissions
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue

The "Paste"-action is now disabled in read-only folders/shares.
- Fixes https://github.com/owncloud/web/issues/7922

Disable 'Paste'-action in read-only folders

---

tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature

Same as https://github.com/owncloud/web/pull/7981 but for `stable-6.0`.

Skip flaky date picker test for oC10

---

changelog/unreleased/bugfix-upload-finalizing-state
changelog/unreleased/bugfix-upload-finishing-state
packages/web-runtime/src/components/UploadInfo.vue
packages/web-runtime/tests/unit/components/UploadInfo.spec.ts

The "upload finished"-state has been introduced to the upload overlay. This state is relevant during the time window when all data has been transferred to the server (= progress bar is at 100%), but the server still needs to write all data to the storage.
The "cancel"- and "pause"-actions are disabled during the "upload finished"-state as the data transfer is technically finished. Previously, when pausing and resuming when being in this state, the upload would be marked as successful instantly, despite the server still writing to the storage.
- Fixes https://github.com/owncloud/web/issues/7956

Introduce 'upload finished'-state in upload overlay

---

tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js

This PR removes check for the month of `December`. May be previously in the month of december the UI would not give us to click the month of december (basically it is disabled). As of now through web UI we can click even if its the month of december.
https://drone.owncloud.com/owncloud/web/29968/10/18
https://github.com/owncloud/web/issues/7227

[tests-only][full-ci]Remove check for expiration date in december month

---

changelog/unreleased/bugfix-text-editor-error-messages
packages/web-app-text-editor/src/App.vue

Error messages in and when leaving the text editor are now being displayed properly.
- Fixes https://github.com/owncloud/web/issues/7960

Fix error message display in text editor

---

changelog/unreleased/enhancement-group-and-user-creation-forms-submit-on-enter
packages/web-app-user-management/src/components/Groups/CreateGroupModal.vue
packages/web-app-user-management/src/components/Users/CreateUserModal.vue
packages/web-app-user-management/tests/unit/components/Groups/CreateGroupModal.spec.js
packages/web-app-user-management/tests/unit/components/Users/CreateUserModal.spec.js

- Fixes https://github.com/owncloud/web/issues/7937
- test case 1:
- test case 2:
- ...

Enter key submits form

---

changelog/unreleased/bugfix-missing-public-password-form
packages/web-app-files/src/views/FilesDrop.vue
packages/web-runtime/src/container/bootstrap.ts

We've fixed a bug where the password form on a public drop page would not show after setting a required password.
- Fixes https://github.com/owncloud/web/issues/7670

Fix missing password form on public drop page

---

changelog/unreleased/bugfix-versions-on-shared-with-me-page
packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
packages/web-runtime/src/plugins/web.js

Downloading and reverting versions on the "Shared with me"-page has been fixed.
- https://github.com/owncloud/web/issues/7980

Fix file versions on 'Shared with me'-page

---

packages/web-app-text-editor/package.json
packages/web-app-text-editor/tests/unit/app.spec.ts
packages/web-client/src/webdav/getFileContents.ts
packages/web-test-helpers/src/mocks/defaultStubs.ts
packages/web-test-helpers/src/mocks/useAppDefaultsMock.ts
pnpm-lock.yaml

This also includes a mock for the `useAppDefaults` composable.

[tests-only] Add unit tests for the text editor

---

changelog/unreleased/bugfix-quota-check-when-replacing-files
packages/web-app-files/src/helpers/resource/actions/upload.ts
packages/web-app-files/tests/unit/helpers/resource/actions/upload.spec.ts

An issue with the quota check when replacing an existing file while having enough quota has been fixed.
- Fixes https://github.com/owncloud/web/issues/7962

Fix quota check when replacing files

---

changelog/unreleased/enhancement-conflict-dialog-ux
packages/web-app-files/src/helpers/resource/actions/transfer.ts
packages/web-app-files/src/helpers/resource/actions/upload.ts
packages/web-app-files/src/helpers/resource/conflictHandling/conflictDialog.ts
packages/web-app-files/tests/unit/helpers/resource/actions/upload.spec.ts
packages/web-app-files/tests/unit/helpers/resource/conflictHandling/conflictDialog.spec.ts
packages/web-app-files/tests/unit/helpers/resource/resourcesTransfer.spec.ts
tests/acceptance/features/webUIFilesCopy/copy.feature
tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature

The UX of the conflict dialog has been improved slightly:
* The name of the conflicting resource is now written in quotes
* The title of the dialog now tells the difference between files and folders
* The "Skip"-dialog now tells the difference between files and folders
- Fixes https://github.com/owncloud/web/issues/7682

[full-ci] Improve UX of the conflict dialog

---

changelog/unreleased/enhancement-preview-app-introduce-zoom-and-rotate
packages/web-app-preview/src/App.vue

- Fixes https://github.com/owncloud/web/issues/7160
- test case 1:
- test case 2:
- ...

Implement zoom and rotate for preview app

---

changelog/unreleased/bugfix-text-editor-multple-save
packages/web-app-text-editor/src/App.vue

Fixes an issue with saving a file multiple times via text editor.
- Fixes https://github.com/owncloud/web/issues/8029

Fix saving a file multiple times with the text editor

---

changelog/unreleased/bugfix-text-editor-appearance
packages/design-system/src/components/OcTextarea/OcTextarea.vue
packages/web-app-text-editor/src/App.vue

The text editor now looks normal again after its appearance had changed due to the inclusion of the ODS in the web repository.

Fix text editor appearance

---

changelog/6.0.0_2022-11-24/enhancement-update-ods
packages/web-runtime/package.json
pnpm-lock.yaml

Bump the design system to the v14.0.1 final release.

chore: bump design system to v14.0.0 final

---

changelog/unreleased/enhancement-preview-app-introduce-full-screen-mode
packages/web-app-preview/src/App.vue

- Fixes https://github.com/owncloud/web/issues/6700
- test case 1:
- test case 2:
- ...

Implement full screen mode

---

.drone.star

Like we have CI runs on merge commits to `master`, we also want to have CI runs on merge commits to `stable-*` (which only applies to `stable-6.0` for now).

ci: run CI on stable branch merge commits

---

packages/design-system/src/components/OcAccordion/OcAccordion.vue
packages/design-system/src/components/OcBreadcrumb/OcBreadcrumb.vue
packages/design-system/src/components/OcBreadcrumb/__snapshots__/OcBreadcrumb.spec.js.snap
packages/design-system/src/components/OcButton/OcButton.vue
packages/design-system/src/components/OcLoader/OcLoader.vue
packages/design-system/src/components/OcProgressPie/OcProgressPie.vue
packages/design-system/src/components/OcSearchBar/OcSearchBar.vue
packages/design-system/src/components/OcTextInput/OcTextInput.vue
packages/design-system/src/components/OcTextarea/OcTextarea.vue
packages/design-system/src/styles/styles.scss
packages/design-system/src/styles/theme/background.scss
packages/design-system/src/styles/theme/oc-text.scss
packages/design-system/src/styles/theme/oc-width.scss
packages/web-app-files/src/components/Spaces/ReadmeContentModal.vue
packages/web-runtime/src/App.vue
rollup.config.mjs
tests/acceptance/pageObjects/personalPage.js
tests/unit/config/jest.config.js

This PR aims to remove the duplicated CSS caused by imports in the design-system.
~~It's not perfect yet, breadcrumbs are broken and input fields (like the search input) look wrong, otherwise it seems to work fairly ok.~~
~~I would be glad if someone with more knowledge of the styles in this project to pick this up and fix the remaining issues.~~
Thanks to @JammingBen for stepping up and taking care of the issues I had left open!🏅 
I have applied the same approach in my vite PR, there everything is even a little more sophisticated ~~(and has the same issues)~~ works the same way, so I'd say finishing this, would be a good preparation for solving this in Vite as well.
Since we imported the ODS into this repo, we have a lot of duplicated styles through imports in the …

[full-ci] Dedupe CSS

---

changelog/unreleased/bugfix-resolving-drives-in-search
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/unit/views/spaces/GenericSpace.spec.ts

We've fixed a bug where folder listing was not reloaded when being in a space/share root and navigating into another space/share root via search.
- Fixes https://github.com/owncloud/web/issues/8034

Fix resolving drives in search results

---

changelog/unreleased/enhancement-warn-unsuported-browsers
package.json
packages/web-container/index.html.ejs
pnpm-lock.yaml
rollup.config.mjs
tests/acceptance/pageObjects/publicLinkPasswordPage.js

We had many users complaining that things were not working and there was no clear reason why... So we decided to warn them.
There's a new compilation env variable to set a link to documentation, in case you have it.
Also, in case the browser still somewhat supports most of the code, users can still force launch it to check it.
I've opened the PR to see your comments, suggestions and interest, but @elizavetaRa is still going to confirm with our users that it displays the error properly (e.g maybe the css will not be well formatted or the regex won't match?)
If there are necessary changes, we'll update the PR.

[full-ci] Warn when using incompatible browser

---

changelog/unreleased/enhancement-retry-failed-uploads
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/composables/upload/useUploadHelpers.ts
packages/web-app-files/src/helpers/resource/actions/upload.ts
packages/web-app-files/tests/unit/composables/upload/useUploadHelpers.spec.ts
packages/web-app-files/tests/unit/helpers/resource/actions/upload.spec.ts
packages/web-runtime/package.json
packages/web-runtime/src/composables/upload/useUpload.ts
packages/web-runtime/src/services/uppyService.ts
pnpm-lock.yaml
tests/unit/config/jest.config.js

When re-uploading a file that failed uploading before (or after closing the browser-tab during the upload), the upload is now being retried instead of being started from scratch again. This fixes some issues with the overlay and preserves the upload progress.
- Fixes https://github.com/owncloud/web/issues/7944

Retry failed uploads on re-upload

---

changelog/unreleased/bugfix-omit-page-query-in-breadcrumb-navigation
packages/web-app-files/src/helpers/breadcrumbs.ts
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/unit/views/spaces/GenericSpace.spec.ts

We've omitted the "page"-query when navigating via breadcrumb. This solves an issue were the file list would be empty after navigating via breadcrumb from a paginated folder.
- Fixes https://github.com/owncloud/web/issues/8060

Omit 'page'-query in breadcrumb navigation

---

changelog/unreleased/enhancement-no-sidebar-when-copying-quicklink
packages/web-app-files/src/mixins/actions/createQuicklink.ts
packages/web-app-files/src/quickActions.js

Green unit tests, let's see how tightly e2e/acceptance tests are woven into this
- Fixes #8008

Fix-8008: Don't open sharing sidebar after creating/copying quicklink

---

changelog/unreleased/bugfix-ui-sorting-quickactions
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/helpers/ui/resourceTable.ts

This PR fixes a bug: if `hoverableQuickActions: true`, the context menus disappear if the mouse exits them or the table row area.
...and improves the sorting in the shared with view.
In the current behaviour it only sorts by the first sharee name, which means we might have rows with multiple sharees (user + groups) appearing in the middle of other rows that only have the user in the sharees. 
This was particularly visible and bad because we even allow multiple groups to appear in this list (as opposed to ocis which seems to be showing only the first group?).
(like in all PRs, I can add the changelog if you think this is ok to be merged)

UI improvements

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIFilesCopy/copyPrivateLinks.feature
tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature

This PR skips the tests related to `private-links`
- part of: https://github.com/owncloud/web/issues/7896
If I understand issue https://github.com/owncloud/web/issues/6844 correctly then there won't be a separate `copy-private-link` button in ocis which is the case for oc10 right now. In the case of ocis 
> As a user I want to get a link to a resource as easily and quickly as possible. I don't want to decide whether I need a 'private' or a 'public' link in the first place. Still, I might want to decide (e.g., for security reasons) for whom the link is usable (link scope): for everybody (public) / only invited people (private).
So Private link tests might be obsolete in this case, thus they are skipped but in `oc10` there is a copy-private-link button
- CI
- locally

[tests-only][full-ci]Skip private link related tests on ocis

---

tests/acceptance/expected-failures-with-oc10-server-openid-login.md

The linked line numbers don't point to a scenario, they rather point to a blank line ad data table, so they can be removed
- Part of https://github.com/owncloud/web/issues/7896
- Locally
- CI

[tests-only][full-ci]Remove tests from expected to failure linked to closed issue

---

changelog/unreleased/bugfix-left-sidebar-navigation-item-text-flickering
changelog/unreleased/bugfix-navigation-text-flickering
packages/web-runtime/src/components/SidebarNav/SidebarNavItem.vue

When you use the left sidebar in light mode the text flickers on transition.
We've fixed a bug that caused the navigation text to flicker in light mode.

Bugfix: Remove navigation text flickering

---

changelog/unreleased/bugfix-re-using-space-images
packages/web-app-files/src/mixins/spaces/actions/setImage.ts
packages/web-app-files/tests/unit/mixins/spaces/setImage.spec.ts
packages/web-test-helpers/src/mocks/store/runtimeModuleMockOptions.ts

We've fixed a bug where re-using a previously used space image via "Set as space image" would cause errors.
- Fixes https://github.com/owncloud/web/issues/8083

Fix re-using space images

---

changelog/unreleased/enhancement-condensed-files-view
packages/design-system/changelog/unreleased/enhancement-condensed-menu-item
packages/design-system/src/assets/icons/menu-line-condensed.svg
packages/web-app-files/src/components/AppBar/ViewOptions.vue
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/composables/index.ts
packages/web-app-files/src/composables/resourcesViewDefaults/useResourcesViewDefaults.ts
packages/web-app-files/src/composables/viewMode/constants.ts
packages/web-app-files/src/composables/viewMode/index.ts
packages/web-app-files/src/composables/viewMode/useViewMode.ts
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/mocks/useResourcesViewDefaultsMock.ts
packages/web-app-files/tests/unit/components/AppBar/ViewOptions.spec.js
packages/web-app-files/tests/unit/components/AppBar/__snapshots__/ViewOptions.spec.js.snap

Adds route-query based toggle between "normal" and "condensed" resource table
- Fixes part of #6380

Add viewMode toggle for condensed resource table

---

package.json
pnpm-lock.yaml
vite.config.ts

`config.json` should not be copied to `dist/` in production builds.
I reenabled `rollup-plugin-gzip` after taking a quick look at `vite-plugin-compress` and `vite-plugin-compression`: one supports only brotli (and no standard gzip) and both don't seem to be as well maintained as `rollup-plugin-gzip`  and I could not see any benefit over our former solution, so I decided to go back to what we used anyway.
- Fixes regressions introduced in #7952 
- test case 1:
- test case 2:
- ...

Fix Vite regressions

---

changelog/unreleased/bugfix-space-member-disappearing
packages/web-app-files/src/store/actions.ts
packages/web-app-files/tests/unit/store/actions.spec.ts

We've fixed a bug where adding links to a space would remove newly added members in the UI.
- Fixes https://github.com/owncloud/web/issues/8081

Fix disappearing space members when adding links

---

tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md
tests/acceptance/features/webUISharingAcceptSharesToRoot/acceptShares.feature

In the changed feature file the user was logged in before API requests are sent to the server to perform some of the operations and page reload was necessary in some cases to fetch the changes made by the API requests. I think it's better if the user is logged in after the API requests are sent. This PR refactors the steps so that the user is logged in after the API request is sent.
- Part of: https://github.com/owncloud/web/issues/7896
- locally
- CI

[tests-only][full-ci]Refactor test steps

---

tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md
tests/acceptance/features/webUILogin/adminBlocksUser.feature
tests/acceptance/pageObjects/loginPage.js

The changed test was failing because it was not compatible with the current behavior of the system, this PR makes it work according to the current behavior and removes closed issue https://github.com/owncloud/web/issues/4795 from the expected to fail.
- Part of: https://github.com/owncloud/web/issues/7896
- Locally
- CI

[tests-only][full-ci]Refactor webUILogin/adminBlocksUser.feature:20 to make it follow the current behaviour

---

changelog/unreleased/enhancement-preview-app-image-preloading
packages/web-app-preview/src/App.vue

- Fixes https://github.com/owncloud/web/issues/2052
- test case 1:
- test case 2:
- ...

Preload images

---

.drone.env

Bump latest `ocis stable-2.0` commit id to `web stable-6.0`
https://github.com/owncloud/QA/issues/791

[tests-only][full-ci]Bump ocis stable-2.0 commit id to web stable-6.0

---

package.json
pnpm-lock.yaml
vite.config.ts

This PR tackles two things:
- we want to support more than the `last 2 versions`, because `last 2 versions` frequently let's e.g. firefox extended support releases (esr) run into the unsupported browser situation. Chrome is probably similar. We expect users to be on a recent-is browser, but `last 2 versions` is too harsh.
- our vite config was actually ignoring the `browserslist` config, as it only uses esbuild targets. Which is a different thing. Added a plugin to transform `browserslist` into `esbuild targets`. If we don't want to do that we need to move away from `browserslist`.
cc @mmattel as this is relevant for the docs.

feat: support browsers that are 1 year old

---

.drone.env

Bump ocis stable-2.0 commit id to latest.
Part of https://github.com/owncloud/QA/issues/791

[full-ci] [tests-only] Bump ocis stable commit id to latest

---

packages/web-app-external/src/App.vue
packages/web-app-external/tests/unit/__snapshots__/app.spec.ts.snap
packages/web-client/src/helpers/resource/functions.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-runtime/package.json
packages/web-runtime/src/helpers/additionalTranslations.ts
pnpm-lock.yaml

Splitting out the propfind 425 status code handling from https://github.com/owncloud/web/pull/8069 so that async upload e2e tests get unblocked.
- Relates to https://github.com/owncloud/ocis/issues/5184
cc @individual-it

[full-ci] Allow 425 status-code in propfinds

---

changelog/unreleased/enhancement-tags-support
packages/web-pkg/src/components/sideBar/CompareSaveDialog.vue
tests/e2e/cucumber/features/smoke/tags.ocis.feature

the tag e2e tests were previously switched off, all necessary ocis pr are merged now and therefore we can enable the tests in web now too.
- Part of https://github.com/owncloud/web/issues/8149

enable tags e2e tests

---

.drone.star

This PR refactors the drone file to minimize the pipeline duration.
The most time-consuming pipeline `oC10RenameFileFolder` had two suites `webUIRenameFolders` and `webUIRenameFiles` each having around 30 scenarios and in total around 60 scenarios. So, the `oC10RenameFileFolder` pipeline is broken out into `oC10RenameFile` and `oC10RenameFolder` pipelines each consisting of around 30 scenarios.
- Fixes https://github.com/owncloud/web/issues/8115
- :robot:

[full-ci] [tests-only] Suites separated into two pipelines, minimize the duration

---

.drone.env

Bump latest `ocis-stable-2.0` commit id to `web-stable-6.0`
https://github.com/owncloud/QA/issues/791

[tests-only][full-ci]Bump latest ocis-stable-2.0 commit-id on web-stable-6.0

---

changelog/unreleased/enhancement-clipboard-copy
packages/web-app-files/package.json
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/PrivateLinkItem.vue
packages/web-app-files/src/components/SideBar/Shares/Links/NameAndCopy.vue
packages/web-app-files/src/helpers/share/link.ts
packages/web-app-files/tests/unit/components/SideBar/PrivateLinkItem.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Links/NameAndCopy.spec.ts
packages/web-runtime/src/defaults/vue.js
pnpm-lock.yaml

Superseds https://github.com/owncloud/web/pull/8136

Feature: #8134 - copy to clipboard 

---

changelog/unreleased/enhancement-share-group-recipient
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
packages/web-app-files/src/fileSideBars.ts
packages/web-app-files/src/mixins/actions/delete.js
packages/web-app-files/src/mixins/actions/emptyTrashBin.js
packages/web-app-files/src/mixins/actions/restore.ts
packages/web-app-files/src/views/spaces/GenericTrash.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/SpaceMembers.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap
packages/web-client/src/graph.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-client/src/helpers/space/functions.ts
packages/web-client/src/helpers/space/types.ts
packages/web-client/tests/unit/helpers/space/functions.spec.ts
packages/web-runtime/src/store/spaces.ts

This pr allows to select groups int the space member sharing dialogue.
So far it was only possible to select users.
be able to share resources to groups instead of user only.

[full-ci] Space group members

---

changelog/unreleased/enhancement-share-group-recipient
tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature
tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature
tests/e2e/cucumber/steps/ui/spaces.ts
tests/e2e/support/store/user.ts

e2e Tests for https://github.com/owncloud/web/issues/8160
https://github.com/owncloud/web/issues/8160

[full-ci] Add e2e tests for spaces group members

---

changelog/unreleased/bugfix-search-bar-input-appearance
packages/design-system/src/components/OcSearchBar/OcSearchBar.vue

The broken appearance of the search bar input field has been fixed.
**Note:** The priority of CSS rules seem to differ between `pnpm build` and `pnpm vite`. With `pnpm vite`, the CSS rules in ODS have a higher prio, which is correct. Somehow this changes with `pnpm build`. That might be worth debugging in the future, but for now, we are fine with simply adding `!important` (like we often do in the ODS).
Fixes https://github.com/owncloud/web/issues/8158

Fix search bar input appearance

---

packages/web-app-files/package.json
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.ts.snap
packages/web-app-search/package.json
packages/web-runtime/package.json
packages/web-runtime/src/defaults/vue.js
packages/web-test-helpers/package.json
packages/web-test-helpers/src/defaultPlugins.ts
pnpm-lock.yaml

We've removed the `vue-async-computed` extension because it was broken in the right sidebar and we want to use vue-concurrency for such things anyway.

Vue 3: Remove `vue-async-computed` extension

---

tests/e2e/support/api/davSpaces/spaces.ts

We have a step to create folder in personal space(`oCIS`) or All files(`oc10`). But it fails in steps with data tables like 
```feature
✖ And "Alice" creates the following folder in personal space using API # tests/e2e/cucumber/steps/api.ts:75
| name                   |
| folder_to_shared       |
| folder_to_shared/hello |
Error: HTTP Request Failed: Failed while creating folder, Status: 405
```
This is a fix PR for this. Now the function supports data tables to create folder like.
```feature
And "Alice" creates the following folder in personal space using API
| name                         |
| folder_to_shared/hello       |
| folder_to_shared             |
| folder_to_shared/hello/lello |
| folder_to_shared/mello       |
```

[tests-only][full-ci]Refactor function for creating folder in `personal space`

---

changelog/unreleased/bugfix-shift-click-selection
changelog/unreleased/change-update-vue
packages/web-app-files/src/components/FilesList/KeyboardActions.vue

"Shift + click"-selection in the files table has been fixed.
- Fixes https://github.com/owncloud/web/issues/8206

Vue 3: Fix 'Shift + click'-selection in files table

---

docker/Dockerfile

This should fix ocis.ocis-web.latest.owncloud.works
- test case 1:
- test case 2:
- ...

Use newer digest for the nginx base image

---

packages/design-system/src/assets/icons/space.svg

At some point we replaced the `space` icon from [remixicon.com](http://remixicon.com) with something custom. We don't seem to use that anymore (at least I couldn't find any occurrence), but use `layout-grid` instead. So this PR re-introduces the `space` remixicon (which represents a `blank/space` for a text editor user interface).

restore original "space" icon from remixicon

---

changelog/unreleased/change-update-vue
packages/web-runtime/package.json
packages/web-runtime/src/components/Topbar/TopBar.vue
packages/web-runtime/src/container/api.ts
packages/web-runtime/src/container/application/classic.ts
packages/web-runtime/src/container/application/next.ts
packages/web-runtime/src/container/types.ts
packages/web-runtime/src/defaults/vue.js
packages/web-runtime/src/index.ts
packages/web-test-helpers/src/defaultPlugins.ts
pnpm-lock.yaml
web.d.ts

Use new Vue 3 `createApp` api and update `portal-vue`.
- test case 1:
- test case 2:
- ...

[full-ci] Vue 3: Use createApp and update portal-vue

---

changelog/unreleased/enhancement-spaces-list-in-admin-settings
packages/web-app-admin-settings/src/components/AppTemplate.vue
packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersPanel.vue
packages/web-app-admin-settings/src/views/Spaces.vue

See https://github.com/owncloud/web/issues/8219
- https://github.com/owncloud/web/issues/8219

Admin panel members list

---

changelog/unreleased/enhancement-spaces-list-in-admin-settings
packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetails.vue
packages/web-pkg/src/mixins/spaces/disable.ts
packages/web-pkg/src/mixins/spaces/restore.ts
packages/web-pkg/src/services/permissionManager.ts
packages/web-pkg/tests/unit/mixins/spaces/disable.spec.ts
packages/web-pkg/tests/unit/mixins/spaces/restore.spec.ts

Contains some smaller follow-ups for https://github.com/owncloud/web/pull/8190.
- https://github.com/owncloud/web/issues/8223
- Fixes https://github.com/owncloud/web/issues/8125

Space management actions followup

---

changelog/unreleased/enhancement-spaces-list-in-admin-settings
packages/web-app-admin-settings/src/views/Spaces.vue
packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetails.vue
packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/SpaceDetails.spec.ts
packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/__snapshots__/SpaceDetails.spec.ts.snap

- https://github.com/owncloud/web/issues/8222

Show space default image image and hide member count in spaces management

---

tests/e2e/cucumber/features/smoke/share.oc10.feature
tests/e2e/cucumber/features/smoke/share.ocis.feature
tests/e2e/cucumber/steps/ui/shares.ts
tests/e2e/support/objects/app-files/share/actions.ts
tests/e2e/support/objects/app-files/share/index.ts
tests/e2e/support/objects/app-files/share/utils.ts

This PR use `When "Alice" removes following share` and create new step: `Then "Brian" should not be able to see share "resource"` in share.ocis.feature
Part of
- https://github.com/owncloud/web/issues/8101
- Locally

[tests-only][full-ci]Add remove sharee step in share.ocis.feature

---

changelog/unreleased/enhancement-spaces-list-in-admin-settings
packages/web-app-files/src/fileSideBars.ts

See https://github.com/owncloud/web/issues/8222
- Works towards https://github.com/owncloud/web/issues/8222

[full-ci] Use SpaceNoSelection for spaces

---

changelog/unreleased/change-update-vue
packages/web-runtime/package.json
packages/web-runtime/src/App.vue
packages/web-runtime/src/container/bootstrap.ts
pnpm-lock.yaml

Remove `vuex-router-sync` because 1. it does not support `vue-router` v4 (https://github.com/vuejs/vue-hackernews-2.0/commit/758961e73ac4089890079d4ce14996741cf9344b#r50475667) and 2. we don't use it anyways (?)

[full-ci] Vue 3: Remove `vuex-router-sync`

---

changelog/unreleased/change-update-vue
packages/design-system/src/components/OcAvatar/OcAvatar.vue
packages/design-system/src/components/OcList/OcList.vue
packages/design-system/src/components/OcTable/OcTable.vue
packages/eslint-config/index.js
packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap

This is needed in preparation for Vue 3 because `Vue.extend()` is not supported anymore.
- https://github.com/owncloud/web/issues/7948

Vue 3: Use Teleport for the drag ghost item

---

changelog/unreleased/enhancement-spaces-list-in-admin-settings
packages/web-app-admin-settings/src/views/Spaces.vue
packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetailsMultiple.vue
packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/SpaceDetailsMultiple.spec.ts
packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/__snapshots__/SpaceDetailsMultiple.spec.ts.snap

See https://github.com/owncloud/web/issues/8222
- Works towards https://github.com/owncloud/web/issues/8222
- Fixes https://github.com/owncloud/web/issues/8246

[full-ci] Extend multiple space selection details

---

changelog/unreleased/enhancement-spaces-list-in-admin-settings
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
packages/web-app-admin-settings/src/views/Spaces.vue

See https://github.com/owncloud/web/issues/8222
- Works towards https://github.com/owncloud/web/issues/8222

[full-ci] Squash spacelist on sidebar open

---

changelog/unreleased/enhancement-spaces-list-in-admin-settings
tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
tests/e2e/support/objects/app-admin-settings/spaces/index.ts

Fixes https://github.com/owncloud/web/issues/8223

Add e2e tests for the spaces management actions

---

changelog/unreleased/bugfix-app-menu-active-display
packages/web-runtime/src/components/Topbar/ApplicationsMenu.vue

Fix application menu active display on hover

---

packages/web-runtime/src/router/patchCleanPath.ts

Fix encoded slashes in file paths in urls.
This generates correctly encoded links but does not fix up encoded links pasted to the address bar, e.g. there is no redirect from `/files/spaces/personal%2Fadmin` to `/files/spaces/personal/admin`.
I've tried to implement that, but vue-router does not navigate, I assume because it thinks they are the same route anyway. It's fixed on the next navigation tho.
This is a follow up to https://github.com/owncloud/web/pull/8215 where we introduced a regression
- test case 1:
- test case 2:
- ...

[full-ci] Vue 3: Fix encoded slashes in urls

---

changelog/unreleased/bugfix-loading-additional-user-data
packages/web-app-admin-settings/src/components/AppTemplate.vue
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
packages/web-app-admin-settings/src/components/Users/UsersList.vue
packages/web-app-admin-settings/src/views/Groups.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/DetailsPanel.spec.ts
packages/web-app-admin-settings/tests/unit/views/Users.spec.ts

This PR improves the loading of additional user data which is needed in the sidebar.
Before, this was handled by a custom `showPanel` event, that first loaded the additional data, then opened the sidebar. Problems here:
1. This event was only fired on action click, not on select (see https://github.com/owncloud/web/issues/8275).
2. We might have deeper component structures in the future. When some deep component (or a composable) wants to emit this event, we'd need to propagate the event all the way to the parent view component.
3. There is no loading-indicator for the user. This might be no issue here, but in general this is bad.
The new approach uses the `eventBus` which is coupled with the `useSidebar` composable. Opening/closing the sidebar and setting the active panels is all being …

Fix sidebar data loading for users

---

pnpm-lock.yaml
tests/e2e/cucumber/features/smoke/reshare.feature
tests/e2e/cucumber/steps/api.ts
tests/e2e/package.json
tests/e2e/support/api/share/index.ts
tests/e2e/support/api/share/share.ts

This PR backports the PR https://github.com/owncloud/web/pull/8227 from `stable-6.0`
https://github.com/owncloud/web/pull/8274

[tests-only][full-ci]Backport `add apisteps accepting shared resources` to master branch

---

changelog/unreleased/enhancement-support-multiple-clients-in-theme-json
docs/theming/_index.md
packages/web-runtime/src/helpers/theme.ts
packages/web-runtime/tests/unit/helpers/theme.spec.js
packages/web-runtime/themes/owncloud/theme.json

The `theme.json` file now supports multiple clients which are defined via the top-level property. Therefore both web themes have been moved down one level into the new property "web". The change is backwards compatible though, meaning it still works when the web themes are defined top-level in `theme.json`.
- See https://github.com/owncloud/enterprise/issues/5502

Add support for multiple clients in `theme.json`

---

tests/e2e/cucumber/features/smoke/reshare.feature
tests/e2e/cucumber/features/smoke/search.feature
tests/e2e/cucumber/features/smoke/share.oc10.feature
tests/e2e/cucumber/features/smoke/share.ocis.feature
tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature
tests/e2e/cucumber/features/smoke/tags.ocis.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/cucumber/steps/ui/shares.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts
tests/e2e/support/objects/app-files/share/collaborator.ts

This Pr refactor codes related to custom permission for resource to work for file.
- https://github.com/owncloud/web/issues/8101
- Locally

[tests-only][full-ci]Add custom permission e2e tests

---

.drone.env

Bumps latest `ocis-master` commit-id to `web-master`
https://github.com/owncloud/QA/issues/795

[tests-only][full-ci]Bump latest `master-ocis` commit to `web-master`

---

.drone.env

Bumps latest `ocis-stable-2.0` commit-id to `web-stable-6.0`
https://github.com/owncloud/QA/issues/795

[tests-only][full-ci]Bump `ocis-stable-2.0` commit to `web-stable-6.0`

---

changelog/unreleased/enhancement-spaces-list-in-admin-settings
packages/web-app-admin-settings/src/components/Spaces/SideBar/ActionsPanel.vue
packages/web-app-admin-settings/src/views/Spaces.vue
packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/ActionsPanel.spec.ts

See https://github.com/owncloud/web/issues/8222
- Works towards https://github.com/owncloud/web/issues/8222

[full-ci] Admin: Spaces actions in sidebar

---

changelog/unreleased/enhancement-move-language-select-to-account-page
config/config.json.sample-ocis
config/vite_oc10/config.json
config/vite_ocis/config.json
dev/docker/oc10.web.config.json
dev/docker/ocis.web.config.json
docs/getting-started.md
packages/web-integration-oc10/lib/Controller/ConfigController.php
packages/web-runtime/src/pages/account.vue
packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
packages/web-runtime/tests/unit/pages/account.spec.ts

The language selection has been moved from the settings app to the personal account page. The settings app has been removed from the default configs because we don't need it currently.
Fixes https://github.com/owncloud/web/issues/8290
Needs a follow-up PR in oCIS to adjust the configs there.

[full-ci] Move language selection to the account page and kill settings app

---

tests/e2e/cucumber/features/smoke/reshare.feature
tests/e2e/cucumber/features/smoke/search.feature
tests/e2e/cucumber/features/smoke/share.oc10.feature
tests/e2e/cucumber/features/smoke/share.ocis.feature
tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/cucumber/steps/ui/shares.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts
tests/e2e/support/objects/app-files/share/collaborator.ts

Added e2e tests to share files and folders with custom permissions
Ported from https://github.com/owncloud/web/pull/8193
https://github.com/owncloud/web/pull/8193

[tests-only][full-ci] Add share with custom permission e2e tests (stable-6)

---

tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature

The test `webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:111` is failing due to a known issue reported here https://github.com/owncloud/web/issues/7513, skipping the test for now.
Need to revert when the issue gets fixed.
Related to https://github.com/owncloud/web/issues/8296

[full-ci] [tests-only] Test skipped for ocis and oc10

---

tests/e2e/cucumber/features/smoke/share.ocis.feature

This PR removes the duplicated steps to accept or decline share in `share.ocis.feature` in master branch. This might have arrived during rebasing while backporting from `stable-6.0` to `master`

[tests-only][full-ci]Remove duplicated steps in feature file for `share.ocis.feature`

---

changelog/unreleased/bugfix-re-loading-space-members
changelog/unreleased/enhancement-share-group-members
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-pkg/src/components/sideBar/Spaces/SpaceInfo.vue
packages/web-pkg/tests/unit/components/sidebar/Spaces/SpaceInfo.spec.ts
packages/web-runtime/src/store/spaces.ts

* Fix re-loading the space members panel
* Fix disappearing groups after removing one group form a space
- Fixes https://github.com/owncloud/web/issues/8298
- Fixes https://github.com/owncloud/web/issues/8299

Fix space member panel issues

---

changelog/unreleased/enhancement-show-selectable-groups-only
packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
packages/web-app-admin-settings/src/components/Users/SideBar/GroupSelect.vue
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/EditPanel.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/GroupSelect.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap

When managing user group assignments, we now show selectable groups only, meaning groups that have been selected already will not show up as available options.
- Fixes https://github.com/owncloud/web/issues/8305

Show selectable groups only

---

changelog/unreleased/change-update-vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue

Toggling indirect links in the sidebar (as well as the broken sidebar state with public links with `pnpm vite`) has been fixed.
- Fixes https://github.com/owncloud/web/issues/8283
- Fixes https://github.com/owncloud/web/issues/8307

Fix indirect link toggling

---

changelog/unreleased/bugfix-edit-user-empty-drive
packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue

Made edit panel more resilient. As of today, the backend sends an empty drive object for users who never logged in.

fix: edit panel for users who never logged in

---

tests/e2e/cucumber/features/journeys/kindergarten.oc10.feature
tests/e2e/cucumber/features/journeys/kindergarten.ocis.feature
tests/e2e/cucumber/features/smoke/link.feature
tests/e2e/cucumber/features/smoke/share.oc10.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts

This PR refactors the download function to be able to download folders as well since previously the download function only downloads the files. This is done in order to extend the download folder feature to `kindergarten.feature`for `oCIS` and `oc10`.
https://github.com/owncloud/web/issues/8101

[tests-only][full-ci]Extended download folders for kinder garden feature

---

changelog/unreleased/bugfix-space-members-panel-deleted-members
packages/web-runtime/src/store/spaces.ts

Loading space members died entirely when one of the members was deleted before. This has been fixed by ignoring the errors on the `getUser` request for deleted users or groups (still appears in the browser console).
- Fixes https://github.com/owncloud/web/issues/8148

fix: space member loading if a user or group was deleted

---

packages/web-app-files/src/helpers/resources.ts

This PR has no user facing value, hence the absence of a changelog item.
Grouping shares bei `file_source` instead of `file_target` would've had a visible effect back when we still had public links and user/group-shares in the same "Shared with others" view. That would've grouped the public links and user/group-shares on the same resource together. But as we don't show them together anymore there is no visible effect.
Technically it's still the correct thing to do, so let's fix it and close one issue. 😁 
- Fixes https://github.com/owncloud/web/issues/6518

fix: group shares by file_source instead of file_target

---

changelog/unreleased/enhancement-admin-settings-user-details-improvement
packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue

- Fixes https://jira.owncloud.com/browse/OCIS-3291
- 
- test case 1:
- test case 2:
- ...

Improve user details panel

---

changelog/unreleased/bugfix-cancel-custom-permissions
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/RoleDropdown.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/RoleDropdown.spec.ts.snap

We've fixed a bug where cancelling the custom permissions on a share would remove all permissions.
- Fixes https://github.com/owncloud/web/issues/8335

Fix cancelling custom permissions

---

changelog/unreleased/enhancement-space-member-expiration
changelog/unreleased/enhancement-update-sdk
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-client/src/helpers/resource/types.ts
packages/web-client/src/helpers/share/space.ts
packages/web-client/src/helpers/space/functions.ts
packages/web-client/tests/unit/helpers/share/space.spec.ts
packages/web-client/tests/unit/helpers/space/functions.spec.ts
packages/web-runtime/package.json
packages/web-runtime/src/store/spaces.ts
pnpm-lock.yaml
tests/e2e/cucumber/features/smoke/spaces/memberExpiry.ocis.feature
tests/e2e/cucumber/steps/ui/spaces.ts
tests/e2e/support/objects/app-files/share/collaborator.ts
tests/e2e/support/objects/app-files/spaces/actions.ts
tests/e2e/support/objects/app-files/spaces/index.ts

We've added expiration for space members and made Web compatible with the new permission structure that was introduced by https://github.com/owncloud/ocis/pull/5453.
To-Dos:

Add expiration for space members and apply new permission structure

---

.drone.env
changelog/unreleased/enhancement-share-group-recipient
changelog/unreleased/enhancement-update-sdk
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/AutocompleteItem.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/RecipientContainer.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/helpers/resources.ts
packages/web-app-files/src/services/folder/loaderSharedWithOthers.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/__snapshots__/RecipientContainer.spec.ts.snap
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/SpaceMembers.spec.ts
packages/web-app-files/tests/unit/store/mutations.spec.ts
packages/web-client/src/helpers/share/space.ts
packages/web-client/src/helpers/share/type.ts
packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/SpaceDetails.spec.ts
packages/web-runtime/package.json
packages/web-runtime/src/store/spaces.ts
pnpm-lock.yaml

The solution is not super straight-forwarded currently, unfortunately... We need to check for the presence of `collaborator.name` as space group shares don't have that property. We can't check for the share type because all user- and group-shares for spaces have the exact same share type.
Edit: we've introduced a `shareType 8` for groups as space members. With that it's pretty much straightforward now.
- Fixes https://github.com/owncloud/web/issues/8243

Fix group avatar display in space members list

---

deployments/examples/ocis_web/docker-compose.yml

fixes a wrong volume declaration which was introduced in #8346
- Fixes bug introduced in #8346
- 
- -

fix the Web latest deployment example

---

tests/e2e/cucumber/features/journeys/kindergarten.oc10.feature
tests/e2e/cucumber/features/journeys/kindergarten.ocis.feature
tests/e2e/cucumber/features/smoke/share.oc10.feature
tests/e2e/cucumber/features/smoke/share.ocis.feature
tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature
tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature
tests/e2e/cucumber/steps/ui/public.ts
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/page/public.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

- This PR expands the kinder garden feature for (`oCIS` and `oc10`) to delete serveral or individual resources.
- This PR also refactors the steps to delete resource to be able to delete the resource(objects) both by batch action and sidebar panel since it was previously only deleted with sidebar panel
https://github.com/owncloud/web/issues/8101

[tests-only][full-ci]Expand kinder garden feature to delete serveral `objects/resources` 

---

packages/web-app-files/src/services/folder/loaderSpace.ts
packages/web-app-files/src/store/actions.ts
packages/web-app-files/src/store/getters.ts
packages/web-app-files/src/store/mutations.ts
packages/web-app-files/src/store/state.ts

This PR introduces the `ancestorMetaData` state in the store. It holds information about all ancestor folders: `fileId`, `sharesTypes`, `space`, `parentFolderId`.

Introduce ancestor meta data to store

---

tests/acceptance/pageObjects/textEditorPage.js

Previously we didn't wait until save-action finished which caused the intermittent failure.
This PR waits for save-button to be disables after it saves the changes
- Fixes https://github.com/owncloud/web/issues/8329
- Locally

[tests-only][full-ci] Confirm context save completion 

---

changelog/unreleased/enhancement-resources-tiles-view
packages/design-system/src/tokens/ods/size.yaml
packages/web-app-files/src/components/AppBar/ViewOptions.vue
packages/web-app-files/src/components/FilesList/ResourceTiles.vue
packages/web-app-files/src/composables/resourcesViewDefaults/useResourcesViewDefaults.ts
packages/web-app-files/src/composables/viewMode/constants.ts
packages/web-app-files/src/composables/viewMode/useViewMode.ts
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/mocks/useResourcesViewDefaultsMock.ts
packages/web-app-files/tests/unit/components/AppBar/ViewOptions.spec.ts
packages/web-app-files/tests/unit/components/AppBar/__snapshots__/ViewOptions.spec.ts.snap

Didn't invest the time to create a `OcSlider` component but kept it inline, also doesn't fetch bigger tiles thumbnails since the current resolution seems quite reasonable even on bigger tiles.
- Fixes #8367
- Addresses parts of #8368

Fix ResourceTiles on mobile and add basic resize slider for tiles

---

.drone.env

This PR bumps the commit id of ocis stable branch for tests
part of: https://github.com/owncloud/QA/issues/797

[tests-only][full-ci]Bump commit id for tests in stable-6.0

---

changelog/unreleased/enhancement-resources-tiles-view
packages/design-system/src/components/OcCheckbox/OcCheckbox.vue
packages/design-system/src/components/OcTile/OcTile.spec.ts
packages/design-system/src/components/OcTile/OcTile.vue
packages/design-system/src/components/OcTile/__snapshots__/OcTile.spec.ts.snap
packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
packages/web-app-files/src/components/AppBar/ViewOptions.vue
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/FilesList/ResourceTiles.vue
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/components/FilesList/ResourceTiles.spec.ts
packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
packages/web-pkg/src/components/ContextActions/ContextMenuQuickAction.vue
packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ContextMenuQuickAction.spec.ts.snap
sonar-project.properties

- Fixes https://github.com/owncloud/web/issues/8365

Add selection model to tiles view

---

changelog/unreleased/enhancement-resources-tiles-view
packages/web-app-files/src/components/AppBar/CreateSpace.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/fileSideBars.ts
packages/web-app-files/src/mixins/actions/copy.ts
packages/web-app-files/src/mixins/actions/downloadArchive.ts
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap

* Fix broken sidebar state when selecting multiple spaces
* Add "Clear selection" action when multiple spaces are selected
- Follow-Up for https://github.com/owncloud/web/pull/8392

Fix multi-select in spaces view

---

packages/web-runtime/src/index.ts
packages/web-runtime/src/services/auth/userManager.ts

Attempt to improve the performance number 2. As opposed to the previous PR (done a couple of months ago), this one touches less things (doesn't improve as much, but also doesn't make assumptions about execution dependencies that might change in the future).
But again, the objective here is to parallelise calls to the server... Currently, web does a lot of sequential calls. When these take long to reply (the case in CERNBox, maybe not as visible in a clean and small ocis deployment), these add up.
I've made the OCS calls for the sharing indicators in parallel with the PROPFIND request. This might be good enough for us while we wait for the async/vue3 table updates (even in that case, I still believe it makes sense to do all of them in parallel...).
The change here is that I do not wait for …

[full-ci]  Performance improvements

---

tests/acceptance/pageObjects/personalPage.js

This PR changes the selector to strictly check for successful upload message dialogue only.
Before used selector was used to check the general upload message dialogue box whether its success or fail.
- Fixes https://github.com/owncloud/web/issues/8391
- Locally

[tests-only][full-ci] Fix upload success check 

---

changelog/unreleased/enhancement-fix-action-list-layout
packages/web-app-admin-settings/src/components/Spaces/SideBar/ActionsPanel.vue
packages/web-app-files/src/components/SideBar/Actions/FileActions.vue
packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue
packages/web-app-files/src/components/SideBar/FileInfo.vue
packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceContextActions.spec.ts.snap
packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
packages/web-pkg/src/components/ContextActions/ActionMenuItem.vue
packages/web-pkg/src/components/sideBar/Spaces/SpaceInfo.vue
packages/web-pkg/tests/unit/components/sidebar/Spaces/__snapshots__/SpaceInfo.spec.ts.snap

Make list of available sidebar actions (File info + Spaces) look better:
- add slight border below file/space name to sepaate it from actions
- add standardized spacing between elements to make it look like other actions lists (e.g. context menu in file list)
- add hover effect
- expand button to make full width clickable 
Before:
After:
- Fixes https://github.com/owncloud/web/issues/8397

cleanup sidebar actions (fileinfo + spaces)

---

changelog/unreleased/enhancement-optional-roles
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/store/actions.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Links/DetailsAndEdit.spec.ts
packages/web-client/src/helpers/share/role.ts
packages/web-client/tests/unit/helpers/share/role.spec.ts
packages/web-pkg/src/composables/capability/useCapability.ts

Follow up to what we discussed in our last meeting (some weeks ago).
This is not final yet (the tests are failing, and I need to check why, as the default behaviour should stay the same...) and I would appreciate feedback.
The Contributor role is now optional, since we do not support it in CERBox.
It also makes the re-sharing permission optional, as allowing re-sharing doesn't mean we want to make it the default.
We discussed this and you were ok with the change, but now I see that oCIS is not honouring the change... Example: I have re-sharing default to false, in the share dialog I set the Viewer role, the request sends the proper permission code (1), together with the role name, but oCIS replies with the sharing permission (1 + 16). Is it using the role name to define the permissions? …

Up roles defaults

---

changelog/unreleased/enhancement-admin-settings-users-role-graph-api-usage
packages/web-app-admin-settings/src/views/Users.vue
packages/web-client/src/graph.ts

- Fixes https://github.com/owncloud/ocis/issues/5474
- test case 1:
- test case 2:
- ...

Fix groups not updated in ui after editing user

---

changelog/unreleased/enhancement-user-group-filter
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
packages/web-app-admin-settings/src/components/Users/UsersList.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
packages/web-app-admin-settings/tests/unit/views/Users.spec.ts
packages/web-client/src/graph.ts
packages/web-pkg/src/components/ItemFilter.vue
packages/web-pkg/tests/unit/components/__snapshots__/ItemFilter.spec.ts.snap

Add the possibility to filter users by their group assignments.
Needs https://github.com/owncloud/ocis/pull/5533 for the server.
- Fixes https://github.com/owncloud/web/issues/8377

Add groups filter to the users list

---

packages/extension-sdk/index.mjs
packages/extension-sdk/package.json
pnpm-lock.yaml

Add a shared vite config file that can be used to develop external extensions.
- #7930 
We ported
- https://github.com/dschmidt/web-app-gpx-viewer 
- https://github.com/cernbox/web-extensions -> top-bar extension

extension-sdk: Add a shared vite config for extensions

---

changelog/unreleased/enhancement-inject-customizations
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/container/index.ts
packages/web-runtime/src/index.ts
packages/web-runtime/tests/unit/container/bootstrap.spec.ts

Add option to include own header scripts and styles.
This function is currently still experimental and there is a possibility that the api will change.
For the reasons mentioned, the functionality is not yet documented in the official documentation, but can be used as follows:
* to inject custom css add the following property to your `config.json`, `"styles": [{ "href": "css/custom.css", }]`.
* to inject custom scripts add the following property to your `config.json`, `"scripts": [{ "src": "js/custom.js", "async": true, }]`.
The feature was requested in https://github.com/owncloud/web/issues/4735 and backported from the experimental branch.

Option to inject custom css and js files

---

packages/web-app-admin-settings/src/index.ts
packages/web-app-admin-settings/tests/unit/index.spec.ts
packages/web-runtime/src/container/application/classic.ts
packages/web-runtime/src/container/application/index.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/container/types.ts
packages/web-runtime/src/index.ts
packages/web-runtime/tests/unit/container/bootstrap.spec.ts

This PR passes `globalProperties` to `routes` and `navItems`, which gives apps the possibility to use those when defining their routes and navigation items.
This is a pre-requisite for https://github.com/owncloud/web/pull/8431

[full-ci] Pass `globalProperties` to routes and navItems of apps

---

changelog/unreleased/enhancement-key-up-down-performance
packages/web-app-admin-settings/src/components/General/AppearanceSection.vue
packages/web-app-files/src/components/FilesList/KeyboardActions.vue
packages/web-app-files/tests/unit/components/FilesList/KeyboardActions.spec.ts
packages/web-pkg/src/components/ContextActions/ActionMenuItem.vue

Keyboard interaction with file listings needs a major rework (should be a composable instead of a component + is not compatible with the tiles view), so I didn't dig deeper. This PR is just a slight improvement of the render performance of the current implementation of up/down key uses, since it was a low hanging fruit.

perf: slightly faster key up/down

---

packages/web-app-admin-settings/package.json
packages/web-app-admin-settings/src/components/Groups/CreateGroupModal.vue
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
packages/web-app-admin-settings/src/components/Groups/SideBar/DetailsPanel.vue
packages/web-app-admin-settings/src/components/Groups/SideBar/EditPanel.vue
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
packages/web-app-admin-settings/src/components/Users/CreateUserModal.vue
packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
packages/web-app-admin-settings/src/views/Groups.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/components/Groups/GroupsList.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/CreateUserModal.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/EditPanel.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap
pnpm-lock.yaml

- Part of https://github.com/owncloud/ocis/issues/4988
- test case 1:
- test case 2:
- ...

Enable change user name 

---

changelog/unreleased/change-configurable-extension-autosave
packages/web-app-text-editor/src/App.vue

Prevents undefined `autosaveInterval` (which leads to _a lot_ of autosaves) when admin only sets `"autosaveEnabled": true` and overwrites the store defaults

Prevent empty autosaveInterval in config editor-options

---

changelog/unreleased/bugfix-paste-action-conflict-dialog-broken
packages/web-app-files/src/components/FilesList/KeyboardActions.vue
pnpm-lock.yaml

See https://github.com/owncloud/web/issues/8462
- Fixes https://github.com/owncloud/web/issues/8462

[full-ci] Bugfix: Copy/Cut/Paste, paste shortcut doesn't trigger sometimes

---

changelog/unreleased/change-remove-permission-manager
packages/web-runtime/src/services/auth/userManager.ts

Follow-up for https://github.com/owncloud/web/pull/8431.

Fix permissions loading for oC10

---

.drone.env
changelog/unreleased/enhancement-user-settings-login-field
packages/design-system/changelog/unreleased/enhancement-align-disabled-state-on-oc-select
packages/design-system/src/components/OcSelect/OcSelect.vue
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
packages/web-app-admin-settings/src/components/Users/UsersList.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap
pnpm-lock.yaml
tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/cucumber/steps/ui/session.ts
tests/e2e/support/api/graph/userManagement.ts
tests/e2e/support/objects/app-admin-settings/index.ts
tests/e2e/support/objects/app-admin-settings/page/index.ts
tests/e2e/support/objects/app-admin-settings/page/users.ts
tests/e2e/support/objects/app-admin-settings/users/actions.ts
tests/e2e/support/objects/app-admin-settings/users/index.ts
tests/e2e/support/objects/runtime/session.ts
tests/e2e/support/types.ts

- Fixed https://github.com/owncloud/web/issues/8484
- Fixes https://github.com/owncloud/web/issues/8467
- test case 1:
- test case 2:
- ...

User management login allowed

---

changelog/unreleased/enhancement-user-group-filter
changelog/unreleased/enhancement-user-role-filter
packages/web-app-admin-settings/src/views/Users.vue

... and reset the loaded additional data because it needs to be re-fetched on selection.
- Fixes https://github.com/owncloud/web/issues/8494

Reset user selection after applying a filter

---

.drone.env

This PR bumps `ocis` commit id for tests
Part of: https://github.com/owncloud/QA/issues/799

[tests-only][full-ci]Bump commit id for tests in stable

---

changelog/unreleased/bugfix-remove-fuzzy-search-results
packages/design-system/src/components/OcSelect/OcSelect.vue
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersPanel.vue
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
packages/web-app-admin-settings/src/components/Users/UsersList.vue
packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
packages/web-app-files/src/helpers/resource/filter.ts
packages/web-pkg/src/components/ItemFilter.vue

See https://github.com/owncloud/web/issues/8493
- Fixes https://github.com/owncloud/web/issues/8493

[full-ci] Bugfix: Remove fuzzy search results

---

changelog/unreleased/bugfix-oc10-pdf-display
packages/web-integration-oc10/lib/Controller/FilesController.php

Using Owncloud Web 6.0.0, it is not possible to display a PDF using PDF Viewer cause the CSP is too restrictive.
It returns : 
```
Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://xyz.com/bb6b39b8-1d71-4960-bc4c-16ab79bc1044 (“default-src”).
```
- Fixes [PDFViewer / Content Security Policy blocks 'blob:'](https://github.com/owncloud/core/issues/40639)
- Fixes https://github.com/owncloud/web/issues/7931
- Fixes https://github.com/owncloud/web/issues/8497
PDF will be working on Firefox out of the box.
Old owncloud server running, updated to 10.11; added new configuration to support OwnCloud Web new front-end.
Before : 
CSP configuration : 
View :
After, with updated CSP and visible PDF :

PDFViewer / CSP - frame-src object-src blob:

---

changelog/unreleased/enhancement-resources-tiles-view
packages/web-app-files/src/components/FilesList/ResourceTiles.vue
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/unit/components/FilesList/ResourceTiles.spec.ts
packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap

- Fixes https://github.com/owncloud/web/issues/8369

Add drag and drop functionality to resource tiles

---

changelog/unreleased/enhancement-inject-customizations
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/tests/unit/container/bootstrap.spec.ts

oCIS parses the config.json file and ignores keys that are not known in the backend struct. Hence moving styles and scripts to "options" because that already is accepted as a (potentially nested) map in the config struct.
The other option would've been to define the `scripts` and `styles` entries in the backend struct. Not much of a difference effort wise, but I don't want to impose the bad design of the config.json on the backend code. 😅 
This is a followup of https://github.com/owncloud/web/pull/8432

fix: move custom styles and scripts to config options

---

changelog/unreleased/change-re-style-file-versions
changelog/unreleased/enhancement-add-negative-margin-design-system
changelog/unreleased/enhancement-re-style-file-versions
packages/design-system/changelog/unreleased/enhancement-add-font-weight-classes
packages/design-system/changelog/unreleased/enhancement-add-font-weight-variables
packages/design-system/changelog/unreleased/enhancement-add-negative-margin
packages/design-system/src/styles/styles.scss
packages/design-system/src/styles/theme/_variables.scss
packages/design-system/src/styles/theme/oc-card.scss
packages/design-system/src/styles/theme/oc-spacing-negative.scss
packages/design-system/src/styles/theme/oc-text.scss
packages/design-system/src/tokens/ods/font.yaml
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/Details/FileDetailsMultiple.vue
packages/web-app-files/src/components/SideBar/FileInfo.vue
packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
packages/web-app-files/tests/unit/components/SideBar/Details/__snapshots__/FileDetails.spec.ts.snap
packages/web-app-files/tests/unit/components/SideBar/Versions/FileVersions.spec.ts
packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetails.vue
packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetailsMultiple.vue
packages/web-pkg/src/components/sideBar/Spaces/SpaceInfo.vue
packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/__snapshots__/SpaceDetails.spec.ts.snap
packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/__snapshots__/SpaceDetailsMultiple.spec.ts.snap
packages/web-pkg/tests/unit/components/sidebar/Spaces/__snapshots__/SpaceInfo.spec.ts.snap
tests/acceptance/pageObjects/FilesPageElement/versionsDialog.js

Beautify file versions list
- Fixes https://github.com/owncloud/web/issues/8503
Before:
After:

[full-ci] style file versions list

---

changelog/unreleased/enhancement-inject-customizations
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/tests/unit/container/bootstrap.spec.ts

Reverts owncloud/web#8512
Turned out that there are some de-serialization issues with maps in slices in the backend side struct. So we'll go the other way and add the `styles` and `scripts` to the config struct.

Revert "fix: move custom styles and scripts to config options"

---

changelog/unreleased/enhancement-user-group-filter
changelog/unreleased/enhancement-user-role-filter
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/views/Users.spec.ts

Change user filter for groups and roles to have an `OR` behaviour. So if you select both groups `physics-lovers` and `physics-haters`, it will result in users that are in either of those groups. Combining different filters like groups and roles still concatenates via `AND`.
- Fixes https://github.com/owncloud/web/issues/8469

Change behaviour of user filters to `OR`

---

changelog/unreleased/enhancement-cern-links
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.ts

Updated the links displayed in the sidebar for CERN's deployment.

Update CERN links

---

tests/e2e/support/environment/actor/shared.ts
tests/e2e/support/objects/app-files/share/actions.ts

enable clipboard both `read` and `write` permissions, and open sharing dialog if not open after creating quicklink (testing against oC10 server)
Same as in https://github.com/owncloud/web/pull/8530/files

[tests-only][full-ci] Refactor e2e test for quick link

---

changelog/unreleased/enhancement-admin-change-spaces-quota-batch-action
packages/web-app-admin-settings/src/components/Users/UsersList.vue
packages/web-app-admin-settings/src/views/Users.vue

* Fix additional user loading when one user is selected
* Prevent sidebar loading state from being mutated twice
- Fixes https://github.com/owncloud/web/issues/8544
- Potentially fixes https://github.com/owncloud/web/issues/8548

Fix additional user data loading

---

changelog/unreleased/change-update-vue
packages/design-system/src/components/OcCheckbox/OcCheckbox.vue

Probably a regression of Vue 3.
- Fixes https://github.com/owncloud/web/issues/8565

Fix custom permissions checkbox selection

---

changelog/unreleased/enhnacement-respect-max-quota
packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
packages/web-pkg/src/components/QuotaSelect.vue
packages/web-pkg/tests/unit/components/QuotaSelect.spec.ts
tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
tests/e2e/support/objects/app-admin-settings/users/actions.ts
tests/e2e/support/objects/app-files/spaces/actions.ts

- Fixes https://github.com/owncloud/web/issues/8536
- Fixes https://github.com/owncloud/web/issues/8575
- test case 1:
- test case 2:
- ...

Max quota follow up 

---

changelog/unreleased/enhancement-quickactions-configurable-capabilities
packages/web-app-files/src/components/SideBar/Shares/Links/CreateQuickLink.vue
packages/web-app-files/src/helpers/share/link.ts
packages/web-app-files/tests/unit/helpers/share/link.spec.ts
packages/web-client/src/helpers/share/role.ts
packages/web-client/src/ocs/capabilities.ts
packages/web-pkg/src/composables/capability/useCapability.ts

We've added the option to change the default quickactions role via capabilities.
See https://github.com/owncloud/web/issues/8547
- Fixes https://github.com/owncloud/web/issues/8547

[full-ci] Change default permissions to capablities

---

changelog/unreleased/bugfix-users-without-role-assignment
packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
packages/web-app-admin-settings/src/components/Users/UsersList.vue
packages/web-app-admin-settings/src/views/Users.vue

- Fixes https://github.com/owncloud/web/issues/8585

Fix loading/editing users that do not have a role assignment

---

changelog/unreleased/enhancement-notification-bell
changelog/unreleased/enhancement-notifications-ocis
packages/web-runtime/src/components/Topbar/Notifications.vue

- Fixes https://github.com/owncloud/web/issues/8593

Change notification sorting to show most recent at the top

---

changelog/unreleased/bugfix-drawio
packages/web-app-draw-io/src/App.vue

If users navigated out of Draw-io and returned afterwards, old event handlers were kept, which failed trying to look for iframes that no longer existed.
This fix removes the handlers when exiting, preventing these user visible errors.

De-duplicate event handling to prevent errors on Draw-io

---

packages/web-app-files/src/views/Favorites.vue
packages/web-app-files/src/views/spaces/GenericSpace.vue

Change order of view modes to `condensed`, `default`, `tiles`. This is the order @tbsbdr and I agreed on - and I think we had that at some point. Somehow got lost in a refactoring. Or my mind is playing games with me and it was always `default`, `condensed`, `tiles`. 🤔

fix: order of view modes

---

packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap
tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/cucumber/steps/ui/application.ts
tests/e2e/support/objects/account/account.ts
tests/e2e/support/objects/app-admin-settings/users/actions.ts
tests/e2e/support/objects/app-admin-settings/users/index.ts

[test-only] E2e. changing user

---

changelog/unreleased/bugfix-password-enforced-check
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue

The `isPasswordEnforcedFor` check in public link creation / editing was basically ignoring the permission bits of the selected role and always did an early return on the first password enforcement capability that was `true`. Fixed by not returning early anymore. 😆 
- Fixes https://github.com/owncloud/web/issues/8587

fix: don't run into early return in password enforcement check

---

tests/e2e/cucumber/features/smoke/admin-settings/general.ocis.feature
tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature
tests/e2e/cucumber/features/smoke/notifications.oc10.feature

Fixes: https://github.com/owncloud/web/issues/8626
This PR adds log-out steps for each login. Some tests were using the session of the previous steps, for instance, Admin , as this user is not recreated, it's possible that the other steps were using the same session for the admin user in different scenarios and we get the login failure which eventually passes in retry.

[tests-only]Fix flaky login e2e test

---

packages/design-system/docs/components/tokens/IconList.vue
packages/design-system/src/components/OcBreadcrumb/OcBreadcrumb.vue
packages/design-system/src/components/OcBreadcrumb/types.ts
packages/design-system/src/components/OcCheckbox/OcCheckbox.vue
packages/design-system/src/components/OcStatusIndicators/OcStatusIndicators.vue
packages/design-system/src/components/OcTable/OcTable.vue
packages/design-system/src/components/_OcGhostElement/_OcGhostElement.vue
packages/web-app-admin-settings/src/components/AppTemplate.vue
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/components/AppBar/Upload/ResourceUpload.vue
packages/web-app-files/src/components/AppBar/ViewOptions.vue
packages/web-app-files/src/components/FilesList/Pagination.vue
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/components/Spaces/SpaceContextActions.vue
packages/web-app-files/src/helpers/breadcrumbs.ts
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/src/views/trash/Overview.vue
packages/web-pkg/src/components/AppTopBar.vue
packages/web-pkg/src/components/Spaces/QuotaModal.vue
packages/web-pkg/src/components/Spaces/ReadmeContentModal.vue
packages/web-pkg/src/composables/actions/types.ts
packages/web-test-helpers/src/mocks/defaultComponentMocks.ts
web.d.ts
web.jest.d.ts

Register ODS components globally with TypeScript, so IDEs can help with autocompletion and show errors for missing or mismatched props.
... and add $route and $router to globally available component properties.
The TypeScript module configuration file has been split into two separate files, as one (the augmentation file) needs to be a module to work correctly and the `*.vue` module declaration (basically just needed for jest) must not be a module.
- Followup for https://github.com/owncloud/web/pull/8406
- test case 1:
- test case 2:
- ...

[full-ci] Augment vue GlobalComponents with ODS components

---

changelog/unreleased/enhancement-share-and-folder-loading-performance
packages/web-app-files/src/components/SideBar/SideBar.vue

Fixes regression from https://github.com/owncloud/web/pull/8349.
- Fixes https://github.com/owncloud/web/issues/8485

Fix endless sidebar loading on search- and favorites-page

---

tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature

Added e2e test for filtering users list by user role
Part of https://github.com/owncloud/web/issues/8601

[tests-only][full-ci] Added e2e tests for filtering users list by role

---

.drone.env
tests/e2e/cucumber/features/smoke/notifications.ocis.feature

related [#5865](https://github.com/owncloud/ocis/issues/5865)
- user should not get notification about own action
@kobergj I ran a notification test agains your branch `kobergj:NoNotificationForOwnActions `and found that the user does not receive notifications about disabling and deleting space. Could you please check this

[test-only] change notification test after fixing #5865

---

changelog/unreleased/enhancement-resources-tiles-view
packages/web-app-files/src/composables/sort/useSort.ts
packages/web-app-files/src/helpers/ui/resourceTable.ts
packages/web-app-files/src/helpers/ui/resourceTiles.ts
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
packages/web-client/src/helpers/space/functions.ts

- Fixes https://github.com/owncloud/web/issues/8439
- Fixes https://github.com/owncloud/web/issues/8409

Add space sorting options: `size` and `mdate`

---

changelog/unreleased/enhancement-add-logout-url
packages/web-pkg/src/configuration/manager.ts
packages/web-pkg/src/configuration/types.ts
packages/web-runtime/src/pages/account.vue
packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
packages/web-runtime/tests/unit/pages/account.spec.ts

We've added "Logout from active devices" in the account settings
- Fixes https://github.com/owncloud/web/issues/8609

Logout from all devices link

---

packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersPanel.vue
packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersRoleSection.vue
tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
tests/e2e/cucumber/steps/api.ts
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/support/api/davSpaces/index.ts
tests/e2e/support/api/davSpaces/spaces.ts
tests/e2e/support/api/share/index.ts
tests/e2e/support/api/share/share.ts
tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
tests/e2e/support/objects/app-admin-settings/spaces/index.ts

This PR does the following
- Adds a scenario to check the list of members in the space
- Adds API step to add member in a space
- Changes the vue component to add some `data-testid` needed for tests
- Part of: https://github.com/owncloud/web/issues/8601
- Local
- CI

[tests-only][full-ci]Add test to check the list of members in a space in the admin settings via sidebar panel

---

tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
tests/e2e/support/objects/app-admin-settings/spaces/index.ts

Implemented differently. 
we check each response while deleting spaces
Sometimes the selector `spaceTrSelector` can resolve to some elements in the spaces list even though the view would change to an `empty` view later. This behavior causes the tests to be flaky (see https://github.com/owncloud/web/issues/8648#issuecomment-1480853116) 
I have added a check for empty view before trying to get the spaces list and early return if the empty view is present.
Part of https://github.com/owncloud/web/issues/8648

[tests-only][full-ci] Check multiple response

---

tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/support/objects/app-admin-settings/groups/actions.ts
tests/e2e/support/objects/app-admin-settings/groups/index.ts
tests/e2e/support/objects/app-admin-settings/spaces/index.ts
tests/e2e/support/objects/app-admin-settings/users/actions.ts
tests/e2e/support/objects/app-admin-settings/users/index.ts

Added wait for the desired list of responses for these batch actions from admin settings:
- delete groups
- delete users
- change users' quota
- add a user to groups
- remove a user from groups
- add users to groups
- remove users from groups
part of https://github.com/owncloud/web/issues/8648

[full-ci][tests-only] Added wait for responses after batch actions

---

packages/design-system/changelog/unreleased/enhancement-beautify-modals
packages/design-system/src/components/OcModal/OcModal.vue
packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap
packages/web-app-admin-settings/src/composables/actions/groups/useGroupActionsDelete.ts
packages/web-app-admin-settings/src/composables/actions/users/useUserActionsDelete.ts
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
packages/web-app-files/src/composables/actions/files/useFileActionsEmptyTrashBin.ts
packages/web-app-files/src/composables/actions/helpers/useFileActionsDeleteResources.ts
packages/web-app-files/src/helpers/resource/conflictHandling/conflictDialog.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDelete.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDisable.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsRestore.ts

Slightly update modal layout:
- Separate modal actions from modal body by thin line
- Replace dark header background (light mode) with light header, to better integrate in light mode and to keep contrast ratio (before: title: light text on dark bg, body: dark text on light bg)
- Use same border radius as input fields (Goal: all interactive elements have the same)
- Increase line-height slightly for better readability
Before: 
After:

[full-ci] Slightly update modal layout

---

changelog/unreleased/enhancement-context-helper-read-more-configurable
docs/getting-started.md
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
packages/web-app-files/src/helpers/contextualHelpers.ts

As a followup to https://github.com/owncloud/web/pull/8713 I have:
- removed a `console.log` statement
- fixed the config option name in the docs
- switched from duplicated check in each context helper to a generic filtering approach
- made the options for the context helpers a single options object (I prefer that most of the time, because you can extend that much easier in the future)
- introduced types for the context helpers
- Fixes https://github.com/owncloud/web/issues/8570 ... again? :trollface:

followup: context helper filter

---

.vscode/extensions.json
.vscode/settings.json

`rvest.vs-code-prettier-eslint` does not format `.vue` files (anymore) -  `esbenp.prettier-vscode` does.
While at it, I added [TypeScript Vue Plugin](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin) to the list of recommended extensions.
- test case 1:
- test case 2:
- ...

vscode: fix auto format

---

dev/docker/ocis.idp.config.yaml

adding client config for developing the `file-picker` (see github.com/owncloud/file-picker) with our dockerized ocis dev environment.

feat: add oidc client config for filepicker development

---

packages/design-system/changelog/unreleased/enhancement-beautify-modals
packages/design-system/src/components/OcModal/OcModal.vue

... to match the other input forms.
- Fixes https://github.com/owncloud/web/issues/8742
Before:
After:

Reduce input height in modals

---

changelog/unreleased/bugfix-password-enforced-check
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue

Fix some quirks of the public link password enforcement.

Fix password enforcement

---

packages/design-system/changelog/unreleased/enhancement-read-only-select-options
packages/design-system/src/components/OcSelect/OcSelect.spec.ts
packages/design-system/src/components/OcSelect/OcSelect.vue
packages/web-app-admin-settings/src/components/Users/GroupSelect.vue
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap
packages/web-app-admin-settings/tests/unit/components/Users/__snapshots__/GroupSelect.spec.ts.snap
packages/web-app-files/src/components/SideBar/TagsPanel.vue
packages/web-app-files/tests/unit/components/SideBar/TagsPanel.spec.ts
tests/e2e/support/objects/app-files/resource/actions.ts

This is required for the user-group-assignment select because a user can have read-only groups that must not be removed.
- Needed for https://github.com/owncloud/web/issues/8729

[full-ci] Introduce read-only options to OcSelect

---

.vscode/extensions.json
.vscode/settings.json

1. To test install the recommended `alexkrechik.cucumberautocomplete`.
2. Go to any cucumber file e.g. `tests/e2e/cucumber/features/smoke/internalLink.ocis.feature`
3. Done, you now have syntax highlighting and autocompletion (also detects missing step definitions)

Add cucumber autocomplete extension + config

---

changelog/unreleased/bugfix-copy-clipboard-text
packages/web-app-files/src/components/SideBar/Shares/Links/NameAndCopy.vue

We've fixed an issue that caused the link message to display the wrong text
See https://github.com/owncloud/web/issues/8725
- Fixes https://github.com/owncloud/web/issues/8725

Bugfix: Copy to clipboard text

---

changelog/unreleased/bugfix-token-renewal-hash-mode
changelog/unreleased/enhancement-unauthenticated-bootstrap
dev/docker/ocis.idp.config.yaml
docker-compose.yml
packages/web-runtime/src/router/setupAuthGuard.ts
packages/web-runtime/src/services/auth/authService.ts
packages/web-runtime/src/services/auth/userManager.ts

this PR fixes multiple oidc related things:
- Our dockerized dev environment was missing the redirect uris for silent token renewal `/oidc-silent-redirect.html`. The silent renewal landed in a (silent :trollface: ) access_denied.
- silent token renewal had a url format that the oidc-client-lib could not parse when in vue router hash mode
- we now stop the application bootstrap early in the silent redirect callback page. This mitigates an ocis bug in the authentication middleware. Will post an ocis issue as well later on. 
As a result you should not get redirected to the access denied page anymore. That was happening on token renewals before. 
Fixes https://github.com/owncloud/web/issues/8420

fix: oidc token renewal

---

changelog/unreleased/bugfix-multiline-breadcrumb
packages/design-system/src/components/OcBreadcrumb/OcBreadcrumb.vue

Fix for bug with the long breadcrumb that was breaking the layout
https://github.com/owncloud/web/issues/6731
- The table options and the sidebar were partly out of the visible area because of the long breadcrumb

Multiline wrapping for long breadcrumb

---

changelog/unreleased/enhancement-enable-rename-groups
packages/web-app-admin-settings/src/components/Groups/ContextActions.vue
packages/web-app-admin-settings/src/components/Groups/CreateGroupModal.vue
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
packages/web-app-admin-settings/src/components/Groups/SideBar/DetailsPanel.vue
packages/web-app-admin-settings/src/components/Groups/SideBar/EditPanel.vue
packages/web-app-admin-settings/src/components/Groups/SideBar/GroupInfoBox.vue
packages/web-app-admin-settings/src/composables/actions/groups/index.ts
packages/web-app-admin-settings/src/composables/actions/groups/useGroupActionsEdit.ts
packages/web-app-admin-settings/src/views/Groups.vue
packages/web-app-admin-settings/tests/unit/components/Groups/ContextActions.spec.ts
packages/web-app-admin-settings/tests/unit/components/Groups/CreateGroupModal.spec.ts
packages/web-app-admin-settings/tests/unit/components/Groups/SideBar/DetailsPanel.spec.ts
packages/web-app-admin-settings/tests/unit/components/Groups/SideBar/EditPanel.spec.ts
packages/web-app-admin-settings/tests/unit/components/Groups/SideBar/__snapshots__/EditPanel.spec.ts.snap
packages/web-app-admin-settings/tests/unit/views/Groups.spec.ts
packages/web-client/src/graph.ts
tests/e2e/cucumber/features/smoke/admin-settings/groups.ocis.feature
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/support/objects/app-admin-settings/groups/actions.ts
tests/e2e/support/objects/app-admin-settings/groups/index.ts

- Fixes https://github.com/owncloud/web/issues/8714
- Fixes https://github.com/owncloud/web/issues/8591
- test case 1:
- test case 2:
- ...

[full-ci] Rename groups + refactoring

---

changelog/unreleased/enhancement-add-support-for-read-only-groups
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
packages/web-app-admin-settings/src/components/Users/GroupSelect.vue
packages/web-app-admin-settings/src/components/Users/GroupsModal.vue
packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
packages/web-app-admin-settings/src/composables/actions/groups/useGroupActionsDelete.ts
packages/web-app-admin-settings/src/composables/actions/groups/useGroupActionsEdit.ts
packages/web-app-admin-settings/src/views/Groups.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/components/Users/GroupSelect.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/EditPanel.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/__snapshots__/GroupSelect.spec.ts.snap
packages/web-app-admin-settings/tests/unit/views/Groups.spec.ts

Adds support for read-only groups. Such groups can't be edited or assigned to/removed from users. They are indicated via a lock icon in the group list and all affected inputs.
Needs latest oCIS master! You can test it by following the instructions given in https://github.com/owncloud/ocis/pull/5974.
- Fixes https://github.com/owncloud/web/issues/8729

Add support for read-only groups

---

changelog/unreleased/bugfix-open-external-apps
packages/web-runtime/src/router/helpers.ts
packages/web-runtime/src/services/auth/authService.ts
packages/web-runtime/tests/unit/router/index.spec.ts
packages/web-runtime/tests/unit/services/auth/authService.spec.ts

Fix query param handling in AuthService.signInCallback, needed at least for the `details` parameter of private links and parameters passed to the external app (fileId, ...).
- Fixes #8773 
`vue-router` does not correctly parse query params  when pushing/replacing a url with query params.
We can parse them with router.resolve and pass them separately.
This makes the `details` handling in `resolvePrivateLink.vue` work and also fixes the params getting lost when redirecting into the external app after sign in.
- test case 1:
- test case 2:
- ...

fix: query param handling in AuthService.signInCallback

---

changelog/unreleased/bugfix-admin-settings-batch-context-actions
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
packages/web-app-admin-settings/src/composables/actions/groups/useGroupActionsDelete.ts
packages/web-app-admin-settings/src/composables/actions/users/useUserActionsDelete.ts
packages/web-app-admin-settings/src/composables/actions/users/useUserActionsEdit.ts
packages/web-app-admin-settings/tests/unit/components/Groups/ContextActions.spec.ts
packages/web-app-admin-settings/tests/unit/composables/actions/general/useGeneralActionsResetLogo.spec.ts
packages/web-app-admin-settings/tests/unit/composables/actions/general/useGeneralActionsUploadLogo.spec.ts
packages/web-app-admin-settings/tests/unit/composables/actions/groups/useGroupActionsDelete.spec.ts
packages/web-app-admin-settings/tests/unit/composables/actions/groups/useGroupActionsEdit.spec.ts
packages/web-app-admin-settings/tests/unit/composables/actions/users/useUserActionsDelete.spec.ts
packages/web-app-admin-settings/tests/unit/composables/actions/users/useUserActionsEdit.spec.ts

Fixes several issues that appeared when selecting multiple users/groups/spaces in the admin-settings and then triggering batch actions via the context menu. Some actions were showing wrongly ("edit"), some actions were resetting the current selection ("show details").
Also adds proper unit tests for the group and user action composables.
- Fixes https://github.com/owncloud/web/issues/8549

Fix batch context actions in admin settings

---

tests/e2e/cucumber/features/smoke/createSpaceFromSelection.ocis.feature
tests/e2e/support/objects/app-files/resource/actions.ts

Fixes flaky e2e tests that were introduced with https://github.com/owncloud/web/pull/8730.
I'd prefer to wait for requests here, but there can be `n` requests, and we don't know `n` inside the test step.
Potentially fixes the broken pipeline in https://drone.owncloud.com/owncloud/ocis/21162/68/10.

[tests-only] Fix flaky 'create-space-from-resource'-e2e test

---

changelog/unreleased/enhancement-font-family-theming
docs/theming/_index.md
packages/design-system/src/index.ts

Adds a `fontFamily` token to the `designTokens` in theming and makes sure that it gets applied to the already existing css variable.

feat: add font family to theming

---

dev/docker/ocis.idp.config.yaml

the filepicker dev setup will use port 3000 when https://github.com/owncloud/file-picker/pull/198 is merged. Changing idp config in our dev setup here to align with that.

chore: change filepicker idp ports

---

changelog/unreleased/enhancement-user-settings-login-field
packages/web-app-admin-settings/src/components/Users/LoginModal.vue
packages/web-app-admin-settings/src/composables/actions/users/index.ts
packages/web-app-admin-settings/src/composables/actions/users/useUserActionsEditLogin.ts
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/components/Users/LoginModal.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/__snapshots__/LoginModal.spec.ts.snap
packages/web-app-admin-settings/tests/unit/composables/actions/users/useUserActionsEditLogin.spec.ts
packages/web-app-admin-settings/tests/unit/views/Users.spec.ts

Adds a batch action to the users list in the admin settings which allows the admin to batch-edit the login state of users.
- Fixes https://github.com/owncloud/web/issues/8798

Implement batch action for editing the login state of users

---

changelog/unreleased/enhancement-preview-app-sorting
packages/web-app-files/src/router/spaces.ts
packages/web-app-preview/src/App.vue
packages/web-app-preview/src/components/MediaControls.vue
packages/web-app-preview/src/components/Sources/MediaAudio.vue
packages/web-app-preview/src/components/Sources/MediaImage.vue
packages/web-app-preview/src/components/Sources/MediaVideo.vue
packages/web-app-preview/src/helpers/types.ts
packages/web-app-preview/tests/unit/app.spec.ts
packages/web-app-preview/tests/unit/components/MediaControls.spec.ts

* Adds sorting to the preview app
* Refactors the code and splits up `App.vue` into smaller components
- Fixes https://github.com/owncloud/web/issues/7978
- Fixes https://github.com/owncloud/web/issues/3821

Respect sorting from the file list in the preview app

---

changelog/unreleased/bugfix-share-recipient-container-exceed
packages/design-system/src/components/OcSelect/OcSelect.vue

- Fixes https://github.com/owncloud/web/issues/8811

Prevent share recipient container from exceeding its height

---

packages/web-app-admin-settings/src/components/Spaces/ContextActions.vue
packages/web-app-admin-settings/src/components/Spaces/SideBar/ActionsPanel.vue
packages/web-app-admin-settings/src/components/Users/ContextActions.vue
packages/web-app-admin-settings/src/composables/actions/groups/useGroupActionsDelete.ts
packages/web-app-admin-settings/src/composables/actions/users/useUserActionsDelete.ts
packages/web-app-admin-settings/src/views/Spaces.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/composables/actions/groups/useGroupActionsDelete.spec.ts
packages/web-app-admin-settings/tests/unit/composables/actions/users/useUserActionsDelete.spec.ts
packages/web-app-files/src/components/Spaces/SpaceContextActions.vue
packages/web-pkg/src/components/Spaces/QuotaModal.vue
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsEditQuota.ts

Fixes user quota reactivity in right sidebar and implements proper messaging on user- and group-batch-delete.
I had to refactor `useSpaceActionsEditQuota.ts` a bit and removed `selectedSpace` and the method which updates it. This was built to deal with one given space, but now that the quota can be edited via batch it doesn't make sense anymore.
- Fixes https://github.com/owncloud/web/issues/8815
- Fixes https://github.com/owncloud/web/issues/8690

Fix user quota reactivity

---

changelog/unreleased/bugfix-remove-drop-target-in-read-only-folders
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts

Removes the drop target in read-only folders
- Fixes https://github.com/owncloud/web/issues/8277

Remove drop target in read-only folders

---

packages/web-app-admin-settings/src/components/AppTemplate.vue
packages/web-app-admin-settings/src/components/Users/UsersList.vue
packages/web-app-admin-settings/tests/unit/views/__snapshots__/Spaces.spec.ts.snap

* [Fix batch labels not hiding when sidebar is being opened](https://github.com/owncloud/web/commit/b5fdf65655c108e93e0b7c7cfba6ee226e364078)
* [Improve user list on smaller screens](https://github.com/owncloud/web/commit/ef258385bac6191f98e145f545c89e8f4c99fe3c)
- Fixes https://github.com/owncloud/web/issues/8844
- Fixes https://github.com/owncloud/web/issues/8831

Improve views in admin-settings when having limited horizontal screen estate

---

changelog/unreleased/bugfix-hide-upload-hint-in-read-only-folders
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/unit/views/spaces/GenericSpace.spec.ts

- Fixes https://github.com/owncloud/web/issues/8834

Hide upload hint in empty read-only folders

---

changelog/unreleased/bugfix-pagination-after-increasing-items-per-page
packages/web-app-files/src/components/AppBar/ViewOptions.vue
packages/web-app-files/tests/unit/components/AppBar/ViewOptions.spec.ts

Fixes an issue where the file list incorrectly showed no items after paginating and increasing the amount of items per page. This was achieved by resetting the `page` query back to `1` if the user is on a page > 1.
- Fixes https://github.com/owncloud/web/issues/6768

Fix pagination after increasing items per page

---

packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/composables/actions/files/useFileActionsAcceptShare.ts
packages/web-app-files/src/composables/actions/files/useFileActionsCreateSpaceFromResource.ts
packages/web-app-files/src/composables/actions/files/useFileActionsDeclineShare.ts
packages/web-app-files/src/composables/actions/files/useFileActionsEmptyTrashBin.ts
packages/web-app-files/src/composables/actions/files/useFileActionsFavorite.ts
packages/web-app-files/src/composables/spaces/useCreateSpace.ts
packages/web-app-files/src/views/FilesDrop.vue
packages/web-pkg/src/composables/actions/files/useFileActionsSetReadme.ts
packages/web-pkg/src/composables/appDefaults/useAppFileHandling.ts
packages/web-pkg/src/composables/download/useDownloadFile.ts
packages/web-runtime/src/components/Account/GdprExport.vue
packages/web-runtime/src/components/Topbar/Notifications.vue

We have to be careful not to destruct the `useClientService` composable in `setup`. The reactivity needed for getting the access token will get lost by doing this.
This is a regression from https://github.com/owncloud/web/pull/8621.
- Fixes https://github.com/owncloud/web/issues/8861

Fix client service requests with new access token

---

changelog/unreleased/enhancement-respect-user-readonly-configuration
packages/design-system/src/components/OcSelect/OcSelect.vue
packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/EditPanel.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap
packages/web-pkg/src/components/QuotaSelect.vue
packages/web-pkg/src/components/Spaces/QuotaModal.vue
packages/web-pkg/src/composables/capability/useCapability.ts

- Fixes https://github.com/owncloud/web/issues/8840
- test case 1:
- test case 2:
- ...

Show read-only user-attributes as locked

---

.drone.star
tests/e2e/cucumber/features/smoke/spaces/memberExpiry.ocis.feature

The skipped test started to fail because we have a bug in the calendar that the scroller will automatically scroll up while trying to select the end-of-the-month dates https://github.com/owncloud/web/issues/7513 .
This PR skips the test so that it won't obstruct the CI
Also, read the comment below https://github.com/owncloud/web/pull/8905#issuecomment-1521214490
Fixes: https://github.com/owncloud/web/issues/8902

[tests-only][full-ci]Skip the expiry date related e2e test

---

packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/DetailsAndEdit.spec.ts.snap
packages/web-pkg/src/components/ItemFilter.vue
packages/web-runtime/src/components/Topbar/ApplicationsMenu.vue
packages/web-runtime/src/components/Topbar/UserMenu.vue
packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.ts.snap

* Adjust line height in account menu dropdown
* Reduce margin-top/bottom on first and last items in several dropdowns:
* Account menu
* App switcher
* Sharing role select
* User filter
- Fixes https://github.com/owncloud/web/issues/7525

Fix various spacings

---

changelog/unreleased/bugfix-calendar-popup-position-in-sidebar
packages/design-system/src/components/OcDatepicker/OcDatepicker.vue
tests/acceptance/features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature
tests/e2e/cucumber/features/smoke/spaces/memberExpiry.ocis.feature

Implements a popper modifier similar to how we do it in `OcDrop` to fix the vertical position of the calendar popup. There could still be edge cases, and the `top` pixels might need some tweaking.
How it basically works: Check if the needed screen space exceeds the window height. If so, move the popup up by quite a bit.
- Fixes https://github.com/owncloud/web/issues/7513

[full-ci] Fix sidebar calendar position

---

.drone.env

This PR bumps ocis commit id for tests
Part of: https://github.com/owncloud/QA/issues/806

[full-ci][tests-only]Bump ocis commit id for tests

---

changelog/unreleased/enhancement-notifications-ocis
packages/web-runtime/src/components/Topbar/Notifications.vue

This is a bit of a hacky (and temporary!) solution to detect if the current user session was terminated remotely: As we poll notifications actively every 30 seconds we simply catch a `401` status response and let the auth service perform `handleAuthError`.
This solution can be removed as soon as the server is able to inform the client that a backchannel logout has been performed.
An alternative solution would be to implement another polling interval that constantly performs requests to the IDP. I don't really like that though as it would introduce more network traffic.
- Fixes https://github.com/owncloud/web/issues/8910

[full-ci] Handle `401` status code when fetching notifications

---

tests/e2e/cucumber/features/smoke/reshare.feature
tests/e2e/cucumber/steps/ui/links.ts
tests/e2e/support/objects/app-files/link/index.ts

Beacuse of the change of this PR https://github.com/owncloud/web/pull/8876. For public link the display text after the selection of different role is now different. So this PR maps different role of public link to different role in displayed in the UI.
https://github.com/owncloud/web/issues/8930

[tests-only][full-ci]Added display role text change before assertion

---

changelog/unreleased/enhancement-share-and-folder-loading-performance
packages/web-app-files/src/store/actions.ts
packages/web-app-files/tests/unit/store/actions.spec.ts

When adding/removing shares while the shares are currently in a loading state, we need to wait for the loading to be finished.
- Fixes https://github.com/owncloud/web/issues/8894
- Fixes https://github.com/owncloud/web/issues/8896

Fix share loading when adding a link via quick action

---

changelog/unreleased/bugfix-infinite-login-redirect
packages/web-runtime/src/services/auth/authService.ts

Fixes login redirect loop when user info or capabilities can't be fetched.
- Fixes https://github.com/owncloud/web/issues/8928
- Fixes https://github.com/owncloud/web/issues/7354
- Fixes https://github.com/owncloud/web/issues/4677

fix: infinite login redirect loop

---

changelog/unreleased/enhancement-webfinger-app
packages/web-app-webfinger/src/index.ts
packages/web-pkg/src/composables/router/types.ts
packages/web-runtime/src/index.ts
packages/web-runtime/src/layouts/Application.vue
packages/web-runtime/src/router/helpers.ts
packages/web-runtime/src/router/setupAuthGuard.ts
packages/web-runtime/src/services/auth/authService.ts
packages/web-runtime/src/services/auth/userManager.ts
packages/web-runtime/src/store/auth.ts

Added an `idp` authContext type and used it for the webfinger resolve page. Idea is that `idp` requires a valid login in contrast to `user` which also requires an ownCloud user. The webfinger app doesn't need an ownCloud backend, only the webfinger service.
As a consequence the `idp` context being ready doesn't lead to loading user, capabilities, spaces, etc.
This again increases the urgency of documenting at least parts of the extension system. The authentication requirements in route definitions are thought through to a good extend, this needs to be written down and explained. Out of scope for this PR though...

feat: idp auth context

---

changelog/unreleased/enhancement-webfinger-app
packages/web-app-webfinger/src/views/Resolve.vue
packages/web-runtime/src/services/auth/authService.ts
packages/web-runtime/src/store/auth.ts

Clear idp user on 401 from webfinger service. The 401 can happen if the access token was invalidated in the meantime. Then we need to enforce another roundtrip to the IdP.

feat: clear idp user on 401 in webfinger resolve

---

changelog/unreleased/enhancement-add-expiration-date-hint-to-public-links
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/DetailsAndEdit.spec.ts.snap

Reverting https://github.com/owncloud/web/pull/8866 except for the switch from `$gettextInterpolate` to `$gettext`. The role labels have changed and now the horizontal space is not sufficient anymore for the expiration hint. See screenshot.

Revert remaining link time label

---

packages/web-app-files/src/components/Spaces/SpaceHeader.vue

- Fixes https://github.com/owncloud/web/issues/8879

Fix space header image ratio in Safari

---

tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
tests/acceptance/pageObjects/FilesPageElement/filesList.js
tests/acceptance/pageObjects/personalPage.js
tests/acceptance/stepDefinitions/filesContext.js

This PR refactors the folder navigation process. Instead of navigating through the url, it uses the click function to navigate inside the folder. Which makes the tests running. Before with navigating with URL, the UI was not properly rendered.
https://github.com/owncloud/ocis/issues/6206

[tests-only][full-ci]Navigate to folder by click instead of navigate with URL

---

changelog/unreleased/enhancement-add-notifications-setting
packages/design-system/src/components/OcSelect/OcSelect.vue
packages/web-runtime/src/helpers/settings.ts
packages/web-runtime/src/pages/account.vue
packages/web-runtime/tests/unit/pages/account.spec.ts

Fixes a regression due to the refactoring in https://github.com/owncloud/web/pull/8911. Also adds proper types for the settings stuff.
- Fixes https://github.com/owncloud/web/issues/8962

Fix highlighting of the currently selected language

---

.drone.env
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js

Bump latest ocis commit-id to web 
https://github.com/owncloud/QA/issues/807

[tests-only][full-ci]Bump ocis commit to web

---

tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature
tests/e2e/cucumber/steps/ui/public.ts
tests/e2e/support/api/graph/userManagement.ts
tests/e2e/support/api/userManagement.ts
tests/e2e/support/environment/userManagement.ts
tests/e2e/support/objects/app-admin-settings/users/actions.ts
tests/e2e/support/objects/app-admin-settings/users/index.ts

This PR removes **dummyUser** variable used from methods other than user creation time.
Now user gets user data from `dummyUser` and creates a user and stores the created data in `createdUser`
In the next PR I will implement the logic for the group store
- https://github.com/owncloud/web/issues/8819
Follow-up PR of 
- https://github.com/owncloud/web/pull/8848
- Locally

[tests-only][full-ci] Refactor user store for e2e tests

---

changelog/unreleased/bugfix-limit-concurrent-tus-requests
packages/web-runtime/src/services/uppyService.ts

Limits the amount of concurrent tus requests when uploading to `5`. The limit defaulted to `20` before, which a normal modern browser can't handle anyways. I benchmarked the upload time before and after the change with a ~700MB folder -> it was roughly the same.
This fixes an issue where the access token renewal failed during an ongoing upload because of the sheer amount of pending requests.
- Fixes https://github.com/owncloud/web/issues/8977

Limit amount of concurrent tus requests

---

changelog/unreleased/enhancement-shrink-table-columns
packages/design-system/src/components/OcAvatars/OcAvatars.vue
packages/design-system/src/components/OcTable/OcTable.vue
packages/design-system/src/components/_OcTableCell/_OcTableCell.vue
packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
packages/web-app-files/src/components/FilesList/ResourceTable.vue

- shrinks table columns that took a weirdly high amount of horizontal space
- adds a prop validator for allowed view modes in the resource table
- invisible sort buttons in the table header no don't take up horizontal space anymore (otherwise alignment looks weird for shrinked columns)
- gave more horizontal padding to the table cells so that the overall look and feel of the table is not crimped
- Fixes https://github.com/owncloud/web/issues/8599

[full-ci] feat: shrink most table columns to their minimum

---

tests/e2e/cucumber/environment/index.ts
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/support/api/graph/userManagement.ts
tests/e2e/support/environment/userManagement.ts
tests/e2e/support/objects/app-admin-settings/groups/actions.ts
tests/e2e/support/objects/app-admin-settings/groups/index.ts
tests/e2e/support/objects/app-admin-settings/users/actions.ts
tests/e2e/support/store/index.ts

This PR removes **dummyGroup** uses other than getting group dummy value at creation time.
Now created group will be stored in **createdGroup**.  Currently, **createdGroupStore** is cleared at `After` hook because we need group id to check whether the group exists after the deletion or nor 
- https://github.com/owncloud/web/issues/8819
Follow-up PR of 
- https://github.com/owncloud/web/pull/8848
- https://github.com/owncloud/web/pull/8871
- Locally

[tests-only][full-ci] Refactor group store for e2e tests

---

changelog/unreleased/bugfix-personal-space-name-after-language-change
packages/web-runtime/src/pages/account.vue
packages/web-runtime/tests/unit/pages/account.spec.ts

- Fixes https://github.com/owncloud/web/issues/8968

Fix personal space name not updating after language change

---

changelog/unreleased/bugfix-endless-loading-public-link-error
packages/web-runtime/src/pages/resolvePublicLink.vue

Fixes an endless loading state that occurred when encountering an error when loading a public link.
- Fixes https://github.com/owncloud/web/issues/9004
(translation is missing)

Fix endless loading when encountering a public link error

---

.drone.star
changelog/unreleased/enhancement-deny-share-access
docker-compose.yml
packages/design-system/src/components/OcDrop/OcDrop.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/services/folder/loaderSharedWithOthers.ts
packages/web-app-files/src/store/actions.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.ts.snap
packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap
packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/SpaceMembers.spec.ts.snap
packages/web-app-files/tests/unit/store/actions.spec.ts
packages/web-client/src/helpers/share/role.ts
tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
tests/e2e/cucumber/features/smoke/denyShareAccess.feature
tests/e2e/cucumber/steps/ui/shares.ts
tests/e2e/support/objects/app-files/share/actions.ts
tests/e2e/support/objects/app-files/share/collaborator.ts
tests/e2e/support/objects/app-files/share/index.ts

Enhancement: deny share access
We've added a way to deny the share access in sub folders in a share or space.
This allows the share editors to restrict access to certain resources within a share for certain share receivers.
- Fix  https://github.com/owncloud/web/issues/7180
- test case 1:
- test case 2:
- ...

[full-ci] feature-deny-access
