tests/e2e/cucumber/environment/index.ts
tests/e2e/cucumber/steps/api.ts
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/support/api/graph/userManagement.ts

This issue clean-up the group in the `After` hook.
Part of
- https://github.com/owncloud/web/issues/8662
- locally

[tests-only][full-ci] Cleanup group created by test scenario at after hook

---

tests/e2e/cucumber/environment/index.ts
tests/e2e/cucumber/steps/api.ts
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/cucumber/steps/ui/session.ts

This issue clean-up the user in the `After` hook.
- https://github.com/owncloud/web/issues/8662
- locally

[tests-only][full-ci] Cleanup user created by test scenario at after hook

---

tests/e2e/cucumber/environment/index.ts
tests/e2e/cucumber/steps/api.ts
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/cucumber/steps/ui/session.ts
tests/e2e/support/api/graph/userManagement.ts
tests/e2e/support/environment/userManagement.ts
tests/e2e/support/objects/app-admin-settings/groups/actions.ts
tests/e2e/support/objects/app-admin-settings/groups/index.ts
tests/e2e/support/objects/app-admin-settings/users/actions.ts
tests/e2e/support/store/index.ts

Backport PRs #8914, #8994 and #8998

[tests-only][full-ci] Backport users and groups teardown test codes

---

changelog/unreleased/bugfix-forbid-virtual-shares
packages/web-pkg/src/composables/driveResolver/useDriveResolver.ts

Preventing access to virtual spaces. Otherwise it's possible to e.g. access the virtual shares space (`virtual/shares`), which we don't want because shares are handled differently in web.

fix: forbid virtual spaces

---

dev/docker/oc10.entrypoint.sh
tests/drone/setup-server-and-app.sh
tests/e2e/cucumber/features/smoke/personalSpacePagination.feature
tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature
tests/e2e/cucumber/steps/api.ts
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

This PR adds test to check the pagination in personal space page
- Part of: https://github.com/owncloud/ocis/issues/5013
- locally
- CI

[tests-only]Add tests for pagination in personal space

---

changelog/unreleased/bugfix-spaces-in-search-results
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/Search/Preview.vue
packages/web-app-files/src/search/sdk/list.ts
packages/web-app-files/src/search/sdk/preview.ts
packages/web-app-files/tests/unit/search/sdk.spec.ts
packages/web-client/src/helpers/space/functions.ts

Fixes wrong icons and sidebar panels for spaces in share results as well as their parent folder below the resource name.
Unfortunately, there is no convenient way to distinguish spaces from folders based on the search response form the server. Although space resources have empty permissions, which differs from folders, it doesn't feel great to distinguish them based on that attribute IMO. I'm open for suggestions though.
- Fixes https://github.com/owncloud/web/issues/9022
- Fixes https://github.com/owncloud/web/issues/8925

Fix spaces in search results

---

changelog/unreleased/enhancement-search-tag-filter
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/router/common.ts
packages/web-app-files/tests/unit/components/Search/List.spec.ts
packages/web-app-search/src/portals/SearchBar.vue
packages/web-app-search/src/views/List.vue
packages/web-app-search/tests/unit/portals/SearchBar.spec.ts
packages/web-app-search/tests/unit/views/List.spec.ts
packages/web-pkg/src/components/ItemFilter.vue

Adds a tag filter to the search result page which can be used to filter the displayed search result by tags.
This was a bit more complicated than I anticipated, mainly because of 2 issues I encountered:
* The file list component's purpose was to simply display a search result, meaning the component could not trigger a search. Triggering a search was done by the parent component in the search app instead. With the filter now living inside the files component, I decided to changed this. The component in the files app now emits a `search` event to the parent component which eventually handles the search. This way, all the filter logic stays decoupled in the files list component.
* The filter chip's visual state can be changed by either interacting with the filter directly or by loading the …

[full-ci] Implement tag filter on search result page

---

changelog/unreleased/enhancement-respect-archiver-limits
packages/design-system/changelog/7.0.0_2021-05-31/bugfix-interactive-oc-tooltip-texts
packages/web-app-files/src/composables/actions/files/useFileActionsDownloadArchive.ts
packages/web-app-files/src/services/archiver.ts
packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceContextActions.spec.ts.snap
packages/web-app-files/tests/unit/services/archiver.spec.ts
packages/web-pkg/src/components/ContextActions/ActionMenuItem.vue
packages/web-pkg/src/composables/actions/types.ts
packages/web-pkg/tests/unit/components/ContextActions/ActionMenuItem.spec.ts

Respect archiver limits on BatchAction download

---

changelog/unreleased/bugfix-no-content-not-found
packages/web-app-files/src/components/FilesList/NotFoundMessage.vue
packages/web-app-files/src/views/spaces/GenericSpace.vue

Fixing two things:
- "Resource not found" obtaining too much height (thus scroll bars were appearing)
- "Resource not found" and "Empty folder" messages appearing at the same time
- Fixes https://github.com/owncloud/web/issues/9061

fix: resource not found and no content message both displayed

---

changelog/unreleased/enhancement-mobile-navigation
packages/web-runtime/src/components/MobileNav.vue

The issue appeared when there was no active nav item present because the mobile nav uses the label of the active nav item for display. The label now falls back to the first nav item (usually that's `Personal`).
- Fixes https://github.com/owncloud/web/issues/9073

Fix search result page on mobile view

---

changelog/unreleased/enhancement-search-fulltext-filter
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/tests/unit/components/Search/List.spec.ts
packages/web-pkg/src/composables/capability/useCapability.ts

Follow-up for https://github.com/owncloud/web/pull/9059.
Reva implementation: https://github.com/cs3org/reva/pull/3913

Add capability check for full-text search

---

changelog/unreleased/enhancement-long-breadcrumb-strategy
packages/design-system/src/components/OcBreadcrumb/OcBreadcrumb.spec.ts
packages/design-system/src/components/OcBreadcrumb/OcBreadcrumb.vue
packages/design-system/src/components/OcBreadcrumb/__snapshots__/OcBreadcrumb.spec.ts.snap
packages/design-system/src/components/OcBreadcrumb/types.ts
packages/web-app-admin-settings/tests/unit/views/__snapshots__/Spaces.spec.ts.snap
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/helpers/breadcrumbs.ts
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/unit/components/AppBar/__snapshots__/AppBar.spec.ts.snap
packages/web-app-files/tests/unit/helpers/breadcrumbs.spec.ts

Breadcrumb should not line-break. This is a new strategy to deal with long breadcrumbs and long folder names.
See https://github.com/owncloud/web/issues/6731
Maybe this helps
Before (old):
After (new):
- Fixes https://github.com/owncloud/web/issues/6731

[full-ci] Implement long breadcrumb strategy

---

tests/e2e/cucumber/steps/ui/accountMenu.ts
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/cucumber/steps/ui/links.ts
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/link/index.ts
tests/e2e/support/objects/app-files/resource/actions.ts

Fixed `expect()` usage as per:
```js
expect.(<RecievedValue>).toBe(<ExpectedValue>)
```
- Fixes https://github.com/owncloud/web/issues/9005

[tests-only] Fix expect().toBe() usage

---

packages/web-runtime/src/pages/resolvePublicLink.vue

Translations for public link error messages are completely missing. Added `$gettext` wrapper to the error messages so that the strings can be extracted for transifex.

fix: wrap public link resolve error messages in $gettext

---

tests/e2e/cucumber/steps/ui/accountMenu.ts
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/cucumber/steps/ui/links.ts
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/api/graph/spaces.ts
tests/e2e/support/objects/account/actions.ts
tests/e2e/support/objects/account/index.ts
tests/e2e/support/objects/app-admin-settings/general/index.ts
tests/e2e/support/objects/app-admin-settings/groups/index.ts
tests/e2e/support/objects/app-admin-settings/spaces/index.ts
tests/e2e/support/objects/app-admin-settings/users/index.ts
tests/e2e/support/objects/app-files/link/index.ts
tests/e2e/support/objects/app-files/page/public.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts
tests/e2e/support/objects/app-files/share/index.ts
tests/e2e/support/objects/app-files/spaces/index.ts
tests/e2e/support/objects/app-files/trashbin/index.ts

Forward port PRs:
- https://github.com/owncloud/web/pull/9093
- https://github.com/owncloud/web/pull/9089
Fixes https://github.com/owncloud/web/issues/9005

[tests-only] Port refactor PRs

---

changelog/unreleased/enhancement-search-fulltext-filter
changelog/unreleased/enhancement-search-tag-filter
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/tests/unit/components/Search/List.spec.ts
packages/web-app-search/src/views/List.vue
packages/web-pkg/src/components/ItemFilter.vue
packages/web-pkg/tests/unit/components/ItemFilter.spec.ts
packages/web-pkg/tests/unit/components/__snapshots__/ItemFilter.spec.ts.snap
tests/acceptance/features/webUIFilesSearch/search.feature

Fixes the search syntax when combining multiple filters together with the search term. For now, only one tag can be selected in the filter due to a server restriction. Also updates the `ItemFilter` component to properly display single-select filters.
This is a follow-up for the most recent search filter PRs.
Note that the PR breaks the search for oC10, see here for more detail: https://github.com/owncloud/ocis/issues/6378#issuecomment-1562498414

[full-ci] fix: search syntax when combining filters

---

.drone.env

Part of: https://github.com/owncloud/QA/issues/809
This PR bumps the ocis commit id for tests

[tests-only][full-ci]Bump commit id for tests 20230525 stable

---

changelog/unreleased/bugfix-share-indicator-after-pasting
packages/web-app-files/src/store/actions.ts

- Fixes https://github.com/owncloud/web/issues/9030

fix: share indicator loading after pasting resources

---

tests/acceptance/expected-failures-with-oc10-server-openid-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md

After fix of issue: https://github.com/owncloud/ocis/issues/904, the test now fail because of https://github.com/owncloud/web/issues/4677, so link the failing test to correct issue

[tests-only][full-ci]Add tests to correct failing issue

---

tests/acceptance/expected-failures-with-oc10-server-openid-login.md
tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md

After fix of issue: https://github.com/owncloud/ocis/issues/904, the test now fail because of https://github.com/owncloud/web/issues/4677, so link the failing test to correct issue
Forward port of: https://github.com/owncloud/web/pull/9123

[tests-only][fulll-ci]Link correct issue to expected to fail file

---

tests/e2e/cucumber/steps/ui/session.ts
tests/e2e/support/objects/app-admin-settings/general/actions.ts
tests/e2e/support/objects/app-admin-settings/page/general.ts
tests/e2e/support/objects/app-admin-settings/page/groups.ts
tests/e2e/support/objects/app-admin-settings/page/spaces.ts
tests/e2e/support/objects/app-admin-settings/page/users.ts
tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
tests/e2e/support/objects/app-admin-settings/users/actions.ts
tests/e2e/support/objects/app-files/link/actions.ts
tests/e2e/support/objects/app-files/page/public.ts
tests/e2e/support/objects/app-files/page/shares/withMe.ts
tests/e2e/support/objects/app-files/page/spaces/projects.ts
tests/e2e/support/objects/app-files/page/trashbin/overview.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts
tests/e2e/support/objects/app-files/resource/utils.ts
tests/e2e/support/objects/app-files/share/collaborator.ts
tests/e2e/support/objects/app-files/share/utils.ts
tests/e2e/support/objects/app-files/spaces/actions.ts
tests/e2e/support/objects/runtime/application.ts

Playwright has discouraged to use `page.waitForSelector`, see https://playwright.dev/docs/api/class-page#page-wait-for-selector
Replaced `page.waitForSelector` with `locator.waitFor`

[tests-only][full-ci] Replace page.waitForSelector with locator.waitFor

---

tests/e2e/support/objects/app-files/link/actions.ts

Select the last notification from the list which is the latest notification for the given action
Fixes the flakiness due to the selector resolving to more than one element

[tests-only] Fix notification selection

---

changelog/unreleased/bugfix-select-all-checkbox
packages/web-app-files/src/components/FilesList/ResourceTable.vue

The problem was that we check if selectedIds.length equal the length of the resources inside the table. So if one item is selected in another table the statement will be true in all tables even so no item was selected.
See https://github.com/owncloud/web/issues/9122
- Fixes https://github.com/owncloud/web/issues/9122

Bugfix: select-all checkbox checks items in other list

---

changelog/unreleased/fix-public-link-file-previews
packages/web-app-files/src/components/SideBar/Actions/FileActions.vue
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.ts

Right sidebar / single file resource details file preview was not working at all in public links.

Fix public link preview

---

changelog/unreleased/enhancement-admin-settings-support-pagination
packages/web-app-admin-settings/src/views/Groups.vue
packages/web-app-admin-settings/src/views/Spaces.vue
packages/web-app-admin-settings/src/views/Users.vue

Adds a pagination reset after deleting all items on the last page of the users-, groups- and spaces-list. This fixes potential empty tables in such scenarios.
Follow-up for https://github.com/owncloud/web/pull/9119.

fix: empty tables after deleting items in admin-settings

---

changelog/unreleased/bugfix-spaces-sidebar-shared-via-link
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/fileSideBars.ts

Fixes the sidebar for spaces on the "Shared via link"-page which acted like the space was a folder resource before. I also decided to hide the actions panel for spaces in this view because the actions don't have any visible impact anyways here.
- Fixes https://github.com/owncloud/web/issues/9020

Fix sidebar for spaces on 'Shared via link'-page

---

changelog/unreleased/bugfix-empty-files-list-after-deleting
packages/web-app-files/src/composables/actions/helpers/useFileActionsDeleteResources.ts
packages/web-app-files/tests/unit/composables/actions/helpers/useFileActionsDeleteResources.spec.ts

Fixes an issue where the file list would be empty after deleting all resources on the last page. The file list now resets the pagination in such scenario.
- Fixes https://github.com/owncloud/web/issues/9014

Fix empty file list after deleting resources

---

changelog/unreleased/enhancement-drag-drop-parent-folder
packages/design-system/src/components/OcBreadcrumb/OcBreadcrumb.vue
packages/design-system/src/components/OcBreadcrumb/types.ts
packages/design-system/src/helpers/constants.ts
packages/design-system/src/styles/theme/oc-text.scss
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/helpers/breadcrumbs.ts
packages/web-app-files/src/helpers/resource/actions/transfer.ts
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/helpers/breadcrumbs.spec.ts
packages/web-app-files/tests/unit/helpers/resource/resourcesTransfer.spec.ts
tests/e2e/cucumber/features/smoke/copyMove.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts

See https://github.com/owncloud/web/issues/9043
- Fixes https://github.com/owncloud/web/issues/9043
- Fixes https://github.com/owncloud/web/issues/7454

[full-ci] Drag & drop on Breadcrumb parent folder 

---

.drone.env
packages/web-app-admin-settings/src/composables/actions/users/useUserActionsEditQuota.ts
packages/web-app-admin-settings/src/index.ts
packages/web-app-admin-settings/tests/unit/composables/actions/users/useUserActionsEditQuota.spec.ts
packages/web-app-files/src/composables/actions/files/useFileActionsCreateSpaceFromResource.ts
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/components/Spaces/SpaceContextActions.spec.ts
packages/web-app-files/tests/unit/views/spaces/Projects.spec.ts
packages/web-client/src/helpers/space/functions.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsEditQuota.ts
packages/web-pkg/src/utils/types.ts
packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsEditQuota.spec.ts
packages/web-runtime/src/services/auth/abilities.ts
packages/web-runtime/tests/unit/services/auth/abilities.spec.ts

Renames the permissions to match the new names coming from the server. Also renames the `Space` ability subject to `Drive` to go hand in hand with the server's naming convention.
Needs https://github.com/owncloud/ocis/pull/6391 to run properly.

refactor: rename permissions

---

packages/design-system/src/components/OcSearchBar/OcSearchBar.vue
packages/web-pkg/src/components/ItemFilter.vue
packages/web-pkg/tests/unit/components/__snapshots__/ItemFilter.spec.ts.snap

* [fix: tag filter spacing in advanced search](https://github.com/owncloud/web/commit/1d401b6ab6c790a557c77aa21b2784006ec0d654)
* [fix: clear- and advanced-search buttons overlapping](https://github.com/owncloud/web/commit/e7880e6223a086ae296375e500aca1024e06330d)

Fix 2 small annoyances in search UI

---

changelog/unreleased/bugfix-upload-info-incorrect-pause
packages/web-runtime/src/components/UploadInfo.vue

Fixes an incorrect pause state in the upload info modal.
- Fixes https://github.com/owncloud/web/issues/9080

fix: incorrect pause state in upload info modal

---

packages/web-app-files/src/helpers/resources.ts

Fixes the `canCreate` permission check in read-only shares. The corresponding method was missing for built shares which could lead to broken share views.
https://github.com/owncloud/web/pull/8938 didn't introduce the problem but made it visible.
- Fixes https://github.com/owncloud/web/issues/9042

fix: canCreate permission check in read-only shares

---

tests/e2e/cucumber/features/journeys/kindergarten.oc10.feature
tests/e2e/cucumber/features/journeys/kindergarten.ocis.feature
tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature
tests/e2e/cucumber/features/smoke/internalLink.ocis.feature
tests/e2e/cucumber/features/smoke/link.feature
tests/e2e/cucumber/features/smoke/notifications.oc10.feature
tests/e2e/cucumber/features/smoke/notifications.ocis.feature
tests/e2e/cucumber/features/smoke/reshare.feature
tests/e2e/cucumber/features/smoke/search.feature
tests/e2e/cucumber/features/smoke/share.oc10.feature
tests/e2e/cucumber/features/smoke/share.ocis.feature
tests/e2e/cucumber/features/smoke/spaces/internalLink.ocis.feature
tests/e2e/cucumber/features/smoke/spaces/memberExpiry.ocis.feature
tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature
tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature
tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature
tests/e2e/cucumber/features/smoke/tags.ocis.feature
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/support/api/share/share.ts
tests/e2e/support/objects/app-files/link/actions.ts
tests/e2e/support/objects/app-files/link/index.ts
tests/e2e/support/objects/app-files/share/collaborator.ts

This PR changes share-role as displayed in the UI
- Fixes https://github.com/owncloud/web/issues/8941
- Locally

[tests-only][full-ci]Refactor Share-role name in feature file according to webUI

---

changelog/unreleased/bugfix-initial-drive-listing
packages/web-app-files/src/composables/parentShare/useIncomingParentShare.ts
packages/web-runtime/src/pages/resolvePrivateLink.vue
packages/web-runtime/src/store/spaces.ts

This PR reduces the initial space preloading to only loading `personal` and `project` spaces. The `virtual/shares` space (share jail) is never needed and hence never loaded. The `mountpoint` spaces will be loaded on demand for now. This has some drawbacks (see comment in the code) but is necessary for performance tuning at the moment. Initially preloading the mountpoints might come back at a later point. Preloading the share jail makes no sense, as web doesn't use it, and will not be reintroduced.
Tuning performance and backend load, especially when a lot of users sign in at the same time.

[full-ci] fix: initial space preloading performance

---

tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature

This pr adds e2e test for admin to be able to manage the space create by other space admin users.
https://github.com/owncloud/web/issues/8763

[tests-only][full-ci]Added e2e test admin manage space created by other space admin

---

tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature
tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature

This PR refactors the order of steps,
Before::
```feature
And "Alice" logs in
And "Admin" assigns following roles to the users using API
| id    | role        |
| Alice | Space Admin |
```
Now::
```feature
And "Admin" assigns following roles to the users using API
| id    | role        |
| Alice | Space Admin |
And "Alice" logs in
```
Build:: https://drone.owncloud.com/owncloud/web/36331/10/12
- Fixes https://github.com/owncloud/ocis/issues/6431
- Locally
- :robot:

[full-ci] [tests-only] Refactored steps order

---

.drone.env

Bump `latest commit-id` on web.
https://github.com/owncloud/QA/issues/811

[tests-only][full-ci]Bump latest ocis commit on web

---

.drone.env

Bump latest ocis commit id to web `stable-7.0`
https://github.com/owncloud/QA/issues/811

[tests-only][full-ci]Bump latest ocis commit on web `stable-7.0`

---

.gitignore
dev/docker/traefik/configs/tls.yml
docker-compose.yml
vite.config.ts

Depends on #9150 
Until #9150 ocis generated tls certs and they were used by  vite and ocis.
So (at least in Chromium) one did not have to accept the certs twice.
Now certs are not autogenerated by ocis anymore and cannot be reused by vite.
Let's reestablish more or less the old behavior.
This PR makes traefik and vite the same certs, which are generated by the traefik container
- test case 1:
- test case 2:
- ...

Automate cert handling with traefik and vite

---

tests/e2e/cucumber/features/smoke/uploadResumable.ocis.feature
tests/e2e/support/objects/app-files/resource/actions.ts

The fix PR of this issue https://github.com/owncloud/web/issues/9080 has been made with this PR https://github.com/owncloud/web/pull/9141. The steps were comment until the feature has been fixed. This PR uncomment those steps for resume upload. Also upon upload resume the request `PATCH` is sent for uploading.
https://github.com/owncloud/web/issues/9080#issuecomment-1577883326

[tests-only][full-ci]Uncomment steps for resume upload and fix test code

---

tests/e2e/cucumber/features/smoke/spaces/downloadSpace.ocis.feature
tests/e2e/cucumber/steps/ui/accountMenu.ts
tests/e2e/cucumber/steps/ui/spaces.ts
tests/e2e/support/objects/account/actions.ts
tests/e2e/support/objects/account/index.ts
tests/e2e/support/objects/app-files/spaces/actions.ts
tests/e2e/support/objects/app-files/spaces/index.ts

This PR adds e2e tests for space download. There is no download feature in stable7.0. 
- space will be downloaded in compressed form as a download.tar file. Currently we check only the name of downloaded file
-  Should we check the  download.tar contains all resources of the downloaded space ❓ 
- Fixes <https://github.com/owncloud/ocis/issues/5014>
- locally

[tests-only][full-ci]Add e2e tests for space download

---

changelog/unreleased/enhancement-streamline-url-query-params
packages/web-app-admin-settings/src/components/AppTemplate.vue
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
packages/web-app-admin-settings/src/components/Users/UsersList.vue
packages/web-app-admin-settings/src/defaults/index.ts
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/composables/resourcesViewDefaults/useResourcesViewDefaults.ts
packages/web-app-files/tests/unit/components/AppBar/__snapshots__/AppBar.spec.ts.snap
packages/web-pkg/src/components/ViewOptions.vue
packages/web-pkg/src/composables/pagination/usePagination.ts
packages/web-pkg/src/composables/router/useRouteQueryPersisted.ts
packages/web-pkg/src/composables/sort/useSort.ts
packages/web-pkg/tests/unit/composables/pagination/usePagination.spec.ts

Pagination for admin-settings has been introduced recently. A weird-ish url query was used for the items per page: `admin-settings-items-per-page`. With this PR I'm streamlining that to be `items-per-page` in both the `admin-settings` and `files` apps respectively by enforcing a prefix for persisting the query value into the localStorage. A kind of prefix already existed before: it was named `routeName`, which is too specific, so I renamed it. As a result the items per page in the files app will be persisted into `oc-options_files_items-per-page` and the items per page in the admin-settings app will be persisted into `oc-options_admin-settings_items-per-page`.
Consistency in a) localStorage, b) url query and c) developer experience

feat: enforce prefix for persisted route query values

---

packages/web-integration-oc10/appinfo/info.xml

I've money-patched that for the release of tag v7.0.2 during the sign process.
-- it still said 6.0.0 all the time from first RC of 7.0.0 to 7.0.2
This should be done before taging, please, next time.

bump info.xml to 7.0.2 

---

docker-compose.yml
packages/web-pkg/src/services/client/client.ts
tests/drone/identifier-registration.yml
vite.config.ts

This removes the vite proxy and fixes adding CORS headers to oCIS in traefik.
This is in general a cleaner workaround as it assumes the server is fine and we don't have mismatches in urls with `:9200` and `:9201`
The downside is that we can't simply point vite to any oCIS server and it would still work just like it is right now, but ... I prefer to have companion imports working in vite.
This actually should just be fixed in oCIS and we wouldn't have to deal with it on any server anymore …
- workaround required because of https://github.com/owncloud/ocis/issues/5108
The occasion for this change is that companion tries to upload to port `:9201` from its container and it doesn't work. Instead of adding yet another hack to keep this working, we can instead just use traefik to add the headers …

Remove vite proxy

---

changelog/unreleased/enhancement-restyle-sharees
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/AutocompleteItem.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/AutocompleteItem.spec.ts

- Show `additionalInfo` for possible sharees in next line
- Hide share type is user or group
- Fixes https://github.com/owncloud/web/issues/9216

feat: restyle autocomplete item

---

changelog/unreleased/enhancement-add-batch-actions-to-search-result-list
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/components/FilesList/KeyboardActions.vue
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/FilesList/ResourceTiles.vue
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/composables/actions/files/useFileActionsCopy.ts
packages/web-app-files/src/composables/actions/files/useFileActionsDelete.ts
packages/web-app-files/src/composables/actions/files/useFileActionsDownloadArchive.ts
packages/web-app-files/src/composables/actions/files/useFileActionsPaste.ts
packages/web-app-files/src/composables/actions/helpers/useFileActionsDeleteResources.ts
packages/web-app-files/src/composables/filesList/useResourceRouteResolver.ts
packages/web-app-files/src/store/actions.ts
packages/web-app-files/src/store/mutations.ts
packages/web-app-files/src/store/state.ts
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/unit/components/FilesList/KeyboardActions.spec.ts
packages/web-app-files/tests/unit/components/FilesList/ResourceTable.spec.ts
packages/web-app-files/tests/unit/composables/actions/helpers/useFileActionsDeleteResources.spec.ts
packages/web-app-files/tests/unit/views/spaces/GenericSpace.spec.ts
packages/web-client/src/helpers/resource/functions.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-client/src/helpers/space/functions.ts
packages/web-pkg/src/composables/actions/types.ts
packages/web-pkg/src/composables/spaces/index.ts
packages/web-pkg/src/composables/spaces/useGetMatchingSpace.ts
packages/web-pkg/src/services/preview/previewService.ts
packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts

- test case 1:
- test case 2:
- ...

[full-ci] Search batch actions

---

changelog/unreleased/enhancement-cloud-import
packages/web-app-files/src/HandleUpload.ts
packages/web-app-files/src/helpers/resource/actions/upload.ts

Fixes the cloud import when importing files into a folder that has special characters in its name.
Follow-up for https://github.com/owncloud/web/pull/9150.

fix: cloud import into folder with special characters

---

packages/design-system/src/components/OcInfoDrop/OcInfoDrop.vue
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/components/AppBar/ViewOptions.vue
packages/web-app-files/src/components/Spaces/SpaceHeader.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/SpaceMembers.spec.ts.snap
packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.ts.snap

Some accessibility fixes
- `h1` tag in `GenericSpace` views was not filled
- fix `h`-tag cascading / order
- moved `div` meta element which is used for the left sidebar nav active item highlighting out of the `ul` (because `div`s  are not allowed as children of `ul`)

Some a11y fixes

---

docs/getting-started.md

Notified by @individual-it there was a typo in the dev docs by using `docker.host.internal` which should be `host.docker.internal` as all the other text refers to the latter.

[docs-only] Update getting-started.md

---

changelog/unreleased/enhancement-search-list-add-highligthed-file-content
package.json
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/search/sdk/list.ts
packages/web-client/src/webdav/constants/dav.ts
pnpm-lock.yaml

- Fixes https://github.com/owncloud/web/issues/9295
- test case 1:
- test case 2:
- ...

feat: search highlights 

---

tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/search/actions.ts

fixes: https://github.com/owncloud/web/issues/9312
The scenario is failing intermittently because of the timing issues while indexing with tika. Adding `1` sec pause before grabbing the elements for asserting seems to fix the issue.
Locally I ran scenario `201` times in headless mode and all the scenarios passed
```bash
201 scenarios (201 passed)
6432 steps (6432 passed)
```
Same in CI as well https://drone.owncloud.com/owncloud/web/36898/9/14
```bash
201 scenarios (201 passed)
6432 steps (6432 passed)
56m03.984s (executing steps: 55m46.368s)
```

[tests-only][full-ci]Fix e2e flaky tests for searching

---

packages/design-system/changelog/unreleased/bugfix-switch-columns-shared-with-me-view
packages/web-app-files/src/components/FilesList/ResourceTable.vue

Previously in the "Shared with me" view the column "Shared by" was hidden whereas the column "Shared with" was displayed on small screens and tablets (screen size <1200px). I switched the visibility of these two columns for this particular view.
- Fixes #9315
As a user, when browsing though files shared with me, it would be more interesting to see who shared a resource with me than with whom it was shared since "Shared with" is always the user himself (or a group he/she is part of). Previously the column "Shared by" was hidden whereas the column "Shared with" was displayed on small screens and tablets (screen size <1200px). With the proposed changes the visibility of these two columns are changed for the specified screen sizes for this particular view.
manual testing using the Chrome …

"Shared with me" view: switch columns displayed on small screens

---

changelog/unreleased/bugfix-uploading-to-folders-with-special-chars
packages/web-app-files/src/HandleUpload.ts
packages/web-app-files/src/helpers/resource/actions/upload.ts
packages/web-runtime/src/composables/upload/useUpload.ts

Fixes uploading resources to folders that contain special characters in their names. This also includes fixes for name conflict handling when running oC10 as server.
- Fixes https://github.com/owncloud/web/issues/9247

fix: uploading to folders that contain special characters

---

changelog/unreleased/bugfix-remember-location-after-token-invalidation
packages/web-runtime/src/pages/accessDenied.vue
packages/web-runtime/src/services/auth/authService.ts

Fixes an issue where token invalidation in the IDP would result in losing the current location. So logging in after token invalidation now correctly redirects to the page the user was before.
- Fixes https://github.com/owncloud/web/issues/9261

fix: remember location after token invalidation

---

changelog/unreleased/bugfix-authenticated-public-links-breaking-uploads
changelog/unreleased/enhancement-resolve-public-link-to-actual-location
packages/web-app-files/src/services/folder/loaderSpace.ts
packages/web-app-files/src/views/FilesDrop.vue
packages/web-app-files/src/views/spaces/DriveResolver.vue
packages/web-app-files/tests/unit/views/FilesDrop.spec.ts
packages/web-app-files/tests/unit/views/spaces/DriveResolver.spec.ts
packages/web-client/src/helpers/space/functions.ts
packages/web-pkg/src/composables/spaces/useGetMatchingSpace.ts
packages/web-runtime/src/pages/resolvePrivateLink.vue
packages/web-runtime/src/pages/resolvePublicLink.vue
packages/web-runtime/src/services/auth/authService.ts
packages/web-runtime/src/services/auth/publicLinkManager.ts
packages/web-test-helpers/src/mocks/store/runtimeModuleMockOptions.ts

Resolve public links to their actual location if the user has proper access to the resource (either via space or share). Also fixes an issue where opening public links in an authenticated context would prevent uploading resources.
- Fixes https://github.com/owncloud/web/issues/9296
- Fixes https://github.com/owncloud/web/issues/9298

[full-ci] feat: resolve public link to actual location if possible

---

tests/e2e/cucumber/features/smoke/fullTextSearch.ocis.feature
tests/e2e/cucumber/features/smoke/share.ocis.feature
tests/e2e/cucumber/steps/ui/public.ts
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts

This PR adds the step to close the file opened in the text editor, pdf viewer, and media viewer.
- Part of https://github.com/owncloud/web/issues/9157
- locally
- ci

[tests-only] [full-ci] file viewer editor close step addition

---

tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

after https://github.com/owncloud/web/pull/9389 I changed e2e test where I check that:
- viewer and editor cannot delete resource from space and manager can
- I cleaned up some unused code

[test-only] Change purge trashbin test

---

changelog/unreleased/enhancement-allow-local-storage-for-auth-token
docker-compose.yml
docs/getting-started.md
packages/web-pkg/src/configuration/manager.ts
packages/web-pkg/src/configuration/types.ts
packages/web-runtime/src/services/auth/userManager.ts
packages/web-runtime/src/store/config.ts

- Fixes https://github.com/owncloud/web/issues/9325
- test case 1:
- test case 2:
- ...

Use env var to determine session or local storage

---

.drone.star

Last week we removed the drone code to stop previous PR builds, and to cancel a build early when a single pipeline fails.
The remaining special CI feature that we have is the drone code that posts a comment to GitHub about a failing acceptance test pipeline. That no longer works because it needs a GitHub token with too many permissions, and we do not make that available to PRs.
This PR removes the GitHub comment code from the drone CI. The `earlyFail` setting is also removed, because there is nothing that uses it any more
This PR uploads the tracing and screenshot results to be available publicly
Part of: https://github.com/owncloud/QA/issues/820

[tests-only]Remove github comment from drone CI

---

package.json
sonar-project.properties

Includes the updated cloud importer. This is probably the last alpha before the first rc.

chore: bump web to v7.1.0-alpha.2

---

changelog/unreleased/enhancement-cloud-import
packages/web-runtime/src/components/UploadInfo.vue

Actions like pausing, resuming and retrying uploads is not (yet) supported by cloud imports, hence hide these.
Fixes https://github.com/owncloud/web/issues/9361

feat: hide upload info actions for cloud imports

---

package.json
pnpm-lock.yaml

Follow-up for https://github.com/owncloud/web/pull/9235. Includes some companion and UI fixes.

chore: bump oc-uppy to v3.12.3

---

packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap

We currently don't display all available batch actions in this view and the download batch action is only effective on one space ( due to restrictions in the backend archiver service). Therefore we disable the batch actions until we are 'feature-complete' 
- Fixes https://github.com/owncloud/web/issues/9384
- test case 1:
- test case 2:
- ...

Don't show batch actions in spaces overview

---

changelog/unreleased/enhancement-pop-up-redirect-blocker-notification
packages/web-app-files/src/composables/actions/files/useFileActions.ts
packages/web-pkg/src/composables/actions/useWindowOpen.ts

Fixes a regression from https://github.com/owncloud/web/pull/9383.

fix: gettext and store usage in `useWindowOpen` composable

---

packages/web-runtime/src/composables/upload/useUpload.ts

Fixes an issue where all tus upload requests would have the exact same X-Request-Id.
- Fixes https://github.com/owncloud/web/issues/9402

fix: generate unique request ids for tus upload requests

---

tests/e2e/support/objects/runtime/application.ts

Since oC10 is slower than oCIS, action to mark all notification as read might not have been successful during the test run. And in the test, we hadn't waited for mark-as-read action to complete before doing page reload. This should have cause the tests to fail with oC10.
So, this PR has added the wait after the mark-as-read action ( wait for notification spinner to get detached)
https://drone.owncloud.com/owncloud/web/37512/9/16
Flaky notification test with oc10
- local
- CI

[tests-only][e2e] Wait until readall notification action is done

---

changelog/unreleased/enhancement-absolute-date-file-versions
packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue

The pr adds a tooltip with absolute date on version’s relative date in version details
Users of CERNBox complain about the visibility of only relative date for versions. Showing absolute dates in tooltip would be consistent with "shared on" in shares and "modified" data
- test case 1:
- test case 2:
- ...

File versions tooltip with absolute date

---

changelog/unreleased/enhancement-add-error-log-to-upload-dialog
packages/design-system/src/components/OcNotificationMessage/OcNotificationMessage.vue
packages/web-runtime/src/components/UploadInfo.vue

- Fixes https://github.com/owncloud/web/issues/9430
- test case 1:
- test case 2:
- ...

Add error log to upload service

---

packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
packages/web-app-files/src/views/shares/SharedWithMe.vue
packages/web-app-files/src/views/shares/SharedWithOthers.vue
packages/web-pkg/package.json
packages/web-pkg/src/cern/components/CollapsibleOcTable.vue
packages/web-pkg/src/cern/composables/index.ts
packages/web-pkg/src/cern/composables/useGroupingSettings.ts
packages/web-pkg/src/cern/composables/useLoadTokenInfo.ts
packages/web-runtime/src/pages/resolvePublicLink.vue
pnpm-lock.yaml
vite.cern.config.ts

Adds a custom vite config for CERN. It overwrites some of our code paths to implement custom logic that only applies to CERN. Web can be built and run using this config via `pnpm build:w -c vite.cern.config.ts` or `pnpm vite -c vite.cern.config.ts`.
This PR already includes 2 things that have been overwritten:
* Collapsible table for the Shared with me/others views
* A custom composable for the `tokenInfo` request to avoid `404` errors.
- Fixes https://github.com/owncloud/web/issues/9424
- Fixes https://github.com/owncloud/web/issues/9310
- Part of https://github.com/owncloud/web/issues/9278

feat: add collapsible table and enable custom vite config for cern

---

oidc-callback.html
oidc-silent-redirect.html
vite.cern.config.ts
vite.config.ts

Adds `base` tag for CERN at build time.
- Fixes #9382
CERN does not want to implement this dynamically on server side like we do and prefers to have a build option.
Unfortunately I needed to move two `.html` files to our project root, I tried very hard but couldn't figure out a way to avoid this. It seems basically impossible to override the output path for `.html` files in vite.
In rollup there seems to be the possibility to provide multiple `input`/`output` values and make it work that way - but that does not work in vite. It might be possibly to use a renaming plugin for rollup/vite but that did not seem worth the trouble just for keeping two files out of the project root...
Done a local CERN build and checked base tag was available in all `.html` files.

Fix #9382: Inject base tag to all .html files

---

changelog/unreleased/enhancement-cloud-import
package.json
packages/web-app-importer/src/extensions.ts
packages/web-runtime/src/components/UploadInfo.vue
packages/web-runtime/src/composables/upload/useUpload.ts
packages/web-runtime/src/services/uppyService.ts
pnpm-lock.yaml

Fixes access tokens not being renewed when they expire during cloud imports.
- Fixes https://github.com/owncloud/web/issues/9445

fix: access token renewal during cloud imports

---

packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/composables/keyboardActions/index.ts
packages/web-app-files/src/composables/keyboardActions/useKeyboardActionsSearchTable.ts
packages/web-pkg/src/composables/keyboardActions/index.ts
packages/web-pkg/src/composables/keyboardActions/useKeyboardActions.ts

Core logic of keyboard actions moved to **useKeyboardActions** composable to web-pkg (this seems to make sense based on [repo-structure.md](https://github.com/owncloud/web/blob/master/docs/development/repo-structure.md)).
Single Keyboard Actions mount to a single element, if no element is filled, it's bound to the document.
Provides 2 functions. 
**bindKeyAction** which accepts the modifier key (based on ModifierKey enum), key (based on Key enum) and callback. 
These actions are saved and called if the event matches the modifier and key. The function returns the index key of action.
**removeKeyAction** allows to remove binded action allowing for dynamic adding / removing key actions.
**useKeyboardActionsSearchTable** is composable utilizing instance of useKeyboardActions, allowing for …

Keyboard Actions composables in Search Results

---

packages/web-app-files/src/HandleUpload.ts

Fixes running multiple, concurrent uploads at the same time. The issue was that the HandleUpload plugin did not only care about new files, but also files that have been processed by the plugin already. That caused multiple issues like folders trying to be created multiple times, wrong quota calculation etc.
- Fixes https://github.com/owncloud/web/issues/9462

fix: concurrent uploads

---

changelog/unreleased/enhancement-cloud-import
packages/web-app-importer/src/extensions.ts

Files that could not be uploaded stay in the Uppy file queue for retries, which caused the dashboard for the cloud importer to display such files instead of the actual importer UI. This PR simply disables the file display in the dashboard as we don't use it anyway.
- Fixes https://github.com/owncloud/web/issues/9469
- Fixes https://github.com/owncloud/web/issues/9473

fix: broken cloud import dashboard when upload failed before

---

changelog/unreleased/bugfix-merging-folders
packages/web-app-files/src/HandleUpload.ts

Skip folder creation when a folder already exists (= server responds with status code `405`).
- Fixes https://github.com/owncloud/web/issues/9461

fix: merging folders

---

changelog/unreleased/enhancement-cloud-import
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/components/AppBar/Upload/ResourceUpload.vue
packages/web-app-files/tests/unit/components/AppBar/Upload/ResourceUpload.spec.ts
packages/web-app-importer/src/extensions.ts
packages/web-app-importer/tests/unit/extensions.spec.ts
packages/web-runtime/src/services/uppyService.ts

Running other uploads or imports when a cloud import is running causes several issues, hence prevent it from happening.
- Fixes https://github.com/owncloud/web/issues/9454

fix: prevent uploads when a cloud import is running

---

changelog/unreleased/enhancement-button-styling
docs/theming/_index.md
packages/web-runtime/themes/owncloud/theme.json

Follow-up for https://github.com/owncloud/web/pull/9394.

docs: add new color tokens to the docs

---

changelog/unreleased/enhancement-scroll-to-created-folder
packages/web-app-files/src/components/FilesList/KeyboardActions.vue
packages/web-app-files/src/composables/actions/files/useFileActionsCreateNewFolder.ts
packages/web-app-files/src/composables/keyboardActions/useKeyboardActionsSearchTable.ts
packages/web-app-files/src/composables/scrollTo/useScrollTo.ts
packages/web-app-files/tests/unit/composables/actions/files/useFileActionsCreateNewFolder.spec.ts
packages/web-app-files/tests/unit/composables/scrollTo/useScrollTo.spec.ts

Upstreams a CERN commit by @elizavetaRa  which originates from before some major refactorings. It also reduces the `scrollToResource` arguments from a full resource where only the `id` would be used to a string/number.
- Fixes #7600 
- Fixes #7601

Feature/7600 - Scroll to newly created folder

---

packages/web-runtime/src/components/Topbar/TopBar.vue

I don't know why exactly, but sometimes the logo is not showing up after a page reload. Adding `width: 100%` via CSS seems to fix the issue.

fix: logo not showing

---

package.json
packages/design-system/package.json
packages/design-system/src/components/OcResourceSize/OcResourceSize.vue
packages/eslint-config/package.json
packages/web-app-files/src/components/FilesList/ListInfo.vue
pnpm-lock.yaml

~Wait for merge until IntelliJ properly supports TS 5:~ -> issues have been resolved with IntelliJ 2023.2.
* https://youtrack.jetbrains.com/issue/WEB-60063/IDE-shows-incorrect-errors-for-import-statements-with-Typescript-5.0-in-Vue-SFC
* https://youtrack.jetbrains.com/issue/WEB-57832
- test case 1:
- test case 2:
- ...

chore: TypeScript 5

---

.drone.env
packages/web-app-files/src/search/sdk/list.ts
packages/web-app-files/src/search/sdk/preview.ts
packages/web-runtime/package.json
pnpm-lock.yaml

Doesn't change anything about the logic, we just call another endpoint to be rfc compliant but this will call the same code in the backend 
- Fixes https://github.com/owncloud/web/issues/9367
- test case 1:
- test case 2:
- ...

Use spaces endpoint for search

---

packages/web-pkg/src/components/Spaces/ReadmeContentModal.vue

We've fixed the space description modal input, which was cut off at smaller screen sizes.
See https://github.com/owncloud/web/issues/9490
- Fixes https://github.com/owncloud/web/issues/9490

Bugfix: Space description edit modal is cut off vertically

---

packages/web-app-files/src/store/mutations.ts

- Fixes https://github.com/owncloud/web/issues/9152
- test case 1:
- test case 2:
- ...

Fix: Double items after moving a file with the same name

---

changelog/unreleased/bugfix-align-label
packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue

Previously in the label of the option "set expiration date" and “edit expiration date” for resources in the Shares sidebar was not in line. The same problem also applied to expiration date of members in Spaces. I removed the spacing between the icons and labels of the options below “set/edit expiration date” so that the design matches with the spacing of the same feature for sharing links. 
- Fixes #9323
Maintain consistent design in the UI
inspecting HTML code output, manual testing in Chrome 
Design Reference for width of spacing
Shares after modification
Spaces after modification
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Code changes

shared with action menu expiration date label alignment

---

.drone.star

Currently, this PR refactor drone to run the tika service on e2e-tests-ocis-1  pipeline. `fullTextSearch.feature` need the tika service. 
- Another way separate pipeline with respect to service needed
- Fixes https://github.com/owncloud/web/issues/9467
- Locally

[tests-only][full-ci] Run `tika` service on necessary pipelines

---

changelog/unreleased/bugfix-set-or-remove-expiration-date-on-group-share-not-possible
packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/__snapshots__/ExpirationDatepicker.spec.ts.snap

- Fixes https://github.com/owncloud/web/issues/8419
- test case 1:
- test case 2:
- ...

Fix set or remove expiration date on groups not possible

---

changelog/unreleased/enhancement-tags-form
packages/design-system/src/components/OcSelect/OcSelect.vue
packages/design-system/src/helpers/types.ts
packages/web-app-admin-settings/tests/unit/views/__snapshots__/Spaces.spec.ts.snap
packages/web-app-files/src/components/SideBar/TagsPanel.vue
packages/web-app-files/src/helpers/contextualHelpers.ts
packages/web-app-files/tests/unit/components/SideBar/TagsPanel.spec.ts
packages/web-pkg/src/configuration/manager.ts
packages/web-pkg/src/configuration/types.ts
tests/e2e/support/objects/app-files/resource/actions.ts

(from JIRA)
- If a Tags is already applied to a resource, it should not be suggested in the autosuggest drop menu. (as it can't be applied again - makes no sense) https://github.com/owncloud/web/issues/9363
- Tags should be autosaved
https://github.com/owncloud/web/issues/9356
- Tag should show tag-icon price-tag-3-fill (= same icon as in files list) https://github.com/owncloud/web/issues/9360
- Tag should have rounded croners like the tag in the files list https://github.com/owncloud/web/issues/9360
- Tag form should keep focus focus so that a user could enter multiple tags without having to use the mouse inbetween https://github.com/owncloud/web/issues/9362
- Add Contextual Helper next to "Add or edit Tags" https://github.com/owncloud/web/issues/9416
additional changes:
- backspace …

9356 9362 tag form improvements

---

packages/web-pkg/src/components/SearchBarFilter.vue

Moving translation to template keeps language and doesn't break "current folder"
- Fixes https://github.com/owncloud/web/issues/9444

Search Bar filter translation

---

.drone.star

Bump SonarCloud to avoid Java errors.

chore: bump sonarcloud to v5.0

---

packages/design-system/src/components/OcFilterChip/OcFilterChip.vue

This error only happened on master and when using `pnpm build:w`. We still need to figure out why CSS properties have different priorities when using `pnpm vite` and `pnpm build`.
Broken:
Fixed:

fix: filter chip design

---

package.json
packages/web-integration-oc10/appinfo/info.xml
sonar-project.properties

...and bump Web to `v7.0.3`. Fixes https://github.com/owncloud/web/issues/9535.

Add note for oC10 version pin

---

.drone.star

Backports https://github.com/owncloud/web/commit/3bf73afed02188e4f144797a361dd586827cc371 to `stable-7.1`.

chore: bump sonarcloud to v5.0 (backport from master)

---

tests/e2e/cucumber/features/smoke/search.feature

This PR updates the search feature to include the test for searching renamed and reshared resources.
Part of: https://github.com/owncloud/web/issues/9157

[tests-only] Add e2e tests for searching renamed and reshared resources

---

packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/components/SideBar/SideBar.vue
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-search/src/portals/SearchBar.vue
packages/web-pkg/package.json
packages/web-pkg/src/composables/keyboardActions/useKeyboardActions.ts
pnpm-lock.yaml

... and handle multiple registered actions for bound keys
- Fixes #9547
- Fixes #9554
With `event.preventDefault()` at the top of the handler all text input is blocked
cc @jacob-nv 
- test case 1:
- test case 2:
- ...

keyboardActions: Use event.preventDefault only when an action has been found

---

packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
packages/web-app-admin-settings/src/components/Users/UsersList.vue

command `pnpm check:style` is failing with:
```
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue(260,43): error TS2554: Expected 0 arguments, but got 1.
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue(458,43): error TS2554: Expected 0 arguments, but got 1.
packages/web-app-admin-settings/src/components/Users/UsersList.vue(307,43): error TS2554: Expected 0 arguments, but got 1.
 ELIFECYCLE  Command failed with exit code 2.
```
I have removed the unnecessary passing of arg in function `useKeyboardActions`. The change was introduced in https://github.com/owncloud/web/pull/9559
- Fixes https://github.com/owncloud/web/issues/9569

fix(type-check): remove unnecessary passing of arg in useKeyboardActions

---

changelog/unreleased/bugfix-pdf-loading-safari
packages/web-app-pdf-viewer/src/App.vue

Due to a Safari bug, we must not use `application/pdf` as object type when loading PDF files. See https://discussions.apple.com/thread/252247740 e.g.
- Fixes https://github.com/owncloud/web/issues/9483

fix: loading pdf files with Safari

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIFilesSearch/search.feature

We have coverage for search in e2e tests so some of the duplicate acceptance tests can be removed.
Part of: https://github.com/owncloud/web/issues/9157

[tests-only][full-ci]Remove acceptance tests related to search

---

changelog/unreleased/bugfix-pdf-loading-safari
changelog/unreleased/bugfix-set-or-remove-expiration-date-on-group-share-not-possible
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.vue
packages/web-app-files/src/helpers/contextualHelpers.ts
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/__snapshots__/ExpirationDatepicker.spec.ts.snap
packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap
packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/SpaceMembers.spec.ts.snap
packages/web-app-pdf-viewer/src/App.vue
packages/web-pkg/src/components/ItemFilter.vue
packages/web-pkg/src/components/SearchBarFilter.vue

Temporarily reverts all recent commits since `7.1.0-rc.5` to make sure we can tag the final `7.1.0` on the very same state as the rc. We will add those commits later again once `7.1.0` has been released (probably end this week - beginning next week).

chore: revert recent commits until 7.1.0-rc.5

---

.drone.star

The log tracing result was not ran in nightly for `e2e` tests. Since tests might be failed in nightly and the tracing would be more helpful for debugging. So this PR adds that step in `nightly` build as well.
Fixes https://github.com/owncloud/web/issues/9581

[tests-only][full-ci]Add log tracing result in nightly as well

---

.drone.star

The recently added `office-suites` app provider tests is not ran in nightly. Its better to run it at least in nightly since it is only ran with `full-ci` tag for the pull request. So this PR runs the test in every nightly.
Fixes https://github.com/owncloud/web/issues/9580

[tests-only][full-ci]Run office-suites app-provider tests in nightly as well

---

tests/e2e/support/objects/app-files/resource/actions.ts

In the kindergarten feature of e2e tests, the deletion steps fails some time when test is unable to record all the responses when the speed of  clicking and checking the response do not match. Due to this all the expected responses are not caught. So, this pr implements the deletion steps where the response checking is made ready before the clicking.
- Fixes https://github.com/owncloud/web/issues/9589
to solve the flaky issue in batch delete step in kindergarten feature of e2e tests.
- locally
- Ci

[tests-only] refactor delete step to be ready for response before clicking

---

.drone.env

This PR bumps latest ocis commit id.
Part of https://github.com/owncloud/QA/issues/824

[full-ci] [tests-only] Bump ocis commit id to latest

---

changelog/unreleased/bugfix-audio-video-loading-shared-with-me
packages/web-client/src/webdav/getFileUrl.ts

Fixes loading audio and video on the Shared with me page with the preview app. The problem was with a potential trailing slash in the download URL.
**Only merge after `7.1.0` has been released!**
- Fixes https://github.com/owncloud/web/issues/9593
- Fixes https://github.com/owncloud/enterprise/issues/5964

fix: loading audio and video on Shared with me page

---

changelog/unreleased/bugfix-internal-public-link-resolving
packages/web-app-files/src/views/spaces/DriveResolver.vue
packages/web-app-files/tests/unit/views/spaces/DriveResolver.spec.ts
packages/web-runtime/src/pages/resolvePrivateLink.vue

Fixes an issue where internally resolved public links instantly triggered the default file action. This behavior is not intended to work for public links if they resolve into an internal space.
**Only merge after `7.1.0` has been released!**
- Fixes https://github.com/owncloud/web/issues/9578

fix: internally resolved public links triggering default action

---

changelog/unreleased/enhancement-display-lock-information
packages/design-system/src/components/OcResource/OcResource.vue
packages/design-system/src/components/OcTile/OcTile.vue
packages/web-app-files/src/components/FilesList/ResourceTable.vue
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/composables/actions/files/useFileActionsDelete.ts
packages/web-app-files/src/composables/actions/files/useFileActionsMove.ts
packages/web-app-files/src/composables/actions/files/useFileActionsRename.ts
packages/web-app-files/tests/unit/composables/actions/files/useFileActionsDelete.spec.ts
packages/web-app-files/tests/unit/composables/actions/files/useFileActionsMove.spec.ts
packages/web-app-files/tests/unit/composables/actions/files/useFileActionsRename.spec.ts
packages/web-client/src/helpers/resource/functions.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-client/src/webdav/constants/dav.ts
packages/web-runtime/package.json
pnpm-lock.yaml
tests/acceptance/features/webUIWebdavLockProtection/move.feature

See https://github.com/owncloud/web/issues/6682
- Fixes https://github.com/owncloud/web/issues/6682

Implement file locking information

---

changelog/unreleased/enhancement-set-expiration-date-in-three-dots-menu
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js

- implements https://github.com/owncloud/web/issues/9493
- test case 1:
- test case 2:
- ...

9493 expiration date three dot menu

---

changelog/unreleased/enhancement-add-batch-actions-to-spaces
packages/design-system/src/components/OcResource/OcResource.vue
packages/design-system/src/components/OcTile/OcTile.vue
packages/web-app-files/src/components/AppBar/AppBar.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/composables/actions/files/useFileActionsCopy.ts
packages/web-app-files/src/composables/actions/files/useFileActionsDelete.ts
packages/web-app-files/src/composables/actions/files/useFileActionsDownloadArchive.ts
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/components/AppBar/__snapshots__/AppBar.spec.ts.snap
packages/web-app-files/tests/unit/components/Spaces/SpaceContextActions.spec.ts
packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceContextActions.spec.ts.snap
packages/web-app-files/tests/unit/composables/actions/files/useFileActionsCopy.spec.ts
packages/web-app-files/tests/unit/composables/actions/files/useFileActionsDelete.spec.ts
packages/web-app-files/tests/unit/composables/actions/files/useFileActionsDownloadArchive.spec.ts
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
packages/web-client/src/helpers/resource/types.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDelete.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDisable.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsEditQuota.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsRestore.ts
packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsDelete.spec.ts
packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsDisable.spec.ts
packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsEditQuota.spec.ts
packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsRestore.spec.ts

- Fixes https://github.com/owncloud/web/issues/9626
- test case 1:
- test case 2:
- ...

Add batch actions to spaces 

---

changelog/unreleased/enhancement-add-keyboard-navigation-to-spaces
changelog/unreleased/enhancement-add-keyboard-navigation-to-spaces-overview
packages/design-system/src/components/OcResource/OcResource.vue
packages/design-system/src/components/OcTile/OcTile.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/composables/keyboardActions/useKeyboardTableMouseActions.ts
packages/web-app-files/src/composables/keyboardActions/useKeyboardTableNavigation.ts
packages/web-app-files/src/views/spaces/Projects.vue

- Fixes https://github.com/owncloud/web/issues/9624
- test case 1:
- test case 2:
- ...

Add keyboard navigation to spaces

---

.drone.env
changelog/unreleased/enhancement-kql-search-query-language
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/tests/unit/components/Search/List.spec.ts
packages/web-app-search/src/portals/SearchBar.vue
packages/web-pkg/src/components/SearchBarFilter.vue
packages/web-pkg/src/composables/search/constants.ts
pnpm-lock.yaml

We've introduced [KQL](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference) as our default query language.
Previously we used our own simple language for queries which is now replaced by kql.
`sample.tx* Tags:important Tags:report Content:annual*`
becomes
`name:"sample.tx*" AND tag:important AND tag:report AND content:"annual*"`
by default KQL uses `AND` as property restriction and the query described above can also be formulated as follows
`name:"sample.tx*" tag:important tag:report content:"annual*"`
More advanced syntax like grouping combined with boolean property restriction is supported too
`(name:"sample*" name:"*txt") tag:important OR tag:report content:"annual*"`
* https://github.com/owncloud/ocis/pull/7212
* …

[full-ci] - use KQL as default search query language

---

changelog/unreleased/enhancement-add-project-space-filter
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/views/spaces/Projects.spec.ts
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap

We've added the option to search for spaces in the project space overview.
See https://github.com/owncloud/web/issues/9650
- Fixes https://github.com/owncloud/web/issues/9650

Implement filter for Project Spaces

---

changelog/unreleased/enhancement-display-lock-information
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ResourceDetails.spec.ts.snap
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.ts
packages/web-client/src/helpers/resource/functions.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-client/src/webdav/constants/dav.ts

See https://github.com/owncloud/web/issues/6682 (followup, added FileDetails)
- Fixes https://github.com/owncloud/web/issues/6682

Feat: Add additional locking information

---

packages/web-app-files/src/HandleUpload.ts
packages/web-app-files/src/helpers/resource/actions/upload.ts
packages/web-app-files/tests/unit/HandleUpload.spec.ts
packages/web-runtime/src/composables/upload/useUpload.ts

Massively improves the upload preparation time. Instead of setting file data on each file, we now accumulate all the data first and then set it in one batch via Uppy's `setState` method.
- Fixes https://github.com/owncloud/web/issues/9458
- Fixes https://github.com/owncloud/web/issues/9553

perf: upload preparation time

---

.drone.env
changelog/unreleased/enhancement-modal-buttons-same-width
packages/design-system/src/components/OcModal/OcModal.vue
packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap
packages/web-app-admin-settings/tests/unit/components/Users/__snapshots__/LoginModal.spec.ts.snap

See https://github.com/owncloud/web/issues/9641
- Fixes https://github.com/owncloud/web/issues/9641

Enhancement: Set OcModal Buttons to equal width

---

.drone.star
tests/e2e/support/objects/app-files/resource/actions.ts

The hard failure was due to previously web `master` while creating files would open then office suites files into a new tab but now all those files are created and opened in the same tab. So This PR adjusts the test code for it. but in web `stable-7.1` it is passing since it opens the new tab during the file creation.
https://github.com/owncloud/web/issues/9674

[tests-only][full-ci]Discard new tab wait for file creation and public link open

---

changelog/unreleased/enhancement-add-password-policy-compatibility
packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts

- test case 1:
- test case 2:
- ...

Add tests for basic password text input functionallity

---

changelog/unreleased/enhancement-add-password-policy-compatibility
packages/design-system/src/components/OcModal/OcModal.vue
packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts
packages/design-system/src/components/OcTextInput/OcTextInput.vue
packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
packages/design-system/src/components/_OcTextInputPassword/_OcTextInputPassword.vue
packages/design-system/src/helpers/types.ts
packages/web-pkg/src/services/passwordPolicy/passwordPolicy.ts

- test case 1:
- test case 2:
- ...

add more tests

---

changelog/unreleased/bugfix-tiles-view-accessibility
packages/design-system/src/components/OcCheckbox/OcCheckbox.vue
packages/design-system/src/components/OcTile/OcTile.vue
packages/design-system/src/components/OcTile/__snapshots__/OcTile.spec.ts.snap

- Fixes https://github.com/owncloud/web/issues/9633

fix: tiles view tab navigation (a11y)

---

changelog/unreleased/enhancement-app-templates
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
packages/web-pkg/src/composables/keyboardActions/useKeyboardActions.ts

Skip checking for disabled keyboard actions in text-editor app

---

packages/web-app-files/src/store/actions.ts

Committing mutation PRUNE_SHARES while removing files, will reset links and prevents displaying previously added links to files or directories under same name
- Fixes https://github.com/owncloud/web/issues/9538

prune shares while removing files

---

changelog/unreleased/bugfix-username-validation
packages/web-app-admin-settings/src/components/Users/CreateUserModal.vue

Added regex validation based on https://github.com/owncloud/ocis/blob/8cbf261568197a5494931357b5318d57b7134ae9/services/graph/pkg/service/v0/users.go#L742 to user creation
- Fixes https://github.com/owncloud/web/issues/9694

Username cannot include special characters

---

changelog/unreleased/enhancement-make-login-url-configurable
docs/getting-started.md
packages/web-pkg/src/configuration/manager.ts
packages/web-pkg/src/configuration/types.ts
packages/web-runtime/src/pages/accessDenied.vue
packages/web-runtime/src/store/config.ts
packages/web-runtime/tests/unit/pages/__snapshots__/accessDenied.spec.ts.snap
packages/web-runtime/tests/unit/pages/accessDenied.spec.ts

- Fixes https://github.com/owncloud/web/issues/9707
- test case 1:
- test case 2:
- ...

load login url from config

---

packages/web-app-admin-settings/src/components/AppTemplate.vue
packages/web-app-admin-settings/tests/unit/views/__snapshots__/Spaces.spec.ts.snap

Sidebar not displaying in web-app-admin-settings.
Removing `oc-flex-wrap` in AppTemplate fixed the issue
- Fixes https://github.com/owncloud/web/issues/9716

Sidebar admin settings not displayed <960px

---

changelog/unreleased/enhancement-add-password-policy-compatibility
packages/design-system/src/components/OcTextInput/OcTextInput.vue
packages/design-system/src/components/_OcTextInputPassword/_OcTextInputPassword.vue

- test case 1:
- test case 2:
- ...

Fix generate password doesnt reset banned password error, autofocus on password input doesn't work

---

changelog/unreleased/enhancement-add-password-policy-compatibility
packages/design-system/src/components/_OcTextInputPassword/_OcTextInputPassword.vue

- test case 1:
- test case 2:
- ...

Don't show password policy if password is just generated

---

tests/unit/config/jest.config.ts

Limit resource usage for Jest. Test don't seem to have increased because of this.
After we landed #9749 unit tests started failing for some reason, usually just one which got killed by the OS - apparently something needs more resources and limiting the concurrency and the amount of workers makes the builds succeed in Drone again. I haven't noticed any test time increase locally (with 64gb RAM and 32 cores, so I assume this won't slow down anyone else either)
- test case 1:
- test case 2:
- ...

Fix unit tests in Drone

---

tests/acceptance/features/webUIFiles/breadcrumb.feature
tests/acceptance/stepDefinitions/generalContext.js

Since there are some changes to webconfig file in PR https://github.com/owncloud/ocis/pull/7369 and we cannot update the webConfig during the test execution. So in this PR following scenario and its implementation are removed.
```feature
Scenario: Check breadCrumb for home folder
Given the property "homeFolder" of "options" has been set to "/0" in web config file
And user "Alice" has logged in using the webUI
Then breadcrumb for folder "0" should be displayed on the webUI
```
- Fixes https://github.com/owncloud/ocis/issues/7385
- locally
- CI

[tests-only][full-ci] Remove scenario which tries to update web config File

---

tests/e2e/cucumber/features/smoke/groupActions.feature
tests/e2e/cucumber/steps/ui/shares.ts
tests/e2e/support/objects/app-files/share/actions.ts
tests/e2e/support/objects/app-files/share/index.ts

related https://github.com/owncloud/ocis/issues/7363
added e2e test for

group action test

---

changelog/unreleased/enhancement-disabling-extensions
packages/web-pkg/src/composables/piniaStores/extensionRegistry.ts
packages/web-pkg/src/configuration/manager.ts
packages/web-pkg/src/configuration/types.ts
packages/web-runtime/src/container/application/classic.ts
packages/web-runtime/src/container/application/index.ts
packages/web-runtime/src/store/config.ts

Adds a config option `disabledExtensions` which enables disabling specific extensions via their id.
oCIS part for the config: https://github.com/owncloud/ocis/pull/7486
- Fixes https://github.com/owncloud/web/issues/8524

feat: introduce extension disabling via config

---

packages/web-pkg/src/composables/actions/files/useFileActionsCopy.ts

See https://github.com/owncloud/web/issues/9218 and https://github.com/owncloud/web/commit/1563e15a2a051833718eb4a662b3525e3f996278.
As discussed it makes no sense to implement an entry point for extensions here. We could add functionality for disabling specific file actions in the future. CERN would then need to implement a custom copy action which includes the added check. However, for now we decided this is the way to handle this.
- Fixes https://github.com/owncloud/web/issues/9218

[cern] feat: restrict copy action above space root

---

tests/e2e/support/objects/app-files/spaces/actions.ts

I have a red CI in ocis because we have differences in the MKCOL request url: 
ocis binary: with `/` at the end
ocis docker-compose:  without `/` at the end

[test-only] loosen the checking url in test

---

changelog/unreleased/enhancement-runtime-footer-portal
packages/web-runtime/src/layouts/Application.vue

Add a new portal into the application layout of runtime package. This portals allows developers to add new content below the app container. Because of this position, I chose the name footer for the portal. This change also makes the wrapper element of the container a flexbox. This is needed because the view itself has a limited height and this allows us to fit in the footer.
- refs #9768
Enable adding new actions in the embed mode without touching the layout of files app.
- test environment: local dev env
- test case 1: create a new element in files app and use portal to teleport it into the footer

feat: add new portal into runtime to include footer

---

changelog/unreleased/enhancement-nav-item-extension
packages/web-app-admin-settings/src/index.ts
packages/web-app-files/src/index.ts
packages/web-pkg/src/apps/types.ts
packages/web-pkg/src/composables/piniaStores/extensionRegistry.ts
packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
packages/web-runtime/src/components/SidebarNav/SidebarNavItem.vue
packages/web-runtime/src/layouts/Application.vue
packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNavItem.spec.ts.snap

Nav items can be registered with the new extension type `SidebarNavExtension`, which consists of a `AppNavigationItem` and optionally scopes (a list of app IDs where the nav item should show).
This PR als adds 2 new optional properties to the `AppNavigationItem` interface:
* `handler` - a click handler that get executes on click. It takes priority over a given route.
* `priority` - a number that determines the nav item's position.
Example extension:
```
{
id: 'com.github.owncloud.web.nav.foobar',
type: 'sidebarNav',
scopes: ['admin-settings', 'files'],
navItem: {
isActive: () => false,
enabled: () => true,
name: () => 'Foo Bar',
icon: 'close',
handler: () => {
console.log('some handler')
},
priority: 10
}
}
```
- Fixes https://github.com/owncloud/web/issues/9239

feat: add registering nav items via extension

---

.eslintrc.json
package.json
packages/eslint-config/index.js
packages/eslint-config/package.json
pnpm-lock.yaml

We want to make our preset package universally usable and jest seems to be too specific for that.

Move jest lint settings out of eslint-config package

---

.drone.star
docker-compose.yml

https://github.com/owncloud/ocis/pull/7477/files#diff-03814e90d6610960b5be6dacceaebdcbe234eafc6b504711dfbb199481c20fac
By default, auto-accept is set to true, so we don't need `FRONTEND_AUTO_ACCEPT_SHARES: "true"`

[test-only] delete unnecessary envs

---

changelog/unreleased/bugfix-webkit-copy-quicklinks
packages/web-pkg/src/composables/actions/files/useFileActionsCreateQuicklink.ts
packages/web-pkg/src/helpers/share/link.ts
packages/web-pkg/src/quickActions.ts
packages/web-pkg/tests/unit/helpers/share/link.spec.ts
pnpm-lock.yaml

copying quicklings was broken on webkit based browsers, this is fixed now.
* https://developer.apple.com/forums/thread/691873
* https://webkit.org/blog/10855/
- Fixeshttps://github.com/owncloud/web/issues/9166
... hmmmm, no bugs, happy dev 🤣
- unit tests

fix: webkit quicklinks copy for webkit

---

tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
tests/e2e/cucumber/steps/ui/links.ts
tests/e2e/cucumber/steps/ui/public.ts
tests/e2e/support/objects/app-files/link/actions.ts
tests/e2e/support/objects/app-files/link/index.ts

In this PR, added the step implementation for new buttons,
- Show/Hide Password
- Copy Password
- Generate Password
- https://github.com/owncloud/web/issues/9795

[tests-only][full-ci]added e2e test for show password, copy password and generate password buttons

---

changelog/unreleased/enhancement-embed-mode-actions
docs/embed-mode/_index.md
packages/web-app-files/src/components/EmbedActions/EmbedActions.vue
packages/web-app-files/src/components/FilesViewWrapper.vue
packages/web-app-files/tests/unit/components/EmbedActions/EmbedActions.spec.ts
packages/web-app-files/tests/unit/views/spaces/GenericSpace.spec.ts
packages/web-app-files/tests/unit/views/spaces/GenericTrash.spec.ts
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap

Add Cancel, Share and Select action into the files app available only when the mode is set to embed. All actions are ported below the app container.
- refs #9768
These new actions allow external developers to consume resources or links from within the embedded web ui.
- test environment: run the embed mode locally
- test case 1: check for cancel event
- test case 2: select resources and check for select event
- test case 3: select resources and check for share event

feat: add actions into the embed mode

---

changelog/unreleased/bugfix-display-path-on-resources
changelog/unreleased/enhancement-add-editors-to-application-menu
packages/design-system/src/components/OcResource/OcResource.vue
packages/web-pkg/src/components/Search/ResourcePreview.vue
packages/web-pkg/src/composables/folderLink/useFolderLink.ts
packages/web-pkg/tests/unit/components/Search/ResourcePreview.spec.ts
packages/web-pkg/tests/unit/components/Search/__snapshots__/ResourcePreview.spec.ts.snap
packages/web-pkg/tests/unit/components/__snapshots__/AppTopBar.spec.ts.snap

- test case 1:
- test case 2:
- ...

Remove unused code, rename share path

---

changelog/unreleased/bugfix-external-url-resolving
packages/design-system/src/components/OcNotificationMessage/OcNotificationMessage.vue
packages/web-app-external/src/App.vue
packages/web-app-external/tests/unit/app.spec.ts
packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
packages/web-pkg/src/composables/fileInfo/index.ts
packages/web-pkg/src/composables/fileInfo/useLoadFileInfoById.ts

External URLs coming from the `open-with-web` endpoint only have a file ID. This PR fixes resolving such URLs.
I basically copied most of the logic from our private link resolving, which works the same under the hood. Normally I would refactor this code and make it re-usable, but this solution is not applicable to master anyway because the external app handling has changed completely. This means we need to implement another (proper) solution on master anyways.
- Fixes https://github.com/owncloud/web/issues/9804
- Make sure you have OnlyOffice running
- Create a `docx` file
- Request an external URL for that file via `https://host.docker.internal:9200/app/open-with-web` and params `fileId=YOUR_ID` and `appName=OnlyOffice`
```
https://host.docker.internal:9200/external/open-with-web?appName= …
```

fix: resolving external URLs via file ID

---

changelog/unreleased/enhancement-last-modified-filter-chips
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/tests/unit/components/Search/List.spec.ts
packages/web-client/src/ocs/capabilities.ts
packages/web-pkg/src/composables/capability/useCapability.ts
packages/web-pkg/src/router/common.ts

added a "last modified" filter chip in search to narrow down results based on last modified date.
- Fixes https://github.com/owncloud/web/issues/9779
- test case 1:
- test case 2:
- ...

MVP - Modified Chip Filter

---

packages/web-client/src/index.ts
packages/web-client/src/webdav/index.ts

As the title says, make DavProperties and other things from web-client/webdav available to apps which need to import from `web-client` without path.

Make DavProperties available to apps

---

changelog/unreleased/enhancement-remove-settings-icon-from-search-bar
packages/design-system/src/components/OcSearchBar/OcSearchBar.spec.ts
packages/design-system/src/components/OcSearchBar/OcSearchBar.vue

see https://github.com/owncloud/web/issues/9664
we removed the search-icon on the left side and moved it to the right side as a replacement for the settings-icon.
- Fixes https://github.com/owncloud/web/issues/9664

Remove Settings-Icon from Search Bar

---

changelog/unreleased/enhancement-embed-folder-creation
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/unit/views/spaces/GenericSpace.spec.ts

Hide the create and upload actions in embed mode and provide a single create folder button instead.
- refs #9768
Since the embed mode provides only create folder action, it does not make sense to hide this in a dropdown.
- test case 1: open web in embed mode and see the correct action being displayed
- test case 2: open web in default mode and see the original actions still present

feat: show only folder create action in embed mode

---

changelog/unreleased/bugfix-duplicated-file-search-request
packages/web-app-files/src/components/Search/List.vue

fixes a bug where the search was sent unnecessarily twice.
- Fixes https://github.com/owncloud/web/issues/9787
- manual, unit and e2e

fix: duplicated file search request

---

changelog/unreleased/enhancement-delete-public-links-passwords-when-password-is-enforced
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
packages/web-client/src/helpers/resource/types.ts
packages/web-pkg/src/composables/actions/files/useFileActionsCreateQuicklink.ts
packages/web-pkg/src/composables/capability/useCapability.ts
packages/web-pkg/src/helpers/share/link.ts
packages/web-pkg/src/quickActions.ts
packages/web-pkg/tests/unit/helpers/share/link.spec.ts
packages/web-runtime/src/services/auth/abilities.ts

We've enabled to ability to allow delete passwords on public links, even if the password is enforced.
Therefore, the user needs respective permission, granted by the server.
This feature is only possible on public links that have the viewer role.
- Fixes https://github.com/owncloud/ocis/issues/7538
- test case 1:
- test case 2:
- ...

Allow to delete passwords on public links when password is enforced but permission is set

---

packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ResourceDetails.spec.ts.snap
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.ts.snap
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/RoleDropdown.spec.ts.snap
packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap
packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/__snapshots__/SpaceDetails.spec.ts.snap

Adds portal targets for file and space details. Also adds a share role icon next to the share role dropdown for CERN.
The removed CERN-code can now be implemented via extension instead (see https://github.com/cernbox/web-extensions/pull/25).
- Works towards https://github.com/owncloud/web/issues/9865 and https://github.com/owncloud/web/issues/9376

feat: add portal targets for file and space details

---

changelog/unreleased/bugfix-tags-not-editable-locked-files
docs/theming/_index.md
packages/web-app-files/src/components/SideBar/TagsPanel.vue
packages/web-pkg/src/composables/actions/files/useFileActionsShowEditTags.ts

- Fixes https://github.com/owncloud/web/issues/9789
- test case 1:
- test case 2:
- ...

Disable tags for locked files

---

changelog/unreleased/enhancement-delete-public-links-passwords-when-password-is-enforced
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/store/actions.ts
packages/web-pkg/src/helpers/share/link.ts

- Part of https://github.com/owncloud/ocis/issues/7538
- test case 1:
- test case 2:
- ...

Fix banned password error not shown in different modals 

---

changelog/unreleased/enhancement-search-term-linking
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/tests/unit/components/Search/List.spec.ts

With this its possible to search for multiple terms with the same type,
at the moment only the tag search benefits from it.
This makes it possible to search for multiple resources with different tags in one query.
The UI now empowers the user to perform advanced searches like:
* all resources with the tags `tag1` OR `tag2`
* all resources with the tags `tag1` OR `tag2` AND containing text `content`
as a rule of thumb, if a property appears multiple times (like `tag1` OR `tag2`)
the search combines the query with an `OR` and different keys are linked with an `AND`.
- Fixes https://github.com/owncloud/web/issues/9829
- Maybe!? https://github.com/owncloud/web/pull/9831
with the introduction of KQL in ocis the search syntax is defined by the MS spec, this brings web a step closer to it and …

enhancement: search query term linking

---

changelog/unreleased/bugfix-duplicated-file-search-request
packages/web-app-files/tests/unit/components/Search/List.spec.ts

add test to validate that search queries only emit a search request if one of the params changes
- tests for: https://github.com/owncloud/web/pull/9861
- tests for: https://github.com/owncloud/web/issues/9787
have query changes tested
- unit test

chore: change to the search query triggers only one request

---

changelog/unreleased/enhancement-location-picker
docs/embed-mode/_index.md
packages/web-app-files/src/components/EmbedActions/EmbedActions.vue
packages/web-app-files/tests/unit/components/EmbedActions/EmbedActions.spec.ts
packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/src/composables/embedMode/useEmbedMode.ts
packages/web-pkg/src/configuration/types.ts
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
packages/web-runtime/src/container/bootstrap.ts

Add a new query param called `embed-target` which is then added into the `configuration.options` object as `embedTarget`. When this parameter has value `location`, it switches the embed mode into location picker. In location picker, resources cannot be selected (checkboxes to do so are hidden), share action is hidden and select action emits the `currentFolder` instead.
- refs #9768
Enable picking location to e.g. upload files into instead of only selecting resources.
- test case 1: run web UI with `mode=embed&embed-target=location` query params
The empty space above files (where create and upload actions would be) will be filled with create folder action once #9853 is merged.

feat: add location picker into embed mode

---

changelog/unreleased/bugfix-search-list-result-rendering
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/tests/unit/components/Search/List.spec.ts
packages/web-app-search/src/views/List.vue
packages/web-app-search/tests/unit/views/List.spec.ts

When entering the search, it displayed the resources from the file list for a short moment,
this has now been fixed and the search always shows the loading spinner first.
After all results have been loaded from the server, the spinner disappears and the result is rendered.
- Fixes https://github.com/owncloud/web/issues/9790
the list should always be up to date and indicate the current state (loading) to the user
- unit tests
- manual testing
- e2e (ci)

fix: rendering of old/wrong set of resources in search list

---

changelog/unreleased/bugfix-tags-not-editable-locked-files
packages/web-pkg/src/composables/actions/files/useFileActionsShowEditTags.ts

Fixes an issue where the file list would break because of the tag action when no resources are loaded (yet).
- Regression of https://github.com/owncloud/web/pull/9873

fix: tag action when resoruces are not loaded yet

---

changelog/unreleased/enhancement-enable-dark-theme-on-importer
packages/web-app-importer/src/extensions.ts

- Fixes https://github.com/owncloud/web/issues/9452
- test case 1:
- test case 2:
- ...

enable dark theme on uppy importer

---

changelog/unreleased/enhancement-reorganize-new-menu
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts
packages/web-app-files/tests/unit/components/AppBar/__snapshots__/CreateAndUpload.spec.ts.snap
packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts

See https://github.com/owncloud/web/issues/9846
- Fixes https://github.com/owncloud/web/issues/9846

Organize "New" menu | Add default extension to menu item

---

tests/e2e/cucumber/features/smoke/copyMove.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

In this PR, steps are implemented for copying and moving multiple resources at once using different methods: `dropdown-menu, keyboard, batch-action, drag-drop, drag-drop-breadcrumb`.
- https://github.com/owncloud/ocis/issues/7363

[tests-only][full-ci]add test for copy and move multiple files at once

---

packages/web-pkg/src/components/AppTemplates/AppWrapper.vue

We noticed this error in the ocis pipeline: https://drone.owncloud.com/owncloud/ocis/28475/40/12. For some reason it didn't fail in Web...
- Regression from https://github.com/owncloud/web/pull/9891.

fix: closing editors on search result page

---

changelog/unreleased/enhancement-app-banner
docs/theming/_index.md

- Fixes https://github.com/owncloud/web/issues/9836
- test case 1:
- test case 2:
- ...

added docs for app banner

---

changelog/unreleased/bugfix-keep-both-conflict
packages/web-app-files/src/helpers/resource/actions/upload.ts

In case of /folder/folder where result should be /folder/folder (1) to resolve conflict, regex updated URL to /folder(1)/folder
- Fixes https://github.com/owncloud/web/issues/9158

Keep both conflict

---

vite.cern.config.ts
vite.config.ts

This allows us to run in debug mode in our config behind nginx (removes ssl which is handled by nginx, basically).
I've also deleted some code from your main config file... This code was not being used anywhere, but I don't know if you use it to check if accessing the config file succeeds while you build. Either way, you would notice it as soon as you launch web, as it will try to load the config either way, no?
If not, I can download our config by passing the env var with a diff url.

Vite serve cern

---

docs/getting-started.md
packages/web-app-external/src/App.vue
packages/web-app-external/tests/unit/app.spec.ts
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
packages/web-pkg/src/configuration/manager.ts
packages/web-pkg/src/configuration/types.ts

Open non-personal files in "view" (readonly) mode when enabled via config: `editor.openAsPreview`.
Based on the logic implemented by CERN this currently is the case for all files in shares and public links.
- Fixes https://github.com/owncloud/web/issues/9255

web-app-external: view mode

---

tests/drone/check-oCIS-cache.sh

Check-ocis-cache script doesn't catch error.This PR fixes that issue
- test case 1:
- test case 2:
- ...

[tests-only][full-ci]fix ocis-cache-build

---

.drone.env
changelog/unreleased/enhancement-share-and-favorite-permission-checks
packages/web-app-files/src/components/FilesList/QuickActions.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/index.ts
packages/web-client/src/helpers/resource/functions.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-client/tests/unit/helpers/resource/functions.spec.ts
packages/web-pkg/src/components/AppBar/AppBar.vue
packages/web-pkg/src/composables/actions/files/useFileActionsCreateQuicklink.ts
packages/web-pkg/src/composables/actions/files/useFileActionsFavorite.ts
packages/web-pkg/src/composables/actions/files/useFileActionsShowShares.ts
packages/web-pkg/src/quickActions.ts
packages/web-runtime/src/services/auth/abilities.ts
packages/web-runtime/tests/unit/services/auth/abilities.spec.ts

Add and enforce permission checks for creating shares and favorites. Note that you need a current oCIS docker image for testing.
- Works towards https://github.com/owncloud/web/issues/9381

feat: add permission checks for creating shares and favorites

---

.drone.env
changelog/unreleased/enhancement-add-file-media-filter-chip
changelog/unreleased/enhancement-add-file-type-filter-chip
packages/web-app-files/src/components/Search/List.vue
packages/web-client/src/ocs/capabilities.ts
packages/web-pkg/src/composables/capability/useCapability.ts
packages/web-pkg/src/router/common.ts
tests/e2e/cucumber/features/smoke/search.feature
tests/e2e/cucumber/steps/ui/search.ts
tests/e2e/support/objects/app-files/search/actions.ts
tests/e2e/support/objects/app-files/search/index.ts

**The capability for mimeTypes needs to be enabled OR find** `unref(modifiedDateCapability).enabled` **and add a** `!`
**Backend is not on master yet, needs Romans PR (https://github.com/owncloud/ocis/pull/7602) as backend**
See https://github.com/owncloud/web/issues/9780
- Fixes https://github.com/owncloud/web/issues/9780

Add "File type" filter Chip

---

packages/web-app-files/src/HandleUpload.ts
packages/web-app-files/tests/unit/HandleUpload.spec.ts

Fix regression from https://github.com/owncloud/web/pull/9721. We accidentally disabled the quota check for a user's own personal space in that PR.

fix: quota check when uploading files to own personal space

---

changelog/unreleased/enhancement-add-file-media-filter-chip
packages/web-pkg/src/components/ItemFilter.vue
packages/web-pkg/tests/unit/components/ItemFilter.spec.ts
packages/web-pkg/tests/unit/components/__snapshots__/ItemFilter.spec.ts.snap

See https://github.com/owncloud/web/issues/9938
- Fixes https://github.com/owncloud/web/issues/9938

Bugfix: Keep ItemFilter sortorder

---

changelog/unreleased/bugfix-respect-details-query
packages/web-runtime/src/pages/resolvePrivateLink.vue
packages/web-runtime/tests/unit/pages/resolvePrivateLink.spec.ts

Properly respect the `details` query on private links when `openLinksWithDefaultApp` is enabled. This fixes an issue where the sidebar would not open despite requesting to do so.
- Fixes https://github.com/owncloud/web/issues/9868

fix: respect details query on private links

---

.drone.star
dev/docker/ocis/password-policy-banned-passwords.txt
docs/testing/testing.md
packages/web-app-external/src/App.vue
tests/drone/banned-passwords.txt
tests/e2e/cucumber/features/smoke/app-provider/officeSuites.feature
tests/e2e/cucumber/features/smoke/internalLink.feature
tests/e2e/cucumber/features/smoke/link.feature
tests/e2e/cucumber/features/smoke/share.feature
tests/e2e/cucumber/features/smoke/spaces/internalLink.feature
tests/e2e/cucumber/features/smoke/spaces/participantManagement.feature
tests/e2e/cucumber/features/smoke/spaces/project.feature
tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
tests/e2e/cucumber/steps/ui/links.ts
tests/e2e/cucumber/steps/ui/public.ts
tests/e2e/cucumber/steps/ui/shares.ts
tests/e2e/support/objects/app-files/link/actions.ts
tests/e2e/support/objects/app-files/link/index.ts
tests/e2e/support/objects/app-files/share/actions.ts
tests/e2e/support/objects/app-files/share/index.ts
tests/e2e/support/objects/app-files/spaces/actions.ts
tests/e2e/support/objects/app-files/spaces/index.ts
tests/e2e/support/objects/app-files/utils/editor.ts
tests/e2e/support/store/user.ts

ToDo: get rid of:
- all warnings related `pnpm lint`
- page.locator.isVisible() - flaky https://playwright.dev/docs/api/class-locator#locator-is-visible 
- deprecated methods like `page.waitForNavigation()`

[full-ci] change e2e test for enforce pass

---

changelog/unreleased/enhancement-create-shortcuts
packages/web-pkg/src/components/CreateShortcutModal.vue

- Fixes https://github.com/owncloud/web/issues/9963
- Fixes https://github.com/owncloud/web/issues/9969
- test case 1:
- test case 2:
- ...

Set first url input item active and highlight search results 

---

packages/web-runtime/src/services/auth/userManager.ts

We're not relying on the userinfo data in web. Instead we fetch the user from OCS or graph and use all that information. Hence it's a good idea to save one request by disabling fetching the oidc userinfo.
cc and thank you @butonic who brought this idea up.
Just explorative testing so far. Let's see what our e2e tests have to say. Edit: looks good to CI. ✅

perf: disable fetching oidc userinfo

---

changelog/unreleased/enhancement-embed-mode-actions
changelog/unreleased/enhancement-location-picker
docs/embed-mode/_index.md
packages/web-app-files/src/components/EmbedActions/EmbedActions.vue
packages/web-app-files/tests/unit/components/EmbedActions/EmbedActions.spec.ts
packages/web-app-files/tests/unit/views/spaces/GenericSpace.spec.ts
packages/web-pkg/src/composables/embedMode/useEmbedMode.ts
packages/web-pkg/src/configuration/types.ts
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/store/config.ts
packages/web-runtime/tests/unit/components/Topbar/TopBar.spec.ts
packages/web-runtime/tests/unit/container/bootstrap.spec.ts

We have switched to using `postMessage` method in the embed mode instead of emitting custom events. This mitigates the issue when running the embed mode on different origin blocked the access to the `dispatchEvent` method.
Solve issues with forbidden access when hosting the iframe on different origin.
- test case 1: run the embed mode and check the correct events being emitted

Use postMessage in embed mode instead of custom events

---

.drone.env
changelog/unreleased/enhancement-additional-languages
packages/web-runtime/l10n/Makefile
packages/web-runtime/src/defaults/languages.ts
packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
tests/e2e/cucumber/features/smoke/languageChange.feature

Adds additional languages to the web ui, namely those which have good translation coverage in transifex + swedish as requested by a community member. Removed Galician, as it only had 14%, seems rather unmaintained.
Note: please use up to date ocis image to test this. There was a change in the settings service to make saving these preferred language values possible...
- Fixes https://github.com/owncloud/web/issues/10007
Make community happy.

Add available languages

---

changelog/unreleased/enhancement-shared-by-filter
packages/web-app-files/src/views/shares/SharedWithMe.vue
packages/web-app-files/tests/unit/views/shares/SharedWithMe.spec.ts

Adds a "Shared by"-filter to the received shares on the "Shared with me"-page. Also fixes a bug where the share type labels were empty inside the "Share type"-filter and ensures to always show it.
- Fixes https://github.com/owncloud/web/issues/10013
- Fixes https://github.com/owncloud/web/issues/10027

feat: add shared by filter on 'Shared with me'-page

---

changelog/unreleased/enhancement-duplicate-space
packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue
packages/web-app-files/src/components/Spaces/SpaceContextActions.vue
packages/web-pkg/src/components/AppBar/AppBar.vue
packages/web-pkg/src/composables/actions/spaces/index.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDuplicate.ts
packages/web-pkg/src/helpers/resource/conflictHandling/conflictUtils.ts
packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsDuplicate.spec.ts

- Fixes https://github.com/owncloud/web/issues/10016
- test case 1:
- test case 2:
- ...

Duplicate space

---

packages/web-runtime/src/pages/oidcCallback.vue

Due to a recent change in the oidc route names the silent sign-in failed after token expiry.

fix: silent sign-in to avoid permanent logout

---

packages/design-system/src/components/OcSelect/OcSelect.vue
tests/e2e/support/objects/account/actions.ts
tests/e2e/support/objects/app-admin-settings/groups/actions.ts
tests/e2e/support/objects/app-admin-settings/spaces/actions.ts
tests/e2e/support/objects/app-admin-settings/users/actions.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/share/collaborator.ts
tests/e2e/support/objects/app-files/spaces/actions.ts

Do not open the oc-select dropdown when oc-select gets focus, only on enter or mouse click.
When vue-select gets focus, it immediately opens its dropdown. This is very odd in a formular, where the first item is a oc-select and the dropdown opens on page load (or when a modal opens). Apart from that it behaves differently from native select boxes and usually it's a good idea to stick as closely as possible to native behaviors if native components can't be used for whatever reason.
- test case 1:
- test case 2:
- ...

Do not open OcSelect Dropdown on focus

---

.drone.star
Makefile
Makefile.release

Brings the CI feature to this pipeline: https://github.com/owncloud/web/pull/9823. This is needed to successfully build and publish the new release `v7.1.2`.

ci: use pnpm version defined in package.json

---

changelog/unreleased/enhancement-new-file-event-handling
packages/web-runtime/src/container/bootstrap.ts

Resources that were upserted via the SSE post-processing event always had `/` as path, which is incorrect. It should be the current folder's path and the resource name concatenated.
This lead to some issues with file duplicates in the files list.
- Fixes https://github.com/owncloud/web/issues/10045

fix: sse resource upsert

---

.drone.star

Follow-up for https://github.com/owncloud/web/pull/10052.

ci: add missing NO_INSTALL param in ci build step

---

changelog/unreleased/enhancement-provide-neutral-file-icons
packages/design-system/src/helpers/resourceIconMapping.json
packages/design-system/src/tokens/ods/color.yaml

Followup for https://github.com/owncloud/web/pull/9911 - adding the docxf icon mapping and adjusting colors.
- Fixes https://github.com/owncloud/web/issues/9847 again

feat: add docxf icon mapping and fix document icon colors

---

changelog/unreleased/enhancement-upload-folder-tree-creation
changelog/unreleased/enhancement-upload-preparation-time
packages/web-app-files/src/HandleUpload.ts
packages/web-app-files/tests/unit/HandleUpload.spec.ts
packages/web-client/src/webdav/createFolder.ts

Speeds up the folder tree creation during upload by running the process asynchronously and by saving up PROPFIND requests on nested folders.
In my test with a folder including 155 sub folders the time for creating those decreased from 20-30 seconds to 5-7. That's still quite a bit, but most likely as good as it can get when doing this on the client-side.
- refs https://github.com/owncloud/web/issues/9817

perf: speed up folder tree creation during upload

---

changelog/unreleased/enhancement-show-webdav-information-in-details
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/store/getters.ts
packages/web-app-files/src/store/mutations.ts
packages/web-app-files/src/store/state.ts
packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ResourceDetails.spec.ts.snap
packages/web-pkg/src/components/AppBar/AppBar.vue
packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/__snapshots__/SpaceDetails.spec.ts.snap
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/index.ts
packages/web-runtime/src/pages/account.vue
packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
packages/web-runtime/tests/unit/pages/account.spec.ts
packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts

- Fixes https://github.com/owncloud/web/issues/9714
- test case 1:
- test case 2:
- ...

Webdav details followup

---

.drone.star

This PR downgrades the version of the `wopiserver` for the e2e app-provider tests since the upgraded version was failing in nightly CI.
https://github.com/owncloud/web/issues/10060

[tests-only][full-ci]Down grade the `wopiserver` version for `app-provider` e2e tests

---

changelog/unreleased/enhancement-embed-mode-actions
packages/web-app-files/src/components/FilesList/QuickActions.vue
packages/web-app-files/tests/unit/components/FilesList/QuickActions.spec.ts

We decided to hide the quick actions in embed mode because the user is supposed to work with the actions provided by the embed mode. No need to clutter the UI with unnecessary stuff.

feat: hide quick actions for files in embed mode

---

changelog/unreleased/bugfix-logout-page-after-token-expiry
packages/web-runtime/src/services/auth/authService.ts

Fixes wrongly showing the logout page after revisiting Web with an expired token. Users now get redirected to the login page instead.
- Fixes https://github.com/owncloud/web/issues/10063
- Fixes https://github.com/owncloud/web/issues/9715

fix: showing the logout page after token expiry

---

changelog/unreleased/enhancement-default-link-permissions
packages/web-app-files/src/components/EmbedActions/EmbedActions.vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/Links/CreateQuickLink.vue
packages/web-app-files/tests/unit/components/EmbedActions/EmbedActions.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/FileLinks.spec.ts
packages/web-pkg/src/composables/capability/useCapability.ts
packages/web-pkg/src/helpers/share/link.ts
packages/web-pkg/tests/unit/helpers/share/link.spec.ts

When creating a new link, Web now respects the default permissions coming from the server.
Needs a reva update in oCIS for Web to properly read the config from the server. Without, Web just defaults to `1` for the permission (the same as the server will).
- Fixes https://github.com/owncloud/web/issues/9919

feat: respect default link permissions

---

packages/web-app-files/src/store/actions.ts
packages/web-app-files/tests/unit/store/actions.spec.ts

Previously, creating links was coupled to the highlighted file in some ways. As a result, share types were only updated for the highlighted file and the determination whether the link is direct or indirect was done by checking the highlighted file. This is bad because the highlighted file is always the first selected file, though we want to be able to create links for multiple selected files in the future.
This change retrieves the actual file from the store instead of using the highlighted file.

feat: decouple creating links from the highlighted file

---

changelog/unreleased/bugfix-disable-expiration-date-alias-link
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Links/DetailsAndEdit.spec.ts

See https://github.com/owncloud/web/issues/9923
- Fixes https://github.com/owncloud/web/issues/9923

Disable expiration date for alias link

---

packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue

Changes the check for internal links in the `DetailsAndEdit` component so it doesn't compare objects against each other. That always feels unstable and broke our unit tests recently.
- Fixes https://github.com/owncloud/web/issues/10087

fix: checking for internal links

---

packages/design-system/src/components/OcModal/OcModal.vue
packages/web-runtime/src/App.vue
packages/web-runtime/src/store/modal.ts

The predefined actions are hardly customizable, which can be a problem when using a custom component that also needs custom actions in a modal. By hiding the modal's actions the custom component can take care of it by itself.

feat: allow disabling the actions of a modal

---

changelog/unreleased/enhancement-add-auth-delegation
docs/embed-mode/_index.md
packages/web-app-files/tests/unit/components/EmbedActions/EmbedActions.spec.ts
packages/web-app-files/tests/unit/views/spaces/GenericSpace.spec.ts
packages/web-pkg/src/composables/embedMode/useEmbedMode.ts
packages/web-pkg/src/configuration/manager.ts
packages/web-pkg/src/configuration/types.ts
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
packages/web-pkg/tests/unit/composables/embedMode/useEmbedMode.spec.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/pages/oidcCallback.vue
packages/web-runtime/src/router/setupAuthGuard.ts
packages/web-runtime/src/services/auth/authService.ts
packages/web-runtime/src/services/auth/userManager.ts
packages/web-runtime/src/store/config.ts
packages/web-runtime/tests/unit/components/Topbar/TopBar.spec.ts
packages/web-runtime/tests/unit/pages/oidcCallback.spec.ts
packages/web-runtime/tests/unit/services/auth/authService.spec.ts

Add option to delegate authentication to parent application when Web is included in Embed mode. The automatic token refresh is disabled in such configuration and token is set/updated via events.
- Fixes #10073
- fixes #10072
Do not force the user to authenticate twice when the parent application already has valid access_token.
- test case 1: open web in embed mode with delegated authentication and manually post an existing access_token with `postMessage` method

feat: delegate auth in embed mode

---

changelog/unreleased/enhancement-show-hide-shares
packages/web-pkg/src/components/FilesList/ResourceTable.vue

This is only a temporary fix until those shares can be accessed properly, which will be possible with the new sharing NG. No unit tests added because of that.
- Fixes https://github.com/owncloud/web/issues/10094

fix: disable router-links for pending and declined shares

---

changelog/unreleased/bugfix-in-here-search
packages/web-app-files/src/components/Search/List.vue
packages/web-app-search/src/portals/SearchBar.vue

Requirement for "term" has been removed from forcing scope.
Ensuring that "scope" filter is moved to the end of search query, which removes possibility of query starting with "AND"
https://github.com/owncloud/ocis/issues/7812#issuecomment-1828252212
- Fixes https://github.com/owncloud/web/issues/9970

Allowing in-here search with empty query

---

docs/embed-mode/_index.md

[docs-only] docs: add hint not to pass bearer string in embed mode access token

---

changelog/unreleased/enhancement-support-mandatory-filter-while-listing-users
docs/getting-started.md
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
packages/web-app-admin-settings/src/components/Groups/SideBar/MembersPanel.vue
packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersPanel.vue
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
packages/web-app-admin-settings/src/components/Users/UsersList.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
packages/web-app-admin-settings/tests/unit/components/Users/UsersList.spec.ts
packages/web-app-admin-settings/tests/unit/views/Users.spec.ts
packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
packages/web-app-files/src/views/shares/SharedWithMe.vue
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/src/views/trash/Overview.vue
packages/web-app-search/src/portals/SearchBar.vue
packages/web-client/src/generated/api.ts
packages/web-pkg/src/components/CreateShortcutModal.vue
packages/web-pkg/src/components/ItemFilter.vue
packages/web-pkg/src/configuration/manager.ts
packages/web-pkg/src/configuration/types.ts
packages/web-runtime/src/App.vue
packages/web-runtime/src/store/config.ts

Don't load users initially and requires active filters if config var `WEB_OPTION_USER_LIST_REQUIRES_FILTER`is set to true
- Fixes https://github.com/owncloud/web/issues/10088
- test case 1:
- test case 2:
- ...

Mandatory filtering implementation

---

changelog/unreleased/bugfix-skip-token-reuse-in-embed-mode
changelog/unreleased/enhancement-add-auth-delegation
packages/web-runtime/src/pages/oidcCallback.vue
packages/web-runtime/src/services/auth/authService.ts
packages/web-runtime/tests/unit/services/auth/authService.spec.ts

When Web is included in an iframe in embed mode with delegated authentication, skip reusing the old token. The parent application is responsible for handling the token and we do not really care about reloading there which the reuse seems to be intended to handle. If the old token is reused, it can lead to an error when fetching user with expired token. That will then lead to a redirect to access denied page once the delegated access_token is received.
Fixing a bug which leads to access denied page.
- test case 1: embed web in an iframe with delegated auth, postMessage with valid token, wait for the token to expire, remove the iframe, build the iframe again with expired token, postMessage with new valid token

fix: skip reusing old token in embed mode with delegated auth

---

.drone.star

use natsjs registry in ocis instead of mdns
- Closes https://github.com/owncloud/web/issues/9687

[tests-only][full-ci] use nats registry in ocis

---

packages/web-client/src/helpers/resource/functions.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-client/src/webdav/constants/dav.ts

Load `audio` and `location` metadata in propfinds.
- Depends on https://github.com/owncloud/ocis/pull/7898
I want to make metadata available to extensions, especially sidebar panels (c.f. #10111)
MS Graph API returns `audio` and `location` facets as soon as they are available for a `driveItem` - assuming oCIS wants to stay compatible with that and that we are going to switch to graph api at some point, I think we don't need to add complexity for loading these props only on demand.

feat: retrieve audio and location metadata

---

packages/web-app-files/tests/unit/components/SideBar/Shares/FileLinks.spec.ts
packages/web-pkg/tests/unit/components/CreateLinkModal.spec.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCopyQuicklink.spec.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateLink.spec.ts

Follow-up after https://github.com/owncloud/web/pull/10104.

test: add unit tests for create link modal

---

changelog/unreleased/enhancement-duplicate-space
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDuplicate.ts
packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsDuplicate.spec.ts

Spaces are listed as regular resources on the projects page, hence we need to make sure to insert duplicated spaces as such.
- Fixes https://github.com/owncloud/web/issues/10124

fix: selection after space duplication

---

packages/design-system/src/components/OcRadio/OcRadio.vue

Fixes the known issue with `pnpm vite` and `pnpm build` prioritizing CSS coming from the ODS differently.
before -> after

fix: radio background color

---

changelog/unreleased/enhancement-manage-tags-in-details-panel
packages/web-app-files/src/components/SideBar/Details/TagsSelect.vue
packages/web-app-files/tests/unit/components/SideBar/TagsSelect.spec.ts
tests/e2e/support/objects/app-files/resource/actions.ts

Remove open indicator caret and enhance no options text 
- Fixes https://github.com/owncloud/web/issues/10115
- Fixes https://github.com/owncloud/web/issues/10114
- test case 1:
- test case 2:
- ...

Remove caret and enhance no options text

---

tests/e2e/cucumber/steps/api.ts
tests/e2e/support/api/keycloak/user.ts
tests/e2e/support/api/provision/user.ts
tests/e2e/support/objects/runtime/session.ts

In this PR, assigning the role to the users using API is done through keycloak.
Part of: https://github.com/owncloud/web/issues/9904

[tests-only][full-ci]assign role to user through keycloak

---

changelog/unreleased/bugfix-spaces-files-list-previews-cropped
changelog/unreleased/bugfix-spaces-overview-tile-previews-zoomed-in
packages/web-app-files/src/components/Spaces/SpaceHeader.vue
packages/web-app-files/src/composables/actions/spaces/useSpaceActionsUploadImage.ts
packages/web-app-files/src/store/actions.ts
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/components/Spaces/SpaceHeader.spec.ts
packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
packages/web-app-files/tests/unit/composables/actions/spaces/useSpaceActionsUploadImage.spec.ts
packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
packages/web-pkg/src/configuration/manager.ts
packages/web-pkg/src/configuration/types.ts
packages/web-runtime/tests/unit/pages/oidcCallback.spec.ts
packages/web-runtime/tests/unit/services/auth/authService.spec.ts

- Fixes [Spaces overview: Thumbnail image is zoomed in · Issue #9328 · owncloud/web](https://github.com/owncloud/web/issues/9328)
- Fixes [[Bug] distorted/clinched space thumbnails in list view · Issue #10133 · owncloud/web](https://github.com/owncloud/web/issues/10133)
- test case 1:
- test case 2:
- ...

Fix tiles view preview images in general (zooming issue) and files list thumbnails in spaces  

---

changelog/unreleased/bugfix-resolve-link-without-drive-alias
packages/web-app-files/src/views/spaces/DriveResolver.vue
packages/web-app-files/tests/unit/views/spaces/DriveResolver.spec.ts

We can simply use our private link resolving in case a drive alias is missing while a `fileId` is present.
- Fixes https://github.com/owncloud/web/issues/9269

fix: resolving links without drive alias

---

changelog/unreleased/bugfix-parallel-uploads
packages/web-app-files/src/HandleUpload.ts

Fixes uploading the same files parallel. Uppy is smart enough to not add duplicated files to the upload queue, we just need to early return in that case.
- Fixes https://github.com/owncloud/web/issues/9220

fix: uploading the same files parallel

---

changelog/unreleased/enhancement-create-link-modal
packages/web-pkg/src/components/CreateLinkModal.vue

Resets the password input in the link creation modal when selecting the internal link role since it doesn't support passwords. This way, unrelated error messages and policy information gets cleared.
- Fixes https://github.com/owncloud/web/issues/10157

fix: reset password input for internal links

---

changelog/unreleased/bugfix-gdpr-export-polling
packages/web-runtime/src/components/Account/GdprExport.vue

Fixes periodically checking for new gdpr exports which didn't work reliably due to never resetting the polling interval.
- Fixes https://github.com/owncloud/web/issues/8862

fix: gdpr export polling

---

docker-compose.yml

This PR changes the registry for the app provider services to `natsjs` and previously it was `mdns` as we have the tests implemented with `natsjs` registry in drone.

[tests-only][full-ci]change the `mdns` registry for app provider to `natsjs`

---

tests/e2e/cucumber/features/smoke/admin-settings/general.feature

We disabled the test with https://github.com/owncloud/web/pull/9698 to get the pipeline green. oCIS has been updated meanwhile, which means we can re-enable the test.

test: re-enable e2e test for changing logo

---

changelog/unreleased/change-theme-handling
docs/theming/_index.md
packages/design-system/src/index.ts
packages/web-pkg/src/composables/piniaStores/theme.ts

Update theming docs after #9698

---

changelog/unreleased/enhancement-extensions-sidebar-panels
packages/web-app-files/src/extensions.ts

- test case 1:
- test case 2:
- ...

fix(files): init sidebar panels in injection context

---

changelog/unreleased/bugfix-versions-readonly
packages/web-app-files/src/components/SideBar/Actions/FileActions.vue
packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
packages/web-app-files/src/fileSideBars.ts
packages/web-app-files/tests/unit/components/SideBar/Versions/FileVersions.spec.ts
packages/web-pkg/src/composables/download/useDownloadFile.ts

Make versions panel readonly when the right sidebar is opened from within a viewer or editor.
Reason for that is that it would require complex user interaction to make reverting versions from within an editor view (= the file content is already displayed) possible. Let's avoid that by only allowing the download action, not the revert action.

Readonly versions panel

---

changelog/unreleased/bugfix-created-file-missing-file-extension
packages/web-app-files/src/composables/actions/files/useFileActionsCreateNewFile.ts

- Fixes https://github.com/owncloud/web/issues/10170
- test case 1:
- test case 2:
- ...

Fix bug file extension was missing while crating file

---

changelog/unreleased/enhancement-create-link-modal
packages/web-pkg/src/composables/actions/files/useFileActionsCreateLink.ts

- test case 1:
- test case 2:
- ...

Fix errors not shown while creating link fails

---

changelog/unreleased/bugfix-turned-off-file-extensions-had-no-effect
packages/web-pkg/src/components/AppTopBar.vue
packages/web-pkg/src/components/Search/ResourcePreview.vue
packages/web-pkg/tests/unit/components/AppTopBar.spec.ts
packages/web-pkg/tests/unit/components/Search/ResourcePreview.spec.ts
packages/web-pkg/tests/unit/components/__snapshots__/AppTopBar.spec.ts.snap

- test case 1:
- test case 2:
- ...

Don't show file extensions in AppTopBar and Search if turned off via setting

---

packages/design-system/src/components/OcModal/OcModal.vue
packages/web-app-files/src/components/Modals/SetLinkPasswordModal.vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
packages/web-app-files/tests/unit/components/Modals/SetLinkPasswordModal.spec.ts
packages/web-runtime/src/App.vue
packages/web-runtime/src/store/modal.ts
packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts

Removes the password logic from our generic modal implementation and uses a custom component instead.

refactor: remove password logic form modal implementation

---

changelog/unreleased/enhancement-show-webdav-information-in-details
packages/web-pkg/src/components/SideBar/WebDavDetails.vue

- test case 1:
- test case 2:
- ...

Add missing gettext calls in WebDavDetails.vue

---

tests/e2e/cucumber/features/smoke/search.feature
tests/e2e/cucumber/steps/api.ts
tests/e2e/support/api/davSpaces/spaces.ts

I'm about to remove the `yesterday` mtime filter option from the backend, see https://github.com/owncloud/ocis/pull/7919
Switching it over to `last 7 days` in the e2e tests.
- Prerequisite for https://github.com/owncloud/web/issues/9779#issuecomment-1807930111

e2e tests: switch "yesterday" to "last 7 days"

---

packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/tests/unit/components/AppBar/__snapshots__/CreateAndUpload.spec.ts.snap
packages/web-pkg/src/components/CreateShortcutModal.vue
packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewShortcut.ts
packages/web-pkg/tests/unit/components/CreateShortcutModal.spec.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateNewShortcut.spec.ts

Before, the state of the shortcut modal was handled by the outside where it was being used. Refactors the modal usage so that the modal state handling is done via the create shortcut action instead, meaning the consuming party doesn't need to care about it anymore.

refactor: shortcut modal usage

---

packages/design-system/src/components/OcModal/OcModal.vue
packages/web-app-admin-settings/src/components/Groups/CreateGroupModal.vue
packages/web-app-admin-settings/src/composables/actions/groups/index.ts
packages/web-app-admin-settings/src/composables/actions/groups/useGroupActionsCreateGroup.ts
packages/web-app-admin-settings/src/views/Groups.vue
packages/web-app-admin-settings/tests/unit/components/Groups/CreateGroupModal.spec.ts
packages/web-app-admin-settings/tests/unit/composables/actions/groups/useGroupActionsCreateGroup.spec.ts
packages/web-app-admin-settings/tests/unit/views/Groups.spec.ts
packages/web-app-files/src/components/Modals/SetLinkPasswordModal.vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
packages/web-app-files/tests/unit/components/Modals/SetLinkPasswordModal.spec.ts
packages/web-runtime/src/App.vue
packages/web-runtime/src/store/modal.ts
packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts

Moved all relevant code parts to the `CreateGroupModal` component in the course of this, instead of having it spread all over the place.

refactor: create dedicated action for creating groups

---

packages/design-system/src/components/OcModal/OcModal.vue
packages/web-app-files/src/components/Modals/SetLinkPasswordModal.vue
packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
packages/web-app-files/src/components/Spaces/SpaceContextActions.vue
packages/web-app-files/tests/unit/components/Modals/SetLinkPasswordModal.spec.ts
packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceContextActions.spec.ts.snap
packages/web-pkg/src/components/Spaces/ReadmeContentModal.vue
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsEditReadmeContent.ts
packages/web-pkg/tests/unit/components/Spaces/ReadmeContentModal.spec.ts
packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsEditReadmeContent.spec.ts
packages/web-runtime/src/App.vue
packages/web-runtime/src/store/modal.ts
packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts

Before, the state of the space readme modal was handled by the outside where it was being used. Refactors the modal usage so that the modal state handling is done via the edit space readme action instead, meaning the consuming party doesn't need to care about it anymore.

refactor: space readme modal usage

---

packages/web-app-admin-settings/src/components/Spaces/ContextActions.vue
packages/web-app-admin-settings/src/components/Spaces/SideBar/ActionsPanel.vue
packages/web-app-admin-settings/src/components/Users/ContextActions.vue
packages/web-app-admin-settings/src/composables/actions/users/useUserActionsAddToGroups.ts
packages/web-app-admin-settings/src/composables/actions/users/useUserActionsEditLogin.ts
packages/web-app-admin-settings/src/composables/actions/users/useUserActionsEditQuota.ts
packages/web-app-admin-settings/src/composables/actions/users/useUserActionsRemoveFromGroups.ts
packages/web-app-admin-settings/src/views/Spaces.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/composables/actions/users/useUserActionsEditQuota.spec.ts
packages/web-app-admin-settings/tests/unit/views/__snapshots__/Spaces.spec.ts.snap
packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
packages/web-app-files/src/components/Spaces/SpaceContextActions.vue
packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceContextActions.spec.ts.snap
packages/web-pkg/src/components/AppBar/AppBar.vue
packages/web-pkg/src/components/Spaces/QuotaModal.vue
packages/web-pkg/src/composables/actions/files/useFileActionsCreateLink.ts
packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewShortcut.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsEditQuota.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsEditReadmeContent.ts
packages/web-pkg/tests/unit/components/AppBar/__snapshots__/AppBar.spec.ts.snap
packages/web-pkg/tests/unit/components/Spaces/QuotaModal.spec.ts
packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsEditQuota.spec.ts
packages/web-runtime/src/App.vue

Before, the state of the quota modal was handled by the outside where it was being used. This caused quite some boilerplate code because it's effectively always the same.
Refactors the quota modal usage so that the modal state handling is done via the quota action instead, meaning the consuming party doesn't need to care about it anymore.

refactor: quota modal usage

---

changelog/unreleased/change-remove-deprecated-quick-actions-extension-point
packages/web-app-files/tests/__fixtures__/fileActions.ts
packages/web-pkg/src/apps/types.ts
packages/web-runtime/src/container/api.ts
packages/web-runtime/src/container/application/classic.ts
packages/web-runtime/src/container/types.ts
packages/web-runtime/src/store/app.ts
packages/web-test-helpers/src/mocks/store/defaultStoreMockOptions.ts

Removes the old and deprecated way of registering quick actions via the `quickaction` property of an app as well as leftovers from the sidebar extension rework.

refactor: remove deprecated extension point for adding quick actions 

---

changelog/unreleased/bugfix-loading-indicator-conflict-dialog
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-pkg/src/composables/actions/files/useFileActionsPaste.ts

Fixes an issue where the loading indicator would show before taking any action in the resource conflict modal.
- Fixes https://github.com/owncloud/web/issues/10215

fix: loading indicator showing during conflict dialog

---

packages/web-pkg/src/composables/actions/files/useFileActionsCopy.ts
packages/web-pkg/src/composables/actions/files/useFileActionsEmptyTrashBin.ts
packages/web-pkg/src/composables/actions/files/useFileActionsMove.ts
packages/web-pkg/src/composables/actions/files/useFileActionsNavigate.ts
packages/web-pkg/src/composables/actions/files/useFileActionsPaste.ts

We removed pgettext, since we merge all translations.json files into one global json file for vue-gettext it is not possible to have two translation types, one created via $gettext (e.G `{"Copy": "Kopieren"}`) and one via $pgettext (e.G `{"Copy":{"Action in the files list row to initiate copying resources":"Kopieren"}}`  in one json file as the keys are identical.
So those compete against each other and one get lost, and lead to a non translated string 
- Fixes https://github.com/owncloud/web/issues/10216
- test case 1:
- test case 2:
- ...

Replace pgettext with gettext

---

.vscode/settings.json

At least for me this causes much less issues in vscode. Otherwise it would use typescript `5.3` which is not yet compatible with Web.

chore: use the project's typescript version in vscode

---

package.json
packages/web-runtime/tests/unit/container/bootstrap.spec.ts
packages/web-runtime/tests/unit/helpers/theme.spec.ts
pnpm-lock.yaml
tests/unit/config/jest.init.ts

Remove the `jest-fetch-mock` because it a) causes security alerts, b) is unmaintained since 4 years and c) we rarely used it and can rely on standard jest functionality.

test: remove jest-fetch-mock dependency

---

.drone.env

Part of https://github.com/owncloud/QA/issues/839

[full-ci] [tests-only] Bump ocis commit id to stable 5.0

---

package.json
pnpm-lock.yaml

Updating `depcheck` to `v1.4.7` for a security patch (they bumped `@babel/traverse` to a newer version)

chore: update depcheck to v1.4.7 (security)

---

packages/eslint-config/package.json
pnpm-lock.yaml

Bumps the typescript eslint packages to `v6.17.0`, which is necessary for compatibility typescript 5.3.3.

chore: bump typescript eslint packages to v6.17.0

---

packages/web-runtime/src/services/auth/userManager.ts

With log level `INFO` for the `oidc-client-ts` lib we see a `user loaded` log message on each route change (because the authService needs to re-initialize the context for the respective route and for we need to query the access token from the user manager... the `oidc-client-ts` lib then prints the `user loaded` log message, no matter if the user is already cached or not. That's just log noise, we should reduce that to warnings.

chore: set oidc-client-ts log level to WARN

---

packages/web-app-files/src/components/FilesList/ResourceTiles.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap

Bring the latest changes from `stable-8.0` to master.

Merge stable 8.0 to master

---

changelog/unreleased/change-remove-home-folder-option
docs/getting-started.md
packages/web-app-files/src/views/spaces/DriveRedirect.vue
packages/web-app-files/src/views/spaces/DriveResolver.vue
packages/web-pkg/src/helpers/router/routeOptions.ts
packages/web-runtime/src/store/config.ts

Removes `homeFolder` option.
CERN is implementing space apis now. If they want to show a full path, we need to handle it in breadcrumbs but not like this.
- test case 1:
- test case 2:
- ...

chore: remove homeFolder option

---

packages/web-runtime/src/layouts/Application.vue
packages/web-runtime/src/store/navigation.ts

Removes the code for registering dynamic nav items since this is no longer possible.

refactor: remove dynamic nav items

---

changelog/unreleased/bugfix-skip-searchbar-preview-fetch-on-reload
packages/web-app-search/src/portals/SearchBar.vue

Setting "search term" from route would trigger search, which would create request on page load.
Added additional bool value to check if this change is triggered by route or user input
- Fixes https://github.com/owncloud/web/issues/10200

Skipping searchbar preview on reload

---

.drone.env

The Ocis build pipeline break fix is merged in Ocis (https://github.com/owncloud/ocis/pull/8158). So, bumping OCIS commit ID.
https://drone.owncloud.com/owncloud/web/41712/5/4

[full-ci] [tests-only] Bump ocis commit-id to include fix for ocis build pipeline

---

changelog/unreleased/bugfix-scrollable-account-page
packages/web-runtime/src/pages/account.vue

Setting `overflow-y: auto` on `<main>` in `account.vue` page to allow scroll in "horizontal" orientation
- Fixes https://github.com/owncloud/web/issues/10313

Account page scrollable

---

packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
packages/web-runtime/src/layouts/Application.vue
packages/web-runtime/src/store/navigation.ts
packages/web-runtime/tests/unit/components/SidebarNav/SidebarNav.spec.ts
packages/web-test-helpers/src/mocks/store/defaultStoreMockOptions.ts

No need to handle the state in a vuex store module, it can be simply handled within the `Application` component.

refactor: remove left sidebar nav state from vuex store

---

changelog/unreleased/enhancement-enable-user-preferences-in-public-links
packages/web-app-admin-settings/src/index.ts
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/Details/TagsSelect.vue
packages/web-app-files/src/index.ts
packages/web-app-files/tests/unit/views/spaces/DriveResolver.spec.ts
packages/web-app-ocm/src/index.ts
packages/web-app-search/tests/unit/portals/SearchBar.spec.ts
packages/web-pkg/src/apps/types.ts
packages/web-pkg/src/composables/piniaStores/apps.ts
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
packages/web-runtime/src/components/Topbar/TopBar.vue
packages/web-runtime/src/components/Topbar/UserMenu.vue
packages/web-runtime/src/pages/account.vue
packages/web-runtime/src/router/index.ts
packages/web-runtime/tests/unit/components/Topbar/TopBar.spec.ts
packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.ts.snap
packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
packages/web-runtime/tests/unit/pages/account.spec.ts
tests/e2e/cucumber/features/smoke/languageChange.feature
tests/e2e/cucumber/steps/ui/accountMenu.ts
tests/e2e/support/objects/account/actions.ts
tests/e2e/support/objects/account/index.ts

Enhancement: Enable user preferences in public links
We've enabled user preferences in public links, so any user even without an account can open
preferences in a public link context and for example change the current language.
- Part of https://github.com/owncloud/web/issues/10181
- test case 1:
- test case 2:
- ...

Preferences for not logged in users (public link context)

---

tests/e2e/cucumber/features/smoke/app-provider/officeSuites.feature
tests/e2e/cucumber/features/smoke/internalLink.feature
tests/e2e/cucumber/features/smoke/languageChange.feature
tests/e2e/cucumber/features/smoke/link.feature
tests/e2e/cucumber/features/smoke/rename.feature
tests/e2e/cucumber/features/smoke/shortcut.feature
tests/e2e/cucumber/features/smoke/spaces/internalLink.feature
tests/e2e/cucumber/features/smoke/spaces/participantManagement.feature
tests/e2e/cucumber/features/smoke/spaces/project.feature
tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
tests/e2e/cucumber/steps/ui/links.ts
tests/e2e/support/objects/app-files/link/actions.ts

I've added the ability to create a public link with the role added immediately at the time of creation
if we create public link with `Invited people` role - password is not required so I check message `Password cannot be set for internal links`
I would add Given step for creating link but want to do it when we switch to sharing NG

[test-only]e2e test. create link with role

---

packages/web-app-files/src/store/actions.ts
packages/web-app-files/src/store/getters.ts
packages/web-app-files/src/store/mutations.ts
packages/web-app-files/src/store/state.ts
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/src/views/trash/Overview.vue
packages/web-app-files/tests/unit/store/getters.spec.ts
packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts

The `filesSearched` store state didn't seem to be used at all, so this removes it from it (including all related mutations). Also removes the `filesAll` getter since it's now the same as `files`.

refactor: remove searched files from store

---

packages/web-app-search/src/portals/SearchBar.vue
packages/web-pkg/src/components/SearchBarFilter.vue
packages/web-pkg/src/composables/search/constants.ts
packages/web-pkg/tests/unit/components/SearchBarFilter.spec.ts
tests/e2e/cucumber/features/smoke/fullTextSearch.feature
tests/e2e/cucumber/features/smoke/search.feature
tests/e2e/cucumber/features/smoke/searchProjectSpace.feature
tests/e2e/support/objects/app-files/resource/actions.ts

- Fixes https://github.com/owncloud/web/issues/10339
- test case 1:
- test case 2:
- ...

Rename search filters to 'current folder' and 'all files'

---

packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/composables/keyboardActions/useKeyboardTableActions.ts
packages/web-app-files/src/composables/keyboardActions/useKeyboardTableSpaceActions.ts
packages/web-app-files/src/helpers/resource/actions/index.ts
packages/web-app-files/src/helpers/resource/actions/types.ts
packages/web-app-files/src/store/actions.ts
packages/web-app-files/src/store/getters.ts
packages/web-app-files/src/store/mutations.ts
packages/web-app-files/src/store/state.ts
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts
packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/src/composables/actions/files/useFileActionsCopy.ts
packages/web-pkg/src/composables/actions/files/useFileActionsMove.ts
packages/web-pkg/src/composables/actions/files/useFileActionsPaste.ts
packages/web-pkg/src/composables/piniaStores/clipboard.ts
packages/web-pkg/src/composables/piniaStores/index.ts
packages/web-pkg/src/helpers/resource/conflictHandling/index.ts
packages/web-pkg/src/helpers/resource/conflictHandling/transfer.ts
packages/web-pkg/src/helpers/resource/conflictHandling/types.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCopy.spec.ts
packages/web-pkg/tests/unit/helpers/resource/conflictHandling/resourcesTransfer.spec.ts
packages/web-test-helpers/src/mocks/pinia.ts
packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts

Removes the clipboard from the vuex file store and adds a slim pinia store instead. There is no need for that to be coupled in any file store.
Also, moves the `pasteSelectedFiles` method from the files store into its corresponding action composable. Again, not really needed in a store since the action is the only place where this is being called. The `ResourceTransfer` component needed to be moved to `web-pkg` for this to happen.

Remove clipboard from files store

---

changelog/unreleased/bugfix-read-only-user-attributes-have-no-effect-on-group-memberships
packages/web-app-admin-settings/src/components/Users/GroupSelect.vue
packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
packages/web-app-admin-settings/src/composables/actions/users/useUserActionsAddToGroups.ts
packages/web-app-admin-settings/src/composables/actions/users/useUserActionsRemoveFromGroups.ts
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap
packages/web-app-admin-settings/tests/unit/composables/actions/users/useUserActionsAddToGroups.spec.ts
packages/web-app-admin-settings/tests/unit/composables/actions/users/useUserActionsRemoveFromGroups.spec.ts

- Fixes https://github.com/owncloud/enterprise/issues/5941
- test case 1:
- test case 2:
- ...

Bugfix: Readonly user attributes have no effect on group memberships

---

packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/store/actions.ts
packages/web-app-files/src/store/getters.ts
packages/web-app-files/tests/unit/store/actions.spec.ts
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts

Removes the `highlightedFile` getter from the vuex file store. The reason behind this decision is that the getter was really opaque to use as it sometimes referred to the current folder and sometimes to the first selected file (which is already confusing in itself since the user can highlight more than 1 resources).
- Fixes https://github.com/owncloud/web/issues/10210

refactor: remove highlightedFile getter from store

---

changelog/unreleased/enhancement-preview-app-add-reset-button-for-images
packages/web-app-preview/src/App.vue
packages/web-app-preview/src/components/MediaControls.vue
packages/web-app-preview/src/components/Sources/MediaImage.vue
packages/web-app-preview/tests/unit/app.spec.ts
packages/web-app-preview/tests/unit/components/MediaControls.spec.ts

- Fixes https://github.com/owncloud/web/issues/9840
- test case 1:
- test case 2:
- ...

Add image reset button to reset zoom, rotation and position

---

packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
packages/web-app-files/src/store/actions.ts
packages/web-app-files/src/store/getters.ts
packages/web-app-files/src/store/state.ts
packages/web-app-files/tests/unit/components/FilesList/ResourceDetails.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Versions/FileVersions.spec.ts
packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts

Removes the file versions from the vuex files store module because there is no need to store them in any store.

refactor: remove file versions from vuex files store module

---

.drone.star
docker-compose.yml

This PR updates docker compose file since there were some difference while running app-provider services in CI and compose. It makes them consistent in both CI and compose. And also makes the services version same in both CI and compose file.
https://github.com/owncloud/web/issues/10359

[tests-only][full-ci]update compose make image versions consistent in CI and compose

---

packages/design-system/docs/visibility.md

It seems like the documentation about the use of `.oc-visible@s`, `.oc-visible@m`, `.oc-visible@l` and `.oc-visible@xl` to display elements only on certain screen sizes is not correct. Working with these classes I noticed that these classes hide the element on screen sizes that are smaller than the given breakpoint and display them on devices with screen sizes bigger or equal to the given breakpoint – as their name also implies (see also css code examples below generated by applying these classes). However the documentation says exactly the opposite which is confusing for developers who want to use these classes.
```
@media (max-width: 959px)
.oc-visible\@m {
display: none !important;
}
@media (max-width: 639px)
.oc-visible\@s {
display: none !important;
}
```
no issue created so far …

[docs-only] update documentation of visibility classes

---

packages/design-system/package.json
packages/design-system/src/components/OcModal/OcModal.vue
packages/web-runtime/package.json
pnpm-lock.yaml

Fixes a regression from https://github.com/owncloud/web/pull/10243 which caused some issues with the initial focus on modals.
I reverted https://github.com/owncloud/web/pull/10243/commits/7526dcaa12e9586aa3925c32fa6f38d47573c170 (which was supposed to fix it) and pinned to the version of `focus-trap` to `7.2.0` since newer versions seem to be responsible for the issue. Needs further debugging, this PR simply brings back the previous working state.

fix: initial focus on modals

---

.drone.star
.gitignore
packages/design-system/docs/components/Preview.js
packages/design-system/docs/utils/tabs.js
packages/design-system/package.json
packages/design-system/src/components/_DocsComponentsList/_DocsComponentsList.vue
packages/design-system/tests/e2e/playwright.config.ts
packages/design-system/tests/e2e/specs/component-example.spec.ts
packages/design-system/tests/e2e/specs/components-list.spec.ts
tests/unit/config/jest.config.ts

- setup playwright in design system
- add two E2E tests to check docs and component example rendering
- run tests in CI (for now only on chrome due to https://github.com/owncloud/web/issues/10388)
- refs #10233
Have more faith in design system changes and allow us to merge deps more quickly
- test environment: macos x64 & CI
- test case 1: run playwright E2E tests

[tests-only] test: add design system docs tests

---

packages/extension-sdk/package.json
pnpm-lock.yaml

This was set to `^5.0.0` which installed a `5.0.0` version of vite alongside the current version `5.0.12`. Setting it to `^5.0` fixes this, as the extension-sdk should use the same version as the root `package.json` specifies.
Security altert: https://github.com/owncloud/web/security/dependabot/144

chore: fix vite peer dependency in extension-sdk package

---

.drone.star

Dev docs **must** not be published from the `stable-*` branches because that overwrites changes from the `master` branch. Dev docs should always only ever reflect the current state from the `master` branch.

ci: stop running docs pipeline on stable branches (master)

---

.drone.star

Dev docs **must** not be published from the `stable-*` branches because that overwrites changes from the `master` branch. Dev docs should always only ever reflect the current state from the `master` branch.

ci: stop running docs pipeline on stable branches (8.0)

---

.drone.star

Dev docs **must** not be published from the `stable-*` branches because that overwrites changes from the `master` branch. Dev docs should always only ever reflect the current state from the `master` branch.

ci: stop running docs pipeline on stable branches (7.0)

---

.drone.star

Dev docs **must** not be published from the `stable-*` branches because that overwrites changes from the `master` branch. Dev docs should always only ever reflect the current state from the `master` branch.

ci: stop running docs pipeline on stable branches (7.1)

---

tests/e2e/cucumber/features/smoke/app-provider/officeSuites.feature
tests/e2e/cucumber/steps/ui/navigateByUrl.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/url-navigation/actions.ts

part of #9897 
check that file can be open in Collabora via url. client feature:

[full-ci] url stability. open file through Collabora

---

changelog/unreleased/bugfix-restore-space
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsRestore.ts

- Fixes https://github.com/owncloud/enterprise/issues/6279
- test case 1:
- test case 2:
- ...

Bugfix: Not able to restore space in some constellations for some(space) admins

---

packages/web-pkg/src/apps/types.ts
packages/web-pkg/src/components/Search/types.ts
packages/web-pkg/src/components/SideBar/types.ts
packages/web-pkg/src/composables/actions/types.ts
packages/web-pkg/src/composables/piniaStores/extensionRegistry.ts
packages/web-pkg/src/utils/types.ts
packages/web-runtime/src/container/api.ts

Just tried writing a basic search provider while working on #10067 and realized search results were hardcoded to be webdav-specific. Figured I'd allow for a more generic approach, at least from a type perspective 🙃

Allow generic search result items for search providers

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
tests/e2e/cucumber/features/smoke/shares/share.feature
tests/e2e/cucumber/steps/ui/shares.ts
tests/e2e/support/objects/app-files/share/actions.ts
tests/e2e/support/objects/app-files/share/collaborator.ts
tests/e2e/support/objects/app-files/share/index.ts

Removed acceptance tests that checks the share access details and added the coverage in e2e

[tests-only] remove share access details tests and add e2e coverage

---

packages/web-runtime/src/components/Account/GdprExport.vue
packages/web-runtime/src/pages/account.vue
packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap

Supersedes stale #8851 and drops unrelated changes
Colorful borders only to make changes more obvious. As discussed with @kulmann the buttons shouldn't be filled-primary since it's not _the_ main action on the page

Restructure GDPR export / turn into dedicated section on accounts page

---

tests/e2e/cucumber/features/smoke/app-provider/officeSuites.feature
tests/e2e/cucumber/features/smoke/app-provider/urlJourneys.feature
tests/e2e/cucumber/steps/ui/navigateByUrl.ts
tests/e2e/support/api/external/index.ts
tests/e2e/support/api/external/openWithWeb.ts
tests/e2e/support/objects/url-navigation/actions.ts

related: https://github.com/owncloud/web/issues/9897
tests for https://github.com/owncloud/web/issues/9804

[full-ci]check file opening for mobile apps

---

.drone.env
packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/views/shares/SharedWithMe.vue
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.ts
packages/web-app-files/tests/unit/views/shares/SharedWithMe.spec.ts
packages/web-client/src/generated/api.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-client/src/helpers/share/functionsNG.ts
packages/web-client/src/helpers/share/types.ts
packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
tests/acceptance/pageObjects/sharedWithMePage.js

Bumps the libre graph client and adjusts the way how share resources are built due to recent API changes (see https://github.com/owncloud/ocis/pull/8322). Multiple shares for the same resource are now being returned as one drive item including multiple permissions. That means no more duplicated resources in the files list.
The `shareId` and the `shareRoot` on a `Resource` are now somewhat misleading, since a resource can hold multiple "shares" (= permissions). We still need those props to be able to resolve into the share jail, but we should remove this in the future.

refactor: adjust building share resources after server changes

---

.drone.env
tests/acceptance/features/webUICreateFilesFolders/createFile.feature
tests/acceptance/features/webUIFiles/download.feature
tests/e2e/cucumber/features/smoke/upload.feature

Added e2e test to create and download a file containing comma in its name.
Removed these acceptance tests:
https://github.com/owncloud/web/blob/59b5bbe6d77af2a530a224abd351f738d2237966/tests/acceptance/features/webUICreateFilesFolders/createFile.feature#L19-L22
and https://github.com/owncloud/web/blob/59b5bbe6d77af2a530a224abd351f738d2237966/tests/acceptance/features/webUIFiles/download.feature#L24-L28
Coverage for:
- https://github.com/owncloud/ocis/issues/8361

[tests-only] test(e2e): create and download file having comma

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
tests/e2e/cucumber/features/smoke/trashbinDelete.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/cucumber/steps/ui/spaces.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

In this PR,
- Added e2e test to delete multiple resources at once from trashbin
- Removed scenarios related to trashbin delete from web UI tests

[tests-only][full-ci] added e2e test to delete multiple resources from trashbin

---

packages/web-app-epub-reader/src/App.vue

- test case 1:
- test case 2:
- ...

Epub reader dark theme support

---

packages/web-app-epub-reader/src/App.vue

- test case 1:
- test case 2:
- ...

save and load location on epub app automatically 

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
tests/e2e/cucumber/features/smoke/shares/link.feature

Removed a bug demonstration test scenario related to issue https://github.com/owncloud/web/issues/2443 from the web UI test and added a step for uploading folder in public link share. As the folder upload is not available in playwright, the step for E2E test is added and is commented for now.
The test is also done manually and the issue doesn't occur in the latest master branch.
Result from manual test.
[Screencast from 02-14-2024 11:33:42 AM.webm](https://github.com/owncloud/web/assets/83579989/ab629237-07a2-495c-a3c9-d77ea123e37f)

[tests-only] Removed scenario related to folder upload from old web UI test

---

changelog/unreleased/bugfix-public-link-file-download
packages/web-pkg/src/composables/download/useDownloadFile.ts
tests/e2e/cucumber/features/smoke/shares/link.feature

Fixes a bug where file downloads via public links that were opened in an authenticated context failed.
- Fixes https://github.com/owncloud/web/issues/10473

fix: public link download in authenticated context

---

packages/web-runtime/src/components/SkipTo.vue

Just stumbled upon the SkipTo button having a bad text contrasts (and violating a11y concerns) in dark mode

Fix contrast for SkipTo Button text

---

changelog/unreleased/enhancement-warn-user-before-close-browser-when-uploading
packages/web-runtime/src/components/UploadInfo.vue
packages/web-runtime/tests/unit/components/UploadInfo.spec.ts

- Fixes https://github.com/owncloud/web/issues/10500
- test case 1:
- test case 2:
- ...

Warn user before closing browser when upload is in progress

---

tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature
tests/acceptance/features/webUIFilesCopy/copy.feature
tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
tests/e2e/cucumber/features/smoke/copyMove.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts

[test-only] rewrite copy/move tests

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature

This PR backports acceptance test changes from https://github.com/owncloud/web/pull/10392
Part of https://github.com/owncloud/web/issues/10457

[tests-only][full-ci] backport acceptance test code changes from #10392

---

.drone.star
docker-compose.yml
docs/backend-ocis.md

changed path in the docker-compose because `WEB_ASSET_PATH` is deprecated 
it was reason why I could not build fresh web
see here: https://github.com/owncloud/ocis/pull/8523#issuecomment-1971017580

[full-ci]change asset path

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
tests/e2e/cucumber/features/smoke/trashbinDelete.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

In this PR,
- removed test scenario from webUI acceptance test related to delete and restore file from shared folder
- added E2E test to delete and restore file from shared folder

[test-only][full-ci] added e2e test to delete and restore file inside a shared folder

---

changelog/unreleased/bugfix-share-sidebar-icons
packages/design-system/src/components/OcAvatarItem/OcAvatarItem.vue
packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/__snapshots__/MembersRoleSection.spec.ts.snap
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/AutocompleteItem.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/AutocompleteItem.spec.ts
packages/web-runtime/src/helpers/navItems.ts

Right sidebar sharing panel didn't have icons in some cases in the sharee search dropdown.
Also found that the `isVisible` check on app nav items was too strict and fixed it as well.

Share sidebar icon fixes

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUITrashbinRestore/trashbinRestore.feature
tests/e2e/cucumber/features/smoke/trashbinDelete.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

This PR backports: https://github.com/owncloud/web/pull/10550

[test-only][full-ci] backport added e2e test to delete and restore file inside a shared folder

---

packages/web-app-admin-settings/src/views/Groups.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/views/Users.spec.ts
packages/web-client/src/graph.ts

The endpoints for listing users and groups will be used for fetching potential sharees in the future. Regular users (non-admins) are not allowed to expand these requests though, hence we need to make the expand option optional.
To be honest, our current wrapper of the Graph SDK just feels like useless boilerplate since we're basically re-implementing it 1:1 (with the exception of some parts that were left out or are set to default - which bites us here e.g.). IMO we should either drop this wrapper or make it somewhat useful.

refactor: make expand on user and group listings optional

---

packages/web-client/src/helpers/share/functionsNG.ts

Fixes reading the hidden state property of shares, which caused shares to never be displayed in a hidden state. This is a regression of the recent sharing NG implementations.
- Fixes https://github.com/owncloud/web/issues/10542

fix: reading hidden state property of shares

---

packages/web-client/src/sse.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/container/sse.ts
packages/web-runtime/src/index.ts

- Fixes https://github.com/owncloud/web/issues/9848
- test case 1:
- test case 2:
- ...

Add sse item renamed event

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIUpload/upload.feature
tests/e2e/cucumber/features/smoke/upload.feature

In this PR,
- removed webUI test related to uploading folder with empty sub-folder
- added a e2e step to uploading folder with empty sub-folder

[tests-only][full-ci] removed webUI test and added e2e test to upload folder containing empty sub-folder

---

docs/testing/testing.md
tests/e2e/.eslintrc.json
tests/e2e/cucumber/steps/ui/public.ts
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/cucumber/steps/ui/spaces.ts
tests/e2e/support/objects/app-files/link/actions.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts
tests/e2e/support/objects/app-files/utils/editor.ts

To prevent mistakes like see here https://github.com/owncloud/web/pull/10553 (which caused tests to be flaky), I have implemented override config for e2e tests with customized rules for `tests/e2e`. With this, we can have separate rules defined for the e2e test code.

[tests-only] override lint rules for tests/e2e

---

packages/web-client/src/sse.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/container/sse.ts

- Fixes https://github.com/owncloud/web/issues/9781
- test case 1:
- test case 2:
- ...

Add sse file locked/unlocked event

---

tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
tests/acceptance/features/webUIUpload/upload.feature
tests/e2e/cucumber/features/smoke/upload.feature

This PR forward ports: https://github.com/owncloud/web/pull/10574

[tests-only][full-ci] forward port removed webUI test and added e2e test to upload folder containing empty sub-folder

---

tests/e2e/cucumber/features/smoke/upload.feature
tests/e2e/support/utils/dragDrop.ts

Drag-n-drop upload was not uploading the file with the correct data which caused the files to be corrupted and the respective file viewer could not open the file. This PR has a fix for that.

[tests-only] fix drag-n-drop upload

---

tests/e2e/cucumber/steps/api.ts
tests/e2e/support/api/davSpaces/spaces.ts

Local file upload via api was not creating the expected file in the server which caused the file viewer unable to open the file.
This PR has a fix for that.

[tests-only] fix api file upload

---

packages/web-client/src/helpers/share/functionsNG.ts

Fixes downloading incoming shared files, which was broken since the switch to sharing NG. Apparently the server now includes the share jail id in a drive item's id, hence Web must not prepend it manually anymore.
- Fixes https://github.com/owncloud/ocis/issues/8618

fix: downloading incoming shared files

---

changelog/unreleased/enhancement-tile-sizes
packages/design-system/src/tokens/ods/size.yaml
packages/web-pkg/src/components/FilesList/ResourceTiles.vue
packages/web-pkg/src/components/ViewOptions.vue
packages/web-pkg/src/composables/viewMode/constants.ts
packages/web-pkg/src/composables/viewMode/useTileSize.ts
packages/web-pkg/src/composables/viewMode/useViewMode.ts
packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap

Played around with tile sizes... stepping from one tile size to the next was too big.
Previously we had 9rem as base tile size and added 9rem for every step in the tile size slider.
Now we have 10rem as base tile size and add 6rem for every step in the tile size slider.
- Fixes https://github.com/owncloud/web/issues/10018
- Fixes https://github.com/owncloud/web/issues/10564

feat: adjust tile sizes

---

changelog/unreleased/enhancement-remember-left-nav-bar-state
packages/web-runtime/src/layouts/Application.vue

- Part of https://github.com/owncloud/web/issues/9613
- test case 1:
- test case 2:
- ...

Persist state of left sidebar

---

changelog/unreleased/bugfix-folder-replace
packages/web-app-files/src/helpers/resource/actions/transfer.ts
packages/web-app-files/src/store/actions.ts
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/unit/helpers/resource/resourcesTransfer.spec.ts

Fixes the "Replace" conflict option when copying/moving a folder.
The mechanism of `isOverwritingParentFolder` falsely prevented this though it should only care about the edge case scenario when moving a sub-folder with the same name as the current folder's parent folder into the parent (via breadcrumbs). This needs an additional check if the current folder differs from the target location.
- Fixes https://github.com/owncloud/web/issues/10515

fix: replacing folders

---

packages/web-app-ocm/src/views/ConnectionsPanel.vue
packages/web-pkg/src/http/client.ts
packages/web-pkg/tests/unit/http/client.spec.ts
packages/web-runtime/src/components/Topbar/Notifications.vue
packages/web-runtime/src/helpers/notifications.ts
packages/web-runtime/tests/unit/components/Topbar/Notifications.spec.ts
tests/e2e/support/objects/runtime/application.ts

Removes the usage of the ownCloud SDK for notifications since it's deprecated and we want to get rid of it. Also removes some old oC10 related code such as `actions` for notifications.
- refs https://github.com/owncloud/web/issues/9709

refactor: remove usage of sdk for notifications

---

changelog/unreleased/enhancement-remember-right-side-bar-state
packages/web-app-admin-settings/src/components/General/SideBar/DetailsPanel.vue
packages/web-app-admin-settings/src/views/General.vue
packages/web-app-admin-settings/src/views/Groups.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/views/__snapshots__/General.spec.ts.snap
packages/web-app-files/src/components/SideBar/NoSelection.vue
packages/web-app-files/src/components/SideBar/TrashNoSelection.vue
packages/web-app-files/src/composables/extensions/useFileSideBars.ts
packages/web-app-files/src/views/trash/Overview.vue
packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
packages/web-app-text-editor/src/App.vue
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/src/components/SideBar/SideBar.vue
packages/web-pkg/src/composables/sideBar/useSideBar.ts
packages/web-pkg/tests/unit/composables/sideBar/useSideBar.spec.ts

- Fixes https://github.com/owncloud/web/issues/9613
- test case 1:
- test case 2:
- ...

Persist state of right sidebar

---

packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
packages/web-app-preview/src/App.vue
packages/web-client/src/webdav/getFileUrl.ts
packages/web-pkg/src/composables/actions/files/useFileActionsDownloadFile.ts
packages/web-pkg/src/composables/download/useDownloadFile.ts
packages/web-runtime/src/components/Account/GdprExport.vue

Removes the usage of the ownCloud SDK for file versions URLs since it's deprecated and we want to get rid of it. This could be achieved quite simple as nearly all the logic we had in `useDownloadFile` is already present in `getFileUrl` of our webdav implementation.
- refs https://github.com/owncloud/web/issues/9709

refactor: remove usage of sdk for file version urls

---

packages/web-app-files/src/helpers/user/avatarUrl.ts
packages/web-app-files/tests/unit/helpers/user/avatarUrl.spec.ts
packages/web-client/package.json
packages/web-client/src/index.ts
packages/web-client/src/ocs/index.ts
packages/web-client/src/ocs/urlSign.ts
packages/web-client/src/webdav/getFileUrl.ts
packages/web-pkg/src/services/archiver.ts
packages/web-pkg/src/services/client/client.ts
packages/web-pkg/tests/unit/services/archiver.spec.ts
packages/web-pkg/tests/unit/services/client.spec.ts
packages/web-runtime/src/container/bootstrap.ts
pnpm-lock.yaml

Moves the URL signing to the OCS client inside our `web-client` package. This allows us to get rid of the implementation in the owncloud SDK.
- refs https://github.com/owncloud/web/issues/9709

refactor: move url signing to web-client package

---

changelog/unreleased/enhancement-add-details-panel-to-trash
packages/web-app-admin-settings/src/components/Groups/SideBar/DetailsPanel.vue
packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/src/components/SideBar/Details/FileDetailsMultiple.vue
packages/web-app-files/src/composables/extensions/useFileSideBars.ts
packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ResourceDetails.spec.ts.snap
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
packages/web-pkg/src/components/SideBar/Spaces/SpaceNoSelection.vue
packages/web-pkg/src/components/SideBar/WebDavDetails.vue
packages/web-runtime/src/App.vue

- Fixes https://github.com/owncloud/web/issues/10620
- Fixes https://github.com/owncloud/web/issues/10616
- test case 1:
- test case 2:
- ...

Add details panel for unique trash and multi select

---

packages/web-pkg/src/composables/driveResolver/useDriveResolver.ts

Fixes an issue where the share nav item would be wrongly marked as active after closing a file viewer/editor in the personal space. This happened because the `currentSpace` had been reset as soon as the `useDriveResolver` composable got unmounted. This must not happen in personal or project spaces though.
Regression from https://github.com/owncloud/web/pull/10452
- Fixes https://github.com/owncloud/web/issues/10615

fix: active share nav item after closing editors

---

changelog/unreleased/enhancement-full-text-search-default
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/tests/unit/components/Search/List.spec.ts
packages/web-app-search/src/portals/SearchBar.vue
packages/web-pkg/src/router/common.ts
tests/e2e/cucumber/features/search/fullTextSearch.feature
tests/e2e/cucumber/features/search/search.feature
tests/e2e/cucumber/steps/ui/search.ts
tests/e2e/support/objects/app-files/search/actions.ts
tests/e2e/support/objects/app-files/search/index.ts

Enables full text search as default if the server supports it.
- Fixes https://github.com/owncloud/web/issues/10534

feat: make full text search default

---

packages/web-app-files/src/services/folder/loaderFavorites.ts
packages/web-client/src/webdav/client/builders.ts
packages/web-client/src/webdav/client/dav.ts
packages/web-client/src/webdav/index.ts
packages/web-client/src/webdav/listFavoriteFiles.ts
packages/web-client/src/webdav/search.ts
packages/web-client/src/webdav/setFavorite.ts
packages/web-client/src/webdav/types.ts
packages/web-pkg/src/composables/actions/files/useFileActionsFavorite.ts

Handle favorites (listing and marking) via our webdav implementation instead of using the SDK. Also adds the possibility to do a `proppatch` and to use `filterRules` via a `report` request via our webdav implementation.
- refs https://github.com/owncloud/web/issues/9709

refactor: handle favorites via our webdav implementation instead of sdk

---

packages/web-pkg/src/composables/actions/files/useFileActionsDownloadArchive.ts
packages/web-pkg/src/composables/actions/files/useFileActionsDownloadFile.ts

Disables the download for unsynced shares as we currently don't support this. It will be possible some day in the future though.
- Fixes https://github.com/owncloud/web/issues/10622

fix: disable download for unsynced shares

---

packages/web-app-files/src/views/spaces/Projects.vue

Fixes errors when re-clicking the "Spaces" nav item when the user is already on that page. The issue existed because the `viewMode` is `undefined` for a short moment on navigation change. This seems to happen because of the asynchronous behaviour of the `useRouteQuery` composable.
- Fixes https://github.com/owncloud/web/issues/10639

fix: re-clicking the spaces nav item

---

.drone.star
tests/drone/get-latest-ocis-commit-id.sh

This PR makes changes on building ocis cache on nightly. After this PR merged, on nightly run, it fetch latest ocis commit id from stable5.0 for web stable8.0  
- Part of https://github.com/owncloud/web/issues/10559
- CI https://drone.owncloud.com/owncloud/web/43481

[full-ci] [tests-only]Cache ocis from latest commit id on nightly 

---

.drone.star

**Problem:**
Command `mc cp -r -a %s/ocis s3/$CACHE_BUCKET/ocis-build/$OCIS_COMMITID` also copied the `ocis_repo` to the cache bucket.
To prevent this, I have renamed the ocis repo to not start with `ocis*`
INFO: The cache was not there and was rebuilt in this PR https://drone.owncloud.com/owncloud/web/43535/7/1
Fixes https://github.com/owncloud/web/issues/10651

[test-only] Prevent caching ocis repo directory

---

changelog/unreleased/bugfix-theme-loading-without-matching-theme
packages/web-pkg/src/composables/piniaStores/theme.ts
packages/web-pkg/tests/unit/composables/piniaStores/theme.spec.ts

Fixes theme loading when no matching theme for the current OS settings is found.
- Fixes https://github.com/owncloud/web/issues/10657

fix: theme loading when no matching theme found

---

changelog/unreleased/bugfix-scope-loss-search-results
packages/web-app-search/src/portals/SearchBar.vue

Prevents the search scope from getting lost when clicking "Show n results" in the search preview.
- Fixes https://github.com/owncloud/web/issues/10634

fix: scope when clicking "Show n results"

---

.drone.star
tests/drone/ocis_keycloak/ocis-ci-realm.dist.json
tests/drone/web-keycloak.json

- separate web config file for keycloak-ocis setup
- removed unnecessary steps/methods/codes

[tests-only][full-ci] use separate web config file for keycloak pipeline

---

.drone.star

`mc cp -a %s/ocis s3/$CACHE_BUCKET/ocis-build/$OCIS_COMMITID` was caching ocis binary as `$OCIS_COMMITID` but not `$OCIS_COMMITID/ocis`. This cause the cache restore failure in pipelines. e.g. https://drone.owncloud.com/owncloud/web/43614/11/8

[full-ci][tests-only] fix ocis cache

---

tests/e2e/support/utils/dragDrop.ts

in the ocis CI test https://github.com/owncloud/web/blob/master/tests/e2e/cucumber/features/spaces/publicLink.feature#L3 is flaky. 
see here: https://drone.owncloud.com/owncloud/ocis/33234/67/9
my guess is that the upload starts before the page opens. Now I'm waiting that button `New` is available on the page, after that start uploading

[test-only] fix drag-n-drop flaky test

---

packages/web-client/src/helpers/call.ts
packages/web-client/src/helpers/index.ts
packages/web-pkg/src/components/SideBar/FileSideBar.vue

Adds a helper function which can be used to make typescript aware of yielded types.
If you have better ideas for a name, let me know ...
- test case 1:
- test case 2:
- ...

chore: add helper to properly type yielded values

---

.drone.env
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/utils/dragDrop.ts

Let's not use the page specific code in the helpers as much as possible. This should let us use the helpers anywhere
Refactor of https://github.com/owncloud/web/pull/10676

[tests-only] move element visibility check from helpers

---

packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.ts
packages/web-pkg/src/composables/piniaStores/modals.ts
packages/web-runtime/src/components/ModalWrapper.vue
tests/e2e/cucumber/features/shares/share.feature

Follow-up for https://github.com/owncloud/web/pull/10433.

refactor: follow-up for #10433

---

tests/e2e/cucumber/features/shares/link.feature
tests/e2e/support/objects/app-files/utils/editor.ts

related https://github.com/owncloud/ocis/issues/8602
we had test for this bug but unfortunately the test didn't expect an error
the image viewer was open, but the image did not appear<img width="2001" alt="Screenshot 2024-03-07 at 17 39 25" src="https://github.com/owncloud/web/assets/84779829/3e5dab9a-6b79-46e6-813e-01ad5740e5fd">
I'm wait locators now
we can check the response, but sometimes that doesn't give us a 100% guarantee that everything works. Example, openning broken pdf file: 
for txt or md files we can check content(ctr+c and evaluate clickboard) but it dificult when user viewer

[test-only]check that image is open

---

packages/web-app-files/src/components/Modals/SetLinkPasswordModal.vue
packages/web-pkg/src/components/CreateLinkModal.vue
tests/e2e/cucumber/features/shares/link.feature

Regression of https://github.com/owncloud/web/pull/10433.
With sharing NG, the server doesn't capitalize the first letter of the banned password error message (or error messages in general). Therefore we need to capitalize it manually until we have a better solution (error codes? translations via server?).

fix: capitalization of banned password error message

---

packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/Shared/RoleItem.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/RoleDropdown.spec.ts
packages/web-pkg/src/components/CreateLinkModal.vue
packages/web-pkg/src/components/LinkRoleDropdown.vue
packages/web-pkg/src/composables/piniaStores/shares/shares.ts
tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/support/api/share/share.ts
tests/e2e/support/objects/app-files/link/actions.ts
tests/e2e/support/objects/app-files/share/collaborator.ts

Removes some hacks that mapped share role ids to human readable strings that were introduced by https://github.com/owncloud/web/pull/10433. These mappings are not supposed to live in runtime code since they were only supposed to support the tests.
I adjusted the tests to check for the role label instead so we don't have to deal with id mappings.

refactor: remove hacks for share role tests

---

packages/web-app-files/src/components/Modals/SetLinkPasswordModal.vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue

Fixes an issue where the password modal was missing when link passwords are enforced and the type of a link changes from internal (or viewer for admins) to anything other.
This was a bit tricky because we first need to add the password to a link and then update its role. The most elegant way of doing this (at least what I found) was by adding a callback function to the password modal component.
Regression of https://github.com/owncloud/web/pull/10433.
- Fixes https://github.com/owncloud/web/issues/10418

fix: missing password modal on link type change

---

packages/web-app-files/src/components/SideBar/Shares/SharesPanel.vue

Removes the shares panel separation between people and link shares when using the `details` query param. It's not needed and didn't work before anyway.

refactor: remove shares panel separation for details query

---

packages/web-runtime/src/helpers/additionalTranslations.ts

Share role labels and descriptions are now coming from the server, hence we need to wrap them manually via `gettext` in our additional translations for them to appear in Transifex (as least for now until we have a better way of handling this).

fix: missing translations for share roles

---

packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/AutocompleteItem.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/RecipientContainer.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/AutocompleteItem.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/SpaceMembers.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap
packages/web-client/src/helpers/share/functions.ts
packages/web-client/src/helpers/share/type.ts
packages/web-client/src/helpers/space/types.ts
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/src/composables/piniaStores/shares/shares.ts
packages/web-pkg/src/composables/piniaStores/spaces.ts

Removes the space share types `spaceUser` and `spaceGroup` because they originate from the removed OCS API and are not needed anymore. This information can easily be retrieved via the underlying resource of a share.

refactor: remove space share types

---

changelog/unreleased/iframe-sandbox-drawio.md
packages/web-app-draw-io/src/App.vue

Applying sandbox attribute to iframe in draw-io extension
https://www.w3schools.com/tags/att_iframe_sandbox.asp
:police_officer: 
- :hand: 
- open draw io file
- see it still working properly

fix: apply sandbox attribute to draw-io iframe

---

packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/AutocompleteItem.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-client/src/helpers/share/types.ts

Since user emails are sensitive information and we can't rely on the server providing it anymore, share autocomplete items now fall back to the username (`onPremisesSamAccountName` in graph).
- refs https://github.com/owncloud/ocis/issues/8726

fix: fall back to username in share autocomplete items

---

changelog/unreleased/iframe-sandbox-drawio.md
changelog/unreleased/iframe-sandbox-external.md
packages/web-app-external/src/App.vue
packages/web-app-external/tests/unit/__snapshots__/app.spec.ts.snap

Applying sandbox attribute to iframe in app-external extension(OnlyOffice & Collabora)
https://www.w3schools.com/tags/att_iframe_sandbox.asp
:police_officer: 
- :hand: 
- open office file file in OnlyOffice
- see it still working properly
- :exclamation: Could not test with Collabora - not showing in docker compose setup - https://github.com/owncloud/ocis/issues/8474

fix: apply sandbox attribute to OnlyOffice/Collabora iframe

---

packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue

Since the server doesn't send any information other than `id` and `displayName` for non-admins when querying users, we need to change the way how to distinguish between users and groups. This basically undos the simplified approach done via PR #10703 as it doesn't work anymore.
- Fixes https://github.com/owncloud/web/issues/10712

fix: sharing for non-admin users

---

.drone.env

This PR:
https://github.com/owncloud/web/issues/10712

[tests-only][full-ci]Bump latest ocis commit on web and fix the failing tests

---

packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersPanel.vue
packages/web-client/src/helpers/resource/types.ts
packages/web-client/src/helpers/space/functions.ts
packages/web-client/src/helpers/space/types.ts
packages/web-pkg/src/components/FilesList/ResourceTile.vue
packages/web-pkg/src/components/Search/ResourcePreview.vue
packages/web-pkg/src/components/SideBar/Spaces/SpaceInfo.vue
packages/web-pkg/src/components/Spaces/QuotaModal.vue
packages/web-pkg/src/composables/actions/files/useFileActionsDisableSync.ts
packages/web-pkg/src/composables/actions/files/useFileActionsEnableSync.ts
packages/web-pkg/src/composables/actions/files/useFileActionsToggleHideShare.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsEditQuota.ts
packages/web-pkg/src/composables/piniaStores/resources.ts
packages/web-pkg/src/composables/piniaStores/spaces.ts
packages/web-pkg/tests/unit/components/sidebar/FileSideBar.spec.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateLink.spec.ts
packages/web-runtime/src/components/Topbar/UserMenu.vue
packages/web-runtime/tests/unit/pages/resolvePublicLink.spec.ts

Improves the `SpaceResource` interface by moving all space relevant properties from the `Resource` interface to there as well as by making them non-optional. This allows us for better distinction between the both.
- fixes https://github.com/owncloud/web/issues/10681

refactor: improve SpaceResource interface

---

packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts

Prevents links from wrongfully showing up in the "Shared with" column on the "Shared with others" page. This page is about authenticated shares only.
No changelog needed since this is a regression from the recent sharing NG changes.
- Fixes https://github.com/owncloud/web/issues/10749

fix: hide link shares on "Shared with others" page

---

packages/web-app-files/src/composables/extensions/useFileSideBars.ts
packages/web-pkg/src/components/SideBar/FileSideBar.vue
tests/e2e/cucumber/features/shares/share.feature
tests/e2e/cucumber/features/spaces/project.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

Fixes an issue were permissions were loaded for and in incoming shares. Also fixes another issue where versions were loaded for files inside incoming resources. Both cases need to check if the current user is an actual member of the current space, meaning either a project space or the own personal space. All other spaces don't support loading this kind of information for "foreign" users.
- Fixes https://github.com/owncloud/web/issues/10756

fix: prevent permissions from being loaded for incoming shares

---

.drone.env

This PR bumps latest `ocis-master` commit to `web-master`.

[tests-only][full-ci]Bump latest `ocis` commit to `web` master

---

.drone.env

This PR bumps latest `ocis stable-5.0` commit to `web stable-8.0`.

Bump stable-5.0 latests ocis commit to web stable-8.0

---

changelog/unreleased/bugfix-incoming-notifications-broken-while-notification-center-is-open
packages/web-client/src/helpers/call.ts
packages/web-runtime/src/components/Topbar/Notifications.vue
packages/web-runtime/tests/unit/components/Topbar/Notifications.spec.ts

- Fixes https://github.com/owncloud/web/issues/10602
- test case 1:
- test case 2:
- ...

Fix new notifications broken while notification center is open

---

.drone.env
packages/web-pkg/src/components/SideBar/FileSideBar.vue

Removes the hack for computing all available share roles since the [server issue](https://github.com/owncloud/ocis/issues/8331) regarding this has been fixed.
- Fixes https://github.com/owncloud/web/issues/10769

refactor: remove available shares roles hack 

---

changelog/unreleased/change-disable-opening-files-in-embed-mode
packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/src/components/FilesList/ResourceTile.vue
packages/web-pkg/src/components/FilesList/ResourceTiles.vue
packages/web-pkg/src/composables/actions/files/useFileActions.ts
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
packages/web-pkg/tests/unit/composables/actions/files/useFileActions.spec.ts
packages/web-test-helpers/src/mocks/pinia.ts

- Fixes https://github.com/owncloud/web/issues/10635
- test case 1:
- test case 2:
- ...

Disable resource click and default editor action if embed mode is enabled

---

changelog/unreleased/enhancement-add-sse-event-for-moving
packages/web-client/src/sse/index.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/container/sse.ts

- Fixes https://github.com/owncloud/web/issues/10780
- test case 1:
- test case 2:
- ...

Add sse event for move operations and add debug logs

---

tests/e2e/cucumber/features/smoke/urlJourneys.feature

common issue where user after assign Space Admin role tries to create space and get 403 error
https://drone.owncloud.com/owncloud/web/44075/12/13
https://drone.owncloud.com/owncloud/ocis/33844/51/10
Fixes https://github.com/owncloud/ocis/issues/8883

[test-only] fix flaky test: 403 while creating space

---

changelog/unreleased/bugfix-flickering-loading-indicator
packages/web-app-files/src/store/actions.ts
packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts

Fixes the flickering loading indicator when batch deleting a bunch of files. Since delete operations are running in parallel, using the `setProgress` method for the loading indicator won't work. This is only suited for serial requests.
Also adds a concurrent request limit via pqueue. This stops the network from being overrun with concurrent requests.
- refs https://github.com/owncloud/enterprise/issues/6425

fix: flickering loading indicator on batch delete

---

changelog/unreleased/enhancement-themeable-sharing-role-icon
docs/theming/_index.md
packages/web-pkg/src/composables/piniaStores/shares/shares.ts
packages/web-pkg/src/composables/piniaStores/theme.ts
packages/web-runtime/themes/owncloud/theme.json

Introduce themeable sharing role icons which are used in the sidebar sharing dialog.
- Fixes https://github.com/owncloud/web/pull/10801
- Fixes https://github.com/owncloud/web/issues/10777
give the individual user the ability to customize the look of the sharing role dropdown
- missing unit tests

enhancement: configurable share role icons

---

changelog/unreleased/bugfix-download-files-special-chars
packages/web-pkg/src/composables/download/useDownloadFile.ts

Fixes downloads of files with special chars, especially `#` in the filename by encoding the webdav path.
- Fixes https://github.com/owncloud/web/issues/10810

fix: download of files with special chars

---

tests/e2e/cucumber/features/smoke/upload.feature

This PR adds the steps for downloading file/folder with hash `#` in their name. When user tries to download file/folder with hash in its name, then the download fails with 404 error on `ocis 5.0.2`.
Test coverage for issue https://github.com/owncloud/web/issues/10810

[tests-only][full-ci] add e2e test coverage for filename with hash

---

tests/acceptance/features/webUITextEditor/textFile.feature
tests/e2e/cucumber/features/shares/share.feature

This PR tests the updating of content of a file inside the personal space as to reflect new content edits.
- Part of https://github.com/owncloud/web/issues/10259
- e2e test for updating the content of file has not been implemented
- Locally
- CI

[tests-only][full-ci]add test for updating content of file

---

.drone.env
.drone.star
tests/drone/csp.yaml

With this PR https://github.com/owncloud/ocis/pull/8777 CSP headers and other security related headers were added to http responses due to which the app providers and keycloak related e2e tests were failing. This PR adds an env `PROXY_CSP_CONFIG_FILE_LOCATION` which specifies path to `csp.yaml` file which specifies the domains for keycloak and app providers.
This PR also bumps latest ocis commit id.
Part of: https://github.com/owncloud/QA/issues/849
Fixes https://github.com/owncloud/web/issues/10860, fixes https://github.com/owncloud/web/issues/10857

[tests-only][full-ci]bump latest ocis commit id

---

packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/FileLinks.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.ts
packages/web-client/src/graph/generated/api.ts
packages/web-client/src/graph/index.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-client/src/helpers/share/functions.ts
packages/web-client/src/helpers/share/types.ts
packages/web-pkg/src/composables/piniaStores/shares/shares.ts
packages/web-pkg/tests/unit/composables/sort/useSort.spec.ts

Adds the missing share date for incoming share resources as well as listed shares in the right sidebar.
- Fixes https://github.com/owncloud/web/issues/10778

fix: add missing share date

---

packages/web-app-files/src/components/SideBar/Shares/SharesPanel.vue
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/src/components/SideBar/SideBar.vue

Removes the unused sidebar event `scrollToElement` (which was never emitted) as well as some broken Vue lifecycle hooks from the right sidebar.

fix: remove unused sidebar events

---

.drone.env

Bump ocis stable-5.0 commit id.
- Part of https://github.com/owncloud/QA/issues/849

[tests-only] [full-ci] Bump ocis stable-5.0 latest commit id to web stable-8.0

---

tests/e2e/cucumber/features/app-provider/lock.feature
tests/e2e/cucumber/features/smoke/sse.feature
tests/e2e/cucumber/steps/ui/shares.ts
tests/e2e/support/objects/app-files/share/actions.ts
tests/e2e/support/objects/app-files/share/collaborator.ts
tests/e2e/support/objects/app-files/share/index.ts

related #10839
check SSE events
- file-unlocked
- file-locked
check that user: 
- can see lock icon
- cannot edit locked file
- cannot edit/delete share of the locked file #10507
- can create link or share to the locked file

[test-only] check lock sse event

---

dev/docker/ocis/csp.yaml
docker-compose.yml

local docker-compose setup was not working with app-providers due to security policies. This PR has a fix for that
Similar to: https://github.com/owncloud/web/pull/10856, https://github.com/owncloud/ocis/pull/9025 due to https://github.com/owncloud/ocis/pull/8777
- Fixes https://github.com/owncloud/ocis/issues/9084
- :computer:

fix: local docker compose setup not working with app-providers

---

tests/e2e/cucumber/features/app-provider/lock.feature
tests/e2e/cucumber/steps/ui/shares.ts
tests/e2e/support/objects/app-files/share/index.ts

The file is opened with `Collabora` and `then` step is checked with `OnlyOffice` so the selector of `OnlyOffice` is not found in `collabora` editor. 
The failure arose after this PR https://github.com/owncloud/web/pull/10873 .
- Fixes https://github.com/owncloud/web/issues/10880
- Locally
- :robot:

[full-ci] [tests-only] Fixed failure in lock test

---

changelog/unreleased/bugfix-idp-logout-issues
packages/web-runtime/src/services/auth/authService.ts

Fixes falsely showing the logout page after opening ownCloud Web with an expired token. The issue seemed to be related to the fact that we manually logged out the user after token expiry, whereas the correct way is to let the IDP auth flow handle this. There is no need for a custom implementation on our side.
Also removes the threshold because it doesn't really make sense IMO. Either the token is expired, or it's still valid.
- refs https://github.com/owncloud/enterprise/issues/6639
- refs https://github.com/owncloud/enterprise/issues/6560
- refs https://github.com/owncloud/enterprise/issues/6627

fix: idp logout issues

---

package.json
packages/web-app-admin-settings/package.json
packages/web-app-external/package.json
packages/web-app-files/package.json
packages/web-app-files/tests/unit/HandleUpload.spec.ts
packages/web-app-ocm/package.json
packages/web-app-text-editor/package.json
packages/web-pkg/package.json
packages/web-runtime/package.json
pnpm-lock.yaml

I contributed a little patch upstream to remove vitepress from the dependency chain, it reduces the noise in the install logs quite a bit

Update vue-concurrency and bump required node version (plus types) to sort out peer dependency warnings

---

changelog/unreleased/bugfix-context-menu-empty-in-tiles-view
packages/web-pkg/src/components/FilesList/ResourceTiles.vue

- Fixes https://github.com/owncloud/web/issues/10793
- test case 1:
- test case 2:
- ...

Fix context menu empty on button click in tiles view

---

docs/extension-system/extension-types/actions.md
docs/extension-system/extension-types/folder-view.md
docs/extension-system/extension-types/left-sidebar-menu-item.md
docs/extension-system/extension-types/right-sidebar-panels.md
docs/extension-system/extension-types/search.md

As per title.
- Fixes https://github.com/owncloud/web/issues/9892

docs: add examples for extension types

---

changelog/unreleased/bugfix-oc-modal-scroll-small-screens
packages/design-system/src/components/OcModal/OcModal.vue

Fix 10814: Make OcModal vertically scrollable

---

changelog/unreleased/enhancement-display-hidden-resources-information-in-files-list
packages/web-app-files/src/components/FilesList/ListInfo.vue
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-pkg/src/composables/piniaStores/resources.ts
tests/e2e/cucumber/features/smoke/personalSpacePagination.feature
tests/e2e/cucumber/features/spaces/pagination.feature

- Fixes https://github.com/owncloud/web/issues/9036
- test case 1:
- test case 2:
- ...

Show hidden files and folders count in file info

---

packages/web-client/src/webdav/constants/dav.ts

Adding `photo` and `image` props to the by default requested dav props. This will enable us to write extensions about image and photo metadata (e.g. an `ExifPanel` for the right sidebar).
Can be merged without the ocis and reva counterparts. Will only deliver results when https://github.com/cs3org/reva/pull/4684 and https://github.com/owncloud/ocis/pull/8504 are merged.
Intentionally didn't add a changelog item because there is no user facing value to this.

feat: add image and photo to dav default requested props

---

.drone.env
tests/e2e/support/objects/app-files/spaces/actions.ts

- Bump latest ocis stable commit id
- Added `waitFor()` to wait for an element after navigating to a project space
Fixes: https://github.com/owncloud/ocis/issues/9170

[tests-only][full-ci] bump latest ocis stable-5.0 commit id

---

packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersPanel.vue
packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/MembersPanel.spec.ts
packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/__snapshots__/MembersPanel.spec.ts.snap
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-client/src/helpers/space/functions.ts
packages/web-client/src/helpers/space/types.ts

Adds the new secure view role to our space roles.
With the new permission and role concept it doesn't feel too great to have these roles "hard-coded" in a space... Especially since the addition of the new role broke Web (see https://github.com/owncloud/ocis/issues/9128#issuecomment-2114750861). But that's something for https://github.com/owncloud/web/issues/10770 I guess.
- refs https://github.com/owncloud/ocis/issues/9128

feat: add secure viewer to space roles

---

.drone.env
tests/e2e/cucumber/features/app-provider/officeSuites.feature

Part of https://github.com/owncloud/QA/issues/852

[tests-only][full-ci] bump ocis commit id - master

---

changelog/unreleased/bugfix-resource-deselection-on-right-click
packages/web-app-files/src/views/spaces/GenericSpace.vue

Prevents the currently selected resource from being deselected when right-clicking any empty space inside the files table.
- Fixes https://github.com/owncloud/web/issues/10918

fix: prevent resource deselection when right-clicking empty space

---

changelog/unreleased/bugfix-space-not-updating
packages/web-app-files/src/HandleUpload.ts
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/components/Spaces/WhitespaceContextMenu.vue
packages/web-app-files/src/composables/keyboardActions/useKeyboardTableSpaceActions.ts
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/tests/unit/HandleUpload.spec.ts
packages/web-pkg/src/components/AppBar/AppBar.vue
packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewFile.ts
packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewFolder.ts
packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewShortcut.ts
packages/web-pkg/src/composables/breadcrumbs/useBreadcrumbsFromPath.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateNewFile.spec.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateNewFolder.spec.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateNewShortcut.spec.ts
packages/web-pkg/tests/unit/composables/breadcrumbs/useBreadcrumbsFromPath.spec.ts

Fixes an issue where the current space did not update when navigating from one space into another directly, e.g. via search results. That could lead to uploads and file actions not working properly.
- Fixes https://github.com/owncloud/web/issues/10941

fix: space reactivity on space navigation

---

tests/e2e/cucumber/features/app-provider/officeSuites.feature

- Added one step in https://github.com/owncloud/web/pull/10892 for testing anonymous user seeing the content changed by file creator in real-time
- Part of: https://github.com/owncloud/web/issues/10750
- Locally

[tests-only][full-ci] refactor(test): add e2e test for anonymous user seeing the content changed by file creator in real-time

---

tests/e2e/cucumber/features/app-provider/officeSuites.feature
tests/e2e/support/objects/app-files/resource/actions.ts

This test ensures that: 
- when a file shared with "Can view" permission by file creator using sidebar panel is opened by sharee, the sharee can not change content of file
- when a file shared with "Can edit" permission by file creator using sidebar panel is opened by sharee, the sharee can change content of file and the changes are seen in real-time in both Collabora and OnlyOffice environments .
- Part of https://github.com/owncloud/web/issues/10750
- Locally

[tests-only][full-ci] add e2e test to view real time update of content by real/loggedIn user

---

.drone.env

Bump ocis commit id to the latest for tests
Part of https://github.com/owncloud/QA/issues/852

[tests-only][full-ci] bump ocis commit id - stable

---

docs/testing/testing.md

This PR adds documentation to run e2e tests on ocis with keycloak locally.
- https://github.com/owncloud/web/issues/10458
- test case 1:
- test case 2:
- ...

[docs-only] Add documentation for running e2e tests on keycloak

---

.drone.star
tests/e2e/cucumber/features/admin-settings/spaces.feature
tests/e2e/cucumber/steps/api.ts
tests/e2e/support/api/keycloak/user.ts
tests/e2e/support/api/provision/user.ts
tests/e2e/support/types.ts

- Keycloak supports assigning multiple realm roles to a user but oCIS supports only one role for a user. 
If multiple roles are assigned to a user in Keycloak, oCIS map the highest priority role among Keycloak assigned roles.
So, before assigning role we have to unassign previous role using keycloak api. This part has been implemented in this PR.
- added more tests to run on CI admin-settings/users.feature:20 related to quota change
- https://github.com/owncloud/web/issues/10458
- LOCALLY

[tests-only][full-ci]Run more e2e tests on keycloak

---

changelog/unreleased/bugfix-local-logout
packages/web-pkg/src/composables/authContext/useAuthService.ts
packages/web-runtime/src/components/Topbar/UserMenu.vue
packages/web-runtime/src/pages/accessDenied.vue
packages/web-runtime/src/pages/logout.vue
packages/web-runtime/src/services/auth/authService.ts
packages/web-runtime/src/services/auth/userManager.ts
packages/web-runtime/tests/unit/pages/__snapshots__/accessDenied.spec.ts.snap

There are IdPs without an `endSessionEndpoint` (e.g. Authelia). In those cases we just need to unload the currently authenticated user.
- Fixes https://github.com/owncloud/enterprise/issues/6631
Hardening.

fix: remove user locally if no logout url in IdP

---

packages/web-app-external/src/App.vue

Fixing the case that the app name for the app provider has e.g. a space in it.

fix: encode app name for app provider

---

packages/web-client/src/helpers/space/functions.ts

I noticed that for the space member checks we first map all users of a role to the result of `isMember`, checking whether the given user is member of that specific space role, and only after that early return with the first boolean `true` we find. So we always run through the whole array once and then again until the first `true` value is hit. The computation complexity can be reduced to doing the early return with the `isMember` check, so we only run once through the list of users in a space role  and early return if `isMember` evaluates to `true`. For spaces with large amounts of members this is a tiny improvement. 😁 
- Relates to https://github.com/owncloud/web/issues/6660

perf: early return space member checks

---

dev/docker/ocis/csp.yaml
tests/drone/csp.yaml

Adds `blob:` as possible entry for `frame-src` to allow opening pdf files, since those are being embedded as a blob.

fix: opening pdf files

---

packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts

Wrapping file name in quotes in modal title (in this case: permanent deletion from trash for a file or folder).
- Fixes https://github.com/owncloud/web/issues/8122

fix: wrap file name in quotes in modal title

---

packages/web-runtime/src/index.ts

loading role permissions is shadowed by a early return which get triggered if the user does not have a personal space.
In some cases, for example if the logged in user is of type (role), user-light, this is a valid use-case.
This is fixed by the pr, but we have to discuss (and test) possible side effects of the change.
- ci
- manuell testing

fix: viewer light role permission loading

---

changelog/unreleased/enhancement-audio-metadata-panel
changelog/unreleased/enhancement-exif-panel
docs/getting-started.md
packages/web-app-files/src/components/SideBar/Audio/AudioMetaPanel.vue
packages/web-app-files/src/components/SideBar/Exif/ExifPanel.vue
packages/web-app-files/src/composables/extensions/useFileSideBars.ts
packages/web-app-files/tests/unit/components/SideBar/Audio/AudioMetaPanel.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Exif/ExifPanel.spec.ts
packages/web-client/src/helpers/resource/functions.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-pkg/src/composables/piniaStores/config/config.ts
packages/web-pkg/src/composables/piniaStores/config/types.ts

This PR introduces an `EXIF` panel, which displays image, photo and location metadata if that's available on the given resource as well as an `Audio Info` panel, which displays audio metadata if that's available on the given resource.
- Relates to https://github.com/owncloud/web/issues/7930
Provide useful additional information.

Exif and audio panels

---

.drone.star
tests/e2e/config.js
tests/e2e/cucumber/environment/world.ts
tests/e2e/support/environment/actor/actor.ts
tests/e2e/support/environment/actor/shared.ts

related https://github.com/owncloud/web/issues/6397
In this PR I check console error and put error to output 
example: 
Until we fix all `uncaught errors` we don't interrupt tests if console error occurs
In order to abort tests when an uncaught error occurs, we need to:
- use `FAIL_ON_UNCAUGHT_CONSOLE_ERR=true pnpm test:e2e:cucumber tests/e2e/cucumber/features/` if you are running the test locally
- use `[check-console-errors]` in the PR header to abort the test in CI if a console error occurs
this is what CI looks if PR header contains `[check-console-errors]`
https://drone.owncloud.com/owncloud/web/44914
I only display the error text. you can find all the error details in the trace (open trace all users. the error often appears for a different user than the one who did the last action). …

[full-ci]show console errors in e2e tests

---

.drone.star

related: https://github.com/owncloud/web/issues/11011
after fixing all console errors https://github.com/owncloud/web/pull/11024 we can set `FAIL_ON_UNCAUGHT_CONSOLE_ERR=true` by default except of `app-provider` suite because https://github.com/owncloud/web/issues/11011#issuecomment-2160141008

[full-ci] fail the test if there is a console error

---

packages/web-app-admin-settings/src/components/Users/AddToGroupsModal.vue
packages/web-app-admin-settings/src/components/Users/CreateUserModal.vue
packages/web-app-admin-settings/src/components/Users/LoginModal.vue
packages/web-app-admin-settings/src/components/Users/RemoveFromGroupsModal.vue
packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/components/Users/AddToGroupsModal.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/CreateUserModal.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/LoginModal.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/RemoveFromGroupsModal.spec.ts
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/EditPanel.spec.ts
packages/web-app-admin-settings/tests/unit/views/Users.spec.ts
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.spec.ts
packages/web-client/src/graph/index.ts
packages/web-client/src/graph/types.ts
packages/web-client/src/graph/users/index.ts
packages/web-client/src/graph/users/types.ts
packages/web-client/src/graph/users/users.ts
packages/web-runtime/src/components/EditPasswordModal.vue
packages/web-runtime/src/pages/account.vue
packages/web-runtime/src/services/auth/userManager.ts
packages/web-runtime/tests/unit/pages/account.spec.ts

Refactors the graph abstraction layer for users to make it more practical and convenient to use.
The new implementation has improved method parameters, types and destructures API responses so users of the abstraction don't need to care about such things.
This is the first PR of a whole series, groups will be next. I currently work on it when I have some spare time, although it would be nice to have this completed for the `9.0.0` release (especially now that we decided to couple web-client releases to Web releases).
- refs https://github.com/owncloud/web/issues/10808

refactor: useful graph abstraction for users

---

tests/e2e/cucumber/features/app-provider/officeSuites.feature
tests/e2e/support/objects/app-files/resource/actions.ts

tests for https://github.com/owncloud/ocis/issues/8691 and https://github.com/owncloud/ocis/issues/8834

[full-ci] createing .odt .docx file using public link

---

package.json
pnpm-lock.yaml
tests/e2e/cucumber/features/shares/share.feature
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/share/collaborator.ts

page.keyboard.press('Control+A') didn't work on macOs, so we had to change it to page.keyboard.press('Meta+A') to run locally.
This has been fixed in the latest version, so now we can use it like await page.keyboard.press('ControlOrMeta+A')

[test-only]use universal ctrl-meta modifier

---

changelog/unreleased/enhancement-page-loading-times
packages/web-pkg/src/apps/types.ts
packages/web-pkg/src/composables/piniaStores/apps.ts
packages/web-runtime/src/container/api.ts
packages/web-runtime/src/container/application/classic.ts
packages/web-runtime/src/container/application/index.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/container/types.ts
packages/web-runtime/src/helpers/customTranslations.ts
packages/web-runtime/src/helpers/language.ts
packages/web-runtime/src/index.ts
packages/web-runtime/src/pages/account.vue
packages/web-runtime/src/services/auth/userManager.ts
packages/web-runtime/tests/unit/container/bootstrap.spec.ts

Changes the way how app languages get set in `gettext` so only the current language is being considered initially. Other languages will be set dynamically when changing the current language.
Also refactors the language setup process a bit to make it simpler.
`announceGettext` sets up gettext in our Vue app, without any translations yet though. `announceTranslations` gets called later during the bootstrap process and provides all translations to `gettext`: the ones for core, additional ones and the ones for the apps for the current language. That way we have all that stuff in one place.
- refs https://github.com/owncloud/web/issues/11035

perf: prevent setting all languages for all apps on initial load

---

packages/web-client/src/helpers/httpError.ts
packages/web-client/src/helpers/index.ts
packages/web-pkg/src/composables/actions/files/useFileActionsRestore.ts
packages/web-pkg/src/composables/piniaStores/messages.ts
packages/web-pkg/src/composables/webWorkers/index.ts
packages/web-pkg/src/composables/webWorkers/restoreWorker/index.ts
packages/web-pkg/src/composables/webWorkers/restoreWorker/useRestoreWorker.ts
packages/web-pkg/src/composables/webWorkers/restoreWorker/worker.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsRestore.spec.ts
packages/web-pkg/tests/unit/composables/webWorkers/restoreWorker/useRestoreWorker.spec.ts
packages/web-pkg/tests/unit/composables/webWorkers/restoreWorker/worker.spec.ts

Adds a web worker for resource restore operations.
- Fixes https://github.com/owncloud/web/issues/10953

feat: web worker for resource restore

---

.drone.star

This PR remove event from `log-tracing-result` and `upload-tracing-result` so that those step pipleine triggers whenever `e2e-tests-oCIS-x` pipeline triggers
- 
- CI

[full-ci][tests-only]Trigger tracing step pipeline when e2e tests run on CI

---

packages/web-runtime/src/helpers/language.ts

It's probably not happening in reality for production, but might occur during development, that an app has no translations. In that case the bootstrapping process would fail hard because translations were not optional.
Keep DX as easy as possible.

fix: keep translations of apps optional

---

tests/e2e/support/objects/app-files/share/collaborator.ts

I'm not very happy with my current solution, but it can unlock you @kulmann quickly. 
this is what happens: 
https://github.com/owncloud/web/assets/84779829/2cb5f01d-e3f1-4b94-8c3c-2a7098f3f978
after setting timeout this behavior doesn't exist

[test-only] fix test expiration date

---

changelog/unreleased/enhancement-consistent-initial-loading-spinner
index.html
packages/web-runtime/src/index.ts

This change makes sure that the loading spinner on the initial page load gets displayed consistently during the bootstrap of the client. The spinner gets hidden eventually after all apps have been announced as ready.
Also aligns the spinner design with all the other loading spinners and reduces the delay before showing it from 1 to 0.5 seconds.
- Fixes https://github.com/owncloud/web/issues/11041
- Run `pnpm build:w`
- Throttle your network to e.g. "Fast 3G"
- (Re-)load the page

feat: show consistent initial loading spinner

---

changelog/unreleased/bugfix-resetting-user-after-logout
packages/web-pkg/src/composables/piniaStores/user.ts
packages/web-runtime/src/services/auth/authService.ts

- Fixes https://github.com/owncloud/web/issues/11055

fix: user reset after logout

---

changelog/unreleased/bugfix-editor-save-after-token-renewal
packages/web-pkg/src/composables/appDefaults/useAppFileHandling.ts

The issue existed because the `ClientService` had been destructured, which lead to the request headers not being reactive.
- Fixes https://github.com/owncloud/web/issues/11062

fix: editor save after token renewal

---

docker-compose.yml

Since ocis daily builds are now available on [owncloud/ocis-rolling:master](https://hub.docker.com/r/owncloud/ocis-rolling/tags), this PR changes the docker image to the rolling one where ocis daily builds are available.
During web development, we were using daily builds so this change ensures that daily builds are up-to-date with `docker compose pull`

chore: use ocis-rolling docker image for development

---

tests/e2e/cucumber/environment/index.ts
tests/e2e/support/environment/sse.ts

Created one `AbortController` for each sse connection and added the controller to the list. This helps to close each sse connections properly. 
- Fixes https://github.com/owncloud/web/issues/11016
- :hand: :computer:

[tests-only][full-ci] properly close the sse connections

---

.drone.env

running all e2e tests as part of rolling release testing https://github.com/owncloud/ocis/issues/9391

[full-ci]bump ocis commit id

---

packages/web-app-preview/src/App.vue
packages/web-app-preview/src/components/Sources/MediaImage.vue
packages/web-app-preview/src/index.ts
packages/web-app-preview/tests/unit/app.spec.ts
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
tests/e2e/support/objects/app-files/resource/actions.ts

Makes use of the `AppWrapper` component in the preview app. This reduces boilerplate code in the app and enables the context menu in the app bar.
The resource loading still happens in the preview app because it's heavily tied to it. The loading in the `AppWrapper` is being bypassed during this.
- Fixes https://github.com/owncloud/web/issues/11065

refactor: use AppWrapper for preview app

---

changelog/unreleased/bugfix-enforce-shortcut-url-protocol
packages/web-pkg/src/components/CreateShortcutModal.vue

If the user types a URL without protocol and doesn't click on the proposed URL in the dropdown (which would include `https://` as protocol), the resulting .url file wouldn't have a protocol in the URL. This PR fixes that by enforcing `https://` as prefix for the user input if none was given. Technically this would've been possible by using `unref(dropItemUrl)` instead of `unref(inputUrl)`, but I've decided to extract the body of `dropItemUrl` into a function and use that, because it would be confusing to use `dropItemUrl` as the final input on confirm.
- Fixes https://github.com/owncloud/web/issues/11063
Enforce url protocol so that mobile clients won't have trouble opening the URLs.

fix: enforce protocol in shortcut urls

---

changelog/unreleased/enhancement-reduce-network-load-on-token-renewal
packages/design-system/src/index.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/defaults/index.ts
packages/web-runtime/src/helpers/silentRedirect.ts
packages/web-runtime/src/index.ts
packages/web-runtime/src/pages/oidcCallback.vue
packages/web-runtime/src/pages/tokenRenewal.vue
packages/web-runtime/src/services/auth/authService.ts

Reduces the network load on token renewal by not bootstrapping the whole application. Parts that are skipped loading during token renewal are:
* loading applications
* loading the inter font
* loading translations
* loading the theme
- Fixes https://github.com/owncloud/web/issues/11069
Network load during token renewal - **before**:
Network load during token renewal - **after**:

perf: reduce network load on token renewal

---

changelog/unreleased/enhancement-enable-default-editor-autosave
packages/web-pkg/src/composables/piniaStores/config/config.ts

As per title.
- Fixes https://github.com/owncloud/web/issues/11090

feat: enable default autosave in editors

---

packages/web-app-external/package.json
packages/web-app-external/src/App.vue
packages/web-app-external/src/Redirect.vue
packages/web-app-external/src/index.ts
packages/web-app-external/src/piniaStores/applicationReady.ts
packages/web-app-external/src/piniaStores/index.ts
packages/web-app-external/tests/unit/app.spec.ts
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/tests/unit/components/AppBar/__snapshots__/CreateAndUpload.spec.ts.snap
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
packages/web-pkg/src/composables/actions/files/useFileActions.ts
packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewFile.ts
packages/web-pkg/src/composables/appProviderService/index.ts
packages/web-pkg/src/composables/appProviderService/useAppProviderService.ts
packages/web-pkg/src/composables/index.ts
packages/web-pkg/src/services/appProvider/index.ts
packages/web-pkg/src/services/appProvider/schemas.ts
packages/web-pkg/src/services/appProvider/service.ts
packages/web-pkg/src/services/index.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateNewFile.spec.ts
packages/web-runtime/src/container/application/classic.ts
packages/web-runtime/src/container/application/index.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/index.ts
packages/web-runtime/tests/unit/container/bootstrap.spec.ts
pnpm-lock.yaml

Dynamically register one instance of the `external` app per app provider app.
No special handling for `open file in editor/viewer` actions anymore.

Dynamic app provider apps

---

changelog/unreleased/enhancement-accessibility-improvements
packages/design-system/src/components/OcContextualHelper/OcContextualHelper.vue
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
packages/web-app-files/src/components/Spaces/WhitespaceContextMenu.vue
packages/web-pkg/src/components/CreateLinkModal.vue

Add missing aria-labels for OcDrops, hide WhiteSpaceContextMenu from screenreader

---

changelog/unreleased/bugfix-opening-public-links-with-expired-token
packages/web-runtime/src/pages/resolvePublicLink.vue
packages/web-runtime/src/services/auth/authService.ts

Fixes bug where opening public links with an expired token would falsely show the access denied page. Instead, Web now tries to login the user. If that doesn't work, the user gets logged out.
- Fixes https://github.com/owncloud/enterprise/issues/6734

fix: visiting public links with expired access token

---

changelog/unreleased/bugfix-browser-confirmation-after-closing-editor
changelog/unreleased/bugfix-button-focus-closing-editor
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
packages/web-runtime/src/App.vue
packages/web-runtime/src/store/modal.ts

* fix: button focus when closing editor with unsaved changes
* fix: browser confirmation dialog after closing editor
- fixes https://github.com/owncloud/web/issues/11091
- fixes https://github.com/owncloud/web/issues/11092

fix: issues with closing editor in dirty state

---

changelog/unreleased/bugfix-keyboard-navigation-breaking
packages/web-pkg/src/composables/keyboardActions/useKeyboardActions.ts

Fixes the keyboard navigation breaking in certain scenarios.
The issue was that `window.getSelection()` would not always return the currently focused element when checking if we need to disable our custom keybindings. So e.g. when clicking the search input and then clicking a file in the file list, the focused element would still be the search input, leading to our keybindings not working.
- Fixes https://github.com/owncloud/web/issues/10942

fix: keyboard navigation breaking

---

changelog/unreleased/bugfix-secure-view-default-action
packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/src/components/FilesList/ResourceTiles.vue
packages/web-pkg/src/composables/resources/index.ts
packages/web-pkg/src/composables/resources/useCanBeOpenedWithSecureView.ts
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
packages/web-pkg/tests/unit/composables/resources/useCanBeOpenedWithSecureView.spec.ts

Prevents files that have been shared via secure view without having a compatible app to view such (or the file type is not supported) from being clicked.
- Fixes https://github.com/owncloud/web/issues/11138

fix: secure view default action

---

tests/e2e/support/objects/app-files/share/collaborator.ts
tests/e2e/support/objects/app-files/utils/editor.ts

https://playwright.dev/docs/api/class-page#page-wait-for-navigation is deprecated. I changed it for `page.waitForURL`

[test-only]delete deprecated playwright method

---

changelog/unreleased/bugfix-duplicated-ui-elements-public-link
packages/web-pkg/src/composables/actions/files/useFileActionsCopy.ts
packages/web-pkg/src/composables/actions/files/useFileActionsPaste.ts
packages/web-pkg/src/composables/piniaStores/extensionRegistry/extensionRegistry.ts
packages/web-pkg/tests/unit/composables/piniaStores/extensionRegistry/extensionRegistry.spec.ts
packages/web-runtime/src/layouts/Application.vue
packages/web-runtime/src/services/auth/authService.ts

Fixes a bug where clicking the ownCloud logo on a public link page would lead to certain UI elements being duplicated.
This happens because some extensions and extension points are being registered more than once because the application layout gets unmounted on mounted again when clicking the logo. The solution is to properly unregister those extensions on unmount.
- Fixes https://github.com/owncloud/web/issues/10371

fix: duplicated elements on public link page

---

tests/e2e/cucumber/features/app-provider/urlJourneys.feature

return back skipped tests for url stability for mobile and desktop
close all releated issue after merging:  
- https://github.com/owncloud/web/issues/11129
- https://github.com/owncloud/web/issues/11116

[full-ci]unskipUrlTests

---

packages/web-app-admin-settings/src/views/Groups.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/views/Users.spec.ts
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-client/src/graph/types.ts

As per title. This allows those requests to be cancelled when a task is being cancelled/restarted.
- Fixes https://github.com/owncloud/web/issues/6517

feat: add abort signals when listing users/groups

---

packages/web-client/src/webdav/clearTrashBin.ts
packages/web-client/src/webdav/client/dav.ts
packages/web-client/src/webdav/copyFiles.ts
packages/web-client/src/webdav/createFolder.ts
packages/web-client/src/webdav/deleteFile.ts
packages/web-client/src/webdav/getFileContents.ts
packages/web-client/src/webdav/getFileUrl.ts
packages/web-client/src/webdav/getPathForFileId.ts
packages/web-client/src/webdav/listFavoriteFiles.ts
packages/web-client/src/webdav/listFileVersions.ts
packages/web-client/src/webdav/listFiles.ts
packages/web-client/src/webdav/listFilesById.ts
packages/web-client/src/webdav/moveFiles.ts
packages/web-client/src/webdav/putFileContents.ts
packages/web-client/src/webdav/restoreFile.ts
packages/web-client/src/webdav/restoreFileVersion.ts
packages/web-client/src/webdav/search.ts
packages/web-client/src/webdav/setFavorite.ts

Adds the option to pass headers and signals to all dav requests. This lays the groundwork for cancelling dav requests.
- refs https://github.com/owncloud/web/issues/11154

feat: add headers and signals to dav implementation

---

.drone.env

run e2e with different deployment: 
this is part of the release process https://github.com/owncloud/ocis/issues/9558

[tests-only][full-ci] bump ocis commit id

---

changelog/unreleased/enhancement-add-share-role-icon-to-shared-with-me-table
packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
packages/web-pkg/src/components/FilesList/ResourceTable.vue

- Fixes https://github.com/owncloud/web/issues/11101
- test case 1:
- test case 2:
- ...

Rename status column to info column, add share role icon

---

packages/web-app-files/src/views/spaces/DriveResolver.vue
packages/web-app-files/tests/unit/views/spaces/DriveResolver.spec.ts
packages/web-runtime/src/pages/resolvePublicLink.vue
packages/web-runtime/tests/unit/pages/resolvePublicLink.spec.ts

Reduces the amount of dav requests when resolving public links from 5 to 2. This is the least we can go since the first request is being used to correctly resolve the link and the second one is being used to list the content.
- Fixes https://github.com/owncloud/web/issues/10870

fix: multiple dav requests on public link page

---

.drone.env

Bump latest ocis stable commit id.
Part of: https://github.com/owncloud/QA/issues/856

[tests-only][full-ci]bump latest ocis stable commit id

---

.drone.star
docker-compose.yml
tests/e2e/cucumber/features/app-provider/officeSuites.feature

[full-ci] enable secure view test

---

tests/e2e/cucumber/features/file-action/download.feature

As per title. This makes sure that regressions like https://github.com/owncloud/web/issues/11169 are found immediately.
- Fixes https://github.com/owncloud/web/issues/11169

test: use file name with blanks in download e2e test

---

.gitignore
docker-compose.yml

Adds an `apps` folder for the dev stack and automatically mounts it in the docker compose stack, using it as ocis web apps folder. This is supposed to make it easier to test third party apps in our dev stack.

feat: add apps folder for dev setup

---

packages/web-app-external/src/Redirect.vue
packages/web-app-external/src/index.ts
packages/web-pkg/src/services/appProvider/service.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/index.ts

Since the ocis backend guarantees that the /app/list endpoint exists we can hardcode the url and initialize the app provider apps before the vue-router is being initialized. This saves us a redirect on page reload in an app provider app, because we don't have to wait for the capabilities being loaded before fetching the app provider app listing.
See https://github.com/owncloud/ocis/issues/9489 for server requirements (were already fulfilled without us realising it :-) ).
Reduce bootstrap complexity.

[full-ci] refactor: initialize app provider apps earlier

---

.drone.env
tests/e2e/cucumber/steps/ui/spaces.ts

related https://github.com/owncloud/ocis/pull/9621
now we download zip by default

use zip instead of tar in the e2e

---

packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.ts
packages/web-pkg/src/composables/actions/files/useFileActionsPaste.ts
packages/web-pkg/src/composables/piniaStores/resources.ts
packages/web-pkg/src/composables/piniaStores/shares/shares.ts
packages/web-pkg/tests/unit/composables/piniaStores/resources.spec.ts

Changes the computing of share types and loading share indicators to work id-based instead of path-based.
This is a prerequisite for having id-based webdav requests in the future.
- Works towards https://github.com/owncloud/web/issues/9786

refactor: id-based share indicators

---

packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.spec.ts
packages/web-client/src/graph/index.ts
packages/web-client/src/graph/permissions/index.ts
packages/web-client/src/graph/permissions/permissions.ts
packages/web-client/src/graph/permissions/types.ts
packages/web-client/src/helpers/share/functions.ts
packages/web-client/tests/unit/helpers/share/functions.spec.ts
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/src/composables/actions/files/useFileActionsCopyQuicklink.ts
packages/web-pkg/src/composables/piniaStores/shares/shares.ts
packages/web-pkg/src/composables/piniaStores/spaces.ts
packages/web-pkg/tests/unit/components/sidebar/FileSideBar.spec.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCopyQuicklink.spec.ts
packages/web-pkg/tests/unit/composables/piniaStores/shares.spec.ts
packages/web-pkg/tests/unit/composables/piniaStores/spaces.spec.ts
packages/web-runtime/src/index.ts

Refactors the graph abstraction layer for permissions (= shares) to make them more practical and convenient to use.
The new implementation has improved method parameters, types and destructures API responses so users of the abstraction don't need to care about such things.
- fixes https://github.com/owncloud/web/issues/10808
- refs https://github.com/owncloud/web/issues/11167

refactor: make graph abstraction layer useful for permissions

---

packages/web-app-files/src/components/SideBar/Exif/ExifPanel.vue
packages/web-app-files/tests/unit/components/SideBar/Exif/ExifPanel.spec.ts
packages/web-pkg/src/composables/piniaStores/config/config.ts
packages/web-pkg/src/composables/piniaStores/config/types.ts

- Fixes https://github.com/owncloud/web/issues/11213
- test case 1:
- test case 2:
- ...

Purge config option options.sidebar.exif.showLocation

---

.drone.env

Bump latest ocis stable commit id.
Part of: https://github.com/owncloud/QA/issues/856

[tests-only][full-ci] bump ocis stable commit id

---

packages/web-app-files/src/composables/actions/spaces/useSpaceActionsUploadImage.ts
packages/web-app-files/tests/unit/composables/actions/spaces/useSpaceActionsUploadImage.spec.ts
packages/web-client/src/helpers/space/functions.ts
packages/web-client/src/webdav/utils.ts
packages/web-pkg/src/composables/actions/files/useFileActionsSetImage.ts
packages/web-pkg/src/composables/actions/files/useFileActionsSetReadme.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsEditReadmeContent.ts
packages/web-pkg/src/composables/actions/spaces/useSpaceActionsSetIcon.ts
packages/web-pkg/src/composables/spaces/useCreateSpace.ts
packages/web-pkg/src/composables/spaces/useSpaceHelpers.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsSetImage.spec.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsSetReadme.spec.ts
packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsEditReadmeContent.spec.ts

Refactors setting/updating space image and readme data to work id-based. The big difference is that we need to retrieve the id of the `.space` meta folder so it can be used for the requests.
Also fixes an issue in scenarios where we want to list files for a space root where no `fileId` and no `path` are being provided. We need to fall back to the space id in such case.
- works towards https://github.com/owncloud/web/issues/9786

refactor: setting space image and readme data id-based

---

packages/web-client/src/errors.ts
packages/web-client/src/webdav/client/dav.ts
packages/web-client/src/webdav/client/parsers.ts
packages/web-client/src/webdav/constants/dav.ts
packages/web-runtime/src/pages/resolvePublicLink.vue
packages/web-runtime/tests/unit/pages/resolvePublicLink.spec.ts

Failed dav requests now throw a new `DavHttpError`, which extends our regular `HttpError` and additionally contains a potential error code from the server response.

feat: parse dav error codes in web-client 

---

.drone.env
tests/e2e/cucumber/features/app-provider/secureView.feature
tests/e2e/cucumber/features/shares/share.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

[full-ci] user should not see thumbnail and preview for secure view file

---

dev/docker/ocis.web-federated.config.json
dev/docker/ocis.web.config.json
docs/getting-started.md
packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/FileLinks.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/SpaceMembers.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap
packages/web-app-files/tests/unit/components/SideBar/TagsSelect.spec.ts
packages/web-pkg/src/composables/piniaStores/config/config.ts
packages/web-pkg/src/composables/piniaStores/config/types.ts
tests/drone/config-ocis.json
tests/e2e/support/objects/app-files/share/actions.ts

- Fixes #11212 
- test case 1:
- test case 2:
- ...

Purge config option options.sidebar.shares.showAllOnLoad

---

changelog/unreleased/change-remove-deprecated-config-options
tests/drone/config-ocis.json

- test case 1:
- test case 2:
- ...

Add changelog item for deprecated config options

---

tests/e2e/cucumber/features/smoke/tags.feature
tests/e2e/support/objects/app-files/utils/sidebar.ts

Create required resources via API steps.
The flakiness reported in https://github.com/owncloud/web/issues/11246 was due to sidebar being refreshed - maybe due to post-processing activity updates which led the inserted tags to disappear.
- Fixes https://github.com/owncloud/web/issues/11246
- :raised_back_of_hand:

[tests-only][full-ci] create resources via API steps

---

changelog/unreleased/bugfix-show-more-toggle-text-in-space-members-view-not-reactive
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue

- Fixes https://github.com/owncloud/web/issues/11261
- test case 1:
- test case 2:
- ...

Make show more button toggle text in space member view reactive

---

changelog/unreleased/bugfix-space-show-links-from-other-spaces
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-test-helpers/src/mocks/store/filesModuleMockOptions.ts

- Fixes #11262 
- test case 1:
- test case 2:
- ...

Prune shares when we enter a project space view, to avoid showing quick link from another space

---

packages/web-app-preview/src/App.vue
packages/web-app-preview/src/components/MediaControls.vue
packages/web-app-preview/src/composables/index.ts
packages/web-app-preview/src/composables/useFileTypes.ts
packages/web-app-preview/src/composables/useFullScreenMode.ts
packages/web-app-preview/src/composables/useImageControls.ts
packages/web-app-preview/src/composables/usePreviewDimensions.ts
packages/web-app-preview/src/helpers/types.ts
packages/web-app-preview/tests/unit/app.spec.ts
packages/web-app-preview/tests/unit/components/MediaControls.spec.ts
packages/web-pkg/src/services/preview/previewService.ts

I noticed that if preloaded images failed loading then we wouldn't show an error state for the image, but we'd have a broken `<img>` instead. So I refactored the loading- and error-states to be individual for each file. And then I refactored more. And more... there's more to refactor (options-api to composition api, putting data loading into a composable, etc), but I don't want to spend more time on it now. Hope the current state is an improvement over current master.
This can be tested easily by starting ocis with `THUMBNAILS_MAX_INPUT_IMAGE_FILE_SIZE=500KB` and then upload some images with 100kb, some with 2mb and then cycle through the folder within the preview app. :-)
This also now makes sure that the file navigation controls are visible on files with loading- or error-state. …

refactor: maintain loading and error state per file

---

docs/extension-system/viewer-editor-apps.md
packages/web-app-admin-settings/src/index.ts
packages/web-app-external/src/index.ts
packages/web-app-files/src/extensions.ts
packages/web-app-files/src/index.ts
packages/web-app-ocm/src/extensions.ts
packages/web-app-ocm/src/index.ts
packages/web-app-search/src/index.ts
packages/web-app-text-editor/src/index.ts
packages/web-app-webfinger/src/index.ts
packages/web-pkg/src/apps/types.ts
packages/web-pkg/src/composables/actions/index.ts
packages/web-pkg/src/composables/actions/useOpenEmptyEditor.ts
packages/web-pkg/src/composables/piniaStores/extensionRegistry/types.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActions.spec.ts
packages/web-runtime/src/components/Topbar/TopBar.vue
tests/e2e/support/objects/runtime/application.ts

Refactors apps to use the new `appMenuItem` extension point instead of the deprecated `applicationMenu` property.
Also deprecates 2 unused app info properties: `type` and `isFileEditor`.
- refs https://github.com/owncloud/web/issues/11259

refactor: make use of menu items extension point

---

changelog/unreleased/enhancement-add-quota-information-to-account-page
packages/web-runtime/src/components/Account/QuotaInformation.vue
packages/web-runtime/src/components/Topbar/UserMenu.vue
packages/web-runtime/src/pages/account.vue
packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.ts.snap
packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
tests/e2e/support/objects/account/actions.ts

- test case 1:
- test case 2:
- ...

Create quota information component, add to account page

---

changelog/unreleased/bugfix-resource-table-keyboard-checkbox
packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts

As per title.
- Fixes https://github.com/owncloud/web/issues/10730

fix: toggling checkboxes via enter key

---

changelog/unreleased/bugfix-upload-nested-folders
packages/web-app-files/src/HandleUpload.ts

Fixes an issue where the upload overlay breaks when uploading a folder that contains exactly one folder (which then contains some files).
The top level folder did not have an upload id in such case, hence the overlay could not retrieve the correct information.
- Fixes https://github.com/owncloud/web/issues/11299
- Possibly fixes https://github.com/owncloud/web/issues/10492

fix: upload overlay breaking with nested folders

---

changelog/unreleased/enhancement-redesign-share-link-modal
packages/design-system/src/components/OcModal/OcModal.vue
packages/web-app-files/src/components/Modals/SetLinkPasswordModal.vue
packages/web-pkg/src/components/CreateLinkModal.vue
packages/web-pkg/src/composables/actions/files/useFileActionsCopyQuicklink.ts
packages/web-pkg/src/composables/actions/files/useFileActionsCreateLink.ts
packages/web-pkg/src/services/passwordPolicy/passwordPolicy.ts
packages/web-pkg/tests/unit/components/CreateLinkModal.spec.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateLink.spec.ts
packages/web-pkg/tests/unit/services/passwordPolicy.spec.ts
tests/e2e/support/objects/app-files/link/actions.ts
tests/e2e/support/objects/app-files/share/actions.ts

- Fixes https://github.com/owncloud/web/issues/11204
- test case 1:
- test case 2:
- ...

Redesign copy link modal

---

changelog/unreleased/enhancement-redesign-share-link-modal
packages/web-pkg/src/components/CreateLinkModal.vue
packages/web-pkg/src/composables/actions/files/useFileActionsCreateLink.ts

- test case 1:
- test case 2:
- ...

Increase padding on create link password field, change clipboard link

---

changelog/unreleased/bugfix-horizontal-table-scroll
packages/design-system/src/components/OcDrop/OcDrop.vue
packages/web-app-admin-settings/src/components/AppTemplate.vue
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
packages/web-app-admin-settings/src/components/Users/UsersList.vue
packages/web-app-admin-settings/src/views/Groups.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/src/components/FilesList/ListInfo.vue
packages/web-app-files/src/components/Search/List.vue
packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
packages/web-app-files/src/views/shares/SharedWithMe.vue
packages/web-app-files/src/views/spaces/GenericSpace.vue
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/src/views/trash/Overview.vue
packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ListInfo.spec.ts.snap
packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/src/components/ViewOptions.vue
tests/e2e/cucumber/features/shares/link.feature
tests/e2e/cucumber/features/smoke/sse.feature
tests/e2e/cucumber/steps/ui/application.ts
tests/e2e/support/objects/runtime/application.ts

Prevents resource tables from being horizontally scrollable for a11y reasons. Instead, information that is available elsewhere will get hidden on smaller displays.
- Works towards https://github.com/owncloud/web/issues/10728

fix: horizontal resource table scroll

---

Makefile
generate-qa-activity-report.js
package.json
pnpm-lock.yaml

how to run: 
- `make generate-qa-activity-report MONTH=06 YEAR=2024`
or
- `pnpm exec node analyzeChanges.js --month 7 --year 2024`
- `pnpm exec node analyzeChanges.js --days 10`
report should be generated to `QA_Activity_Report.md`
example: 
[QA_Activity_report-07.24.md](https://github.com/user-attachments/files/16503128/QA_Activity_report-07.24.md)

Analyze change

---

packages/web-pkg/src/composables/piniaStores/shares/shares.ts

As per title. Was forgotten in https://github.com/owncloud/web/pull/11188.

fix: share indicator not appearing when adding a new share

---

packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/RoleDropdown.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.ts.snap
packages/web-app-ocm/src/views/IncomingInvitations.vue
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/src/composables/piniaStores/apps.ts
packages/web-pkg/src/composables/scrollTo/useScrollTo.ts
packages/web-pkg/tests/unit/components/sidebar/FileSideBar.spec.ts

Adds a filter inside the collaborator share search input to enable searching for external users.
The available share roles are different for external users, hence there is a clear separation needed between internal and external sharing.
This filter is only available when the OCM app is enabled.
- refs https://github.com/owncloud/ocis/issues/9735
- refs https://github.com/owncloud/ocis/issues/9747

feat: external collaborator search filter

---

packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.spec.ts
packages/web-client/src/graph/permissions/permissions.ts
packages/web-client/src/graph/permissions/types.ts
packages/web-client/src/helpers/share/functions.ts
packages/web-client/tests/unit/helpers/share/functions.spec.ts
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/src/composables/piniaStores/shares/shares.ts
packages/web-pkg/tests/unit/composables/piniaStores/spaces.spec.ts
packages/web-test-helpers/src/mocks/pinia.ts

Refactors the unified graph role definitions from an array to an object because it simplifies the way how to work with those. When retrieving a role via its id (which is 99% of the use cases), it can now be done with the object index instead of looping through the array.
Works towards https://github.com/owncloud/web/issues/10770.

refactor: transform graph roles to object

---

changelog/unreleased/enhancement-replace-custom-datepicker-with-native-element
packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/components/SideBar/Shares/ExpirationDateIndicator.vue
packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
pnpm-lock.yaml

Follow up for https://github.com/owncloud/web/pull/11377
- Fixes 
- test case 1:
- test case 2:
- ...

Follow up: Make set/edit/remove expiry-date-buttons accessible 

---

.editorconfig
changelog/unreleased/enhancement-display-disabled-role-permissions
packages/design-system/src/components/OcInfoDrop/OcInfoDrop.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/RoleDropdown.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.ts.snap

adds a new feature to the sharing sidebar panel which allows you to see the permissions of a role that has been disabled.
- Fixes https://github.com/owncloud/ocis/pull/9727
- Part of https://github.com/owncloud/web/issues/10770

Disabled unified roles

---

pnpm-lock.yaml

Bumps `micromatch` to `v4.0.8`. This at least fixes the security alert in our runtime code.
There is still `vue-styleguidist` though, which has a lot of outdated dependencies like this and doesn't seem to be maintained. I don't see a fix for this when keeping this dependency.
- see https://github.com/owncloud/web/security/dependabot/190

fix(deps): micromatch security alert

---

.drone.env

Bump ocis commit id of stable5.0
Part of: https://github.com/owncloud/QA/issues/860

[tests-only][full-ci] bump ocis latest commit id-stable5.0

---

packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
packages/web-client/src/helpers/share/functions.ts

Prevents the 'Shared With Me'-page from breaking with external shares and fixes the share types on incoming share resources.
- refs https://github.com/owncloud/ocis/issues/9735

fix: displaying external shares on 'Shared With Me'-page

---

tests/e2e/cucumber/environment/index.ts
tests/e2e/cucumber/features/navigation/personalSpacePagination.feature
tests/e2e/support/api/graph/userManagement.ts
tests/e2e/support/api/token/index.ts
tests/e2e/support/api/token/utils.ts
tests/e2e/support/objects/runtime/session.ts
tests/e2e/support/utils/tokenHelper.ts

This PR adds an implementation for getting bearer tokens using API rather than from UI via login.
- Fixes https://github.com/owncloud/web/issues/11307

[tests-only] [full-ci] adding step for getting bearer token with api

---

packages/web-runtime/package.json
packages/web-runtime/src/defaults/index.ts
pnpm-lock.yaml

As far as I can see, the dependency was only used to display the attribution in the browser console. However, this attribution has been removed with their version `6.6.0`.
Also, according to https://fontawesome.com/license/free it's sufficient to have the attribution embedded in the downloaded icons (which we have).
Superseds https://github.com/owncloud/web/pull/11418.

chore: remove font-awesome dependency

---

packages/design-system/src/components/OcBreadcrumb/OcBreadcrumb.vue
packages/design-system/src/components/OcButton/OcButton.vue
packages/design-system/src/components/OcInfoDrop/OcInfoDrop.vue
packages/design-system/src/components/OcSelect/OcSelect.vue
packages/design-system/src/styles/theme/oc-spacing-negative.scss
packages/design-system/src/styles/theme/oc-spacing.scss
packages/web-app-files/src/components/Spaces/WhitespaceContextMenu.vue
packages/web-pkg/src/components/BatchActions.vue
packages/web-pkg/src/components/FilesList/ResourceGhostElement.vue
packages/web-pkg/src/components/SideBar/Spaces/SpaceInfo.vue

Fixes the sass nesting so that nested declarations always come after root ones.
- Fixes https://github.com/owncloud/web/issues/11427

fix: sass nesting

---

changelog/unreleased/bugfix-missing-space-members-for-group-memberships
packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.ts

As per title.
- Fixes https://github.com/owncloud/web/issues/11384

fix: missing space member list for group memberships

---

changelog/unreleased/bugfix-ocm-invite-body
packages/web-app-ocm/src/views/OutgoingInvitations.vue

this pr adds the email and description json param top level instead of having it nested inside a params key.
- https://github.com/cs3org/reva/pull/4832
- https://github.com/owncloud/ocis/issues/9583
- https://github.com/owncloud/ocis/pull/9966
- since this is a ongoing ocm optimization currently only via my local installation

bugfix(ocm): fix invitation JSON body

---

changelog/unreleased/enhancement-improve-tiles-view-performance
packages/design-system/src/components/_OcTableRow/_OcTableRow.vue
packages/web-pkg/src/components/FilesList/ResourceTile.vue
packages/web-pkg/src/components/FilesList/ResourceTiles.vue
packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
pnpm-lock.yaml

- Fixes https://github.com/owncloud/web/issues/11480
- test case 1:
- test case 2:
- ...

Add lazy loading for tiles view

---

changelog/unreleased/enhancement-add-select-all-checkbox-to-tiles-view
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/src/components/FilesList/ResourceTiles.vue
packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap

- test case 1:
- test case 2:
- ...

Add tooltip to select all checkbox, adjust position

---

packages/web-pkg/src/composables/actions/files/useFileActions.ts

forgot this in https://github.com/owncloud/web/pull/11515

refactor: use find instead of filter for getting default action

---

packages/extension-sdk/package.json
pnpm-lock.yaml

https://github.com/owncloud/web/pull/11510 is broken for some reason, hence doing this manually.

chore: bump @vitejs/plugin-vue to v5 in extension-sdk

---

changelog/unreleased/enhancement-hide-versions-panel
packages/web-app-files/src/composables/extensions/useFileSideBars.ts
packages/web-client/src/helpers/share/types.ts
packages/web-client/src/helpers/space/functions.ts
packages/web-client/src/helpers/space/types.ts
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/src/composables/resources/index.ts
packages/web-pkg/src/composables/resources/useCanListVersions.ts
packages/web-pkg/tests/unit/components/sidebar/FileSideBar.spec.ts
packages/web-pkg/tests/unit/composables/resources/useCanListVersions.spec.ts
tests/e2e/cucumber/features/spaces/project.feature

Users that have insufficient permissions to view file versions don't see the version sidebar panel anymore. This currently affects regular share receivers, space viewers and space editors without the `versions/read` permission.
Also introduces a helper `useCanListVersions`.
To enable Space Viewers without version permissions, start the latest oCIS with this env var: `GRAPH_AVAILABLE_ROLES="b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6,3284f2d5-0070-4ad8-ac40-c247f7c1fb27"`
- Closes https://github.com/owncloud/web/issues/11359

feat: hide version panel with insufficient permissions

---

changelog/unreleased/bugfix-logut-on-token-failure
packages/web-pkg/src/composables/authContext/useAuthService.ts
packages/web-pkg/src/composables/webWorkers/tokenTimerWorker/useTokenTimerWorker.ts
packages/web-runtime/src/services/auth/authService.ts

Adds a logout when the token renewal fails for some reason. This fixes the issue with the user being able to access the Web UI without a valid token, leading to a broken state.
- Fixes https://github.com/owncloud/web/issues/11478

fix: logout when token renewal fails

---

.drone.env

bump latest ocis stable commit id.
Part of: https://github.com/owncloud/QA/issues/861

[tests-only][full-ci] bump ocis stable-5.0 commit id

---

changelog/unreleased/bugfix-ocm-token-clipboard-copy
packages/web-app-ocm/src/views/OutgoingInvitations.vue

As per title.
- Fixes https://github.com/owncloud/web/issues/11552

fix(ocm): token copy after invitation

---

changelog/unreleased/bugfix-ocm-local-instance-check
packages/web-app-ocm/src/views/IncomingInvitations.vue

this fixes a bug where the local instance was listed in the inviter select.
reduce confusion by removing the current (users instance) from the inviter select.

bugfix(ocm): exclude the local instance in the inviter select

---

changelog/unreleased/enhancement-add-versions-to-the-left-sidebar-bottom
packages/web-runtime/src/components/SidebarNav/SidebarNav.vue

- Fixes https://github.com/owncloud/enterprise/issues/6814
- test case 1:
- test case 2:
- ...

Add versions to the left sidebar bottom

---

dev/docker/ocis/csp.yaml

I added `blob:` to the default csp rules in ocis with https://github.com/owncloud/ocis/pull/9993
Doing the same here for the dev stack.

feat: add blob to csp connect-src

---

changelog/unreleased/enhancement-a11y-improvements
packages/design-system/src/components/OcContextualHelper/OcContextualHelper.vue
packages/design-system/src/components/OcInfoDrop/OcInfoDrop.spec.ts
packages/design-system/src/components/OcInfoDrop/OcInfoDrop.vue
packages/design-system/src/components/OcModal/OcModal.vue
packages/design-system/src/components/_OcTextInputPassword/_OcTextInputPassword.vue
packages/design-system/src/helpers/types.ts
packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
packages/web-app-files/src/components/Shares/CopyPrivateLink.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/components/Shares/__snapshots__/CopyPrivateLink.spec.ts.snap
packages/web-app-ocm/src/views/ConnectionsPanel.vue
packages/web-app-ocm/src/views/IncomingInvitations.vue
packages/web-app-ocm/src/views/OutgoingInvitations.vue
packages/web-pkg/src/components/CreateShortcutModal.vue
packages/web-pkg/src/components/Spaces/QuotaModal.vue

Adds a focus trap to contextual helpers to prevent the user from focusing elements in the background.
- refs https://github.com/owncloud/web/issues/10725

fix(a11y): focus trap for contextual helpers

---

.drone.env
.drone.star
docker-compose.yml
tests/e2e/config.js
tests/e2e/cucumber/environment/index.ts
tests/e2e/cucumber/environment/world.ts
tests/e2e/support/environment/actor/actor.ts
tests/e2e/support/environment/actor/shared.ts

Currently, we get the tracing reports of all the tests that have been retried regardless of pass or fail. And with keycloak tracing is enabled which causes all tracing to be reported for all tests.
Report only the tracings of failed tests. With this PR, now we should get the tracing reports of failed tests only.

[tests-only][full-ci] report tracings of failing tests only

---

packages/web-runtime/src/components/SidebarNav/SidebarNav.vue

Follow up to https://github.com/owncloud/web/pull/11561
- smaller text
- more padding
(is still accessible)

Polish version in left sidebar

---

changelog/unreleased/enhancement-app-store-min-ocis-version
packages/web-app-app-store/src/components/AppVersions.vue
packages/web-app-app-store/src/types.ts

This PR adds a `minOCIS` field to the app version schema and displays its value in the app releases table in the app store app details.
Show min required ocis version to admins.

feat: add min oCIS to app releases table

---

changelog/unreleased/bugfix-logout-issues-token-renewal-failure
packages/web-client/src/helpers/space/functions.ts
packages/web-runtime/src/services/auth/authService.ts

Adds a silent signIn retry when token renewal fails for some reasons. If the retry fails again, then force the user to logout. This is the "old" behavior from `stable-8.0` for the most part, expect for the forced logout.
We might want to force the logout in other scenarios as well, e.g. when the webfinger app receives a `401` status code from the server. This might solve the webfinger issues we have on newer instances, although I can't confirm that.
- Fixes https://github.com/owncloud/web/issues/11478
- Fixes https://github.com/owncloud/ocis/issues/10038

fix: idp logout issues when token renewal fails

---

tests/e2e/cucumber/environment/index.ts
tests/e2e/support/api/keycloak/utils.ts

This PR adds code for getting **access token** from keycloak using `password grant type` flow.
For now in keycloak, one has to log in manually to be authenticated which isn't possible if one wants to get an access token without login. 
Note: **Password Grant flow** isn't recommended by OIDC due to security issue https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#section-2.4
- Part of https://github.com/owncloud/web/issues/11307

[tests-only] [ full-ci]adding code to get bearer token in keycloak

---

changelog/unreleased/enhancement-a11y-improvements
packages/design-system/src/components/OcCheckbox/OcCheckbox.spec.ts
packages/design-system/src/components/OcCheckbox/OcCheckbox.vue
packages/design-system/src/components/_OcTableRow/_OcTableRow.vue
packages/design-system/src/styles/theme/oc-form.scss
packages/web-app-admin-settings/src/composables/keyboardActions/useKeyboardTableNavigation.ts
packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
packages/web-app-files/src/composables/keyboardActions/useKeyboardTableNavigation.ts
packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
packages/web-pkg/src/helpers/ui/index.ts
packages/web-pkg/src/helpers/ui/resourceCheckbox.ts
packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap

* Fixes the issue where the current focus would not change when navigating the resource table/tiles with the keyboard.
* Fixes the border color contrast for focused inputs. The border colors for the inputs in general need a color token change and therefore need a change in ocis (see https://github.com/owncloud/ocis/pull/10076).
* Redesigns the space member search in the right sidebar so it has a label. Also moves the search from the top of the sharing panel to the members section where all members are listed.
- refs https://github.com/owncloud/web/issues/10729
- fixes https://github.com/owncloud/web/issues/10724

fix(a11y): contrast, checkbox focus and space member search label

---

changelog/unreleased/enhancement-a11y-improvements
packages/design-system/src/components/OcDrop/OcDrop.spec.ts
packages/design-system/src/components/OcDrop/OcDrop.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-pkg/src/components/ItemFilter.vue
packages/web-pkg/src/components/SideBar/SideBar.vue
packages/web-runtime/src/components/Topbar/ApplicationsMenu.vue
packages/web-runtime/src/components/Topbar/TopBar.vue
tests/e2e/support/objects/app-admin-settings/users/actions.ts

* Automatically closes drops when leaving them via keyboard navigation.
* Prevents background elements form being focused when the sidebar takes 100% screen width (mobile view).
* Fixes an issue where selecting a filter would cause a focus jump to the sidebar on the users page.
- Fixes https://github.com/owncloud/web/issues/10733

fix(a11y): keyboard navigation

---

packages/web-app-app-store/src/components/AppVersions.vue

Using `Infinite Scale Version` instead of `oCIS Version` in the app store details versions table because it's user facing................... 👍
Also switched the order of app version and min ocis version to make it look less horrible with such a long table header cell.

fix: use Infinite Scale instead of oCIS because it's user facing

---

changelog/unreleased/enhancement-a11y-improvements
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/src/components/SideBar/SideBar.vue
packages/web-pkg/src/composables/sideBar/useSideBar.ts
packages/web-runtime/src/components/Topbar/ApplicationsMenu.vue
tests/e2e/support/objects/app-admin-settings/users/actions.ts
tests/e2e/support/objects/runtime/application.ts

Fixes 2 main issues with the right sidebar focus:
* Prevents the sidebar from stealing the focus when loading the page with the sidebar being initially opened.
* Sets the focus on the sidebar when necessary (e.g. when opening/closing a specific sidebar panel).
I decided to get rid of the visibility- and the hidden-observer because it's painful to tweak them right and they weren't working as supposed anyway. The simple solution I went for sets the focus when opening the sidebar or a specific panel, or when closing a sub-panel and returning to the root panel.
- Fixes https://github.com/owncloud/web/issues/10618

fix: right sidebar focus

---

changelog/unreleased/enhancement-soothe-sidebar-transitions
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/src/components/SideBar/SideBar.vue
packages/web-pkg/tests/unit/components/sidebar/FileSideBar.spec.ts
tests/e2e/support/objects/app-files/utils/sidebar.ts
tests/e2e/support/objects/runtime/application.ts

Soothe right sidebar transitions when opening and closing sub panels.
(Added by @tbsbdr )
Before and after for better comparison:
https://github.com/user-attachments/assets/94b59897-2de7-40b9-90f6-4ca4cd4d62f2

feat: soothe right sidebar panel transitions

---

.drone.env

Bump latest ocis stable commit id.
Part of: https://github.com/owncloud/QA/issues/862

[tests-only] [full-ci] bump ocis stable commit id

---

packages/design-system/src/components/OcDatepicker/OcDatepicker.vue
packages/design-system/src/components/OcFilterChip/OcFilterChip.vue
packages/web-pkg/src/components/Filters/DateFilter.vue
packages/web-pkg/src/components/Filters/index.ts
packages/web-pkg/tests/unit/components/Filters/DateFilter.spec.ts
packages/web-pkg/tests/unit/components/Filters/__snapshots__/DateFilter.spec.ts.snap

Adds a filter for custom date ranges. This is needed for the soon to come activities app.
The filter stores the custom dates in a query param as milliseconds because that's a nice format for URLs. That means the implementing party might need to convert it to an actual date when working with the filter.
- Closes https://github.com/owncloud/web/issues/11546

feat: add custom date range filter

---

changelog/unreleased/bugfix-logout-issues-token-renewal-failure
packages/web-app-webfinger/src/views/Resolve.vue
packages/web-pkg/src/composables/authContext/useAuthService.ts
packages/web-runtime/src/services/auth/authService.ts

This restores some of the behavior we had before https://github.com/owncloud/web/pull/10881.
It is a partial backport of https://github.com/owncloud/web/pull/11584.

fix: force logout after token expiry retry (backport)

---

.drone.env
tests/e2e/cucumber/features/smoke/activity.feature

Bumped ocis commit-id and fixed the activity messages.
The activity message was changed in ocis (https://github.com/owncloud/ocis/pull/10049)
- Fixes https://github.com/owncloud/web/issues/11625
- https://github.com/owncloud/QA/issues/862

[tests-only][full-ci] fix activity message

---

.drone.env
tests/e2e/cucumber/features/smoke/activity.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

Checking activity by sharee is not possible with latest ocis.
- Fixes https://github.com/owncloud/web/issues/11635

[tests-only][full-ci] sharee cannot see activity

---

changelog/unreleased/enhancement-move-permanent-link-indicator
changelog/unreleased/enhancement-redesign-sidebar-link-sharing-panel
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ContextMenuItem.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditDropdown.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.ts.snap
tests/e2e/support/objects/app-files/share/collaborator.ts
tests/unit/config/vitest.config.ts

Follow-up for https://github.com/owncloud/web/pull/11606.
- closes https://github.com/owncloud/web/issues/11613

feat: move "Shared via"-indicator in sidebar to context menu

---

changelog/changelog-csv.tmpl

To be able to create "the spreadsheet", we need the changelog in CSV format.
Somebody with drone knowledge should add the following command line to the file `.drone.star` (it seems):
```
calens -o dist/changelog.csv -t changelog/changelog-csv.tmpl 
```
to be executed when releasing.

[docs-only] add changelog template for csv changelog output

---

changelog/unreleased/bugfix-hide-share-type-switch-project-spaces
packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.spec.ts

Hides the share type switch when adding members to project spaces because they currently don't support external shares.
- Fixes https://github.com/owncloud/web/issues/11579

fix: remove share type filter for project spaces

---

packages/web-client/README.md
packages/web-client/src/index.ts
packages/web-client/src/webdav/client/dav.ts
packages/web-client/src/webdav/index.ts
packages/web-client/src/webdav/types.ts
packages/web-pkg/src/composables/webWorkers/deleteWorker/worker.ts
packages/web-pkg/src/composables/webWorkers/pasteWorker/worker.ts
packages/web-pkg/src/composables/webWorkers/restoreWorker/worker.ts
packages/web-pkg/src/http/client.ts
packages/web-pkg/src/services/client/client.ts
packages/web-pkg/tests/unit/composables/webWorkers/deleteWorker/worker.spec.ts
packages/web-pkg/tests/unit/composables/webWorkers/pasteWorker/worker.spec.ts
packages/web-pkg/tests/unit/composables/webWorkers/restoreWorker/worker.spec.ts
packages/web-pkg/tests/unit/services/client.spec.ts

Removes the old way of re-initializing clients in the client service when they needed to. The client service now uses request interceptors for the dynamic headers such as `Authorization`.
This a) is more developer friendly since the client service can now be destructured and b) removes the overhead of re-initializing the clients over and over again.
A few (non-breaking) changes needed to be done in the `web-client` package for this. It now exposes the 3 individual client init methods for initializing clients via the `web-client` package:
* `graph()`
* `ocs()`
* `webdav()`
This also deprecates the `client()` method which initializes all 3 clients at the same time because it's intransparent to the user. E.g. you pass an `axios` instance to this method, but the webdav client doesn't use it. …

refactor: use request interceptors in client service 

---

changelog/unreleased/enhancement-remove-uploader-link-type
packages/web-pkg/src/composables/links/useLinkTypes.ts
packages/web-pkg/tests/unit/composables/links/useLinkTypes.spec.ts

As per title.
- Fixes https://github.com/owncloud/web/issues/11381

feat: adjust link type descriptions and remove "Uploader" type

---

changelog/unreleased/bugfix-user-filters-after-page-reload
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-admin-settings/tests/unit/views/Users.spec.ts
packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap

Fixes an issue where applied user filters would not be visible after page reload.
- Fixes https://github.com/owncloud/web/issues/11604

fix(admin-settings): user filters after page reload

---

changelog/unreleased/enhancement-allow-setting-view-mode-for-apps-via-query
packages/web-app-external/src/App.vue
packages/web-app-external/tests/unit/app.spec.ts

- Fixes https://github.com/owncloud/web/issues/11667
- test case 1:
- test case 2:
- ...

Allow to set external app view mode via query 'view_mode' (view|write)

---

changelog/unreleased/bugfix-hide-copy-permanent-link-action-public-pages
packages/web-pkg/src/composables/actions/files/useFileActionsCopyPermanentLink.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCopyPermanentLink.spec.ts

As per title.
- Fixes https://github.com/owncloud/web/issues/11645

fix: remove copy permanent link action in public spaces

---

packages/web-app-admin-settings/src/views/Spaces.vue
packages/web-app-admin-settings/src/views/Users.vue
packages/web-app-external/src/App.vue
packages/web-app-files/src/services/folder/loaderFavorites.ts
packages/web-app-files/src/services/folder/loaderSharedViaLink.ts
packages/web-app-files/src/services/folder/loaderSharedWithMe.ts
packages/web-app-files/src/services/folder/loaderSharedWithOthers.ts
packages/web-app-files/src/services/folder/loaderSpace.ts
packages/web-app-files/src/services/folder/loaderTrashbin.ts
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/src/views/trash/Overview.vue
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/src/composables/appDefaults/useAppFileHandling.ts
packages/web-pkg/src/composables/piniaStores/resources.ts
packages/web-pkg/src/composables/piniaStores/spaces.ts
packages/web-pkg/src/composables/search/useSearch.ts
packages/web-pkg/tests/unit/composables/piniaStores/spaces.spec.ts
packages/web-runtime/src/components/Account/GdprExport.vue
packages/web-runtime/src/components/Topbar/Notifications.vue
packages/web-runtime/src/pages/account.vue
packages/web-runtime/src/pages/resolvePublicLink.vue

Adds abort signals to (almost) all requests that are running in a task. This way they get cancelled properly when a task is being cancelled or restarted.
Also wraps the search call in a task so it can benefit from this functionality.
closes https://github.com/owncloud/web/issues/11650

feat: add abort signals

---

changelog/unreleased/bugfix-undefined-request-ids
packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
packages/web-pkg/src/composables/webWorkers/deleteWorker/useDeleteWorker.ts
packages/web-pkg/src/composables/webWorkers/deleteWorker/worker.ts
packages/web-pkg/src/composables/webWorkers/pasteWorker/usePasteWorker.ts
packages/web-pkg/src/composables/webWorkers/pasteWorker/worker.ts
packages/web-pkg/tests/unit/composables/webWorkers/deleteWorker/worker.spec.ts
packages/web-pkg/tests/unit/composables/webWorkers/pasteWorker/worker.spec.ts

Errors in workers need to be constructed manually in the main thread since they can't be serialized and passed from the worker to the main thread.
This also fixes the issue with the missing request ids in failing copy, move and delete requests.
fixes https://github.com/owncloud/web/issues/11678

fix: error parsing in delete- and paste-worker

---

packages/web-app-files/src/HandleUpload.ts
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
packages/web-pkg/src/helpers/resource/conflictHandling/transfer.ts
tests/e2e/cucumber/features/smoke/upload.feature

Adding an "insufficient quota" message detail to the file/folder copy and move error messages. Additionally I've tried to streamline the quota error messages a bit. Would be good to get some native language speaker feedback. Trying to spawn @phil-davis for that 😁 
Relates to all the confusion in https://github.com/owncloud/enterprise/issues/6857 and trying to ease some of it.
More details in error messages for normal users.

feat: add insufficient quota info to file copy

---

changelog/unreleased/bugfix-tags-shared-with-me-page
packages/web-pkg/src/components/SideBar/FileSideBar.vue

Tags are currently not available on the Graph API, hence we need to manually take them from the webdav response.
fixes https://github.com/owncloud/web/issues/11677

fix: add missing resource tags on 'Shared with me' page

---

changelog/unreleased/bugfix-escape-html-characters-in-activities-and-notification-view
packages/web-app-files/src/components/SideBar/ActivitiesPanel.vue
packages/web-runtime/src/components/Topbar/Notifications.vue

- Fixes #11705 
- test case 1:
- test case 2:
- ...

Escape html in ActivitiesPanel and Notificiations views

---

changelog/unreleased/bugfix-details-panel-wrong-webdav-url-of-recieved-shares
packages/web-pkg/src/components/SideBar/WebDavDetails.vue

- Fixes #11704 
- test case 1:
- test case 2:
- ...

fix: wrong webdav url in details panel of received shares

---

changelog/unreleased/bugfix-accessing-disabled-password-protected-space-does-not-show-error
packages/web-runtime/src/pages/resolvePublicLink.vue
packages/web-runtime/tests/unit/pages/resolvePublicLink.spec.ts

- Fixes #11721
- test case 1:
- test case 2:
- ...

Show error message when accessing space via publik link that is disabled

---

changelog/unreleased/bugfix-application-menu-not-operable-in-safari-browser
packages/design-system/src/components/OcDrop/OcDrop.vue

- Fixes #11718 
- test case 1:
- test case 2:
- ...

Bugfix: Dropdown menu links not working in Safari

---

changelog/unreleased/bugfix-delete-federated-connections
packages/web-app-ocm/src/views/ConnectionsPanel.vue

Fixes deleting federated connections in the science mesh app.
fixes https://github.com/owncloud/web/issues/11688

fix: deleting federated connections

---

changelog/unreleased/enhancement-file-size-warning-in-editors
packages/web-app-text-editor/src/index.ts
packages/web-pkg/src/apps/types.ts
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue

- Fixes #8038 
- test case 1:
- test case 2:
- ...

Feat: Add warning popup to editors, when file exceeds threshold

---

packages/design-system/package.json
pnpm-lock.yaml

Fixes a bunch of alerts from https://github.com/owncloud/web/security/dependabot.

chore(deps): bump (sub-) dependencies to fix security alerts

---

changelog/unreleased/enhancement-add-not-found-page
packages/web-runtime/src/pages/notFound.vue
packages/web-runtime/src/router/index.ts
tests/e2e/cucumber/features/navigation/pageNotFoud.feature
tests/e2e/cucumber/steps/ui/navigateByUrl.ts
tests/e2e/support/objects/url-navigation/actions.ts
tests/e2e/support/objects/url-navigation/index.ts

We've added a not found page to communicate to users when they've navigated to a page that doesn't exist.
- Fixes #5804 
- test case 1:
- test case 2:
- ...

Add general not found page

---

packages/eslint-config/index.js
packages/eslint-config/package.json
pnpm-lock.yaml

Prepares the `10.3.0` release for `eslint-config` and adds some ignore patterns in the course of this.
closes https://github.com/owncloud/web/issues/11743

chore(eslint-config): prepare 10.3.0 release

---

packages/design-system/src/components/OcModal/OcModal.vue
packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap
packages/design-system/src/components/OcPageSize/OcPageSize.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditDropdown.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.ts
packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.ts.snap
packages/web-pkg/src/components/FilesList/ResourceTiles.vue
packages/web-pkg/src/components/QuotaSelect.vue
packages/web-pkg/src/components/Spaces/QuotaModal.vue
packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
packages/web-runtime/src/components/MobileNav.vue
tests/e2e/support/objects/app-admin-settings/users/actions.ts

* transforms the select dropdown in the tiles view to a select input to be a11y compliant.
* hides the visible label in the `OcPageSize` component for screen readers since the combobox has its own label.
* removes a duplicated DOM id in quota select
* sets `aria-current` props in mobile nav
* moves the `aria-labelledby` property in modals to the modal body where `role="dialog"` sits.
* removes the `aria-expanded` property on the div that surrounds the share actions because it's invalid on a div-element. This was happening because the access details drop was placed in a wrong position in the DOM.
fixes https://github.com/owncloud/web/issues/10739

fix: various small a11y issues 

---

changelog/unreleased/bugfix-navigating-into-external-folders
packages/web-app-files/src/index.ts
packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/src/composables/appDefaults/useAppFolderHandling.ts
packages/web-pkg/src/composables/spaces/useGetMatchingSpace.ts

When retrieving a matching space via `getMatchingSpace`, we must not use a `mountpoint` space as internal space. This was happening for OCM shares, leading to them being inaccessible.
Also fixes the active nav item marker after navigating into an OCM share.
fixes https://github.com/owncloud/web/issues/11753
fixes https://github.com/owncloud/ocis/issues/10271

fix: ocm folder issues

---

packages/web-app-app-store/src/LayoutContainer.vue
packages/web-app-app-store/src/components/AppAuthors.vue
packages/web-app-app-store/src/components/AppImageGallery.vue
packages/web-app-app-store/src/components/AppResources.vue
packages/web-app-app-store/src/components/AppTags.vue
packages/web-app-app-store/src/components/AppVersions.vue
packages/web-app-app-store/src/types.ts
packages/web-app-app-store/tests/unit/LayoutContainer.spec.ts
packages/web-app-app-store/tests/unit/components/AppActions.spec.ts
packages/web-app-app-store/tests/unit/components/AppAuthors.spec.ts
packages/web-app-app-store/tests/unit/components/AppImageGallery.spec.ts
packages/web-app-app-store/tests/unit/components/AppResources.spec.ts
packages/web-app-app-store/tests/unit/components/AppTags.spec.ts
packages/web-app-app-store/tests/unit/components/AppVersions.spec.ts

Adding a few unit tests for the app store... far from "done", but since I need to switch to a different task I probably won't add more coverage in the next few days. So trying to get the current state into master.
Works towards https://github.com/owncloud/web/issues/11634

App store unit tests (first batch)

---

packages/web-pkg/README.md
packages/web-pkg/package.json
packages/web-pkg/types.d.ts
packages/web-pkg/vite.config.ts
pnpm-lock.yaml

Prepares `web-pkg` for a publish with the actual implementation, not just the types. This is needed for unit tests in external apps, since the runtime is not present in this context to provide the actual implementation.
Also moves the peer dependencies to regular dependencies because the app that uses this package should not need to provide all the peers. The ODS is currently an exception to this until we have it published via npm again.
closes https://github.com/owncloud/web/issues/11741

chore(web-pkg): prepare publish with implementation

---

packages/web-pkg/src/components/FilesList/ResourceTiles.vue
packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap

Apparently without the `scoped` styles in the tiles view, the `oc-flex` class on the `<ul>` overwrites the `display: grid` style from the `oc-tiles` class. 🤔 
Even weirder: was only happening in the `production` build, not with `pnpm vite`.
- Fixes https://github.com/owncloud/web/issues/11757

fix: tile sizing by removing unnecessary class

---

packages/web-client/package.json
packages/web-test-helpers/README.md
packages/web-test-helpers/package.json
pnpm-lock.yaml

Moves peers of `web-client` and `web-test-helpers` to regular dependencies where it makes sense so users of these packages are not forced to provide them.

chore: move peers to regular dependencies

---

dev/scripts/bump_versions.sh
dev/scripts/create_and_push_tags.sh
docs/releasing.md

Adds 2 scripts for updating versions and creating & pushing tags of the main app as well as all published packages.
Also updates the dev docs.

chore: scripts for updating versions and creating tags

---

tests/e2e/cucumber/features/smoke/activity.feature
tests/e2e/cucumber/steps/api.ts
tests/e2e/support/api/share/index.ts
tests/e2e/support/api/share/share.ts

[test-only ]expand Activity test

---

packages/design-system/package.json
packages/design-system/vite.config.ts
packages/web-pkg/package.json
packages/web-pkg/vite.config.ts
packages/web-test-helpers/.npmrc
packages/web-test-helpers/package.json
packages/web-test-helpers/vite.config.ts
pnpm-lock.yaml

`design-system`:
* Fixes the published exports since esm and cjs were mixed up.
* Stubs `webfontloader` and removes it from the external deps to avoid loading fonts in a unit testing context. This would only be a problem when using the ODS standalone, which basically noone does.
* Removes `vue-select` from the external deps because there seems to be something wrong with their package type.
`web-pkg` and `web-test-helpers`:
* Removes the pre-bundling of the design-system and mark it external since it's now published.

chore: fix ods build and mark it external in other packages

---

dev/scripts/bump_versions.sh
dev/scripts/create_and_push_tags.sh
packages/eslint-config/package.json
packages/extension-sdk/package.json
pnpm-lock.yaml

* `extension-sdk`: Aligns the extension-sdk version with the one of the mono repo and its packages. Also adds a version range to the `sass` dependency so users of this package don't need to provide the pinned version exactly.
* `eslint-config`: Inscreases the minimum version of `@babel/eslint-parser` to `7.25.8` because this ensures compatibility with eslint v9. The previous, older version didn't do that.

chore: fix unmet peer warnings when using extension-sdk and eslint-config

---

.drone.star

Most of the builds fails while making a request to the logon URI with `502 Bad gateway` in the response in the before hook.
Make wait for the ocis service to be ready for the admin user. Hopefully fixes the issue https://github.com/owncloud/web/issues/11669

[tests-only][full-ci] wait for ocis service to be ready for admin user

---

changelog/unreleased/bugfix-sharing-label-for-locked-files
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.ts

Fixes an issue where a locked file would be falsely labelled as shared in the right sidebar.
refs https://github.com/owncloud/enterprise/issues/6915

fix: sharing label for locked files

---

packages/web-app-files/src/views/spaces/Projects.vue

having a text with line breaks seems to cause issues with translations being loaded from the translations.json

fix: use list instead of text for spaces contextual helper

---

.drone.env
tests/e2e/cucumber/features/shares/share.feature
tests/e2e/cucumber/steps/ui/resources.ts

part of https://github.com/owncloud/ocis/issues/10345

[full-ci] ocisBump_6.6.0

---

changelog/unreleased/bugfix-missing-translations
packages/web-app-files/src/composables/resourcesViewDefaults/useResourcesViewDefaults.ts
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
packages/web-pkg/src/helpers/ui/resourceTiles.ts

Adds missing translations for the tile sort options and the editor "Save"-button.

fix: add missing translations

---

tests/e2e/config.js
tests/e2e/cucumber/environment/index.ts
tests/e2e/cucumber/features/ocm/ocm.feature
tests/e2e/cucumber/steps/ui/session.ts
tests/e2e/support/api/graph/userManagement.ts
tests/e2e/support/api/http.ts
tests/e2e/support/api/keycloak/ocisUserToken.ts
tests/e2e/support/api/token/utils.ts
tests/e2e/support/environment/token.ts
tests/e2e/support/environment/userManagement.ts
tests/e2e/support/objects/url-navigation/actions.ts
tests/e2e/support/store/index.ts
tests/e2e/support/store/token.ts
tests/e2e/support/store/user.ts
tests/e2e/support/utils/tokenHelper.ts

This PR update store for federated oCIS instance. On follow-up PR, tests related to oCIS federation will be added.
- https://github.com/owncloud/web/issues/11680
- Locally

[tests-only][full-ci]Store federated ocis user and token for e2e tests

---

changelog/unreleased/bugfix-preview-retries
packages/web-pkg/src/services/preview/previewService.ts
packages/web-pkg/tests/unit/services/previewService.spec.ts

Adds a retry mechanism to preview loading when the server responds with `429` status codes.
fixes https://github.com/owncloud/web/issues/11798

fix: preview image retry

---

changelog/unreleased/bugfix-respect-post-logout-url
packages/web-pkg/src/composables/piniaStores/config/types.ts

The parameter was simply missing in our `zod` schema, hence it was not loaded into the config object.
fixes https://github.com/owncloud/web/issues/11816

fix: setting post logout redirect url

---

.drone.star
tests/drone/config-ocis-federated.json
tests/drone/config-ocis.json
tests/drone/providers.json
tests/e2e/support/objects/federation/actions.ts

This PR add code to run ocm tests suite on CI
- Part of https://github.com/owncloud/web/issues/11680
- CI

[tests-only][full-ci]Run ocm tests on ci

---

tests/e2e/cucumber/features/ocm/ocm.feature
tests/e2e/cucumber/steps/ui/shares.ts
tests/e2e/support/objects/app-files/share/actions.ts
tests/e2e/support/objects/app-files/share/collaborator.ts

related https://github.com/owncloud/ocis/issues/10272#issuecomment-2437419295

[full-ci] federated user downloads shared resources

---

changelog/unreleased/bugfix-files-appearing-in-file-list
packages/web-runtime/src/container/sse/files.ts

Fixes the issue with files wrongly appearing in the file list during an upload. This was happening because of SSE since a check for the current folder was missing.
fixes https://github.com/owncloud/web/issues/11803

fix: files wrongly appearing in the file list

---

changelog/unreleased/bugfix-sidebar-showing-wrong-shares
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue

This fixes an issue where the right sidebar would display wrong shares when being inside a space and opening a file from another space (e.g. via the search results).
fixes https://github.com/owncloud/web/issues/11787

fix: clear ancestor data in app wrapper

---

changelog/unreleased/enhancement-resource-name
packages/design-system/l10n/.tx/config
packages/web-app-activities/l10n/.tx/config
packages/web-app-admin-settings/l10n/.tx/config
packages/web-app-app-store/l10n/.tx/config
packages/web-app-epub-reader/l10n/.tx/config
packages/web-app-external/l10n/.tx/config
packages/web-app-files/l10n/.tx/config
packages/web-app-ocm/l10n/.tx/config
packages/web-app-pdf-viewer/l10n/.tx/config
packages/web-app-preview/l10n/.tx/config
packages/web-app-search/l10n/.tx/config
packages/web-app-text-editor/l10n/.tx/config
packages/web-app-webfinger/l10n/.tx/config
packages/web-client/l10n/.tx/config
packages/web-pkg/l10n/.tx/config
packages/web-runtime/l10n/.tx/config

Fixes: #11839 (Harmonize naming translations resources)
Add a `resorce_name` property to each TX definition (`packages/xxx/.tx/config`)
`activities` --> `web-activities` (`<repo-name>-<resource-name>`
Now, we can destinguish by the name in TX where the source is located:
`web-yyy`
`web-extension-yyy`
...

Add resource_name to TX definition

---

changelog/unreleased/bugfix-right-side-bar-cut-off
packages/web-pkg/src/components/SideBar/SideBar.vue

fixes https://github.com/owncloud/web/issues/11830

fix: right side bar cut off

---

changelog/unreleased/bugfix-context-menu-open-app-in-new-tab-broken
packages/web-pkg/src/components/ContextActions/ActionMenuItem.vue

- Fixes #11853 
- test case 1:
- test case 2:
- ...

fix: use a tag in context menu instead of button for editors in ctx menu

---

docker-compose.yml

The backend introduced a new env var for the collaboration app product (was falsely relying on the app name before, but since the app name needs to be customizable to customer needs we can't do string comparisons on strings like `collabora` or `onlyoffice` in the backend on that variable. Hence the `product` variable was introduced. See https://github.com/owncloud/ocis/pull/10335
- Relates to https://github.com/owncloud/ocis/issues/10479
Keep our dev stack working...

chore: include product var into collaboration-oo stack

---

changelog/unreleased/bugfix-lock-information
packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
packages/web-client/src/helpers/resource/functions.ts
packages/web-client/src/helpers/resource/types.ts
packages/web-client/src/webdav/constants/dav.ts
packages/web-test-helpers/package.json
pnpm-lock.yaml

We were showing ` ()` for for the `Locked by` field in the file details for two reasons:
1. the lock owner propfind info was referencing the wrong field name
2. the `()` were shown if there was no lock time
Fixing this by
1. Referencing the correct field (after the backend prettified the string in that field)
2. Showing `(<lockTime>)` only if there is a lockTime and hiding the parentheses entirely if there is no lockTime info
- Fixes https://github.com/owncloud/web/issues/11008

fix: lock owner in file details

---

.drone.star

After talk with @rhafer we enabled vips for web CI see here https://github.com/owncloud/ocis/pull/10310
we can use it in in webCI and don't use in ocisCi in this way we can check both options 
@micbar @kulmann Is that okay?

[full-ci]enable vips for thumbnails

---

packages/design-system/src/styles/theme/oc-form.scss
packages/design-system/vite.config.ts
packages/web-pkg/vite.config.ts
tests/unit/config/vitest.config.ts
vite.config.ts

With sass > 1.80.0 imports and global functions have been deprecated.
Replacing the global functions in `oc-form.scss` in this PR. Import statements are a different story and more complicated.

chore: don't use global sass functions in oc-form.scss

---

.drone.star
tests/drone/config-ocis.json

PR https://github.com/owncloud/web/pull/11664 introduced app-store test suite has been added to cover app-store feature but never run in CI. This PR setup drone to run `app-store` on CI
- https://github.com/owncloud/web/issues/11837
- CI

[tests-only][full-ci]Run app-store e2e tests on CI

---

changelog/unreleased/bugfix-preview-retries-postprocessing
packages/web-pkg/src/services/preview/previewService.ts
packages/web-pkg/tests/unit/services/previewService.spec.ts

Adds a retry mechanism for preview requests when the images could not be loaded due to postprocessing.
fixes https://github.com/owncloud/web/issues/11870

fix: preview loading retry after 425 status code

---

tests/e2e/support/objects/app-files/resource/actions.ts

Response check MUST always be done using `Promise.all` along with the action that triggers the response. If not the assertion will become flaky. 
- Failing test: https://drone.owncloud.com/owncloud/ocis/40977/4/14

[tests-only][full-ci] do proper response check with click action

---

changelog/unreleased/bugfix-save-as-open-action-embed-delegate-authentication
packages/web-pkg/src/components/Modals/FilePickerModal.vue
packages/web-pkg/src/components/Modals/SaveAsModal.vue
packages/web-pkg/tests/unit/components/Modals/FilePickerModal.spec.ts
packages/web-pkg/tests/unit/components/Modals/SaveAsModal.spec.ts

Fixes the "Open" and "Save as" actions when the server has enabled `embed.delegateAuthentication`. This flag needs to be ignored for these 2 actions since Web is basically embedding itself and always needs authentication.
fixes https://github.com/owncloud/web/issues/11897

fix: file picker when embed delegate authentication is enabled

---

changelog/unreleased/bugfix-app-top-bar-does-not-show-location-when-shared-file-is-opened
changelog/unreleased/bugfix-open-from-app-and-save-as-feature-broken-when-opened-via-shared-file
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
packages/web-pkg/src/components/AppTopBar.vue
packages/web-pkg/src/components/Modals/FilePickerModal.vue
packages/web-pkg/src/components/Modals/SaveAsModal.vue
packages/web-pkg/src/composables/folderLink/useFolderLink.ts
packages/web-pkg/tests/unit/composables/folderLink/useFolderLink.spec.ts

- Fixes #11895 
- Fixes #11896 
- test case 1:
- test case 2:
- ...

Fix: always, show location in top bar, make file picker work in various locations, file picker width too narrow

---

changelog/unreleased/bugfix-app-top-bar-does-not-show-location-when-shared-file-is-opened
changelog/unreleased/bugfix-open-from-app-and-save-as-feature-broken-when-opened-via-shared-file
changelog/unreleased/bugfix-preview-app-shared-with-me-page
changelog/unreleased/bugfix-public-folder-reload
changelog/unreleased/bugfix-save-as-open-action-embed-delegate-authentication
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
packages/web-pkg/src/components/AppTopBar.vue
packages/web-pkg/src/components/Modals/FilePickerModal.vue
packages/web-pkg/src/components/Modals/SaveAsModal.vue
packages/web-pkg/src/composables/appDefaults/useAppFolderHandling.ts
packages/web-pkg/src/composables/folderLink/useFolderLink.ts
packages/web-pkg/src/composables/piniaStores/resources.ts
packages/web-pkg/src/composables/resources/useCanListVersions.ts
packages/web-pkg/tests/unit/components/Modals/FilePickerModal.spec.ts
packages/web-pkg/tests/unit/components/Modals/SaveAsModal.spec.ts
packages/web-pkg/tests/unit/composables/folderLink/useFolderLink.spec.ts

Backports the following fixes to `stable-11.0`:
* #11900 
* #11893
* #11904
* #11899

fix: backport recent fixes to stable-11.0

---

changelog/unreleased/bugfix-fix-order-in-roles-drop-down
packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue

- Fixes #11915 
- test case 1:
- test case 2:
- ...

Sort roles in role dropdown according to backend

---

changelog/unreleased/bugfix-extension-actions-right-sidebar
packages/web-pkg/src/composables/actions/files/useFileActions.ts

fixes https://github.com/owncloud/web/issues/11898

fix: show extension actions in right sidebar actions panel

---

changelog/unreleased/bugfix-expose-request-id-when-delete-fails
changelog/unreleased/bugfix-preview-app-shared-with-me-page
packages/web-app-preview/src/App.vue
packages/web-app-preview/tests/unit/app.spec.ts
packages/web-pkg/src/composables/actions/files/useFileActions.ts
packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts

fix: backport recent master fixes to stable-11.0

---

.drone.env
.drone.star
docker-compose.yml
tests/e2e/cucumber/features/shares/denyShareAccess.feature
tests/e2e/cucumber/features/spaces/denySpaceAccess.feature
tests/e2e/cucumber/steps/ui/shares.ts
tests/e2e/support/api/share/share.ts
tests/e2e/support/objects/app-files/share/actions.ts
tests/e2e/support/objects/app-files/share/collaborator.ts
tests/e2e/support/objects/app-files/share/index.ts

related https://github.com/owncloud/ocis/pull/10627
- enable deny/allow share test
- added deny/allow test with project space

[test-only] enable again denyAccess tests

---

.drone.star
tests/drone/script.sh
tests/e2e/cucumber/environment/index.ts

This PR 
- update `PLUGINS_S3 = "plugins/s3:1.5"` version
- cache chromium with respect to playwright version
- Use cached chromium to run e2e tests
- add script to get playwright version to store cache 
- can't upgrade minio version because some command are not available in the latest minio image 
- Fixes https://github.com/owncloud/web/issues/11921
- CI

[tests-only][full-ci]Cache playwright chromium

---

changelog/unreleased/bugfix-ocm-invite-flow
packages/web-app-ocm/src/schemas.ts
packages/web-app-ocm/src/views/IncomingInvitations.vue
packages/web-app-ocm/src/views/OutgoingInvitations.vue

Fix the OCM invite flow by implementing an encoded "quick token" and removing the email sending process as the server does not support it currently.
fixes https://github.com/owncloud/web/issues/11983

fix(ocm): base64 encoded invite token

---

changelog/unreleased/bugfix-do-not-load-versions-when-sidebar-is-closed
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/tests/unit/components/sidebar/FileSideBar.spec.ts

We've fixed the the loading of file versions which was triggered even when sidebar was closed. File version will now be loaded only when the sidebar is opened.
- Fixes https://github.com/owncloud/web/issues/11979
Do not perform requests when not needed.
- test environment: unit & local
- test case 1: added unit tests
- test case 2: follow reproduction steps from the issue
- ...

fix: do not load version when sidebar is closed

---

changelog/unreleased/bugfix-use-only-space-as-space-into-sidebar
packages/web-app-files/src/views/spaces/Projects.vue
packages/web-app-files/tests/unit/views/spaces/Projects.spec.ts

We've fixed the issue where any selected resource got passed to the sidebar as a space in Spaces page. Now only space resource with `driveType` "project" will be passed as a space.
- Fixes https://github.com/owncloud/web/issues/11978
So that our app does not crash and console is clean of errors.
- test environment: unit & local
- test case 1: added unit tests
- test case 2: repeat issue reproduction steps
- ...

fix: pass only space as space prop to sidebar

---

changelog/unreleased/bugfix-missing-activities-shared-with-me-page
packages/web-app-files/src/components/SideBar/ActivitiesPanel.vue

We need to use the resource's `fileId` to load the activities since the regular `id` won't work for share resources.

fix: add missing activities on Shared with me page

---

changelog/unreleased/bugfix-show-missing-role-name-in-link-share-panel
packages/web-pkg/src/components/CreateLinkModal.vue
packages/web-pkg/src/composables/actions/files/useFileActions.ts

- test case 1:
- test case 2:
- ...

Show missing role name in link share panel

---

changelog/unreleased/bugfix-missing-translations-share-type-filters
packages/web-app-files/src/views/shares/SharedWithMe.vue
packages/web-app-files/src/views/shares/SharedWithOthers.vue
packages/web-app-files/tests/unit/views/shares/SharedWithMe.spec.ts
packages/web-app-files/tests/unit/views/shares/SharedWithOthers.spec.ts

- test case 1:
- test case 2:
- ...

Fix bug where translations were missing on the share type filters

---

changelog/unreleased/bugfix-permanent-link-for-shares
packages/web-client/src/helpers/share/functions.ts
packages/web-client/tests/unit/helpers/share/functions.spec.ts
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
packages/web-pkg/src/services/folder/loaders/loaderSharedViaLink.ts
packages/web-pkg/src/services/folder/loaders/loaderSharedWithMe.ts
packages/web-pkg/src/services/folder/loaders/loaderSharedWithOthers.ts
packages/web-pkg/src/services/folder/loaders/loaderSpace.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/container/sse/shares.ts
packages/web-runtime/src/container/sse/types.ts
packages/web-runtime/tests/unit/container/sse/files.spec.ts
packages/web-runtime/tests/unit/container/sse/helpers.spec.ts
packages/web-runtime/tests/unit/container/sse/shares.spec.ts

fixes https://github.com/owncloud/web/issues/12001

fix: permanent link for share resources

---

changelog/unreleased/enhancement-add-notifications-settings
packages/web-client/src/ocs/capabilities.ts
packages/web-runtime/src/components/Account/AccountTable.vue
packages/web-runtime/src/composables/notificationsSettings/index.ts
packages/web-runtime/src/composables/notificationsSettings/useNotificationsSettings.ts
packages/web-runtime/src/helpers/settings.ts
packages/web-runtime/src/pages/account.vue
packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
packages/web-runtime/tests/unit/pages/account.spec.ts

We've added a new notifications settings section into the account screen. This section allows users to configure what notifications they wish to receive either in-app or via email, when to receive email notifications, and drops the previous notifications toggle.
- Fixes https://github.com/owncloud/web/issues/9248
Give more control to users to decide what notifications they wish to receive.
- test environment: local & unit
- test case 1: add unit tests
- test case 2: test in the browser

feat: add notifications settings

---

changelog/unreleased/bugfix-preview-app-files-visibility
packages/web-app-preview/src/App.vue
packages/web-app-preview/tests/unit/app.spec.ts
packages/web-pkg/src/composables/appDefaults/useAppNavigation.ts

We've fixed the issue with displaying hidden files when user open a file in preview app in "Shared with me" list. The `q_share-visibility` query param is now passed to the app so that if a user opens a file while listing "visible shares", the preview app will allow moving only to another visible files. When the `q_share-visibility` query param is set to `hidden` (i.e. user is listing "hidden shares"), the preview app will allow moving only to another hidden files.
We've fixed the issue with displaying hidden files when user open a file in preview app in "Shared with me" list.
The `q_share-visibility` query param is now passed to the app so that if a user opens a file while listing "visible shares", the preview app will allow moving only to another visible files.
When the …

fix: hidden shares in preview app

---

.drone.env

This PR bump latest ocis commit id of stable7.0 branch 
Part of 
- https://github.com/owncloud/QA/issues/870

[tests-only][full-ci]Bump stable7.0 ocis commit id on web stable11.0

---

changelog/unreleased/enhancement-disable-resources-in-delete-queue.md
packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
packages/web-pkg/src/composables/piniaStores/resources.ts
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
packages/web-pkg/tests/unit/composables/actions/helpers/useFileActionsDeleteResources.spec.ts
packages/web-test-helpers/src/mocks/pinia.ts

We've added a new delete queue which is used to disable resources that are being currently deleted. When the resource is in delete queue, it also replaces select checkbox with a spinner to better hint that there is an action in progress.
- Fixes https://github.com/owncloud/web/issues/11956
Understand better that resource is being deleted and prevent trying to delete it again.
- test case 1: delete resources in chrome
- test case 2: unit tests
https://github.com/user-attachments/assets/6eed6bec-d2d9-44fb-b2da-00f792955d26

feat: add delete queue

---

changelog/unreleased/bugfix-disable-paste-action-in-same-folder.md
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts
tests/e2e/support/objects/app-files/resource/actions.ts

We've fixed the state of the "paste files" action when copied resources are from the same folder. The button will be disabled in such case and a tooltip with explanation message displayed.
- Fixes https://github.com/owncloud/web/issues/12021
Prevent overwrite action.
- test case 1: added unit tests
- test case 2: try to paste resources in chrome into same folder

fix: disable paste button in same folder

---

changelog/unreleased/bugfix-do-not-push-sidebar-close-action-away.md
changelog/unreleased/bugfix-update-sidebar-width-on-resize.md
changelog/unreleased/bugfix-use-correct-breakpoints-in-sidebar.md
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
packages/web-pkg/src/components/SideBar/SideBar.vue

Fixed various issues with sidebar resizing. Close button is no longer pushed away, resize event is added, and correct breakpoint is used.
- Fixes https://github.com/owncloud/web/issues/11536
Resilient layout 💪 
- test case 1: Resize browser window
- test case 2: Zoom in & out in browser
https://github.com/user-attachments/assets/ca766a4f-d370-499a-b421-a1a0dabe9d29

fix: handle sidebar resizing

---

changelog/unreleased/bugfix-show-indirect-shares-on-search-page.md
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/tests/unit/components/sidebar/FileSideBar.spec.ts

We've fixed an issue where the indirect shares of resources were not displayed in the sidebar when user is on search page.
- Fixes https://github.com/owncloud/web/issues/10939
🐛less code
- test case 1: add unit tests to check whether ancestors metadata are loaded on search page
- test case 2: follow reproduction steps in chrome

fix: show indirect shares in search results

---

changelog/unreleased/enhancement-use-generic-private-link-error.md
packages/web-runtime/src/pages/resolvePrivateLink.vue

Use more generic error message when resolution of private link fails.
- Fixes https://github.com/owncloud/web/issues/12009
Prevent confusing errors.
- test case 1: Open private link of unshared resource with another user

feat: use more generic private link error message

---

.drone.env

This pr bumps latest ocis stable-7.0 commit id.
Part of:  https://github.com/owncloud/QA/issues/870

[tests-only][full-ci] bump ocis stable 7.0 commit

---

changelog/unreleased/bugfix-reload-preloaded-resource-in-sidebar.md
packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts

We've fixed an issue where actions were not being updated on a resource. We are now reloading metadata of the resource even in the case when it is already preloaded so that we get up to date information. To prevent reloading currently selected resource, prevent selecting it.
- Fixes https://github.com/owncloud/web/issues/10748
Preloaded resource in the sidebar can easily become stale e.g. by hiding it in shares and then directly opening the sidebar again while having hidden filter set. In order to always get up to date information, always reload the resource.
- test case 1: added unit test
- test case 2: follow reproduction steps in the issue

fix: reload sidebar preloaded resource

---

changelog/unreleased/bugfix-change-opacity-of-disabled-checkboxes.md
packages/design-system/src/components/OcCheckbox/OcCheckbox.vue

We've fixed an issue where disabled checkbox was not clearly distinguishable from enabled ones by lowering it's opacity.
- Fixes https://github.com/owncloud/web/issues/12060
Clearly distinguishable checkbox states.
- test case 1: check disabled and enabled checkboxes

fix: lower disabled checkbox opacity

---

changelog/unreleased/bugfix-use-local-state-in-sidebar-in-embed-mode.md
packages/web-pkg/src/composables/sideBar/useSideBar.ts
packages/web-pkg/tests/unit/composables/sideBar/useSideBar.spec.ts

When embed mode is enabled, use local state instead of local storage in sidebar to prevent overlapping the content when the embed iframe is opened.
- Fixes https://github.com/owncloud/web/issues/11875
Content is visible when embed iframe is opened.
- test case 1: added unit tests
- test case 2: open embed iframe while sidebar is opened in the "regular" app

fix: use local state in sidebar in embed mode

---

changelog/unreleased/bugfix-refetch-notifications-settings-on-locale-change.md
packages/web-runtime/src/pages/account.vue
packages/web-runtime/tests/unit/pages/account.spec.ts

To make sure that the server returns settings bundle strings in the correct locale, refetch it after a locale is changed via the UI.
- Fixes https://github.com/owncloud/web/issues/12064
Correct translations
- test case 1: switch locale in the account settings
- test case 2: added unit tests
https://github.com/user-attachments/assets/564a62fa-3fe0-45a1-890f-3e7891ac8958

fix: refetch settings bundle on locale change

---

.drone.env

Bump latest `stable-7.0-ocis` commit to `web-11.0-stable`
Part of:
https://github.com/owncloud/QA/issues/872

[tests-only][full-ci]Bump ocis stable to web stable

---

packages/web-runtime/src/pages/account.vue

`Mail` --> `Email`
(we dont send snail mails 🤣 )
Just a small fix that relates to:
https://github.com/owncloud/ocis/pull/10835 ([docs-only] Update settings source strings for translation)
Should be part of the upcoming 7.1 release, needs manual translation sync up/down and a port

Update account.vue: fix gettext values

---

.drone.env

Bumps ocis stable-7.0 commit id.
Part of: https://github.com/owncloud/QA/issues/872

[tests-only][full-ci]Bump latest ocis stable-7.0 commit id

---

changelog/unreleased/bugfix-missing-user-light-translations.md
packages/web-runtime/src/helpers/additionalTranslations.ts

We've added a missing "User Light" string definition into our translations in order to get this role translated.
- refs https://github.com/owncloud/web/issues/12100!
- refs https://github.com/owncloud/ocis/issues/10870!
Translatable UI.

fix: add missing User Light role translations definition

---

changelog/unreleased/bugfix-optionally-access-preview-app-route-query.md
packages/web-app-preview/src/App.vue
packages/web-app-preview/tests/unit/app.spec.ts

When filtering out files in preview app, access route query optionally in case it is undefined to prevent broken loading.
- Fixes https://github.com/owncloud/web/issues/12108
- resolves https://github.com/owncloud/web/issues/12106
The app loads even when the route query got somehow lost.
- test case 1: added unit test
- test case 2: open the editor without the route query

fix(web-app-preview): optionally access route query

---

changelog/unreleased/bugfix-change-federated-share-icon.md
changelog/unreleased/bugfix-improve-federated-share-icon-contrast.md
packages/design-system/src/components/OcAvatarFederated/OcAvatarFederated.vue

Use "earth" icon instead of "cloud" and make the icon lighter not to fail contrast check.
- refs https://github.com/owncloud/web/issues/12117
Good a11y and same icon as in other places.
- test case 1: share file with federated user

fix(design-system): use earth icon for federated shares

---

changelog/unreleased/bugfix-show-external-share-indicator.md
packages/design-system/src/styles/theme/oc-flex.scss
packages/web-app-files/src/components/Shares/SharedWithMeSection.vue

The external shares indicator was hidden when permissions indicator was displayed. This prevents users from understanding quickly that the share is actually external. This changes the condition to include both indicators independently.
- refs https://github.com/owncloud/web/issues/12117
Quickly understandable shares.
- test case 1: share resource with external user

fix(web-app-files): show external shares indicator

---

tests/e2e/cucumber/report/index.mjs

Convert report generate script to mjs so that it can be used from within the repo.
```bash
node tests/e2e/cucumber/report/index.mjs
```
- test environment: :raised_hands:

test: convert report generator to mjs

---

changelog/unreleased/enhancement-add-custom-handler-to-file-extensions.md
docs/extension-system/viewer-editor-apps.md
packages/web-pkg/src/apps/types.ts
packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewFile.ts
packages/web-pkg/src/composables/piniaStores/apps.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateNewFile.spec.ts

We've added a new property into application file extensions called `customHandler`. This property allows app developers to use completely custom flows when creating new files.
More freedom in the file creation.
- test case 1: unit tests
- test case 2: run https://github.com/owncloud/web-extensions/pull/130 app and create a folder

feat(web-pkg): add file extension custom handler

---

changelog/unreleased/enhancement-handle-extensions-without-editor.md
packages/web-pkg/src/apps/types.ts
packages/web-pkg/src/composables/actions/files/useFileActions.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActions.spec.ts
packages/web-runtime/src/container/application/classic.ts

When an app does not expose any routes, mark it as editor-less so that we do not try to load editor actions for such extension.
Extension without editor does not break the app.
- test case 1: manually add extension without any routes and open sidebar
- test case 2: extend existing unit tests

feat: handle editor-less extensions

---

docker-compose.yml

With recent update of docker on my Apple Silicon MacBook, the tika container started crashing immediatelly after starting. That then caused random 502 responses when doing requests to oCIS. Adding linux/amd64 seems to fix this. Tika container starts again and 502 responses are gone = I am a happy dev with working env again :).

chore: specify linux/amd64 platform in tika

---

dev/scripts/create_and_push_tags.sh

The signing of the main tag was missed out. This adds the signing flag so that it has the same behaviour as tagging single packages.
Sign tags via script.
- test environment: macos
- test case 1: run the script to tag https://github.com/owncloud/web/tree/v11.1.2

chore: sign main tag

---

changelog/unreleased/enhancement-password-protected-folder-permissions.md
packages/web-app-password-protected-folders/src/components/CreateFolderModal.vue
packages/web-app-password-protected-folders/src/composables/useCreateFileHandler.ts
packages/web-app-password-protected-folders/tests/unit/components/CreateFolderModal.spec.ts
packages/web-app-password-protected-folders/tests/unit/composables/useCreateFileHandler.spec.ts

We've added the permissions dropdown into the create password protected folder dialog. Users can now decide what permissions they would like to add to the folder. Permissions are matching folder public link permissions.
- test case 1: extended unit tests to include permissions change
- test case 2: create folder with set permission

feat(password-protected-folders): add permissions dropdown

---

changelog/unreleased/enhancement-add-password-protected-folders-handler.md
changelog/unreleased/enhancement-control-more-elements-visibility-via-url-query.md
dev/docker/ocis/csp.yaml
packages/web-app-password-protected-folders/src/components/FolderViewModal.vue
packages/web-app-password-protected-folders/src/composables/useCreateFileHandler.ts
packages/web-app-password-protected-folders/src/composables/useOpenFolderAction.ts
packages/web-app-password-protected-folders/tests/unit/components/FolderViewModal.spec.ts
packages/web-app-password-protected-folders/tests/unit/composables/useCreateFileHandler.spec.ts
packages/web-app-password-protected-folders/tests/unit/composables/useOpenFolderAction.spec.ts
packages/web-pkg/src/composables/piniaStores/config/types.ts
packages/web-runtime/src/components/Topbar/TopBar.vue
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/layouts/Application.vue
packages/web-runtime/tests/unit/components/Topbar/TopBar.spec.ts

Add modal rendering an iframe with the public link content using a limited UI.
Give users a way to open password protected folders
- test case 1: open a folder in the browser
- test case 2: extended unit tests

feat(password-protected-folders): open folder in an iframe

---

changelog/unreleased/enhancement-display-default-actions-in-context-menu.md
changelog/unreleased/enhancement-hide-password-protected-folders-actions.md
changelog/unreleased/enhancement-hide-password-protected-folders-extension.md
packages/web-app-password-protected-folders/src/composables/useExtensions.ts
packages/web-client/package.json
packages/web-client/src/helpers/resource/functions.ts
packages/web-client/tests/unit/helpers/resource/functions.spec.ts
packages/web-pkg/src/components/FilesList/ContextActions.vue
packages/web-pkg/src/components/FilesList/ResourceListItem.vue
packages/web-pkg/src/components/SideBar/Files/FileInfo.vue
packages/web-pkg/src/composables/actions/files/useFileActions.ts
packages/web-pkg/src/composables/actions/files/useFileActionsCreateSpaceFromResource.ts
packages/web-pkg/src/constants.ts
packages/web-pkg/tests/unit/components/FilesList/ResourceListItem.spec.ts
pnpm-lock.yaml

Hide .psec extensions, hide all actions except delete, and display default actions in context menu.
Make the file look more like a folder
- test case 1: create a folder, open context menu and see available actions
- test case 2: create a folder, open sidebar and see available actions

feat(password-protected-folders): hide extension and actions

---

changelog/unreleased/enhancement-delete-password-protected-folders.md
packages/web-app-password-protected-folders/src/index.ts
packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
packages/web-pkg/src/composables/webWorkers/deleteWorker/worker.ts
packages/web-pkg/src/constants.ts
packages/web-pkg/tests/unit/composables/actions/helpers/useFileActionsDeleteResources.spec.ts

When deleting `.psec` files, try to get also the related hidden folder and delete it as well. If the folder is not found or user does not have enough permissions, output a warning in the console and ignore it.
Clean files list
- test environment: chrome & unit
- test case 1: delete a psec file in personal space
- test case 2: delete a psec file in space
- test case 3: delete a psec file in space as non-owner

feat(password-protected-folders): delete protected folder

---

changelog/unreleased/bugfix-do-not-render-default-actions-in-context-menu.md
packages/web-app-password-protected-folders/src/composables/useExtensions.ts
packages/web-app-password-protected-folders/src/composables/useOpenFolderAction.ts
packages/web-pkg/src/components/FilesList/ContextActions.vue

We've fixed an issue where the default action was rendered in the context menu leading into duplicate actions being shown. The default action was originally introduced into the context menu to show "Open folder" action of password protected folders extension but we fixed this to use the correct category in the extension which renders the action as expected.
- Fixes https://github.com/owncloud/web/issues/12154
No duplicate actions
- test case 1: open context menu on template file
- test case 2: open context menu on psec file

fix: do not render default actions in context menu

---

changelog/unreleased/bugfix-create-password-protected-folder-in-personal-space.md
changelog/unreleased/enhancement-recursive-folder-creation.md
packages/web-app-password-protected-folders/src/components/CreateFolderModal.vue
packages/web-app-password-protected-folders/src/composables/useCreateFileHandler.ts
packages/web-app-password-protected-folders/tests/unit/components/CreateFolderModal.spec.ts
packages/web-app-password-protected-folders/tests/unit/composables/useCreateFileHandler.spec.ts
packages/web-client/src/webdav/createFolder.ts
packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts

Create the hidden folder in users personal space
Other users cannot access the folder without the pass
- test case 1: Create a password protected folder in users personal space
- test case 2: Create a password protected folder in created space

fix(password-protected-folders): create folder in the personal space

---

changelog/unreleased/bugfix-open-password-protected-folder-when-clicking-on-its-name.md
packages/web-client/src/helpers/resource/functions.ts
packages/web-pkg/src/components/FilesList/ResourceTable.vue
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts

Since all the necessary permissions to allow clickable resource name are missing on password protected folders and we cannot affect what mimetype the file will have, we added a psec file specific condition to skip check of these permissions.
- Fixes https://github.com/owncloud/web/issues/12176
Users can click the file to open it
- test case 1: open the password protected folder by clicking on psec file name

fix: open password protected folder when clicking its name

---

changelog/unreleased/bugfix-skip-upload-dropzone-init-when-files-view-is-missing.md
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts

When initializing the uppy upload dropzone, first check whether the target files view element is present to prevent the app from crashing due to the non-existing target.
- Fixes https://github.com/owncloud/web/issues/12150
Non-crashing app
- test case 1: navigate into any space and then back to personal space

fix(files): check files view presence in upload dropzone init

---

changelog/unreleased/enhancement-allow-camera-in-external-app-iframe.md
packages/web-app-external/src/App.vue
packages/web-app-external/tests/unit/__snapshots__/app.spec.ts.snap

We've added the  attribute into the external app iframe so that users can use their cameras in external apps.
- Fixes https://github.com/owncloud/web/issues/12121
Users can use their cameras
- test case 1: Check whether the attribute is present (we unfortunately cannot run geogebra locally)

feat(external): allow camera

---

.drone.env

This pr bumps ocis stable-7.0 latest commit id.
https://github.com/owncloud/QA/issues/877

[tests-only][full-ci] test: bump ocis stable-7.0 commit id

---

changelog/unreleased/bugfix-prevent-password-protected-folder-move.md
packages/web-pkg/src/helpers/permissions.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsMove.spec.ts
packages/web-pkg/tests/unit/helpers/permissions.spec.ts

To prevent moving password protected folders, check whether the resource is password protected folder and if yes, disable move.
- Fixes https://github.com/owncloud/web/issues/12198
Only delete action is available for password protected folders.
- test case 1: try to move psec file
- test case 2: try to move anything else

fix(pkg): prevent move of psec files

---

changelog/unreleased/bugfix-preserve-current-language-in-password-protected-folder-view.md
changelog/unreleased/enhancement-add-lang-url-query-parameter.md
packages/web-app-password-protected-folders/src/components/FolderViewModal.vue
packages/web-app-password-protected-folders/tests/unit/components/FolderViewModal.spec.ts
packages/web-pkg/src/composables/piniaStores/config/types.ts
packages/web-runtime/src/container/bootstrap.ts
packages/web-runtime/src/index.ts
packages/web-runtime/tests/unit/container/bootstrap.spec.ts

This adds a new  URL query parameter which is used as the default language of the UI. It is ignored when the value does not match supported language codes or when user is logged in. This param is now used in folder view in password protected folders app to preserve the language when opening a folder.
- Fixes https://github.com/owncloud/web/issues/12186
Preserved language when opening password protected folders.
- test case 1: change language of the UI to something different than the default value and open password protected folder

fix: preserve language in password protected folders

---

changelog/unreleased/bugfix-display-shared-file-versions.md
packages/web-client/src/helpers/share/functions.ts
packages/web-client/src/helpers/share/types.ts
packages/web-pkg/src/composables/resources/useCanListVersions.ts
packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
packages/web-pkg/tests/unit/composables/resources/useCanListVersions.spec.ts

Instead of checking permissions of the space, check permissions directly on the resource object if it is an incoming share because the space is manually built there without permissions.
- Fixes https://github.com/owncloud/web/issues/12168
Versions are visible when shared with correct permissions.
- test case 1: share a file with sufficient permissions

fix: display shared file versions

---

.drone.env

This pr bumps commit id of ocis stable-7.0
Part of: https://github.com/owncloud/QA/issues/877

[tests-only][full-ci] bump ocis stable-7.0 commit id

---

tests/e2e/cucumber/environment/index.ts
tests/e2e/cucumber/features/admin-settings/users.feature
tests/e2e/cucumber/steps/ui/adminSettings.ts
tests/e2e/support/api/graph/userManagement.ts
tests/e2e/support/api/keycloak/user.ts
tests/e2e/support/api/token/index.ts
tests/e2e/support/api/token/utils.ts

The error https://github.com/owncloud/web/issues/11669 can occur if the request is too early, so I have added a retry mechanism with a timeout if that happens.
- Fix user deletion in after hook: refresh admin token before trying to delete user
- Retry logon if the server returns 502 
- Fixes https://github.com/owncloud/web/issues/11669
- test environment: :raised_hands:

[tests-only][full-ci] retry logon until timeout if the server responds with 502

---

changelog/unreleased/bugfix-broken-title-for-public-files-link.md
packages/web-app-files/src/views/spaces/GenericSpace.vue

Currently, the window title is incorrectly shown when user opens a public link.
- Fixes https://github.com/owncloud/web/issues/12220
- test case 1:
- test case 2:
- ...

bugfix: show correct window title when opening a public link

---

changelog/unreleased/bugfix-disable-password-protected-folders-creation-inside-public-links.md
packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
packages/web-app-files/tests/unit/components/AppBar/__snapshots__/CreateAndUpload.spec.ts.snap
packages/web-app-password-protected-folders/src/composables/useApplicationFileExtensions.ts
packages/web-app-password-protected-folders/src/index.ts
packages/web-app-password-protected-folders/tests/unit/composables/useApplicationFileExtensions.spec.ts
packages/web-pkg/src/apps/types.ts
packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewFile.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateNewFile.spec.ts

To prevent all kinds of issues with nested password protected folders, disable their creation inside of folders shared via public link.
- Fixes https://github.com/owncloud/web/issues/12190
- resolves https://github.com/owncloud/web/issues/12182
Password protected folders are opened via public links. This mainly prevents creation of password protected folders within another password protected folder.
- test case 1: open a password protected folder via the psec file and try to create a new one
- test case 2: open a password protected folder via its hidden folder and try to create a new one

fix: disable psec creation in public links

---

changelog/unreleased/bugfix-add-password-policies-to-password-protected-folders.md
packages/web-app-password-protected-folders/src/components/CreateFolderModal.vue
packages/web-app-password-protected-folders/tests/unit/components/CreateFolderModal.spec.ts

Add password policies to the create password protected folder modal so that users are prevented from trying to create folders with invalid passwords.
- refs https://github.com/owncloud/web/issues/12223
Users are prevented from making an error.
- test case 1: create a password protected folder

fix: add password policies to psec

---

changelog/unreleased/bugfix-make-password-protected-folder-tile-clickable.md
packages/web-pkg/src/components/FilesList/ResourceTiles.vue
packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts

Due to missing permissions on the psec resource, check whether it is a password protected folder and then automatically allow it.
- Fixes https://github.com/owncloud/web/issues/12193
Folder can be easily opened.
- test case 1: in tiles view mode, click on psec file

fix(pkg): make psec files clickable

---

dev/scripts/bump_versions.sh

In the bump versions script, include also a script to bump the project version in sonar properties file.
No need to do it manually - removes user error
- test environment: macOS + zsh
- test case 1: run the bump script and check the sonar properties file

chore: extend version bump script to sonar

---

changelog/unreleased/bugfix-generate-public-link-password-on-click.md
packages/web-pkg/src/components/CreateLinkModal.vue

Directly calling the generate method caused the new password being passed instead of the method as callback. Also, needs to be passed using arrow function. Otherwise it looses the password rules.
Users can generate passwords again.
- test case 1: generate password when creating new link
- test case 2: generate password when editing existing link

fix(web-pkg): pass generate link password method as callback

---

changelog/unreleased/bugfix-add-password-generator-into-password-protected-folders.md
packages/web-app-password-protected-folders/src/components/CreateFolderModal.vue

Add missing generate password method.
Users can generate passwords instead of typing them manually.
- test case 1: generate password when creating password protected folder

fix(web-app-password-protected-folders): add password generator

---

tests/e2e/cucumber/steps/ui/public.ts
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/environment/actor/actor.ts
tests/e2e/support/objects/app-files/page/public.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts
tests/e2e/support/objects/app-files/resource/webOffice.ts

This PR hardens that weboffice e2e tests.
Notable changes:
- separate weboffice actions to own file
- use localStorage to disable some weboffice dialogs
- remove unnecessary try catch

[tests-only][full-ci] harden weboffice tests

---

tests/e2e/cucumber/features/file-action/passwordProtectedFolder.feature

This PR add tests for deleting the password protected folders in both Personal and Project spaces
```gherkin
Scenario: password-protected folder in personal space
Scenario: password-protected folder in project space
```
- Related to: https://github.com/owncloud/web/issues/12181
- Locally
- CI

[tests-only][full-ci] Test for deleting password protected folder

---

changelog/unreleased/bugfix-two-spaces-are-created-on-enter.md
packages/design-system/src/components/OcModal/OcModal.vue
packages/design-system/src/components/OcTextInput/OcTextInput.vue

This bugfix addresses an issue where pressing the Enter key in a modal to create a space or folder results in the creation of two spaces or folders instead of just one. The fix ensures that only a single space or folder is created when the Enter key is pressed.
- Fixes https://github.com/owncloud/web/issues/12276
- test case 1:
- test case 2:
- ...

bugfix: create only one space/folder when user presses enter on modal

---

.drone.env
tests/e2e/cucumber/features/app-provider/officeSuites.feature
tests/e2e/cucumber/features/file-action/groupActions.feature
tests/e2e/cucumber/features/journeys/kindergarten.feature
tests/e2e/cucumber/features/ocm/ocm.feature
tests/e2e/cucumber/features/shares/share.feature
tests/e2e/cucumber/features/smoke/activity.feature
tests/e2e/cucumber/features/smoke/sse.feature
tests/e2e/cucumber/features/smoke/tags.feature
tests/e2e/cucumber/features/smoke/trashbinDelete.feature
tests/e2e/cucumber/features/spaces/project.feature
tests/e2e/cucumber/features/user-settings/notifications.feature
tests/e2e/support/api/share/share.ts

This PR fixes some E2E tests which are failing after renaming the role "Can edit" to "Can edit without versions".
- Fixes [#11104](https://github.com/owncloud/ocis/issues/11104)
- Relates to [PR #11116](https://github.com/owncloud/ocis/pull/11116)
Some of the E2E tests for [PR #11116](https://github.com/owncloud/ocis/pull/11116) were failing after the changes.
To be able to fix them, first these changes should be merged into `stable-11.0` branch of the `web` repo.
- Tested locally
- Tested by executing the Drone job

[full-ci] Fix failing E2E tests

---

changelog/unreleased/bugfix-do-not-reveal-generated-password.md
changelog/unreleased/bugfix-drop-advanced-mode-when-creating-links.md
packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts
packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
packages/design-system/src/components/_OcTextInputPassword/_OcTextInputPassword.vue
packages/web-pkg/src/components/CreateLinkModal.vue
packages/web-pkg/tests/unit/components/CreateLinkModal.spec.ts
tests/e2e/support/objects/app-files/link/actions.ts

Drop the advanced mode and display password and expiration fields immediately. Also, stop revealing password inside of the password input after generating a password.
- Fixes https://github.com/owncloud/web/issues/12275
Streamlined process and secure password generation
- test case 1: create new public link
- test case 2: generate password

fix: drop links advanced mode

---

tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/utils/dragDrop.ts

Replacing playwright `dragTo` with a function that does the drag-n-drop manually.
I ran the tests with and without the fix and the manual one didn't show any failure whereas the tests can fail with the in-built `dragTo` function.
- Fixes https://github.com/owncloud/web/issues/12233

[full-ci][tests-only] use manual elements drag-n-drop in the tests

---

changelog/unreleased/bugfix-delete-psec-file.md
packages/web-app-password-protected-folders/README.md
packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
packages/web-pkg/src/composables/piniaStores/spaces.ts
packages/web-pkg/tests/unit/composables/actions/helpers/useFileActionsDeleteResources.spec.ts

Delete `.psec` file if it still matches path and name of the hidden folder.
- Fixes https://github.com/owncloud/web/issues/12273
No zombie files
- test case 1: Create password protected folder in space and then delete the actual folder

fix: delete psec file when deleting password protected folder

---

changelog/unreleased/bugfix-handle-shares-loading-error.md
packages/design-system/src/styles/theme/oc-text.scss
packages/web-app-files/src/components/SideBar/Shares/SharesPanel.vue
packages/web-pkg/src/components/SideBar/FileSideBar.vue
packages/web-pkg/src/composables/piniaStores/shares/shares.ts

Add try catch to handle the error and display an error message instead of infinite loader.
- refs https://github.com/owncloud/ocis/issues/11119
Users know that the loading failed.
- test case 1: Trigger an error during shares load

fix: handle shares loading error

---

.drone.env

This pr bumps latest commit id of ocis stable-7.1 branch.
Part of: https://github.com/owncloud/QA/issues/880

[tests-only][full-ci] bump ocis stable-7.1 commit-id

---

packages/design-system/src/components/OcButton/OcButton.vue
packages/design-system/src/components/OcSpinner/OcSpinner.vue
packages/design-system/vite.config.ts
packages/web-pkg/vite.config.ts
vite.config.ts

Replace SASS `round` function with the correct `math.round` to keep using the SASS function.
- Fixes https://github.com/owncloud/web/issues/12314
No deprecation warnings and consistent functions usage.
- test environment: 🤖 
- test case 1: Run `pnpm build`

chore: fix SASS round function deprecation

---

changelog/unreleased/bugfix-order-spaces-in-project-view
packages/web-app-files/src/views/spaces/Projects.vue

The order by function is broken in spaces view. Just go here: https://demo.owncloud.com/ and to spaces and try to sort via any quota. it breaks the view.
**Fix**: Test if value a string before committing it the toLowerCase function.
Please merge asap, because alot of user have a broken view when using the orderby in the spaces view. Thank you.

Fix sorting in spaces view may crash the application

---

changelog/unreleased/bugfix-show-path-tooltip-on-parent-folder.md
packages/web-pkg/src/components/FilesList/ResourceListItem.vue
packages/web-pkg/src/components/FilesList/ResourceName.vue
packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceName.spec.ts.snap

Instead of showing the path tooltip on the actual resource, show it on the parent folder using its path as a content.
- Fixes https://github.com/owncloud/web/issues/7776
- test case 1: hover on the resource and on its parent folder

fix(web-pkg): move path tooltip to parent folder

---

changelog/unreleased/bugfix-handle-changed-public-link-password-in-file-editors.md
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue

If public link password is changed and any user with already opened file shared via that link inside of an editor refreshes the page, redirect to the link password screen instead of displaying an error.
- Fixes https://github.com/owncloud/web/issues/12113
User can quickly enter the password again and continue editing instead of being confused by an error which even uses "username" in there...
- test case 1: open public links shared .txt file, change password, refresh page

fix(web-pkg): display password screen when link auth fails in editors

---

.drone.star
tests/drone/config-ocis-federated.json
tests/drone/providers.json

Define ocm providers using patterns. Run tests with this ocm setup in the CI.
- Cover issue: https://github.com/owncloud/enterprise/issues/7073
- https://github.com/cs3org/reva/pull/5061
- test environment: :raised_back_of_hand: :robot:

[tests-only][full-ci] combine ocm provider configs using wildcards

---

docker-compose.yml
tests/e2e/cucumber/features/app-provider/officeSuites.feature
tests/e2e/support/environment/actor/actor.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/webOffice.ts

Check the lock status of the word document when created/edited in OnlyOffice.
The lock is released after sometime when opened in OnlyOffice. and when we open the file before the lock is released, there will be no content in the file leading to the flakiness.
- Reduce failure like https://drone.owncloud.com/owncloud/web/51407/13/16
- :raised_hand_with_fingers_splayed:

[tests-only][full-ci] check lock before opening word document file 

---

changelog/unreleased/bugfix-use-resource-id-in-share-notifications.md
changelog/unreleased/bugfix-watch-scroll-target-in-shared-list.md
packages/web-app-files/src/views/shares/SharedWithMe.vue
packages/web-runtime/src/components/Topbar/Notifications.vue
packages/web-runtime/tests/unit/components/Topbar/Notifications.spec.ts

Use resource ID instead of share ID to find the correct resource and watch for scroll target change to react to the click when the shared with me list is already opened.
- Fixes https://github.com/owncloud/web/issues/10398
List correctly reacts to user action
- test case 1: share a resource with einstein and click on the notification from personal space
- test case 2: share a resource with einstein and click on the notification from shared with me list

fix: scroll to resource on share notification click

---

changelog/unreleased/bugfix-download-archives-directly.md
changelog/unreleased/bugfix-request-archive-as-blob.md
packages/web-pkg/src/services/archiver.ts
packages/web-pkg/tests/unit/services/archiver.spec.ts

When in authenticated context or inside public links without password, download the archive file directly by opening the download URL instead of fetching it. This gets around constrains on memory. In public links with password, we still need to request the file first due to missing public link signed URLs. At least we are now requesting the file as blob instead of arraybuffer which works at least with bigger limits in Chrome and Firefox.
- Fixes https://github.com/owncloud/web/issues/12405
Users are able to download large archives without errors and their memory being nuked.
- test environment: chrome & safari & firefox
- test case 1: download archived folder with 2GB+ content
- test case 2: download several files with total size 2GB+

fix(web-pkg): download archives directly

---

packages/web-pkg/package.json
packages/web-pkg/src/services/archiver.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActionsDownloadArchive.spec.ts
packages/web-pkg/tests/unit/services/archiver.spec.ts
pnpm-lock.yaml

oC10 is not supported for several major versions. This drops archiver code specific to version 1 (oC10) archivers.
- Fixes https://github.com/owncloud/web/issues/12403
Cleanup 🧹 
- test case 1: download an archive with oCIS

chore(web-pkg): drop oC10 archiver handling

---

changelog/unreleased/enhancement-add-tag-characters-limit.md
packages/web-app-admin-settings/tests/unit/components/Users/SideBar/EditPanel.spec.ts
packages/web-app-files/src/components/SideBar/Details/TagsSelect.vue
packages/web-app-files/tests/unit/components/SideBar/TagsSelect.spec.ts
packages/web-client/src/ocs/capabilities.ts
packages/web-pkg/src/composables/piniaStores/capabilities.ts
packages/web-runtime/tests/unit/pages/account.spec.ts
packages/web-test-helpers/src/mocks/pinia.ts

Read limit set via config from capabilities and apply it to resource tags. Defaults to 30.
Secure web app.
- test case 1: set oCIS config to limit chars to 8 and try to create tag with >= 9 chars

feat: limit tag chars

---

changelog/unreleased/bugfix-wrong-html-lang-attribute.md
packages/web-runtime/src/App.vue
packages/web-runtime/tests/unit/App.spec.ts
packages/web-test-helpers/src/defaultPlugins.ts

We've added a fix to ensure that the HTML lang attribute is set correctly in the web application. This change improves accessibility and ensures that screen readers and other assistive technologies can properly interpret the language of the content.
- Fixes https://github.com/owncloud/web/issues/12409
- test case 1:
- test case 2:
- ...

bugfix: set correct html lang attribute

---

packages/web-app-files/src/components/SideBar/Details/TagsSelect.vue

We are using plural form all over the UI. This just makes it consistent.
- Fixes https://github.com/owncloud/web/issues/12480
Consistent UI.

fix: use plural form of tags in chars limit message

---

changelog/unreleased/bugfix-deleted-resource-throws-unknown-error.md
packages/web-pkg/src/components/AppTemplates/AppWrapper.vue

We've added a friendly error message when user tries to open a resource that has been deleted.
- Fixes https://github.com/owncloud/web/issues/12461
- test case 1:
- test case 2:
- ...

bugfix: refreshing page with a deleted resource throws unknown error

---

changelog/unreleased/enhancement-add-ocm-explanatory-tooltips.md
packages/web-app-ocm/src/views/ConnectionsPanel.vue

Add two tooltips to connections panel in OCM to better explain users and institutions.
- Fixes https://github.com/owncloud/web/issues/11567
Better user understanding of the complex OCM topic.
- test case 1: create connection and see tooltips

feat(web-app-ocm): add explanatory tooltips

---

tests/e2e/cucumber/features/ocm/ocm.feature
tests/e2e/cucumber/steps/ui/shares.ts

check `Domain` of external user in the share details
- https://github.com/owncloud/web/issues/12184

[full-ci][tests-only] check domain detail of external collaborator

---

packages/web-pkg/src/components/TextEditor/TextEditor.vue

This renames the label of supported languages link in the markdown to . This change should prevent
confusion with spoken languages. As a small bonus, add context to the translations so it is clear in Transifex as well.
No confusion.
- test case 1: Open the markdown editor and see links

fix: rename languages link in md editor

---

changelog/unreleased/enhancement-add-spinner.md
packages/web-runtime/src/pages/resolvePublicLink.vue
packages/web-runtime/tests/unit/pages/resolvePublicLink.spec.ts

add loading spinner to submit button for password-protected public links.
We have enhanced the user experience by displaying a loading spinner and disabling the submit button when clicked on password-protected public links. This ensures users on slower connections receive clear feedback that their request is being processed.
- Fixes https://github.com/owncloud/enterprise/issues/7190
- test case 1:
- test case 2:
- ...

feat: add loading spinner to submit button for password-protected public links

---

docs/testing/testing.md

Add documentation on how to run web e2e tests with predefined users
closes https://github.com/owncloud/web/issues/12425

docs: add docs about running e2e tests with predefined users

---

.drone.env

Bump latest ocis stable-7.1 commit id.
Part of: https://github.com/owncloud/QA/issues/884

[test-only][full-ci] bump ocis stable-7.1 commit id

---

packages/design-system/package.json
pnpm-lock.yaml

We are no longer using this dependency for anything. Away with it! Surpasses https://github.com/owncloud/web/pull/12530.
Clean house 🧹 
- test environment: 🤖 
- test case 1: CI passes

chore(design-system): drop npm-run-all2 dependency

---

tests/e2e/cucumber/features/file-action/copyMove.feature
tests/e2e/cucumber/steps/ui/resources.ts
tests/e2e/support/objects/app-files/resource/actions.ts
tests/e2e/support/objects/app-files/resource/index.ts

This PR add tests for duplicating resources using sidebar panel, dropdown-menu, and batch-action button
- https://github.com/owncloud/web/issues/9898
- locally

[full-ci][tests-only]Add tests for duplicating resources

---

tests/e2e/cucumber/environment/index.ts
tests/e2e/support/environment/actor/shared.ts

some browser capabilities and permissions are not supported in all browsers (chromium, firebfox, webkit). Therefore, adding the correct browser configs based on their support.

[tests-only][full-ci] set configs based on browser support

---

changelog/unreleased/enhancement-disable-space-membership-management-when-its-server-managed
packages/web-client/src/ocs/capabilities.ts
packages/web-pkg/src/composables/piniaStores/capabilities.ts
packages/web-pkg/src/composables/shares/useCanShare.ts

Add a check to the canShare permissions check to assert on space whether the  capability is set. If it is , hide the "Add members" section and member edit options in the "Members" panel in space sidebar.
Respect capabilities and allow space members to be maintained via OIDC claims.
- test case 1: `server_managed` is `true`
- test case 2: `server_managed` is `failse`

feat: add configurable space members management

---

dev/docker/ocis.idp.config.yaml
dev/docker/ocis.storage.ocmproviders.json
dev/docker/ocis.web-federated.config.json
docker-compose.yml
tests/e2e/config.js

Use the same hostname for both ocis instances:
```diff
host.docker.internal:9200
- ocis.owncloud.test:10200
+ host.docker.internal:10200
```
This reduces the need for adding many hosts in the system while using the `docker-compose.yml` setup.
Fix: `collabora/code:25.04.2.1.1` was not working, so replaced it with `collabora/code:24.04.10.2.1` (same as in the CI)

[full-ci] use same hostname for both ocis instances in docker compose setup

---

.drone.star

Make docker images accessible to renovate bot by suffixing `_IMAGE` in the variables.

ci: make .drone.star docker images accessible by renovate

---

.drone.env

This PR bump latest commit id of ocis `stable-7.1` branch.
Part of: https://github.com/owncloud/QA/issues/885

[tests-only][full-ci] bump ocis latest commit id of ocis stable branch

---

changelog/unreleased/bugfix-do-not-crash-when-tus-is-unsupported.md
packages/web-pkg/src/composables/piniaStores/capabilities.ts

When TUS is not supported, we were not setting a fallback value. This was causing the app to crash. We're now setting an empty string as fallback value so that we can still call `includes` method and not crash the app. Based on https://github.com/owncloud/web/pull/11946/commits/2a1319b5aa8de11bfffcd9c26f1d4eb9a21f4568.
App without crashes.

fix(web-pkg): do not crash when TUS is unsupported

---

.drone.env
.drone.star
tests/drone/script.sh

Follow up: https://github.com/owncloud/web/pull/12594
images defined in .drone.star are accessible to renovate if `_IMAGE` suffix is used. Example: https://github.com/owncloud/web/pull/12595

[full-ci] make .drone.star images accessible by renovate

---

changelog/unreleased/enhancement-hide-active-editor-action.md
packages/web-pkg/src/composables/actions/files/useFileActions.ts
packages/web-pkg/tests/unit/composables/actions/files/useFileActions.spec.ts

When an editor is already opened and the user clicks on the Open in ... action, it pushes the same editor route into the history causing a bug where the user needs to click twice on the close button to actually close the editor. This change hides the editor action if an editor with matching route name is already opened which prevents this behaviour.
- refs https://github.com/owncloud/web/issues/12108
No confusion with re-opening the active editor.
- test case 1: added unit test
- test case 2: open an image in the preview app and open sidebar

fix(web-pkg): hide sidebar editor action when the editor is already opened

---

changelog/unreleased/enhancement-add-login-error.md
packages/web-runtime/src/pages/login.vue

When the login fails due to any kind of error, the user is now presented with an error message.
User is not stuck in endless loading spinner loop.
- test case 1: run ocis and kill idp

feat(web-runtime): add login error

---

.drone.star
docs/Makefile

This PR fixes the global build pipeline for owncloud.dev.
Compared to the `.drone.star` pipeline in ocis, this one copied the `docs` folder and not the `docs/hugo/content/web` folder causing a loophole within hugo when running a build via `owncloud.github.io`

Fix the global owncloud.dev build process

---

docs/Makefile

The `make docs-clean` command has been updated.
Because a doc build uses a docker image, files created by hugo are now from the root user in folder `docs/hugo` which needs elevated permissions to delete them.

[docs-only] Update the make docs-clean command

---

changelog/unreleased/bugfix-export-correct-design-system-files.md
packages/design-system/package.json

After recent changes, the built files changed and instead of exporting CommonJS modules as .js files, we are now exporting ESM as .js and CommonJS as .cjs. The exports field in package.json was not adjusted causing issues when installing the package. This uses correct file extensions.
Correct files.

fix(design-system): export ESM as .js

---

.drone.env

Bump latest ocis `stable-7.1` branch commit id.
Part of: https://github.com/owncloud/QA/issues/887

[tests-only][full-ci] Bump latest ocis commit id on stable-11.0 branch

---

changelog/unreleased/bugfix-handle-direct-admin-settings-access.md
packages/web-app-admin-settings/src/index.ts
packages/web-app-admin-settings/tests/unit/index.spec.ts

Opening the admin settings directly by pasting the URL in the browser address bar or opening the app in a new tab now works correctly. The redirect was not correctly using the navigation guard leading to a mismatch in users permissions. We now redirect to the first available route and leave the route itself to handle the permissions navigation guard.
Users can open admin settings by entering URL address.
- test environment: macos, chrome
- test case 1: open admin settings on new tab
- test case 2: open admin settings by entering URL

fix(web-app-admin-settings): [OCISDEV-138] handle direct admin settings access

---

.drone.env

Bump latest ocis `stable-7.2` branch commit id.
Part of: https://github.com/owncloud/QA/issues/890

[tests-only][full-ci] Bump latest ocis commit id on stable-12 branch

---

packages/web-client/src/helpers/share/functions.ts
packages/web-pkg/src/components/FilesList/ResourceListItem.vue
packages/web-pkg/src/composables/folderLink/useFolderLink.ts

Fixes an issue where a shared space incorrectly showed its own folder as the parent. Now, it correctly points to the root folder of the space. Also, the parent folder is now labeled as "Spaces" instead of ".".
- test case 1:
- test case 2:
- ...

bugfix(web-client, web-pkg): [OCISDEV-208] space parent return invalid path when parent is spaces' root

---

changelog/unreleased/bugfix-deactivated-spaces-clips-german-translated-word.md
packages/design-system/src/components/OcFilterChip/OcFilterChip.vue

We have fixed an issue where the "Deactivated Space" button would clip the German translated word. The button now displays the full word without clipping.
- test case 1:
- test case 2:
- ...

bugfix(design-systems): [OCISDEV-194] fixes clipped german translation of deactivated spaces button

---

packages/design-system/package.json
packages/design-system/vite.config.ts
packages/web-client/package.json
packages/web-client/vite.config.ts
packages/web-pkg/package.json
packages/web-pkg/vite.config.ts
packages/web-test-helpers/package.json
packages/web-test-helpers/vite.config.ts

Explicitly set export path for types and use that path in package exports.
Seems that (probably during a dependency update) the types started being exported into a different directory (`/dist/packages`). This broke the exports in packages because they were pointing to non-existing directories. By hardcoding the `outDir`, we make sure that it stays in our desired directory.
- test environment: macos, node v22
- test case 1: build all the affected packages and check whether the paths match

chore: [OCISDEV-272] fix packages type exports

---

changelog/unreleased/bugfix-add-clipboard-permissions.md
packages/web-app-external/src/App.vue
packages/web-app-external/tests/unit/__snapshots__/app.spec.ts.snap

Added clipboard permissions to the iframe in external apps to allow the external editor to read and write to the clipboard.
With latest OnlyOffice version updated [here](https://github.com/owncloud/web/pull/12937), copying and pasting got broken due to missing permissions.
- test environment: macos, chrome
- test case 1: copy text inside onlyoffice
- test case 2: paste text inside onlyoffice

fix(web-app-external): add clipboard permissions

---

changelog/unreleased/bugfix-sign-public-link-archiver-download-url.md
packages/web-app-files/src/helpers/user/avatarUrl.ts
packages/web-app-files/tests/unit/helpers/user/avatarUrl.spec.ts
packages/web-client/src/ocs/index.ts
packages/web-client/src/ocs/urlSign.ts
packages/web-client/src/webdav/getFileUrl.ts
packages/web-pkg/src/composables/actions/files/useFileActionsDownloadArchive.ts
packages/web-pkg/src/services/archiver.ts
packages/web-pkg/src/services/client/client.ts
packages/web-pkg/tests/unit/services/archiver.spec.ts
packages/web-runtime/src/index.ts

Start signing the archiver download URL in public link context in case the link is password protected. This allows users to download large archives without memory limits imposed by browsers.
- Fixes https://github.com/owncloud/web/issues/12811
Users can download large archives.
- test environment: macos, chrome
- test case 1: share a folder with several files with total size 5 GB+ via link protected by password, access the link and try to download them as archive

fix: [OCISDEV-147] sign public link archiver download URL

---

changelog/unreleased/bugfix-md-editor-code-block-header-cuts-off-other-elements.md
packages/web-pkg/src/components/TextEditor/TextEditor.vue

We have fixed an issue where the code block header in the markdown editor was cutting off other elements on the page. This has been resolved by setting the z-index of the code block header to 0.
- Fixes https://kiteworks.atlassian.net/browse/OCISDEV-307
- test case 1:
- test case 2:
- ...

bugfix(web-pkg): [OCISDEV-307] set md editor code head to have z-index of 0

---

changelog/unreleased/bugfix-make-progress-bar-settings-reactive.md
packages/web-runtime/src/layouts/Application.vue

We had a bug where the progress bar settings were not reactive. This caused labels to not be updated when the language changed. Adding reactivity to the progress bar settings fixes this issue.
Fully reactive UI.
- test environment: macos, chrome
- test case 1: change locale in settings and watch progress bar strings
https://github.com/user-attachments/assets/9f6acfcd-8493-40be-98d9-1db8154155c5

fix: [OCISDEV-267] make progress bar settings reactive

---

.drone.star
package.json
tests/e2e-playwright/helpers/setAccessAndRefreshToken.ts
tests/e2e-playwright/playwright.config.ts
tests/e2e-playwright/specs/internalLink.spec.ts
tests/e2e-playwright/steps/api/api.ts
tests/e2e-playwright/steps/ui/index.ts
tests/e2e-playwright/steps/ui/public.ts
tests/e2e-playwright/steps/ui/resources.ts
tests/e2e-playwright/steps/ui/session.ts
tests/e2e-playwright/steps/ui/shares.ts
tests/e2e/support/api/davSpaces/spaces.ts

Rewrite the old Cucumber test from `tests/e2e/cucumber/features/shares/internalLink.feature` with a new Playwright test at `tests/spec/internalLink.spec.ts`
https://github.com/owncloud/web/issues/12938
To run test locally in `chromium` in `headed` mode
```
pnpm test:e2e:playwright --project=chromium --headed
```

[POC][tests-only] e2e tests with Playwright only

---

changelog/unreleased/universal-icon-has-incorrect-color.md
packages/design-system/src/components/OcRemoteIcon/OcRemoteIcon.vue

- Fixes https://kiteworks.atlassian.net/browse/OCISDEV-353
- test case 1:
- test case 2:
- ...

bugfix(design-system): fix incorrect universal icon color
