- .drone.star
Backport of PR : https://github.com/owncloud/web/pull/9600 and https://github.com/owncloud/web/pull/9599
> [tests-only][full-ci]Backport drone nightly changes from master to `stable-7.1`

- changelog/unreleased/enhancement-set-expiration-date-in-three-dots-menu
- packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
- test case 1:
- test case 2:
- ...
> close dd on date pick

- tests/e2e/support/objects/app-files/link/actions.ts
- tests/e2e/support/objects/app-files/share/actions.ts
This PR is backport of master https://github.com/owncloud/web/pull/9616
> [tests-only][full-ci] Backport wait for pop-up before removing it 

- .drone.env
- .drone.star
- docker-compose.yml
- docs/backend-ocis.md
- tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
- tests/acceptance/nightwatch.conf.js
- tests/acceptance/stepDefinitions/generalContext.js
- tests/drone/config-ocis.json
This PR bump latest ocis commit id.
Part of https://github.com/owncloud/QA/issues/824
> [tests-only] [full-ci] Bump ocis commit id latest stable

- packages/web-app-files/src/composables/actions/files/useFileActionsMove.ts
- packages/web-app-search/src/portals/SearchBar.vue
- packages/web-pkg/src/components/SearchBarFilter.vue
- packages/web-pkg/src/composables/search/constants.ts
- packages/web-pkg/tests/unit/components/SearchBarFilter.spec.ts
- tests/e2e/cucumber/features/smoke/fullTextSearch.feature
- tests/e2e/cucumber/features/smoke/search.feature
- tests/e2e/cucumber/features/smoke/searchProjectSpace.feature
- tests/e2e/support/objects/app-files/resource/actions.ts
- Fixes https://github.com/owncloud/web/issues/9628
- test case 1:
- test case 2:
- ...
> Change search location filter names

- .drone.env
This PR bumps latest ocis commit id.
Part of https://github.com/owncloud/QA/issues/824
> [tests-only][full-ci] bumps ocis latest commit id

- .drone.env
This PR bumps latest ocis commit id.
Part of https://github.com/owncloud/QA/issues/824
> [tests-only][full-ci] Bump oCIS commit id

- changelog/unreleased/bugfix-pdf-loading-safari
- changelog/unreleased/bugfix-set-or-remove-expiration-date-on-group-share-not-possible
- packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
- packages/web-app-files/src/components/Search/List.vue
- packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
- packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.vue
- packages/web-app-files/src/helpers/contextualHelpers.ts
- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.spec.ts
- packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/__snapshots__/ExpirationDatepicker.spec.ts.snap
- packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap
- packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/SpaceMembers.spec.ts.snap
- packages/web-app-pdf-viewer/src/App.vue
- packages/web-pkg/src/components/ItemFilter.vue
- packages/web-pkg/src/components/SearchBarFilter.vue
Re-adds the latest reverted changes (see https://github.com/owncloud/web/pull/9586).
**Only merge after `7.1.0` has been released!**
> Revert "chore: revert recent commits until 7.1.0-rc.5 (#9586)"

- packages/web-app-files/src/views/spaces/DriveResolver.vue
See here for background: https://github.com/owncloud/web/issues/9296#issuecomment-1653084649
> feat: prevent public links resolving to actual location for CERN

- packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
This PR updates the unit test snapshot since it is failing in CI.
https://github.com/owncloud/web/issues/9659
> [tests-only][full-ci]Update unit test snapshot

- packages/design-system/src/components/OcTextInput/OcTextInput.vue
- packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
- packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/SpaceMembers.spec.ts.snap
- packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
- packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
- Part of https://github.com/owncloud/web/issues/9638
- 
- test case 1:
- test case 2:
- ...
> Render portal conditinal

- changelog/unreleased/enhancement-add-password-policy-compatibility
- packages/web-client/src/ocs/capabilities.ts
- packages/web-pkg/src/services/passwordPolicy/passwordPolicy.ts
- packages/web-pkg/tests/unit/services/passwordPolicy.spec.ts
- test case 1:
- test case 2:
- ...
> Password policy followup

- .drone.star
- docs/testing/testing.md
- tests/e2e/config.js
- tests/e2e/cucumber/environment/index.ts
- tests/e2e/support/api/http.ts
- tests/e2e/support/objects/runtime/session.ts
We've switched to using an api token, and now I make using it by default
> [full-ci] Using auth token by default

- packages/design-system/src/components/OcFilterChip/OcFilterChip.vue
- packages/web-pkg/tests/unit/components/__snapshots__/ItemFilter.spec.ts.snap
See https://github.com/owncloud/web/issues/9618
- Fixes https://github.com/owncloud/web/issues/9618
[screen-capture (7).webm](https://github.com/owncloud/web/assets/786551/e21ac960-0bd5-4501-9c53-95ef52f413e6)
> Enhancement: Add animation to filter tag

- packages/web-app-files/src/components/FilesList/QuickActions.vue
- packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
- packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
- packages/web-app-files/src/quickActions.ts
- packages/web-pkg/src/services/passwordPolicy/passwordPolicy.ts
- packages/web-runtime/src/index.ts
- test case 1:
- test case 2:
- ...
> fix init as store wasnt ready

- packages/design-system/src/components/_OcTextInputPassword/_OcTextInputPassword.vue
- packages/web-app-admin-settings/src/views/Spaces.vue
- packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
- packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/__snapshots__/SpaceDetails.spec.ts.snap
- packages/web-runtime/src/components/Topbar/UserMenu.vue
- packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.ts.snap
- Fixes https://github.com/owncloud/web/issues/9668
- test case 1:
- test case 2:
- ...
> Show space id in admin settings

- packages/design-system/src/components/OcBreadcrumb/OcBreadcrumb.vue
- packages/design-system/src/components/OcBreadcrumb/__snapshots__/OcBreadcrumb.spec.ts.snap
Make `to` optional in Breadcrumb items. If `to` is missing, items are not clickable and have no hover effect.
- Prepares #6120
We need to support inaccessible breadcrumb items for #6120.
> breadcrumbs: Support inaccessible breadcrumbs

- package.json
- pnpm-lock.yaml
- vite.cern.config.ts
- vite.config.ts
- test case 1:
- test case 2:
- ...
> Vite: Enable history mode

- packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/RoleDropdown.spec.ts
If owner of folder shared folder with group they are part of, they would loose owner permission.
Fixing it with checking if owner matches user.
- Fixes https://github.com/owncloud/web/issues/9225
> Owner sharing folder with group keeping owner permissions

- packages/design-system/src/components/OcDrop/OcDrop.vue
- packages/design-system/src/components/OcDrop/__snapshots__/OcDrop.spec.ts.snap
Changing max width of OcDrop.vue from 400 to 416px to account for padding
- Fixes https://github.com/owncloud/web/issues/9108
> Fixing max width of tippy box

- packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
- move left sidebar visually to back
- removes rounded corners
- follows the idea of use of shadows in material design: https://m3.material.io/styles/elevation/overview
> move left sidebar to back as its less important than the main content.

- changelog/unreleased/bugfix-tiles-view-accessibility
- packages/design-system/src/components/OcCheckbox/OcCheckbox.vue
- packages/design-system/src/components/OcTile/OcTile.vue
- packages/design-system/src/components/OcTile/__snapshots__/OcTile.spec.ts.snap
- packages/web-app-admin-settings/src/components/AppTemplate.vue
- packages/web-app-admin-settings/tests/unit/views/__snapshots__/Spaces.spec.ts.snap
- packages/web-app-files/src/HandleUpload.ts
- packages/web-app-files/src/helpers/resource/actions/upload.ts
- packages/web-app-files/tests/unit/HandleUpload.spec.ts
- packages/web-runtime/src/composables/upload/useUpload.ts
Merge `stable-7.1`@`2820aa8c92b69ceaff5379993b9819bc2387910a` to master.
> Merge stable 7.1 to master

- .drone.env
This PR bumps latest ocis commit id.
Part of https://github.com/owncloud/QA/issues/827
> [tests-only][full-ci] Bump latest commit id

- packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
Image preview visible in detail after selecting folder.
Fixed by setting preview to undefined (default value for preview) if recognized as folder
- Fixes https://github.com/owncloud/web/issues/9713
> Remove image preview when switching to folder

- packages/web-app-preview/src/App.vue
Preview content was left aligned, should be centered
> fix-center-preview

- .drone.env
Part of https://github.com/owncloud/QA/issues/832
> [full-ci] [tests-only] Bump ocis stable commit id to latest

- changelog/unreleased/enhancement-sse-get-notifications-instantly
- packages/web-runtime/src/components/Topbar/Notifications.vue
It didn't work because the data structure on the server changed.
- https://github.com/owncloud/web/issues/9742
> fix: sse notifications not working

- vite.cern.config.ts
Fix regression from https://github.com/owncloud/web/pull/9749.
> fix: cern custom vite config paths

- .drone.star
- test case 1:
- test case 2:
- ...
> fix docs artifacts build

- .drone.env
Part of https://github.com/owncloud/QA/issues/832
> [tests-only] [full-ci] bump latest stable commit id of ocis

- .drone.env
Part of https://github.com/owncloud/QA/issues/832
> [tests-only] [full-ci] bump latest commit ocis id master

- .drone.env
> [tests-only] bump ocis commit-id

- packages/web-app-files/src/components/FilesList/ResourceTiles.vue
- packages/web-app-files/src/composables/resourcesViewDefaults/useResourcesViewDefaults.ts
- packages/web-pkg/src/components/AppBar/index.ts
- packages/web-pkg/src/helpers/ui/index.ts
Follow-up for https://github.com/owncloud/web/pull/9749.
> fix: circular import issues with resourceTable helper

- packages/web-runtime/src/layouts/Application.vue
Follow-up for https://github.com/owncloud/web/pull/9814.
> fix: add enabled-check for nav-item extensions

- packages/web-pkg/src/composables/actions/files/useFileActionsPaste.ts
Check for null in currentFolder inside useFileActionsPaste preventing errors while copying file in public link
- Fixes https://github.com/owncloud/web/issues/9765
> check for current folder not being nullable in paste action

- packages/web-app-files/src/views/spaces/Projects.vue
Fixing sort direction in spaces. Removing condition turning 'asc/desc' to true/false
- Fixes https://github.com/owncloud/web/issues/9837
> Order in spaces fix

- changelog/unreleased/enhancement-search-tags-filter-style
- packages/web-app-files/src/components/Search/List.vue
- Fixes https://github.com/owncloud/web/issues/9834
- test case 1:
- test case 2:
- ...
> aligned tag styling in search

- .drone.env
Bump ocis commit id to the latest for the tests
Part of https://github.com/owncloud/QA/issues/834
> [full-ci][tests-only] bump ocis commit id

- .drone.env
bump ocis commit id for tests
part of https://github.com/owncloud/QA/issues/834
> [tests-only][full-ci] bump ocis commit-id

- packages/web-pkg/src/configuration/manager.ts
- packages/web-pkg/src/configuration/types.ts
- packages/web-runtime/src/services/auth/userManager.ts
- Fixes https://github.com/owncloud/web/issues/9245
> [cern] feat: add cern reva auth token handling

- .drone.env
bump ocis commit id for tests
part of https://github.com/owncloud/QA/issues/834
> [tests-only][full-ci] Bump ocis latest commit id

- .drone.env
bump ocis commit id for tests
part of https://github.com/owncloud/QA/issues/834
> [tests-only][full-ci] Bump ocis latest commit id on stable

- tests/e2e/cucumber/features/smoke/copyMove.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
Existing tests for copying and moving files using `dropdown-menu` implements following steps:
1. right clicks on the resource
2. clicks on `Copy` button on `app bar batch action`
3. pastes on the new location
This flow implementation does not seem proper as after right click on the resource we are not copying the file from the dropdown menu, instead, we are copying files from `app bar`.
In this PR, proper implementation for copying/moving files using `dropdown-menu` is done and added an extra step for copying/moving files using the button from `app bar`.
> [tests-only][full-ci]implement separate step for dropdown-menu and batch-action for copy and move

- packages/design-system/src/components/OcSearchBar/OcSearchBar.vue
- packages/web-pkg/src/components/SearchBarFilter.vue
Background color set to SearchBarFilter component
- Fixes https://github.com/owncloud/web/issues/9842
> Search text overlaid on the search location filter fix

- packages/web-app-files/package.json
- packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
- packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
- packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
- packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
- packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
- packages/web-app-files/src/store/actions.ts
- packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/DetailsAndEdit.spec.ts.snap
- packages/web-client/src/helpers/share/functions.ts
- packages/web-client/src/helpers/share/share.ts
- packages/web-client/src/types.ts
- pnpm-lock.yaml
Implemented by https://github.com/owncloud/web/commit/9ffff2de54266f231e43e1e7e96e8110ae0ea7a5.
- Fixes https://github.com/owncloud/web/issues/9378
> feat (cern): add share notifications

- .drone.env
bump ocis commit id for tests
part of https://github.com/owncloud/QA/issues/835
> [tests-only][full-ci] Bump ocis stable commit

- .drone.star
- tests/drone/check-oCIS-cache.sh
This PR maintains script file which checks builds in cache
- Fixes https://github.com/owncloud/web/issues/9930
- CI
> [full-ci][tests-only]Use minio find command to check ocis cache

- .drone.star
- Makefile
- Makefile.release
- package.json
- pnpm-lock.yaml
- Fixes https://github.com/owncloud/web/issues/9797
> chore: bump pnpm to version 8.10.5

- changelog/unreleased/change-remove-deprecations
- packages/web-runtime/src/container/bootstrap.ts
- packages/web-runtime/src/store/user.ts
- noticed in #7338 
- test case 1:
- test case 2:
- ...
> Remove deprecated code after prior notices

- package.json
- test case 1:
- test case 2:
- ...
> Bump node version when using volta

- package.json
- packages/design-system/package.json
- pnpm-lock.yaml
> chore: bump autoprefixer to v10.4.16

- packages/design-system/src/components/OcResource/OcResource.vue
- packages/design-system/src/components/OcResourceLink/OcResourceLink.vue
- packages/web-app-search/src/portals/SearchBar.vue
- packages/web-pkg/src/components/Search/ResourcePreview.vue
- test case 1:
- test case 2:
- ...
> Search: Add close-on-click, remove dozens of event handlers

- packages/design-system/src/components/OcSelect/OcSelect.vue
- packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap
- packages/web-app-admin-settings/tests/unit/components/Users/__snapshots__/GroupSelect.spec.ts.snap
- packages/web-app-admin-settings/tests/unit/components/Users/__snapshots__/LoginModal.spec.ts.snap
- packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
Make sure getOptionLabel is consistently used. The same function (which can be overriden via prop) is always used in templates and passed to the original vue-select.
- test case 1:
- test case 2:
- ...
> Fix getOptionLabel in oc-select

- changelog/unreleased/enhancement-new-file-event-handling
- packages/web-client/package.json
- packages/web-client/src/webdav/index.ts
- packages/web-client/src/webdav/listFilesById.ts
- packages/web-client/src/webdav/types.ts
- packages/web-runtime/package.json
- packages/web-runtime/src/container/bootstrap.ts
- pnpm-lock.yaml
Handle new files and insert them into the current file listing, if they are added to the currently viewed folder. 
- Kind of fixes: https://github.com/owncloud/web/issues/9782
This uses the FileReadyEvent emitted after post-processing. This is a nice start, but it's not fired for empty or copied files, probably not for restored from trash files, etc... 
- Depends on https://github.com/owncloud/ocis/pull/7770
- test case 1:
- test case 2:
- ...
https://github.com/owncloud/web/assets/448487/07efb99c-014f-4a18-af5f-6c0ab2dcc437
> feat: handle FileReadyEvent for new files

- packages/web-app-files/src/views/shares/SharedWithMe.vue
- packages/web-app-files/tests/unit/views/shares/SharedWithMe.spec.ts
- packages/web-pkg/src/components/ItemFilter.vue
- packages/web-pkg/tests/unit/components/ItemFilter.spec.ts
- packages/web-pkg/tests/unit/components/__snapshots__/ItemFilter.spec.ts.snap
Keep the original objects, so we can do identity checks against them and don't need to copy them for getters, so we can copy them and then copy them.
This was a workaround to keep item order stable on search, but we can achieve the same without copying by just filtering the original array by the results.
Side effect: this should be more efficient
- test case 1:
- test case 2:
- ...
> fix: do not shallow copy items in ItemFilter

- changelog/unreleased/enhancement-share-search-filter
- packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
- packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
- packages/web-app-admin-settings/src/components/Users/UsersList.vue
- packages/web-app-admin-settings/src/views/Users.vue
- packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
- packages/web-app-files/src/views/shares/SharedWithMe.vue
- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/src/views/trash/Overview.vue
- packages/web-app-files/tests/unit/views/shares/SharedWithMe.spec.ts
- packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
- packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
Adds a text search filter to the 'Shared with me'-page and aligns the other search inputs to the right.
- Fixes https://github.com/owncloud/web/issues/10014
> Shares search filter

- docs/theming/_index.md
- packages/web-pkg/src/components/AppBanner.vue
- packages/web-runtime/themes/owncloud/theme.json
See https://github.com/owncloud/web/issues/10015
- Fixes https://github.com/owncloud/web/issues/10015
> Disable AppBanner

- packages/web-app-admin-settings/src/views/Spaces.vue
- packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
- packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ResourceDetails.spec.ts.snap
- packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
- packages/web-pkg/src/components/SideBar/WebDavDetails.vue
- packages/web-pkg/src/components/SideBar/index.ts
- packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/__snapshots__/SpaceDetails.spec.ts.snap
Enables copy webdav url and copy webdav path, settings needs to be done in a different pr 
- Part of https://github.com/owncloud/web/issues/9714
- test case 1:
- test case 2:
- ...
> Add copy webdav url and copy webdav path

- changelog/unreleased/enhancement-add-explaining-contextual-helper-to-spaces-overview
- packages/web-app-files/src/views/spaces/Projects.vue
- Fixes https://github.com/owncloud/web/issues/8163
- test case 1:
- test case 2:
- ...
> Add contextual helper

- tests/e2e/cucumber/features/smoke/shortcut.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/index.ts
create shortcut to: 
- folder
- file 
- shared file
- public link 
- website
- project space -> will be implement in the next PR
and make sure the shortcut opens
> [test-only] create e2e test for shortcut feature

- packages/web-app-preview/src/components/MediaControls.vue
Before 
After
- test case 1:
- test case 2:
- ...
> Change zoom icons in preview app

- packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
- packages/web-client/src/ocs/capabilities.ts
- packages/web-pkg/src/composables/capability/useCapability.ts
Works towards https://github.com/owncloud/web/pull/10076
> refactor: create composable for password enforcement capability

- changelog/unreleased/bugfix-disable-expiration-date-alias-link
- packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/DetailsAndEdit.spec.ts.snap
Fix the seperator line if only one item is in the list
> Bugfix: Disable expiration date alias link followup

- packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
- packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
- packages/web-app-admin-settings/src/components/Users/UsersList.vue
- packages/web-client/src/graph.ts
Only mark relevant columns like displayName while search term is applied
Mark new entities while being added and search term is applied
- Part of https://github.com/owncloud/web/issues/10088
- test case 1:
- test case 2:
- ...
> Admin settings fix mark problems, remove memberOf from list users query

- packages/design-system/src/components/OcResource/OcResource.vue
- packages/design-system/src/components/OcResource/__snapshots__/OcResource.spec.ts.snap
- packages/web-pkg/src/components/AppTopBar.vue
- Fixes https://github.com/owncloud/web/issues/9965
> Truncate folder name in TopBar

- packages/extension-sdk/index.mjs
- test case 1:
- test case 2:
- ...
> Make it possible to override the app name in extension-sdk

- tests/e2e/cucumber/features/smoke/link.feature
- tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
- Part of https://github.com/owncloud/web/pull/10112
- test case 1:
- test case 2:
- ...
> add test to create quick link in project space

- packages/web-runtime/src/container/bootstrap.ts
> fix: sse postprocessing when no current folder given

- changelog/unreleased/enhancement-duplicate-space
- packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDuplicate.ts
- packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsDuplicate.spec.ts
- Fixes https://github.com/owncloud/web/issues/10123
- test case 1:
- test case 2:
- ...
> Add quota from existing space while duplicating

- tests/e2e/cucumber/features/smoke/fullTextSearch.feature
- tests/e2e/cucumber/features/smoke/search.feature
- tests/e2e/cucumber/steps/api.ts
- tests/e2e/cucumber/steps/ui/search.ts
- tests/e2e/support/api/davSpaces/spaces.ts
- tests/e2e/support/objects/app-files/search/actions.ts
- tests/e2e/support/objects/app-files/search/index.ts
- added test for origin `lastModifiedFilter` search filter
> e2e test. lastModified search filter

- docker-compose.yml
- test case 1:
- test case 2:
- ...
> Lower password policy for dev setup

- packages/design-system/src/components/OcModal/OcModal.vue
- packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap
- packages/web-app-admin-settings/tests/unit/components/Users/__snapshots__/LoginModal.spec.ts.snap
- Fixes https://github.com/owncloud/enterprise/issues/6269
> fix: truncate modal title if too long

- packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
- test case 1:
- test case 2:
- ...
> fix: make apps take all available space

- packages/web-runtime/src/components/Topbar/UserMenu.vue
- packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.ts.snap
Logout button was shown over the user quota, this is bad UX, the PR fixes that 
- test case 1:
- test case 2:
- ...
> Show logout button under user quota

- packages/web-runtime/src/services/auth/userManager.ts
- Fixes https://github.com/owncloud/web/issues/10184
- test case 1:
- test case 2:
- ...
> Translate propertyName metaDataUrl so OIDC lib can use it

- packages/web-app-files/src/index.ts
- packages/web-app-files/src/services/folder/loaderFavorites.ts
- packages/web-pkg/src/composables/actions/files/useFileActionsFavorite.ts
- packages/web-runtime/src/services/auth/abilities.ts
- packages/web-runtime/tests/unit/services/auth/abilities.spec.ts
- test case 1:
- test case 2:
- ...
> fix(favorites): use correct permissions and fix loader task

- changelog/unreleased/enhancement-create-link-modal
- packages/web-pkg/src/components/CreateLinkModal.vue
- test case 1:
- test case 2:
- ...
> Dont show password input error and errorMessage together on failure

- deployments/examples/ocis_web/docker-compose.yml
- packages/web-pkg/src/components/SideBar/WebDavDetails.vue
- packages/web-runtime/src/pages/account.vue
See:
- https://en.wikipedia.org/wiki/WebDAV
- https://en.wikipedia.org/wiki/URL
Proper uppercase characters in WebDAV + URL
- Improves [<issue_link>](https://github.com/owncloud/web/issues/9714)
WebDAV + URL abbreviatiojns should follow the usual conventions
- https://en.wikipedia.org/wiki/WebDAV
- https://en.wikipedia.org/wiki/URL
- test case 1:
- test case 2:
- ...
> Typo: WebDAV + URL with uppercase characters

- tests/e2e/cucumber/features/smoke/urlJourneys.feature
The logout step was missed in the PR https://github.com/owncloud/web/pull/10136 so this PR adds it.
> [tests-only] test: add missed logout step

- tests/e2e/cucumber/features/smoke/urlJourneys.feature
The logout step was missed in the PR https://github.com/owncloud/web/pull/10136 so this PR adds it.
> [tests-only] test: add missed logout step 

- tests/e2e/cucumber/features/smoke/urlJourneys.feature
- tests/e2e/cucumber/steps/ui/navigateByUrl.ts
- tests/e2e/support/api/davSpaces/spaces.ts
- tests/e2e/support/objects/url-navigation/actions.ts
- tests/e2e/support/objects/url-navigation/index.ts
This PR adds tests for opening a file/folder directly on the web. In case the web has text editor installed the file will directly open in the text editor and that's what's covered in the test here
- Part of: https://github.com/owncloud/web/issues/9897
- locally
- ci
> [tests-only] e2e tests for url stability open file directly in the web

- tests/e2e/cucumber/features/smoke/urlJourneys.feature
- tests/e2e/cucumber/steps/ui/navigateByUrl.ts
- tests/e2e/support/objects/url-navigation/actions.ts
- tests/e2e/support/objects/url-navigation/index.ts
- Part of: https://github.com/owncloud/web/issues/9897
- locally
- CI
> [tests-only] test: add e2e test for directly opening project space through url

- tests/e2e/cucumber/features/smoke/urlJourneys.feature
- tests/e2e/cucumber/steps/ui/navigateByUrl.ts
- tests/e2e/support/objects/url-navigation/actions.ts
- tests/e2e/support/objects/url-navigation/index.ts
Forward port: https://github.com/owncloud/web/pull/10202
- Part of: https://github.com/owncloud/web/issues/9897
> [tests-only][full-ci] test: add e2e test for directly opening project space through url

- packages/design-system/l10n/.tx/config
- packages/web-app-admin-settings/l10n/.tx/config
- packages/web-app-draw-io/l10n/.tx/config
- packages/web-app-external/l10n/.tx/config
- packages/web-app-files/l10n/.tx/config
- packages/web-app-importer/l10n/.tx/config
- packages/web-app-ocm/l10n/.tx/config
- packages/web-app-pdf-viewer/l10n/.tx/config
- packages/web-app-preview/l10n/.tx/config
- packages/web-app-search/l10n/.tx/config
- packages/web-app-text-editor/l10n/.tx/config
- packages/web-app-webfinger/l10n/.tx/config
- packages/web-client/l10n/.tx/config
- packages/web-pkg/l10n/.tx/config
- packages/web-runtime/l10n/.tx/config
- packages/web-runtime/l10n/Makefile
- packages/web-runtime/src/defaults/languages.ts
Adding simplified Chinese (85% translation coverage, wow!), but mapping it to the main Chinese language code `zh` since we can only work with language codes.
- Works towards https://github.com/owncloud/ocis/issues/7999
Make community happy.
> feat: add simplified chinese and map to chinese

- packages/design-system/l10n/.tx/config
- packages/web-app-admin-settings/l10n/.tx/config
- packages/web-app-draw-io/l10n/.tx/config
- packages/web-app-external/l10n/.tx/config
- packages/web-app-files/l10n/.tx/config
- packages/web-app-importer/l10n/.tx/config
- packages/web-app-ocm/l10n/.tx/config
- packages/web-app-pdf-viewer/l10n/.tx/config
- packages/web-app-preview/l10n/.tx/config
- packages/web-app-search/l10n/.tx/config
- packages/web-app-text-editor/l10n/.tx/config
- packages/web-app-webfinger/l10n/.tx/config
- packages/web-client/l10n/.tx/config
- packages/web-pkg/l10n/.tx/config
- packages/web-runtime/l10n/.tx/config
- packages/web-runtime/l10n/Makefile
- test case 1:
- test case 2:
- ...
> Fix makefile so zh lang l10n works 

- changelog/unreleased/enhancement-harmonize-appswitcher-icon-colors
- packages/web-app-ocm/src/index.ts
- packages/web-app-text-editor/src/index.ts
See https://github.com/owncloud/web/issues/10121
- Mitigates https://github.com/owncloud/web/issues/10121
> Harmonize AppSwitcher Icon colors

- changelog/unreleased/bugfix-created-file-missing-file-extension
- packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
- packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewFile.ts
includes those 2 fixes:
* https://github.com/owncloud/web/pull/10163
* https://github.com/owncloud/web/pull/10169
> fix: pick recent fixes from stable-7.1

- tests/e2e/cucumber/features/smoke/urlJourneys.feature
Adds case for when a file is opened directly through url and the appropriate editor for the file is not in the web `odt` file format is used
- Part of https://github.com/owncloud/web/issues/9897
- locally
- CI
> [tests-only] test: add e2e url stability test for the file without editor

- changelog/unreleased/change-creating-modals
- packages/web-app-admin-settings/src/components/Groups/CreateGroupModal.vue
- packages/web-app-admin-settings/src/components/Users/CreateUserModal.vue
- packages/web-app-files/src/components/Modals/SetLinkPasswordModal.vue
- packages/web-pkg/src/components/CreateLinkModal.vue
- packages/web-pkg/tests/unit/composables/piniaStores/modals.spec.ts
Follow-up after https://github.com/owncloud/web/pull/10212.
> modal refactor follow-up

- changelog/unreleased/bugfix-tiles-view-whitespace
- packages/web-app-files/src/components/FilesList/ResourceTiles.vue
- packages/web-app-files/src/views/spaces/GenericSpace.vue
- packages/web-app-files/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
Fixes an issue where the tiles on the spaces overview would not align side by side.
> fix: tiles view listing on spaces overview

- package.json
- packages/design-system/package.json
- packages/web-runtime/package.json
- pnpm-lock.yaml
Aligns some of our dependency versions across the project to be the same. No need to have multiple versions for one and the same dependency.
> chore: align dependency versions

- packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
Clearing expiry date on "share" submit to reset, which fixes issue of expiration date picker not having displayed "clear" button properly after submit
- Fixes https://github.com/owncloud/web/issues/10273
> Clear expiration date after submit

- .drone.env
Part of https://github.com/owncloud/QA/issues/839
> [full-ci] [tests-only] Bump ocis-stable-5.0 commit id

- changelog/unreleased/enhancement-file-sidebar
- packages/web-pkg/src/components/SideBar/SideBar.vue
- test case 1:
- test case 2:
- ...
> Bugfix: Navigate into trashbin while sidebar is open is not possible

- packages/web-app-external/src/index.ts
- packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
- packages/web-pkg/src/apps/types.ts
- packages/web-pkg/src/composables/actions/files/useFileActions.ts
- packages/web-pkg/src/composables/piniaStores/apps.ts
Fixes regressions from https://github.com/owncloud/web/pull/10346.
- refs https://github.com/owncloud/web/issues/10351
> fix: opening files via external apps

- changelog/unreleased/change-registering-app-file-editors
- packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
- packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewFile.ts
- Fixes https://github.com/owncloud/web/issues/10351
- test case 1:
- test case 2:
- ...
> [full-ci] fix: show only a single new file action per extension/mime-type

- .drone.star
- docker-compose.yml
Backport: https://github.com/owncloud/web/pull/10360
> [tests-only][full-ci]update compose make image versions consistent in CI and compose

- .drone.env
Part of https://github.com/owncloud/QA/issues/840
> [full-ci] [tests-only] Bump ocis stable-4.0 commit id

- changelog/unreleased/bugfix-user-data-not-updated-while-altering-own-user
- packages/web-app-admin-settings/src/views/Users.vue
- Fixes https://github.com/owncloud/web/issues/10373
- test case 1:
- test case 2:
- ...
> Update userStore while updating currrent user via admin settings app

- .drone.env
- .drone.star
Part of https://github.com/owncloud/QA/issues/840
> [full-ci] [tests-only] Bump ocis stable-5.0 commit id

- .drone.env
Part of https://github.com/owncloud/QA/issues/840
> [full-ci] [tests-only] Bump ocis stable 5.0 commit

- deployments/continuous-deployment-config/ocis_web/daily.yml
- deployments/continuous-deployment-config/ocis_web/latest.yml
> chore: remove lookacat ssh key from cd instances

- docker-compose.yml
- test case 1:
- test case 2:
- ...
> Fix natsjs name

- .drone.star
- docker-compose.yml
related https://github.com/owncloud/ocis/pull/8207
I expect this error in CI:  https://github.com/owncloud/ocis/issues/8272 please DON'T merge before fixing
> [full-ci][test-only] update wopi

- packages/web-app-files/src/views/FilesDrop.vue
- Fixes https://github.com/owncloud/web/issues/10411
- test case 1:
- test case 2:
- ...
> Add note about folder structure to secret file drop

- changelog/unreleased/enhancement-top-loading-bar-increase-visibility
- packages/web-pkg/src/components/LoadingIndicator.vue
- Fixes https://github.com/owncloud/web/issues/10383
- test case 1:
- test case 2:
- ...
> Make top progress bar more visible

- .drone.env
Bump latest `ocis-master` commit to web
https://github.com/owncloud/QA/issues/841
> [tests-only][full-ci]bump ocis latest master commit

- packages/design-system/src/components/OcTable/OcTable.spec.ts
- packages/web-app-files/src/HandleUpload.ts
- packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
- packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
- packages/web-app-files/src/composables/parentShare/useIncomingParentShare.ts
- packages/web-app-files/src/index.ts
- packages/web-app-files/src/views/FilesDrop.vue
- packages/web-app-files/src/views/spaces/GenericTrash.vue
- packages/web-app-files/tests/unit/HandleUpload.spec.ts
- packages/web-app-files/tests/unit/index.spec.ts
- packages/web-client/src/webdav/clearTrashBin.ts
- packages/web-client/src/webdav/listFiles.ts
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-pkg/src/composables/actions/files/useFileActionsDelete.ts
- packages/web-pkg/src/composables/actions/files/useFileActionsRestore.ts
- packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
- packages/web-pkg/src/composables/driveResolver/useDriveResolver.ts
- packages/web-pkg/src/composables/piniaStores/capabilities.ts
- packages/web-pkg/src/composables/resources/useGetResourceContext.ts
- packages/web-pkg/src/composables/spaces/useGetMatchingSpace.ts
- packages/web-pkg/tests/unit/composables/actions/files/useFileActionsRestore.spec.ts
- packages/web-pkg/tests/unit/composables/driveResolver/useDriveResolver.spec.ts
- tests/e2e/support/objects/account/actions.ts
Since https://github.com/owncloud/ocis/pull/8303 has been merged, spaces will be always enabled, so there is no need for the checks anymore.
- test case 1:
- test case 2:
- ...
> Remove spaces enabled checks

- packages/web-runtime/src/pages/account.vue
- packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
Follow-up to #10435 to improve user experience ("sort by most frequently/likely accessed" 🤓 )
> Move extracted GDPR section below preferences on account page

- .drone.env
Part of https://github.com/owncloud/QA/issues/841
> [tests-only][full-ci] Bump ocis commit

- .drone.env
part of https://github.com/owncloud/QA/issues/841
> [tests-only][full-ci] Bump ocis commit id stable 8

- packages/web-app-text-editor/src/App.vue
- Fixes https://github.com/owncloud/web/issues/10459
- test case 1:
- test case 2:
- ...
> Fix scrolling readonly markdown not possible

- changelog/unreleased/enhancement-text-editor-intergrate-toast-ui-editor
- packages/web-app-text-editor/src/App.vue
Make url links scrollable since b64 images might geht pretty long 
- test case 1:
- test case 2:
- ...
> Make url links scrollable

- packages/web-app-epub-reader/src/App.vue
- test case 1:
- test case 2:
- ...
> Epub reader design polishing

- changelog/unreleased/enhancement-highlight-search-term-in-sharing-autosuggest-list
- packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- Fixes https://github.com/owncloud/web/issues/10453
- test case 1:
- test case 2:
- ...
> Hilight search term in share invite list

- changelog/unreleased/bugfix-load-thumbnail-when-postprocessing-is-finished
- docker-compose.yml
- packages/web-pkg/src/services/preview/previewService.ts
- packages/web-runtime/src/container/bootstrap.ts
- packages/web-runtime/src/index.ts
- Fixes https://github.com/owncloud/web/issues/10486
- test case 1:
- test case 2:
- ...
> Load preview when postprocessing is done

- tests/e2e/cucumber/features/smoke/app-provider/officeSuites.feature
- tests/e2e/cucumber/features/smoke/languageChange.feature
- tests/e2e/cucumber/features/smoke/rename.feature
- tests/e2e/cucumber/features/smoke/shares/internalLink.feature
- tests/e2e/cucumber/features/smoke/shares/link.feature
- tests/e2e/cucumber/features/smoke/shortcut.feature
- tests/e2e/cucumber/features/smoke/spaces/internalLink.feature
- tests/e2e/cucumber/features/smoke/spaces/participantManagement.feature
- tests/e2e/cucumber/features/smoke/spaces/project.feature
- tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
- tests/e2e/cucumber/steps/ui/accountMenu.ts
- tests/e2e/cucumber/steps/ui/links.ts
- tests/e2e/support/objects/account/actions.ts
- tests/e2e/support/objects/account/index.ts
- tests/e2e/support/objects/app-files/link/actions.ts
Backported in this PR
-  https://github.com/owncloud/web/pull/10207 
-  https://github.com/owncloud/web/pull/10335
Part of https://github.com/owncloud/web/issues/10457
> [test-only][full-ci]backport PRs #10207 and #10335

- tests/e2e/cucumber/features/smoke/app-provider/officeSuites.feature
- tests/e2e/cucumber/features/smoke/app-provider/urlJourneys.feature
- tests/e2e/cucumber/steps/ui/navigateByUrl.ts
- tests/e2e/support/api/external/index.ts
- tests/e2e/support/api/external/openWithWeb.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/url-navigation/actions.ts
Backported PRs #10420 and #10442
Part of https://github.com/owncloud/web/issues/10457
> [tests-only][full-ci] Backport PRs #10420 and #10442

- tests/e2e/support/objects/account/actions.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
Backported test codes from #10437 and #10426
> [tests-only][full-ci][backport ] backport test codes from #10437 and #10426

- tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
- tests/acceptance/features/webUISharingInternalUsersShareWithPage/shareWithUsers.feature
- tests/e2e/cucumber/features/smoke/shares/share.feature
- tests/e2e/cucumber/steps/ui/shares.ts
- tests/e2e/support/objects/app-files/share/actions.ts
- tests/e2e/support/objects/app-files/share/collaborator.ts
- tests/e2e/support/objects/app-files/share/index.ts
> [tests-only][full-ci][backport] remove share access details tests and add e2e coverage (#10427)

- tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
- tests/acceptance/features/webUICreateFilesFolders/createFile.feature
- tests/acceptance/features/webUIFiles/download.feature
- tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature
- tests/acceptance/features/webUITrashbinDelete/trashbinDelete.feature
- tests/e2e/cucumber/features/smoke/shares/link.feature
- tests/e2e/cucumber/features/smoke/trashbinDelete.feature
- tests/e2e/cucumber/features/smoke/upload.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/cucumber/steps/ui/spaces.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/index.ts
Backported PRs #10447, #10449 and #10480
> [tests-only][full-ci] backport PRs #10447, #10449 and #10480

- .drone.star
- docker-compose.yml
- docs/backend-ocis.md
changed path in the docker-compose because `WEB_ASSET_PATH` is deprecated
related https://github.com/owncloud/web/pull/10545 and https://github.com/owncloud/web/pull/10547
> [full-ci]change asset path (#10545)

- .drone.star
- docker-compose.yml
- docs/backend-ocis.md
Reverts owncloud/web#10545
Needs to be targeted at `master`, not `stable-8.0`.
> Revert "[full-ci]change asset path"

- .drone.env
need for https://github.com/owncloud/web/pull/10548
> [full-ci] bump ocis

- packages/web-app-files/src/components/EmbedActions/EmbedActions.vue
Title says it all. Super important string change that came up in https://github.com/owncloud/file-picker/issues/246#issuecomment-1985556611
- Relates to https://github.com/owncloud/file-picker/issues/246#issuecomment-1985556611
> feat: super important string change

- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
This PR forward port: https://github.com/owncloud/web/pull/10553
> [tests-only][full-ci] forward port add await for locator visibility

- changelog/unreleased/bugfix-web-dav-url-is-missing-dav-in-path
- packages/web-pkg/src/components/SideBar/WebDavDetails.vue
- test case 1:
- test case 2:
- ...
> Add dav to path to right sidebar webdav url 

- changelog/unreleased/bugfix-add-link-does-not-copy-to-clipboard
- packages/web-pkg/src/composables/actions/files/useFileActionsCreateLink.ts
- Fixes https://github.com/owncloud/web/issues/10563
- test case 1:
- test case 2:
- ...
> Copy link to clipboard via 'Add link' action in sharing panel

- docs/testing/testing.md
- tests/e2e/.eslintrc.json
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/cucumber/steps/ui/spaces.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/index.ts
> [tests-only][port] override lint rules for tests/e2e (#10562)

- changelog/unreleased/bugfix-add-link-does-not-copy-to-clipboard
- packages/web-pkg/src/composables/actions/files/useFileActionsCreateLink.ts
- test case 1:
- test case 2:
- ...
> Log error message

- .drone.star
- tests/drone/ocis_keycloak/ocis-ci-realm.dist.json
- tests/e2e/cucumber/steps/ui/adminSettings.ts
- tests/e2e/support/objects/app-admin-settings/users/index.ts
This PR runs tests on keycloak in CI. For now, tests under journey are running on keycloak. 
`Journey` folder contains multiple user login and logout, sharing. 
On stable-8.0, all feature files mentioned below passes but on master spaces.feature has some problem so only journey is running for now
- tests/e2e/cucumber/features/smoke/admin-settings/users.feature:20 
- tests/e2e/cucumber/features/smoke/admin-settings/spaces.feature
- tests/e2e/cucumber/features/journeys
master pr link:https://github.com/owncloud/web/pull/10481
- Fixes <https://github.com/owncloud/web/issues/10458>
- CI
> [full-ci][tests-only] Run e2e tests on keycloak

- tests/e2e/cucumber/features/smoke/shares/link.feature
test for https://github.com/owncloud/ocis/issues/8621
> download resource using single share view

- tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
- tests/acceptance/features/webUILogin/openidLogin.feature
In this PR,
- removed the webUI test scenario related to user redirection to login page when logged in user is deleted
> [tests-only][full-ci] remove webUI test related to user redirection to login page after the logged in user is deleted

- tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
- tests/acceptance/features/webUILogin/openidLogin.feature
Forward port PR: https://github.com/owncloud/web/pull/10575
> [tests-only][full-ci] forward port remove webUI test related to user redirection to login page after the logged in user is deleted

- tests/e2e/cucumber/features/smoke/shares/link.feature
> download resource using single share view (#10587)

- tests/e2e/cucumber/features/smoke/shares/link.feature
- tests/e2e/cucumber/features/smoke/shortcut.feature
- tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
- tests/e2e/cucumber/features/smoke/upload.feature
- tests/e2e/cucumber/steps/api.ts
- tests/e2e/support/api/davSpaces/spaces.ts
- tests/e2e/support/utils/dragDrop.ts
Port PRs #10594 and #10595
Revert step changes from #10571
> [tests-only] fix file upload via api and drag-n-drop

- docs/extension-system/_index.md
- docs/extension-system/viewer-editor-apps.md
- Fixes https://github.com/owncloud/web/issues/10533
> docs: add documentation for viewer and editor apps

- tests/acceptance/features/webUIPreview/mediaPreview.feature
- tests/e2e/cucumber/features/shares/link.feature
- tests/e2e/cucumber/features/smoke/download.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
part of #10259
test for #10484
added dowloading using batch action
> [test-only]download image file from editor

- changelog/unreleased/enhancement-tile-sizes
- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
- Fixes https://github.com/owncloud/web/issues/10638
> fix: tile size slider on spaces overview

- .drone.env
- tests/e2e/cucumber/features/spaces/publicLink.feature
added test for project space link where public is doing grud operations like: upload, download, rename, change file content, delete file 
related https://github.com/owncloud/ocis/issues/8699
> [test-only] more e2e test for space link

- changelog/unreleased/bugfix-hidden-sidebar-on-small-screens
- packages/web-pkg/src/components/SideBar/SideBar.vue
- Fixes https://github.com/owncloud/web/issues/10598
> fix: hidden right sidebar on small screens

- .drone.star
- changelog/unreleased/bugfix-hidden-sidebar-on-small-screens
- changelog/unreleased/bugfix-scope-loss-search-results
- changelog/unreleased/bugfix-theme-loading-without-matching-theme
- packages/web-app-search/src/portals/SearchBar.vue
- packages/web-pkg/src/components/SideBar/SideBar.vue
- packages/web-pkg/tests/unit/composables/piniaStores/theme.spec.ts
- tests/drone/get-latest-ocis-commit-id.sh
> Merge stable-8.0 to master

- .drone.star
Backport of https://github.com/owncloud/web/pull/10663
> [tests-only][full-ci] send notifications to talk.owncloud

- packages/design-system/src/components/OcModal/OcModal.spec.ts
- packages/design-system/src/components/OcModal/OcModal.vue
- Fixes https://github.com/owncloud/web/issues/10674
> fix: translations for modal actions

- .drone.star
In this PR, path is added to trigger pipeline `chat-notifications` for branch `stable`
- closes https://github.com/owncloud/web/issues/10692
- CI
- ...
> [full-ci] configure drone file to trigger chat-notification

- package.json
- packages/web-pkg/package.json
- pnpm-lock.yaml
> chore: bump vite and vitest (security)

- .drone.env
In this PR, latest commit id of ocis master branch is bump
part of https://github.com/owncloud/QA/issues/847
> [tests-only][full-ci] Bump latest commit

- docs/extension-system/_index.md
Fixes the broken reference to the service docs.
- fixes https://github.com/owncloud/ocis/issues/8774
> docs: fix web service reference

- docker-compose.yml
using `owncloudci/wait-for:latest`image insted of `dadarek/wait-for-dependencies`
> chang tika waiting image

- docker-compose.yml
> port #10747

- packages/web-app-files/src/components/SideBar/Shares/Links/CreateQuickLink.vue
- packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditDropdown.spec.ts
- packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/AutocompleteItem.spec.ts
- packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.spec.ts
- packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/RoleDropdown.spec.ts
- packages/web-app-files/tests/unit/components/SideBar/Shares/Links/CreateQuickLink.spec.ts
- packages/web-app-files/tests/unit/components/SideBar/Shares/Links/DetailsAndEdit.spec.ts
- packages/web-pkg/src/components/SideBar/FileSideBar.vue
- packages/web-pkg/tests/unit/components/LinkRoleDropdown.spec.ts
- packages/web-pkg/tests/unit/components/sidebar/FileSideBar.spec.ts
Adds component unit tests to improve coverage on the new sharing NG implementation.
> test: add component unit tests for sharing NG implementation

- packages/web-app-files/src/HandleUpload.ts
- packages/web-app-files/src/helpers/resource/actions/upload.ts
- packages/web-app-files/tests/unit/HandleUpload.spec.ts
- packages/web-app-files/tests/unit/helpers/resource/actions/upload.spec.ts
- packages/web-pkg/src/components/Modals/ResourceConflictModal.vue
- packages/web-pkg/src/helpers/resource/conflictHandling/conflictDialog.ts
- packages/web-pkg/tests/unit/components/Modals/ResourceConflictModal.spec.ts
- Fixes https://github.com/owncloud/web/issues/10640
- test case 1:
- test case 2:
- ...
> Rename "Replace" conflict option to "Merge" for folder uploads

- packages/web-client/tests/unit/helpers/share/functions.spec.ts
> test: add unit tests for share helper functions

- packages/web-pkg/src/components/CreateLinkModal.vue
- Fixes https://github.com/owncloud/web/issues/10767
- test case 1:
- test case 2:
- ...
> Adjust wording share link(s) in embed mode

- changelog/unreleased/enhancement-support-sse-event-for-file-updates
- packages/web-runtime/src/container/sse.ts
- Fixes https://github.com/owncloud/web/issues/10779
- test case 1:
- test case 2:
- ...
> SSE support for file size and mdate

- .vscode/extensions.json
- package.json
- packages/design-system/package.json
- packages/eslint-config/package.json
- packages/tsconfig/tsconfig.json
- packages/web-client/src/webdav/client/parsers.ts
- packages/web-pkg/package.json
- packages/web-pkg/src/composables/portalTarget/usePortalTarget.ts
- packages/web-pkg/src/services/uppy/uppyService.ts
- packages/web-test-helpers/src/helpers.ts
- patches/portal-vue@3.0.0.patch
- patches/vue3-gettext@2.4.0.patch
- patches/webdav@5.3.1.patch
- pnpm-lock.yaml
- test case 1:
- test case 2:
- ...
> chore: bump typescript and use more modern settings

- .drone.env
This PR bump latest ocis(master) commit to web master.
> [tests-only][full-ci]bump ocis master commit to web master

- packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
Fix `web-client` import, see https://github.com/owncloud/web/pull/10792.
> fix: web-client import

- packages/extension-sdk/index.mjs
- packages/web-runtime/src/container/application/index.ts
Inject `web-client` exports for extensions so they can use the package.
- refs https://github.com/owncloud/web/issues/10773
> feat: inject web-client exports for extensions

- packages/web-app-admin-settings/src/composables/keyboardActions/useKeyboardTableNavigation.ts
- packages/web-app-files/src/composables/keyboardActions/useKeyboardTableActions.ts
- packages/web-app-files/src/composables/keyboardActions/useKeyboardTableNavigation.ts
- packages/web-app-files/src/composables/keyboardActions/useKeyboardTableSpaceActions.ts
- packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
- packages/web-pkg/src/composables/keyboardActions/useKeyboardActions.ts
- packages/web-pkg/tests/unit/composables/keyboardActions/useKeyboardActions.spec.ts
> Limit useKeyboardAction listener to one modifier key

- .drone.env
Bump ocis latest master commit to web master
> [tests-only][full-ci]Bump ocis latest master commit to web master

- .drone.env
Bump ocis commit web april 19 stable 8.0
> [tests-only][full-ci]Bump ocis commit web april 19 stable 8.0

- .drone.star
- packages/web-pkg/README.md
- packages/web-pkg/package.json
- packages/web-pkg/tsconfig.json
- packages/web-pkg/vite.config.ts
- pnpm-lock.yaml
Implements a proper build process for the web-pkg package so we can publish it in the future.
- refs https://github.com/owncloud/web/issues/8380
> feat: build process and publishing for web-pkg

- packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.ts
- packages/web-client/src/helpers/resource/functions.ts
- packages/web-client/src/ocs/capabilities.ts
- packages/web-pkg/src/composables/actions/files/useFileActionsNavigate.ts
- packages/web-pkg/src/composables/filesList/useResourceRouteResolver.ts
- packages/web-pkg/src/composables/piniaStores/capabilities.ts
- tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js
- tests/acceptance/stepDefinitions/sharingContext.js
- tests/e2e/cucumber/steps/ui/shares.ts
- tests/e2e/support/objects/app-files/share/actions.ts
Removes all leftovers from resharing from the codebase.
- Fixes https://github.com/owncloud/web/issues/10771
> refactor: remove resharing

- docs/development/repo-structure.md
- docs/extension-system/_index.md
- packages/web-client/README.md
- refs https://github.com/owncloud/web/issues/10773
> docs: add proper readme content for web-client package

- tests/e2e/cucumber/features/smoke/upload.feature
Fordward port of PR: https://github.com/owncloud/web/pull/10812
> [tests-only][full-ci] forward port add test coverage for filename with hash

- .drone.env
- tests/acceptance/features/webUISharingPublicBasic/publicLinkEdit.feature
- tests/acceptance/features/webUISharingPublicManagement/sharingPublicSession.feature
- tests/e2e/cucumber/features/shares/link.feature
Forward port of PR https://github.com/owncloud/web/pull/10826
> [full-ci] [tests-only] Forward port `#10826`

- packages/web-runtime/src/container/sse/files.ts
- packages/web-runtime/tests/unit/container/sse/files.spec.ts
- test case 1:
- test case 2:
- ...
> Add sse unit tests for files

- package.json
- packages/web-app-admin-settings/package.json
- packages/web-app-draw-io/package.json
- packages/web-app-external/package.json
- packages/web-app-files/package.json
- packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
- packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/Links/DetailsAndEdit.spec.ts
- packages/web-app-ocm/package.json
- packages/web-app-search/package.json
- packages/web-app-search/src/portals/SearchBar.vue
- packages/web-client/package.json
- packages/web-pkg/package.json
- packages/web-pkg/src/components/CreateLinkModal.vue
- packages/web-pkg/src/helpers/share/link.ts
- packages/web-runtime/package.json
- packages/web-test-helpers/src/defaultPlugins.ts
- pnpm-lock.yaml
Adds type packages for JavaScript libraries to be fully compatible with TypeScript. Without these type packages, TypeScript complains in strict mode, which is something we want to enable in the future.
> chore: add type packages for js libraries

- packages/web-runtime/src/container/sse/types.ts
- packages/web-runtime/tests/unit/container/sse/helpers.spec.ts
- test case 1:
- test case 2:
- ...
> Add sse unit tests for helpers

- tests/e2e/cucumber/features/app-provider/lock.feature
- tests/e2e/cucumber/features/journeys/kindergarten.feature
- tests/e2e/cucumber/features/search/fullTextSearch.feature
- tests/e2e/cucumber/features/search/searchProjectSpace.feature
- tests/e2e/cucumber/features/shares/internalLink.feature
- tests/e2e/cucumber/features/shares/share.feature
- tests/e2e/cucumber/features/smoke/createSpaceFromSelection.feature
- tests/e2e/cucumber/features/smoke/groupActions.feature
- tests/e2e/cucumber/features/smoke/notifications.feature
- tests/e2e/cucumber/features/smoke/rename.feature
- tests/e2e/cucumber/features/spaces/downloadSpace.feature
- tests/e2e/cucumber/features/spaces/internalLink.feature
- tests/e2e/cucumber/features/spaces/memberExpiry.feature
- tests/e2e/cucumber/features/spaces/pagination.feature
- tests/e2e/cucumber/features/spaces/participantManagement.feature
- tests/e2e/cucumber/features/spaces/project.feature
- tests/e2e/cucumber/features/spaces/publicLink.feature
- tests/e2e/cucumber/steps/ui/spaces.ts
`And "Alice" navigates to the projects space page`
`And "Alice" navigates to the project space "team.1"`
to one `And "Alice" navigates to the project space "team.1"`
> [test-only] combine steps

- packages/web-runtime/tests/unit/container/sse/files.spec.ts
- packages/web-runtime/tests/unit/container/sse/helpers.spec.ts
- test case 1:
- test case 2:
- ...
> add types to getMocks func

- packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
- Fixes https://github.com/owncloud/web/issues/10783
> fix: searching share recipients by email

- tests/acceptance/features/webUITextEditor/textFile.feature
- tests/e2e/cucumber/features/shares/share.feature
Backport of PR: https://github.com/owncloud/web/pull/10838
> [tests-only][full-ci] backport add test for updating content of file

- packages/web-runtime/src/container/sse/shares.ts
- packages/web-runtime/tests/unit/container/sse/shares.spec.ts
- test case 1:
- test case 2:
- ...
> sse unit tests for shares 

- .drone.env
- tests/drone/csp.yaml
Bump latest ocis commit id.
Part of: https://github.com/owncloud/QA/issues/849
> [tests-only][full-ci]bump latest ocis commit id

- packages/web-pkg/src/composables/upload/useUpload.ts
- packages/web-pkg/src/services/uppy/uppyService.ts
Fixes our uppy plugin type mess to be more compliant with the uppy plugin types.
> fix: uppy plugin types

- package.json
- tests/e2e/cucumber/features/search/fullTextSearch.feature
- tests/e2e/cucumber/features/shares/internalLink.feature
- tests/e2e/cucumber/features/spaces/internalLink.feature
- tests/e2e/cucumber/features/spaces/participantManagement.feature
- tests/e2e/cucumber/features/spaces/publicLink.feature
- tests/e2e/cucumber/features/spaces/sse.feature
- tests/e2e/cucumber/steps/ui/search.ts
- tests/e2e/cucumber/steps/ui/shares.ts
- tests/e2e/cucumber/steps/ui/spaces.ts
- tests/e2e/support/objects/app-files/share/actions.ts
- tests/e2e/support/objects/app-files/share/index.ts
- tests/e2e/support/objects/app-files/spaces/actions.ts
- tests/e2e/support/objects/app-files/spaces/index.ts
- tests/e2e/support/objects/app-files/spaces/utils.ts
> [test-only] e2e tests for space sse events

- packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
- Fixes https://github.com/owncloud/web/issues/10822
- test case 1:
- test case 2:
- ...
> Show context helper if user has no role

- packages/design-system/src/components/OcTextInput/OcTextInput.vue
- packages/web-pkg/src/components/CreateShortcutModal.vue
- Fixes https://github.com/owncloud/web/issues/10852
- test case 1:
- test case 2:
- ...
> Make create shortcut modal ux more easy

- .drone.env
Part of https://github.com/owncloud/QA/issues/851
> [full-ci] [tests-only[ Bump ocis master commit id to latest

- docker-compose.yml
related https://github.com/owncloud/enterprise/issues/6651#issuecomment-2107052192
@butonic I changed `OCIS_CORS_ALLOW_ORIGINS` and now TUS upload works again
CC @dschmidt @JammingBen
> fix TUS uploading #6651

- .drone.env
Part of https://github.com/owncloud/QA/issues/851
> [full-ci] [tests-only] Bump ocis commit id to latest stable

- packages/web-app-files/src/views/spaces/GenericSpace.vue
- Fixes https://github.com/owncloud/web/issues/10766
- test case 1:
- test case 2:
- ...
> Fix margin on new folder button in embed mode

- packages/web-runtime/src/components/EditPasswordModal.vue
- Fixes https://github.com/owncloud/web/issues/10235
- test case 1:
- test case 2:
- ...
> Show error when current password and new password are equal

- tests/e2e/support/objects/app-files/spaces/actions.ts
Forward port of PR: https://github.com/owncloud/web/pull/10910
> [tests-only][full-ci] forward port add wait for a element to be visible after navigating to a project space

- tests/e2e/cucumber/features/app-provider/officeSuites.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/index.ts
This test ensures that the permissions and access controls set for anonymous users are correctly enforced in both Collabora and OnlyOffice environments. The tests validate that anonymous users cannot edit files with "Can view" permission access.
- Part of #10750
- Locally
> [tests-only][full-ci] add e2e test to restrict the modification of document by anonymous user

- pnpm-lock.yaml
I ran `pnpm i` after https://github.com/owncloud/web/pull/10921 has been merged.
> chore: remove acceptance test dependencies

- changelog/unreleased/bugfix-disable-search-in-public-link-context
- packages/web-app-search/src/portals/SearchBar.vue
- Fixes https://github.com/owncloud/web/issues/10915
- test case 1:
- test case 2:
- ...
> Disable search in public link context

- changelog/unreleased/enhancement-add-loading-spinner-to-admin-settings-spaces-and-groups
- packages/web-app-admin-settings/src/views/Groups.vue
- packages/web-app-admin-settings/src/views/Spaces.vue
- Fixes https://github.com/owncloud/web/issues/10922
- test case 1:
- test case 2:
- ...
> Add loading state for admin settings spaces and groups

- tests/e2e/cucumber/features/app-provider/officeSuites.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
This test ensures that: when content of a file with "Can edit" permission is opened with the public link and password shared by creator to an "anonymous" user then the changes made by "anonymous" user are seen by the creator in real-time in both Collabora and OnlyOffice environments .
- Part of https://github.com/owncloud/web/issues/10750
- Locally
> [tests-only][full-ci] add e2e test to view real time update of content

- packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/Links/DetailsAndEdit.spec.ts
As per title.
This is a sharing NG regression, hence no need to port it to `stable-8.0`.
- Fixes https://github.com/owncloud/web/issues/10912
> fix: navigating to shared parents for indirect link shares

- tests/e2e/cucumber/features/app-provider/officeSuites.feature
test for https://github.com/owncloud/ocis/issues/9068
> [full-ci] open secure view file with collabora

- .drone.env
Part of https://github.com/owncloud/QA/issues/852
> [tests-only][full-ci] bump ocis commit id - stable

- tests/e2e/cucumber/features/app-provider/officeSuites.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/index.ts
Forward port of PR: https://github.com/owncloud/web/pull/10892/ and  https://github.com/owncloud/web/pull/10908/
> [full-ci] [tests-only] Forward port #10892 and #10908

- packages/web-app-files/src/components/SideBar/Details/TagsSelect.vue
- packages/web-app-search/src/portals/SearchBar.vue
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-runtime/src/layouts/Application.vue
- tests/e2e/cucumber/features/shares/link.feature
- tests/e2e/support/objects/app-files/resource/actions.ts
- Fixes https://github.com/owncloud/web/issues/10940
- Fixes https://github.com/owncloud/web/issues/10938
- test case 1:
- test case 2:
- ...
> fix various bugs in public link context

- tests/e2e/cucumber/features/smoke/sse.feature
part of https://github.com/owncloud/web/issues/10839
> [test-only]add sse test for file operations

- changelog/unreleased/bugfix-resource-deselection-on-right-click
- changelog/unreleased/bugfix-resources-consist-of-numbers-wont-show-up-in-trash
- changelog/unreleased/bugfix-space-not-updating
- packages/web-app-files/src/HandleUpload.ts
- packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
- packages/web-app-files/src/components/Spaces/WhitespaceContextMenu.vue
- packages/web-app-files/src/composables/keyboardActions/useKeyboardTableSpaceActions.ts
- packages/web-app-files/src/views/spaces/GenericSpace.vue
- packages/web-app-files/tests/unit/HandleUpload.spec.ts
- packages/web-client/src/helpers/resource/functions.ts
- packages/web-pkg/src/components/AppBar/AppBar.vue
- packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewFile.ts
- packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewFolder.ts
- packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewShortcut.ts
- packages/web-pkg/src/composables/breadcrumbs/useBreadcrumbsFromPath.ts
- packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateNewFile.spec.ts
- packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateNewFolder.spec.ts
- packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCreateNewShortcut.spec.ts
- packages/web-pkg/tests/unit/composables/breadcrumbs/useBreadcrumbsFromPath.spec.ts
- tests/e2e/cucumber/features/smoke/rename.feature
Merge the latest `stable-8.0` changes to master.
> Merge stable 8.0 to master

- tests/e2e/cucumber/features/app-provider/officeSuites.feature
Forward port of: https://github.com/owncloud/web/pull/10964
> refactor(test): add sharer seeing the content changed by anonymous in real-time (#10964)

- .drone.env
- .drone.star
- tests/e2e/cucumber/features/app-provider/lock.feature
- tests/e2e/cucumber/steps/ui/shares.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/share/actions.ts
Bump ocis commit id to the latest for tests
Part of https://github.com/owncloud/QA/issues/852
> [tests-only][full-ci] fix flaky app-provider e2e tests

- .drone.star
Remove unused/unnecessary and leftover of oc10 drone configs
> [tests-only][full-ci] remove unnecessary drone configs

- packages/web-app-external/src/index.ts
- packages/web-app-external/src/schemas.ts
- packages/web-client/src/helpers/resource/functions.ts
- packages/web-client/src/helpers/resource/types.ts
- packages/web-client/src/helpers/share/constants.ts
- packages/web-client/src/helpers/share/functions.ts
- packages/web-client/src/webdav/constants/dav.ts
- packages/web-pkg/src/apps/types.ts
- packages/web-pkg/src/composables/actions/files/useFileActions.ts
- packages/web-pkg/src/composables/actions/files/useFileActionsCopy.ts
- packages/web-pkg/src/composables/piniaStores/apps.ts
- packages/web-pkg/src/composables/piniaStores/clipboard.ts
- packages/web-pkg/src/services/preview/previewService.ts
- packages/web-pkg/tests/unit/composables/actions/files/useFileActions.spec.ts
- packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCopy.spec.ts
- packages/web-pkg/tests/unit/services/previewService.spec.ts
- Fixes https://github.com/owncloud/web/issues/10765
- test case 1:
- test case 2:
- ...
> Secure view fixes

- packages/web-pkg/src/services/loadingService.ts
- Fixes https://github.com/owncloud/web/issues/10954
- test case 1:
- test case 2:
- ...
> Show leave site confirmation dialog when loadingService has active tasks

- packages/tsconfig/package.json
> chore: bump tsconfig to v0.0.6

- changelog/unreleased/enhancement-add-enabled-only-filter-to-spaces-overview
- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/tests/unit/views/spaces/Projects.spec.ts
- packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
- packages/web-pkg/src/components/ItemFilterToggle.vue
- test case 1:
- test case 2:
- ...
> Add enabled only filter to spaces overview

- .drone.env
Part of https://github.com/owncloud/QA/issues/853
>  [tests-only][full-ci] bump ocis commit id - master

- .drone.env
Part of https://github.com/owncloud/QA/issues/853
> [tests-only][full-ci] bump ocis commit id - stable 

- packages/design-system/src/components/OcEmojiPicker/OcEmojiPicker.vue
- packages/design-system/src/components/OcModal/OcModal.vue
- packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap
- packages/web-pkg/src/composables/actions/spaces/useSpaceActionsSetIcon.ts
- packages/web-pkg/src/composables/piniaStores/modals.ts
- Fixes https://github.com/owncloud/web/issues/10990
- test case 1:
- test case 2:
- ...
> fix emoji picker search field not focused nor usable

- packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
- packages/web-pkg/src/composables/webWorkers/deleteWorker/useDeleteWorker.ts
- packages/web-pkg/src/composables/webWorkers/deleteWorker/worker.ts
- packages/web-pkg/tests/unit/composables/webWorkers/deleteWorker/useDeleteWorker.spec.ts
- packages/web-pkg/tests/unit/composables/webWorkers/deleteWorker/worker.spec.ts
As per title.
- Fixes https://github.com/owncloud/web/issues/10952
> feat: use delete web worker for trash bin delete operations

- packages/web-app-files/src/views/spaces/GenericSpace.vue
- packages/web-runtime/src/container/sse/files.ts
- packages/web-runtime/src/container/sse/helpers.ts
- packages/web-runtime/src/container/sse/shares.ts
- tests/e2e/cucumber/environment/index.ts
- tests/e2e/cucumber/features/smoke/sse.feature
- Fixes https://github.com/owncloud/web/issues/11011
- test case 1:
- test case 2:
- ...
> [check-console-errors] Console error e2e fixes

- docker-compose.yml
- packages/web-app-importer/src/extensions.ts
- test case 1:
- test case 2:
- ...
> fix: minor web-app-importer issues

- packages/web-app-files/src/views/spaces/GenericSpace.vue
- packages/web-pkg/src/composables/actions/files/useFileActionsPaste.ts
- packages/web-pkg/src/composables/webWorkers/index.ts
- packages/web-pkg/src/composables/webWorkers/pasteWorker/index.ts
- packages/web-pkg/src/composables/webWorkers/pasteWorker/usePasteWorker.ts
- packages/web-pkg/src/composables/webWorkers/pasteWorker/worker.ts
- packages/web-pkg/src/helpers/resource/conflictHandling/conflictDialog.ts
- packages/web-pkg/src/helpers/resource/conflictHandling/transfer.ts
- packages/web-pkg/src/helpers/resource/conflictHandling/types.ts
- packages/web-pkg/tests/unit/composables/webWorkers/pasteWorker/usePasteWorker.spec.ts
- packages/web-pkg/tests/unit/composables/webWorkers/pasteWorker/worker.spec.ts
- packages/web-pkg/tests/unit/helpers/resource/conflictHandling/resourcesTransfer.spec.ts
Adds a web worker for pasting resources that were copied/cut before.
- Fixes https://github.com/owncloud/web/issues/10951
> feat: web worker for copy/move operations

- packages/web-app-admin-settings/tests/unit/views/Spaces.spec.ts
- packages/web-pkg/src/composables/piniaStores/modals.ts
- packages/web-runtime/src/pages/logout.vue
- Fixes https://github.com/owncloud/web/issues/10502
- test case 1:
- test case 2:
- ...
> Remove all modals on logout

- packages/web-app-preview/src/App.vue
- packages/web-app-preview/src/components/Sources/MediaAudio.vue
- test case 1:
- test case 2:
- ...
> Show artist and title in audio preview app

- packages/web-runtime/src/pages/account.vue
- packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
- test case 1:
- test case 2:
- ...
> Change icon for help translate link

- docker-compose.yml
- test case 1:
- test case 2:
- ...
> Enable collabora as secureview handler

- tests/e2e/cucumber/features/admin-settings/spaces.feature
- tests/e2e/cucumber/features/file-action/download.feature
- tests/e2e/cucumber/features/file-action/groupActions.feature
- tests/e2e/cucumber/features/smoke/sse.feature
- tests/e2e/cucumber/features/spaces/internalLink.feature
- tests/e2e/cucumber/features/spaces/publicLink.feature
- tests/e2e/cucumber/steps/api.ts
- tests/e2e/support/api/davSpaces/index.ts
- tests/e2e/support/api/davSpaces/spaces.ts
- tests/e2e/support/api/graph/index.ts
- tests/e2e/support/api/graph/spaces.ts
- tests/e2e/support/api/share/index.ts
- tests/e2e/support/api/share/share.ts
- tests/e2e/support/types.ts
Replace ocs api with graph endpoint
- Part of https://github.com/owncloud/web/issues/10949
- test case 1: locally
- test case 2: CI
- ...
> [tests-only][full-ci]: use graph endpoint to do the share in API steps

- changelog/9.0.0_2024-06-13/enhancement-add-enabled-only-filter-to-spaces-overview
- changelog/9.0.0_2024-06-13/enhancement-add-include-disabled-filter-to-spaces-overview
- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/tests/unit/views/spaces/Projects.spec.ts
- packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
- packages/web-pkg/src/components/ItemFilterToggle.vue
- test case 1:
- test case 2:
- ...
> Rename enabled only filter to include disabled, turn off by default

- changelog/unreleased/bugfix-admin-settings-ui-update-after-save
- packages/web-app-admin-settings/src/composables/stores/groupSettings.ts
- packages/web-app-admin-settings/src/composables/stores/spaceSettings.ts
- packages/web-app-admin-settings/src/composables/stores/userSettings.ts
- Fixes https://github.com/owncloud/web/issues/11033
> fix: updating admin-settings ui after saving changes

- tests/e2e/support/objects/app-files/share/actions.ts
- tests/e2e/support/objects/app-files/share/collaborator.ts
Reverts quick fix https://github.com/owncloud/web/pull/11051/commits/80310c54c61b493415daa55f773c9ff31cdaf790
Fix for https://github.com/owncloud/web/issues/11046
> [tests-only][full-ci] wait for transition to end before picking a date

- .drone.star
- tests/e2e/cucumber/environment/index.ts
It was found that the access token used was invalid so deletion of any users from Web-Ocis is not happened afterall clean up. The access token becomes invalid due to Keyclock's backchannel logout feature, which makes the token invalid when the user logs out. So, above problem is cover in this PR.
More describe in here: [link](https://github.com/owncloud/docs-ocis/pull/872/files#diff-634ab767980da7e3f92f7e33d92a0f46480f230cc1d6203e74056f1bdd6069cdR25-R27)
Also in this PR, there is addition of the scenario from suites `admin-settings` that will pass in drone.
The scenarios of suites `admin-settings` which are fails in drone and are not included are as follows:
```console
- Scenario: user login can be managed in the admin settings: 3
- Scenario: edit user:84
- Scenario: admin creates user: …
```
> [full-ci][tests-only] regenerate the access token for web-ocis while running with keycloak

- packages/web-app-files/src/components/FilesViewWrapper.vue
- packages/web-app-files/tests/unit/components/FilesViewWrapper.spec.ts
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-pkg/src/components/FilesList/ResourceTiles.vue
- packages/web-pkg/src/composables/embedMode/useEmbedMode.ts
- packages/web-pkg/src/composables/piniaStores/config/types.ts
- packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
- packages/web-pkg/tests/unit/composables/embedMode/useEmbedMode.spec.ts
- packages/web-runtime/src/container/bootstrap.ts
for testing add ?embed=true&embed-target=file&embed-extensions=txt
- Fixes https://github.com/owncloud/web/issues/11052
- test case 1:
- test case 2:
- ...
> Add file picker mode

- changelog/unreleased/enhancement-accessibility-improvements
- packages/design-system/src/directives/OcTooltip.ts
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
> Make tippy content iteractive to fix #5387

- changelog/unreleased/enhancement-accessibility-improvements
- packages/design-system/src/components/OcDrop/OcDrop.vue
- packages/design-system/src/components/OcDrop/__snapshots__/OcDrop.spec.ts.snap
> Remove aria-describedby for OcDrop

- .drone.env
- tests/e2e/support/objects/account/actions.ts
Wait until the gdpr report is ready for download
- Fixes https://github.com/owncloud/ocis/issues/9448
> [tests-only][full-ci] wait until the GDPR report is ready for download

- tests/e2e/cucumber/features/shares/share.feature
- tests/e2e/cucumber/steps/ui/accountMenu.ts
- tests/e2e/support/objects/account/actions.ts
- tests/e2e/support/objects/account/index.ts
> [test-only] check access to unsynced shares

- .drone.env
Bump ocis commit id of stable5.0
Part of https://github.com/owncloud/QA/issues/854
> [tests-only][full-ci] bump ocis commit id-stable5.0

- packages/web-client/src/sse/index.ts
- packages/web-runtime/src/container/bootstrap.ts
- packages/web-runtime/src/container/sse/common.ts
- packages/web-runtime/src/container/sse/index.ts
- packages/web-runtime/src/container/sse/types.ts
- Fixes https://github.com/owncloud/web/issues/11045
- test case 1:
- test case 2:
- ...
> Add backchannel logout sse event handler

- dev/docker/ocis.idp.config.yaml
- packages/web-app-external/src/Redirect.vue
The backend doesn't add the app name to the web ui URL. Built a kind of "last resort" fallback here to mitigate the issue. Needs to be fixed properly server side (will do that on monday).
- Fixes https://github.com/owncloud/web/issues/11108
Manually with a desktop client connected to the web dev stack.
> Fix external app redirect

- deployments/continuous-deployment-config/ocis_web/master.yml
- docker/Dockerfile
Add new deployment config for `ocis.ocis-master.owncloud.works`
Fixes links and the web router by bumping the nginx base image to get https://github.com/owncloud-ops/nginx/pull/111
- test case 1:
- test case 2:
- ...
> [docs-only] feat: add new master deployment config

- packages/web-app-files/src/composables/extensions/useFileSideBars.ts
- Fixes https://github.com/owncloud/web/issues/11111
- test case 1:
- test case 2:
- ...
> Adjust actions sidebar panel icon

- packages/web-app-admin-settings/src/views/Spaces.vue
- test case 1:
- test case 2:
- ...
> Change action icon in admin settings

- packages/web-app-external/src/Redirect.vue
Apparently we need another redirect for the external app...
- Mitigates https://github.com/owncloud/web/issues/11129
client integration
> feat: build another fallback for external app redirect

- changelog/unreleased/bugfix-covered-tooltip-in-trash-bin
- packages/design-system/src/styles/theme/oc-text.scss
Please check carefully for other issues that might pop up through this fix
- Fixes #11135
> Fix partly hidden tooltip in trashbin view

- .drone.env
- Related to : https://github.com/owncloud/QA/issues/854
> [tests-only][full-ci] bump ocis commit id - master

- .drone.env
Bump ocis commit id of stable-5.0
- Related to https://github.com/owncloud/QA/issues/854
> [tests-only][full-ci] bump ocis commit id stable-5.0

- packages/web-pkg/src/components/Modals/FilePickerModal.vue
... the type is globally available in TypeScript anyway
- test case 1:
- test case 2:
- ...
> fix: remove incorrect happy-dom import

- packages/web-pkg/src/components/Modals/FilePickerModal.vue
- packages/web-pkg/tests/unit/components/Modals/FilePickerModal.spec.ts
- packages/web-runtime/src/components/Topbar/TopBar.vue
- test case 1:
- test case 2:
- ...
> Don't show logo in embed file picker mode

- packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
- packages/design-system/src/components/_OcTextInputPassword/_OcTextInputPassword.vue
- test case 1:
- test case 2:
- ...
> Use more padding for password policy indicators

- packages/eslint-config/package.json
- pnpm-lock.yaml
To ensure compatibility with TS 5.5.
> chore: bump typescript eslint plugin

- deployments/examples/ocis_web/docker-compose.yml
Use latest collabora patch release.
Use latest collabora patch release.
- Fixes locking issue.
- test case 1:
- test case 2:
- ...
> Update collabora to latest patch release

- packages/web-app-admin-settings/src/views/Users.vue
- packages/web-app-admin-settings/tests/unit/views/Users.spec.ts
- packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
- packages/web-app-files/src/components/Search/List.vue
- packages/web-app-files/src/components/SideBar/ActivitiesPanel.vue
- packages/web-app-files/src/components/SideBar/Details/TagsSelect.vue
- packages/web-app-files/tests/unit/components/Search/List.spec.ts
- packages/web-app-files/tests/unit/components/SideBar/ActivitiesPanel.spec.ts
- packages/web-app-files/tests/unit/components/SideBar/TagsSelect.spec.ts
- packages/web-client/src/graph/activities/activities.ts
- packages/web-client/src/graph/activities/index.ts
- packages/web-client/src/graph/activities/types.ts
- packages/web-client/src/graph/applications/applications.ts
- packages/web-client/src/graph/applications/index.ts
- packages/web-client/src/graph/applications/types.ts
- packages/web-client/src/graph/index.ts
- packages/web-client/src/graph/tags/index.ts
- packages/web-client/src/graph/tags/tags.ts
- packages/web-client/src/graph/tags/types.ts
Refactors the graph abstraction layer for activities, apps & tags to make them more practical and convenient to use.
The new implementation has improved method parameters, types and destructures API responses so users of the abstraction don't need to care about such things.
- refs https://github.com/owncloud/web/issues/10808
> refactor: useful graph abstraction activities, apps & tags

- packages/web-app-draw-io/src/App.vue
- packages/web-app-external/src/App.vue
- packages/web-app-external/tests/unit/__snapshots__/app.spec.ts.snap
Apps like collabora, needs a lot permissions to work in sandbox, which makes the whole feature kind of useless (as we need to allow most of the permissions)
- test case 1:
- test case 2:
- ...
> Remove sandbox for apps

- docker-compose.yml
Set up collaboration service (wopi server provided by oCIS) in docker compose.
- Part of https://github.com/owncloud/web/issues/10960
- locally
> Configure ocis collaboration service in docker compose

- changelog/unreleased/bugfix-downloading-files-via-app-top-bar-not-reflects-current-state
- packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
- Fixes https://github.com/owncloud/web/issues/11072
- test case 1:
- test case 2:
- ...
> Save file in app when dowload gets triggered, so the file eq the current state

- .drone.star
- tests/e2e/support/objects/app-files/resource/actions.ts
- Configure ocis wopi services for Collabora and Onlyoffice
- Fix tests
- part of https://github.com/owncloud/web/issues/10960
> [tests-only][full-ci] configure new ocis wopi server

- packages/web-pkg/src/components/CreateLinkModal.vue
- Fixes https://github.com/owncloud/web/issues/11168
- test case 1:
- test case 2:
- ...
> Close dropdown when user changes expiration date in create link modal

- changelog/unreleased/bugfix-images-streched-in-preview-app-in-safari
- packages/web-app-preview/src/components/Sources/MediaImage.vue
- Fixes https://github.com/owncloud/web/issues/10511
- test case 1:
- test case 2:
- ...
> Fix preview app image gets strechted in safari

- changelog/unreleased/bugfix-ui-breaks-when-tags-are-numbers
- packages/web-client/src/helpers/resource/functions.ts
- Fixes  https://github.com/owncloud/web/issues/11193
- test case 1:
- test case 2:
- ...
> Coerce dav tags to string

- packages/web-client/src/webdav/constants/dav.ts
> fixing issue part2: #11193

- packages/web-app-files/src/services/folder.ts
- test case 1:
- test case 2:
- ...
> Change to console.debug, as some routes e.G search doesnt have a  currentFolder

- packages/web-app-files/src/views/spaces/GenericSpace.vue
- packages/web-pkg/src/composables/breadcrumbs/useBreadcrumbsFromPath.ts
- packages/web-pkg/tests/unit/composables/breadcrumbs/useBreadcrumbsFromPath.spec.ts
- Fixes https://github.com/owncloud/web/issues/7799
> refactor: use fileId for breadcrumb navigation

- docs/getting-started.md
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-pkg/src/composables/piniaStores/config/config.ts
- packages/web-pkg/src/composables/piniaStores/config/types.ts
- Fixes https://github.com/owncloud/web/issues/11214
- test case 1:
- test case 2:
- ...
> Purge config option hoverableQuickActions

- dev/docker/ocis.web-federated.config.json
- dev/docker/ocis.web.config.json
- packages/design-system/src/components/OcNotifications/OcNotifications.vue
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-pkg/src/composables/piniaStores/config/config.ts
- packages/web-pkg/src/composables/piniaStores/config/types.ts
- packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
- packages/web-runtime/src/components/MessageBar.vue
- tests/drone/config-ocis.json
- vite.config.ts
- Fixes [issues/11215](https://github.com/owncloud/web/issues/11215)
- test case 1:
- test case 2:
- ...
> Purge config options topCenterNotifications and displayResourcesLazy

- tests/e2e/cucumber/features/navigation/personalSpacePagination.feature
related https://github.com/owncloud/ocis/issues/9648
> [test-only] skip pagination test

- packages/web-pkg/src/composables/piniaStores/config/config.ts
- packages/web-pkg/src/composables/piniaStores/config/types.ts
- Fixes https://github.com/owncloud/web/issues/11211
- test case 1:
- test case 2:
- ...
> Purge unused config option sharingRecipientsPerPage

- config/config.json.sample-ocis
- docs/getting-started.md
- packages/web-pkg/src/composables/piniaStores/config/types.ts
- packages/web-pkg/src/composables/upload/useUpload.ts
- Fixes #11217 
- test case 1:
- test case 2:
- ...
> Purge config option upload.xhr.timeout

- docs/getting-started.md
- packages/web-app-ocm/src/extensions.ts
- packages/web-pkg/src/composables/piniaStores/config/config.ts
- packages/web-pkg/src/composables/piniaStores/config/types.ts
- packages/web-runtime/src/pages/resolvePublicLink.vue
- Fixes #11219 
- test case 1:
- test case 2:
- ...
> Purge config options.ocm.openRemotely couple with cernFeatures config

- packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
Hides the shared-via info in shared spaces since it makes no sense there.
Also moves the remaining options API parts of this component to composition API.
- Fixes https://github.com/owncloud/web/issues/11208
> fix: shared-via info in shared spaces

- docs/getting-started.md
- packages/web-app-files/src/views/spaces/DriveResolver.vue
- packages/web-pkg/src/composables/piniaStores/config/config.ts
- packages/web-pkg/src/composables/piniaStores/config/types.ts
- packages/web-pkg/tests/unit/composables/piniaStores/config.spec.ts
- packages/web-runtime/src/pages/resolvePrivateLink.vue
- packages/web-runtime/src/pages/resolvePublicLink.vue
- packages/web-runtime/tests/unit/pages/resolvePrivateLink.spec.ts
- Fixes #11218 
- test case 1:
- test case 2:
- ...
> Purge config option options.openLinksWithDefaultApp

- docs/getting-started.md
- packages/web-app-ocm/src/extensions.ts
- packages/web-pkg/src/composables/piniaStores/config/config.ts
- packages/web-pkg/src/composables/piniaStores/config/types.ts
- packages/web-runtime/src/pages/resolvePublicLink.vue
Reverting to use new strategy (keep in named config but set via cernFeature config flag)
This reverts commit 13ca43f2bea31a11841dc77c8160966c446bb391.
- test case 1:
- test case 2:
- ...
> Revert "Purge config options.ocm.openRemotely couple with cernFeature config (#11230)"

- packages/web-pkg/src/composables/piniaStores/config/config.ts
- Fixes #11216 
- ## Motivation and Context
- test case 1:
- test case 2:
- ...
> Dont load config routing from config.json, instead set based on cernFeatures option

- changelog/unreleased/bugfix-admin-settings-open-dropdown-menu-does-not-deselect-other-items
- packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
- packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
- packages/web-app-admin-settings/src/components/Users/UsersList.vue
- Fixes #11245 
- test case 1:
- test case 2:
- ...
> Fix bug where opening context menu in admin settings doesn't deselect other items

- packages/web-client/src/helpers/share/functions.ts
- Fixes https://github.com/owncloud/web/issues/11167
> fix: add missing invited-by share info

- packages/web-app-preview/src/App.vue
- packages/web-app-preview/src/index.ts
- packages/web-app-preview/src/mimeTypes.ts
Supported mimetypes for the preview app are static, and therefore should not be loaded via config 
- test case 1:
- test case 2:
- ...
> Don't load preview app supported mimetypes from config

- packages/extension-sdk/index.mjs
- packages/extension-sdk/package.json
This allows apps to have unit tests without necessarily specifying a vitest config.
> chore: add vitest config to extension-sdk

- package.json
- pnpm-lock.yaml
- tests/e2e/cucumber/features/navigation/shortcut.feature
- tests/e2e/cucumber/features/shares/link.feature
- tests/e2e/cucumber/features/smoke/upload.feature
- tests/e2e/cucumber/steps/ui/public.ts
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
Thanks to the platwright team, we now have the ability to test folder uploads  🎉 e-huu 
thank them very much 👍 
related task: 
https://github.com/owncloud/web/issues/6051
https://github.com/owncloud/web/issues/2222
> [test-only] upload folder test

- .drone.env
Bump ocis latest master commit 
Part of https://github.com/owncloud/QA/issues/857
> [tests-only][full-ci]ocis master bump

- .drone.env
ocis stable commit bump on web stable
Part of https://github.com/owncloud/QA/issues/857
> [tests-only][full-ci]Ocis stable commit bump

- tests/e2e/cucumber/features/file-action/copyMove.feature
- tests/e2e/cucumber/features/shares/share.feature
- tests/e2e/cucumber/features/spaces/internalLink.feature
- tests/e2e/cucumber/features/spaces/participantManagement.feature
- tests/e2e/cucumber/steps/ui/spaces.ts
- tests/e2e/support/objects/app-files/resource/index.ts
- tests/e2e/support/objects/app-files/share/actions.ts
- tests/e2e/support/objects/app-files/share/index.ts
- tests/e2e/support/objects/app-files/spaces/actions.ts
- tests/e2e/support/objects/app-files/spaces/index.ts
after implementing SSE we don't need reload page in the different steps
> [full-ci] Removed unnecessary reload.page. 

- packages/web-app-importer/src/extensions.ts
- test case 1:
- test case 2:
- ...
> Use matching icon for cloud importer

- packages/web-pkg/tests/unit/composables/webWorkers/tokenTimerWorker/worker.spec.ts
Replace the timeout wait with an actual promise that is awaited to be called.
- Fixes https://github.com/owncloud/web/issues/11270
> test: fix token worker test flakyness

- changelog/unreleased/enhancement-add-edit-description-button-to-space-info
- packages/web-app-files/src/components/Spaces/SpaceHeader.vue
- packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
- test case 1:
- test case 2:
- ...
> Add edit space description button to space header

- .drone.env
- Bump ocis master latest commit id
- Part of https://github.com/owncloud/QA/issues/857
> [tests-only] [full-ci] Bump ocis master latest commit id

- packages/web-client/README.md
This clause can be removed now that the graph abstraction layer of the web-client has been refactored.
> docs: remove web-client exception clause for graph sdk

- .drone.star
- docker-compose.yml
- test case 1:
- test case 2:
- ...
> [full-ci]collabora/code bump version to 24 in dev setup, add needed extra param

- docs/extension-system/extension-types/app-menu-items.md
> docs: add instructions on how to use priority for menu items

- .drone.star
- tests/e2e/support/objects/app-files/resource/actions.ts
I tried to update collabora in CI here https://github.com/owncloud/web/pull/11301/commits/05049857107d6511666adc83be9552f36d9c24e0
but due new copy-paste warning popup tests were red. The popup window appears after pressing `ctr+C`.
I didn't find how disable this popup so I close it using UI when if it exists
> [full-ci] update collabora in CI

- packages/web-pkg/src/components/CreateLinkModal.vue
- Fixes #11309 
- test case 1:
- test case 2:
- ...
> Fix setting date in public link results in error

- tests/e2e/cucumber/features/smoke/activity.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/cucumber/steps/ui/spaces.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/index.ts
- tests/e2e/support/objects/app-files/spaces/actions.ts
- tests/e2e/support/objects/app-files/spaces/index.ts
first basic activities test. the rest of the tests we implement later when the activity feature will be fully implemented.
I check that the user can open the activity sidebar and see the activity in
- project space
- shares jail
- in the resources from personal space
> [test-only] activities test

- .drone.env
- Bump ocis master latest commit id
- Part of https://github.com/owncloud/QA/issues/857
> [tests-only] [full-ci] Ocis master bump

- packages/web-runtime/src/components/Account/ExtensionPreference.vue
- Fixes #11314 
- test case 1:
- test case 2:
- ...
> Fix extension prefrences not filterable

- packages/design-system/src/components/OcDrop/OcDrop.vue
- packages/design-system/src/components/OcFilterChip/OcFilterChip.vue
- packages/design-system/src/components/OcSelect/OcSelect.vue
- packages/design-system/src/components/OcTable/OcTable.sort.spec.ts
- packages/design-system/src/components/OcTable/OcTable.vue
- packages/design-system/src/styles/theme/helper.scss
- packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
- packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
- packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
- packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
- packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
- packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.ts.snap
- packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap
- packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
- packages/web-pkg/src/components/AppTopBar.vue
- packages/web-pkg/src/components/FilesList/ResourceName.vue
- packages/web-pkg/src/components/SideBar/FileSideBar.vue
See individual commits for all information.
- Works towards https://github.com/owncloud/web/issues/10735
> fix: outlines on focussed elements

- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- Fixes #11333 
- test case 1:
- test case 2:
- ...
> fix: All"-checkbox is checked if all resources disabled

- packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
- packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
- packages/web-pkg/src/components/FilesList/ResourceListItem.vue
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-pkg/src/components/FilesList/ResourceTile.vue
- packages/web-pkg/src/components/FilesList/ResourceTiles.vue
- Fixes #11334 
- test case 1:
- test case 2:
- ...
> Remove click event from disabled spaces

- packages/web-pkg/src/composables/actions/files/useFileActionsCopyQuicklink.ts
- Fixes #11327 
- test case 1:
- test case 2:
- ...
> Fix: copy quicklink, when exsiting user share is present, fails

- changelog/unreleased/bugfix-ocm-page-reload
- packages/web-app-ocm/src/index.ts
As per title.
- Fixes https://github.com/owncloud/web/issues/11153
> fix: page reload on ocm page

- packages/web-pkg/src/components/TextEditor/TextEditor.vue
- Fixes #11326 
- test case 1:
- test case 2:
- ...
> Enable command shortcuts on text-editor

- packages/web-pkg/src/components/FilesList/ResourceListItem.vue
- test case 1:
- test case 2:
- ...
> Remove tooltip from parent folder, to avoid overlapping tooltips

- changelog/unreleased/bugfix-closing-an-app-opened-via-in-app-open-feature-stays-open
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-pkg/src/components/Modals/FilePickerModal.vue
- packages/web-pkg/src/composables/actions/files/useFileActions.ts
- packages/web-pkg/src/composables/appDefaults/useAppNavigation.ts
- packages/web-pkg/src/composables/embedMode/useEmbedMode.ts
- packages/web-pkg/tests/unit/components/Modals/FilePickerModal.spec.ts
- test case 1:
- test case 2:
- ...
> Fix: closing opened app via file picker modal doesn't route to correct location 

- changelog/unreleased/bugfix-closing-an-app-opened-via-in-app-open-feature-stays-open
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- test case 1:
- test case 2:
- ...
> fix: open in app tries to open deleted folder

- packages/web-app-files/src/composables/extensions/useFileSideBars.ts
- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
- packages/web-pkg/src/composables/actions/spaces/useSpaceActionsShowMembers.ts
- packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/SpaceDetails.spec.ts
- packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsShowMembers.spec.ts
- Fixes #11362 
- test case 1:
- test case 2:
- ...
> Hide members panel when space is disabled

- packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
- packages/web-app-files/src/components/SideBar/Shares/Links/NameAndCopy.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/NameAndCopy.spec.ts.snap
- tests/e2e/support/objects/app-files/link/actions.ts
- tests/e2e/support/objects/app-files/share/actions.ts
- Fixes #10734 
- Fixes #11375
- test case 1:
- test case 2:
- ...
> Add screen reader creation time in share sidebar for links

- packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
- packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.ts.snap
- Part of https://github.com/owncloud/web/issues/10739
- test case 1:
- test case 2:
- ...
> Add aria expanded to left sidebar toggle

- generate-qa-activity-report.js
- pnpm-lock.yaml
part of https://github.com/owncloud/ocis/issues/9730
report for unit tests
result - csv file which includes info about UI test and Unit test
example: 
```
Test-Type,Date,Tests Added,Tests Changed,Tests Deleted,commit-ID
UI Test,2024-08-19T14:30:23+05:45,0,2,0,08d14124cb17b3e928575d67a84c4f71fb0967cb
UI Test,2024-08-19T11:36:04+05:45,0,2,0,9ff8cfabd32b33b22f50d4685f8148f1bbc03336
Unit Test,2024-08-16T11:23:42+02:00,2,0,0,55c32e1b1ad3713bb746ad1f80752d5b589ae269
Unit Test,2024-08-15T12:04:51+02:00,4,7,0,4c3dc5e77b5d01d98c375729793847414c5e900f
Unit Test,2024-08-09T13:48:07+02:00,4,7,0,b4eca2528933406eede42a98a29523606270e88f
Unit Test,2024-08-15T08:10:09+02:00,0,36,0,40abad45909bd2ecb3dd8e137671774422a03862
Unit Test,2024-08-14T07:42:50+02:00,0,36,0,fc82de577f5b973df79dda9a8f29de4573faaa4e …
```
> report for unit tests

- packages/web-client/src/graph/generated/api.ts
- packages/web-pkg/src/components/SideBar/FileSideBar.vue
As per title.
Also uses the `ListPermissionsSpaceRootSelectEnum` from the generated code, since the original issue with this enum has now been fixed.
- Fixes https://github.com/owncloud/web/issues/11363
> chore: update graph sdk

- package.json
- pnpm-lock.yaml
> chore: bump pnpm to v9.8.0

- .drone.env
Bump ocis commit id to the latest.
Part of: https://github.com/owncloud/QA/issues/860
> [tests-only][full-ci] bump ocis latest commit id - master

- .drone.env
- .drone.star
- docker-compose.yml
This PR fixes the nightly failure in `e2e-tests-app-provider` suite by adding:
```
"GRAPH_AVAILABLE_ROLES": "b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6"
```
to drone config file and also in docker compose file
- Fixes: https://github.com/owncloud/web/issues/11442
- Locally
- CI
> test: fix nightly failure and add configs

- packages/web-app-ocm/src/views/OutgoingInvitations.vue
Fixes date times for ocm invitations so they get displayed properly in the UI.
- refs https://github.com/owncloud/ocis/issues/9735
> fix(ocm): invitation date times

- .renovaterc.json
- pnpm-lock.yaml
Run `pnpm dedupe` and add it as post update script for Renovate.
> chore: pnpm dedupe

- .drone.env
- .drone.star
This PR places the config variable `GRAPH_AVAILABLE_ROLES` in the right place which fixes the nightly failure.
- Fixes: https://github.com/owncloud/web/issues/11442
- Locally
- CI
> [tests-only][full-ci] place cofig variable into right place

- packages/design-system/src/components/OcTextInput/OcTextInput.vue
Fixes a regression introduced by https://github.com/owncloud/web/commit/72ae7e9ec126470729b568f07a047606db95d7f2.
Fixes https://github.com/owncloud/web/issues/11471.
> fix: initial filename selection in modal

- changelog/unreleased/enhancement-add-select-all-checkbox-to-tiles-view
- packages/design-system/src/components/OcCheckbox/OcCheckbox.spec.ts
- packages/design-system/src/components/OcCheckbox/OcCheckbox.vue
- packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
- packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
- packages/web-app-admin-settings/src/components/Users/UsersList.vue
- packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
- packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
- packages/web-app-files/src/components/Search/List.vue
- packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
- packages/web-app-files/src/views/Favorites.vue
- packages/web-app-files/src/views/shares/SharedViaLink.vue
- packages/web-app-files/src/views/shares/SharedWithOthers.vue
- packages/web-app-files/src/views/spaces/GenericSpace.vue
- packages/web-app-files/src/views/spaces/GenericTrash.vue
- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-pkg/src/components/FilesList/ResourceTiles.vue
- packages/web-pkg/src/components/ItemFilter.vue
- packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
- test case 1:
- test case 2:
- ...
> Select all checkbox tiles view

- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-pkg/src/components/FilesList/ResourceTiles.vue
- packages/web-pkg/src/components/Modals/FilePickerModal.vue
- packages/web-pkg/src/composables/embedMode/useEmbedMode.ts
- Fixes #11516 
- test case 1:
- test case 2:
- ...
> Fix bug where file picker doesnt work with built web

- .drone.env
bump latest ocis master commit id
Part of: https://github.com/owncloud/QA/issues/861
> [tests-only][full-ci] bump latest ocis commit id

- packages/web-pkg/src/components/CreateLinkModal.vue
- test case 1:
- test case 2:
- ...
> Don't expose password in create link modal

- packages/web-app-app-store/src/components/AppImageGallery.vue
- packages/web-app-app-store/src/piniaStores/apps.ts
- packages/web-app-app-store/src/types.ts
- packages/web-app-app-store/src/views/AppList.vue
Adding an optional `badge` prop for app store apps.
> feat: badges for the app store

- changelog/unreleased/enhancement-add-split-confirm-button-to-create-link-modal
- packages/web-pkg/src/components/CreateLinkModal.vue
- packages/web-pkg/src/composables/actions/files/useFileActionsCreateLink.ts
- packages/web-pkg/tests/unit/components/CreateLinkModal.spec.ts
- packages/web-runtime/src/components/ModalWrapper.vue
- Fixes #11551 
- test case 1:
- test case 2:
- ...
> Make copy link primary action and copy link with password secondary action

- dev/docker/ocis.storage.ocmproviders.json
nothing huge, just a tiny conf change to make it compatible with the latest ocis container
> fix(ocm): conf

- .drone.env
- .drone.star
- tests/e2e/config.js
- tests/e2e/cucumber/environment/index.ts
- tests/e2e/cucumber/environment/world.ts
- tests/e2e/support/environment/actor/actor.ts
- tests/e2e/support/environment/actor/shared.ts
Port https://github.com/owncloud/web/pull/11571
> [tests-only][full-ci] report tracing for failed tests only

- package.json
- pnpm-lock.yaml
latest version have some fixes for the traceviewer
https://github.com/microsoft/playwright/releases/tag/v1.47.1
https://github.com/microsoft/playwright/releases/tag/v1.45.3
> [tests-only][full-ci] bump playwright version to 1.47.1

- changelog/unreleased/bugfix-thumbnails-for-geogebra-slides-not-showing-up
- packages/web-pkg/src/services/preview/previewService.ts
- Fixes #11576 
- test case 1:
- test case 2:
- ...
> Bugfix: thumbnails for geogebra slides weren't displayed anymore

- tests/e2e/cucumber/features/user-settings/languageChange.feature
- tests/e2e/cucumber/steps/ui/accountMenu.ts
- test case 1:
- test case 2:
- ...
> Enable e2e language change test

- .drone.env
Bump latest ocis master commit id.
Part of: https://github.com/owncloud/QA/issues/862
> [tests-only] [full-ci] bump latest ocis master commit id

- changelog/unreleased/bugfix-app-version-downloads
- packages/web-app-app-store/src/components/AppActions.vue
App version downloads from the app releases table were failing.
> fix: app version downloads

- tests/e2e/cucumber/features/file-action/copyMove.feature
- tests/e2e/cucumber/features/file-action/download.feature
- tests/e2e/cucumber/features/file-action/groupActions.feature
- tests/e2e/cucumber/features/file-action/rename.feature
- tests/e2e/cucumber/features/navigation/shortcut.feature
- tests/e2e/cucumber/features/navigation/urlJourneys.feature
- tests/e2e/cucumber/features/search/fullTextSearch.feature
- tests/e2e/cucumber/features/search/search.feature
- tests/e2e/cucumber/features/shares/internalLink.feature
- tests/e2e/cucumber/features/shares/link.feature
- tests/e2e/cucumber/features/shares/share.feature
- tests/e2e/cucumber/features/smoke/activity.feature
- tests/e2e/cucumber/features/smoke/sse.feature
- tests/e2e/cucumber/features/smoke/tags.feature
- tests/e2e/cucumber/features/smoke/uploadResumable.feature
- tests/e2e/cucumber/features/user-settings/languageChange.feature
- tests/e2e/cucumber/features/user-settings/notifications.feature
- tests/e2e/cucumber/features/user-settings/tiles.feature
- tests/e2e/cucumber/steps/api.ts
- tests/e2e/cucumber/steps/ui/links.ts
- tests/e2e/cucumber/steps/ui/public.ts
- tests/e2e/support/api/share/share.ts
- tests/e2e/support/objects/app-files/link/index.ts
- tests/e2e/support/store/index.ts
- tests/e2e/support/store/link.ts
As per https://github.com/owncloud/web/pull/11456#pullrequestreview-2289864737 , the login step will be done only after all API of the `Given` statement.  
For the scenario involving creating the link, `roleDisplayText` and `securePassword` are removed from the Link object because these are just used for storing link-related information, and to access them, one has to create a new object. 
- Fixes https://github.com/owncloud/web/issues/11496
> [tests-only][full-ci]move login step after all API query is done

- packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
- packages/web-app-files/tests/unit/components/AppBar/__snapshots__/CreateAndUpload.spec.ts.snap
- Fixes #11336 
- test case 1:
- test case 2:
- ...
> Refactor new and upload menus

- changelog/unreleased/bugfix-wrong-webdav-url-in-sidebar
- packages/web-pkg/src/components/SideBar/WebDavDetails.vue
- Fixes #11590 
- test case 1:
- test case 2:
- ...
> Fix webdav url in sidebar

- packages/web-app-files/src/components/Shares/CopyPrivateLink.vue
- packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
- packages/web-app-files/tests/unit/components/Shares/__snapshots__/CopyPrivateLink.spec.ts.snap
- Fixes #11383 
- test case 1:
- test case 2:
- ...
> Don't show add members headline in space sharing panel if user doesn't have the respective permission

- packages/web-app-app-store/src/views/AppList.vue
As per title 
- test case 1:
- test case 2:
- ...
> Add no content message, when search gives no result in app store

- .drone.env
- tests/e2e/cucumber/environment/index.ts
- tests/e2e/cucumber/features/smoke/activity.feature
- tests/e2e/support/api/davSpaces/spaces.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- Fixes #11647
- Fixes #11657
- Fixes #11648
> [tests-only][full-ci] fix nightly e2e test failures

- changelog/unreleased/enhancement-a11y-improvements
- packages/web-pkg/src/components/SideBar/SideBar.vue
Fix tiny issue from https://github.com/owncloud/web/commit/1e2c6982b1854502d92c4b68d35cf15462ec138b.
> fixup! fix(a11y): focusing background elements with 100% sidebar

- changelog/unreleased/bugfix-file-name-truncation
- packages/web-pkg/src/components/FilesList/ResourceLink.vue
- packages/web-pkg/src/components/FilesList/ResourceListItem.vue
- packages/web-pkg/src/components/FilesList/ResourceName.vue
- packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
- packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
As per title.
This is a regression caused by https://github.com/owncloud/web/commit/3093821a879dc81b49ae7e37dab18440aed6ad9e.
- Fixes https://github.com/owncloud/web/issues/11617
> fix: file name truncation in file lists

- deployments/examples/ocis_web/docker-compose.yml
- docker-compose.yml
Same as https://github.com/owncloud/ocis/pull/10193 but for our dev stack and demo deployment...
> chore: add ocis url to collaboration service

- .drone.env
part of https://github.com/owncloud/ocis/issues/10186
> [full-ci] bump ocis/run all tests

- .drone.env
Bump latest ocis master commit id
- Part of: https://github.com/owncloud/QA/issues/863
> [tests-only][full-ci] test: bump latest ocis commit id

- changelog/unreleased/bugfix-prevent-not-allowed-characters-in-shortcut-name
- packages/web-pkg/src/components/CreateShortcutModal.vue
As per title.
Note that we don't need to be as restrictive as in `packages/web-pkg/src/composables/actions/files/useFileActionsCreateNewFile.ts`since we always append  the .`url` extension
- Fixes #11702 
- test case 1:
- test case 2:
- ...
> Restrict shortcut name

- packages/web-app-app-store/src/views/AppDetails.vue
- packages/web-app-files/src/components/Spaces/SpaceHeader.vue
- packages/web-pkg/src/components/TextEditor/TextEditor.vue
- packages/web-runtime/tests/unit/pages/resolvePublicLink.spec.ts
- pnpm-lock.yaml
- test case 1:
- test case 2:
- ...
> Enhancement: enable markdown for app description in app store

- .drone.env
> [tests-only][full-ci] Bump latest commit id of ocis master

- docker-compose.yml
- vite.config.ts
Use server theme endpoint in vite.
> fix: logo upload and theme handling in dev stack

- packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
- packages/web-app-files/src/components/SideBar/Shares/Links/EditDropdown.vue
- packages/web-app-files/src/components/SideBar/Shares/Links/ListItem.vue
- packages/web-pkg/src/composables/piniaStores/shares/shares.ts
- pnpm-lock.yaml
Partial update of public links, so the API only receives the updated props.
- Part of owncloud/ocis#10295 
- test case 1:
- test case 2:
- ...
> Partial update for publink links

- packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
- packages/web-pkg/src/components/AppTemplates/AppWrapperRoute.ts
- packages/web-pkg/src/components/AppTopBar.vue
> Allow editors to overwrite global autosave configuration

- packages/web-app-ocm/package.json
- packages/web-app-search/package.json
- pnpm-lock.yaml
- test case 1:
- test case 2:
- ...
> fix: add missing deps to ocm and search app

- vite.config.ts
- test case 1:
- test case 2:
- ...
> fix: theme shipping

- packages/web-pkg/src/components/FilesList/ResourceIcon.vue
Fixes regression from https://github.com/owncloud/web/commit/6c43a2485849444da34b3690ae7f6db55e134577.
> fix: resource icon size in file list

- tests/e2e/cucumber/environment/index.ts
- tests/e2e/cucumber/features/admin-settings/spaces.feature
- tests/e2e/cucumber/features/admin-settings/users.feature
- tests/e2e/cucumber/steps/ui/session.ts
- tests/e2e/support/api/keycloak/index.ts
- tests/e2e/support/api/keycloak/ocisUserToken.ts
- tests/e2e/support/api/keycloak/user.ts
- tests/e2e/support/api/keycloak/utils.ts
- tests/e2e/support/objects/runtime/session.ts
- tests/e2e/support/utils/tokenHelper.ts
This PR adds the code for getting access token for ocis user when keycloak is used as IDP. 
This is done so that login step can be shifted after all API task is performed.
The grant type for getting access token is [Authorization Code Grant Type](https://oauth.net/2/grant-types/authorization-code/)
- Fixes https://github.com/owncloud/web/issues/11307
> [tests-only][full-ci]getting ocis keycloak token using auth code flow

- .drone.env
Bump latest commit id of ocis->stable5.0
- Part of: https://github.com/owncloud/QA/issues/863
> [tests-only][full-ci] bump ocis stable5.0 commit id

- .drone.env
Bump latest ocis master commit id
- Part of: https://github.com/owncloud/QA/issues/863
> [tests-only][full-ci] test: bump latest ocis master commit id

- tests/e2e/cucumber/environment/index.ts
- tests/e2e/support/api/graph/userManagement.ts
- tests/e2e/support/api/keycloak/ocisUserToken.ts
- tests/e2e/support/api/keycloak/user.ts
- tests/e2e/support/api/keycloak/utils.ts
- tests/e2e/support/utils/tokenHelper.ts
Follow up PR after https://github.com/owncloud/web/pull/11630
Cleaning up some test code related to user creation step to maintain the consistency. 
- test case 1:
- test case 2:
- ...
> [tests-only][full-ci]cleaning code related for user token

- tests/e2e/cucumber/features/shares/share.feature
- tests/e2e/cucumber/steps/ui/resources.ts
accidentally hit a commit #11808 ->revert it
> [test-only] revert changes from #11808

- .drone.env
part of https://github.com/owncloud/QA/issues/865
> [tests-only][full-ci] Bump ocis master latest commit id

- README.md
- docs/development/repo-structure.md
Basic housekeeping
- Fixes #8366
> Start updating repo structure in dev docs and root readme

- packages/web-pkg/src/services/preview/previewService.ts
Make web request previews for .ggp files.
- Works towards https://github.com/owncloud/enterprise/issues/6907
> feat: allow .ggp preview fetching

- .drone.env
Bump latest commit id of ocis->stable5.0
- Part of: https://github.com/owncloud/QA/issues/866
> [tests-only][full-ci] test: bump ocis stable-5.0 commit id

- packages/web-app-files/src/views/spaces/Projects.vue
Before:
After:
- test case 1:
- test case 2:
- ...
> Fix: files app space sorting is case sensitive and therefore wrong

- .drone.env
Bump latest ocis master commit id
- Part of: https://github.com/owncloud/QA/issues/866
> [tests-only][full-ci] test: bump latest commit id of ocis master

- changelog/unreleased/enhancement-create-spaces-via-admin-settings
- packages/web-app-admin-settings/src/views/Spaces.vue
- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/tests/unit/components/AppBar/__snapshots__/CreateSpace.spec.ts.snap
- packages/web-pkg/src/components/AppBar/CreateSpace.vue
- packages/web-pkg/src/components/AppBar/index.ts
- packages/web-pkg/tests/unit/components/AppBar/CreateSpace.spec.ts
- packages/web-pkg/tests/unit/components/AppBar/__snapshots__/CreateSpace.spec.ts.snap
- tests/e2e/cucumber/features/admin-settings/spaces.feature
- Fixes #11771 
- test case 1:
- test case 2:
- ...
> Create spaces via admin settings

- tests/e2e/cucumber/features/file-action/groupActions.feature
- tests/e2e/cucumber/features/smoke/uploadResumable.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
> [tests-only[full-ci] refactor button assertion

- changelog/unreleased/bugfix-expose-request-id-when-delete-fails
- packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
- Part of #11925 
- test case 1:
- test case 2:
- ...
> expose request id, when delete fails

- packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
- Fixes #12007 
- test case 1:
- test case 2:
- ...
> Replace (not user friendly) custom permission list with generic info text

- tests/e2e/support/objects/federation/actions.ts
In the current behavior, the invitation token is now encoded, eliminating the need to explicitly choose an OCIS instance during federated sharing. This PR introduces the following updates:
- Removed steps that were previously used for selecting a specific OCIS instance. These are no longer required due to the encoded invitation token functionality.
- Added code to encode the invitation code received via the API to align with the current implementation and ensure compatibility.
- Fixes https://github.com/owncloud/web/issues/12017
- locally
> [full-ci][tests-only] Adjust federated share step based on current behavior

- .drone.env
- .drone.star
run all tests on ocis `7.0.0-rc.4`
> [full-ci] update ocis. run tests

- .drone.env
This PR bumps latest ocis commit id of master branch 
Part of 
- https://github.com/owncloud/QA/issues/870
> [tests-only][full-ci]Bump ocis master commit id

- .drone.env
This pr bumps latest ocis master commit id.
Part of: https://github.com/owncloud/QA/issues/870
> [tests-only][full-ci] bump latest ocis master commit id

- .drone.env
This pr bumps latest ocis master commit id.
Part of: https://github.com/owncloud/QA/issues/870
> [tests-only] [full-ci] bump ocis master commit id

- .drone.env
Bump latest `master-ocis` commit to `web-master`
Part of:
https://github.com/owncloud/QA/issues/872
> [tests-only][full-ci]Bump ocis to web

- .drone.env
Bump latest ocis commit.
Part of https://github.com/owncloud/QA/issues/872
> [tests-only][full-ci]commit ocis master

- packages/web-test-helpers/src/mocks/pinia.ts
Extended the types.
Needed in https://github.com/owncloud/web-extensions/pull/130
> feat(web-test-helpers): add currentSpace type into mocked pinia

- packages/extension-sdk/index.mjs
- vite.config.ts
Make dist dir in extension-sdk configurable
With this env var multiple apps can be written to a single folder that then is consumed by oCIS via `WEB_ASSET_APPS_PATH`.
- test case 1:
- test case 2:
- ...
> feat: make dist dirs configurable

- packages/web-runtime/src/container/bootstrap.ts
Use file extension icon before falling back to app icon.
The only real change is
```
name: fileExtensions.icon || app.icon,
```
I've additionally renamed the variables because they were incredibly hard to reason about for no good reason imho.
- test case 1:
- test case 2:
- ...
> fix: use file extension icon

- .drone.env
Bump latest ocis stable 7.0 commit id
- Part of: https://github.com/owncloud/QA/issues/876
> [tests-only][full-ci] test: bump latest ocis stable7.0 commit id in stable 11.0

- package.json
- packages/design-system/package.json
- packages/web-client/package.json
- packages/web-pkg/package.json
- pnpm-lock.yaml
- test case 1:
- test case 2:
- ...
> chore: update dependency

- changelog/unreleased/bugfix-sanitize-editor-content.md
- packages/web-pkg/package.json
- packages/web-pkg/src/components/TextEditor/TextEditor.vue
- pnpm-lock.yaml
- Fixes [<issue_link>](https://github.com/owncloud/enterprise/issues/7092)
- test case 1:
- test case 2:
- ...
> bugfix: sanitize content from md-editor

- .drone.env
This pr bumps ocis latest commit id.
https://github.com/owncloud/QA/issues/877
> [tests-only][full-ci] test: bump ocis commit id

- packages/web-app-app-store/src/views/AppDetails.vue
- packages/web-pkg/src/components/TextEditor/TextEditor.vue
Md editor content is being overflown when used in the app store.
- Fixes https://github.com/owncloud/web/issues/12178
- test case 1:
- test case 2:
- ...
> bugfix: fix editor content overflow

- changelog/unreleased/bugfix-preserve-current-page-on-file-open.md
- packages/web-pkg/src/router/spaces.ts
- Fixes https://github.com/owncloud/web/issues/12162
- test case 1:
- test case 2:
- ...
> fix: preserve current page when opening a file

- tests/drone/config-ocis.json
- tests/e2e/cucumber/features/file-action/passswordProtectedFolder.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
This PR adds e2e tests for password-protected folders, including a scenario for `creating a password-protected folder`.
**screen video demonstrating how the test is done:**
[Screencast from 02-21-2025 11:17:02 AM.webm](https://github.com/user-attachments/assets/661c3fcd-229e-413d-a283-ab5562ffb510)
- https://github.com/owncloud/web/issues/12181
- Docker
- CI
> [tests-only][full-ci] added test for password protected folder

- packages/web-app-password-protected-folders/README.md
This PR updates the readme of password protected folders.
It is based on intense discussions with @LukasHirt 
@phil-davis mind to do a language review?
Note that line numbering always starting with 1. is a markdown thing and makes that the line numbers increase automatically without defining the value explicily :sweat_smile:
> Update / fix the password protected folders readme

- changelog/unreleased/bugfix-sorting-arrow-misplaced.md
- packages/design-system/src/components/OcTable/OcTable.vue
- Fixes https://github.com/owncloud/web/issues/12232
- test case 1:
- test case 2:
- ...
> bugfix: place sorting arrow correctly next to the text

- packages/web-app-password-protected-folders/README.md
Fix a typo in password protected folders readme
> Typo fix, update PPF README.md

- changelog/unreleased/enhancement-add-new-supported-language-to-md-editor.md
- packages/web-pkg/package.json
- packages/web-pkg/src/components/TextEditor/TextEditor.vue
- packages/web-pkg/src/components/TextEditor/l18n.ts
- pnpm-lock.yaml
- Add Arabic language to md-editor
- Add auto focus on md-editor
- test case 1:
- test case 2:
- ...
> feat: add Arabic language to md-editor

- tests/e2e/support/api/token/utils.ts
exit retry loop if the request is success
Test code was performing auth request until timeout
- test environment: :hand:
> [test-only][full-ci] test: exit retry loop on success

- docs/releasing.md
Update release docs to reflect the latest process and include update steps for oCIS
Everyone knows how to create a new release
> docs: update release process and add oCIS Web update steps

- pnpm-lock.yaml
The CI started failing now with the latest deps PRs merges. This should fix it.
> chore: rebuild broken lockfile

- README.md
Update README file to include correct oCIS demo page link.
- test case 1:
- test case 2:
- ...
> chore: update readme file to include correct oCIS demo page link

- packages/web-runtime/src/components/MaintenanceBanner/MaintenanceBanner.vue
- packages/web-runtime/src/components/MaintenanceBanner/MaintenanceDetailsModal.vue
Add a missing word to a translatable source string.
> Just a small source text fix for translations

- .drone.env
This PR updates only the `.drone.env` config file to use branch `stable-7.1` and it's latest commit - `051ad98d46ae662e49e25f3ab4b7271e5b15b559`
- Fixes [#11104 ](https://github.com/owncloud/ocis/issues/11104)
Drone config file should point to the proper branch name and commit hash code
- tested locally only
> [full-ci] Update Drone config file for branch `stable-7.1`

- .drone.star
- .prettierignore
- generate-qa-activity-report.js
- package.json
- packages/eslint-config/index.js
- packages/eslint-config/package.json
- pnpm-lock.yaml
- web.d.ts
Using the plugin hurts performance of eslint too much.
- Fixes https://github.com/owncloud/web/issues/12051
Faster linting
- test environment: 🤖
> chore: use prettier config instead of plugin

- changelog/unreleased/bugfix-distinguish-between-external-users.md
- packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/ListItem.spec.ts
- packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/__snapshots__/ListItem.spec.ts.snap
We've fixed an issue where multiple external users with the same name were indistinguishable. By adding the domain to the user information/tooltip and below the user name, external users can now be easily distinguished.
- Fixes https://github.com/owncloud/web/issues/12184
- test case 1:
- test case 2:
- ...
> bugfix: add domain name to distinguish between external users

- changelog/unreleased/enhancement-rephrase-science-mesh-invite-users.md
- packages/web-app-ocm/src/views/OutgoingInvitations.vue
rephrase invite users to invite users to federate
- Fixes https://github.com/owncloud/web/issues/11566
- test case 1:
- test case 2:
- ...
> task: rephrase invite users to invite users to federate

- tests/e2e/cucumber/features/file-action/passwordProtectedFolder.feature
This PR adds test coverage for bug: https://github.com/owncloud/web/issues/12273
https://github.com/owncloud/web/issues/12273
- Locally
- CI
> [tests-only][full-ci] Test coverage for bug #12273

- tests/e2e/cucumber/features/file-action/passwordProtectedFolder.feature
- tests/e2e/cucumber/steps/ui/application.ts
- tests/e2e/cucumber/steps/ui/links.ts
- tests/e2e/cucumber/steps/ui/public.ts
- tests/e2e/support/environment/actor/actors.ts
- tests/e2e/support/objects/app-files/link/actions.ts
- tests/e2e/support/objects/app-files/link/index.ts
- tests/e2e/support/objects/app-files/page/public.ts
- tests/e2e/support/objects/app-files/utils/sidebar.ts
This PR contains test steps to check if password protected folder can be opened or not:
- open by normal user in Personal space
- open by public user
- open by space member in Project space
From unlocking the password protected folder to list those, all are wrapped inside iFrame that can be located using id selector `'#iframe-folder-view'`.
- Related to: https://github.com/owncloud/web/issues/12181
- Locally
- CI
> [tests-only][full-ci] Test for opening  password protected folder 

- tests/e2e/cucumber/features/file-action/passwordProtectedFolder.feature
- tests/e2e/cucumber/steps/ui/public.ts
- tests/e2e/support/objects/app-files/link/actions.ts
- tests/e2e/support/objects/app-files/link/index.ts
- tests/e2e/support/objects/app-files/page/public.ts
This PR contains test steps to check if password protected folder can't be opened with wrong password and proper error message appears for trying to do so in both project and personal space
Related to: https://github.com/owncloud/web/issues/12181
- Locally
- CI
> [tests-only][full-ci] Test for opening password protected folder with wrong password

- changelog/unreleased/bugfix-mock-services-correctly.md
- packages/web-pkg/tests/unit/components/sidebar/FileSideBar.spec.ts
- Fixes https://github.com/owncloud/web/issues/12375
- test case 1:
- test case 2:
- ...
> bugfix: correctly mock services

- packages/design-system/src/components/OcDrop/OcDrop.vue
- packages/design-system/src/components/OcInfoDrop/OcInfoDrop.spec.ts
- packages/design-system/src/components/OcInfoDrop/OcInfoDrop.vue
Refactor oc-drop-info Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-drop-info component using script setup

- packages/design-system/src/components/OcAvatarCount/OcAvatarCount.vue
Refactor oc-avatar-count Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-avatar-count component using script setup

- packages/design-system/src/components/OcAvatar/OcAvatar.vue
Refactor oc-avatar Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-avatar component using script setup

- packages/design-system/src/components/OcApplicationIcon/OcApplicationIcon.vue
Refactor oc-application-icon Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-application-icon component using script setup

- packages/design-system/src/components/OcAvatarFederated/OcAvatarFederated.vue
Refactor oc-avatar-federated Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-avatar-federated component using script setup

- packages/design-system/src/components/OcAvatarLink/OcAvatarLink.vue
Refactor oc-avatar-link Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-avatar-link component using script setup

- packages/design-system/src/components/OcAvatars/OcAvatars.vue
Refactor oc-avatars Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-avatars component using script setup

- packages/design-system/src/components/OcAvatarGroup/OcAvatarGroup.vue
Refactor oc-avatar-group Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-avatar-group component using script setup

- packages/design-system/src/components/OcAvatarGuest/OcAvatarGuest.vue
Refactor oc-avatar-guest Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-avatar-guest component using script setup

- packages/design-system/src/components/OcAvatarItem/OcAvatarItem.vue
Refactor oc-avatar-item Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-avatar-item component using script setup

- packages/design-system/src/components/OcButton/OcButton.spec.ts
- packages/design-system/src/components/OcButton/OcButton.vue
Refactor oc-button Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-button component using script setup

- .drone.env
This pr bumps latest commit id of ocis stable-7.1
- Related to: https://github.com/owncloud/QA/issues/881
> [tests-only][full-ci] bump ocis stable-7.1 commit id

- packages/design-system/src/components/OcDefinitionList/OcDefinitionList.vue
Refactor oc-definition-list Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-definition-list component using script setup

- packages/design-system/src/components/OcContextualHelper/OcContextualHelper.vue
Refactor oc-contextual-helper Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-contextual-helper component using script setup

- packages/design-system/src/components/OcCheckbox/OcCheckbox.spec.ts
- packages/design-system/src/components/OcCheckbox/OcCheckbox.vue
- packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
Refactor oc-checkbox Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-checkbox component using script setup

- packages/design-system/src/components/OcErrorLog/OcErrorLog.vue
Refactor oc-error-log Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-error-log component using script setup

- packages/design-system/src/components/OcEmojiPicker/OcEmojiPicker.vue
Refactor oc-drop-zone Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-emoji-picker component using script setup

- packages/design-system/src/components/OcDropzone/OcDropzone.vue
Refactor oc-drop-zone Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-drop-zone component using script setup

- packages/design-system/src/components/OcFilterChip/OcFilterChip.vue
Refactor oc-filter-chip Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-filter-chip component using script setup

- packages/design-system/src/components/OcGrid/OcGrid.spec.ts
- packages/design-system/src/components/OcGrid/OcGrid.vue
Refactor oc-grid Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-grid component using script setup

- packages/design-system/src/components/OcHiddenAnnouncer/OcHiddenAnnouncer.vue
Refactor oc-hidden-announcer Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-hidden-announcer component using script setup

- packages/design-system/src/components/OcLogo/OcLogo.vue
Refactor oc-logo Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-logo component using script setup

- packages/design-system/src/components/OcIcon/OcIcon.vue
Refactor oc-icon Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-icon component using script setup

- packages/design-system/src/components/OcList/OcList.vue
Refactor oc-list Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-list component using script setup

- packages/design-system/src/components/OcLoader/OcLoader.vue
Refactor oc-loader Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-loader component using script setup

- packages/design-system/src/components/OcModal/OcModal.spec.ts
- packages/design-system/src/components/OcModal/OcModal.vue
Refactor oc-modal Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-modal component using script setup

- packages/design-system/src/components/OcNotifications/OcNotifications.spec.ts
- packages/design-system/src/components/OcNotifications/OcNotifications.vue
Refactor oc-notifications Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-notifications component using script setup

- packages/design-system/src/components/OcPagination/OcPagination.spec.ts
- packages/design-system/src/components/OcPagination/OcPagination.vue
Refactor oc-pagination Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-pagination component using script setup

- packages/design-system/src/components/OcNotificationMessage/OcNotificationMessage.spec.ts
- packages/design-system/src/components/OcNotificationMessage/OcNotificationMessage.vue
Refactor oc-notification-message Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-notification-message component using script setup

- packages/design-system/src/components/OcProgress/OcProgress.vue
Refactor oc-progress Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-progress component using script setup

- packages/design-system/src/components/OcProgressPie/OcProgressPie.vue
Refactor oc-progress-pie Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-progress-pie component using script setup

- packages/design-system/src/components/OcRecipient/OcRecipient.spec.ts
- packages/design-system/src/components/OcRecipient/OcRecipient.vue
Refactor oc-recipient Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-recipient component using script setup

- package.json
- pnpm-lock.yaml
- tests/e2e/cucumber/environment/index.ts
Updated the playwright version to `1.51.1`
- Fixes: https://github.com/owncloud/web/issues/12436
- CI
> [tests-only][full-ci] update playwright version to 1.51.1

- packages/design-system/src/components/OcSearchBar/OcSearchBar.vue
Refactor oc-searchbar Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-searchbar component using script setup

- packages/design-system/src/components/OcSelect/OcSelect.vue
- packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap
- packages/web-app-admin-settings/tests/unit/components/Users/__snapshots__/GroupSelect.spec.ts.snap
- packages/web-app-admin-settings/tests/unit/components/Users/__snapshots__/LoginModal.spec.ts.snap
Refactor oc-select Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-select component using script setup

- packages/design-system/src/components/OcSpinner/OcSpinner.vue
Refactor oc-spinner Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-spinner component using script setup

- packages/design-system/src/components/OcSwitch/OcSwitch.vue
Refactor oc-switch Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-switch component using script setup

- packages/design-system/src/components/OcTable/OcTable.sort.spec.ts
- packages/design-system/src/components/OcTable/OcTable.spec.ts
- packages/design-system/src/components/OcTable/OcTable.vue
Refactor oc-table Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-table component using script setup

- packages/design-system/src/components/OcTableSimple/OcTableSimple.vue
Refactor oc-table-simple Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-table-simple component using script setup

- packages/design-system/src/components/OcTextarea/OcTextarea.vue
Refactor oc-text-area Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor oc-text-area component using script setup

- packages/design-system/src/components/OcRadio/OcRadio.spec.ts
- packages/design-system/src/components/OcRadio/OcRadio.vue
Refactor oc-radio Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor-oc-radio-to-setup-script

- changelog/unreleased/bugfix-application-language-and-browser-language-do-not-match.md
- packages/web-runtime/src/container/bootstrap.ts
- packages/web-runtime/src/index.ts
We've added a fix to ensure that the application language and browser language match. This fix is particularly important for users who have set their browser language to a language that is not supported by us.
- Fixes https://github.com/owncloud/web/issues/12486
- test case 1:
- test case 2:
- ...
> bugfix: application language and browser language do not match

- changelog/unreleased/enhancement-add-flat-list.md
- packages/web-app-admin-settings/src/components/AppTemplate.vue
- packages/web-app-admin-settings/tests/unit/views/__snapshots__/Spaces.spec.ts.snap
- packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
- packages/web-pkg/src/components/AppBar/AppBar.vue
- packages/web-pkg/src/components/ViewOptions.vue
- packages/web-pkg/src/composables/piniaStores/resources.ts
- packages/web-pkg/src/composables/sort/useSort.ts
- packages/web-pkg/tests/unit/components/AppBar/__snapshots__/AppBar.spec.ts.snap
- packages/web-pkg/tests/unit/components/ViewOptions.spec.ts
- packages/web-runtime/src/container/bootstrap.ts
This feature provides a flat view of files and folders, allowing users to sort them in ascending or descending order without grouping folders separately from files.
- Fixes https://github.com/owncloud/web/issues/12503
- test case 1:
- test case 2:
- ...
> feat: flat list

- .drone.star
Do not use cache server and bucket name from secrets
Part of https://github.com/owncloud/QA/issues/883
> [tests-only][ci] use cache server and bucket variables

- tests/e2e/cucumber/features/smoke/upload.feature
- tests/e2e/support/utils/dragDrop.ts
Added e2e test to upload a folder via drag-n-drop
- Fixes https://github.com/owncloud/web/issues/6051
> [full-ci][tests-only] add test to upload folder via drag-n-drop

- .drone.env
Bump latest ocis commid id.
Part of: https://github.com/owncloud/QA/issues/884
> [tests-only][full-ci] bump lastest ocis commit id

- tests/e2e/cucumber/features/spaces/pagination.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/index.ts
Adding test for flat list (sorting resource alphabetically)
- Related issue: https://github.com/owncloud/web/pull/12509
- locally
> [full-ci][tests-only] adding test for flat list

- tests/e2e/cucumber/features/smoke/tags.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/index.ts
This PR adds E2E test to validate the tags creation with maximum characters. On creating a tag with length >100, it should show a message that says `Tags must not be longer than 100 characters`.
- Part of: https://github.com/owncloud/ocis/issues/11243
> [full-ci][tests-only] add test for tag feature

- tests/e2e/cucumber/features/file-action/copyMove.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/index.ts
This PR adds tests related to duplicating multiple resource at once using batch action
- https://github.com/owncloud/web/issues/9898
- locally
> [full-ci][tests-only]add tests for duplicating multiple resource at once using batch-action

- .drone.star
- tests/drone/notifcation.sh
This PR updated the notify pipeline to send the build notification to matrix.
using bash script because we need dynamic build message depending on build status.
- CI
> [full-ci] Send build notification to matrix

- packages/web-app-activities/src/components/ActivityItem.vue
Refactor activity-item Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor-activity-item to setup script

- .drone.env
Bump latest ocis `master` branch commit id.
Part of: https://github.com/owncloud/QA/issues/886
> [full-ci][tests-only] Bump ocis latest commit id

- .drone.env
Bump latest ocis `stable-7.1` branch commit id.
Part of: https://github.com/owncloud/QA/issues/886
> [full-ci][tests-only] Bump latest commit id ocis stable

- packages/web-app-activities/src/views/App.vue
Refactor app-web-activities Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor app-web-activities to setup script

- packages/web-app-admin-settings/src/components/General/InfoSection.vue
Refactor info-section Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor info-section component to use script setup

- packages/web-app-admin-settings/src/components/General/AppearanceSection.vue
Refactor appearance-section Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor appearance-section component to use script setup

- .drone.env
Bump latest ocis `stable-7.1` branch commit id.
Part of: https://github.com/owncloud/QA/issues/886
> [tests-only][full-ci] Bump latest commit id of ocis

- packages/web-app-admin-settings/src/components/Groups/SideBar/DetailsPanel.vue
- packages/web-app-admin-settings/tests/unit/components/Groups/SideBar/DetailsPanel.spec.ts
Refactor details-panel Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor details-panel component to use script setup

- packages/web-app-admin-settings/src/components/Groups/SideBar/MembersPanel.vue
- packages/web-app-admin-settings/tests/unit/components/Groups/SideBar/MembersPanel.spec.ts
Refactor members-panel Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor members panel to use script setup

- .drone.env
This bump should hopefully resolve flaky tests.
> [full-ci] chore: bump oCIS commit ID

- packages/web-app-admin-settings/src/components/Groups/SideBar/MembersRoleSection.vue
Refactor members-role-section Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor members-role-section component to use script setup

- packages/web-app-admin-settings/src/components/Groups/ContextActions.vue
Refactor context-actions Component to Use <script setup> Syntax.
- test case 1:
- test case 2:
- ...
> chore: refactor context-actions to use script setup

- vitest.config.ts
We are getting a warning that workspace has been deprecated since vitest 3.2 in favor of projects which works exactly the same. This PR replaces workspace with projects.
- test case 1:
- test case 2:
- ...
> chore: replace deprecated workspace with projects

- packages/web-app-files/tests/unit/components/SideBar/Shares/Links/CopyLink.spec.ts
- packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/CopyLink.spec.ts.snap
- packages/web-app-search/tests/unit/portals/SearchBar.spec.ts
- test case 1:
- test case 2:
- ...
> chore: fix vue test warnings

- packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
- packages/web-app-admin-settings/tests/unit/components/Users/SideBar/DetailsPanel.spec.ts
- test case 1:
- test case 2:
- ...
> chore: refactor users-sidebar-details-panel to use script setup

- packages/web-app-admin-settings/src/components/Users/AddToGroupsModal.vue
- packages/web-app-admin-settings/tests/unit/components/Users/AddToGroupsModal.spec.ts
- test case 1:
- test case 2:
- ...
> chore: refactor add-to-groups-modal to use script setup

- packages/web-app-admin-settings/src/components/Users/CreateUserModal.vue
- packages/web-app-admin-settings/tests/unit/components/Users/CreateUserModal.spec.ts
- test case 1:
- test case 2:
- ...
> chore: refactor users-create-user-modal to use script setup

- packages/web-app-admin-settings/src/components/Users/RemoveFromGroupsModal.vue
- packages/web-app-admin-settings/tests/unit/components/Users/RemoveFromGroupsModal.spec.ts
- test case 1:
- test case 2:
- ...
> chore: refactor remove-form-groups-modal to use script setup

- packages/web-app-admin-settings/src/components/Users/GroupSelect.vue
- packages/web-app-admin-settings/tests/unit/components/Users/GroupSelect.spec.ts
- test case 1:
- test case 2:
- ...
> chore: refactor group-select to use script setup

- packages/web-app-admin-settings/src/views/General.vue
- test case 1:
- test case 2:
- ...
> chore: refactor web-admin-views-general to use script setup

- packages/web-app-admin-settings/src/views/Groups.vue
- packages/web-app-admin-settings/tests/unit/views/Groups.spec.ts
We have refactored the admin-web-views-groups component to use script setup
- test case 1:
- test case 2:
- ...
> chore(web-app-admin-settings): [OCISDEV-104] refactor admin-web-views-groups to use script setup

- packages/web-app-app-store/src/components/AppAuthors.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-app-store): [OCISDEV-173] refactor app-authors to use script setup

- packages/web-app-app-store/src/components/AppTags.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-app-store): [OCISDEV-173] refactor app-tags to use script setup

- packages/web-app-app-store/src/views/AppList.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-app-store): [OCISDEV-173] refactor app-list component to use script setup

- packages/web-app-files/src/components/AppBar/Upload/ResourceUpload.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor web-app-files app-bar component to use script setup

- packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
- packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor web-app-files create-and-upload component to use script setup

- packages/web-app-files/src/components/AppBar/SharesNavigation.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor web-app-files shares-navigation component to use script setup

- packages/web-app-files/src/components/FilesList/NotFoundMessage.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor web-app-files not-found-message component to script setup

- .drone.env
Bump latest ocis `master` branch commit id.
Part of: https://github.com/owncloud/QA/issues/890
> [tests-only][full-ci] Bump latest ocis commit id on master branch

- packages/web-app-files/src/components/Modals/DatePickerModal.vue
- packages/web-pkg/src/composables/piniaStores/modals.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor web-app-files date-picker-modal component to use script setup

- packages/web-app-files/src/components/Modals/SetLinkPasswordModal.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor web-app-files set-link-password-modal component to use script setup

- packages/web-app-files/src/components/Search/List.vue
- packages/web-app-files/tests/unit/components/Search/List.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor web-app-files list component to use script setup

- packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
- packages/web-pkg/src/cern/composables/useGroupingSettings.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor share-with-me-section component to use script setup

- packages/web-app-files/src/components/SideBar/Actions/FileActions.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor file-actions component to use script setup

- packages/web-pkg/package.json
- pnpm-lock.yaml
- test case 1:
- test case 2:
- ...
> chore(web-pkg): [OCISDEV-210] update md-editor-v3 to version v5.8.2

- .drone.star
This PR skip clone step in notification pipeline
> [tests-only][full-ci] Chore(ci):skip clone step in notification pipeline

- .drone.star
This PR is backport of master PR https://github.com/owncloud/web/pull/12841
> [tests-only][full-ci] Backport/disable clone on notification

- packages/web-app-files/src/components/SideBar/Details/FileDetailsMultiple.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor file-details-multiple component to use script setup

- packages/web-app-files/src/components/SideBar/Details/TagsSelect.vue
- packages/web-app-files/tests/unit/components/SideBar/TagsSelect.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor details-tags component to use script setup

- packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/ExpirationDatepicker.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor expiration-date-picker component to use script setup

- packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/AutocompleteItem.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor auto-complete-item component to use script setup

- packages/web-app-files/src/components/SideBar/Shares/Collaborators/RoleDropdown.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor role-drop-down component to use script setup

- packages/web-app-files/src/components/SideBar/Shares/Links/ContextMenuItem.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor context-menu-item component to use script setup

- packages/web-app-files/src/components/SideBar/Shares/Links/CopyLink.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor copy-link component to use script setup

- packages/web-app-files/src/components/SideBar/Shares/Links/EditDropdown.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/Links/EditDropdown.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor edit-drop-down component to use script setup

- packages/web-app-files/src/components/SideBar/Shares/ExpirationDateIndicator.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor expiration-date-indicator component to use script setup

- packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor file-links component to use script setup

- packages/web-app-files/src/components/SideBar/NoSelection.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor no-selection component to use script setup

- packages/web-app-files/src/components/SideBar/ActivitiesPanel.vue
- packages/web-app-files/tests/unit/components/SideBar/ActivitiesPanel.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor activities-panel component to use script setup

- packages/web-app-files/src/components/Spaces/WhitespaceContextMenu.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor white-space-context-menu to use script setup

- packages/web-app-admin-settings/package.json
- packages/web-app-files/package.json
- packages/web-app-ocm/package.json
- packages/web-client/package.json
- packages/web-client/src/helpers/share/functions.ts
- packages/web-pkg/package.json
- packages/web-pkg/src/components/FilesList/ResourceListItem.vue
- packages/web-pkg/src/composables/folderLink/useFolderLink.ts
- packages/web-runtime/package.json
- packages/web-test-helpers/package.json
- pnpm-lock.yaml
- test case 1:
- test case 2:
- ...
> Chore/backport to stable 11.0 axios v11 and parent folder bugfix

- packages/web-app-files/src/components/FilesViewWrapper.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor files-view-wrapper component to use script setup

- packages/web-app-files/src/views/shares/SharedViaLink.vue
- packages/web-app-files/tests/unit/views/shares/SharedViaLink.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor shared-via-link component to use script

- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/tests/unit/views/spaces/Projects.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-files): [OCISDEV-179] refactor projects component to usse script setup

- packages/web-app-preview/src/components/Sources/MediaVideo.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-preview): [OCISDEV-243] refactor media-video component to use script setup

- packages/web-app-preview/src/components/MediaControls.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-preview): [OCISDEV-243] refactor media-controls component to use script setup

- packages/web-app-preview/src/App.vue
- packages/web-app-preview/src/index.ts
- packages/web-app-preview/tests/unit/app.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-preview): [OCISDEV-243] refactor app component to use script setup

- packages/web-runtime/src/pages/account.vue
- Fixes https://kiteworks.atlassian.net/browse/OCISDEV-240
- test case 1:
- test case 2:
- ...
> bugfix(web-runtime): [OCISDEV-240] fixes vue missing prop label warning

- .drone.star
- Makefile
- docs/Makefile
- docs/building.md
Refernces: https://github.com/owncloud/ocis/pull/11585 ([docs-only] Fix docs build process)
Align the docs building process to ocis
> Align docs building process to ocis

- packages/web-app-search/src/views/List.vue
- packages/web-app-search/tests/unit/views/List.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-search): [OCISDEV-246] refactor list component to use script setup

- packages/web-app-search/src/portals/SearchBar.vue
- packages/web-app-search/tests/unit/portals/SearchBar.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-search): [OCISDEV-246] refactor search-bar component to use script setup

- changelog/unreleased/bugfix-deactivated-spaces-clips-german-translated-word.md
- packages/design-system/src/components/OcFilterChip/OcFilterChip.vue
- test case 1:
- test case 2:
- ...
> bugfix(design-systems): [OCISDEV-194] fixes clipped german translation of deactivated spaces

- packages/web-pkg/src/components/ContextActions/ContextMenuQuickAction.vue
- packages/web-pkg/src/helpers/contextMenuDropdown.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-pkg): [OCISDEV-256] refactor context-menu-quick-action component to use script setup

- packages/web-pkg/src/components/FilesList/ResourceGhostElement.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-pkg): [OCISDEV-256] refactor resource-ghost-element component to use script setup

- packages/web-pkg/src/components/FilesList/ResourceIcon.vue
- packages/web-pkg/tests/unit/components/FilesList/ResourceIcon.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-pkg): [OCISDEV-256] refactor resource-icon component to use script setup

- packages/web-pkg/src/components/FilesList/ResourceLink.vue
- packages/web-pkg/src/components/FilesList/ResourceListItem.vue
- packages/web-pkg/src/components/FilesList/ResourceTile.vue
- packages/web-pkg/tests/unit/components/FilesList/ResourceListItem.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-pkg): [OCISDEV-256] refactor resource-link component to use script setup

- packages/web-pkg/src/components/FilesList/ResourceStatusIndicators.vue
- test case 1:
- test case 2:
- ...
> chore(web-app-pkg): [OCISDEV-256] refactor resource-status-indicators to use script setup

- packages/web-pkg/src/components/FilesList/ResourceTile.vue
- packages/web-pkg/src/components/FilesList/ResourceTiles.vue
- packages/web-pkg/tests/unit/components/FilesList/ResourceTile.spec.ts
- packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTile.spec.ts.snap
- test case 1:
- test case 2:
- ...
> chore(web-app-pkg): [OCISDEV-256] refactor resource-tile component to use script setup

- packages/web-app-password-protected-folders/src/composables/useApplicationFileExtensions.ts
- packages/web-client/package.json
- packages/web-client/src/constants.ts
- packages/web-client/src/helpers/resource/functions.ts
- packages/web-client/src/index.ts
- packages/web-client/tests/unit/helpers/resource/functions.spec.ts
- packages/web-pkg/src/components/FilesList/ResourceListItem.vue
- packages/web-pkg/src/components/SideBar/Files/FileInfo.vue
- packages/web-pkg/src/composables/actions/files/useFileActionsCreateSpaceFromResource.ts
- packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
- packages/web-pkg/src/constants.ts
- packages/web-pkg/tests/unit/components/FilesList/ResourceListItem.spec.ts
- pnpm-lock.yaml
Move hidden extensions constants into web-client to prevent circular dependencies.
Prevent circular deps.
> chore: prevent circular deps

- packages/web-app-password-protected-folders/src/composables/useApplicationFileExtensions.ts
- packages/web-client/package.json
- packages/web-client/src/constants.ts
- packages/web-client/src/helpers/resource/functions.ts
- packages/web-client/src/index.ts
- packages/web-client/tests/unit/helpers/resource/functions.spec.ts
- packages/web-pkg/src/components/FilesList/ResourceListItem.vue
- packages/web-pkg/src/components/SideBar/Files/FileInfo.vue
- packages/web-pkg/src/composables/actions/files/useFileActionsCreateSpaceFromResource.ts
- packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
- packages/web-pkg/src/constants.ts
- packages/web-pkg/tests/unit/components/FilesList/ResourceListItem.spec.ts
- packages/web-runtime/tests/unit/components/UploadBar.spec.ts
- packages/web-runtime/tests/unit/components/UploadInfo.spec.ts
- pnpm-lock.yaml
This PR backports a circular dependencies fix.
> chore: backport prevent circular deps

- packages/web-pkg/src/components/FilesList/ResourceTiles.vue
- packages/web-pkg/src/composables/filesList/useResourceRouteResolver.ts
- packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-pkg): [OCISDEV-256] refactor resource-tiles component to use script setup

- packages/web-pkg/src/components/Modals/FilePickerModal.vue
- packages/web-pkg/tests/unit/components/Modals/FilePickerModal.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-pkg): [OCISDEV-256] refactor file-picker-modal component to use script setup

- packages/web-pkg/src/components/Modals/ResourceConflictModal.vue
- packages/web-pkg/tests/unit/components/Modals/ResourceConflictModal.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-pkg): [OCISDEV-256] refactor resource-conflict-modal component to use script setup

- packages/web-pkg/src/components/FilesList/ResourceListItem.vue
- packages/web-pkg/src/components/Search/ResourcePreview.vue
- packages/web-pkg/tests/unit/components/Search/ResourcePreview.spec.ts
- packages/web-pkg/tests/unit/components/Search/__snapshots__/ResourcePreview.spec.ts.snap
- test case 1:
- test case 2:
- ...
> chore(web-pkg): [OCISDEV-256] refactor resource-preview component to use script setup

- packages/web-pkg/src/components/SideBar/Files/FileInfo.vue
- test case 1:
- test case 2:
- ...
> chore(web-pkg): [OCISDEV-256] refactor file-info component to use script setup

- packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetailsMultiple.vue
- test case 1:
- test case 2:
- ...
> chore(web-pkg): [OCISDEV-256] refactor space-details-multiple component to use script setup

- packages/web-pkg/src/components/SideBar/Spaces/SpaceInfo.vue
- test case 1:
- test case 2:
- ...
> chore(web-pkg): [OCISDEV-256] refactor space-info component to use script setup

- packages/web-pkg/src/components/SideBar/SideBar.vue
- test case 1:
- test case 2:
- ...
> chore(web-pkg): [OCISDEV-256] refactor side-bar component to use script setup

- packages/design-system/src/helpers/types.ts
- packages/web-pkg/src/components/Filters/DateFilter.vue
- packages/web-pkg/tests/unit/components/Filters/DateFilter.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-app-pkg): [OCISDEV-256] refactor date-filter component to use script setup

- packages/web-pkg/src/components/CustomComponentTarget.vue
- test case 1:
- test case 2:
- ...
> chore(web-pkg): [OCISDEV-256] refactor custom-component-target component to use script setup

- packages/web-pkg/src/components/ItemFilter.vue
- packages/web-pkg/tests/unit/components/ItemFilter.spec.ts
- test case 1:
- test case 2:
- ...
> chore(web-pkg): [OCISDEV-256] refactor item-filter component to use script setup

- packages/web-pkg/src/components/ItemFilterToggle.vue
- packages/web-pkg/tests/unit/components/ItemFilterToggle.spec.ts
- refactor item-filter-toggle component to use script setup
- fix unit test linting issue
- test case 1:
- test case 2:
- ...
> chore(web-pkg): [OCISDEV-256] refactor item-filter-toggle component to use script setup

- package.json
- packages/design-system/package.json
- packages/eslint-config/package.json
- packages/extension-sdk/package.json
- packages/web-client/package.json
- packages/web-pkg/package.json
- packages/web-test-helpers/package.json
- sonar-project.properties
Bump version to also include the latest version in master.
> chore: bump version to 12.1.0
